### ISSUE TITLE
Integrate New Promotion Screen by Default

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#10]
[This mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1124609091&searchtext=new+promotion+screen+by+default) should make for a more consistent and nicer user experience. Plus the new promotion screen already supports 3 abilities per rank! Just need to sort out training center integration first.

**Comment by pledbrook** [comment]
As #115 points out, the mod doesn't support officer abilities with LW2 at the moment.

**Comment by jmartinez989** [comment]
One thing to note on this is that the new promotion screen only displays up to the gunnery sergeant rank. You would have to extend the UI for it to show the Master Sergeant rank as well.
