### ISSUE TITLE
Avatar progress doesn't seem to be progressing properly

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#100]
I've had reports of the doom clock acting oddly, for example with every added pip being removed again. This removes the doom clock from being a consideration at all for campaigns.

**Comment by jmartinez989** [comment]
So I found that the Avatar project clock is actually going up like it is supposed to but you only see that if you actually uncover the facilities that have been adding to the avatar project. If they are not revealed then the clock will add a pip then remove one. Once you uncover that facility you will see all of the pips correctly that it added.

**Comment by pledbrook** [comment]
That's weird. Wonder what's going on. I need a pre-facility-reveal save file if anyone has one lying around.

**Comment by jmartinez989** [comment]
Look at #139 That has a save file for another issue with alien facilities. That save I have revealed a facility.

**Comment by pledbrook** [comment]
Right. I was hoping for one just before the facility is revealed :smile: A tough ask, I know. I can probably work out what's going on from other saves, like that one and HQ assaults.

**Comment by jmartinez989** [comment]
Have a solution implemented for this but part of it requires a CHL modification so will need to push that change to the highlander repo as well.
