### ISSUE TITLE
Squad stuck with no current mission

### ISSUE THREAD

**Issue by Meuhoua** [long-war-2/lwotc#1000]
Hello, i got a strange bug on my new playtrough : a squad is engaged on a mission (infiltration up to 200%), but the related mission has vanished from geoscape so i can't start it (or even abord it).
Is there a way to unlock the situtation with the console ?

**Comment by pledbrook** [comment]
Not that I know of. I haven't come across this or heard it being reported before, so it's either very rare, or has something to do with other mods you have installed. I have no idea how to rectify it. If I had a save to work from, I might be able to diagnose it, but I have a backlog of things to work on.

**Comment by fedupwithbioware** [comment]
> Hello, i got a strange bug on my new playtrough : a squad is engaged on a mission (infiltration up to 200%), but the related mission has vanished from geoscape so i can't start it (or even abord it).
> Is there a way to unlock the situtation with the console ?

I am not a mod creater but I did find a band aid solution. I found that I was missing some great troops and then my heroes. I found this colsole command and it works. Go to your squadname list and type the squadname you want back and they return.

I managed to get to plasma weapons and was resigned to losing these great teams when I found this. I got back people still using mag weapons and lasers.

Also, not sure the affect it would have on squad the you actually can use or that isn't missing with the same name. So wait until you have all your missions that you can have, back. and don't forget capitals,

LWForceSquadPostMissionCleanup "squadname"

**Comment by GrocerOfDespair** [comment]
I get this when I get a mission from a Covert Action and assign a squad to infiltrate.  When that mission pops up as launch or abort I can't assign the squad that I had already assigned, and the squad that was already assigned ends up in infiltration limbo.  

The above console command saved my campaign, so thanks fedupwithbioware!

**Comment by GrocerOfDespair** [comment]
I believe the issue is a problem with the Covert Action Missions mod.

**Comment by copyrite** [comment]
This seems to be more or less resolved.
