### ISSUE TITLE
Beta3 update/RespecAllSoldiers broke my Psi Ops

### ISSUE THREAD

**Issue by VektorT** [long-war-2/lwotc#1002]
Not sure if the Beta 3 update or the RespecAllSoldiers console command I used like the README suggest did it, but my Psi Ops are broke. They have no abilities at all, even the ranked ones, everything locked.

The work around I found is to console command change them back to rookie and retrain them in the Psi Lab, but obsiously you lose all their ranks and time.

**Comment by pledbrook** [comment]
I'm going to exclude Psi Ops from `RespecAllSoldiers`. Sorry, that was an oversight. I forgot about the effect it would have on them.

**Comment by VektorT** [comment]
No prob. I ended editing the files so Psi training took 0 days, made my Psi ops rookies agains and send them on some missions together where I cheated so they could get some kills fast and level up back as soon as possible to where they was. XD

**Comment by Grobobobo** [comment]
Already fixed.
