### ISSUE TITLE
Pistol slot bug for non-trooper classes

### ISSUE THREAD

**Issue by Morflight** [long-war-2/lwotc#1006]
Impacted classes : Reaper, Skirmisher, Psi Ops

Bug : Something forces the said classes to equip +1 pistol. It results in several pistol overwatch abilities in game as well as down to a -10 mobility malus at the start of the mission. On top of that, it is impossible to remove or give a better pistol to the said classes (which means a permanent -1 mobility for the class). The first equipped pistol is unusable.

Patchwork fix : on the character loadout, click on the cross to remove your pistol. It should stay in the slot, but your mobility should gradually come back to a reasonnable amount. Alternatively, unequipping all (barracks, squad, etc.) should work as well.

Cause : unknown for now. It realized it after I upgraded some of my armor to mid-tier (plate). But I'm unable to willingly reproduce the bug.

Modlist : Default and recommended. No cosmetic.

I mentionned this issue in another ticket as they seem linked somehow. Link below.

**Comment by Grobobobo** [comment]
Was fixed a while ago.
