### ISSUE TITLE
Apotheosis (Templar Skill) isnt working properly

### ISSUE THREAD

**Issue by Naitsir91** [long-war-2/lwotc#1007]
Hey, thx so much for the mod :)

To the matter at hand: the Apotheosis Skill mostly doesnt seem to do anything except consuming my focus. Im not sure wether there is supposed to be an audiovisual cue or smth of the likes when I press it?
When it activates I do get a little buff Icon next to the Class Icon, and the extended stat screen suggest that my dodge increases by 100. However, this increase only seems to last for the players turn (making this useless except for maybe doding overwatch shots? But 3 focus would be a lot to pay for that). Also the Rend damage isnt increased at all and neither is my mobility. I have tried it with and without Reaper activated. It doesnt seem to work in either case. 
Best regards

**Comment by pledbrook** [comment]
> However, this increase only seems to last for the players turn (making this useless except for maybe doding overwatch shots?
It should last into the enemy's turn following activation, which is what it did in testing.

> Also the Rend damage isnt increased at all and neither is my mobility

It was working in testing. I'll have to take another look.

**Comment by Grobobobo** [comment]
Fixed a while ago.
