### ISSUE TITLE
Too few enemies on supply raid

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#101]
Only 8 on the supply raid in the attached save file. It was supposed to be Very Light.

[save_8-enemy supply raid.zip](https://github.com/long-war-2/lwotc/files/3086369/save_8-enemy.supply.raid.zip)

**Comment by twobob** [comment]
possibly #11 as well
We killed everything and it didn't end 
https://clips.twitch.tv/ProudGoodKiwiTheRinger

It had like 100 enemies by the end.  
So many the game's tick was too slow to properly draw the enemy readouts ;)
https://clips.twitch.tv/UnsightlyDarkCodOneHand  

Hope it helps.

**Comment by BlackRose39** [comment]
#636

**Comment by pledbrook** [comment]
This is so old now and there haven't been any recent reports of issues with this, so closing.
