### ISSUE TITLE
Mac Install problem

### ISSUE THREAD

**Issue by ThomGoodchild** [long-war-2/lwotc#1011]
Hi all,

I am having trouble with installing the mod on my macbook - I have followed the steps laid out in the guide, including verifying files and flushing the cache, and have gotten to the point where my mod launcher shows all of the correct starting mods (including the updated Highlander and the LWOTC mod) as 'enabled' at launch. However I still get a New Game button instead of a Long War button, and when I launch into gatecrasher I have a four-man destroy monument mission. Workshop mods (the four recommended in the install guide, robojumper etc.) are working as advertised. 

The troubleshooting mentions that there are some 'additional steps' that can be taken and I wonder if anyone here could help out? Big thanks to the devs - I'm really looking forward to having a chance to play this mod.

**Comment by pledbrook** [comment]
Could you please post the content of the file *~/Library/Application Support/Feral Interactive/XCOM\ 2\ WotC/VFS/Local/my games/XCOM2 War of the Chosen/XComGame/Config/XComModOptions.ini*?

**Comment by ThomGoodchild** [comment]
Hi Paledbrook! It's Louis from Xwynn's discord, glad to see this mod is still active!

.ini below: 

[IniVersion]
0=1589627952.000000

[Engine.XComModOptions]
ActiveMods=BetterSecondWaveSupport
ActiveMods=LongWarOfTheChosen
ActiveMods=ModConfigMenu
ActiveMods=WOTCRevertOverwatchRules
ActiveMods=X2WOTCCommunityHighlander
ActiveMods=robojumperSquadSelect_WotC

**Comment by Grobobobo** [comment]
No longer relevant.
