### ISSUE TITLE
Failing a "Recruit Engineer" CA still gives "New Staff acquired" popup

### ISSUE THREAD

**Issue by Bigglett** [long-war-2/lwotc#1018]
Issue: Recruit Engineer cover action mission - when it fails you still get the "New Staff Acquired" popup, but the engineer is not recruited. The popup should not be there. 

Could also be applicable to Scientists/Recruits, but not confirmed.

**Comment by Bigglett** [comment]
![image](https://user-images.githubusercontent.com/65498489/82259240-8921f880-995b-11ea-8536-a9d2d7536b7a.png)

**Comment by Bigglett** [comment]
![image](https://user-images.githubusercontent.com/65498489/82259342-b1115c00-995b-11ea-8074-f549d4a59558.png)

**Comment by Bigglett** [comment]
[save_Recruit Engineer-CA-Failure.zip](https://github.com/long-war-2/lwotc/files/4646695/save_Recruit.Engineer-CA-Failure.zip)

**Comment by Grobobobo** [comment]
Already fixed.
