### ISSUE TITLE
Chosen Items not showing up for assignment.

### ISSUE THREAD

**Issue by fedupwithbioware** [long-war-2/lwotc#1021]
I killed my Chosen and the Arashi was supposed to be in inventory. Nothing.
Killed my chosen and received some kind of armor and a weapon but its still not in my inventory.

Anyone have this?

What is the best way to up load mod list and save game?

**Comment by McTrevor79** [comment]
You need to resesrch it first

**Comment by fedupwithbioware** [comment]
I did research the Stronghold loot, that is how I got the named loot.

**Comment by Grobobobo** [comment]
Unable to reproduce.
