### ISSUE TITLE
The lost

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1025]
Are still a boon xcom. I assume the 70-30 split in targeting is intended to help, but that is treating the symptom rather than the disease. The real problem is where they spawn. They seem to most often spawn behind advent. Thus, while they prefer xcom, the shear number of juicy advent targets between them and xcom means they get distracted and wail on advent. I am playing legendary with grim horizon and got the lost world dark event. If the lost would spawn somewhere equidistant to xcom and advent, I think the targeting preference could go back down to 60-40. As it is, the lost are wasting all of advents attacks and the lost do a lot of my work for me.

Alternatively, if advent would pay a little less attention to the lost, that would help as well. The lost might be beating on them, but they generally have lots of hp and don't care that much.

**Comment by Grobobobo** [comment]
Already made changes regarding this topic.
