### ISSUE TITLE
Game crashes upon launching lwotc beta3

### ISSUE THREAD

**Issue by Leskit** [long-war-2/lwotc#1027]
Hello,

I took a few years off xcom2, but i'm back now and I'm having a problem where the game crashes during a mission, and after that, the game crashes continually either before reaching the menu screen, or upon reaching the menu screen. 1.0 Beta 3 is my installed version of lwotc. Any help would be greatly appreciated!

First recurring crash was around 6-7 hours of gameplay. Second recurring crash was around 11 hours of gameplay.
Attempted troubleshooting, 1st time:
-cleared "config" folder
-verified game files so many times
-copied save game files to backup folder, replacing only the current save
-removed mods one by one until only the required mods are used.
-unsubscribed from all non-required mods
-disabled v-sync, bloom, and set ambient occlusion to Tile-AO, rebooted computer.

Game would finally run and launch after completely uninstalling xcom 2, reinstalling, and reinstalling  LWOTC. I started a new campaign using only the required mods, played for a few hours. Installed a few more mods (cosmetics/outfits, and the "wotc peek from concealment UI", "wotc gotcha again", "wotc peek from concealment" mods).
Played another few hours. Installed a few more mods ("free the hood-wotc", "wotc new target icons", "Wotc flawless" "evac all-wotc",". It ran fine for 5-6 hours, then crashed during a mission and I'm back in the crash loop. 
Mods I _have not_ reinstalled on the second run that I remember: "wotc: color coded bonds", "stop wasting my time - wotc", "more starting soldiers (wotc)", "missing packages fix+resource", "missing packages fix - parcels and maps edition" "wotc overflow ability points" "wotc melee weapon breakthrough" "recruit multiple heroes from all" "additional vest types" "wotc iridar's defensive items overhaul" and its required mods.

Let me know what files you need and I'll upload them asap! Downloading the whole xcom 2 takes hours so I'd like to avoid a complete uninstall-reinstall cycle.

**Comment by Leskit** [comment]
Update: After deleting the config folder contents and verifying the game, it's back working again. Don't know what caused the problem in the first place though. I'll update if it goes into a crash loop again.

**Comment by Leskit** [comment]
After the update to the xcom launcher on steam today, I'm back to crashes, but this time without crash logs screen sending info to the developers. I deleted the config folder items, verified the files, and the game ran for about 20 minutes. But now the game just closes at different times. It's failed to get to the main menu a dozen times, and crashed upon loading a save a few times, and crashed once just after loading a save. It also reset all the mods. Any help would be greatly appreciated.

**Comment by Grobobobo** [comment]
Unable to reproduce.
