### ISSUE TITLE
Required mods activated, game tells me they are not

### ISSUE THREAD

**Issue by Mystikvm** [long-war-2/lwotc#1028]
I have started LWOTC2 with only the required mods. It tells me that 3 of them are not activated and that I should activate them. They are activated, however. 

I have cleared the config folder, to no avail. I've also unsubscribed and resubscribed to the mods. Is there something I'm missing?

**Comment by SwissArmyKnlfe** [comment]
Check and make sure your load orders are correct. With LWOTC and it's dependencies up near the top.
If you're not already definitely grab and use the Alternative Launcher rather than the one that comes with the base game.

https://github.com/X2CommunityCore/xcom2-launcher/releases

**Comment by Mystikvm** [comment]
That seems to have fixed it. Thanks!
