### ISSUE TITLE
Crash on HQ assault 

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#103]
As mentioned in discord, I am having a reproducible crash to desktop when loading into an very heavy HQ assault. Attached is the log file and the save

[HQ assault crash.zip](https://github.com/long-war-2/lwotc/files/3086811/HQ.assault.crash.zip)

**Comment by pledbrook** [comment]
Interesting. It actually crashes during the "soldiers entering the map" cinematic. The Mac crash information may have a clue as to where this is happening. I saw `AX2GameRulesetVisibilityManager::execGetAllViewersOfTarget(FFrame&, void*)` in the callstack of the crashed thread.

@tracktwo Does any of this sound familiar to you? I've not encountered a mission crashing at this exact point before. And the plot has definitely loaded fine in Skirmish mode.

**Comment by tracktwo** [comment]
Unfortunately no, I don't think we had any HQ specific crashes. Could it be due to a pod activating right at mission start perhaps? I don't know why `GetAllViewersOfTarget` would be involved at that stage otherwise, maybe searching for uses of that in the xcomgame sources and seeing if you can catch a breakpoint at a caller before it enters native to see if something looks wrong.

**Comment by ansabalirai** [comment]
So I ended up having to cancel and reinfiltrate the HQ and it worked fine. I am guessing maybe it was an issue with the drop point or map assets? Anyways, it is up to you whether to keep it open or not (since it is not technically resolved :) )

**Comment by pledbrook** [comment]
Yes, will keep open. It's a serious bug. As tracktwo said, could be a pod activation or a spawn problem. Something's not working as it should, regardless.

**Comment by pledbrook** [comment]
This appears to be crashing in `X2TacticalVisibilityHelpers.GetFlankersOfTarget()` when calling `GetAllViewersOfTarget()`.

**Comment by pledbrook** [comment]
Sorry, this won't make it into alpha 3. Will take another look for alpha 4. It's just not an easy issue to diagnose.

**Comment by pledbrook** [comment]
We think this was because one or more of your squad was previously on a mission as a haven adviser. That bug has been fixed with [this commit](https://github.com/long-war-2/lwotc/commit/a1335233a41618a53bbe53531b1eebdf6186e7ce).
