### ISSUE TITLE
Installation directory on Windows 10

### ISSUE THREAD

**Issue by felis** [long-war-2/lwotc#1030]
After some time playing lwotc stopped working. I'm trying to restore it with the latest beta. I'm having difficulty following the installation instructions. Specifically, on my win10 machine the `XCom2-WarOfTheChosen` directory doesn't exist. When I install under `Steam/steamapps/common/XCOM 2` hierarchy I see `NEW GAME` instead of `LONG WAR 2` and I can only see workshop mods, same if I create `XCom2-WarOfTheChosen` hierarchy manually. I started a new WOTC game just to check if it's present and it runs fine.

What am I doing wrong?

**Comment by Grobobobo** [comment]
You'd need to verify in-game files if the directory isn't there. it should be Steam/steamapps/common/XCOM/XCom2-WarOfTheChosen .
