### ISSUE TITLE
Beta 3.1 (Linux) - Impossible Turn Timer in Mission

### ISSUE THREAD

**Issue by Taijian** [long-war-2/lwotc#1031]
[save_AUTOSAVE- Campaign 11, Mission 4, Turn 1.zip](https://github.com/long-war-2/lwotc/files/4672663/save_AUTOSAVE-.Campaign.11.Mission.4.Turn.1.zip)
Hi there!

I just started my first game of LWotC and I must say that so far, I am pretty impressed! Looks very good and is fun to play.
However, I seem to have run into somewhat of a glitch - my third mission is one to plant X4 on an active psyonic relay thingy. So far, so good. Unfortunately, the Turn Timer starts at 3 (three!) turns to fail the mission, when a quick look at the map tells me that my people might not make it in time even if they did nothing but yellow move (dash). So... can I do anything about this, or is this just broken?

Save file is attached.
[save_AUTOSAVE- Campaign 11, Mission 4, Turn 1.zip](https://github.com/long-war-2/lwotc/files/4672663/save_AUTOSAVE-.Campaign.11.Mission.4.Turn.1.zip)

**Comment by zyxpsilon** [comment]
Don't worry.. you'll have plenty of time, if you play "wisely".
These special maps offer multiple little target-Pods that you must destroy to ADD an extra timer/turn for each.
Reaching the objective still is a priority though. ;)

**Comment by Taijian** [comment]
Ah, so it's kinda like the 'bomb disposal' missions from XCOM 1? Then that makes a lot more sense!

Sometimes it is difficult knowing what is a bug and what a feature, because of the documentation being to spotty, due to the beta state of lwotc...
