### ISSUE TITLE
No music in between battles

### ISSUE THREAD

**Issue by Bluemethod** [long-war-2/lwotc#1033]
I have the latest version installed but this has been happening since 3.0. There is no music playing before and between battles, the idle music if you will, just dead silence. Does anyone know of this issue? Thank you.

**Comment by RogueSeeker24** [comment]
It seems to vary from map to map, or mission to mission. I haven't been playing long enough to find a pattern other than more denser city maps with jailbreak missions, but it's also happened on VIP Extraction and now the Broadcast Tower mission.

**Comment by Grobobobo** [comment]
Not a LWOTC bug.
