### ISSUE TITLE
newly trained psi warriors

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1036]
So, when I train a rookie to be a psi soldier in the psi lab, they come out with 3 abilities, soul fire, mind merge, and insanity. However, the promotion screen shows mind merge, mind merge, and insanity. Soul fire is not in the tree. I was confused at first, but now I think it is a bug. Soul fire should be one of the abilities there or they have soul fire when they shouldn't. soul fire seems really strong for an initiate and the damage appears to be independent of psi-offense...which seems strange. Screenshot is attached
![20200524155229_1](https://user-images.githubusercontent.com/38798278/82763727-bb0de180-9dd7-11ea-9f28-b7ae843addaf.jpg)

**Comment by Grobobobo** [comment]
Not a bug.
