### ISSUE TITLE
multiplying plasma grenades and nano-medkits

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1037]
So, I completed the proving ground projects for nano-medkits and plama grenades, which gave me one, but now, many missions later, I have 7 plasma grenades and 4 nano-medkits. Here is the problem. I never built any of them besides the one from the proving grounds. It is not clear to me how I acquired them. I don't think they can be loot or artifacts recovered from missions. I suspect it has something to do with unequipping the barracks.  I tend to gear up my haven advisors reasonably well so they can complete the rendevous missions. It may be that unequipping the barracks takes the items from folks that are  infiltrating or haven advisors and puts them in the inventory, but then they still have them on the mission. When they get back from the mission or haven duty, now I have the one I gave them when they left as well as the one taken from them when I unequipped the barracks.

**Comment by bobjjones** [comment]
FYI, I am up to 13 plasma grenades and 7 nano-medkits. I still haven't built one besides the one I got when the proving ground project was completed.

**Comment by bobjjones** [comment]
I gotta say. This one is really bugging me. I can't figure out when it is that the plasma grenades and medkits get duplicated. Sometimes I unequip my barracks to free up items and a bunch more of them show up.

Has nobody else had this issue?

**Comment by pledbrook** [comment]
Fixed with above commit.
