### ISSUE TITLE
Units appearing in wrong places

### ISSUE THREAD

**Issue by just-dont** [long-war-2/lwotc#1038]
I'm fairly sure it's related to LWotC, as I never experienced anything of sorts with vanilla WotC.

There's two cases:
1) Non-flying units may appear way off their normal position upon loading a tactical save. They're actually in their correct positions, just their model is displayed in a completely different place (sometimes quite far). It fixes itself when the unit move (on the next enemy turn). Essentially, it's a visual glitch, although an annoying one. I never saw it happen during the normal play, only upon loading a save.
2) It's opposite with flying units: sometimes flying units (e.g. drones, archons) after their movement end up in "desynchronized" state: their model is displayed in one tile but their actual position is in a different tile. It fixes itself if you save and then load the game, but usually you find out it was the case when you e.g. grenade a drone and it takes no damage (because it's actually in a different tile). This one affects gameplay rather badly.

**Comment by bobjjones** [comment]
I have experienced this too.

**Comment by Grobobobo** [comment]
Unable to reproduce.
