### ISSUE TITLE
Squad deploys as concealed for supply raid below 100% infiltrated 

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#104]
One of the ways farming underinfiltrated supply raids was nerfed was through having no squad concealment when below 100% infiltrated. This does not seem to be the case in alpha 2 and so should be fixed.
No save game handy but can be easily reproduced.

**Comment by pledbrook** [comment]
This is handled by `XCGS_LWListenerManager.CheckForConcealOverride()`, which relies on an event that needs adding to the highlander.

**Comment by pledbrook** [comment]
Actually, `XCGS_BattleData` has a `bForceNoSquadConcealment` property that we could use. Much simpler!
