### ISSUE TITLE
Cant build squad but have all the facilitys

### ISSUE THREAD

**Issue by scounter** [long-war-2/lwotc#1043]
Hi there i am new here.
I have searched the net via google and many many forums but i cant find a solution for my issue.
After starting a new campaign and build all the facilitys i needed, i cant build a squad. The squad build button doesnt exist in the armory screen and if i start a mission and press the "create squad" button it does nothing. And the only squadbutton in the beginning of a Mission shows always "squadname" but if i press it, it also dont works. - pls help...

And sorry, my english is not so good :/

Best regards
scounter
![20200526092846_1](https://user-images.githubusercontent.com/65943112/82874892-f3780180-9f36-11ea-9f81-3ad6a8e5b82d.jpg)
![20200526092841_1](https://user-images.githubusercontent.com/65943112/82874920-fbd03c80-9f36-11ea-9f35-36cb08d662de.jpg)
![20200526092834_1](https://user-images.githubusercontent.com/65943112/82874942-0559a480-9f37-11ea-9382-a5e0e2a0cdb4.jpg)

**Comment by Grobobobo** [comment]
Lack of Robojumper's squad select indicates an installation issue.
