### ISSUE TITLE
Not responding when launching game with lwotc

### ISSUE THREAD

**Issue by makongas** [long-war-2/lwotc#1045]
I installed all 4 required mods and both lwotc folders to xcomgame/mods. After deleting the config and launching the game there is no button for long war. When i try to launch the game for a second time I only get a windowed white screen and the game is not responding. What could be the problem?

**Comment by bobjjones** [comment]
They will need more info than that to help with your problem. Maybe show screen shots of where all the mods are to demonstrate they are in the right place. Show them which config files you deleted. How did you "install" the required mods? Did you subscribe to them in steam? Are you using AML?

**Comment by makongas** [comment]
The mods are in steamapps/common/xcom2/xcomgame/mods. I deleted config files in the documents/my games folder. I subscribed to the required mods on steam.  And I am using AML, the mods are showing up correctly in the launcher, the game just does not launch.

**Comment by makongas** [comment]
![image](https://user-images.githubusercontent.com/65981698/82997579-360d0d00-a00f-11ea-9583-ed96ce2f4297.png)
This is the screen I get when launching second time

**Comment by nickkeane** [comment]
I'm pretty sure the lwotc and custom highlander go in their own specific folder, not the same mods folder as standard mods. Triple check the paths in the wiki.

I have LongWarOfTheChosen and X2WOTCCommunityHighlander in steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods. The other 4 required mods I think go in a different place (I subscribed via workshop so idk where they are specifically).

**Comment by copyrite** [comment]
Closing as pre-Workshop installation issue.
