### ISSUE TITLE
Various strange issues after the launcher update

### ISSUE THREAD

**Issue by tn67078** [long-war-2/lwotc#1048]
I ran into the same issues as everyone else when I tried to launch LWotC after the launcher update. I installed the Alternative Mod Launcher, and I can now see and select all of my mods (LWotC and the Highlander + a relatively small number of cosmetic and QoL mods). However, I immediately 
noticed all sorts of weird issues in-game when I tried loading two of my previous saves. The skill icons for different types of grenades are black when I load a tactical save, and the strategy layer has missing icons and buttons. I don't have menu buttons for resistance management or squad management, the status column of soldiers currently infiltrating shows '0', and the missions I'm infiltrating have a star icon on the world map and can't be interacted with (the attached screenshot shows the world map). The new game button in the main menu shows LWotC and the Highlander is active, so the mods are loaded. Is it just me, or has the update/AML broken anyone else's saves?  Does the load order in the AML matter? I have the Highlander and LWotC as 1 and 2, and everything else is in the default order. I can upload save files if it helps, but I thought I'd ask first if anyone else is having similar issues. 

![LWotC missing icons](https://user-images.githubusercontent.com/53411897/82967645-464bca80-9fc4-11ea-984c-de7b58dbea55.png)

**Comment by bobjjones** [comment]
I'm not associated with the mod development team, but I would suggest deleting the config files you were told to delete when you first installed the mod and try regenerating them.

I had somewhat similar issues when my game kept crashing.

I would also try starting a new game to see if the issue is with the save file or the game itself both before and after regenerating the inis.

**Comment by tn67078** [comment]
Thank you for the suggestions. I deleted the config files, but my game was then crashing on start-up with LWotC and the Highlander enabled. The game seems to be very unstable at the moment. I decided to start a new vanilla campaign since my other mods seem to be working when I use the AML as a work-around. I think I'll wait for a patch for the official launcher before I try to run LWotC again.

**Comment by UMebius** [comment]
I also ran into such issues such as missing grenade icons despite using AML.

**Comment by copyrite** [comment]
Grenade icons were an issue when Cost-Based Ability Colors was used without setting a config in LWOTC, however that has been mitigated if not completely fixed. Otherwise the only thing I can say is that this issue is now very old, open a new one if this is still relevant.
