### ISSUE TITLE
Long War of the Chosen not showing up

### ISSUE THREAD

**Issue by KodeShikou** [long-war-2/lwotc#1049]
Finally unreverted the oldschool library to accommodate the new launcher, and followed the installation instructions again, and Long War of the Chosen isn't showing up in the mod list under WoTC in the new launcher, and it worked last week before the update. Took a look through the issues but didn't see anything like it, unless I'm just blind.

**Comment by cryptikon** [comment]
Same problem here. I assume the update broke the launcher's capability to discover mods.

Interestingly, even XCOM Alternative Mod Launcher couldn't find mods installed in the manual mod directory.

The way that I fixed it was by adding the mod folder manually in the Xcom Alternative Mod Launcher settings.
......\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods

**Comment by Kondenado** [comment]
Hi

I am having the same issue, I can not find Long War of the Chosen or the other non-steam mod with the new launcher. 

I have tried installing manually in: \steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods but no luck

**Comment by ansabalirai** [comment]
As the post above suggests, maybe consider getting AML installed and running. You can find instructions here: https://github.com/long-war-2/lwotc/wiki/New-Player-Resources

**Comment by TheOtherNewJack** [comment]
AML is a no go for me. And PLEASE stop calling it a fix - it is not fixed. It is a workaround.

**Comment by Grobobobo** [comment]
No longer relevant.
