### ISSUE TITLE
Add faction unit armors and weapons.

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#105]
I am raising this to take this issue for implementation. I actually already did this in my fork but at this point I am testing the changes. I am going to be playing with balance issues. I made bullpups have the same mobility and detection bonuses as smgs but might play around with that.

I added higher bases damages to the mag and beam weapons for the faction weapons as well (the biggest bump being to templar celestial gauntlets as they are the highest risk of all of the faction units).

Wanna keep this open until the amounts for the stats of weapons and armor are good. The armor is probably good as I am just having them use the same amounts as regular soldier armor (so plated faction armor will have the same stats as plated xcom armor).

**Comment by jmartinez989** [comment]
Looks like the schematics for the weapon upgrades are still showing up. I'll get that fixed within the next day.

**Comment by ansabalirai** [comment]
I would definitely be ok with either the bullpup increased damage and/or changing the range table. Basically, we need to make sure that either it is good up close with higher damage than smgs or it is more forgiving at longer ranges like an assault rifle. IMO, it is pretty pathetic in terms of damage right now

**Comment by pledbrook** [comment]
It definitely looks like a short range weapon visually.

**Comment by GitWadeanthony** [comment]
Since the faction units miss a rank in weapons (Beam and Gauss) how would you feel about adding pistols to Templar and SMGs to Skirmishers as standard weapons. Auto Pistol and Bullpup can get an increase in min/max base damage to match the other tiers and have Bullpup have an increase in crit damage similar to the shotgun so the SMG is not a straight upgrade?

**Comment by jmartinez989** [comment]
Ok so this has been implemented and seems to be working. I made bullpups give only 2 bonus mobility and have a slightly higher detection radius than smgs. This should put them in a good spot. They also do have a slightly higher sound radius than smgs as the in game sound for them does indeed sound louder.

**Comment by jmartinez989** [comment]
I think at this point we can consider this closed. Looks like the values for faction armor and weapons are pretty good. The damage values for the higher tiers seems to be in a good place and should be able to keep pace with a lot of the higher health values of the late game units.
