### ISSUE TITLE
Killing a Pyro with Soulfire should not cause them to explode

### ISSUE THREAD

**Issue by krisnye** [long-war-2/lwotc#1050]
Minor thing, but it would be an improvement if there was no chance for them to detonate if killed with mental attacks.

**Comment by Bigglett** [comment]
+1

**Comment by Matthew-V-Milone** [comment]
By any chance, do you or anybody else viewing this issue have a save file taken mid-mission with both a Psi Operative and a Purifier? That would be helpful for testing purposes. I'm interested in solving some of these issues, but I'm not interested in doing half of a campaign just to get to the point where I can test that interaction.

**Comment by Grobobobo** [comment]
Disagree.
