### ISSUE TITLE
Missions...

### ISSUE THREAD

**Issue by Charlie0309** [long-war-2/lwotc#1051]
I am not sure if this is an issue. I several times to register on the Pavonis forum, and dont seem to get the email, so I guess I will have to post this here...

I am a LW vet from Xcom1, and this is my first full playthrough on Xcom2/LWotC, so I am not 100% sure of what to expect when. My game is on easy difficulty, and I have only installed recommended mods, plus a few ease of life mods.

I am in September. I have finished the research tree. I have liberated all of Europe, Asia and Australasia. I am just trying to level up my officers and PSI before I embark on the Shadow Chamber missions. I gather I am almost at the end of the game (equivalent of the Overseer mission, I guess).

So far, I have seen no defence missions, and no retaliation/terror missions. The only Advisor/haven mission I have seen have been intercepting the shapeshifter meeting.

I have also yet to see an Archon, Andromedean, Gatekeeper, Sectopod, any of the alien leaders or the Hive queen (I have the hunters turned off). I feel like I may be missing some of the content, but I am not sure if it is because Advent are not strong enough to field these units, or perform retaliations... I am not as familiar with the mission generator, or how Advent strength works, although I think the highest strength that I can see in any region is 6 (There are 3 regions I have yet to contact) and Force is at level 13.

What am I doing right/wrong?

Cheers!

**Comment by ansabalirai** [comment]
None of what you mentioned seem to be obvious bugs. I would suggest joining the LWOTC discord here for more information:
https://discord.gg/vv5yJF9

**Comment by Grobobobo** [comment]
No way to reproduce anything.
