### ISSUE TITLE
saves made offline won't load

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1052]
I was forced offline while playing. All of the saves I made while offline will not load properly. 

Here are two examples.
[save_Save 158_1.zip](https://github.com/long-war-2/lwotc/files/4706536/save_Save.158_1.zip)

**Comment by bobjjones** [comment]
To be clear. I already tried refreshing the config folder. I am running beta 3.0.

**Comment by Grobobobo** [comment]
Unlikely to be a lwotc issue.
