### ISSUE TITLE
Anyway of enabling the chosen if you forget at the start?

### ISSUE THREAD

**Issue by gedking** [long-war-2/lwotc#1055]
I'm a few years into my LWOTC and done most things but forgot to enable the chosen in the advanced menu when I started the game. I've noticed the beta 3 game allows you to enable them but as of yet they will not activate. Is there any way I can do this threw the ini files since I think the timers might be out of wack ? Any help would be good. Thanks

**Comment by Grobobobo** [comment]
No longer relevant.
