### ISSUE TITLE
deception hack+ haywire bug

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1056]
In the attached save, use ragtime to first hack the tower for deception. This succeeds and controls a chrysallid. Then use ragtime to try to hack the mec to control it. This also succeeds. However, after that, another advent trooper in a different part of the map also gets mind controlled. This last mind control seems to be an "extra" one that results from a deception hack immediately followed by a haywire control.
[save_AUTOSAVE- Campaign 13, Mission 33, Turn 3.zip](https://github.com/long-war-2/lwotc/files/4725855/save_AUTOSAVE-.Campaign.13.Mission.33.Turn.3.zip)

This appears to be  a bug.

**Comment by copyrite** [comment]
Duplicate of #740
