### ISSUE TITLE
Long war of the chosen and community highlander do not appear in the mod list of new launcher

### ISSUE THREAD

**Issue by Kondenado** [long-war-2/lwotc#1057]
As I am saying, I can not "load" those two core mods, as they don't appear in the list of mods I can load when I start a new game. Note, that now there is a new launcher. 

This is the folder where the mods are supposed to be right?

C:\Program Files (x86)\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods\LongWarOfTheChosen

C:\Program Files (x86)\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods\X2WOTCCommunityHighlander

How can I fix this?

**Comment by Kondenado** [comment]
Hi

It might be solved by using alternative mod loader.

https://github.com/X2CommunityCore/xcom2-launcher/blob/master/readme.md


(Remember to include in the folder to look for mods:

C:\Program Files (x86)\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods\
(folder of the two main mods)

AND

C:\Program Files (x86)\Steam\steamapps\workshop\content\241100

(where the mods you will install via steam are)

**Comment by Kondenado** [comment]
I am not sure if i have loaded properly the other 3 mods i need.

The game was telling me about that the mods were missing despite being "ticked" in the AML.

In addition in "advanced options" the available option was "enable chosen" not "enable second wave".

**Comment by Grobobobo** [comment]
No longer relevant.
