### ISSUE TITLE
Templar's Deep Focus&Supreme Focus replaced by other abilities in Beta 3.1

### ISSUE THREAD

**Issue by y403899457** [long-war-2/lwotc#1061]
Any ideas?
![bug1](https://user-images.githubusercontent.com/43226148/84016978-a83b0580-a9b0-11ea-86fe-04f95c3531e4.png)
![bug2](https://user-images.githubusercontent.com/43226148/84016986-aa04c900-a9b0-11ea-9f75-8bf597d71b15.png)

**Comment by Grobobobo** [comment]
Intentional, templars now get deep and supreme focus through gauntlet upgrades.
