### ISSUE TITLE
Can't find skirmisher!

### ISSUE THREAD

**Issue by Ryanzhangtr** [long-war-2/lwotc#1062]
I started the game without chose any hero camp, and I can find the reaper and templer, but until now I have already gain one reaper one templer and met all three chosen, still I don't find the skrimsher, neither the rescue  covert action nor finding the skirmisher camp! So I just wondering if I missed something or there is a bug, help plz _(:τ」∠)_

**Comment by daruperez** [comment]
you must recluit a hero in mission room

**Comment by Ryanzhangtr** [comment]
> you must recluit a hero in mission room
Sorry,English is not my mother language,  do you mean I have to rescue Mox（the skirmisher）at first? But so far I still don't get this mission

**Comment by daruperez** [comment]
In lwotc, you need to recruit a hero in the mission room to find the camp

**Comment by Ryanzhangtr** [comment]
> could you put a screenshort of the mission room?
> mission to find faction is on top of the screen

![20200611110201_1](https://user-images.githubusercontent.com/66689037/84345096-03523f80-abdf-11ea-8a44-e7640a713028.jpg)

**Comment by daruperez** [comment]
Hi,

it's a error...

when you start you must have these missions of the choosen:
![image](https://user-images.githubusercontent.com/56190157/84353647-d3e00a80-abbf-11ea-96cb-4ac7cd756d47.png)

**Comment by Ryanzhangtr** [comment]
> Hi,
> 
> it's a error...
> 
> when you start you must have these missions of the choosen:
> ![image](https://user-images.githubusercontent.com/56190157/84353647-d3e00a80-abbf-11ea-96cb-4ac7cd756d47.png)

alright，that seems I really get into a trouble.thank you bro for answering my question so patient :)

**Comment by Grobobobo** [comment]
Unable to reproduce.
