### ISSUE TITLE
haven defence mission balance

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1066]
When advent hits a haven, there seem to be two different scenarios. One where they have boots on the ground already and one where they are sending reinforcements as you try and collect people and evac.

in the second one, I almost never lose a rebel. But in the first type, I will typically lose 4-5 rebels depending on how lucky I get. It is nearly impossible to avoid losing rebels.

As far as I can tell, which type you get is random. I think that the evac missions need to be a little harder to make you more likely to lose people and the boots on the ground missions should be harder as well, but maybe make it more possible to save rebels.

Also, why aren't the rebels armed? On supply convoy missions they are armed. On rendevouz, they are armed. What? They couldn't find a gun when they are in the haven?

**Comment by Anxoczt** [comment]
I would make the evac one abit harder and the full on retaliation less frustrating by buffing rebels HP so they can atleast survive one magnetic weapon hit and make them harder to hit. And capping max enemies that can spawn on that level so a retaliation in advent strenght 7 and above isnt absolute shitshow.

I would add some starting enemies (1-2 pods) to the full evac one so you have something that can threaten the rebels.
Or i would change the mission entirely to be like Supply defence, you face large pods in waves and once they are all dead the mission is over. And you cannot evac rebels from it. So you need to take care of them too.

Or the already burning heaven could be filled with random, non rebel civilians like in Provisional govt. sector raid mission for ayys to gun down so there is abit more time (and with luck) to save the people that actually matter.

**Comment by bobjjones** [comment]
The last of your suggestion is, I think, the easiest one to implement. The problem is that every turn, you will lose at least one resistance person, and you simply can't get to all the enemies faster than 4 or 5 turns even if it is a relatively weak force. 

If I could do this the way I wanted, I would say that the haven raid would be a hidden mission that could be uncovered with intel (like finding troop movements). If you find the mission, you get the one where the enemy is dropping in as you get there. However, if you don't find the mission before it expires, then you get a rapid response mission where advent already has forces on the ground assaulting the camp.

However, I would argue that, in both of these cases, the rebels that are part of your haven should be armed and there should be other unarmed civilians running around.

**Comment by pledbrook** [comment]
These missions have been rebalanced for the Chosen.
