### ISSUE TITLE
Crashed when entering the first mission

### ISSUE THREAD

**Issue by leaoguo** [long-war-2/lwotc#1067]
after complete loading the first mission on skyranger and i click my mouse, the game crashed. i can't hear bradford's voice when on skyranger too, is it normal? do i need to provide any log files to solve it.

**Comment by Grobobobo** [comment]
Something's likely wrong with your installation, make sure you followed all steps here:

https://github.com/long-war-2/lwotc/wiki/Installing-Long-War-of-the-Chosen

**Comment by leaoguo** [comment]
> Something's likely wrong with your installation, make sure you followed all steps here:
> 
> https://github.com/long-war-2/lwotc/wiki/Installing-Long-War-of-the-Chosen

already solved it, i didn't download full content before
