### ISSUE TITLE
suggestion: refuge missions by level

### ISSUE THREAD

**Issue by daruperez** [long-war-2/lwotc#1080]
hi
Perhaps the refuge missions are according to the level and an appearance percentage, this way you could add the missing refuge mission

mission 1: with help (easy)
mission 2: wait skyranger (medium)
mission 3: kill alien (hard)

appearance:
-lv1 to lv10: m1 50%, m2 35%, m3 15%
-lv11 to lv15: m1 25%, m2 50%, m3 25%
-lv16: m1 15%, m2 35%, m3 50%

or another percentage and/or level...

**Comment by Grobobobo** [comment]
I'm not sure what are you even asking about, but that kind of level scaling is a terrible idea regardless.
