### ISSUE TITLE
subtitles in another language, is it possible? how?

### ISSUE THREAD

**Issue by daruperez** [long-war-2/lwotc#1081]
hi,

I would like to have the voice in English and the subtitles in Spanish, is it possible? How?

thanks

**Comment by ToastedAmphibian** [comment]
Not sure if your still looking for this or not, but here:
[INT.zip](https://github.com/long-war-2/lwotc/files/5033892/INT.zip)

Set your language to English, then unpack the file and replace your INT folder at     Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Localization\  with it. Audio is English, menu options and subtitles are in Spanish. Other things are a bit of a crapshoot. Make sure to back up your original INT file, I only tested so far as booting up the first level and I don't speak Spanish. Hope it helps.

**Comment by daruperez** [comment]
Perfect!!, thanks
