### ISSUE TITLE
Infiltration % not showing, unable to start ADVENT Tower mission.

### ISSUE THREAD

**Issue by Kerbomancer** [long-war-2/lwotc#1083]
When a squad is deployed to a mission, the infiltration % doesn't appear on the Geoscape. Missions can't be started early if the icons are clicked on, the only way to start them is their counters expiring.

[save_AUTOSAVE- Campaign 4, Mission 27_2.zip](https://github.com/long-war-2/lwotc/files/4942833/save_AUTOSAVE-.Campaign.4.Mission.27_2.zip)

 Also, even after infiltrating it to 200% (Checked it with the armory screen), the liberation mission with the tower can't be started from the Geoscape. I can send another team in and pick the old one up, but the mission can never be started, it's almost as if it was never infiltrated in the first place.

**Comment by putmeinthegamecoach** [comment]
having the same problem looked all over for a solution.  Can't progress in the story

**Comment by attilabertok** [comment]
I also have this one. :(

**Comment by copyrite** [comment]
Closing due to age and framerate smoothing being the probable cause. There's a mention of this in the wiki so no point keeping this issue open just for that.
