### ISSUE TITLE
Suggestion: add strategical information

### ISSUE THREAD

**Issue by LogunovAV** [long-war-2/lwotc#1084]
It was already implemented for LW2 as separated mod, but sometimes it conflicts with existing.
I think it can be a good idea to move it inside the package, because this mod is important for legend playing. I think user shouldn't count everything in his mind.

https://steamcommunity.com/sharedfiles/filedetails/?id=925598042&searchtext=Vigilance \\Already implemented version

**Comment by Grobobobo** [comment]
It's already integrated, has been since pretty much the start,

**Comment by LogunovAV** [comment]
Sorry for bothering :( , I was drunk yesterday and tried to install it over the exist integration.

Strange thing happens sometime...
