### ISSUE TITLE
Reaper not affected by BETA Strike HP

### ISSUE THREAD

**Issue by TyborPL** [long-war-2/lwotc#1086]
I have a Reaper that has standard number of hit poins while BETA Strike is enabled
[save_IRONMAN- Campaign 59.zip](https://github.com/long-war-2/lwotc/files/5005854/save_IRONMAN-.Campaign.59.zip)
![mod list](https://user-images.githubusercontent.com/36968943/89015072-c66d1400-d316-11ea-9282-9f8918105fe1.jpg)

![PrintSreen](https://user-images.githubusercontent.com/36968943/89015608-996d3100-d317-11ea-8e09-efb8c73cfa47.jpg)

**Comment by Grobobobo** [comment]
Not specifically a LWOTC issue
