### ISSUE TITLE
Chosen not showing up for his assualt on the Avenger

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1087]
As the comment suggests, the hunter was assaulting the avenger, but when I sent my two 5 man squads out to take out the guns, he never showed up. I was under the impression that he was supposed to show up. Saves are attached. I included one from the save immediately before the assault in case it is useful.
[save_Save 264 (2).zip](https://github.com/long-war-2/lwotc/files/5009093/save_Save.264.2.zip)

**Comment by pledbrook** [comment]
Fixed in [this commit](https://github.com/long-war-2/lwotc/commit/bc302f6a67c163511ff63a64cb0d0a1bb1b2311a).
