### ISSUE TITLE
defending against chosen assault appears to be an infiltration mission

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1089]
During squad selection for this mission, the infiltration time is still in the top right.  In the attached save, when I took the avenger to the scan for supplies at the "lead," the hunter jumped me. Hopefully that allows for reproduction of the issue.
[save_Save 252.zip](https://github.com/long-war-2/lwotc/files/5009112/save_Save.252.zip)

**Comment by wdanny69** [comment]
this is an old issue and the mission has been reworked. trying save does not reproduce the issue and may have been fixed.

if it still occurs, please provide a save if reproducible, a mod list and as much details about the set up to the point the bug occurs
