### ISSUE TITLE
alien rulers are a no-show in 3.1

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1091]
When are they supposed to show up? I am at force level 14, and I still haven't seen any. Should they have happened already? I am about to murder my first chosen, and I haven't seen one alien ruler.

**Comment by StuartA101** [comment]
Same

**Comment by StuartA101** [comment]
Just had the Berserker Queen show up on a mission. Highest Advent strength in a region was 10 :)

**Comment by Charlie0309** [comment]
I just finished my first play through and did not get any rulers show up at all.

I had the chosen switched off, as I heard they are unbalanced early game... not sure if that has an effect.

I might give it another go when the next version is released, as it seems a lot of the WOTC scripted levels/maps is not playable yet (and I have yet to play them as I cant stomach the vanillia versions).

The lack of claustraphobic maps is somewhat a disappointment, with no underground alien bases or large enclosed ufos... And Roland Rizzo's score leaving knots in my stomach

It took until the final mission when we finally get something that felt otherworldly... Oh, and the Hunter dude showed up for a very, very short cameo.

**Comment by bobjjones** [comment]
I am at force level 21, I saw the viper king once, the archon king once, and I have not seen beserker queen at all. The chosen also completely stopped showing up for a while. I definitely think there is a bug in here that seems to be turning off the kings/queens/chosen checks.

Its possible the kings and queens are gated by advent strength in the region. I haven't really done any missions where advent strength is higher than 5. I just use those regions for recruitment and supplies.

**Comment by pledbrook** [comment]
These should be showing up now, although they're still not very common unless you manage to detect some Troop Columns and Supply Raids.
