### ISSUE TITLE
feedback not working as intended?

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1092]
The resistance order feedback appears to have some glitches.

Advent priests will randomly trigger feedback when you approach them. I think they have some kind of aura that is triggering it.

The bigger problem one is that, when a sectoid mind controls one of your soldiers, he does not suffer feedback. I presume this is because he is now a friendly and feedback procs after the skill is resolved. I think it should proc before the skill is resolved. Mind control is the only one it matters for. Also, feedback does not seem to affect the chosen warlock. However, when I use a psi ability on the mind controlled soldier, I suffer feedback damage. I don't think this is intended.

**Comment by Grobobobo** [comment]
We will not be touching the feedback ability.
