### ISSUE TITLE
Change the holy warrior ability description to reflect LWOTC changes

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#1093]
Killing a priest buffing a Naja with Holy Warrior did not cause the Naja to die.
[save_Holywarrior Bug.zip](https://github.com/long-war-2/lwotc/files/5011555/save_Holywarrior.Bug.zip)

(Fleche with Shinobi)

**Comment by Grobobobo** [comment]
That's intended, was removed a while ago.

**Comment by ToastedAmphibian** [comment]
Okay. Could someone alter the description of the ability to reflect that change?

**Comment by Grobobobo** [comment]
Right, forgot about renaming enemy abilities for F1 purposes.
