### ISSUE TITLE
Covert Ops: Got reward on a failed mission

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#1094]
Doing an op for the Templars to recruit an Engineer. The op failed, but I received the staff anyways.

Save is from the day before the mission completes.
[save_AUTOSAVE- Campaign 12, Mission 43.zip](https://github.com/long-war-2/lwotc/files/5020685/save_AUTOSAVE-.Campaign.12.Mission.43.zip)

**Comment by Grobobobo** [comment]
Duplicate of #1018
