### ISSUE TITLE
All Rescue Resistance Contacts Missions crash PC

### ISSUE THREAD

**Issue by StuartA101** [long-war-2/lwotc#1097]
Hi,

I been playing this for a while, with the 5 mods + only cosmetic mods. All missions seem to run fine, but every 'Rescue Resistance Contacts' mission causes the game to crash. All other missions seem to run fine (one crash with a smash & grab mission - but all others have been fine).

I added a 'maps' mod, but the  'Rescue Resistance Contacts' mission were crashing multiple times before that anyway.

I'm not very techie, so let me know how I can help more, as I`m loving this :)

Ps. The animation of posting X4 doesnt seem to show some times, but doesn't affect the game at all.

**Comment by StuartA101** [comment]
Update: I've been doing some testing and think it might be a mod conflict.. not sure which one though, will post when I figure it out!

**Comment by Adventburger** [comment]
I am having the exact same problem.  I am on my third playthrough and I have deleted the config file in documents and run a validation each time, before and during campaign.  I can add the log file if requested.

I have managed to play more than a dozen other missions without issue, but when this one comes up it's a CTD every time.

**Comment by StuartA101** [comment]
I unchecked all the mods and started a new campaign, with just the 5 mods mentioned in the set-up. The 'Rescue Resistance Contacts' then worked. Slowly, I added a mod back after each time those missions came up.. and so far so good. I still have quite a few more to re-add, but none of the ones I added so far has caused the crash.

**Comment by Adventburger** [comment]
I was using an additional maps mod. When I removed this, I no longer had the CTD issue on this mission type.

**Comment by StuartA101** [comment]
Do you remember which map mod it was?

**Comment by Adventburger** [comment]
Not exactly.
I believe there are only 3 that are for WOTC and I unsubscribed from all of them.
I have done a number of these missions now and no issues.
Regards


    On Tuesday, September 1, 2020, 10:59:03 AM GMT+1, StuartA101 <notifications@github.com> wrote:  
 
 


Do you remember which map mod it was?

**Comment by StuartA101** [comment]
Cool. I have probably got all 3 as well... but none running at the moment, I`ll have to try them out and see if any work.
Cheers :)

**Comment by Grobobobo** [comment]
Was deemed a mod conflict.
