### ISSUE TITLE
Error detected attempting load of package: LW_Overhaul

### ISSUE THREAD

**Issue by dpstafford** [long-war-2/lwotc#1098]
Can't play LWOTC.   Get this error every time.   Does anybody know what I am missing??

**Comment by dpstafford** [comment]
Had the wrong Highlander.   All good now!

**Comment by lahidden** [comment]
You are the best kind of person. Thank you!

**Comment by ArielOjosVerdes** [comment]
> Had the wrong Highlander. All good now!

Can you be more specific on what you had and how you fixed it?

**Comment by Gibbanator** [comment]
got the same problem.. says error loading than goes in not responding mode. I got no Highlander mod so not sure what your talking about. Looks like I need to load game and click one mod at a time to fine it for there is not mod called LW_Overhaul so must be in one of the mods
