### ISSUE TITLE
Power relays not present on a Psionic transmitter mission

### ISSUE THREAD

**Issue by ghost** [long-war-2/lwotc#1100]
[Logs.zip](https://github.com/long-war-2/lwotc/files/5058829/Logs.zip)

This zip includes logs and 2 saves. Don't know what logs are relevant so I included all of them and save files is inside the logs folder. One save start takes you before the mission has started and the other one on the first turn of the mission. Can't confirm that there are NO power relay's on the map, but I have explored about 90 % of the map thrice now by reloading before mission start. The only mod I'm using that's not on the recommended or must have list is the numerical health display (https://steamcommunity.com/sharedfiles/filedetails/?id=1126938196).

Thanks for working on the mod : )

**Comment by zonixum** [comment]
Note: It seems like the soldiers react to finding the relays("object sighted" etc). So I suppose they are there, however I cannot see them on the map neither target them using my soldiers.

**Comment by pledbrook** [comment]
This was probably a temporary bug while I was testing cooking.
