### ISSUE TITLE
Assistance with installing

### ISSUE THREAD

**Issue by Spirit117** [long-war-2/lwotc#1101]
I need some help getting this mod working. I had it running maybe a year ago, but ive since wiped and reinstalled Windows 10 so i need to set it up again. I unzipped my files into my steam install on my secondary HDD where xcom 2 is installed E:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods

In the mods folder i see the LongWaroftheChosen and X2WOTCCommunityHighlander folders, so that should be fine. My alternative mod launcher refuses to launch about half the time, either requiring a new install of the mod launcher or a restart of my machine. When it does work, I set the launch path with local files as specified to the steam install on my E drive, yet i do not see these 2 mods available to select/launch. 

Any suggestions for what im missing here, regarding mods not detected and the mod launcher breaking?

**Comment by ToastedAmphibian** [comment]
Did you add E:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods\   as a mod directory in the launcher?
![ModDirect](https://user-images.githubusercontent.com/52621448/90343877-84182800-dfe2-11ea-87dc-720233e7cb02.jpg)

**Comment by Grobobobo** [comment]
No response since then.
