### ISSUE TITLE
post mission hack rewards are not right

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1102]
I just completed a mission where I was hacking a chest. I had two specialists with me. Each one of them skull-jacked a soldier for a large intel cache. Then I hacked the chest for another large intel cache. Then I hacked a lamp post for an advanced PCS.

I didn't notice if the advanced PCS was recorded, but I saw that I only got one of the 3 intel caches I hacked. The mission was an intel mission, so I got a little bit from that too.

This may be intended behavior, but if it is, players should be informed of what the actual behavior is. Is only one hacking award allowed per mission? If so, which one is thrown away? one hacking award per specialist?

Saves are attached from both before the end of the mission and after the end of the mission.

[save_AUTOSAVE- Campaign 19, Mission 48, Turn 12.zip](https://github.com/long-war-2/lwotc/files/5078221/save_AUTOSAVE-.Campaign.19.Mission.48.Turn.12.zip)

**Comment by wdanny69** [comment]
Not sure if its intentional or not but this behavior also existed back in long war 2 ( could possilby be a bug ). Essentially you are only allowed one of each intel cache, so as you described if you succesfully get three large intel caches you'd only actually get one. Same thing with small intel caches.

**Comment by daruperez** [comment]
it also happens in the original game

**Comment by copyrite** [comment]
Known base game bug: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/1190
