### ISSUE TITLE
Stand by Me // Stun Bug?

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#1103]
Drone stunned a gunner, bonded sniper moved adjacent and 'removed' the stun, in that a message popped up saying the soldier was no longer stunned, they got back to their feet. However they did not get any action points that turn, and they did not get any action points the following turn either. Ended up giving them their action back with the console.

[save_Stun Bug.zip](https://github.com/long-war-2/lwotc/files/5081362/save_Stun.Bug.zip)

**Comment by wdanny69** [comment]
cannot reproduce, the save also has "reivival protocol fix" which is hard incompatible with lwotc. This is an old issue and may have been fixed

if it comes back,, please provide a reproducible save if able, a mod list, and as much detail about the set up up to the point it occurred
