### ISSUE TITLE
Traverse Fire // Light 'em Up

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#1106]
Light 'em Up: Taking a Standard Shot with your Primary Weapon as your First Action no longer ends your turn.

Traverse Fire: After taking a Standard Shot with your Primary Weapon with your First Action, you may take an ADDITIONAL non-movement action.

The descriptions seem to say that, if you take that standard shot with your first action, you get to keep your normal second action (Light 'em Up) and gain an extra action (Traverse Fire). In reality, Traverse Fire does not trigger at all with Light 'em Up, making it a very poor purchase for 40 AP.

Admittedly, A Standard Shot + Any Action + Any non-movement Action ability with no aim penalty and no cool down could well be OP, even at Master Sargent level. Probably the easiest way to solve the problem is to note in the description that they don't work together, the way Hit and Run and Run and Gun do.

[save_AUTOSAVE- Campaign 12, Mission 111, Turn 4.zip](https://github.com/long-war-2/lwotc/files/5121995/save_AUTOSAVE-.Campaign.12.Mission.111.Turn.4.zip)

**Comment by Grobobobo** [comment]
Changed in dev 18.
