### ISSUE TITLE
XCOM 2 Long War of the Chosen not working

### ISSUE THREAD

**Issue by Kotwald** [long-war-2/lwotc#1107]
Hi. I have tried going through https://github.com/long-war-2/lwotc/wiki/Installing-Long-War-of-the-Chosen troubleshooting guide. Running only the mods listed, but my LWOTC is still not launching. It launches the first time after I delete config files but then on the 2nd startup it is not responding and wont start. Could you please help me with this issue?

**Comment by MikkaRibou** [comment]
Hi. 

I have exactly the same issue and I also followed the guide.
The game is completely frozen.

![image](https://user-images.githubusercontent.com/16610409/93617410-396d3f80-f9d6-11ea-893c-59d7a99e6e91.png)

Thank a lot if you can help me (and Kotwald).

**Comment by Grobobobo** [comment]
Apparently the guy fixed it in #1108

**Comment by shemerk** [comment]
Thanks you! installed the xcom2WOTCHighlinderCommunity from steam and it solved the issues!
