### ISSUE TITLE
LWOTC not working, probable issue with CommunityHighlander

### ISSUE THREAD

**Issue by Marcusbjol** [long-war-2/lwotc#1108]
Installed Beta 3 (Both the LWOTC and CommunityHighlander) in the correct directory (mods dir). Added that dir Alternative Mod Launcher. Deleted XCom2 war of the chosen/xcomgame/config. Launched game and had the "New Game" button, restart, and crash. Verified files via steam.

When starting a new game, accidentally left LWOTC enabled and had installed the steam version of the CommunityHighlander and had the correct button to start the LWOTC campaign (no crash).

**Comment by Kotwald** [comment]
You are a genius man. The same thing happened with my launch and I was starting to get frustrated. The troubleshooting guide explicitly says to remove the steam version of this mod. I subscribed to the steam version of ComHighlander and now it finally works. I however get redscreen error messages but so far its nothing serious. Thank you for this great tip.

**Comment by Grobobobo** [comment]
No response since then, assumed to be fixed.

**Comment by Marcusbjol** [comment]
I am unsure on what I was supposed comment to? The guide specifically states to not use the community highlander off steam but that is the only way I could get the mod to run.

**Comment by Grobobobo** [comment]
Oh, sorry. Either way, this isn't really something we can really fix, considering the fact that the instructions work for almost everyone else. You probably screwed up somewhere I can't see, and if you can't find out where then the only thing you can really do is to wait for the workshop release.

**Comment by Marcusbjol** [comment]
Fair enough. 
Might be worth it to leave the issue open as others have used this solution to fix the problem.
