### ISSUE TITLE
Holo-Targeting AWC Perk for Templar does nothing

### ISSUE THREAD

**Issue by xXerxes** [long-war-2/lwotc#1109]
At first I assumed Holo-Targeting would apply to his secondary Auto-Pistol since its his only projectile weapon, then I read the description which says Shard attacks (his psionic Gauntlet) apply the targeting buff. After testing it by console leveling him to max level I found none of the Templars attacks (Volt,Meele,Faceoff,Pistol-shot (didnt test Stun-Strike)) apply the buff making the perk entirely useless as a pick.
Thank you for your time on porting long war its much appreciated.

Edit: After going through the classdata config files it seems to be intentioned to apply to the templars secondary, Clutch shot does seem to actually apply the holo though im not sure why, I'm using a few cosmetic and gameplay improving mods alongside longwar though none that interact with the templar, inventory spaces or secondary weapons.

**Comment by pledbrook** [comment]
Templar can no longer get Holotargeting.
