### ISSUE TITLE
Injured soldiers available to be sent on mission

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#111]
If part of a pre-defined squad, injured soldiers can be sent on a mission. In the attached savefile, run the supply raid being currently infiltrated and the ranger would have some missing health.

[injured soldier on mission.zip](https://github.com/long-war-2/lwotc/files/3092839/injured.soldier.on.mission.zip)

**Comment by jmartinez989** [comment]
Yeah I've seen this as well. It's basically the auto fill squad feature squad select mod. It send all units in a squad even if they are wounded. You can kick them from the squad loadout and then you wont be able to select them from the roster after so that part still works.

**Comment by MiserablePileOfBugs** [comment]
That's odd because I loaded this save and saw the issue but I wasn't able to recreate it in my own game. I tried a monument sabotage and a jailbreak mission but selecting a squad with injured soldiers seems to work as intended.

Could it be that it only happens on certain missions types?

**Comment by pledbrook** [comment]
@MiserablePileOfBugs That can happen if you can't reproduce the game state in that save file. For example, newer versions of the mod may fix things that mean units never get into that state again. So the bug can't be reproduced in new campaigns. Not saying that's the case here, but it's the kind of thing that can happen. That seems more likely than the mission type having anything to do with it.

**Comment by pledbrook** [comment]
That wounded soldier appears to be bugged out. He has a status of `eStatus_Active` when it should be `eStatus_Healing`. The bug that caused the incorrect status may still be in the mod, but this issue won't help find it I'm afraid. Hopefully it's already been fixed.
