### ISSUE TITLE
Dual Wield Melee/Pistols not working with LWOTC

### ISSUE THREAD

**Issue by WolfLordFenrir** [long-war-2/lwotc#1110]
Can't seem to equip a second pistol or melee weapon with LWOTC enabled. Primary secondaries is working fine, but if I equip a pistol or melee weapon in either the primary or secondary slot, it locks that category (Using Tactical Armory UI) for the other slot so taking two is impossible. Any suggestions? Thanks.

Note: Don't know if it's something to do with the BETA Highlander maybe? Or if there's a config file somewhere I can edit as a workaround/fix that'd be great.

**Comment by Grobobobo** [comment]
There are specific compatibility patches for that kind of thing, not a responsibility of the base mod
