### ISSUE TITLE
Nothing to scan on map LWOTC

### ISSUE THREAD

**Issue by Zedolk** [long-war-2/lwotc#1111]
hello, I've felt like playing some LWOTC, after installing everything like the instal wiki said, deleting the config in my games and all.
I launched the game with only the required mods nothing else everything is fine from that point. After gatecrasher I see that my geoscape has black market for 1day of scanning, the first haven given and my starting faction, nothing else can be scanned.

I scanned for a bit thinking there may be some that pop up, but except missions nothing poped up i tried scanning for 2 month still nothing.

I also tried changing the highlander for the beta one on steam, it did the same thing but the black market had 3 days to scan (I don't think it's related)

![image](https://user-images.githubusercontent.com/70483041/91665496-049b5600-eac4-11ea-8252-723179a8b21d.png)

**Comment by wdanny69** [comment]
this is just normal long war behavior. unlike vanilla there aren't constant random points of interests spawning for you to scan. here scanning with the avenger acts like multiple rebels on the intel job and is what helps you find missions. points of interests now spawn as a mission reward. usually from missions that reward you with a "intel package"

**Comment by Zedolk** [comment]
ahh ok it changed a lot then, thanks
