### ISSUE TITLE
Reinforcement Flares not showing 

### ISSUE THREAD

**Issue by StuartA101** [long-war-2/lwotc#1113]
I know they only show on rookie and veteran difficulty (which I`m doing my first LWOTC playthrough on), but during Evac or defend resistance personal, only the initial flare shows up, further ones only show if you save and reload.

I didn't notice at first and thought it was just part of the new set up, but I had to save a game and when I loaded it later, a flare was burning away.

**Comment by Grobobobo** [comment]
Working as intended.

**Comment by pledbrook** [comment]
Not a bug
