### ISSUE TITLE
infiltrator commander perk does not do anything

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1115]
So far as I can tell, the benefit of this perk is zero. Doing a 10 man infiltration on the psionic gate, I found a grand total of 2 hours difference between using my colonel with infiltrator and a random tech sergeant. This 2 hour difference is likely due to the fact that a few of the people in the group served under her before and are getting an infiltration bonus for that. There appears to be no benefit from the infiltrator perk.

Can anybody else definitively show that the infiltrator perk does something?

**Comment by pledbrook** [comment]
Fixed in [this commit](https://github.com/long-war-2/lwotc/commit/065805c89ca55610effebd2388bbc2003d143f34).
