### ISSUE TITLE
game crash on start of missions mid campaign

### ISSUE THREAD

**Issue by MONST3R12** [long-war-2/lwotc#1117]
so everything was working fine up and till missions would just crash after the loading screen i was hoping someone could help me pint point the issue with the log i have i already tried deleting the config file in the documents and verifying files 
[Launch-backup-2020.09.12-20.26.42.log](https://github.com/long-war-2/lwotc/files/5213078/Launch-backup-2020.09.12-20.26.42.log)

things i tried:
-tried to run the mission without any mods but the ones needed to run lwotc

-tried running a diffrent mission that i hadnt started to infiltrate yet, the mission started but the other 3 missions that i am curently trying to do still crash i cant just ignore them because this issue could show up again later on

-tried deleting config files

-tried disabling all the mods loading the game saving going back out and re enabling them

-tried moving all the mods but the ones needed out of the workshop folder and trying to run the mission

-tried to verify files but it keeps getting stuck at 99%

**Comment by MONST3R12** [comment]
first thing that came to mind was the map mods i have i tried disabling them but nothing

**Comment by mutusfa** [comment]
Have you tried moving/deleting your profile.bin from saves folder?

Seems to have helped for some linux guys that kept getting segfaults https://github.com/long-war-2/lwotc/issues/829

**Comment by MONST3R12** [comment]
> Have you tried moving/deleting your profile.bin from saves folder?
> 
> Seems to have helped for some linux guys that kept getting segfaults #829

Thanks for the hintni was planning on starting a new campaign once the mod gets more developted if it ever happens again ill try that out

**Comment by copyrite** [comment]
Closing due to age. Reopen or post a new one if issue persists with newer versions.
