### ISSUE TITLE
Game time-out upon killing Chosen

### ISSUE THREAD

**Issue by Letheron** [long-war-2/lwotc#1119]
I can't figure out why the game stops working after I kill the warlock, it's my first encounter with him on a supply mission and after I defeat him the game stops running.

I would attach the save file but it's unsupported, any help would be really appreciated, so far I've tried killing him with different units multiple times but it keeps causing the same issue. Because of the red screens it's the error due to hang and I don't know enough to get it resolved

**Comment by Grobobobo** [comment]
add the following launch parameters to your game: -noRedScreens -review
