### ISSUE TITLE
suggestion: description of missions and trap mission

### ISSUE THREAD

**Issue by daruperez** [long-war-2/lwotc#1120]
hi, 
suggestion: indicate the different missions: liberation, UFO and obtain data

the trap missions: indicate the mission as "It is possible that the mission is a trap ..., but the reward may be worth it" ..., the reward to be obtained could be doubled, or other type of reward...

**Comment by daruperez** [comment]
Ambush missions can be set...
that come out according to level...

**Comment by wdanny69** [comment]
liberation missions ufos etc now have a description noting them

trap missions do not and would kind of defeat the purpose of them being traps
