### ISSUE TITLE
No Income

### ISSUE THREAD

**Issue by RaynorCZE** [long-war-2/lwotc#1122]
Hello, 

First of all I would like to thank you and all people who has been assisting to make this mod possible.

but now to the issue.
I am Having (I guess) Bug when on World map it shows me My income as +0 even with 2 sectors captured, also when I have been choosing the sector to capture it showed me "Additional income: 0". Is it new feature from one of the latest version? Or maybe is it because of some of the mods I am using? 

Adding my load order to review.

Thanks in Advance

Load Order
https://docs.google.com/document/d/1SAoyxeLdaAE9bXbRlehL9NTA0xiILWFMw_s1hRLyFmg/edit?usp=sharing

**Comment by RaynorCZE** [comment]
Ok after first supply drop, income came back UP, I don't know why but hey it seems fixed

**Comment by dpstafford** [comment]
What are your resistance personnel doing? Need to switch them over to gathering supplies.On Sep 16, 2020 2:15 PM, RaynorCZE <notifications@github.com> wrote:
Ok after first supply drop, income came back UP, I don't know why but hey it seems fixed
