### ISSUE TITLE
[LWOTC] Whiplash isn't a free action

### ISSUE THREAD

**Issue by Pfannen** [long-war-2/lwotc#1125]
The Skirmisher's Whiplash is listed as a free action but will end your turn as if it were a full attack.  Maybe this was intentional, but if it was it's currently listed as a free action which is erroneous.  Also, I can't find any kind of wiki specifically for LWOTC over LW2, so I don't know how to check which of these issues is the real one.

**Comment by wdanny69** [comment]
Hello. in lwotc the whiplash is not free anymore so that description is outdated. How it functions now is that it costs one action and also non-turn ending like justice/wrath.

**Comment by Grobobobo** [comment]
Working as intended.
