### ISSUE TITLE
Chosen Warlock Suggestion

### ISSUE THREAD

**Issue by youporkchop5** [long-war-2/lwotc#1129]
so here’s an idea: why not give the chosen warlock an aoe mind control. In compensation you can break mind control from the warlock by dealing enough damage or using a flashbang to break his concentration. 

You’d have to deal a certain percentage damage (so that it scales with upgrades) to his health to break the concentration or you can flashbang him which while it won’t disorient or prevent him from using his other abilities it will break the mind control.

You could also keep the daze effect solely for the warlock since I think it makes sense for him and is also pretty threatening with upgrades as it chains to other soldiers when he uses mind scorch

I feel like both these would definitely make him a bit scarier even if they are a bit easy to counter

I think it would be interesting if you really pushed the support chosen angle by giving him mostly “harmless” abilities if he was on his own but when he has backup they become very threatening since you have to divide your action economy between attacking him, clearing the negative status effects or killing enemies. Would make for some tough descisions I think

Also make him able to summon allies, I know you’re removing that ability from some chosen, but if anyone should be able to summon it’s the warlock, and he should spawn more enemies than usual, like 2 each use of summon

What’s your opinion on my ideas?

**Comment by daruperez** [comment]
They seem too difficult to me. Now I try to avoid their missions

**Comment by copyrite** [comment]
3 years later, the Chosen Warlock has gone through a rework that emphasizes his summoner/support side. I think this issue has now been completed in spirit, at least.
