### ISSUE TITLE
Smash and grab crashging to desktop

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#113]
[smashandgrab.zip](https://github.com/long-war-2/lwotc/files/3095228/smashandgrab.zip)
Attached is the file that it is happening on on. This is happning even with all other mods except LW2 and the highlander selected. This happens every time the mission load is attempted.

**Comment by pledbrook** [comment]
This loaded fine for me with my limited set of mods. Perhaps get someone else to test it on Windows?

**Comment by jmartinez989** [comment]
Hmm that is weird. Will see if I can get a friend to test it out. Could have just been a fluke of a mission. As stated all other smash and grabs have worked fine.

**Comment by jmartinez989** [comment]
Ok so yeah I spawned a smash and grab and was able to start it. Not sure what the deal was. Maybe just a fluke. Not sure what to call this one. Was even able to load it with all of my mods. Will leave it up to you if you want to just close this and bring it up again if it happens.

**Comment by pledbrook** [comment]
Two people have failed to reproduce from the save file, so closing for now.
