### ISSUE TITLE
Replenish Resistance Operatives 

### ISSUE THREAD

**Issue by dpstafford** [long-war-2/lwotc#1131]
One region came to have zero living operatives.  Sure, I must have missed a retaliation mission or something.  Is there any way to get even one new operative so to begin repopulating?   Yes, I could scan for a prisoner rescue mission.  But I have since liberated the region, and now it will sit forever with no operatives?

Some crazy suggestion.
1) a successful liberation should auto repopulate the region with a full slate of operatives?
2) Or maybe empty regions could a have a chance to generate an operative who could then be set to recruiting?
3) Or maybe there is already a solution to this that I just don't know about yet....?

**Comment by youporkchop5** [comment]
soldiers advisors recruit

**Comment by dpstafford** [comment]
I an aware.  And I always had a soldier in there.

However, I can now report that a operative did finally recruit into the empty region!   I am happy!!

It's a long way to rebuilding the haven, but then it is a Long War ......

**Comment by Grobobobo** [comment]
Not a bug.
