### ISSUE TITLE
suggestion: put button to remove soldier  or limited recruitment time

### ISSUE THREAD

**Issue by daruperez** [long-war-2/lwotc#1132]
Hi,

Is there a mod that does that?, 

I have many soldiers that I will never recruit, Could you add a button to eliminate the soldier?

![image](https://user-images.githubusercontent.com/56190157/95561686-60d68b80-0a1b-11eb-94cb-a00010b3020c.png)

**Comment by copyrite** [comment]
Looks like a scrollbar has been added sometime in development, I don't think anyone will bother with further additions.
