### ISSUE TITLE
Can't loot crates on smashNgrab mission

### ISSUE THREAD

**Issue by Dman883** [long-war-2/lwotc#1133]
Can't loot crates on smashNgrab mission Restarted several times, both the mission and the game. No option/icon to activate crates. Not sure how to list my active mods.

**Comment by pledbrook** [comment]
If using AML, you can go to the "Profiles" tab and then select the "Save" button in the top right to export the list of mods as a text file. There are no other reports of this specific issue, so putting it down to either mods or a problematic installation.
