### ISSUE TITLE
Covert Risk percentage disappeared and all tasks except Intense Training have High Failure

### ISSUE THREAD

**Issue by Yumetix** [long-war-2/lwotc#1134]
As described in title, however there was no issue before sometime around June it just happened at one point.

**Comment by pledbrook** [comment]
Did you install a new mod that added the Community Highlander from Steam by any chance?

**Comment by Yumetix** [comment]
None that I know of, at least in my AML it shows that only 1 Highlander (the version downloaded here) is enabled.

**Comment by pledbrook** [comment]
If you'd like help in diagnosing the issue, I recommend heading over to [our Discord server](https://github.com/long-war-2/lwotc/wiki/New-Player-Resources#discord). Also note that if you have the Chosen enabled, they may be increasing the risk chances as one of their activities.
