### ISSUE TITLE
Fix intro loading scene for infiltration missions

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#114]
Currently, the mission loading screen with Bradford briefing shows the skyranger interior, but it should technically be in the room with the dog (read: faceless) photo, since the squad is already there for some time and not being deployed currently. 
Also, in case multiple missions are infiltrating, the skyranger is loaded with a different squad than the one that is to appear on the mission being loaded (usually it is the squad you last did a mission with)

**Comment by pledbrook** [comment]
See [this commit](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/commit/36906fa5614fd2f17b3044a12416655075e4f463) in Strategy Overhaul for implementation of the first bit.

For the second, see [this bit of code](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/3ebba1164d42290935ca884b5662b2adad15ea47/CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc#L625-L628).

**Comment by ansabalirai** [comment]
BTW, have you noticed that for rendezvous missions, it is a quick response mission and the avenger actually flies to the relevant region before the mission starts loading (which is not the case for infiltration missions). So, maybe dropping out of the skyranger for rendezvous is ok. In my head, the justification is that you need skyranger to quickly transport rebels and haven advisor to the meeting site since it is quick response.
I am splitting hairs though and keeping same behavior as LW2 is totally ok :)

**Comment by pledbrook** [comment]
Just as I was adding Rendezvous to that comment, I was actually wondering whether it was a drop in or walk in mission. Will have to check YouTube once again.

**Comment by pledbrook** [comment]
Rendezvous is a walk-in mission. It is weird that the Avenger goes there, but more importantly, the Skyranger does not. So if the Skyranger doesn't go there, what are they zipping down from?

**Comment by pledbrook** [comment]
The wrong squad on the Skyranger should be raised as a separate issue.
