### ISSUE TITLE
M3 gunners don't use Traverse Fire

### ISSUE THREAD

**Issue by GafrieGithub** [long-war-2/lwotc#1152]
I am fairly certain that there is something wonky with M3 gunners AI. They have Traverse Fire ability, but not once have I seen them shoot twice in a turn. They always choose to hunker/OW after the first shot (which is AdventRedFallbackAction behaviour, but I don't know why it is chosen instead of preceding LWAdventGunnerRedLastAction). 

The attached save file have single M3 gunner opposing the squad. By simply skipping turns I allowed him to shoot me for several turns in a row and he never shot twice. 

[save_Save_29.zip](https://github.com/long-war-2/lwotc/files/5506650/save_Save_29.zip)

**Comment by pledbrook** [comment]
Should be fixed by above commit from Nilch.
