### ISSUE TITLE
Negative hack scores means soldiers can't hack objectives

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#1156]
If a soldier has been wounded through redfog, his hack can drop below 0. This prevents them from being able to hack an objective.

Solution (?): Clamp hack to 0, rather than allowing negatives.

**Comment by GrouchPotato** [comment]
This seems.... realistic.

So all your soldiers' brains are too zapped to hack at all... looks like it's time to evac out and call the mission a failure.
