### ISSUE TITLE
Cannot train a psi operative using a controller. Have to use mouse. 

### ISSUE THREAD

**Issue by destroyer11687** [long-war-2/lwotc#1165]
Just as the title states, when training a psi operative or training a rookie, the button does nothing when pressing “A” on the controller. I have to go to main menu change input to mouse then go back into game to train psi unit.

I am using dev build 20.1.

**Comment by kdm2k6** [comment]
That's strange; I just tried it on an old save, but using an up to date LWotC and highlander, and I believe it works.
Are you using the following mod : https://steamcommunity.com/sharedfiles/filedetails/?id=2098062078 ? My guess is that this is the problem, as it provides controller support for the "no drop down list" mod.

**Comment by destroyer11687** [comment]
> Are you using the following mod : https://steamcommunity.com/sharedfiles/filedetails/?id=2098062078 

Are you saying I should be using this mod? Because right now I'm not using it.

**Comment by kdm2k6** [comment]
Just do it 👍 
Then let me know if it fixes the problem.

**Comment by destroyer11687** [comment]
Ok, will do! Thanks for the help. I'll post on here if that doesn't clear it up.

**Comment by kdm2k6** [comment]
Please post here even if it does work, just so I know there are no problems with it.
Thanks.

**Comment by destroyer11687** [comment]
Ok, will do. I won't be able to take a look until later today, but I'll be sure to post an update once I do.

**Comment by kdm2k6** [comment]
No problem. Thanks.

**Comment by destroyer11687** [comment]
Hey, just checked it out and it works! Thanks...it turns out I had the non-wotc version of this mod installed. Removed and installed the right version and it works.

**Comment by kdm2k6** [comment]
Excellent! Thanks for getting back to me.
