### ISSUE TITLE
Rapture is first tier xcom row on Templar

### ISSUE THREAD

**Issue by LogunovAV** [long-war-2/lwotc#1167]
![image](https://user-images.githubusercontent.com/71711739/100035071-61ca4d80-2e0e-11eb-84df-76df1ccd10d0.png)

version: Dev 21.5
Rapture is on the first tier inside xcom row. I don't think it's a place for it, posted on discord server, got an answer that it isn't the place for it.

**Comment by Grobobobo** [comment]
It's an autopistol skill, so yes, it is a place for it.
