### ISSUE TITLE
 gauntlet flamethrower only no rockets

### ISSUE THREAD

**Issue by Pyrobladeich** [long-war-2/lwotc#1168]
My technicals and rocketeers only have flamethrowers for their gauntlets in the secondary slot. Is it supposed to be that way?

**Comment by pledbrook** [comment]
No. Most likely reason is a mod conflict of some sort. Are you using LW2 Secondary Weapons?

**Comment by Pyrobladeich** [comment]
yes [WOTC] LW2 Secondary Weapons by shiremct.

**Comment by pledbrook** [comment]
Try disabling that mod

**Comment by Pyrobladeich** [comment]
yea that one is as requirement for RPGO I might just have to deal with it if that mod is the issue.

**Comment by ChrisTheThinMint** [comment]
RPGO changes the gauntlet to only have one flamethrower charge by default. You need skills in the Purifier/Rocketeer specializations to unlock it's full potential.

**Comment by copyrite** [comment]
Resolved as a mod conflict or mod issue.
