### ISSUE TITLE
Floating Head Enemies

### ISSUE THREAD

**Issue by aondiar** [long-war-2/lwotc#117]
When reinforcements were called into a mission (via teleport), the Advent Sentry appeared as a floating trooper head without a helmet. However, when i saved the game so I could upload it, upon reloading the game the issue fixed itself.

Other than Long War 2 [WOTC] and X2WOTCCommunityHighlander, the only mod i am running is Evac All.

**Comment by MajorEvil** [comment]
I also had the exact same issue today in an advent retaliation mission. Except this time it was with the advent sergeants. In this case though, there were a lot of corpses all over the floor in close proximity to the evac lol. I killed 55 advent in the mission. That probably explains a lot! I must have killed 40 advent before the sergeants started showing up with floating heads. I will do an edit of this post and post the yt link of the recording I got off that mission when able. That way you can better see what happened.

**Comment by jmartinez989** [comment]
So this seems to only apply to RNF units and in particular only the Advent RNF units that were not in the vanilla WotC (i.e. anything not a trooper, officer, purifier or priest). 

Also if you save and reload the file the enemies will then have their models restored. It seems to have something to do with not updating the models for those RNF units.

**Comment by pledbrook** [comment]
I've reproduced with this save:

[save_FloatingHeadRNFs.zip](https://github.com/long-war-2/lwotc/files/3218169/save_FloatingHeadRNFs.zip)

Just need to end the turn and see what happens with the reinforcements.
