### ISSUE TITLE
No chosen on black site dev21.5

### ISSUE THREAD

**Issue by Arubiano83** [long-war-2/lwotc#1173]
[save_No chosen on blacksite.txt](https://github.com/long-war-2/lwotc/files/5599319/save_No.chosen.on.blacksite.txt)

Changed filetype to txt to upload it.
But as titel says, no chosen on blacksite.

**Comment by pledbrook** [comment]
Fixed by [this commit](https://github.com/long-war-2/lwotc/commit/051ed9bf8cd0598d832e56ca7233542c355b2bd0)
