### ISSUE TITLE
Rescue VIP mission crashes consistently on load

### ISSUE THREAD

**Issue by aondiar** [long-war-2/lwotc#118]
This seems to crash consistently every time I attempt this mission.

Steps to reproduce:
1) Load game, go to world map and scan with avenger until Launch or Abort mission appears (Operation Driving Gods in West Asia, 99% infiltration)
2) Launch mission, after the brief load in screen, the game crashes when bringing up the tactical control UI.

[save_LWOTC Game.zip](https://github.com/long-war-2/lwotc/files/3098525/save_LWOTC.Game.zip)

Other than Long War 2 [WOTC] and X2WOTCCommunityHighlander, only mod I am running is EVAC All.

**Comment by pledbrook** [comment]
This crashes at a very similar point to #103, so I suspect they're related, if not the same bug.

**Comment by pledbrook** [comment]
Can confirm this is crashing at the same place in the code as #103
