### ISSUE TITLE
Shellshocked not procing on Assassin

### ISSUE THREAD

**Issue by Swarbs1982** [long-war-2/lwotc#1196]
[save_Assassin bug.txt](https://github.com/long-war-2/lwotc/files/5701595/save_Assassin.bug.txt)

On a protect the datatap mission, Assassin spawned next to the datatap rather than the squad. Not sure if that's WAD - seems harsh to put the Chosen amongst the rebels, particularly if there'd only been 3-4 of them.

Rebels throwing grenades at the Assassin on protect the datatap mission don't proc shellshocked. Makes it almost impossible to keep the relay safe, as she runs straight to it and slashes for 3 dmg each turn.

Also not sure the reaper vulnerability is procing correctly, seems to be inconsistent on this mission

**Comment by MiserablePileOfBugs** [comment]
It's the same for the warlock. I had this in two different missions. 

Also using the flamethrower procs his ability that gives him ablative hitpoints. I don't know if it's intended but all this makes him a really though opponent to kill.

**Comment by pledbrook** [comment]
Chosen no longer get weaknesses other than the adversary ones.
