### ISSUE TITLE
bug: No soldiers to rescue. Can't go back

### ISSUE THREAD

**Issue by daruperez** [long-war-2/lwotc#1198]
hi

If you don't have soldiers to perform the rescue then you can't go back to the main screen

![image](https://user-images.githubusercontent.com/56190157/102523852-6d6d0500-4098-11eb-88ce-293ad1ecf43e.png)

**Comment by pledbrook** [comment]
Known issue. Will be fixed in next patch release (22.2) as soon as that's ready. Hopefully should be soon.
