### ISSUE TITLE
Step 4 in download

### ISSUE THREAD

**Issue by Endwolf** [long-war-2/lwotc#1200]
It's not really very clear for me how to make sure there are at least two paths to mod directories - one for the workshop mods, the other for local mods.Where do i do that in steam the picture is not much help to me.

**Comment by cptnhotsauce** [comment]
Local mods like LWotC should be kept in XCom2's install directory (typically \steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods). You should be using the Alternative Mod Launcher, in which case open up Options>Settings to add the WotC mod directory. You can add additional mod directories by clicking Add, then add the directory.
![Screenshot 2020-12-21 155913](https://user-images.githubusercontent.com/47469720/102821772-a6152300-43a5-11eb-9119-2d071565d08b.png)
![Screenshot 2020-12-21 155941](https://user-images.githubusercontent.com/47469720/102821782-aad9d700-43a5-11eb-8985-215e7cbf3a9c.png)

**Comment by Quikcksilver** [comment]
Within the alternate mod launcher,  you go to the settings. In there it should show something almost exactly like the picture.

**Comment by copyrite** [comment]
Closing as no longer relevant, as the mod is on Workshop.
