### ISSUE TITLE
LWOTC Gatecrasher crashes

### ISSUE THREAD

**Issue by Veracity670** [long-war-2/lwotc#1205]
Hi,

I have downloaded and enjoyed playing LWOTC for the past 4 weeks. 

After recently loading Musashi's dual wield mod and associated mods the game stopped working. Removing the mod did not restore game function.

I have followed the trouble shooting guide to get a fresh load of LWOTC, re-verified the game cache, checked all file paths for LWOTC and Beta X2 Community highlander, deleted documents/xcom-wotc/config, removed profile.bin from savedata. Used AML to launch the basic set of LWOTC mods:
[Engine.XComModOptions]
ActiveMods=LongWarOfTheChosen
ActiveMods=X2WOTCCommunityHighlander
ActiveMods=robojumperSquadSelect_WotC
ActiveMods=WOTCRevertOverwatchRules
ActiveMods=BetterSecondWaveSupport
ActiveMods=ModConfigMenu

[IniVersion]
0=1608785549.000000. 

I have re-established the load page with the LWOTC button.

The basic LWOTC launches until the gatecrasher mission which then freezes mid-loading and crashes out to desktop. An Xcom2.exe error has been noted - "unknown software exception error (0x00000001) at location 0x00007FFCF7D83B29"

Any guidance on this issue is appreciated

**Comment by dpstafford** [comment]
I have the same thing happening to me.  But only under the following circumstances.   Having the MOD Quick Soldier Info installed AND having no one in my character pool.   (I have to disable the mod, for Gatecrasher mission, then reenable afterwards).

**Comment by Veracity670** [comment]
Thanks for replying, FYI I have LWOTC working again after dropping the graphics to minimum and config cache clear out. It appears to be a memory problem as the Advent HQ raid (2+ hrs) generates a screen freeze after successfully completing the mission.

**Comment by Tomas-Sandnes** [comment]
Regarding Quick Soldier Info: Turn off the option of taking soldier photos in missions, and it will not crash the game anymore.

**Comment by Veracity670** [comment]
I have re-run the Advent HQ mission 3 times to the end and the freeze/crash issue arises whether its end mission on a straight run thru or loading from a savegame file. I'm loading the error log, if anyone can see what's glitching it would be appreciated.

System
CPU i7-6700Hq@2.6Gz
RAM 16Gb
NVIDIA GeForce GTX 960M

Error Log files
[XCom-CL374751-2021.01.18-16.16.32_Logfile.zip](https://github.com/long-war-2/lwotc/files/5833042/XCom-CL374751-2021.01.18-16.16.32_Logfile.zip)
[Launch-backup-2021.01.19-07.30.54.zip](https://github.com/long-war-2/lwotc/files/5833060/Launch-backup-2021.01.19-07.30.54.zip)

**Comment by dpstafford** [comment]
> Regarding Quick Soldier Info: Turn off the option of taking soldier photos in missions, and it will not crash the game anymore.

Started a new 23.1 game recently,  And the problem did not occur.  I didn't take any special precautions.

**Comment by copyrite** [comment]
Looks like the issues have been fixed, closing.
