### ISSUE TITLE
lwotc doesn't starts with Gatecrasher on Mac

### ISSUE THREAD

**Issue by silver645** [long-war-2/lwotc#1208]
Heyho everybody, thanks for this awesome mod.

I've been installing lwotc on my iMac (Mac OS Big Sur 11.0.1 (20B29)) up to the point where it shows the 'Long War (LWOTC)' button in the game. But when I press that button the games starts with the monument mission instead of Gatecrusher. Also I noticed that the option 'the chosen: enables the chosen' isn't showing in the advanced options when setting up the game.

This is what pops up when hovering over the right bottom cornver in the launch screen:
![image](https://user-images.githubusercontent.com/76750373/103311408-aa1df200-49f0-11eb-86c3-81f579826296.png)

Note: Long War2 Mod without the chosen expansion works but I hate the long loading times and the missing faction content.

What I've done for bugfixing so far without success:
- relaunch it several times
- deleted the config files in the 'mygames' directory parth
- disactivated all mods except for the 5 mods needed to start the game
- renamed the profile.bin file
- moved all savegames to a different folder
- finished the monument mission to see if it works afterwards. what's interesting is that the savegames created by the game  are have the description 'Sabotage ADVENT monument - Operation Gatecrusher 3/1/2035'

What else can I do?

**Comment by pledbrook** [comment]
I suggest joining our Discord. It's easier to diagnose issues and try things in real time rather than via GitHub. Plus there will be more people available to help.
