### ISSUE TITLE
bug: no reward, no rebels

### ISSUE THREAD

**Issue by daruperez** [long-war-2/lwotc#1209]
![image](https://user-images.githubusercontent.com/56190157/103375427-86cf7180-4ada-11eb-8431-4bffdf08e7b3.png)

![image](https://user-images.githubusercontent.com/56190157/103376514-21c94b00-4add-11eb-9224-67893bf5e2e0.png)

**Comment by pledbrook** [comment]
This was probably due to the bug with captured soldiers, now finally fixed.
