### ISSUE TITLE
Soldier defense value not showing up on armory ui screen

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#121]
Title pretty much describes it. I can fix it myself if I know where I edit. Actually I think I might be able to look at the mod that does this. If I find out how to do it then I'll do it myself.

**Comment by jmartinez989** [comment]
The code for this is in the vanilla LW2 folder which I have but not sure how it will interact. Going to try to implement it on my local build tonight.

**Comment by jmartinez989** [comment]
So I have this working but the problem is that I actually had to make the change in the UISoldierHeader class that is in the highlander. I guess I can get with robojumper about maybe doing a merge or pull request for it to the highlander.

**Comment by jmartinez989** [comment]
closing this. I will be creating an issue in the highlander repo for this to push the changes up to that.

**Comment by jmartinez989** [comment]
reopening this as we are going to not use the CHL modified implementation. Will look to implement via events if possible.

**Comment by jmartinez989** [comment]
@pledbrook so how do you feel about implementing this via the suggestion you gave me earlier where I add a bool attribute in the CHHelper class and then use that in the UISoldierHeader class to determine if we display it by creating an overloaded method for display soldier stats where the overloaded method signature just has the additional argument for defense. This way the original functionality is not lost.

**Comment by pledbrook** [comment]
Whatever fix is implemented should sort out #148 for the UISoldierHeader at least.

**Comment by pledbrook** [comment]
I think I'm going to defer this *yet again*. Doh! I'm sure I'll get round to it at some point...

**Comment by pledbrook** [comment]
With Defense no longer included in Not Created Equal, this is kind of irrelevant right now.

**Comment by pledbrook** [comment]
Defense is now 0 across the board, so no need to display it.
