### ISSUE TITLE
XComClassData.ini AbilitySlots often have 1 empty element at the end.

### ISSUE THREAD

**Issue by kdm2k6** [long-war-2/lwotc#1217]
Within XComClassData.ini, I think a lot of AbilitySlots have an extra 'none' ability at the end.

For example : 
```
+SoldierRanks=(AbilitySlots=((AbilityType=(AbilityName="RevivalProtocol", ApplyToWeaponSlot=eInvSlot_SecondaryWeapon)), \\
(AbilityType=(AbilityName="Sentinel_LW", ApplyToWeaponSlot=eInvSlot_PrimaryWeapon)), \\
(AbilityType=(AbilityName="CombatProtocol", ApplyToWeaponSlot=eInvSlot_SecondaryWeapon)), \\
(RandomDeckName="Tier1_XComAbilities"), \\
(AbilityType=(AbilityName="ReturnFire", ApplyToWeaponSlot=eInvSlot_Pistol)), \\
***_THE_COMMA_JUST_BEFORE_THIS_STATEMENT_CREATES_AN_EXTRA_ELEMENT***), \\
aStatProgression=((StatType=eStat_Offense,StatAmount=2), (StatType=eStat_Will,StatAmount=5), (StatType=eStat_Hacking,StatAmount=10), (StatType=eStat_HP,StatAmount=1), (StatType=eStat_Strength,StatAmount=0), (StatType=eStat_CombatSims,StatAmount=0))\\
)
```

I noticed that when you log `AbilityTree.Length` after setting it via :
`AbilityTree = Unit.GetRankAbilities(Column.Rank);`
you often get 6 even though there are 5 abilities for a given rank.

I'm not sure if this matters or not. I'm assuming these 'none' abilities are just skipped in code generally speaking.

This can be closed if it is a non-issue.

**Comment by pledbrook** [comment]
I'm not seeing that comma. I'd hoped they'd all been removed. See [here](https://github.com/long-war-2/lwotc/blob/master/LongWarOfTheChosen/Config/XComClassData.ini#L294). They definitely shouldn't be there as they will result in empty ability slots as you mention.

**Comment by kdm2k6** [comment]
Ahhh. I see now.

I'm working off an older 'master' still.
December 22, 2020 commit by you : Remove rogue commas in XComClassData.ini.
You beat me to it by a couple weeks. Good to know.
