### ISSUE TITLE
witcher: kidnap, too hard?

### ISSUE THREAD

**Issue by daruperez** [long-war-2/lwotc#1218]
Hi, 

The witch had a great time, I not so much..., is it normal?

![image](https://user-images.githubusercontent.com/56190157/104205982-4d2e2d00-542f-11eb-8c01-80da804a5ca2.png)

![image](https://user-images.githubusercontent.com/56190157/104206010-5919ef00-542f-11eb-9dd3-a7d0cb0cf597.png)

![image](https://user-images.githubusercontent.com/56190157/104206173-85ce0680-542f-11eb-9f97-6b57ca82843d.png)

![image](https://user-images.githubusercontent.com/56190157/104206204-8bc3e780-542f-11eb-8f82-0e734994ea03.png)

**Comment by MiserablePileOfBugs** [comment]
2 snipers, 2 rangers, 1 assault, 1 specialist, 1 gunner and 1 shinobi... Interesting team compo for a black site mission :)

Anyway, I doubt the Warlock was the issue here. He only kidnaps soldiers that fall unconscious.

**Comment by daruperez** [comment]
one behind the other... 1ºranger, 2ºspecialist, 3º assault, 4º shinobi, 5ºranger, 6ºgunner and snippers

I started the battle against 6 enemies..., control a drone, I join other 6 enemies joined including the witcher (away from my team)... 
Before they destroyed the drone, 5 chryssalid joined... i dead

What team is he wearing?

**Comment by copyrite** [comment]
Chosen no longer appear on golden path missions and the balance suggestion is also otherwise coming from a very old version at this point, I'll consider this closed.
