### ISSUE TITLE
Resistance MECs not controllable on missions

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#122]
Although Resistance MECs are added to team XCOM on haven missions where they're available, they don't have any actions because they aren't added to the primary initiative group. That should be done in [`LWTacticalMissionUnitSpawner.LoadResistanceMECsFromOutpost()`](https://github.com/long-war-2/lwotc/blob/master/LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTacticalMissionUnitSpawner.uc#L349). See [how it's done for liaisons](https://github.com/long-war-2/lwotc/blob/master/LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTacticalMissionUnitSpawner.uc#L451) for the solution.

Save file with Haven Defence mission available to test: 
[save_AUTOSAVE- Campaign 55, Mission 27.zip](https://github.com/long-war-2/lwotc/files/3101037/save_AUTOSAVE-.Campaign.55.Mission.27.zip)

**Comment by MajorEvil** [comment]
Further to this, I can confirm I also had this issue in Alpha 2.0. Here is another save file to test if you are interested: [Resistance Mech Autosave test Retalliation.zip](https://github.com/long-war-2/lwotc/files/3119495/Resistance.Mech.Autosave.test.Retalliation.zip)

**Comment by pledbrook** [comment]
Fixed
