### ISSUE TITLE
Str modifier on intel raids during chosenless camapign

### ISSUE THREAD

**Issue by Q-Chaos** [long-war-2/lwotc#1233]
Without chosen, raids are getting +3 str modifier instead of +1
This is the second time in the campaign, where intel raid in an str 3 region was light-moderate, which should be light.

**Comment by pledbrook** [comment]
Think this was fixed in [this commit](https://github.com/long-war-2/lwotc/commit/100000a650ab9124b9282d4a3eea29f06bb897db).
