### ISSUE TITLE
Reaper's silent killer ability pop-up - misinformation

### ISSUE THREAD

**Issue by ABCXYZQWE123** [long-war-2/lwotc#1235]
Every time you deal a killing blow to an enemy with reaper, a pop-up appears that shadow's duration was increased by 1 turn, regardless of was it actually increased or not. So it means you cannot know for sure if your reaper will be detected next turn, pop-up shows up 100% of time and in 75% trials it will be wrong. Also, there is no info about this 25% chance in the description of the silent killer. Can provide a save file to replicate the issue if needed.

**Comment by pledbrook** [comment]
The extension to Shadow duration has been removed now that the base duration is 2 seconds.
