### ISSUE TITLE
Cannot install LWOTC

### ISSUE THREAD

**Issue by digitCruncher** [long-war-2/lwotc#1241]
![image](https://user-images.githubusercontent.com/48256023/106442843-a7775680-64e0-11eb-917b-6bbee30f9c90.png)

I have followed the instructions here (https://github.com/long-war-2/lwotc/wiki/Installing-Long-War-of-the-Chosen) and have also gone through the troubleshooting process here (https://docs.google.com/document/d/1EEZqmzCQQoprh3sDFZQZyiuyRE8I_lsA7Z8pHTSRuzU/edit)

The troubleshooting document is a bit outdated (there is an additional required LWOTC mod that is available on the steam workshop, and the default launcher no longer works so the alternative mod launcher needs to be used). However I can start the game by deleting my 'My Documents' Config directory ( C:\Users\digit\Documents\My Games\XCOM2 War of the Chosen\XComGame\Config ), but that has the 'New Game' button. After that, I closed the game and tried to launch, but it just hangs on startup.

I have deleted all of the C:\Users\digit\Documents\My Games\XCOM2 War of the Chosen\XComGame directory, and have also tried using the Steam version of X2CommunityHighlander , but neither option works.

Attached is the log file on Launch. 
[Launch-backup-2021.02.02-00.58.15.log](https://github.com/long-war-2/lwotc/files/5903768/Launch-backup-2021.02.02-00.58.15.log)

There are a *lot* of error messages that appear, and it seems that lots of config files seem to be missing from the Steam Config directory, but I have installed and verified the files, but those missing files don't seem to be there.

**Comment by Arubiano83** [comment]
The mods folder is in the wrong folder. 
Should be: D:\SteamLibrary\Steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods

**Comment by digitCruncher** [comment]
Thanks. That was a silly mistake that took way too long for me to fix >.<
