### ISSUE TITLE
Game Crashes on Launch

### ISSUE THREAD

**Issue by kaosimmortal** [long-war-2/lwotc#1254]
Although I have gotten this game to work on other machines, I have been having a problem ever since I switched to my current desktop. Since then, launching on the downloaded files from Nexus Mods results in a game that does not respond or fully launch. Some playing around with files and with Steam has found that using Steam's version of the Community Highlander results in a game that makes it to the main menu and runs fine, but unit experience appears to only work by kills. If I unsubscribe to Steam's beta version, it goes back to crashing immediately. I have included an example log file of my most recent launch.

[Launch-backup-2021.02.13-17.31.07.log](https://github.com/long-war-2/lwotc/files/5976729/Launch-backup-2021.02.13-17.31.07.log)

**Comment by Dcruize** [comment]
You need to use the version of the Community Highlander that comes with LWotC. Step 2 of 'building or running the mod' shows;

"Either clone my fork of the X2WOTCCommunityHighlander repository or download the lwotc-dev branch from GitHub."

**Comment by Dcruize** [comment]
Use the version of the Community Highlander that comes with LWotC and make sure there's no other version.

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting

"Unsubscribe from the X2WOTCCommunityHighlander mod if you're subscribed to it. Don't worry, the version that comes with LWOTC (and is required by LWOTC) is backwards compatible with the version on the Workshop.

Download the LWOTC beta 3.1 zip file from Nexus Mods. This includes Long War of the Chosen and a custom version of the Community Highlander."

**Comment by kaosimmortal** [comment]
I had already unsubscribed to the mod, and have now checked all of the file locations for the steam version. I did notice that the LWotC Highlander was in my documents and so moved it to my C: drive where the rest of the game file are located. This did not fix my problem though. I had also downloaded the Highlander several times from the Nexus Mods location, with the same crash each time. The log seems to think that various objects have the same IDs, but I don't know what could be causing that or what its solution is.

**Comment by kaosimmortal** [comment]
I had already unsubscribed to the mod, and have now checked all of the file locations for the steam version. I did notice that the LWotC Highlander was in my documents and so moved it to my C: drive where the rest of the game file are located. This did not fix my problem though. I had also downloaded the Highlander several times from the Nexus Mods location, with the same crash each time. The log seems to think that various objects have the same IDs, but I don't know what could be causing that or what its solution is.

**Comment by RedLinesBurn** [comment]
u need the mod called "Mod Jam" otherwise the game won't run with LWotC active.

**Comment by pledbrook** [comment]
These are the wrong paths for the two mods:
> 0004.50] Log: Checking DLC installation for C:\Users\andre\Documents\my games\XCOM2 War of the Chosen\XComGame\mod\LongWarOfTheChosen ...
[0004.50] Log: IS INSTALLED : , YES
[0004.53] Log: Checking DLC installation for C:\Users\andre\Documents\my games\XCOM2 War of the Chosen\XComGame\mod\X2WOTCCommunityHighlander ...

Please read and carefully follow the installation instructions again. You may still have the wrong installation path. If you're still having issues, please join our [Discord Server](https://discord.gg/vv5yJF9) for help.
