### ISSUE TITLE
Geoscape Bug after killing warlock

### ISSUE THREAD

**Issue by Falcon8V** [long-war-2/lwotc#1260]
Hi,

is anyone in here, who can help me fixing my save game? I have a well know bug, on may 15, after i killing the warlock for the first time i hop on the worldmap, the cam snaps on the big red chosen avatar and i think it should trigger a cutscene or central text or something, but i stuck. time is running,i hear the music but nothing controlable so far.
in the last 24 hours i tried everything! loaded a earlier savegame, played again, unsubscriped all mods, looking for a broken mod or mod conflict, checked everything....i tried to force the game to skip that with console commands, cleared my config, verified my local data about 10 times, but everytime i stuck at the same point.

If i looking for it in google, i find a looot of similar Problems since vanilla, but i cant find a proper fix. Well we are in 2021, is there something i can do instead of start a new campaign? im afraid, starting new will end in this again at any time.

Greetings

This is a screenshot of my current view and installed mods:

https://prnt.sc/109dn7d

**Comment by Falcon8V** [comment]
after starting a new campaign with the same settings, the chosen were all introduced without problems. So, i guess it`s still a gamebreaking bug.

**Comment by pledbrook** [comment]
This is highly likely to be because you enabled Lost and Abandoned unintentionally. Did you start the very first mission (Gatecrasher) without a faction/hero soldier?

**Comment by Grobobobo** [comment]
Assumed it's caused by enabling lost and abandoned
