### ISSUE TITLE
Very buggy interaction between haven advisors and maybe Field Surgeon

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#1263]
A before and after screenshot:
![20210313120924_1](https://user-images.githubusercontent.com/54481962/111039962-831f6b80-83f6-11eb-8583-a2487e1d548b.jpg)
![20210313120659_1](https://user-images.githubusercontent.com/54481962/111039963-83b80200-83f6-11eb-8d1b-755ae0975679.jpg)

A haven advisor participated in a full retal mission. During this mission he had 4 base hp, was wearing predator armor and nanoscale vest, for a total of 9 hp. He also had an alloy plating and no third item.

During the mission, he took a light hit of 1 hp. I thought this would be fine, as 2 specialists with Field Surgeon were also on the mission. However, this causes his HP stat to glitch out.

As you can see from the "after" photo, he has entered a buggy state where: 1. He is wounded despite Field Surgeon. 2: He is displaying 3 HP, not 3/4 HP as it should be if Field Surgeon simply did not apply. 3. He seems to have permanently lost max HP.

I have seen soldiers losing max HP in previous versions and suspect something similar caused it, but did not observe it in detail before now.

**Comment by GafrieGithub** [comment]
The soldier did not lose max HP. He is displaying 3HP because he does have 3 out of 4 HP currently and that is how it is displayed. Not sure why you thought it should display "3/4".

The fact that Field Surgeon did not apply is a bug in current implementation indeed. Field Surgeon simply never applies to liaisons (or rebels for that matter) because they are added into the mission after the trigger to apply Field Surgeon to all allies happen, and the trigger only happen once. I might be able to fix this behavior, but it turned out trickier than I thought for reasons which are non-obvious to me.

**Comment by allenhu0912** [comment]
If you get a "conventionally" wounded soldier and examine them in the barracks, their HP will display 3/4 in red, rather than just a flat "3". This is most definitely not normal

**Comment by GafrieGithub** [comment]
I just checked and all of my wounded soldiers display only single value. So it is most definitely normal.

**Comment by allenhu0912** [comment]
You're right; but the salient issue is that this same guy was in a buggy state post-mission. He was auto-picked when choosing soldiers to infiltrate the next mission, but he was in the wounded stance, and I could not alter his loadout. Obviously it wasn't just a case of the game failing to apply Field Surgeon, it was actively confused about whether or not he was healthy.

**Comment by GafrieGithub** [comment]
I believe that is some separate bug in the code auto-selecting wounded soldiers. I've seen it doing that on occasion. But it doesn't have anything to do with Field Surgeon specifically.

**Comment by pledbrook** [comment]
So is this basically the same as #111?

**Comment by pledbrook** [comment]
Fixed by @GafrieGithub in [this commit](https://github.com/long-war-2/lwotc/commit/3306ca242be37655e13d78865eabc8c8c667c117).
