### ISSUE TITLE
Game Crashes after Clicking the any button 

### ISSUE THREAD

**Issue by RedLinesBurn** [long-war-2/lwotc#1270]
Here some logs?
[XCom-CL374751-2021.03.18-00.48.51_Logfile.log](https://github.com/long-war-2/lwotc/files/6167681/XCom-CL374751-2021.03.18-00.48.51_Logfile.log)
[Launch-backup-2021.03.17-20.59.30.log](https://github.com/long-war-2/lwotc/files/6167685/Launch-backup-2021.03.17-20.59.30.log)

**Comment by RedLinesBurn** [comment]
if any is having this problem after extensive testing i found that the most latest updated version of highlander on steam workshop is needed

**Comment by RedLinesBurn** [comment]
I've tested all mods and have come to the conclusion that it's this version of highlander trying to load maps that makes it crash. I've tried using the Highlander on Steam updated in October 2020 and it never crashes however it also won't level up soldiers.

**Comment by pledbrook** [comment]
It looks like you're using the Workshop version of the Community Highlander, which will not work. If you would like help troubleshooting, please ask on our [Discord Server](ttps://discord.gg/vv5yJF9). But I recommend carefully following the [installation instructions](https://github.com/long-war-2/lwotc/wiki/Installing-Long-War-of-the-Chosen) again.
