### ISSUE TITLE
No "Deep focus' for Templar

### ISSUE THREAD

**Issue by KeepMedicine** [long-war-2/lwotc#1271]
As in the title, th skill for Templar "Deep Focus" is eleminated. So Templar's maximum focus can only reach 2. Actually the new skill "Apotheosis " require 3 to use.

**Comment by Savancosinus** [comment]
"Deep focus" is granted by gauntlets now. Did you try to upgrade them?

**Comment by pledbrook** [comment]
As mentioned by Savancosinus, Deep Focus and Supreme Focus are on the upgraded versions of the gauntlets in LWOTC.
