### ISSUE TITLE
ADVENT Drone Control and building transparency issues

### ISSUE THREAD

**Issue by RogueSeeker24** [long-war-2/lwotc#1276]
I know XCOM 2 has some noticeable issues with tabbing between soldiers in motion at different elevations, sometimes resulting in no more wall/roof transparency. I'm noticing almost constantly now that whenever I take control of an ADVENT Drone, this issue usually triggers. I'll try to run a few more tests to be sure before posting the saves where it happens. I don't know if you'd need saves when the issue is already occurring or just before?

I do feel I need to clarify I'm running a lot of other mods in parallel, but nothing like ABBA that I know changes units outright. They're mostly QoL and aesthetic mods, but I do have a few like "Hack Plus", "Nobody Saw That" (so far seems to work) and "Iridar's SPARK Arsenal".

Finally, thanks to the team for making this possible. It's been a blast to play LWOTC and I hope my reports help even a little bit.

**Comment by McTrevor79** [comment]
Caused by the camera of Quick Soldier Info.

**Comment by RogueSeeker24** [comment]
> Caused by the camera of Quick Soldier Info.

Thanks for the quick reply. I went back to the steam page and saw quite a few people were having issues (some even crashes) that I never saw in LW2 or base WOTC, but it also seems nobody's found a fix for it.

**Comment by Grobobobo** [comment]
Not a lwotc issue.
