### ISSUE TITLE
Possible oversight: Soldiers do not gain AP at MSGT

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#1279]
See title. I suspect this is an oversight as base game soldiers had one less max rank/level than in LWOTC, so AP progression on MSGT was neglected. This means, for example, that an average comint MSGT gets 35 AP, not 40. Would probably be more intuitive to either add AP progression to MSGT, or smooth out current AP progression across 8 ranks rather than 7.

**Comment by Grobobobo** [comment]
gaining 5 points per rank should be for guys with below average comint, average should have 6 across 7 promotions: LCPL, CPL, SGT, SSGT, TSGT, GSGT, MSGT. = 42. Soldiers don't get AP on squaddie.

**Comment by pledbrook** [comment]
As far as I'm aware, MSGT gets an AP increase just like all the other ranks from LCPL.
