### ISSUE TITLE
Chosen Assassin - Suggestion

### ISSUE THREAD

**Issue by grobertson1970** [long-war-2/lwotc#1282]
Just completed third try at Chosen Stronghold for Assassin.  The combination of blood thirst, prime reaction, Soulstealer, and not being able to be critically hit makes this mission impossible.  With only 5 squad members we were unable to do damage and prevent squad members from being hit by the Assassin.  Once a squad member is hit, it is over.  The Assassin gets health back, does more damage, and the squad is unable to keep up with its damage escalation.  The injured squadmate (or a newly injured squadmate) is then kidnapped and there is nothing that can be done.  Kidnap had previously been something Chosen did in melee range.  Being able to kidnap from a distance seems unreasonable.  We believe the Chosen should be a challenge with a method of managing their traits and skills but this seems a bit too much.  Perhaps lose the immunity to being critically hit?  Or keep that and lose the prime reaction?  Bottom line, it seems the Assassin needs some more rebalancing.  Thank you so much for the work on this mod! It's amazing!

**Comment by allenhu0912** [comment]
You are playing on an older version. Chosen on recent versions cannot heal in any way, so they can't become unkillable like this anymore.

**Comment by ctm98** [comment]
I am on the most recent version and can confirm Assassin still regains health every turn and is practically impossible to beat. Wipes my squad every time and is seriously OP considering they get a shot every time i fire on her. Also the fact they cannot be stunned or disoriented.. Is there anyway to make her easier in settings as it is ruining the game for me? Even on rookie shes a monster.

**Comment by Grobobobo** [comment]
There was a warning regarding updating that even though the strengths would be removed from the pool, chosen that already gained them would keep them, which is why updating on existing campaigns was not recommended. Regardless, this is outdated.
