### ISSUE TITLE
Chosen Hunter showing up on GOP (dev 25) 

### ISSUE THREAD

**Issue by DerAva** [long-war-2/lwotc#1286]
Chosen hunter showed up on a Jailbreak mission - should only show up on retals and story missions in dev 25.

He was also T4 at FL 9.

Save from geoscape before the mission and from within the mission attached. 

Campaign was previously updated from Dev build 23 at FL 4.

Mod list: https://steamcommunity.com/sharedfiles/filedetails/?id=2389520045

[hunter.zip](https://github.com/long-war-2/lwotc/files/6287146/hunter.zip)

**Comment by pledbrook** [comment]
Hopefully [this commit](https://github.com/long-war-2/lwotc/commit/63492b3240b7819d2c9fd6e1cd9cf3148a1c13ec) will prevent a the effects of the bug. I tried the strategy save with dev 26 and launched the mission. No Chosen appeared.
