### ISSUE TITLE
Ruler, no ruler

### ISSUE THREAD

**Issue by Arubiano83** [long-war-2/lwotc#1297]
Prototype dev26. Save right before ruler troop column.

[save_No ruler.zip](https://github.com/long-war-2/lwotc/files/6415585/save_No.ruler.zip)

**Comment by pledbrook** [comment]
`Should be fixed by [this commit](https://github.com/long-war-2/lwotc/commit/8885beb8923fec0cb90f30d2ecbedf11a04b9d56).
