### ISSUE TITLE
Evac only the wounded 

### ISSUE THREAD

**Issue by sreevatsank1999** [long-war-2/lwotc#1302]
It will be great if the supporting soldier carrying the incapacitated can return back to the battlefield to assist in battle or carry more incapacitated soldiers to safety.

**Comment by copyrite** [comment]
There is a mod for that: [Phantom Evac](https://steamcommunity.com/sharedfiles/filedetails/?id=1748331160). It's unlikely that this functionality will be integrated into LWOTC.
