### ISSUE TITLE
Volt use crashes game

### ISSUE THREAD

**Issue by DerAva** [long-war-2/lwotc#1303]
Using Volt on a large group of advent repeatedly crashes the game. Not clear if it's the number of enemies, the fact that some of the enemies are out of line of sight or other factors contributing here.

Clip from stream where this was reproduced multiple times: https://www.twitch.tv/videos/1016652521

Save attached

Mod list for save: https://steamcommunity.com/workshop/filedetails/?id=2389520045

[save_voltcrash.zip](https://github.com/long-war-2/lwotc/files/6447628/save_voltcrash.zip)

**Comment by pledbrook** [comment]
Closing until it's reproducible without Less BS Yellow Alert.
