### ISSUE TITLE
the old green Guerilla ops missions appearing with impossible timers 

### ISSUE THREAD

**Issue by hazerddex** [long-war-2/lwotc#1306]
I'm not sure if it's a bug, but instead of the building icon i get the green soldier icon after the two LW mission infiltration missions, but they still have the  long war 2 mechanic except the time is like 1 day or 12 hours which makes any time except 1 person impossible to use for it and 1 soldier can't beat 7-9 enemies alone. especially early game rookies.

**Comment by TwinuX** [comment]
Almost all missions in LW2 are detected through rebel intel jobs, with varying timers based on a mix of rebel intel generation and RNG. I'd recommend brushing up on these mechanics, then reconsidering whether there is a bug here or just a bit of misunderstanding. 

https://www.youtube.com/watch?v=4XSLjOd6WIs provides a pretty decent overview of the haven mechanics.

**Comment by pledbrook** [comment]
Assuming this is a misunderstanding of how LW2/LWOTC
