### ISSUE TITLE
How to install Dev builds

### ISSUE THREAD

**Issue by UMebius** [long-war-2/lwotc#1308]
I know how to install zips with several GBs large by following instructions written on the wiki, but I'm not quite sure how to install the several MBs large zips with minimal files in it. I really wanna get my hands on Dev build 26 and try things out. Can anyone give me a few pointers ? Thanks a lot.

**Comment by TwinuX** [comment]
Copy any of the folders inside the patches to your LongWarOfTheChosen directory. It'll overwrite any of the existing files that need changing.

**Comment by UMebius** [comment]
> Copy any of the folders inside the patches to your LongWarOfTheChosen directory. It'll overwrite any of the existing files that need changing.

I wasn't sure if this is all it takes cause I saw the instructions writing things like "cooking the build" and stuff. Now I feel stupid asking about this. Thank you very much for your help !
