### ISSUE TITLE
The game dont start

### ISSUE THREAD

**Issue by Gabrielarada** [long-war-2/lwotc#1309]
Idk why  but the game doesnt start 
![image](https://user-images.githubusercontent.com/84391711/118657201-a59c7f00-b7c1-11eb-9205-a720522b6bb9.png)
Those are the only mods that I am using and its not working do I need something else?

**Comment by pledbrook** [comment]
Please join our [Discord server](https://discord.gg/ZCWq8QX) for help with troubleshooting.
