### ISSUE TITLE
Templar first promotion screen immediately after Gatecrasher doesn't display properly

### ISSUE THREAD

**Issue by cicero225** [long-war-2/lwotc#131]
I am not running any mods but LWOTC.

[save_WeirdTemplarPromotion.zip](https://github.com/long-war-2/lwotc/files/3115974/save_WeirdTemplarPromotion.zip)

Instructions to reproduce: Kill the remaining trooper (a single Templar rend will do) to end the mission, then attempt to promote the Templar from the post-mission screen.

Bug: instead of getting a promotions screen, get this empty image and have no ability to promote a templar.
![20190425013438_1](https://user-images.githubusercontent.com/1408556/56722098-2e3bb480-66fb-11e9-8a25-770dd16a390d.jpg)

I suspect it's trying (and failing) to load the cutscene where Geist tells you about Templar. If you go back to the avenger and visit the Templar in the armory, this cutscene will play and then the promotion screen can be accessed as normal.

**Comment by pledbrook** [comment]
Known issue. The cinematic is the old LW2 one, which doesn't account for faction soldiers, which have a different soldier class template. I opened that cinematic file once and had no idea what was going on. Not a priority right now, but something I would like to get fixed at some point.

**Comment by cicero225** [comment]
Ah, sorry about the duplicate. I didn't find that previous issue in search...

**Comment by cicero225** [comment]
Sorry, didn't realize my previous comment would reopen this somehow. I'll close this again.

**Comment by pledbrook** [comment]
Yes, there are two buttons. One just to comment, and the other to reopen and comment.

And I'm glad you created the new issue. It really needed to be separated out from this one. Particularly as this one isn't very descriptive about the how the problem appears to players.

**Comment by pledbrook** [comment]
Wait, what? Erm, sorry, I got confused and thought we were on the old issue. This one needs to stay open please!

**Comment by pledbrook** [comment]
Closing in preference to #51 .
