### ISSUE TITLE
Skill tree orders swapped for Faction Heroes (modded)

### ISSUE THREAD

**Issue by UMebius** [long-war-2/lwotc#1312]
I have been using Proficiency class mods by shiremct to replace Reaper and Skirmisher. However their default skill trees always have their Squaddie and Major (7 skills not 8) skills swapped. I tried tweaking Reaper configs and make another tier for them, but skill trees order would become 61234785 instead of normal 1 to 8. Haven't tried adding another tier for Skirmisher but I bet it'd be pretty similar. Did recent patches did anything to Reaper and Skirmisher's skillsets cause the mod worked fine several patches earlier, and down its core its just another class mod (I think)

**Comment by pledbrook** [comment]
Dev build 26 reworked all the faction soldiers' ability trees.
