### ISSUE TITLE
Everything is in the right place but I cannot get the LW to show up in the mod list

### ISSUE THREAD

**Issue by Lipshawitz** [long-war-2/lwotc#1313]
![Help!](https://user-images.githubusercontent.com/84539290/119032660-6ebd9900-b97a-11eb-92f5-872e490d9ff4.jpg)

**Comment by ansabalirai** [comment]
Make sure this directory (XComGame\Mods) is added in AML settings as well

**Comment by Lipshawitz** [comment]
That did it! thank you!
