### ISSUE TITLE
Jammer resets number og uses if you save and reload

### ISSUE THREAD

**Issue by Rollo-Tomasi-git** [long-war-2/lwotc#1314]
Dev 26.1, Jammer (officer ability) bug: If you save after you have used it, then load and play from the save, your number of remaining uses has gone back up to 1.

**Comment by pledbrook** [comment]
Fixed by @GafrieGithub in [this commit](https://github.com/long-war-2/lwotc/pull/1478/commits/94a55faa36927ed96adbc0e6ed7a2c69c21756d6).
