### ISSUE TITLE
Ambush mission map generation has a giant hole in it 

### ISSUE THREAD

**Issue by eraserman59** [long-war-2/lwotc#1315]
[save_bugged Map.zip](https://github.com/long-war-2/lwotc/files/6558850/save_bugged.Map.zip)

In the attached ambush mission, there is a portion of the map that did not load. 
![268500_screenshots_20210527234634_1](https://user-images.githubusercontent.com/55302930/119941831-f5a7de00-bf45-11eb-8d73-a145e047862c.jpg)

None of the mods I'm running affects map gen. Sorry I don't have the save that launches the ambush forgot to reload and save it during the mission.

**Comment by eraserman59** [comment]
There's additional saves from other people in the discord bug report channel

**Comment by pledbrook** [comment]
The mission type for Covert Escape (the internal name for the CA ambush mission) is configured to use an objective PCP, whereas the Rendezvous maps are designed to use an objective parcel. This meant a PCP was being selected for one of the parcel slots.

Proposed solution is to create a new mission type for Covert Escape that uses an objective parcel instead. That should be the mission type that can select Rendezvous plots.
