### ISSUE TITLE
Chosen Geoscape Softlock (Savefile)

### ISSUE THREAD

**Issue by YifanLi5** [long-war-2/lwotc#1318]
When scanning a new region with a Chosen the game will pan over the red Chosen icon on the Geoscape and refuse to progress further, time however will still tick but even a queued up mission expiring will not pull me out. This seems similar to https://github.com/long-war-2/lwotc/issues/1260 except in my case I did not kill him. 

[save_Chosen Softlock.zip](https://github.com/long-war-2/lwotc/files/6574285/save_Chosen.Softlock.zip)

**Comment by YifanLi5** [comment]
To reproduce, finish scanning the South Africa region.

**Comment by pledbrook** [comment]
You enabled the Lost and Abandoned mission. The story start for WOTC is known to brick the campaign. I'm afraid you'll have to start a new campaign and be sure you do *not* enable the WOTC tutorial (Lost and Abandoned).
