### ISSUE TITLE
Restore the graze band

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#132]
Vanilla just "feels" too random/arbitrary, and it doesn't seem like the Dodge stat has any effect.

**Comment by ansabalirai** [comment]
![giphy](https://user-images.githubusercontent.com/15093261/56785389-d60fbb80-67a9-11e9-856b-692540e9cff5.gif)
I was afraid to say anything since I didn't hear anything from anyone about this. No graze also renders drones almost non-threatening, several perks become meaningless and dodge stat in general is basically useless

**Comment by pledbrook** [comment]
It was always on my mind, but various comments from @Ronar1 pushed it to the forefront of my mind. It really was just the difficulty of implementing it that stopped my from porting it over in the first place. And I'd forgotten how frustrating vanilla is...

**Comment by GitWadeanthony** [comment]
I remember playing with EU aim roll around the time when Flashed Advent would crit your soldiers if they hit and Smoke was useless for the same reason. But I hadn't tried it with WoTC, I'll try it tonight with LWOTC.

Question @MajorEvil , have you noticed Grazing Fire and dodge related perks working correctly with EU Aim rolls?

**Comment by Ronar1** [comment]
I'm pretty happy with how LW2 handled hit chance which was similar to how EU aim rolls did it, except it used the crit and dodge mechanics as a way of upgrading/downgrading damage which was really cool. LW2 was balanced with the LW2 calc method in mind when it came to enemies with perks like evasive, hard target, and high dodge in general. My only complaint would be that perks like stun gunner, drone stun, and viper grab would get the full effect if it grazed so they basically had a 10% accuracy buff. The idea of using crit to bypass dodgy vipers or using high dodge stat soldiers for people often in flankable positions was very neat as opposed to just lumping it all into independent rolls. I understand @MajorEvil 's concerns, but that (Like low hits always critting) should all be fixed if the LW2 calcs are carried over. If the LW2 calcs are too hard to implement for whatever reason, I wouldn't mind the EU aim rolls, but if possible try and add something similar with the opposing crit/dodge mechanics.

**Comment by pledbrook** [comment]
I think I prefer the LW2 calculations too. Particularly around using crit and dodge to upgrade or downgrade the damage. And as pointed out above, LW2 perks and other features are balanced around the graze band and upgrade/downgrade mechanics.

For what it's worth, I used to play with a +/-5 graze band rather than the default. Found it much less frustrating.

**Comment by MajorEvil** [comment]
@GitWadeanthony Yeah, I tested EU aim rolls with LWOTC and it defiantly works. Sure, I still do get hit and crit sometimes by an advent trooper who has penalties to aim with both smoke and flash up. But that's XCOM. With EU aim rolls enabled though, the chances of that happening are very small and that's very noticable via the mod. However, LW2's graze band is a way of fixing dodge and graze as it stands in LWOTC. Plus the graze band was made Specifically for LW2 for balance reasons. Ultimately, it will be up to the player to decide what RNG rule's the player want's to use for his/her Campaign in LWOTC with a custom mod set-up. But I can support the idea of porting over the graze band for balance reasons 100%.

**Comment by MiserablePileOfBugs** [comment]
Thanks for restoring the graze band, I hope you will be able to roll out alpha 5 quickly.

Right now combat feels too binary. It isn't that unlikely to see a soldier completely avoid ten shots in a row and then getting wrecked by a crit behind full cover. But the worst is having a stat that's totally useless.

**Comment by pledbrook** [comment]
Sadly this has hit a possibly intractable problem. No one seems to understand why some important code is bugging out in certain situations. 😢

**Comment by MiserablePileOfBugs** [comment]
That bad uh? What happened exactly?

**Comment by pledbrook** [comment]
It hangs the games reliably in certain situations. At the moment, it has only been reproduced with a soldier using the Hunter's Axe. And then only if you activate the Fleche ability. It works fine if you right-click to perform the Fleche attack.

It's very weird. I am tempted to make a dedicated build available to people that want to try it out, just so we can find out whether there are any other situations in which the game hangs. At least the Hunter's Axe situation has a workaround (use right-click attack).

**Comment by MiserablePileOfBugs** [comment]
I would gladly test this build. I was waiting for alpha 5 to start a new campaign anyway.

Since I'm not very good at modding the game, I can at least do some bug hunting.
