### ISSUE TITLE
I have an issue about XCOM2 LWOTC

### ISSUE THREAD

**Issue by maur1an** [long-war-2/lwotc#1320]
Hello everyone, 

Actually i did litteraly everything about what it says in "installation steps"
Furthermore, i did  the fallow step Long War of the Chosen Troubleshooting Guide v0.04

But i still meet an issue, i noticed 2 things who can be "wrong" or proofs about the fact there is a problem. 

First, this happens when i try to click on "Run War of the Chosen"
![1](https://user-images.githubusercontent.com/85264834/120570787-2c379a00-c419-11eb-9a3f-0a85ab1a5856.png)

So i can't Run War of the chosen

So i tried to click on "Run XCOM 2" with mods for WOTC and without the mods, in both cases the game run but without mod and WOTC, and my folder "Config" still empty even after I left the game.
![2](https://user-images.githubusercontent.com/85264834/120571099-b5e76780-c419-11eb-946f-dc2fc20fc600.png)

In my opinion the main problem is the fact my Config folder still empty but i'm not sure and i don't know how change that cause, it's never change even when i run the game and left it. I even did the step “Verify Integrity of Game Files” from Steam

So if you can help me, that could be very cool =)

Thanks everyone for reading and for the help !

**Comment by pledbrook** [comment]
It looks like you deleted the wrong config files. From the installation guide on the wiki:
> Delete all the files in Documents\My Games\XCOM2 War of the Chosen\XComGame\Config 

You deleted the ones in the game directory instead. Run Steam's Verify Integrity of Game Files. That will restore the config files for you.
