### ISSUE TITLE
Fleche causing game-freeze when targeting specific character

### ISSUE THREAD

**Issue by Bigglett** [long-war-2/lwotc#1323]
Release 1.0 Beta 4
Save game
Choose the shinobi (Flipper) and fleche the "Heavy Lancer" in the back. Game will freeze (and my PC also becomes semi-unresponsive)

[save_QUICKSAVE-_Campaign_8_Mission_75_Turn_3.zip](https://github.com/long-war-2/lwotc/files/6602522/save_QUICKSAVE-_Campaign_8_Mission_75_Turn_3.zip)

**Comment by wdanny69** [comment]
this should be resolved now, if it occurs still make a save and post a modlist, give as much detail about the set up and to the point it crashed
