### ISSUE TITLE
Ambient music missing on some missions (and other music issues)

### ISSUE THREAD

**Issue by tacticalweapon1** [long-war-2/lwotc#1326]
At the moment, some missions act very strange when it comes to the music. Jailbreak missions and smash and grab missions do not have ambient music and I am running into a weird issue on abandoned maps. Sometimes there will be no music, other times after a reload there is. Anyone else having this issue? Does this appear elsewhere?

**Comment by pledbrook** [comment]
Duplicate of #338.

**Comment by pledbrook** [comment]
Are you using beta 4?
