### ISSUE TITLE
Templar's Rend is not getting Bonus Damage from Vital Point Targeting

### ISSUE THREAD

**Issue by DerAva** [long-war-2/lwotc#1327]
Attaching two screenshots of the damage preview for Shield Bash and Rend against the same target. Rend does not seem to get the damage bonus provided by a Sharpshooters "Vital Point Targeting" holotarget buff:

![bug1](https://user-images.githubusercontent.com/49518216/120995498-bcf9d700-c785-11eb-9158-c0bac350b904.jpg)
![bug2](https://user-images.githubusercontent.com/49518216/120995502-be2b0400-c785-11eb-8091-db7941ffbe5f.jpg)

**Comment by pledbrook** [comment]
Does the Templar have Arc Wave? If so, that will disable Vital Point Targeting.

**Comment by DerAva** [comment]
Yes, he has Arc Wave. Is that then intentional that VPT gets disabled or just necessary for it to work correctly?

**Comment by pledbrook** [comment]
It's intentional that VPT does not work for any ability with multi-targeting effects. So no Trench Gun, Street Sweeper, Iron Curtain etc. I'm reluctant to carve out a special exception for Arc Wave, but I'll think about it.

**Comment by pledbrook** [comment]
I think I'll leave it as it is. I'm not sure it's at all possible to limit the VPT bonus to just the primary target, so if multiple targets are holoed and then hit by Arc Wave, they'll all be hit by the bonus damage. So I think it's best to treat Arc Wave just like all the other AoE abilities.
