### ISSUE TITLE
Review perks for new unit types

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#133]
LW2 added a bunch of perks to enemy unit types, but the new unit types just have vanilla perks. We need to check that they work and help the unit scale.

 * Priest
 * Purifier
 * Spectre

**Comment by Grobobobo** [comment]
Already reviewed with my WOTC enemies rework.

**Comment by pledbrook** [comment]
Implemented with [this commit](https://github.com/long-war-2/lwotc/commit/95d50a16aba99f965c96cbf1636bc62e70b4438d)
