### ISSUE TITLE
LWOTC not responding

### ISSUE THREAD

**Issue by jjameson23** [long-war-2/lwotc#1330]
Hello-

I just downloaded the mod and launcher, following all of the steps in the installation guide. The first launch is successful (showing the "new game" button). I exit the game and attempt to relaunch but it isn't working. I just get a window for the game that shows "not responding". I've confirmed everything in the installation guide (ex. correct paths in the launcher settings and correct mods selected) and reviewed the troubleshooting document and I've done everything exactly as indicated. While I'm sure I must be missing something as nobody else seems to be having this issue, I have no idea what else to try.

**Comment by pledbrook** [comment]
Please attach your Launch.log file, found in *Documents/My Games/XCOM2 War of the Chosen/XComGame/Logs*.

**Comment by jjameson23** [comment]
Here you go. Thanks!
[Launch.log](https://github.com/long-war-2/lwotc/files/6642137/Launch.log)

**Comment by pledbrook** [comment]
You've put the mods in the wrong location. Double-check the path in the instructions. The "XCom2-WarOfTheChosen" directory should be in the path to the unpacked mods.

**Comment by jjameson23** [comment]
I figured it would be something right in front of my face. I'm getting the correct title screen so I think I'm good. 

Thanks for your help and time!
