### ISSUE TITLE
Range of officer abilities does not match up with command range

### ISSUE THREAD

**Issue by DerAva** [long-war-2/lwotc#1331]
The descriptions for officer abilities like "Get some", "Incoming" and "Oscar Mike" mention that they would affect allies within command range. It seems that their range is fixed at base command range and doesn't increase with officer rank.

See screenshots below for the command range of a Field Commander officer compared to the aoe range for "Get some". Not just a graphical issue, units outside the aoe range were not affected by "Get some":

![command_range](https://user-images.githubusercontent.com/49518216/121777510-ca9eca80-cb92-11eb-97f2-9e6515b42aa8.jpg)
![get_some](https://user-images.githubusercontent.com/49518216/121777511-cbcff780-cb92-11eb-86e8-6bd68e94d465.jpg)

**Comment by pledbrook** [comment]
How did it behave in LW2?

**Comment by wdanny69** [comment]
for lw2, it should extend out to the indicated command range which the ui shows its shorter. i will add that height does affect the range a bit but that doesn't seem to be the case here, (height didn't affect officer abilities in regards to command range but it appears so in lwotc)

**Comment by DerAva** [comment]
As far as I remember the abilities would affect anyone inside the green outline. I don't even remember "get some" and others showing an aoe radius when you activate them.

**Comment by pledbrook** [comment]
Correct, LW2 did not show the aoe radius in the same way.

**Comment by DerAva** [comment]
So, fun anecdote: was going to showcase this issue on stream today, and there the "get some" and "oskar mike" ranges matched up exactly with the command range, so not sure what is wrong with this specific officer. Will do some more testing.

**Comment by allenhu0912** [comment]
![20210620005321_1](https://user-images.githubusercontent.com/54481962/122679990-c6863480-d1b2-11eb-9128-7dc9a944c41a.jpg)
Having the same problem here. You can just see the command range at the edge of the screenshot. I wonder if it happens mostly on field commanders, since the soldiers that are suffering from this problem all happen to be so.

**Comment by pledbrook** [comment]
Fixed by @GafrieGithub in [this commit](https://github.com/long-war-2/lwotc/pull/1442/commits/5195a16109fe510e51a6b51515b6506b6c842817).
