### ISSUE TITLE
Chosen Sabotage states it delays Covert Ops by 7 days, ads 12 days instead

### ISSUE THREAD

**Issue by DerAva** [long-war-2/lwotc#1334]
What the title says, clip here: https://clips.twitch.tv/CourageousTubularDurianCorgiDerp-xVbjzry9IXvS9YVm (time left on covert action is 3 days at the start of the clip, 15 days after the sabotage happened)

I'd say either it's also adding the base duration on top of it again or it might do something funky with the modifier given by Engineers assigned to the ring.

**Comment by pledbrook** [comment]
It should be 14 days added to the covert action. The alert box clearly isn't parameterised.
