### ISSUE TITLE
Late game performance troubleshooting

### ISSUE THREAD

**Issue by DerAva** [long-war-2/lwotc#1340]
I was trying to do some performance troubleshooting: looking at the log while giving orders I noticed that whenever I select one specific soldier there are about 50 lines of
[1104.05] LW_PerkPack_Trace: LRLW firing 1
[1104.05] LW_PerkPack_Trace: LRLW firing 2
which lock the game for like 2 seconds before I can resume control
also lots of
[1691.85] LW_PerkPack_Trace: Bastion: Distance = 10
[1691.85] LW_PerkPack_Trace: Bastion: Distance = 9
[1691.85] LW_PerkPack_Trace: Bastion: Distance = 6
but that seems to be instant, so not hurting performance - but spamming the log a lot since it creates a line for each tile you even hover over

I made a very quick vid to show what is happening there: https://www.youtube.com/watch?v=rd7lEPsdPf0

Found this reddit thread from a month ago from someone who had a similar issue: https://www.reddit.com/r/LWotC/comments/njbfdz/lagfreezing_with_high_level_squads_during_actions/

Tried killing the psi soldier with bastion via killclosesttocursor had no effect.

Attaching the savegame from the strategy layer before the mission - FL 18 facility raid with 40-42 enemies, so good performance testing ground. Also adding the logfile.

[save_Save 64.zip](https://github.com/long-war-2/lwotc/files/6658606/save_Save.64.zip)
[Launch.log](https://github.com/long-war-2/lwotc/files/6658609/Launch.log)

**Comment by pledbrook** [comment]
It's a Chryssalid Soldier that's causing the Lightning Reflex checks. And for some reason, only for the Gunner and the Ranger. Even more weirdly, moving the other soldiers causes a check against the Ranger. I'm not even sure if Lightning Reflexes is the cause of the pauses. Struggling to get the mission to start with the debugger.

**Comment by pledbrook** [comment]
It looks like there is [a bug](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/1022) in the implementation of RapidFire2, ChainShot2, CyclicFire2 and CyclicFire3. There is also a bug with the highlander that may have made things worse, but not sure.

**Comment by DerAva** [comment]
Bumping this one and adding another late game mission with high enemy count:

Savegame is attached with the Forge being 100% infiltrated, 47 enemies on the map according to the Shadow Chamber.

In-mission performance issues:
Long delay between issuing a command and soldier actually moving
very long alien turns that tanked FPS

video example from the stream: https://www.twitch.tv/videos/1085262208


AML profile also attached. 

[lwotc2021_2.txt](https://github.com/long-war-2/lwotc/files/6807864/lwotc2021_2.txt)


[save_forge100.zip](https://github.com/long-war-2/lwotc/files/6807799/save_forge100.zip)

**Comment by pledbrook** [comment]
These have largely been resolved. Create new issues for any specific problems that remain.
