### ISSUE TITLE
Error detected attempting load of package: LW_PerkPack_Integrated

### ISSUE THREAD

**Issue by Bosies** [long-war-2/lwotc#1346]
I recently got LWotC setup on my local machine. XCOM2 WotC wasn't able to start with the Alternative Mod Launcher, so I decided to run from Steam's 2K launcher. The managed to start, but in the menu, I got a warning saying that a required mod 'robojumperSquadSelect' was required to run. I quit out of the game and enabled the mod, but then I was getting this error:

Error detected attempting load of package: LW_PerkPack_Integrated

I can't find anything on this and would like to know what's going on. Thanks in advance!

**Comment by pledbrook** [comment]
I recommend getting troubleshooting advice on our [Discord Server](https://discord.gg/vv5yJF9). In the meantime, how big is your "LongWarOfTheChosen" directory? I'm wondering if you installed the correct LWOTC package.

**Comment by Bosies** [comment]
Somehow I got it working. Dunno what I exactly did, but I managed to get a LW campaign started. I guess I'll keep my thread updated if issues pop up. Thanks.
