### ISSUE TITLE
Impersonal Edge does not reduce Shadow cooldown.

### ISSUE THREAD

**Issue by Alicg** [long-war-2/lwotc#1348]
Impersonal Edge does not reduce Shadow cooldown by 1, while the description says it should.

**Comment by TwinuX** [comment]
Impersonal Edge reduces Shadow Cooldown by 1 for every _knife kill_. It does not passively reduce shadow cooldown.

**Comment by Alicg** [comment]
ah, it's clear now. thanks.

**Comment by pledbrook** [comment]
Not a bug
