### ISSUE TITLE
Allow spark rifles to have upgrade slots as they do in WotC

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#135]
Title pretty much describes the suggestion/issue. As it stands spark rifles for LW2 do not have any upgrade slots like they do in WotC. This could be an issue change that I could make to LWOverhaul.ini.

**Comment by pledbrook** [comment]
This was mentioned in #77. Just testing the INI fix now.

**Comment by pledbrook** [comment]
Fixed in [this commit](https://github.com/long-war-2/lwotc/commit/6f4221fe8c1f163fc6f7e48d3d4bfef5b85be3cd)
