### ISSUE TITLE
Reinforcements not arriving despite being signaled as such

### ISSUE THREAD

**Issue by DSeyka** [long-war-2/lwotc#1350]
Here's a save file which has "reinforcements arriving" warning being shown, despite them never arriving, even after 50 turns or so.
[save_reinforcement_bug.zip](https://github.com/long-war-2/lwotc/files/6681411/save_reinforcement_bug.zip)

**Comment by pledbrook** [comment]
I'm afraid I can't do anything with that save file as it's for a non-English version of XCOM 2.

**Comment by DSeyka** [comment]
This was sent to me by someone on Discord, so I don't have any further info on this issue either.
Feel free to close it then, as this seems to be non-reproducible.
