### ISSUE TITLE
Avenger Defense Soldier Reinforcements uncontrollable

### ISSUE THREAD

**Issue by DerAva** [long-war-2/lwotc#1352]
Soldiers showing up as reinforcements do not have a complete action bar, do not react to movement orders and abilities on the limited action bar they do have can not be activated.

2 save files attached: start of the Avenger Defense mission and 3 turns in just after the new soldier arrives. In order to get Bradford to send in new soldiers you first need to lose a unit (a turret will do).

[save_AD_RNFs.zip](https://github.com/long-war-2/lwotc/files/6682117/save_AD_RNFs.zip)
[save_Avenger_Defense.zip](https://github.com/long-war-2/lwotc/files/6682119/save_Avenger_Defense.zip)

**Comment by Tedster59** [comment]
Issue apparently fixed by Highlander, closing.
