### ISSUE TITLE
Reaper knife sometimes breaks concealment despite claiming that knifing doesn't

### ISSUE THREAD

**Issue by xor50** [long-war-2/lwotc#1354]
as the title says

as you can see in the screenshot you even get the warning that it will break concealment, despite the skill claiming it wont
![image](https://user-images.githubusercontent.com/37473184/122766375-bac56b80-d2a1-11eb-9196-66d4ff12da0a.png)

save game:
[save_QUICKSAVE- Campaign 1, Mission 1, Turn 4.zip](https://github.com/long-war-2/lwotc/files/6686785/save_QUICKSAVE-.Campaign.1.Mission.1.Turn.4.zip)

**Comment by TwinuX** [comment]
Shadow =/= Concealment

Reaper Throwing Knives do not break Shadow, but they do break Concealment. Important distinction.

**Comment by xor50** [comment]
Wait? In vanilla I'm pretty sure it gets handled in the same way.

So I guess in LWOTC that's not the case? Everyone starts in concealment, including Reapers, so when concealment gets broken everyone loses stealth (including Reapers) because it's normal concealment and not Shadow?

Well... I mean that makes sense but is irritating coming from vanilla.
But oh well, case closed I guess.

**Comment by pledbrook** [comment]
In LWOTC, Shadow is distinct from normal concealment. And Reapers do not start in Shadow. It is admittedly confusing and there are probably some things we can do to make it less confusing. But I think players coming from vanilla will always assume that Reapers start in Shadow.
