### ISSUE TITLE
Tooltip of Templar Focus doesn't show correct values

### ISSUE THREAD

**Issue by xor50** [long-war-2/lwotc#1357]
self-explanatory, see image

![image](https://user-images.githubusercontent.com/37473184/123170403-c6b85580-d47a-11eb-9e46-432f0d358ee2.png)

**Comment by TwinuX** [comment]
Actually, it's correct. There are no bonuses for Focus itself, any more. Overcharge give some bonuses based on Focus, but Focus alone does not.

The tooltip should probably be reworked to remove references to focus granting bonuses.

**Comment by xor50** [comment]
Ok so Focus without additional perks does... nothing? It only acts as kind of mana for skills like Volt?

**Comment by TwinuX** [comment]
Currently, yes. The intention is to encourage using it rather than hoarding it, unless we specifically take Overcharge. In base-game, it was preferable to just sit on as much focus as possible at all times.

**Comment by xor50** [comment]
Interesting. Excited to try it out!

**Comment by xor50** [comment]
btw so Overcharge is also showing zeroes in the tooltip.

**Comment by pledbrook** [comment]
I couldn't reproduce the issue with Overcharge, at least in the promotion info. It showed +5 and +10 for me.

**Comment by xor50** [comment]
That's weird. Will check again every time I look at my Templar.

**Comment by pledbrook** [comment]
Ah, I only fixed it 10 days ago [here](https://github.com/long-war-2/lwotc/commit/f41744f7d46958c16d046f73260cf2d0ebddbbbf).
