### ISSUE TITLE
PSI Lab not recognizing LW Psi Operatives

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#136]
So it looks like if you train a rookie to be a psi op the psi lab does not recognize them as a psi op. This is likely due to the fact that the psi lab is looking for a vanilla psi op instead of an LW2 psi op. Not sure where to look for this one. If I can find it I'll take care of it but putting this one up in case anyone else wants to take a crack at it @pledbrook @tracktwo .

**Comment by pledbrook** [comment]
Probably has something to do with [this code](https://github.com/long-war-2/lwotc/blob/master/LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc#L3077). I can't remember what the issue was, but I couldn't port the code as is, so I just threw in something that would get the mod to build and I hoped it worked. But it probably doesn't if it's the cause of this issue.

**Comment by jmartinez989** [comment]
Ok if that is the case let me see if I can take a crack at it.

**Comment by jmartinez989** [comment]
so been looking at this for a while and section of code it seems to be failing on is below:

`if (class'Utilities_PP_LW'.static.CanRankUpPsiSoldier(Unit))`

It seems that is returning false for the psi op. The specific part of that call that is failing is this:

`if (Unit.GetSoldierRank() + 1 < `GET_MAX_RANK && !Unit.bRankedUp)`

Going to do some messing around with this. With the way that the abilities are being checked I don't think the check for whether or not the soldier can rank up even needs to be done.

**Comment by pledbrook** [comment]
I suggest you compare to what original LW2 was doing. I can't remember the technicalities of Psi promotions other than you could pick abilities that were higher than your rank.

**Comment by jmartinez989** [comment]
Ok so I seem to have fixed this. I was able to train a psi op to all abilities and when they were all learned I could not longer staff them. Here is what the code looks like now:
`// this is an override for the psi training slot, to disallow training of soldiers currently on a mission
static function bool IsUnitValidForPsiChamberSoldierSlot(XComGameState_StaffSlot SlotState, StaffUnitInfo UnitInfo)
{
	local XComGameState_Unit Unit;
	local X2SoldierClassTemplate SoldierClassTemplate;
	local SCATProgression ProgressAbility;
	local array<SoldierClassAbilityType> AllPsiAbilities;
	local SoldierClassAbilityType PsiAbility;

	Unit = XComGameState_Unit(`XCOMHISTORY.GetGameStateForObjectID(UnitInfo.UnitRef.ObjectID));
	
	`LWTrace("Checking whether " $ Unit.GetName(eNameType_Full) $ " is valid for PsiChamber");

	if(class'LWDLCHelpers'.static.IsUnitOnMission(Unit)) // needed to work with infiltration system
		return false;

	if (Unit.CanBeStaffed()
		&& Unit.IsSoldier()
		&& !Unit.IsInjured()
		&& !Unit.IsTraining()
		&& !Unit.IsPsiTraining()
		&& !Unit.IsPsiAbilityTraining()
		&& SlotState.GetMyTemplate().ExcludeClasses.Find(Unit.GetSoldierClassTemplateName()) == INDEX_NONE)
	{
		if (Unit.GetRank() == 0 && !Unit.CanRankUpSoldier()) // All rookies who have not yet ranked up can be trained as Psi Ops
		{
			`LWTrace("Rookie! Can train as PsiOp");
			return true;
		}
		else if (Unit.IsPsiOperative()) // Psi Ops can only train if there are abilities left
		{ 
			`LWTrace("This is a PsiOp - need to check whether they can rank up");
			SoldierClassTemplate = Unit.GetSoldierClassTemplate();

			// WOTC TODO: Need to test soldier selection for Psi Chamber. This may not work as it includes
			// a random deck of abilities. I don't know if it's possible to distinguish between Psi abilities
			// and others
			AllPsiAbilities = SoldierClassTemplate.GetAllPossibleAbilities();

			foreach AllPsiAbilities(PsiAbility)
			{
				`Log("Checking for (Psi?) ability " $ PsiAbility.AbilityName $ " (" $ PsiAbility.UtilityCat $ ")");
				if (PsiAbility.AbilityName != '' && !Unit.HasSoldierAbility(PsiAbility.AbilityName))
				{
					return true; // If we find an ability that the soldier hasn't learned yet, they are valid
				}
			}
		}
	}
	return false;
}`

**Comment by jmartinez989** [comment]
Going to close this. Psi lab actually works but there is another issue with psi operatives. WIll open new issue for it.
