### ISSUE TITLE
Training Center, SPARK is genious, but not getting any own points for training

### ISSUE THREAD

**Issue by Chaos-UA** [long-war-2/lwotc#1360]
SPARK is genious, but not getting any own points for training. 
But it is still possible to train additional perks for my SPARK by using shared XCOM training points.
Is this is a bug and spark should get some own training points per level?

![genious-spark](https://user-images.githubusercontent.com/6782550/123866894-5146fc00-d936-11eb-8ada-015890bbbca8.png)

**Comment by TwinuX** [comment]
SPARKs do not have XCOM rows, and multiple-abilities-per-rank is not enabled by default, and is thus not part of the intended LWOTC experience. Therefore, SPARKs do not need to gain APs. This is not a bug, and is intended, even though the ability points UI/Combat Intelligence rating are still displayed.

**Comment by pledbrook** [comment]
Not sure what the behaviour here should be. I don't even know what base-game behaviour is. It's intended that SPARKs do not have combat intelligence and do not gain individual AP. What I'm not sure about is whether they should be able to purchase multiple class abilities at each rank. I can't see us removing that behaviour, though.

**Comment by pledbrook** [comment]
I think I'll just leave it as is. XCOM pool AP is not available in large quantities and if someone has enabled that particular second wave option and wants to spend the points on their SPARKs, I'm happy to let them do it.
