### ISSUE TITLE
Reward box after completion of covert op is empty, no reward given

### ISSUE THREAD

**Issue by qazqaz310** [long-war-2/lwotc#1362]
After sending soldiers on a covert op at the end of March, I was prepared to receive 46 supplies as a reward. However, after the covert op ended, the reward box was empty, both in the geoscape and in the avenger before the mission finished. Attached are screenshots and a save game.
![covert op 1](https://user-images.githubusercontent.com/86807079/124194813-151eb300-da7e-11eb-8f78-5658fa29ef4e.PNG)
![covert op 2](https://user-images.githubusercontent.com/86807079/124194822-17810d00-da7e-11eb-9b5f-826ae7ae1e34.PNG)

**Comment by pledbrook** [comment]
While there was a problem with the Recover Loot covert action, I don't see any issues with Gather Supplies. I can reproduce with the save file provided in Discord, but the save point is unfortunately too late to work out where things went wrong in this case.

**Comment by pledbrook** [comment]
If there are more blank rewards, we can either reopen or create new issues. Fingers crossed whatever caused this has been fixed.
