### ISSUE TITLE
Dev27, Black Market is empty

### ISSUE THREAD

**Issue by Lyca-x** [long-war-2/lwotc#1366]
The BM is empty. I can see the preview of the scientist, the engineer and a soldier having supply costs associated with them, but all items are completely blank and cost 0 supplies. buying them gives me the appropiate item. Reloading the save and restarting the game do not work, so the error must likely be generated during the supply drop sequence. I can look into the logs if needed, but I'd need a keyword to search for.
Savegame if needed:
[save_Commander-R_1.zip](https://github.com/long-war-2/lwotc/files/6756912/save_Commander-R_1.zip)
![20210702215940_1](https://user-images.githubusercontent.com/86854667/124324965-25b95100-db84-11eb-810c-c1c99194adc0.jpg)

Save was created with Dev27.
As a sidenote, Chosen have not appeared during FL3 and FL4 retals, and my first Lost sitrep mission appeared at FL4. Want a separate issue for this?

**Comment by pledbrook** [comment]
Did you start this campaign on dev build 27? Or upgrade it mid way?

**Comment by Lyca-x** [comment]
Hi!
I started this campaign on dev27. On the next supply drop, the black market returned to normal values. So it seems to be a sporadic value that is rolled during the supply drop/reshuffling of the BM.

**Comment by pledbrook** [comment]
Haven't had this reported since. Likely a glitch related to mods or perhaps an old bug that's been fixed.
