### ISSUE TITLE
Faction Influence needs Implementing at some point to better test resistance orders/Hero classes

### ISSUE THREAD

**Issue by MajorEvil** [long-war-2/lwotc#137]
So before I start here, you are going to see me reference to #54 a few times here. This is because although this issue is separate from that, It does require issue #54 to be solved before this one can really be solved. 

So a few days ago, while playing LWOTC, I got a Covert action to recruit a new reaper. However, because you can't get any faction Influence with any of the factions in LWOTC at the moment, you can't recruit any new hero's from the factions. This is due to the chosen being disabled for balance reasons as most of us here know from supporting this project for a while. See issue #54. Meaning if I wanted to help test and re-balance the Templar for LWOTC, but he/she gets killed early on in the campaign, I can't do that. I would have to put in a cheat code or something. ;) But This can not only prevent us from being able to recruit a new hero from a faction, it also prevent's us from being able to better test resistance orders in the game. Because faction Influence also effects that. The more faction Influence you get, the more Resistance orders you can have at any one time. Thus allowing us, the play-testers to be able to have a better say on what resistance orders we should keep/change/remove to balance them out better. See #72 on that one.

**Comment by pledbrook** [comment]
This may happen automatically once the Chosen are activated.

**Comment by pledbrook** [comment]
Chosen are now active, albeit not balanced.
