### ISSUE TITLE
CTD problems when loading save files in late game [1.0 beta 4.1]

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1370]
Here is a collection of log files:

[CTD.ZIP](https://github.com/long-war-2/lwotc/files/6771366/CTD.ZIP)

It is noticeable that the problems with save files often occur when I save after assembling teams for missions, while save files created after completing a mission are usually fine.

**Comment by MilesDPrice** [comment]
I've been having the exact same problem. I had a portion where I had to send loads of teams at once and couldn't do all of them in one go, so I saved. Then tried loading it again, CTD. Tried again, CTD. Went to the last working save (Last turn of the last mission) and tried again, half way through I had to quit once again, Saved periodically, and all saves after assembling a team do not load and CTD. Tried this multiple times and nothing works. It's practically killed my save. I've tried everything I could think of to fix it and nothing works.

**Comment by MoreFirepower** [comment]
> I've been having the exact same problem. 

Thanks for your message! I was already afraid to be alone with this problem.

There are also two other bugs in connection with the save function, namely sometimes (partly grotesque) wrongly positioned own or enemy units after loading, as well as the display of enemy light markers, although I'm not playing on the lowest difficulty level.

**Comment by pledbrook** [comment]
Collating these issues in #600
