### ISSUE TITLE
Meet 13-15 enemies with a chosen in a intel raid mission at 4/22

### ISSUE THREAD

**Issue by leaogzl** [long-war-2/lwotc#1371]
here's 2 saves before the intel raid mission
[SaveData.zip](https://github.com/long-war-2/lwotc/files/6776542/SaveData.zip)

**Comment by KrzepkiSzpinak** [comment]
Same here, 24th of April. Commander diff, met 24 hp hunter with stacking 25% dmg reduction buffs after multiple hits making him alone a big pain in the ass. I thought bewildered should buff dmg done to him, what's the point of granting him both bewildered and dmg reduction puzzles me..

**Comment by pledbrook** [comment]
> Oh and resistance MEC didn't show up despite acquiring.

Are you sure the Resistance MEC was in that region?

**Comment by wdanny69** [comment]
mecs will only show in resistance controlled areas. intel/recruit raids are within advent city centers and thus won't have mecs
