### ISSUE TITLE
The Geoscape's Interface is dying on me.

### ISSUE THREAD

**Issue by MisterForz** [long-war-2/lwotc#1372]
![Geoscape](https://user-images.githubusercontent.com/87075910/124761375-04fd4c80-df32-11eb-88c9-722e3fd3ce4c.jpg)

As the campaign went, many buttons started disappearing, first the contacts and now the infiltration buttons. I can't do stronghold or similar missions as they don't yank me back to them at their (lack of) expiration, infact there's an infiltration underway right on this screen in the Chosen Hunter's stronghold.

It happened on the 1.0 beta 4.1 release, and it still persists now on the devbuild 27.1.

I have a save on the devbuild 27.1 right when this screenshot was taken if it can be of any help.
[Geoscape.zip](https://github.com/long-war-2/lwotc/files/6777374/Geoscape.zip)

**Comment by TwinuX** [comment]
Have you enabled Framerate Smoothing in the video settings menu? If you have, clear your configs and do not touch that setting. It's a buggy mess and tends to break mods, being a common cause of this issue.

**Comment by MisterForz** [comment]
Well... this is... I feel silly, I did touch that setting once before disabling it and it was indeed before this mess appeared. Clearing the config resolved the issue entirely.

I'd say that I looked for similar issues on both github and Discord before posting but if it's common I suppose I haven't looked hard enough. Thanks for reply.
