### ISSUE TITLE
Missing required mods

### ISSUE THREAD

**Issue by osigum** [long-war-2/lwotc#1380]
Required mods https://steamcommunity.com/sharedfiles/filedetails/?id=1921971985 activated: I subscribed to them in Steam and checked them in the Alternative Launcher.

6 mods are in the Alternative launcher: lwotc, highlander, mod config menu, reset overwatch rules, better second wave, robojumper's.

Deleted "Documents\My Games\XCOM2 War of the Chosen\XComGame\Config" folder.

Launching the game from the Alternative Launcher-> Run War of the Chosen.

Game says that LWOTC is missing required mods: WotC: robojumper's Squad Select, Better Second Wave Mod Support, Revert Overwatch Rules Change.

Tried several time diffenet steps, but it's still the same. Have read though the #1028  but didn't find how to modify loading order.

After second launch, there is no error message. Is everything ok then?

**Comment by RustyDios** [comment]
Yes, after a config folder purge the first launch of the game will/should always be "modless".. this is because the game needs to generate the base game config files - including the one that informs/defines what mods are loaded.

The second and subsequent launches should be fine

**Comment by pledbrook** [comment]
As Rusty says, you typically need to restart the game twice after deleting your user configs.
