### ISSUE TITLE
Chosen Knowledge Bug? Build 27.2

### ISSUE THREAD

**Issue by aedn0239843** [long-war-2/lwotc#1382]
![20210712055809_1](https://user-images.githubusercontent.com/87316526/125293578-64fc4600-e2d8-11eb-8446-304108154a6e.jpg)
![20210712055630_1](https://user-images.githubusercontent.com/87316526/125293593-688fcd00-e2d8-11eb-96b6-65bbaba16271.jpg)
![20210712055635_1](https://user-images.githubusercontent.com/87316526/125293599-6af22700-e2d8-11eb-8cb9-d0a46bf42cdc.jpg)
![20210712055636_1](https://user-images.githubusercontent.com/87316526/125293611-6ded1780-e2d8-11eb-99de-e2a6de01130d.jpg)

Potential bug with chosen knowledge gain, Legend Difficulty. Templar Start, Warlock First Chosen Encountered, Hunter @ East Asia in May, Assassin at New Brazil in June Intel Retaliation, last chosen encountered. Assassin Knowledge level is 53% full, gained a large amount of knowledge at End of Month, Approx June 13th. Campaign was started on 27.1 and updated to 27.2 prior to meeting assassin & hunter.

**Comment by pledbrook** [comment]
Do the logs have anything about knowledge gain? No idea where it would be coming from. And somewhat surprised that Warlocks knowledge is so low for 13th June.

**Comment by aedn0239843** [comment]
there are about 6 lines like the one listed below, same text. Other then that nothing that i can find in the backup file from my earlier session. Might be using the wrong search terms, not really sure what the label would be. 

[1324.32] Error: (AddNetObject) Object AkEvent XPACK_SoundChosenSharedAbilities.Chosen_Extract_Knowledge_Soldier_Land with invalid NetIndex 111 (max: 22)

**Comment by pledbrook** [comment]
Was Loyalty Among Thieves (dark event) active? Could be that + captures + retributions.

**Comment by Grobobobo** [comment]
No longer relevant.
