### ISSUE TITLE
Mission load freeze

### ISSUE THREAD

**Issue by Cornolios** [long-war-2/lwotc#1383]
I've ran into a problem whenever I start a mission with a large map sitrep the game stops responding. I couldn't get a crash log since the game hardlocks, leaving me with two options of either restarting the comp or alt+f4'ing :(

I tried starting with my two mod packs disabled but that didn't bear any fruits.

Any ideas? Maybe a way to disable the large map sitrep?

**Comment by pledbrook** [comment]
The Large Map sit rep doesn't do anything. It's only there for informational purposes. The map would have been selected anyway and it would still have been large.

Do you happen to have Missing Packages Fix: Parcels and Maps installed?

**Comment by Cornolios** [comment]
> The Large Map sit rep doesn't do anything. It's only there for informational purposes. The map would have been selected anyway and it would still have been large.
> 
> Do you happen to have Missing Packages Fix: Parcels and Maps installed?

Yes, I do.

**Comment by pledbrook** [comment]
One of the discussions on its Steam page has a link to a fixed version that should work with LWOTC. Otherwise, just disable that mod.

**Comment by Cornolios** [comment]
> One of the discussions on its Steam page has a link to a fixed version that should work with LWOTC. Otherwise, just disable that mod.

It worked. Now i can have the full lwotc experience :) Thank you
