### ISSUE TITLE
mini retaliations within 2 days

### ISSUE THREAD

**Issue by KrzepkiSzpinak** [long-war-2/lwotc#1391]
Hi, 

not sure if it's a bug but I had 2 mini retaliations ( intel and supply ) within 2 days or even shorter in the same heaven.

BR

**Comment by wdanny69** [comment]
retals are independent of each other, yes you can fill the buckets enough such that they occur within a short time frame of each other

**Comment by KrzepkiSzpinak** [comment]
Ok thanks, wasn't aware of that!

**Comment by pledbrook** [comment]
Not a bug, but something that may change as part of an overhaul of the strategy layer.
