### ISSUE TITLE
More a question then a issue 

### ISSUE THREAD

**Issue by mfitz1970** [long-war-2/lwotc#1392]
How do you change the length between missions? I'm getting hit with mission after mission with no break is there a way to edit a file to fix this? Also how do I edit the number of enemies that attack on the map it's always in the 20's yet the mission always says between 8-12 on light missions. Please help any suggestions will be thankful.

Warlord

**Comment by TwinuX** [comment]
LW2/LWOTC does not use the same strict mission schedules of vanilla, and getting lots of missions is intended. We don't have to do all of them, most of them don't have a penalty for skipping.
As for enemy counts, that mostly relates to the infiltration system and enemy strength in the region. 

I'd highly recommend joining the LWOTC official discord for any questions, as we are much better able to answer them over there. https://discord.gg/uWM3nNhv
