### ISSUE TITLE
Hunker down does not put out fire.

### ISSUE THREAD

**Issue by AdityaPrakash-26** [long-war-2/lwotc#1396]
I want to ask if the burning effect still persisting after hunkering down is intended? I normally have to send a medic's gremlin to heal my soldier and remove burning. 

I can send a save file if you want.

**Comment by TwinuX** [comment]
Hunker not clearing the Fire debuff is intended, as this was LW2 behaviour.

**Comment by AdityaPrakash-26** [comment]
Okay! Thank you :)

How do you deal with the burning debuff then? Are there any ways other than just waiting it out or sending a gremlin to remove the debuff?

**Comment by TwinuX** [comment]
Medkits can cure it, hazmat vests can prevent it. Some maps have water, which can remove it when stepped in. This part isn't really explained anywhere.

Mostly, though, avoid getting burned. It's pretty dangerous.

**Comment by AdityaPrakash-26** [comment]
I will keep that in mind! Burning isn't really a big issue for me on most missions, unless the Chosen Warlock shows up and mind scorches the rookie I brought along to level him up lol. I'll just keep him back for now.

Thank you so much! :D
