### ISSUE TITLE
Recovered soldier still in statis suit

### ISSUE THREAD

**Issue by AdityaPrakash-26** [long-war-2/lwotc#1397]
Also, it does not show the name of the soldier I just rescued. Neither of them is a game-breaking bug, but I felt it was best to report them :)

It will be nice though if I can see the soldier name so I know who I am launching the mission for.

![268500_20210803234417_1](https://user-images.githubusercontent.com/55011564/128069213-53797e18-29e8-4638-89d3-458a62080582.png)

**Comment by pledbrook** [comment]
Why is the soldier in a stasis suit? Is there some other mod involved here?

**Comment by pledbrook** [comment]
Reopen if you can provide a reproducible example. This may partially be fixed by porting LW2's implementation of this screen that supports multiple rescuees.
