### ISSUE TITLE
Melee attack with Serpent skin crushes the game (Solved)

### ISSUE THREAD

**Issue by Maximmoore** [long-war-2/lwotc#1398]
When Ninja equipped with unique Viper body armor attacks in melee, sometimes, game just freezes permanently.

**
Just use mouse coursor to launch a melee attack
**
 
For some reason it completly solvels the case with out any mod manipulations. And the armor you are wearing has nothin to do with the problem.

**Comment by pledbrook** [comment]
This is a known and long-running issue that we have worked around to the best of our abilities. Any real solution will likely have to come from the Community Highlander and it's not even clear that can fix the issue fully.
