### ISSUE TITLE
Scanning in regions randomly gone rather early in game

### ISSUE THREAD

**Issue by ArthurSkok** [long-war-2/lwotc#1399]
March 23rd in game and I went back to geoscape, cannot see the option to scan in regions, only blackmarket and templar hq?
![Screenshot (4717)](https://user-images.githubusercontent.com/64739271/128377415-f88a64f5-0a8e-4d82-90f2-4a3a7dc730c5.png)

**Comment by TwinuX** [comment]
Have you enabled the Framerate Smoothing video setting?
It breaks mods often, causing issues such as this. You will need to disable the setting and clear your configs files.

**Comment by ArthurSkok** [comment]
> Have you enabled the Framerate Smoothing video setting?
> It breaks mods often, causing issues such as this. You will need to disable the setting and clear your configs files.

Disabling it and deleting the config files worked like a charm, thank you!!
