### ISSUE TITLE
Combat rush

### ISSUE THREAD

**Issue by KrzepkiSzpinak** [long-war-2/lwotc#1401]
Hi, 

combat rush sim doesn't trigger on kills (using it on grenadier). Also, it's possible to train abilities with ap points while on mission. 

BR

**Comment by wdanny69** [comment]
can you be a bit more specific. like is it not triggering at all? how are you sure its not triggering? are the effects just not being given?

**Comment by KrzepkiSzpinak** [comment]
Not triggering at all - no visuals or sound, i also check the detailed stats of soldiers and no effect is applied

**Comment by wdanny69** [comment]
i can try and test on my end, do you have a save i could use? hopefully not too many mods, or what version were you playing? don't say "latest" as i won't be sure if you mean the dev or beta build

**Comment by wdanny69** [comment]
ok ran some quick tests and it is indeed broken

**Comment by pledbrook** [comment]
Fixed thanks to Gafrie
