### ISSUE TITLE
Potential cause for duplicate items bug

### ISSUE THREAD

**Issue by Iridar** [long-war-2/lwotc#1403]
[Relevant line of code](https://github.com/long-war-2/lwotc/blob/76385e133a1e8163533dd12f00588f73bb01938b/LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc#L2113)

# The problem:

As was discovered recently, when the `CanAddItemToInventory_CH_Improved` runs for game state code, it bypasses the usual check of "is inventory slot already occupied". Setting `bCanAddItem = 1` without checking if the slot is already occupied can and will result in duplicate items being equipped into that slot by `XCGS_Unit::EquipOldItems()`. 

# The fix:

Simply adding a `CheckGameState != none && UnitState.GetItemInSlot(Slot, CheckGameState) == none` check before doing `bCanAddItem = 1`  should be enough to prevent the bug from happening.

To be clear, I don't have concrete proof that LWOTC actually suffers from this issue, but I see no reason why it wouldn't, as it uses the `CanAddItemToInventory_CH_Improved` hook in exact same way that other mods that have been confirmed to cause this problem.

For more context see [this Highlander issue](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/1056).

**Comment by Iridar** [comment]
This problem *might* be the cause of Grobo's issues with Templars and their sidearm animations.

**Comment by pledbrook** [comment]
Are you sure that's the fix? We need to be careful that we're doing the right thing in *both* code paths where this hook is called. If `CheckGameState` is `none`, then should we still be setting `bCanAddItem` to `1`?

**Comment by pledbrook** [comment]
Ah, of course `bCanAddItem` (the required `out` parameter) doesn't matter for one of them 🙄 I really wish this had been implemented as two separate hooks.

**Comment by Tedster59** [comment]
Closing this since it apparently didn't close when I actually merged the changes.
