### ISSUE TITLE
The Geoscape is locked into an infinite slide in this save file

### ISSUE THREAD

**Issue by Xerandael** [long-war-2/lwotc#1407]
LWOTC 1.0 beta 4.1

[save_IRONMAN- Campaign 77.zip](https://github.com/long-war-2/lwotc/files/6969438/save_IRONMAN-.Campaign.77.zip)

I've exited and reloaded the game and the problem persists with this save.

-------------------------

I do have a few extra mods but wouldn't think they'd relate:
 - [WOTC Lightsabers](https://steamcommunity.com/sharedfiles/filedetails/?id=1401316048)
 - [Reward Decks Refresher](https://steamcommunity.com/sharedfiles/filedetails/?id=665435869)
 - [Weapon Skin Replacer]( https://steamcommunity.com/sharedfiles/filedetails/?id=1517938486)
 - [Primary Secondaries]( https://steamcommunity.com/sharedfiles/filedetails/?id=1142234205)
 - [Dual Wield Melee](https://steamcommunity.com/sharedfiles/filedetails/?id=1439279281)
 - [Jedi Class Revised](https://steamcommunity.com/sharedfiles/filedetails/?id=2031929512)
 - [Animation and Sockets Supplement](https://steamcommunity.com/sharedfiles/filedetails/?id=1943613600)

**Comment by kenruof** [comment]
If you have a joystick unplug it. If the scrolling stops then edit the following file. 
Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\Engine\Config\BaseEngine.ini and change the line AllowJoystickInput=0

**Comment by Xerandael** [comment]
Brilliant, cheers
