### ISSUE TITLE
Games freezes in geoscape view (world view)

### ISSUE THREAD

**Issue by kenruof** [long-war-2/lwotc#1412]
After I scan a new haven and it revels a chosen and I have not contacted any  resistance the game screen freezes in world view although the time is still ticking. No response from keyboard all I can do is close the game. This did not happen if I have contacted one of the resistance groups.

**Comment by wdanny69** [comment]
If you're screen is locked looking at the chosen reveal, this is more than likely that you enabled "lost and abandoned", i recommend you look at the final few steps of the installation guide that tells you to not enable the tutorial or the intro mission

**Comment by kenruof** [comment]
That fixed it thanks!
