### ISSUE TITLE
Chosen Sniper barracks aim display

### ISSUE THREAD

**Issue by wdanny69** [long-war-2/lwotc#1416]
equipping the darklance has a duplicate line displaying the weapon's accuracy 
![image](https://user-images.githubusercontent.com/39199279/129940758-78a42859-866b-4e77-b8d3-b9e66fddcb4a.png)

**Comment by pledbrook** [comment]
This is likely because of [this code](https://github.com/long-war-2/lwotc/blob/master/LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc#L2509). I don't know why that code is there.
