### ISSUE TITLE
PSI Operatives not showing as promoted after a mission

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#142]
After a mission if the psi op has acquired enough xp to promote they after mission briefing will not show it as such. This makes it so you have to go to the psi lab to see if the psi op is actually able to learn a new skill.

**Comment by pledbrook** [comment]
Looks like this was implemented via a highlander event. See the `OnCheckForPsiPromotion()` method in `XComGameState_LWListenerManager`.

**Comment by ansabalirai** [comment]
So, just to confirm, the issue isn't as much as Psi ops not getting XP for promotions, just that they don't show as being eligible for promotions from outside of the Psi lab?

**Comment by pledbrook** [comment]
@ansabalirai Correct

**Comment by pledbrook** [comment]
Depends on [highlander #631](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/631).
