### ISSUE TITLE
Geoscape stuck showing the chosen Hunter's location

### ISSUE THREAD

**Issue by Brawler6216** [long-war-2/lwotc#1420]
I just finished my first advent retaliation strike in LWOTC and now whenever I enter the geoscape on my save, it'll immediately move the camera to the chosen hunter, then just stay there. with the time still passing.

I have these mods installed:
WotC: Color Coded Bonds
[WotC+Classic] Reliable Smoke
[WOTC] Coloured PCS Icons
[WOTC] Passive Icons Core Collection Edition
[WOTC] More Target Icons 2020
[WotC] UI - Colored Weapon Tiers
[WotC] UI - Colored Ammo Bar
[WOTC] Better Armory Item Stats
[WotC] Better Grappling!
[WOTC] Extended Personnel Info
[WOTC] New Target Icons
[WOTC] Free Reload Anytime
[WOTC] YAF1 Profile Extension
X2WOTCCommunityHighlander v1.22.4 ( I was only able to get LWOTC to boot when I have both the normal community highlander, and the special beta installed)
Long War of the Chosen
Yet Another F1
Show More Buff Details
[WOTC] Stats on New Promotion Screen
Better Second Wave Mod Support
[WOTC] Revert Overwatch Rules Change
Evac All - WotC
WotC: robojumper's Squad Select
Still Stop Wasting My Time
[WotC+Classic] TacticalUI KillCounter
[WotC] Mod Config Menu
WOTC - Extended Information!
Instant Avenger Menus - WotC
[WotC] Gotcha Again
[WOTC] Peek From Concealment
[WotC] Peek From Concealment UI Fix

**Comment by NilchEi** [comment]
https://github.com/long-war-2/lwotc/issues?q=is%3Aissue+is%3Aopen+lost+and+abandoned

Your campaign is permanently bricked if you turned on Lost and Abandoned (it would have been on if your campaign did not have faction hero on Gatecrasher)

**Comment by Brawler6216** [comment]
> 
> 
> https://github.com/long-war-2/lwotc/issues?q=is%3Aissue+is%3Aopen+lost+and+abandoned
> 
> Your campaign is permanently bricked if you turned on Lost and Abandoned (it would have been on if your campaign did not have faction hero on Gatecrasher)

The version of LWOTC I was playing won't even let me turn lost and abandoned on. So I never did, it was greyed out.

**Comment by wdanny69** [comment]
if the box is checked that means its enabled and it extremely likely is enabled cuz this issue is linked to exactly this problem. another way it can be enabled is through those pop ups about enabling tutorial or introduction mission or whatever, its the last couple steps of the installation guide

**Comment by Brawler6216** [comment]
I'm so sorry, you're right, I made a new save and I started with a templar in my gatecrasher squad unlike my first campaign, I did notice a check when I made my first campaign but the line was greyed out so I couldn't un-check it. Once again sorry for the mistake.
