### ISSUE TITLE
Still unable to access long war option

### ISSUE THREAD

**Issue by NightingaleSong** [long-war-2/lwotc#1424]
I will attach some photos.

I have tried all the basic troubleshooting steps to be able to have LW appear instead of New Game. All attempts have failed and I am confused as to what I have done wrong. 

As you can see in the photos I have extracted the folders and files into the mods folder of Xcom2 WoTC and I only have the LWoTC mods installed and checked. 

If you need further details I can try to give it to you but as of right now I get not Long War option when opening Xcom2. Please, help. 

![Mods folder](https://user-images.githubusercontent.com/89705786/131227990-10633a31-f57f-494e-8723-0e31ce092f76.JPG)
![Selected mods](https://user-images.githubusercontent.com/89705786/131227991-02ce1df2-305b-461b-90b2-5350526ef98d.JPG)

**Comment by TwinuX** [comment]
Do you have Framerate Smoothing enabled in video settings?
Disable it if so, and delete your configs regardless then reboot twice.
The config files can be found under Documents\my games\XCOM2 War of the Chosen\XComGame\Config

**Comment by NightingaleSong** [comment]
Still a no-go. I went in and did not see Framerate Smoothing enabled so I enabled it, exited opened it, and then I disabled it to exit the game again. I then went into my config files in My Documents deleted everything again and tried the steps. Still nothing.

**Comment by NightingaleSong** [comment]
I went ahead closed Steam down too and deleted everything after closing Steam - no-go.

**Comment by TwinuX** [comment]
Try both validating X2's file integrity, and updating LWOTC to one of the more recent Dev builds, rather than B4. Also make sure not to use any installers to install the mod, they seem to break LWOTC.

**Comment by NightingaleSong** [comment]
According to the install guide I am suppose to use AML. 

4. Download and install the latest release of the Alternative Mod Launcher. In AML's settings, make sure there are at least two paths to mod directories - one for the workshop mods, the other for local mods.

Which I did. I also verified the integrity of X2 files and I have the most-up-date full release version of LW. 

Kind of upset because I finally got my mods working yesterday after two days of messing with them and replaying the first mission countless times I came across LWoTC. I unsubscribed from all my mods to install this only for it not to work. I know I must of missed a step but I do not know where or how.

**Comment by TwinuX** [comment]
AML is a launcher, not an installer. I meant stuff like Vortex, which breaks LWOTC. If you simply manually downloaded it and placed it into the mods folder, you didn't use an installer.

The most recent "full" version is Beta4.1, but the most recent Dev build, Dev27.3 is more recent and includes more up-to-date code and functions, as well as extra highlanders, which I can't see in your installation. I'd recommend trying it instead of B4.1, as it's functionally superior, but mostly might help ensure there wasn't some download issue.

**Comment by NightingaleSong** [comment]
Ah! That makes a lot more sense! Thank you for clarifying yourself! I will go ahead and try this out and I will come back here to let you know.

**Comment by NightingaleSong** [comment]
Question: Is there anything from with my manually downloading it and placing in the mods folder?

**Comment by TwinuX** [comment]
shouldn't be, it's the intended method

**Comment by NightingaleSong** [comment]
You were right! It works! Although, on the install steps it says I should have five active mods before launching and adding of my own but, I have an active eight mods instead. I do not know if this means anything but it works.
![active mods](https://user-images.githubusercontent.com/89705786/131236720-a65bec13-0c50-4abc-a98d-b604c415cbc3.JPG)
