### ISSUE TITLE
Normal to have a hero unit at the start of the game?

### ISSUE THREAD

**Issue by NightingaleSong** [long-war-2/lwotc#1425]
Is it normal to start a new LWoTC game with a hero unit? In the first game I made I had a skirmisher and now I have a reaper in game two. In the second wave options I did not click to start at a faction HQ. It is not game breaking or anything I am just curious if this meant to be or maybe one of the mods I have is interfering.

![20210829122251_1](https://user-images.githubusercontent.com/89705786/131259522-93b2b45a-e807-4119-a8bb-ed36589afbe4.jpg)

**Comment by 0xStarcat** [comment]
Yup! Totally normal. This mod removes the vanilla WOTC hero story mission (the one which gives you the Reaper first, then the skirmisher next) and replaces them with 1 random hero at hame start then later acquisition through covert ops. 

We also have a discord where you can ask any questions and get a quick reply:

https://discord.gg/9fUCvcR

**Comment by NightingaleSong** [comment]
Thanks buddy for the informative answer!
