### ISSUE TITLE
Undying Loyalty that triggers on an OW shot freezes the game for 5-10 minutes

### ISSUE THREAD

**Issue by Alchete** [long-war-2/lwotc#1427]
Build: 27.3
AML: 1.4.1 (no conflicts)

Attaching save file.  To duplicate:

- Overwatch everyone to end the turn
- Ranger should do 8 damage that triggers Undying Loyalty with the first OW shot.
- Undying Loyalty animation appears
- Then the game hangs on Alien Activity

Setting "slomo 5.0" results in the game still hanging for ~1 minute.  

(Remove the .jpg extension from the save.  Github wouldn't accept the file without an extension)

![save_IRONMAN-_Campaign_69](https://user-images.githubusercontent.com/4705189/131756224-2aca8659-2a3c-4e05-902c-11014fc48c7b.jpg)

**Comment by pledbrook** [comment]
Try "Less Overwatch Lockups" mod. Probably won't try to do anything in LWOTC.
