### ISSUE TITLE
1 of 3 chosen never show up in Dev27

### ISSUE THREAD

**Issue by y403899457** [long-war-2/lwotc#1430]
Since the Chosen in born region only able to contact through retal missions,if u move fast enough to libreate ur born region and  adjacent ones(before regional Strengh raised above 3,quite simple under low difficulty),there's no way to contact him in rest of the game(Unless u leave ur home region to retal on purpose).
It's July now my hunter is still taking day off :P, making it impossible to launch stronghold CA,and never able to erase CA's ambush risk of this faction,pretty annoying in late-term gameplay.
I think make chosen destined to appear in lib 5 would be nice for this

**Comment by pledbrook** [comment]
Each Chosen is tied to a third of the regions, so you should still be able to contact a region that will have the starting Chosen on the retaliations. Unless you somehow liberate those regions before retaliations too 😄 

That said, the process of encountering the Chosen doesn't work as well as it could, particularly when combined with the way that the Chosen gain power (or don't gain power until you encounter them). It's something we can look at after the 1.0 release.

**Comment by eurofjr** [comment]
I have a similar issue (one Chosen never being contacted) although the circumstances are a little different. 

In my case, I've contacted all the regions with the consequent continent bonuses. I've contacted two of the factions (Templars and Reapers) and defeated two of the Chosen (Assassin and Warlock). However, I've never encountered the Skirmishers and never had the opportunity to do any missions against the Hunter. Still, the Hunter continues to build power and knowledge and is still able to interdict my missions, including assaulting the Avenger. I can see his graphic on the world map but, without the ability to contact the Skirmishers, cannot hunt him. 

I'm on my second Chosen Avenger defense mission (both with the Hunter) and he appears to act as expected. Same for the other missions, including Retaliation. I've attached the save file showing the world map. I keep drawing out the game, hoping for some way to contact the Skirmisher faction.

[save_'nuther.zip](https://github.com/long-war-2/lwotc/files/7192902/save_.nuther.zip)

**Comment by pledbrook** [comment]
@eurofjr Have you tried any new campaigns? I've never encountered this issue. Wondering if it's a conflict with another mod.

**Comment by eurofjr** [comment]
I ended up restarting the campaign and was able to run through without that particular bug occurring. Same setup and I only have the basic recommended mods. 

I have been playing Phoenix Point lately but will eventually go back to LWOTC and, if it occurs again, I'll post as an issue. It looks like LWOTC is now on Steam so that could be once I finish my current PP campaign. 

Appreciate the reply. Take care!

**Comment by pledbrook** [comment]
I'm going to close this. I may or may not revisit how Chosen are contacted in the future. I think there's potential for having them all active at the same time, but it would probably only work if they're rivals and their knowledge gain is different enough that you don't get a Chosen Avenger Assault from all 3 at around the same time.
