### ISSUE TITLE
In-game error on launch: Required mods are not installed

### ISSUE THREAD

**Issue by MissedWarrior** [long-war-2/lwotc#1436]
Hey!

I followed exactly through the lwotc [installation guide](https://github.com/long-war-2/lwotc/wiki/Installing-Long-War-of-the-Chosen) but got some troubles:
1) (not related to title) Guide says that there must be two directories after unzip while I'm seeing 3: [pic](https://i.gyazo.com/16939389a3a8dbd8b9fd676fcbf33c6c.png)
2) (related to title) After launching a game I see [this error](https://i.gyazo.com/91eab21d85967148950f7726908fe830.png). It says that required mods are not installed for lwotc: X2WOTCCommunityPromotionScreen

Current "setup":
lwotc: Dev Build 28.2 (Complete package)
AML 1.5.0-beta.2
Mod list [pic](https://i.gyazo.com/99eca34453bb9dd3d0fad4ea022971dd.png)

Did I missed something or do something wrong?

I can provide additional info/files if you need them, just request.

P.S. Also I see this [warning](https://i.gyazo.com/3407a36b699527301d575afb26d57103.png), is it ok?

**Comment by cptnhotsauce** [comment]
Starting in Dev-28, the Community Promotion Screen mod is required to be subscribed from the workshop. https://steamcommunity.com/sharedfiles/filedetails/?id=2542543519 . Additionally, your modlist has DLC2CommunityHighlander disabled. that will take care of your second warning.

**Comment by MissedWarrior** [comment]
Yeah, already figured that. Thanks for clarification

**Comment by TheOne320** [comment]
I subscribed to "[WOTC] Squad Manager" and am still getting the error concerning "X2WOTCCommunityPromotionScreen".
![image](https://user-images.githubusercontent.com/7705568/134313862-cb9b1572-4d95-40bb-b5f4-43f5e63afbe4.png)
![image](https://user-images.githubusercontent.com/7705568/134313930-52a1f06f-0344-466a-90a9-9a2e02dd987d.png)

**Comment by MissedWarrior** [comment]
@TheOne320 here is my mod list [pic](https://i.gyazo.com/0f916e04e417e23be9411f062bd1bb3f.png). works like a clock
