### ISSUE TITLE
Startup Error/ Midgame Error

### ISSUE THREAD

**Issue by ViruzZ1337** [long-war-2/lwotc#1437]
Hey, so my Game tells me in the beginning that I'm missing the required mods, (but just once so can't screenshot it) even though they are installed in the aml. ALSO my Game just randomly starts closing. Sometimes even bluescreening my PC. I have only the required Mods installed and the directories are okay too. I downloaded the 1.0 beta 4.1 Version on NMM.

**Comment by pledbrook** [comment]
Hopefully Steam version works for you OK. Support requests should be directed to our Discord ideally.
