### ISSUE TITLE
Some Proving ground projects are instant and free

### ISSUE THREAD

**Issue by Yoshidk** [long-war-2/lwotc#1446]
Proving ground projects Experimental heavy weapon and Experimental powered weapon is both INSTANT and free, so you can just create millions for free

[save_Error.zip](https://github.com/long-war-2/lwotc/files/7230473/save_Error.zip
![error2](https://user-images.githubusercontent.com/7499313/134788258-0b385b87-14de-4d7f-8783-c2c5723f12b4.JPG)
)

**Comment by DerAva** [comment]
Experimental PG projects should not be there in lwotc. You probably have a conflicting mod that adds them back in.

**Comment by Yoshidk** [comment]
I run these mods, i think its only the required and recommended:
![image](https://user-images.githubusercontent.com/7499313/134788360-7d783911-0c36-4c5c-a28e-2ba57edfba97.png)

**Comment by lasjorg** [comment]
Just an FYI. I had the same bug. Turns out I had forgotten that I disabled the Alien Hunters DLC, but I was still using DLC2CommunityHighlander. After disabling that mod, the "free" PG projects went away.

**Comment by pledbrook** [comment]
Not a bug with LWOTC.
