### ISSUE TITLE
Hyper-reactive pupils activates even when others miss a shot on the Ranger's target

### ISSUE THREAD

**Issue by Alchete** [long-war-2/lwotc#1447]
v28.2

My Ranger had a 92% chance to hit on a drone.  Instead of firing with the Ranger, I took the shot with my Gunner and he missed.  

Back to the Ranger, and he now has +10 from Hyper-reactive Pupils and a 100% hit chance on the same drone.  He still has both actions.

Save game attached with Ranger having both actions and +10 from Hyper-reactive on *both* Drones within view.

EDIT:  I need more testing, but it honestly looks like if anyone misses anything, then Hyper-reactive activates.

[save_IRONMAN- Campaign 71.zip](https://github.com/long-war-2/lwotc/files/7240161/save_IRONMAN-.Campaign.71.zip)
e.

**Comment by pledbrook** [comment]
Fixed with [this commit](https://github.com/GafrieGithub/lwotc/commit/6c53c8429010e451d15dba9fe04e805859f03ab8).
