### ISSUE TITLE
Allow different grenades to have different sound ranges with grenade launcher

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#145]
Although vanilla supports different sound ranges for items, including grenades, that only works if they're thrown. The grenade launcher has a 0 sound range, so the highlander needs modifying to use the sound range of the grenade ammo.

The original LW2 added this to the `XCGS_Unit.OnAbilityActivated()` event handler.

**Comment by SirMrMister** [comment]
To clarify, this is regarding only the sound of the grenade's explosion, not the sound of the grenade launcher's shot, right?

**Comment by pledbrook** [comment]
Not quite sure what you mean. The sound of the grenade's explosion needs to be tied to the ammo type used, rather than the grenade launcher itself. On top of that. the grenade launcher has a 0 sound range.

**Comment by SirMrMister** [comment]
> On top of that. the grenade launcher has a 0 sound range.

Should it stay that way though? It's no "BOOM" for sure, but it's still [about 100db](https://www.quora.com/How-loud-is-a-grenade-launcher-in-dB).

**Comment by pledbrook** [comment]
You can request a change for that, but it should be a separate issue.

**Comment by pledbrook** [comment]
This was implemented in [this commit](https://github.com/long-war-2/lwotc/commit/ffedd9ead000014ffd67a95b96447486fb17e133) by attaching a handler to the highlander's new `OverrideSoundRange` event.
