### ISSUE TITLE
Crash when loading a specific (and previously working) mission

### ISSUE THREAD

**Issue by DarthHarry** [long-war-2/lwotc#1457]
This is a weird one. I was playing Troop Column ambush mission. At one point the game crashed when I had a Shinobi attack a Sectoid. When I relaunched the game and attempted to load the last autosave It started loading, froze about 3 times then crashed to desktop. At first I figured the autosave was corrupted but the same thing happened with the earlier ones. Which is extra strange since I have loaded saves in that particular mission before. I loaded the Geoscape autosave continued playing and launched that mission again, and AGAIN it crashed. This time after the "door" screen. As an experiment I aborted that mission and launched a different one and it loaded up just fine. 

I am playing relatively heavily modded but made sure all are compatible with LWOTC along with Mod Jam and they have worked fine so far IN THAT SPECIFIC MISSION no less. And I haven't changed a thing prior or after the initial crash. I have also tried validating game files and clearing out the config files to be generated again. No change.

[Launch-backup-2021.10.11-21.40.43.log](https://github.com/long-war-2/lwotc/files/7327984/Launch-backup-2021.10.11-21.40.43.log)
e,

**Comment by pledbrook** [comment]
Log file doesn't help, I'm afraid. This may be similar to all the other issues with loading saves. Could also be mods. I'm trying to prune issues and I don't see that I can do anything here outside of what I do for #600 (if I ever manage to do anything for that). If you run into more issues, please try the #troubleshooting channel on our Discord server first.
