### ISSUE TITLE
Review of Install Instructions

### ISSUE THREAD

**Issue by Onfroygmx** [long-war-2/lwotc#1458]
Hello,

After being a player of XCOM 2 for several years I decided lately to try lwotc.
So below a description of my journey.

My problem is I'm on MAC and have a 512k internet connection.

I tried following the instructions provided but really nothing worked :(

First: Retrieving the complete package up to date (really a problem that it is only available only on Nexus) Maybe having a torrent file when it is released could help for slow connections.

Second: The following official step is to install "Alternative Mod Launcher", which only works on windows and then the fun really starts.

Third: For a Mac and Linux also I think, everything must be done manually because the steam integration is not very good.
- All the Required and Recommended mods must be downloaded separately.
- None of the instructions provided by Feral or other troubleshooting posts worked.
- The macos launcher is a crap and provides absolutely no debugging information (it shows the mods in the path, but not in the launcher).
- Depending on where you got the game from (App store / Steam / Direct Download) the paths (and case of the mods folder) used are not the same.

So after a lot of trial and error, 6 different mods directories in Upper and Lower case, with and without configuration files, partially enabled mods in actual saved games, I finally got the mods to show up in the launcher and enabled them. And magically I could start LWOTC.

I will now start playing with it, but the installation process should be reviewed, I can help a bit but it seems there will be no guide that works for all.

Onf

**Comment by Onfroygmx** [comment]
After using it a bit:
- For mac users upgrade to Monterey the performance improvement is huge!!!

<details>
<summary>List of Mods</summary>

DLC2CommunityHighlander/
LongWarOfTheChosen/
X2WOTCCommunityHighlander/
better_second_wave_mod_support/
evac_all_wotc/
wotc_accurate_situation_report/
wotc_mod_config_menu/
wotc_nice_mission_debriefing/
wotc_revert_overwatch_rules_change/
wotc_robojumper_s_squad_select/
wotc_tactical_ui_kill_counter_redux/

</details>

It seems evac all is not working anymore, was working with Big Sur.

I think I understood how to use mods on Mac so I would be glad to help making a new install guide when needed.

**Comment by Onfroygmx** [comment]
evac all works but not on a saved game .

**Comment by copyrite** [comment]
Considering that all comments on this were posted before the Steam Workshop release, I'm closing this.
