### ISSUE TITLE
Show current intel on Boost Infiltration screen.

### ISSUE THREAD

**Issue by SawNaw** [long-war-2/lwotc#1460]
When you click Boost Infiltration, it asks the user whether they want to spend 25 Intel to speed up the infiltration. It would be nice if the same screen showed the total amount of intel available.

**Comment by wdanny69** [comment]
https://github.com/long-war-2/lwotc/commit/8bd5f49322cfa031926e6d8ee98ad4fdc03687ea

this has now been implemented and upcoming in 1.2
