### ISSUE TITLE
Red Fog doesn't support multiplicative option, despite text in config. 

### ISSUE THREAD

**Issue by dzfischer** [long-war-2/lwotc#1463]
Config:
![image](https://user-images.githubusercontent.com/47398228/138571521-8ed9c3c1-c29d-41da-a310-62561d9b3c01.png)
![image](https://user-images.githubusercontent.com/47398228/138571548-9b4853e8-9185-43d9-b0fb-cfc2a551ca00.png)

Ingame: Multiplicative and linear, no applied debuffs.
![image](https://user-images.githubusercontent.com/47398228/138571461-bdd3b555-5bfc-45a5-8f7a-f008f8e6f0f8.png)

This seems due to the multiplication case expecting a float percentage between 0-1, but ComputeStatLoss rounds to int before returning as float.

Expecting float percentage:
https://github.com/long-war-2/lwotc/blob/b15ae98e60d1f7b855190cad6aa11b2aa48e9145/LongWarOfTheChosen/Src/LW_Toolbox_Integrated/Classes/X2Effect_RedFog_LW.uc#L165

Getting an int StatLoss:
https://github.com/long-war-2/lwotc/blob/b15ae98e60d1f7b855190cad6aa11b2aa48e9145/LongWarOfTheChosen/Src/LW_Toolbox_Integrated/Classes/X2Effect_RedFog_LW.uc#L189

I think this is easily fixed by doing something like this for the addition case, while removing the int cast from the ComputeStatLoss function.
> NewChange.StatAmount = -int(ComputeStatLoss()...)

Might need to round the value in the multiplication case so it doesn't show the player "0.72727272% multiplier" or something, no clue how the display side handles it.

**Comment by pledbrook** [comment]
This honestly looks more broken than that. `ComputeStatLoss()` doesn't take into account whether it should produce a value between 0 and 1 or a larger integer value. I don't think I'm going to invest time in trying to fix this, but I'd be happy to look at a pull request if it includes a reproducible example that demonstrates it's fixed.

For now, I will just modify the config file so it doesn't make any references to Modop type, particularly as that option is not available in the in-game settings.
