### ISSUE TITLE
Long War of the Chosen 2 is not showing up in AML

### ISSUE THREAD

**Issue by joha6695** [long-war-2/lwotc#1466]
The X2WOTCCommunityHighlander has showed up, but no Long War of the Chosen 2. Both folders are in the correct folder (steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods) and I have the path meant to refer to the folder

**Comment by EnsaisReborn** [comment]
Did you figure this out?  I have the same issue...

**Comment by pledbrook** [comment]
Now it's available on Steam!
