### ISSUE TITLE
Lwotc not showing up in the AML 

### ISSUE THREAD

**Issue by neighborwangsaid** [long-war-2/lwotc#1468]
I've followed the instructions and the AML did not show lwotc, but it could find the coummunityhighlander that was in the same MODS folder with lwotc, can anyone check what did I do wrong?

![搜狗截图20210604132030](https://user-images.githubusercontent.com/74082148/140606415-fcea5ff5-e325-4a6b-972c-7c00bf3575a8.png)
![搜狗截图20211106032606](https://user-images.githubusercontent.com/74082148/140606420-9f44b6d9-3402-4a0c-a77b-327f72233031.png)

**Comment by EnsaisReborn** [comment]
Did anyone answer this or did you figure it out?  I have the same issue...

**Comment by pledbrook** [comment]
The fact you have lwotc-master.zip suggests you downloaded LWOTC from GitHub. That won't work, hence why it didn't appear in AML. Anyway, it's on Steam now!
