### ISSUE TITLE
DLC_3 slider?

### ISSUE THREAD

**Issue by TheRealAyCe** [long-war-2/lwotc#1469]
There is a slider here with a missing translation. [This](https://www.reddit.com/r/Xcom/comments/k8dsxr/just_started_to_play_today_and_i_see_this_setting/) suggests that it should be DLC content related. Is something broken? I just installed LWOTC right now, following the tutorial exactly, with all required and recommended mods added.

![20211108225418_1](https://user-images.githubusercontent.com/11407231/140824512-b867fa17-822d-4e64-b845-d721779a0674.jpg)

**Comment by pledbrook** [comment]
I'm pretty sure that's a base-game option that we have no control over. In fact it shows DLC_3 for me too. DLC 3 is Shen's Last Gift.

**Comment by TheRealAyCe** [comment]
![20211219183457_1](https://user-images.githubusercontent.com/11407231/146684847-7659a57b-14b7-4742-967d-e440f4bc8fbd.jpg)
This is what it shows for me when all mods are disabled. It doesn't even appear? So I think the mods should add a translation, if none exists already, no?

**Comment by pledbrook** [comment]
It has nothing to do with mods. That is the base game's behaviour. Did you disable Shen's Last Gift?

**Comment by TheRealAyCe** [comment]
No, I did not disable anything. Both are the options menu from the main menu without a loaded save.

**Comment by Iridar** [comment]
This happens because Shen's Last Gift is missing a localized DLC identifier used by these sliders. Highlander makes the slider show up even in this case. LWOTC has nothing to do with it, the "problem", if you can call it that, is between Shen's Last Gift and Highlander.

**Comment by TheRealAyCe** [comment]
So the error needs to be reported to the community highlander mod developers? Do you know where I can report it?
