### ISSUE TITLE
I can edit soldiers that should be grayed out

### ISSUE THREAD

**Issue by eyescela** [long-war-2/lwotc#1473]
The problem is you can edit soldiers that should be grayed out (mission / haven / covert infiltration). It is fixed temporarily after you sort the list once. Here is the gif. https://gfycat.com/majesticspicyeeve
I am on dev 28.2. My mods https://pastebin.com/6578Hz0M

**Comment by eyescela** [comment]
might be the same bug #472

**Comment by pledbrook** [comment]
Closing as duplicate
