### ISSUE TITLE
Templar 1-tile movement bug (possible workaround/fix)

### ISSUE THREAD

**Issue by Alchete** [long-war-2/lwotc#1475]
The Templar unit currently has a bug where it becomes restricted to a 1-tile movement radius after certain actions:  i.e. looting a chest, providing Shield Wall cover to an adjacent unit, etc.  Folks have said that this is a base-WOTC bug.  However, I'd like to propose an idea for a fix.

Fix outline:
1.  Store the default Templar's movement radius at a point where it's known to be good, such as the start of the mission (subtracting any GTS 1st turn movement bonuses of course).  This would need to be unique per-Templar, as there may be more than one on a mission.

2.  At the start-of-turn (in a "callback"?), check if the Templar's (movement radius == 1) AND (Templar != stunned, incapacitated, etc.)  If true, then restore the previously saved movement radius to that Templar unit.

Hopefully, this isn't an embarrassing simplification of the issue, but it seems like, even with a base game bug, such a workaround-fix might be possible.

**Comment by pledbrook** [comment]
This would be better handled in the highlander, if it's at all possible. I seriously doubt I'll ever look into it I'm afraid. I'd rather just remove cover generation from the Templar. XCOM 2 just doesn't seem to handle it well.
