### ISSUE TITLE
Purifier explosions dealing no damage in Beta 5

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#1484]
Killed a purifier with sawn off shotgun at point blank and they blew up, yet my ranger took no damage. Later killed another with a sword, shinobi took no damage.
![20211123211817_1](https://user-images.githubusercontent.com/54481962/143170414-146738ea-af7e-4820-8867-941ed65addb6.jpg)

**Comment by pledbrook** [comment]
Can't do anything without a reproducible example because normally those explosions do damage things.

**Comment by copyrite** [comment]
I'm positive that Purifier explosions have dealt damage for a good while now.
