### ISSUE TITLE
[Beta 5] Still problems with savegames

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1485]
Hello, it still happens that after loading savegames units are placed incorrectly. If you reload the savegame, then it *can* happen that the positioning is suddenly correct again, but the behavior at this point is erratic.

![ridiculous_position_after_loading__example1](https://user-images.githubusercontent.com/87030865/143326778-cade6286-b4ed-49a8-af57-2c3379a95f5e.jpg)

![ridiculous_position_after_loading__example2](https://user-images.githubusercontent.com/87030865/143326782-6b34b28c-947a-42bc-901c-48eeaa815a6a.jpg)

![correct_position_after_loading__example1](https://user-images.githubusercontent.com/87030865/143326790-0367dcde-8b2d-4fbc-b169-3976dfe11b03.jpg)

[save_AUTOMATISCHER SPIELSTAND- Kampagne 21, Einsatz 8, Runde 5.zip](https://github.com/long-war-2/lwotc/files/7599232/save_AUTOMATISCHER.SPIELSTAND-.Kampagne.21.Einsatz.8.Runde.5.zip)

**Comment by pledbrook** [comment]
I don't think this is anything we can fix in LWOTC. As far as I'm aware, it's a base-game problem that just seems to affect LWOTC more than the base game, either because of more enemies, or bigger maps or something else entirely.

**Comment by MoreFirepower** [comment]
If I draw the correct conclusions from what I observe when this error occurs, then the units have an optical position and a logical position? Wrong in these cases is always only the optical position. If I aim at wrongly positioned enemy units, then the game behaves as if I were firing at the logical position. My unit then seems to fire into the void and if I land a fatal hit, then the enemy unit falls down at a different position.

**Comment by pledbrook** [comment]
Yes, it's the visual position that is wrong. The game is aware of the correct position, though, particularly with things like flanking indicators.

Anyway, filing under normal XCOM 2 "jank".
