### ISSUE TITLE
[Beta 5] Problems with the visibility of fields

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1488]
The fields in front of the building are colored gray, although the line of sight is not blocked.

![visibility](https://user-images.githubusercontent.com/87030865/143727633-277a6995-2a04-4d43-970c-a035dbd08bc8.jpg)

**Comment by MoreFirepower** [comment]
Another problem related to visibility: I could just target an enemy through a closed, non-transparent door.

**Comment by BlueMajere** [comment]
are you running any map mods?

**Comment by MoreFirepower** [comment]
> are you running any map mods?

No. See screenshots here:

https://github.com/long-war-2/lwotc/issues/1487#issuecomment-980531748

**Comment by pledbrook** [comment]
Pretty sure this is standard XCOM 2 "jank". Sometimes areas in vision are not revealed properly. If I remember correctly, saving a reloading fixes the problem.
