### ISSUE TITLE
Infiltration bonus for skirmishers

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#149]
Since they are former advent, they should have some info about the advent network which should give them knowledge of things like advent patrol paths and missions strategies.
With regards to implementation, I imagine giving them tradecraft as a start might work? Covert might not be needed given they already have reduced detection radius, but could work as well.

**Comment by jmartinez989** [comment]
This can be done by giving Skirmishers the tradecraft perk which we are looking to do.

**Comment by BlackRose39** [comment]
Now that we have "Battlemaster," which speeds up infiltration times for the Skirmisher, we can close this.
