### ISSUE TITLE
LW 2 secendary weapons have no perks

### ISSUE THREAD

**Issue by frostWorks96** [long-war-2/lwotc#1490]
all lw 2 secondary weapons are useless and don't add the necessary perks to the weapons to make them usable.

**Comment by TwinuX** [comment]
LW2/LWOTC applies weapon abilities at a class-level, not weapon-level. Secondary Weapons draw from these class-assigned abilities to function, but do not apply those abilities themselves.

Using these secondaries on classes without the required abilities won't work, as you probably discovered.

**Comment by frostWorks96** [comment]
so is the problem with RPGO?
