### ISSUE TITLE
Trojan damage is less than expected

### ISSUE THREAD

**Issue by DerAva** [long-war-2/lwotc#1491]
Trojam should do 8 damage if hack score exceeds hack defense by more than 50 according to:
`SYNC_RAND_STATIC(100) < 50 + AttackerHackStat - DefenderHackDefense

65 hack defense drone hacked with 119 hack specialist (net +54) resulted only in 3-6 damage.

Savegames attached pre-hack and with trojan about to trigger (just end turn)
[save_trojan.zip](https://github.com/long-war-2/lwotc/files/7627984/save_trojan.zip)

AML profile for the save:
[lwotc_minimal.txt](https://github.com/long-war-2/lwotc/files/7627988/lwotc_minimal.txt)

**Comment by Tedster59** [comment]
fix merged so closing.
