### ISSUE TITLE
 [Beta 5] Grenades do not destroy cover

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1492]
![1](https://user-images.githubusercontent.com/87030865/144152264-640132a3-b0b6-4ed8-829a-6616c99cb616.jpg)

![2](https://user-images.githubusercontent.com/87030865/144152742-4ed51bbb-850f-4f24-8f74-33b960cc5042.jpg)

**Comment by TwinuX** [comment]
Environmental Damage is altered in LW2/LWotC, and grenades are no longer reliable for destroying most environmental objects.
You need the Sapper and Combat Engineer perks to more reliably destroy various objects.

**Comment by MoreFirepower** [comment]
@TwinuX: Thank you! Is this new to beta5?

**Comment by TwinuX** [comment]
No, it's a fairly old LW2 function. 
In the case provided, the box likely has 10 env HP, and grenades deal 9 base env damage, with 100-120% variation, so it's possible for the grenade to sometimes break the box on a direct hit.

Env damage also falls off with range from centre of explosion, unless the Combat Engineer ability is taken.

**Comment by pledbrook** [comment]
Not a bug.
