### ISSUE TITLE
[Beta 5] Resistance Mech not spawning on Protect the Datatap mission

### ISSUE THREAD

**Issue by Olin011** [long-war-2/lwotc#1494]
As per title, the resistance mech I got via covert action did not spawn on Protect the Datatap retaliation mission. The mission was against Warlock.

**Comment by DerAva** [comment]
Resistance MECs are not supposed to appear on these missions. Thematically the rebels have set up a hidden listening post in advent controlled territory, so bringing a MEC along for that is not that stealthy.
Resistance MECs only show up on Invastions, Full Retals, Rendezvous and Supply Mini-Retal missions

**Comment by pledbrook** [comment]
Why the show up on Supply retaliations I have no idea, since those missions don't take place in the haven. Anyway, as DerAva explained, this is not a bug.

**Comment by Olin011** [comment]
Ok, thanks. I was not aware of this

**Comment by pledbrook** [comment]
It's not explained anywhere, sadly. Not sure if it's worth adding something to the XCOM Archives. I just doubt anyone would look there.
