### ISSUE TITLE
[Beta 5?] One of many line of sight problems

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1495]
The two screenshots show the same situation from different perspectives. The sniper should not be allowed to target the Chosen. Of course I don't know again if the problem is solvable in lwotc ;)

![LOS2](https://user-images.githubusercontent.com/87030865/144601148-4e935e02-a36e-4c17-8c38-21c6522df10b.jpg)
![LOS1](https://user-images.githubusercontent.com/87030865/144601184-639c2a9a-c533-4a0a-90bc-1bb5f2754ab2.jpg)

**Comment by pledbrook** [comment]
Yeah, line-of-sight issues are pretty much vanilla things. Like the ability to step out into thin air or through walls to get flanks.
