### ISSUE TITLE
CTD after Liberation mission. After that any autosave from Liberation mission fails to load 

### ISSUE THREAD

**Issue by Olin011** [long-war-2/lwotc#1496]
I successfully completed liberation mission and got CTD. After that I tried to load any of the three autosaves from that mission and every time I got CTD as well. Any other campaign or mission save loads fine. Maybe it's a lack of memory. I have an old laptop but that was never an issue with Xcom 2 and original Long War mod.

I attached the crash log
[XCom-CL374751-2021.12.03-19.23.17_Logfile.log](https://github.com/long-war-2/lwotc/files/7651690/XCom-CL374751-2021.12.03-19.23.17_Logfile.log)

**Comment by pledbrook** [comment]
Probably encountering the same or similar issue to #600
