### ISSUE TITLE
Avenger defence mission. No place to put the bomb

### ISSUE THREAD

**Issue by santoshels** [long-war-2/lwotc#1497]
Hi finally came to the mini turret to put the bomb and there is no option to place the bomb. Also My reinforcements never came I see weird  solders randomly standing with arms streached out.

**Comment by santoshels** [comment]
![2021-12-07 10_11_19-XCOM 2_ War of the Chosen](https://user-images.githubusercontent.com/57630429/145055020-d8624f4c-5b40-4cf7-ae52-6d179d2a6e18.png)
Right now I am stuck. Since its an avenger defense mission.

**Comment by DerAva** [comment]
This was fixed with Beta 5, if you have a save from before the mission you can upgrade to beta 5 and replay from there, but there is no way to fix it in the mission if it's broken like that.

**Comment by pledbrook** [comment]
Fixed with [this commit](https://github.com/long-war-2/lwotc/commit/8279354dc6cacd3badc05dd4e4be466bbe0088b0)

**Comment by Wernerses** [comment]
This is still very much a prevalent issue, with users reporting on the original mod creator page that their mod "fixed" this bug.

Needs to be re-opened.
