### ISSUE TITLE
[Beta 5?] Drone flies through steel beam on wall

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1501]
The drone's movement was triggered by the soldier marked by the red arrow in the second screenshot.

![Walls1](https://user-images.githubusercontent.com/87030865/145498634-b8d33171-7701-4fb0-ac12-e95d869150b5.jpg)
![Walls2](https://user-images.githubusercontent.com/87030865/145498668-fbe637f1-3bde-473e-bef9-2a8b5d529fa1.jpg)

**Comment by TwinuX** [comment]
Firaxis map design issues. The tops of the walls are non-solid, so flying enemies (of which there are few) can pathfind over.

**Comment by pledbrook** [comment]
Yep, more problems that we really aren't in a position to fix.
