### ISSUE TITLE
Possibly not a Beta5 issue again, but what is it?

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1502]
![Hmmm](https://user-images.githubusercontent.com/87030865/145668982-4af9700a-19a3-4f62-b930-73a52bd15991.jpg)

**Comment by BlueMajere** [comment]
did your templar take the skill "channel" ?

because your arrow is pointing to the "loot" focus you can pick up with your templar to gain a point of focus.

**Comment by MoreFirepower** [comment]
Thank you very much, that's it!
