### ISSUE TITLE
Cannot start the latest "beta 5" version 

### ISSUE THREAD

**Issue by arsenestef7** [long-war-2/lwotc#1504]
[Launch.log](https://github.com/long-war-2/lwotc/files/7717282/Launch.log)
Hello everyone. 
I've got an issue when starting the latest beta 5 version of the Long War of the chosen 2.
When I previously played the game with Beta 4.1, it runs without any issue on my Portable Computer, and the mods are running normally as well. 
But the issue came up when I got the Beta 5. I tried the "reporting issues" guides you mentioned ; clearing my config directory (Documents\My Games\XCOM2 War of the Chosen\XComGame\Config) and moving the profile.bin file out of the SaveData directory (which is next to the Config folder). All that ended up at nothing.
And then I followed the Troubleshooting guides[](https://docs.google.com/document/d/1EEZqmzCQQoprh3sDFZQZyiuyRE8I_lsA7Z8pHTSRuzU/edit)  either, but the issue wasn't detected 
I wonder what was the real issue of all of it. 
Thank you in advance for your help.

PS: you can find my "Launch.log" up this report.

**Comment by pledbrook** [comment]
Please use Discord for troubleshooting. I notice that the required mods are all missing (except for the highlanders). Hopefully you'll have more like with the Steam release.
