### ISSUE TITLE
Shinobi is inexplicably revealed (Bug?)

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1505]
1. Shinobi in full cover

![why1](https://user-images.githubusercontent.com/87030865/146163225-64f5ed86-0f4a-4311-a063-7f595d04dac6.jpg)

2. Shinobi is revealed

![why2](https://user-images.githubusercontent.com/87030865/146163350-78f51bce-9b49-42dd-b9ee-eb5beb439fd7.jpg)

3. The red arrow points to the dead archon

![why3](https://user-images.githubusercontent.com/87030865/146163484-df4dfe57-1e76-4795-935e-b0576431b531.jpg)

I can offer a savegame (german).

**Comment by Clibanarius** [comment]
The middle two segments of cars' high cover are basically broken, in my experience. They claim to be high cover but your soldiers will be seen through them and shot through them as though they're in the open. Why, I have no idea whatsoever but it's a Firaxis-side bug.

**Comment by BlueMajere** [comment]
seconding the above. There are some cover in the game that are just broken, and arent real cover.

**Comment by pledbrook** [comment]
Very little we can do about this, sorry.
