### ISSUE TITLE
[Beta 5] Again big problems with broken savegames in the final stage of the game

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1506]
Can someone load this savegame (german!)?

[save_Mission_Start.zip](https://github.com/long-war-2/lwotc/files/7726580/save_Mission_Start.zip)

Since I expected that there might be difficulties again, I save frequently. What catches the eye is the sudden increase in file sizes.

![savegames](https://user-images.githubusercontent.com/87030865/146358112-92d534b8-bafe-476f-b506-eb6471ecb5fb.jpg)

The penultimate save file is also broken, the rest I have not tested yet. Hopefully I won't have to go back so far that I have to repeat hours of play.

**Comment by MoreFirepower** [comment]
Supplement:

[XCom-PC-NAME-CL374751-2021.12.16-12.02.02-Crash.zip](https://github.com/long-war-2/lwotc/files/7726752/XCom-PC-NAME-CL374751-2021.12.16-12.02.02-Crash.zip)

**Comment by pledbrook** [comment]
Collating in issue #600

**Comment by MoreFirepower** [comment]
> Collating in issue #600

The problem I described is not related to HQ assaults or only a few kills. There must already be more than a thousand kills and I have already described the problem in #1370 (Beta 4.1).

**Comment by pledbrook** [comment]
The problems with large save files are not exclusive to HQ assaults or number of kills. That just happens to be the issue where I have reported more on the extent of current investigations than elsewhere. I want just one issue to track with respect to these save game issues.
