### ISSUE TITLE
[Beta 5] Two enemy units on the same field

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1507]
![Two](https://user-images.githubusercontent.com/87030865/146544085-e3809e9a-cd39-417d-8487-c6375be681c2.jpg)

**Comment by pledbrook** [comment]
Are they still on the same tile if you save and reload? Although if that's an HQ, you probably don't want to test that. Either way, I don't think there's anything we can do about these types of glitches, sorry.
