### ISSUE TITLE
Templar (and potentially other Faction Heroes) tutorial popup uses outdated description

### ISSUE THREAD

**Issue by Iridar** [long-war-2/lwotc#1509]
WOTC shows a tutorial popup for each of the faction soldier classes when they are selected for the first time in tactical.

https://i.imgur.com/9eyxAGL.jpg

From what I understand, LWOTC overhauls templars to no longer receive passive bonuses from Focus, contrary to the vanilla tutorial popup, which can be misleading. Probably should update vanilla tutorial description.

**Comment by Iridar** [comment]
Addendum: this LW2 tutorial screen appears to be outdated as well: https://i.imgur.com/55v4yWQ.jpg

**Comment by Iridar** [comment]
Addendum: appears plating's category is not localized. There should be an event for this. https://i.imgur.com/qfCugwk.jpg

(Sorry for putting it all into one issue, but I'm lazy)

**Comment by Iridar** [comment]
It appears middle tree for many soldier classes is missing their proper localized name: https://i.imgur.com/R9OEZ3j.jpg

**Comment by wdanny69** [comment]
> It appears middle tree for many soldier classes is missing their proper localized name: https://i.imgur.com/R9OEZ3j.jpg

about the middle tree name, from what i remember lw2 never had any and this is just something that carried over

**Comment by Iridar** [comment]
The new popup tutorial also says about underinfiltrated missions having more enemies, but I thought that feature is not present in LWOTC? https://i.imgur.com/1Pl3YZX.jpg

**Comment by TwinuX** [comment]
Under-infiltrating missions increases alert/strength, resulting in more enemies and faster reinforcements. It's absolutely a core part of LW2/LWOTC infiltration.

**Comment by Iridar** [comment]
Ufopedia says the following:

> Supply Raids, Troop Columns, UFOs now grant enemy stat bonuses based on underinfiltration (0-24%, 25-49%, 50-74%,75-99%). Underinfiltration was meant to be a risk reward system where you take on more enemies and other negative modifiers in order to complete a mission but high level players abused this mechanic and launched at 0% infiltration to gain more corpses. Enemies gain a flat Aim and Defense bonus with an HP multiplier, these bonuses increases with lower infiltration.

https://www.ufopaedia.org/index.php/Differences_from_Long_War_2_(LWOTC)#Missions

Apparently I forgot that it applies only to specific missions - I assume to missions where you get to keep corpses. Seems very inconsistent if that's still the case, but I guess then the tutorial is still correct somewhat.

**Comment by TwinuX** [comment]
Strength is still boosted when under-infiltrating on troop columns and the likes, so enemy count does increase. It just has the added difficulty of also providing direct stat boosts to all enemy units.

We really don't want people trying to 0% these missions, hence the somewhat nuclear approach currently used.

**Comment by Iridar** [comment]
I see, thanks for the explanation.

**Comment by wdanny69** [comment]
will update the ufopedia to hopefully fix the misunderstanding, the change was an addition to those type of missions specifically because it spawned in additional enemies meaning additional corpses to be recovered. in lw2 this was fairly abused to effectively become a reward system vs the risk/reward like take in underinfiltrating missions where you took the risk to do it anyway despite the little time but specifically those missions it became mostly a benefit than a drawback

**Comment by Iridar** [comment]
TBH having enemy numbers jump all over the place depending on infiltration is something I always hated in LW2, and was happy to see gone in Covert Infiltration mod. A bit bummed out it didn't make it into LWOTC, but I suppose it would've been too radical of a change.

**Comment by pledbrook** [comment]
> Addendum: appears plating's category is not localized. There should be an event for this. https://i.imgur.com/qfCugwk.jpg
> 
> (Sorry for putting it all into one issue, but I'm lazy)

Ah, it looks like Long War 2 had a highlander hook in there that I missed. When you say there should be an event for this, do you mean you think there is one? Or we need to add one? I don't see a relevant hook in the community highlander.

**Comment by pledbrook** [comment]
> It appears middle tree for many soldier classes is missing their proper localized name: https://i.imgur.com/R9OEZ3j.jpg

See [this issue](https://github.com/long-war-2/lwotc/issues/1503).

**Comment by Iridar** [comment]
> When you say there should be an event for this, do you mean you think there is one? Or we need to add one? I don't see a relevant hook in the community highlander.

Hmm apparently there's an event only for WeaponCat, but not ItemCat. So you'd have to extend X2ItemCat and override `function string GetLocalizedCategory()`, if you're not lazy enough about it.

**Comment by Iridar** [comment]
> > It appears middle tree for many soldier classes is missing their proper localized name: https://i.imgur.com/R9OEZ3j.jpg
> 
> See [this issue](https://github.com/long-war-2/lwotc/issues/1503).

A bit confused, so the suggested solution is for players to go and add missing localization themselves?..

**Comment by TwinuX** [comment]
LW2 simply didn't have names for the middle trees, the ability loadout UI it used didn't support them. The linked issue is suggesting a set of names that should fit the centre rows for each class.

Given that it's a change from LW2, of sorts, and that it's not critical to any real gameplay mechanics, it's not one that's likely to be rushed through.

**Comment by pledbrook** [comment]
> > > It appears middle tree for many soldier classes is missing their proper localized name: https://i.imgur.com/R9OEZ3j.jpg
> > 
> > 
> > See [this issue](https://github.com/long-war-2/lwotc/issues/1503).
> 
> A bit confused, so the suggested solution is for players to go and add missing localization themselves?..

No, I was just pointing out there was already an issue raised for this particular change. It mostly didn't go into 1.0 because I didn't want to add to the burden of translators. I'll probably incorporate the suggested changes at some point.

**Comment by Iridar** [comment]
Okay, that clears it up, thanks to both of you.
