### ISSUE TITLE
Cannot use shredder gun from equipped exosuit - icon doesn't show

### ISSUE THREAD

**Issue by Studioname** [long-war-2/lwotc#1513]
https://drive.google.com/drive/folders/1gQf-5Y3omDvVpJQgma43cnbaePxGrS0Y

**Comment by wdanny69** [comment]
link no longer works and the issue isn't clear

technicals cannot equip shredder guns and all other classes can only use shredder guns with the heavy weapon slot

if this still occurs, please provide a save if reproducible a mod list and as much details leading up to the issue.
