### ISSUE TITLE
Hacking only awards the first prize

### ISSUE THREAD

**Issue by KAW0** [long-war-2/lwotc#1515]
![Hacking bug](https://user-images.githubusercontent.com/16373327/147303506-949c7c9b-cda9-4282-ad70-bf2e43a793b6.png)
Version 1.0.1
Happens: Always

**Comment by pledbrook** [comment]
You choose one of the awards. The default is the left one, which is highlighted in your screenshot. If you want to risk a lower chance on the other award, you need to click on it first before performing the hack.

This is not a bug.
