### ISSUE TITLE
Remove tutorial style suggested first building at start of the campaign

### ISSUE THREAD

**Issue by DerAva** [long-war-2/lwotc#1516]
When starting a new campaign if you go into the "Build Facilities" mode the Resistance Ring is flashing, basically the game suggesting to you that this should be your first build. That should either be disabled or changed to the GTS as early RR is generally considered not optimal or even a trap.

![Screenshot 2021-12-24 104525](https://user-images.githubusercontent.com/49518216/147341576-2a6aa44f-a5ff-45a0-a333-5ca3cc55a228.png)

**Comment by copyrite** [comment]
Implemented
