### ISSUE TITLE
Bug: shots from area suppression occasionally ignoring shields

### ISSUE THREAD

**Issue by bigdewie** [long-war-2/lwotc#1517]
This just occured in my game:
I area suppressed a priest with my gunner.
On his turn, the priest cast holy warrior on a nearby trooper, giving the trooper some defensive shield.
After that, the trooper ran through the area suppression taking a reaction shot from my gunner which grazed him.
My gunner had bluescreen rounds which are supposed to do extra damage to defensive shield.
The trooper took 8 damage from this grazing shot from beam cannon to his health from my gunner but his shield was completely untouched.
The trooper was not in line of sight of my gunner when he started to move but started in range of the area suppression.

i am using the steam version of LWOTC and its required mods together with alternative mod loader,

**Comment by TwinuX** [comment]
Bluescreen rounds is supposed to both ignore shield HP when calculating damage and purge shields afterwards.
However, it may be interacting weirdly with the ablative HP given by non-shieldbearer units, ignoring the shields but not purging them.

**Comment by Grobobobo** [comment]
Probably bluescreen rounds.
