### ISSUE TITLE
CTD when I try to promote anything but normal soldiers

### ISSUE THREAD

**Issue by Sir1Twist** [long-war-2/lwotc#1518]
I get a CTD when I promote anyone, other than vanilla, base, soldiers. I believe this is from the integrated mod WOTC New Promotion Screen By Default. I am going to try to remove it, to the best of my ability, and try again,

**Comment by copyrite** [comment]
You should only be running [[WOTC] Community Promotion Screen](https://steamcommunity.com/sharedfiles/filedetails/?id=2550561145) without [[Deprecated] New Promotion Screen by Default](https://steamcommunity.com/sharedfiles/filedetails/?id=1124609091). With this issue close to 2 years old, I'm closing this, reopen if this is still somehow relevant.
