### ISSUE TITLE
[Beta 5] Defense against an invasion: Killed resistance personnel are not counted

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1519]
Although the enemies kill several units of resistance personnel, the bodies are not counted and at the end of the mission the haven remains fully occupied (14 people).

![Invasion](https://user-images.githubusercontent.com/87030865/147862743-02fbe073-a13f-4d10-81ab-d4bd689af120.jpg)
![Invasion2](https://user-images.githubusercontent.com/87030865/147862747-3828ed32-c8d4-4164-8631-26b05151403b.jpg)
![Invasion3](https://user-images.githubusercontent.com/87030865/147862749-12f1c9e5-1cf0-495f-8ca5-a0517648e055.jpg)

**Comment by TwinuX** [comment]
Invasions take place in the 'capital city' of the region, with both resistance personnel and regular civilians mixed in.
ADVENT can't tell the difference (or doesn't care), and shoots both, but only the Resistance Personnel count against the haven's population.

We can tell the difference between resistance personnel and regular civies by their clothing; Resistance Personnel don't ditch their worn-out gear despite being within the cities now.

**Comment by Grobobobo** [comment]
That's working as intended, Civilians are mixed with resistance members.
