### ISSUE TITLE
Electroshock perk (assault) doesn't work

### ISSUE THREAD

**Issue by PollyPock** [long-war-2/lwotc#1521]
Electroshock perk from assault doesnt work at all, a missed shot is a missed shot and that's all, no disorientation effect on the enemy in case of miss.

**Comment by Q-Chaos** [comment]
What exactly do you mean by 'shot'?
In case it's not clear, Electroshock only disorients targets when you miss targets with the arc thrower, not your primary weapon.
Also, you can't disorient something if it has mindshield (M2/M3 priests).

**Comment by TwinuX** [comment]
Spectres are unique in that they have resistance to disorient from some sources. Arc thrower electroshock does not work against them, while a regular stun will.

**Comment by Grobobobo** [comment]
Working as intended.
