### ISSUE TITLE
Shield bash does not work as declared

### ISSUE THREAD

**Issue by tay451** [long-war-2/lwotc#1523]
According to the tooltip Shield bash is supposed to knock back for 2 tiles and have a 2 turn cooldown and it's actually 1 and 3, respectively.

In the first picture the viper was only knocked back one tile (from the tile between the templar and the snake)

![shieldbash](https://user-images.githubusercontent.com/38005695/149683095-c9f890c5-d433-4d29-8914-fa89ee5fa430.png)

With the usual convention of cooldown, shield bash should be usable every other turn but is only usable every 3rd. (compare that with double tap which also has 2 turn cooldown in its description and can be used every other turn).

![shieldbash2](https://user-images.githubusercontent.com/38005695/149683093-13bf7b9e-38d3-45b2-ba9f-d7913c629e28.png)

Depending on whether this is intended or not (I hope not, shield bash is not very competetive as is), it can be seen either as a localization issue or a bug.

**Comment by Iridar** [comment]
I would assume shield bash is going away once Templar Shield is integrated into LWOTC, but just as a note in general Knockback against living units is very inconsistent and should not be relied upon.

**Comment by tay451** [comment]
All right. Depending how long this Templar rework takes until release, at least a fix for the wrong cooldown from 3 to 2 might make sense in the next 1.0x version (specifically since it is not a dev version anymore), imho.

**Comment by Grobobobo** [comment]
The next version won't have shield bash anymore, so this isn't really worth fixing. Can be closed imo.
