### ISSUE TITLE
Laser Sight weapon attachment wrong symbol

### ISSUE THREAD

**Issue by McTrevor79** [long-war-2/lwotc#1525]
I noticed that on the laser scatteray the icon for the scope attachment is used when installing a laser sight. Another user on Reddit confirmed this. On conventional shotgun the correct icon is used for laser sight weapon attachment.

**Comment by copyrite** [comment]
All laser tier weapons are affected, except vektor and SPARK rifle, which have no icon at all (#688).

**Comment by copyrite** [comment]
Same goes for the corresponding set of coil tier weapons.

**Comment by copyrite** [comment]
Problem has been traced to Robojumper's Squad Select, which replaces the attachment category images for some attachments. Working theory is that it does so before LWOTC adds its own for laser and coil tier.

Also affected: Expanded magazines and auto-loaders of the same weapons. And more surprisingly, elite auto-loader icon seems to be the stock one for all weapons.

**Comment by copyrite** [comment]
Elite auto-loader icon is due to a mistake in RJSS default config, report has been sent.

**Comment by copyrite** [comment]
Fixed by moving RJSS to run after LWOTC so that the attachments exist at the time when they're modified.
