### ISSUE TITLE
Crashing when pressing start infiltration or launch mission buttons on the holo-globe

### ISSUE THREAD

**Issue by Nbghserd** [long-war-2/lwotc#1527]
I'm now in the mid game, and I can't even get to the operative equipment screen from the holo globe to start any missions without the game suddenly crashing.

**Comment by Nbghserd** [comment]
[Launch-backup-2022.01.18-19.36.50.log](https://github.com/long-war-2/lwotc/files/7894212/Launch-backup-2022.01.18-19.36.50.log)
[XCom-MSI-CL374751-2022.01.18-19.41.01-Crash.zip](https://github.com/long-war-2/lwotc/files/7894227/XCom-MSI-CL374751-2022.01.18-19.41.01-Crash.zip)
[save_Save 77.zip](https://github.com/long-war-2/lwotc/files/7894230/save_Save.77.zip)

it didn't let me attach my logs or saves all together when I wrote the description, I'm rather new to github.

**Comment by Nbghserd** [comment]
As far as I can tell the problem comes from the shadow chamber not being able to give its preview
Critical: appError called: Assertion failed: appErrorf [File:G:\BuildAgent\work\9a884cb2af69f6ff\main\XCOM2\Development\Src\Core\Src\UnObj.cpp] [Line: 2456]
Failed to find function GetShadowChamberStrings in XComGameState_MissionSite Transient.XComEngine_0:XComGameStateHistory_0.XComGameState_14259.XComGameState_MissionSite_966
from the log files of all my crashes. 
I had run into this bug before months, even years ago and never connected it to my building the shadow chamber

**Comment by Nbghserd** [comment]
deleting the shadow chamber does indeed fix the issue, gotta use console commands to get it back though big poor energy ;-;

**Comment by robojumper** [comment]
`GetShadowChamberStrings` is a vanilla function that was removed in WotC, so you probably have a vanilla mod that's not compatible with WotC.

**Comment by Nbghserd** [comment]
> `GetShadowChamberStrings` is a vanilla function that was removed in WotC, so you probably have a vanilla mod that's not compatible with WotC.

Thank you, I'll start going through my mods list again and see if I can find the conflict

**Comment by Nbghserd** [comment]
There was in fact a conflict with a mod I had to show the shadow chamber preview on the loadout screens, no more crashing or having to replace the shadow chamber, thank you Robo. I'm a little dumb, in hindsight.
