### ISSUE TITLE
Coup de grace on gunner not working on primary weapon

### ISSUE THREAD

**Issue by Squishyblob** [long-war-2/lwotc#1533]
I just picked up the Coup de grace skill from the xcom row on a gunner and noticed that it doesn't seem to apply to their main gun attack (at least against disoriented aliens, haven't tried stunned or paniced yet), despite mentioning it applying to their **primary** weapon. I'm assuming it's appllying to their dagger instead (haven't checked). So either the description needs changing for gunners, or the ability is just plain broken for gunners. Coup de grace does seem to work fine for the ranger I got it on, that's what makes me think it's affecting the gunner's knife instead of their gun.

**Comment by TwinuX** [comment]
Gunner Coup de Grace is intended to work for their secondary rather than primary, hence it's lower AP cost than on other classes. CdG on gunner primaries would also be too effective, so the alternative would be removing it from gunners instead.

**Comment by Squishyblob** [comment]
I assumed that was the case, so it's just the description that's wrong.

**Comment by copyrite** [comment]
Appears to be fixed between 1.0 and 1.1, as Gunner's Coup de Grâce is labeled *(secondary weapon)* by Community Promotion Screen, and the text specifies *combat knife*.
