### ISSUE TITLE
Hole in map

### ISSUE THREAD

**Issue by McTrevor79** [long-war-2/lwotc#1534]
I am using the current steam version of LWotC and got a map for Troop column with a part of the map missing in it. I am using absolutely no map mods or something like that.
![20220124135002_1](https://user-images.githubusercontent.com/59993279/150786831-f75921f3-a7e1-4139-9be2-01dd1798b287.jpg)
.

**Comment by TwinuX** [comment]
Do you have the Tactical Legacy Pack DLC?

**Comment by McTrevor79** [comment]
Yes, I think so.

**Comment by TwinuX** [comment]
TLP has some incorrectly configured plots and parcels, like that one. They won't cause issues terribly often, but it's not something we can easily fix. It's essentially a base-game bug that we notice easier in the higher-mission-count LW2 setting.

**Comment by McTrevor79** [comment]
Maybe add some explanation about that on the Steam Workshop page? What other issues can I expect? I will report similar issues I notice in this ticket. Maybe this can be used for documentation purpose so other players can read, what to expect and enable/disable the DLC based on that.

**Comment by BlueMajere** [comment]
The Steam Workshop page is already pretty jam-packed, and it's pretty low-impact, imo.

**Comment by copyrite** [comment]
Closing as a base game bug.
