### ISSUE TITLE
Tactical Legacy Pack Weapons

### ISSUE THREAD

**Issue by StuartA101** [long-war-2/lwotc#1535]
Just a quick question:

Are the Tactical Legacy weapons supposed to upgrade like they did before in LWOTC? The basic ones are there, but they never upgrade to the cool ones, like they did in the vanilla game? I even did the playthrough again (as I completed it before installing LWOTC), but it stays the same :/

Thanks :)

**Comment by TwinuX** [comment]
TLP weapons are upgraded via the squad upgrade schematics, which are not enabled in LW2/LWOTC. With weapons being single-built, giving free TLP weapons upon reaching mag/plasma tech would be unintended, too.

Use an alternative mod like XSkin to apply them as cosmetics to existing weapons instead.

**Comment by StuartA101** [comment]
Shame that, as they were a cool addition to WOTC :/ - Thanks for info though.
