### ISSUE TITLE
Teamwork not working

### ISSUE THREAD

**Issue by SupTang1** [long-war-2/lwotc#1537]
Hi,

Level 1 bond skill 'Teamwork' does not seem to work properly on my soldiers. Whenever I use it on a soldier it does provide me with a move only action, however I am unable to shoot guns or use any skills (which require 1 action to use). I am running heavily modded lwotc campaign. It's not how I remember Teamwork skill working, has anyone came across this issue before or is this intended?

**Comment by 1rb1s1rb1s** [comment]
What do you think a "MOVE-ONLY action" means?

**Comment by SupTang1** [comment]
> What do you think a "MOVE-ONLY action" means?

That's what I'm trying top find out, is it move only or grant 1 action as from the description I though it's 1 action (which you can use for shooting etc)

**Comment by 1rb1s1rb1s** [comment]
The description (quote: "Grant an additional movement point to a bondmate. Has a single charge shared between bondmates.") explicitly says that regular teamwork grants a move-only action, which surprisingly enough can only be used to move. The ability granting a normal action point is advanced teamwork, available with lvl.2 bond.

**Comment by SupTang1** [comment]
> The description (quote: "Grant an additional movement point to a bondmate. Has a single charge shared between bondmates.") explicitly says that regular teamwork grants a move-only action, which surprisingly enough can only be used to move. The ability granting a normal action point is advanced teamwork, available with lvl.2 bond.


Thank you, I must have completely missed this in the description somehow. Thank you for taking the time to respond.
