### ISSUE TITLE
Burning does not disable Chosens Kidnap Power

### ISSUE THREAD

**Issue by draconas1** [long-war-2/lwotc#1539]
As above, had a supply defence where one of my soldiers was dropped and bleeding.  Managed to set the Chosen Warlock on fire (definitely was suffering from the burning condition.  Suffered damage at the start of his turn and still had the debuff when it came round to my turn afterwards).  Warlock was able to use his capture power on my downed soldier.

If this is behaviour as intended feel free to close, but given burnings effect on available actions it didn't feel like it should be.

**Comment by Grobobobo** [comment]
Working As intended.
