### ISSUE TITLE
Add sound range to grenade launcher (the launcher, not the grenade)

### ISSUE THREAD

**Issue by SirMrMister** [long-war-2/lwotc#154]
Currently they produce no sound in-game for detection puproses. Apparently they are [about 100dB](https://www.quora.com/How-loud-is-a-grenade-launcher-in-dB).

I have no real opinion on the matter of balance; I just created this issue because I know that if #145 didn't make me think of it, I would never think of bringing it up, and this little detail may rest forgotten.

**Comment by pledbrook** [comment]
I don't think this is workable. The grenades themselves have a sound range and the game can only have one sound source for activations as far as I can tell.

**Comment by SirMrMister** [comment]
Well then, that's an open-and-shut issue then.
