### ISSUE TITLE
Missing image for Alloy Throwing Knife

### ISSUE THREAD

**Issue by DSeyka** [long-war-2/lwotc#1540]
This shows up after researching Stun Lancer Autopsy:
![image](https://user-images.githubusercontent.com/66876732/152399589-4cc4cd52-ef19-4e4c-8ac7-b22fc475ac18.png)
I'm using latest Steam Workshop version, 1.0.2.

**Comment by richard-melvin** [comment]
fixed in current beta.

**Comment by copyrite** [comment]
Indeed fixed between 1.0.5 and 1.1
