### ISSUE TITLE
ini changes not taking

### ISSUE THREAD

**Issue by Cyrneco** [long-war-2/lwotc#1541]
Hi. I'm trying to understand why at some stage the ini modifications I  make don't take anymore. For example I change the damage value of a weapon and it doesn't work. But it did before... Please let  me know what I'm missing...
Thanks
Cirneco

**Comment by copyrite** [comment]
Hi, this issue is very old at this point, so I'm going to assume this is no longer relevant. Please reopen the issue if you'd still like to receive help.
