### ISSUE TITLE
Defilade might not do what it advertises

### ISSUE THREAD

**Issue by LordAbizi** [long-war-2/lwotc#1554]
In line 19 of X2Effect_Defilade, the condition checks if the Attacker is in relevant position for the aura. This means, that if the ENEMY is within the Command range, then ALL allies get the defensive buff, regardless of whether they are in the Command range or not, and if the enemy is not in the Command range, then no ally gets the defensive buff.
This behavior doesn't seem to correspond the localization of the ability. 

 By switching Attacker to Target in this line, it will check if the actual squad members are in range, and will give them the defensive buff if they are in the Command range, regardless of where the attacker is, which seems closer in meaning to what the localization says.

**Comment by Tedster59** [comment]
fixed with my standalone mod, and incorporated into the latest beta.
