### ISSUE TITLE
Flashbang grenades do not work properly

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1555]
In the situation shown, flashbang grenades always disorient only one of the two enemies! If I reload and then throw the flashbang grenade exactly on the field of the enemy that was not disoriented in the screenshot, then that enemy is disoriented, but again not the second enemy.

![FB1](https://user-images.githubusercontent.com/87030865/163706715-d03b1b4b-1735-42f9-8e98-b6513c598876.jpg)
![FB2](https://user-images.githubusercontent.com/87030865/163706717-7f847549-5974-440e-b822-92c76592c07b.jpg)

**Comment by MoreFirepower** [comment]
Correction: In my further attempt, it is the adjacent field.

![FB3](https://user-images.githubusercontent.com/87030865/163707434-b52fd8e9-8964-4a26-a8d0-b87598dd45b2.jpg)
![FB4](https://user-images.githubusercontent.com/87030865/163707558-e9e00181-a0bd-4db2-b080-975f8e74d42b.jpg)

**Comment by TwinuX** [comment]
Some enemies, like Muton Centurions, have flashbang resistance. This means that flashbangs have a chance to not apply. Other sources of disorient, or Sting Grenades stun chance, ignore this.

**Comment by MoreFirepower** [comment]
> This means that flashbangs have a chance to not apply. 

Hmmm. I then tried around a bit more. It should have been a throw on the marked field, which finally worked for **both** enemies:

![FB5](https://user-images.githubusercontent.com/87030865/163730675-0175ae26-a823-4497-9550-c071757be90b.jpg)

**Comment by TwinuX** [comment]
As I said, they have a chance not to apply.
For Muton Centurions (MutonM2_LW) this is a 20% resist chance.

`+ENEMY_FLASHBANG_RESIST=(UnitName=MutonM2_LW,` Chance=20)

**Comment by MoreFirepower** [comment]
> As I said, they have a chance not to apply. For Muton Centurions (MutonM2_LW) this is a 20% resist chance.
> 
> `+ENEMY_FLASHBANG_RESIST=(UnitName=MutonM2_LW, Chance=20)`

Thanks for the information! But the behavior I described was reproducible! Do savegames also contain already determined random numbers?

**Comment by TwinuX** [comment]
XCOM saves contain an RNG seed that doesn't change when reloading the save. It's not the same seed as was used by the initial run, but every reload of the save will produce the same results as the initial reload.

**Comment by copyrite** [comment]
Explained by Flashbang resistance and RNG mechanics, not an issue.
