### ISSUE TITLE
Line of sight. Is there a rule that explains this behavior?

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1559]
![LOS1](https://user-images.githubusercontent.com/87030865/164971549-62aded2e-125b-4b8b-9373-be533994b577.jpg)
![LOS2](https://user-images.githubusercontent.com/87030865/164971562-8e2a44d2-18c0-442f-97af-5abe873d7d8b.jpg)

Something like "You can shoot through the ceiling if ..."?

**Comment by TwinuX** [comment]
"XCOM Jank"

Unfortunately, sometimes maps have weird LoS angles for no particular reason.

**Comment by MoreFirepower** [comment]
I think that if the XCOM developers are not willing to fix such gross bugs, then they should give the source code to capable people!

At this point I would like to note that I think it's absolutely great what the LWOTC artists got out of the game! If only it weren't for the incomprehensibly high difficulty level for my way of playing (*). I would like to have a difficulty level 1.5 ;)

---
(*) I like to finish my games without losing a single soldier!

**Comment by copyrite** [comment]
Line of sight jank is not something for LWOTC to fix. You're better off asking Community Highlander, though I doubt it's in their power either.
