### ISSUE TITLE
LWOTC shows XCOM perk row abilities as unlockable even if the soldier cannot afford the AP

### ISSUE THREAD

**Issue by Iridar** [long-war-2/lwotc#1566]
https://github.com/long-war-2/lwotc/blob/329b810b667790da6bd751babcf001668a39a9b4/LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2EventListener_Soldiers.uc#L521

^ This line is most likely at fault. Should check if the soldier can afford the perk before setting 'true'.

**Comment by Grobobobo** [comment]
I can't really fix it for lwotc, but i can fix it for GTO.

**Comment by Grobobobo** [comment]
![image](https://user-images.githubusercontent.com/50756826/177039287-c090e16a-3fdd-470e-8c6f-0f0b7336a223.png)
Something like this?

**Comment by Grobobobo** [comment]
![image](https://user-images.githubusercontent.com/50756826/177039324-a6afdab1-8670-4d7b-ba8f-7b9403bffda1.png)
Something like this?

**Comment by Iridar** [comment]
> ![image](https://user-images.githubusercontent.com/50756826/177039324-a6afdab1-8670-4d7b-ba8f-7b9403bffda1.png) Something like this?

The `bCanAffordAP` is already given in the Tuple, you don't need to redo the check yourself.

**Comment by Grobobobo** [comment]
![image](https://user-images.githubusercontent.com/50756826/177048588-265d4474-daf1-4415-b874-c23ee763e1cc.png)That's tuple[12] then, right?

**Comment by Iridar** [comment]
Yeah

**Comment by Tedster59** [comment]
https://github.com/Tedster59/lwotc/pull/14/files/c5c3192cf799b88bbe1661a451a14a52a8943731

Somebody did this one for me, it's merged into my latest beta.
