### ISSUE TITLE
Controller not working

### ISSUE THREAD

**Issue by Nusse469** [long-war-2/lwotc#1569]
For the most part the controller can clumsily make it through the game, but when I try to launch the very first infiltration the "start menu" on my XBOX controller doesn't start the mission.  I can back out and cycle everything else ..  and the button works outside of the squad screen, but not in it.

I have the required mods for controller support installed.

**Comment by kdm2k6** [comment]
I implemented controller support and played a campaign over a year ago. Just tried it again today and it still works. Here is what I used to test today :

- Community Highlander 1.24.0

- Yet another F1

- Robojumper's squad select

- Squad Management for Lwotc

- Manage equipment menu for Lwotc

- Long War of the Chosen

- List loader for Lwotc

- Better Second wave mod support

- Evac all

- Revert overwatch rules change

- No Drop down lists with controller support

- Mod config menu

- Gotcha again

- Community Promotion Screen

- Alien Hunters Community Highlander 1.24.0

- Accurate situation report

**Comment by kaphula** [comment]
I am having the same issue. Can't start the mission because the start button of the controller is not working.

**Comment by Nusse469** [comment]
My issue is resolved. Was a mod.

**Comment by kaphula** [comment]
> My issue is resolved. Was a mod.
Could you tell which mod caused the issue?
