### ISSUE TITLE
Consider chain activations a la Long War Rebalance

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#157]
The Yellow Alert Gameplay mod seems to have builtin support for activating pods that are in visual range of other alien pods that are on red alert. See the `YellowAlert_UIScreenListener.OnAlertDataTriggerAlertAbility()` method.

**Comment by ansabalirai** [comment]
While the idea would be interesting, the issue I foresee is that with most missions being timer based and pods being deployed roughly between your starting position and the objective,, this would lead to all pods being active in the first few turn when you lose concealment. IIRC, the mod has this as a configurable option, so we can try to see how it works (whenever the next alpha drops)

**Comment by SirMrMister** [comment]
I'd love to see a more complex implementation combined with other Inflitration and Yellow Alert mechanics, like chance-based depending on infiltration (just like the antibeagle reaction).

For now though, the basic stuff - I'm all for chain activation. We can agree at least on allowing chaining only from directly activated pods (so chain-activated pods cannot activate other pods), and to allow for chian activation both on a direct pod activation during XCOM's turn and at the end of the alien turn for any pod in LoS of a red alert pod, just like in LWR?

**Comment by jmartinez989** [comment]
If this gets implemented into lwotc we def need to make it so that green and yellow alert actions get differentiated. As it stands yellow alert game play allows all actions for green alert so it is effectively no different than yellow alert. Would need to make it so that things like overwatch or archon blazing pinions are the only things that can be done on green alert.

**Comment by Grobobobo** [comment]
This sounds like a change too fundamental for LWOTC, But I'm 100% attempting this in LWOTC-R.

**Comment by pledbrook** [comment]
LWOTC-R will be doing this. LWOTC classic will largely remain in the vein of LW2.
