### ISSUE TITLE
Crash when starting UFO Avenger Defense

### ISSUE THREAD

**Issue by Heater6123** [long-war-2/lwotc#1571]
Hey, I always crash after selecting my Soldiers for UFO Avenger Defense.
I tried all of the things I could find via google to fix the issue but nothing worked.
Here is my Logfile for the Crash.
I hope you can help me.

[XCom-CL469133-2022.09.09-17.34.26_Logfile.log](https://github.com/long-war-2/lwotc/files/9537031/XCom-CL469133-2022.09.09-17.34.26_Logfile.log)

**Comment by FlashVanMaster** [comment]
Can you post your list of mods? Maybe conflict with at least one of them

**Comment by FlashVanMaster** [comment]
Can you post your list of mods? Maybe conflict with at least one of them

**Comment by Heater6123** [comment]
Here is the List:

Loot Pinatas
Allow for larger Squads
Stats on New Promotion
Core Collection Meta Mod
Electrical Damage Consistency
Faceoff Ammo Fix
Defense Matrix Sabotage Fix
Avenger Defense Bondmates Fix
Ability to Slot Reassignment
Wrist-Mounted Grenade Launchers
UI-Colored Weapon Tiers
Standardised Resources Bar
Spark Repair Fix
Skulljack Mind-controlled Enemies
Shredstorm Cannon Build Fix
Scouting Protocol
Revert Overwatch Rules Change
Reliable Ever Vigilant
Powered Armor Rebalance
Powerful Breakthroughs
No Low Profile
Soldier Info Redux
Civilians Scream
Open Class Weapon Restrictions
Bstar´s Perk Pack
AP Grenades Redux
Inventory Slot Weight Toggler for LWOTC
Cut Content Psionics for LWOTC
Randomized Gatcrasher Loadouts for LWOTC
Iridar´s Bounty Hunter Class
Microstim Implants
WOTC Vest Slot
Beam Grenade Launcher
Additional Ammo Types
Additional Vest Types
Superior Explosives
Playable Titan Armor
LW2 Utility Plating
Upcoming Events
LWOTC
Evac Now
More Cities WotC
Robots on Covert Action
Extended Information
Tactical Information Overhaul
Smart Overwatch All
Still Stop Wasting My Time
Stop Wasting My Time
Pause World Time
Instant Avenger menus
Free Camera Rotation
Evac All
Extract Corpses
Guaranteed Interchangeable Upgrades/PCS Research
Custom Soldiers Evac Zone Fix
DLC Breakthroughs Support
Blackmarket Usage
Configure Upgrade Slots
WotC Enhanced AoE Preview
WotC: Color Coded Bonds
Yet Another F1
[WOTC] Passive Icons Core Collection Edition
X2WOTCCommunityHighlander v1.24.0
Grimy's Loot Mod WOTC
[WOTC] Point-Based Not Created Equal
Better Second Wave Mod Support
[WOTC] Sell Heavy Weapons
[WOTC] WSR Weapon Skin Replacer - Core
Commanders Choice [WOTC & Vanilla]
Ketaros 2D Package
Chimera Squad Ability Icons
[WOTC] Iridar's Template Master - Core
[WOTC] Alien Hunters Community Highlander v1.24.0
[WOTC] Musashi's Mods Fixes
[WOTC] Iridar's Perk Pack
[WotC] Mod Config Menu
Missing Packages Fix + Resource
Perk Pack - A Better Barracks (WOTC)
After Max Level Advancement
[WotC] UI - Colored Ammo Bar
[WotC+Classic] Reliable Smoke
[WOTC] Accurate Situation Report
[WOTC] Automatic Reload by Iridar
[WOTC] Civilians Revamped
[WOTC] Cost-Based Ability Colors
[WOTC] Corpse Drops Revamped
[WOTC] Configurable Chosen Weapons Upgrades
[WOTC] Cooldown Teamwork
[WOTC] Accurate Covering Fire
[WOTC] Community Promotion Screen
WotC: robojumper's Squad Select
WOTC Show Enemies and Terrain on Mission Planning
WotC Mod Everything Reloaded
Reward Decks Refresher
Show More Buff Details
Pause Scanning [WOTC]
[WOTC] Detailed Soldier Lists Redux
[WOTC] Iridar's Vest and Plating Overhaul
[WOTC Only] Move End Interrupt Fix
[WOTC] Extended Personnel Info
[WotC] Strip Weapon Upgrades and Customization
[WOTC] Tactical UI Kill Counter Redux
[WOTC] Squad Based Roster (BETA)
[WOTC] Show All Class Counts
[WOTC] Show Tech Rewards
[WOTC] New Target Icons
[WOTC] Open Squad Select at any time
[WOTC] Ability Interaction Fixes
[WotC] No Drop Down Lists With Controller Support
[WOTC] Less Overwatch Lock Ups!
[WotC] Gotcha Again
[WOTC] Free Reload Anytime
[WotC] Instant Loot
[WOTC] Loot Mind Control
[WOTC] Corrosive Rounds
[WOTC] Guaranteed Interchangeable Upgrades/PCS Addon

Borderlands 2 Zer0 Voice Pack
Zone-tan Voice Pack
The Shaper Voice Pack
Sundowner Voice Pack
SoulCalibur VI Amy Sorel Voice Pack
SoulCalibur VI / Witcher 3 Geralt of Rivia Voice Pack
Sean Bean Voice Pack
Seto Kaiba Voice Pack
RWBY / Blazblue Cross Tag Battle Blake Belladonna Voice Pack
RWBY / Blazblue Cross Tag Battle Weiss Schnee Voice Pack
RWBY / Blazblue Cross Tag Battle Ruby Rose Voice Pack
RE2 Claire Redfield Voice Pack
RE3 Jill Valentine Voice Pack
Nier:Automata English 2B WOTC Voice Pack
Persona / Blazblue Cross Tag Battle Chie Satonaka Voice Pack
Paladin Danse Voice Pack
Overwatch Tracer Voice Pack
Ben Yahtzee Croshaw Voice Pack
JoINrbs Soldier Voice Pack
Jesse Faden Voice Pack
Johnny Silverhand Voice Pack
Lara Croft Reboot Voice Pack
Mass Effect Miranda Lawson Voice Pack
Faith Connors Voice Pack
Eric Cartman Voice Pack
Gears Marcus Fenix Voice Pack
Mr. Torgue Voice Pack
Final Fantasy Tifa Lockhart Voice Pack
Borderlands Jack Voice Pack
Starcraft 2 Voice Mod Part 1 + 2
Diablo Nephlem Voice Mod Part 1
WTR L4D Voice Compilation
Freeman´s Mind Voice Pack
Bayonetta Voice Pack
Back 4 Blood Holly Voicepack

**Comment by FlashVanMaster** [comment]
Can you try without Avenger Defense Bondmates Fix and without Defense Matrix Sabotage Fix

**Comment by Heater6123** [comment]
Just tried it, crashed the exact same way as before, new logfile for reference attached as well.
[XCom-CL469133-2022.09.10-12.40.30_Logfile.log](https://github.com/long-war-2/lwotc/files/9540114/XCom-CL469133-2022.09.10-12.40.30_Logfile.log)

**Comment by FlashVanMaster** [comment]
Hm. I remember one bug with soldiers cosmetic mod or equip. There is also way to try operatives one by one on launiching mission (1 opeative per launch)
Sorry i can not see other way.
You can visit discord chanel about #troubleshooting

**Comment by Heater6123** [comment]
Hey, sorry for the late reply but i found the culprit, it was Custom Soldiers Evac Zone Fix, without it everything worked as it should
