### ISSUE TITLE
If Soldier is panicked from Mindspin, and is MC'd with another Mindspin next turn, the MC'd soldier then gets to act immediately during this turn

### ISSUE THREAD

**Issue by merkmekr73** [long-war-2/lwotc#1575]
Alien Turn: Sectoid mindspins Shinobi and Shinobi is panicked
XCOM turn: Shinobi does nothing because panicked
Alien Turn: Another sectoid mindspins Shinobi, rolls MC
Same Alien Turn: Shinobi fleches XCOM squad

**Comment by wdanny69** [comment]
this is the same issue as #1039 

the vanilla code cleanses any effects when a unit becomes mind controlled and clearing stun will grant actions back which when the two conditions are combined will result in cases like that.

might be something we can fix or not.
