### ISSUE TITLE
more than 8 soldiers on missions..... cant get it to work....

### ISSUE THREAD

**Issue by RevenganceDK** [long-war-2/lwotc#1579]
cant get more than 8 soldiers in a squad with any mod.  Just need some direction on how to change LWOTC base files to do so.  IS it hard coded where i can not access it?  4 hours online no answers

**Comment by Tedster59** [comment]
LWoTC mission sizes are defined in individual mission definitions, and the number of units you send is often less than the max due to infiltration mechanics.  Some missions such as the Chosen Avenger Defense and Liberation 5 (Assault Advent HQ) allow 10 soldiers.
