### ISSUE TITLE
cant start choosen stronghold mission. and other missions as well

### ISSUE THREAD

**Issue by Beerthirty1701** [long-war-2/lwotc#1582]
everytimee i send my squad to a mission that is not timed. ie choosen stronghold. my squad goes mind you only 5 go and i dont see any way to send more. but after i send them they get to 200 infiltrating. but then nothing. how do i go into the damn battle

**Comment by copyrite** [comment]
I'm having a hard time parsing what the problem is. If you still need help, please reopen with screenshots.
