### ISSUE TITLE
after quick save (quick load) the camera is not in same location and rotation

### ISSUE THREAD

**Issue by goofyseeker311** [long-war-2/lwotc#1589]
when loading it would be nice if the camera stayed on the same location and rotation as when saved.

edit: also possibly related to saving/reloading times in a row, some characters teleport partially to a roof.
edit: when did claymore become a knife, when thrown :)

if an unit was revived (by medic drone) in a loot box (3x3 area) then the unit will not pick up the loot immediately.

**Comment by copyrite** [comment]
Topic in title is not in LWOTC's scope.
