### ISSUE TITLE
Haven Advisers Not getting Proper Loadout on Retaliations

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#159]
So it seems that specifically to retaliations (all kinds) haven advisers are not starting with their proper loadout. When the mission loads they only have their weapon and some utility items (they never have their plating that grants them ablative hp even if you have it equipped). They usually seem to have their flashbang and frag grenades but that is about it. Also if you have any armor on them that increases their health (like plated or powered armor, their model looks like they have the armor on but they don't get the hp bonus from it. Also it appears that they get their skills and perks but the perks don't show up on the bottom left (at least from what I saw the last few times).

Seems this can be reproduced at every retaliation with a haven adviser on it.

My list of mods besides the CHL and lwotc:
```
[WotC] Advent MEC for SPARK
[WotC] Yellow Alert Gameplay
Tactical Information Overhaul [WotC]
[WotC] Mod Config Menu
[WotC] Faster Reload Animations
Darker Nights
Grey Smoke Grenades
Sabotage Cover Action Rebalance
More Cities WotC
More Effective Blast Padding
Turrets Are Cover [WotC]
[WotC] Advent Flashlights
WotC Enhanced AoE Preview
Tracking Shot Defense
Show More Buff Details
WOTC - Extended Information
Spectre Vanish Fix
[WOTC] EU Aim Roles
Skirmisher Cape
Insider Knowledge Fix
Gravely Wounded Scars
Full Character Customization From Start
Defense Matrix Sabotage Fix
[WOTC] Ability Interaction Fixes
[WOTC] Faceoff Ammo Fix
[WOTC] LOS Preview Ability
[WotC+Classic] Reliable Smoke
Capnbubs Accessories - WotC
Templar Gear
WotC: Show GTS Class Counts
[WOTC] EU/EWI Map Remakes
DLC Breakthroughs Support
Misclick Confirm WOTC
[WOTC] Cost-Based Ability Colors
Bradford's Voice
John "Central" Bradford
Custom Soldiers Evac Zone Fix
EmptyNames [WOTC]
[WOTC] Fair Lost Targeting
Avatar Buffs
Always Recruit and Rescue
[WOTC] New Promotion Screen by Default
[WOTC] Invisible Parts For Hero Units
Empty WOTC Deco Slots for XCOM Soldiers (+ Some other empty things)
[WotC] Gotcha Again
[WOTC] Camera Rotation Config
[WotC+Classic] TacticalUI KillCounter
[WOTC] Facility Clearing UI Indicator Fix
Chosen Dark Events Fix
Recruit Multiple Heroes From All
[WOTC] LifetimeStats
Upcoming Events [WotC]
[WOTC] Hours Instead of Days
[WOTC] Quick Soldier Info
[WotC] Revival Protocol Fixes
Yet Another F1
Remove Missing Mods for WotC
Stop Wasting My Time - WotC
```

**Comment by torma** [comment]
I got the same issue.

Save file can be found here:
https://drive.google.com/file/d/1FCm6VBzNbR6jokZ3HasuNKElln6DyhJc/view?usp=sharing

Adviser is a gunner. 

| Equipment | At mission start |
| --------------- | --------------- |
| Cannon | Only with 1 ammo |
| Frag Grenade | He has it |
| Flashbang Grenade | He has it |
| Ablative Health | Missing |
| Abilities | Not shown / Probably missing |

Mod list (only listing additional mods):
[WOTC] New Target Icons
WOTC - Extended information
Evac All - WOTC
[WOTC] Additional Icons
[WOTC + Classic] Tacticalui Killcounter
Yet Another F1

**Comment by jmartinez989** [comment]
So from further testing on retals advisers don't even get their perks. Just utility items (minus plating) and skills. Health from armor and perks and plating are all missing.

**Comment by jmartinez989** [comment]
So I have implemented what looks to be like a fix to this. Doing a bit more testing to make sure it works before I create a pull request for it.
