### ISSUE TITLE
sorting by rank mixes SSGT with 1LT 

### ISSUE THREAD

**Issue by goofyseeker311** [long-war-2/lwotc#1590]
sorting by rank mixed up unit list menus like in guerrilla tactics officer training selection.

edit: since when salvo (rocket heavy weapons) ability has been with the sniper class. in the xcom row.

**Comment by goofyseeker311** [comment]
other random bugs: if you start your turn inside an evac zone, might be an original game bug, it will not show a green evac button, claims its outside evac zone.

**Comment by copyrite** [comment]
Sorting by rank sorts by the combat rank, not officer rank. An officer trained only to 1Lt can be higher in combat rank.

Also don't expand your issues with unrelated topics.
