### ISSUE TITLE
LWOTC should ship "Disable Aim Assist" default config for Extended Information

### ISSUE THREAD

**Issue by Iridar** [long-war-2/lwotc#1600]
Given how ubiquitous this issue is. This ought to do it: 

`XComWOTC_DisplayHitChance_MCMDefaults.ini`
```
[WOTC_DisplayHitChance.MCM_Defaults]
TH_AIM_ASSIST = false
```
This won't do anything for people who have already changed their MCM config for EI in any way, but it's beta than nuffin.

**Comment by Tedster59** [comment]
Good idea.
