### ISSUE TITLE
Enemies killed by explosions from purifiers still yield corpses

### ISSUE THREAD

**Issue by DerAva** [long-war-2/lwotc#161]
Killing an enemy with an explosion or fire should make the corpse unavailable for salvage. This seems to not always be the case when purifiers are involved. Quick example:
Explosion kills: https://www.twitch.tv/videos/423358303?t=02h05m38s
Mission reward screen: https://www.twitch.tv/videos/423358303?t=02h15m50s

This is most likely related to the purifier explosion only. In the initial blast there are:
2 Troopers (killed by claymore - corpse not salvaged)
Stun Lancer (killed by claymore - corpse not salvaged)
Purifier (killed by claymore - corpse recovered)
MEC (killed by purifier explosion - corpse recovered)
Sectoid (killed by purifier explosion -corpse recovered)

**Comment by wdanny69** [comment]
death explosions do not destroy loot/corpses as doing so would make it impossible to recover the corpse of the unit with the death explosion
