### ISSUE TITLE
Bladestorm not activating (during pod activation)

### ISSUE THREAD

**Issue by ZadratAntares** [long-war-2/lwotc#1617]
[save_AUTOSAVE- Campaign 46, Mission 52, Turn 10.zip](https://github.com/long-war-2/lwotc/files/12847626/save_AUTOSAVE-.Campaign.46.Mission.52.Turn.10.zip)

[modlist.txt](https://github.com/long-war-2/lwotc/files/12847689/modlist.txt)

Attached is a save file and installed modlist for reference in which I have replicably created the scenario of using the fleche ability on a unit in a pod of enemies such that the unit stands adjacent to several enemies, and then the enemies activate and move from an adjacent tile with no activation of bladestorm. Is this intended behaviour? If not, would this be potentially due to a mod conflict? I have tried loading with and without the overwatch ruleset rollback mod with no changes.

**Comment by Mrveczt** [comment]
Yeah, thats intentional, this was also done partially (aside from preventing shinobies to wiping out enemies before they get even a chance to scatter) to prevent mutons parry striking your shinobies from a bladestorm when they pass  from any reason, because getting a massive injury, just cuz a Muton dropped in as RNF was bullshit.

**Comment by ZadratAntares** [comment]
> Yeah, thats intentional, this was also done partially (aside from preventing shinobies to wiping out enemies before they get even a chance to scatter) to prevent mutons parry striking your shinobies from a bladestorm when they pass from any reason, because getting a massive injury, just cuz a Muton dropped in as RNF was bullshit and completely out of control of the player.

Ah right, thank you. Just re-inspected the ability and this is actually explained in-game as well, I just hadn't noticed the change. Thanks!
