### ISSUE TITLE
Expected Enemy Activity calculation is wrong

### ISSUE THREAD

**Issue by ppoutine** [long-war-2/lwotc#1619]
When the game displays the expected Enemy Activity Level at xyz infiltration percentage on the squad select screen, if the Alertness Modifier is non-zero then the calculation performed is incorrect; sometimes (but not always) giving the player an incorrect result for Expected Enemy Activity Level (ie. the difficulty band - Extremely Light, Very Light etc)

The problem lies in [UIUtilities_Text_LW.uc](https://github.com/long-war-2/lwotc/blob/d9713674eb02737bb9e404677f5b4318bafa33c9/LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIUtilities_Text_LW.uc):

```
MissionState.GetShadowChamberMissionInfo (EnemyUnits, Dummy);
Difficulty = Max (1, (EnemyUnits-4) / 3) + AlertModifier;
```

This function is getting the baseline number of enemy units, calculating the Difficulty based on that, and then adding/subtracting the AlertModifier to the Difficulty to get the expected difficulty band. In other words the game acts as though every increment in Alertness Modifier equates to one increment in Difficulty bands, e.g. from Extremely Light to Very Light. But this is not the case. For example, for the revealed guerilla ops mission schedule, Alert 4 means 12 enemies and Alert 3 means 10-11 enemies. But the game will tell me that infiltrating an Alert 4 mission to 125% gives me 7-9 enemies. So this leads to false estimates, as well as to players not understanding how the infiltration system works

Instead, this function should be adding in the AlertModifier first: calling the mission state for "how many enemy units if the alert level was +/-X", _then_ calculating the Difficulty band based on this number of enemy units. But I'm not sure how to do that code-wise / if the MissionState has such a function

**Comment by Tedster59** [comment]
I've actually done this on the beta branch already.  It now makes a dummy mission, calcs the alert changes, and caches the mission data for that one.  This solves this issue, but does have a few humorous edge cases, such as some troop column schedules where one Alert level has 21 enemies, but then the level below has 22, so the enemy estimate actually goes up.

https://github.com/Tedster59/lwotc/blob/84fa462fc55a1bffad12eb58202b8b7e35951aa8/LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIUtilities_Text_LW.uc

**Comment by ppoutine** [comment]
That's exactly what I was looking for, thanks so much for being one step ahead of me

Regarding the new issue you mentioned: big picture, I feel like it was a mistake not to expose the effective Alert Level to the player, so they could see what is actually happening when they infiltrate to different breakpoints ie. understand what infiltration does fundamentally; but that's a larger design question & probably not worth fixing at this point. At least now we'll have an accurate result.
