### ISSUE TITLE
Templar got stuck with One For All

### ISSUE THREAD

**Issue by kaphula** [long-war-2/lwotc#1621]
I pushed repeatedly (3 times perhaps) One For All between turns for templar and he got stuck unable to move anywhere, meaning there were not any suitable cells to move at. This happened when the templar was against/next to high cover. Sorry, don't have save. This was during Iron Man play.

**Comment by Tedster59** [comment]
Yeah, that's an unfortunate side effect of units that provide cover due to shields.  It's another reason Templars are losing the ballistic shield soon.
