### ISSUE TITLE
Chosen sometimes respawns with 100% health if sarcophagus was destroyed on the same turn

### ISSUE THREAD

**Issue by copyrite** [long-war-2/lwotc#1626]
After the Chosen is killed the first time in their Stronghold, their respawn percentage gets set to 25%/34%/50% (depends on difficulty, and I may misremember the values). If the sarcophagus is destroyed on the same turn, the Chosen should respawn on the next turn with percentile health equal to the respawn percentage, but they sometimes respawn with 100% health instead.

Allegedly this has been occurring more in 1.1's beta (with T5 Chosen, may or may not be relevant), but not exclusively.

Reported by several people, e.g.
https://discord.com/channels/590853492084572170/590853932314656778/1181965033035542528
https://discord.com/channels/590853492084572170/590853932314656778/1175718536535097354
https://discord.com/channels/590853492084572170/590853932314656778/1173818004404973588
https://discord.com/channels/590853492084572170/942415676872740867/1152502045287391252

**Comment by richard-melvin** [comment]
which presumbaly comes from these lines in XComLW_Overhaul.ini:

![image](https://github.com/long-war-2/lwotc/assets/5872490/0d9a772e-3ceb-405b-b1a2-0c5110ca4868)

wheras XComGame.ini contains:

![image](https://github.com/long-war-2/lwotc/assets/5872490/6f4fb752-ea03-4be1-8b79-fa3d378cfcaf)

note that one of those lines is not like the others...

**Comment by copyrite** [comment]
Fixed by c94e07e056f426f6b1b0d34a9662e2bd782875d1
