### ISSUE TITLE
Avatars Spawning as regular enemies on some missions

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#164]
It looks like somewhere along the line of the latest build something happened where on certain mission types (likely things like advent hq raids and golden path missions) an avatar will be patrolling around the filed by itself as if it were just a normal enemy to have on a mission.

Probably has something to do with avatars being on the list of allowed uints to be in a pod on a mission. Not sure where I would begin to look at this one. Thing is I can only provide a save from the tactical layer as I never know if the mission I am on is going to have an avatar in it.

**Comment by pledbrook** [comment]
Pretty sure this is expected. AdvPsiWitch3 is a late game enemy in LW2, is it not?

**Comment by jmartinez989** [comment]
> Pretty sure this is expected. AdvPsiWitch3 is a late game enemy in LW2, is it not?

No they never were. The only ones that you are ever supposed to see are the one that you fight after skulljacking a codex and the ones that you fight at the alien fortress.

I do not recall ever fighting an avatar late game in LW2 before other than in those situations. Even all the way up to 1.5. And they only seem to be showing up on missions like hq raids and the ufo defense.

Before the latest build I did not see avatars anywhere other than the above mentioned situations, even with the late game hq raids.

**Comment by jmartinez989** [comment]
On thinking about this I don't really think this is an issue and can actually make things more interesting. I know that Avatars are not supposed to spawn solo but I'm going to close this as I think it would make missions more interesting.

**Comment by ansabalirai** [comment]
"Interesting" lol. From lore perspective, the first one you encounter after jacking a codex has missing health, reflecting the completion state of the avatar progress I guess. Would those spawning afterwards be impacted (I assume not) or otherwise have lower HP/stats than the three we see at Leviathan?

**Comment by jmartinez989** [comment]
no it seems they are all at full health. They are just spawning as  normal units with full health. Thankfully they seem to only be able to spawn at things like HQ raids, UFO Defense and I assume Alien Facilities.

**Comment by ansabalirai** [comment]
Hmmm. Looking at the inis, I only see `ForceSpawnTemplateNames[0]="AdvPsiWitchM3"` in fortress related sections, although they do have entries within `DefaultLeaders_LW` and `AlienLeaders_LW` in the spawn distribution lists starting at FL20.

**Comment by jmartinez989** [comment]
> Hmmm. Looking at the inis, I only see `ForceSpawnTemplateNames[0]="AdvPsiWitchM3"` in fortress related sections, although they do have entries within `DefaultLeaders_LW` and `AlienLeaders_LW` in the spawn distribution lists starting at FL20.

Right those are for when they spawn in as RNFs from the gates in the last part of water world. That is the only times those configs should apply.
