### ISSUE TITLE
Squad Select: Add Clear Squad button.

### ISSUE THREAD

**Issue by Jia3Huo4** [long-war-2/lwotc#165]
Is it possible to add a clear squad button to the squad select window?

**Comment by ansabalirai** [comment]
Add to this the autofill squad button (for those quick response retaliations where you just want the top 8 rank soldiers) and the make weapons, armor and utility items available buttons on the squad select screen, which are quite handy in terms of minimizing the number of clicks to get a squad deployed

**Comment by pledbrook** [comment]
rj's Squad Select has a 'UISquadSelect_NavHelpUpdate' event that can be used for this purpose. It might even be possible to override/remove the existing buttons, although as rj himself says:

> Unfortunately, you'll also have to intercept some input as the buttons for controller users are handled in OnUnrealCommand

**Comment by ansabalirai** [comment]
LW2 with a controller? Didn't even know that was a thing
