### ISSUE TITLE
Integrate vanilla bugfixes from [WOTC] Weapon Fixes

### ISSUE THREAD

**Issue by SirMrMister** [long-war-2/lwotc#166]
Mr. Nice recently uploaded [[WOTC] Weapon Fixes](https://steamcommunity.com/sharedfiles/filedetails/?id=1737532501), a mod which fixes the following bugs from vanilla behaviour (copypasted from the description):

> Issues addressed
> - When the "Insider Knowledge" order is activated, weapons with an expanded magazine installed do not actually benefit until they have been used on a mission, or their installed upgrades are changed. This leads to them being one round short at the start of the mission.

> - "Saturation Fire" does not apply Ammo Effects (eg burning, poison...) or Weapon Effects (eg "Disruptor Rifle" auto-crit on psionic enemies). The mod will also fix the similar issue with "Face Off" if the standalone Face Off Ammo Fix is not active. These fixes may be toggled with Mod Config Menu or directly editing the config file.
> - Stock damage on missed shots is not applied for several abilities, notably Rapid Fire, Banish, Dual Strike, Saturation Fire, Kill Zone and Rupture. This mod enables stock damage using a heuristic approach, not a fixed list, including enabling stock damage for pistol abilities, where it does not normally matter since they cannot be upgraded without mods. This also means it may fix issues with abilities from other mods which have forgotten to enable stock damage.
> - The conventional Vektor Rifle has its "typical cost" set to 2 actions not 1! Without mods, this only shows up if you get "Deadeye" as a bonus ability, since the standard Reaper Abilities have their cost hard coded to one action, not checking the "typical cost" for the weapon. With other mods which mean that Vektor Rifles are used with more varied abilities then in base WotC, this fix will stop them costing 2 actions when they should only cost 1 if they use "typical cost".
> - Some abilities which should have the "typical cost" for the weapon used are instead hard coded to cost 1 AP. Note this only becomes an issue with mods, since all abilities which are eligible for cross class use without mods are not affected by this. However it can be a problem with custom classes or weapons. These changes can be reverted with the use of Mod Config Menu.
> 
> Compatability
> This mod changes the "BuildNewGameStateFn" and "BuildVisualizationFn" of "Saturation Fire", but it does apply the existing function first. This means that although this will cause compatability issues with any other mod which also changes these "Saturation Fire" delegates, they may be fixed by making sure they are subscribed to before this mod. If necessary, this fix can be disabled via Mod Config Menu, in the same way that the "Face Off" fix may be enabled.

I know that we already have a thread for incorporating smaller mods (#67 ), but those are QoL or improvement mods - this is plain bugfixing, and I'm of the opinion that LWOTC in its no-extra-mods state should be as close to bugfree as possible, including fixing remaining bugs from vanilla behaviour - hence my request to integrate these fixes rather than relying on the user using this mod alongside LWOTC.

**Comment by MrNiceUK** [comment]
Point of order, that's my mod not Veehemata's!

**Comment by SirMrMister** [comment]
> Point of order, that's my mod not Veehemata's!

Whoopsie, apologies - I had another tab open with a mod of theirs, and when copy-pasting the name of the uploader I opened the wrong one.

Thanks for your work on it, nice!

**Comment by yoshimo** [comment]
Fixes that are not specific to  LongWar or other big mods, should be handled separately from them.
Yes, i think we should have them merged all in one place and i think it is better to either have them in the Highlander (https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/32) or as a Community Fix Master Mod.
It is not the best place to have it here.

**Comment by Grobobobo** [comment]
We already fixed the vektor, so only Saturation fire and typical ability fix is relevant here. Doesn't seem like highlander itself has decided to have the fix, so we should probably do it instead.

**Comment by Grobobobo** [comment]
I've ultimately decided it's better to NOT integrate weapon fixes because we do not need to make any changes to the mod, and other mods depend on it. If we integrate it and deem it incompatible as a result, those mods will raise a missing dependency flag in AML which will be confusing for most users.
