### ISSUE TITLE
Firestorm does not benefit from phosphorus' shredding

### ISSUE THREAD

**Issue by wdanny69** [long-war-2/lwotc#1663]
Issue: Technical Firestorm ability does not benefit from phosphorus, not shredding armor but it does allow dealing damage to fire immune targets.

Expected Behavior: Phosphorus should be applying to all flamethrower attacks and for firestorm it should also mean shredding armor which does not seem to be working properly but the damage immunity bypass does.

reproduce: use the firestorm ability against armored targets while having the phosphorus perk. it should show that damage can be dealt to fire immune targets but armor will not be shredded as it should.

modlist:
[lwotc.txt](https://github.com/long-war-2/lwotc/files/14151031/lwotc.txt)

**Comment by Tedster59** [comment]
Fixing in https://github.com/long-war-2/lwotc/commit/afd563ab97e0e53efa815772406fa6ce0b0987c3
