### ISSUE TITLE
Smash and Grab spawning without anyone on intel job or scanning

### ISSUE THREAD

**Issue by torma** [long-war-2/lwotc#167]
A Smash and grab mission spawned for me in New Mexico without anyone on intel job or having the avenger scanning there.

Save file at:
https://drive.google.com/file/d/1YAimUor5Ltfqte0Q3JOK9_c6a0APRyqh/view?usp=sharing

Mod list:
[WOTC] New Target Icons
WOTC - Extended information
Evac All - WOTC
[WOTC] Additional Icons
[WOTC + Classic] Tacticalui Killcounter
Yet Another F1

**Comment by ansabalirai** [comment]
Just a hunch, but maybe you already had banked enough intel income (from previously scanning/rebel assignment) beyond the detection threshold and you just succeeded the roll quite late? One way to check is by inspecting the log and looking at the mission detection chances and whether they keep going up every (6?) hours even with no one assigned to intel and/or avenger scanning

**Comment by jmartinez989** [comment]
yeah I think this is a case of the mission spawning just a bit after you switched all rebels from intel to whatever else. I can assure you that I have not had ANY missions spawn at all without assigning rebels to intel or scanning there. You probably spawned it from the leftover intel that you had before you switched and it got spent on detecting that mission.

**Comment by torma** [comment]
Yep false alarm. Thanks for clarifying @ansabalirai and @jmartinez989 

`

	Line 1010: [0131.67] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 43648: [5198.96] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 43823: [5199.36] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 43947: [5266.42] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 43950: [5267.38] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 44010: [5314.59] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 44196: [5315.03] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 44199: [5315.34] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 44203: [5315.69] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 44207: [5316.08] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 44471: [5339.93] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 44509: [5353.28] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 44530: [5358.30] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 44535: [5360.02] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 44712: [5361.41] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 44717: [5368.45] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
	Line 44722: [5368.82] LWTrace: DISCOVERY: New Mexico : DetectionChance for Logistics : 6.9750
`
