### ISSUE TITLE
Unbreakable (Beta 1.2) chosen strength does not work

### ISSUE THREAD

**Issue by wdanny69** [long-war-2/lwotc#1672]
Issue: The Unbreakable chosen strength should make the chosen immune to rupture effects but it does not properly function and they will still be inflicted with rupture and take additional damage based on the amount applied.

Expected Behavior: Unbreakable should be making them immune to rupture such that no bonus damage is dealt.

modlist
tested with basic requirements

**Comment by Tedster59** [comment]
Fixed by commit https://github.com/long-war-2/lwotc/commit/f110303f9a15753acb6f379ee3a907fa9ff52d2d
