### ISSUE TITLE
Allow Dual Strike with Double Tap action

### ISSUE THREAD

**Issue by copyrite** [long-war-2/lwotc#1675]
Dual Strike cannot be activated with a Double Tap action. Tested with Sharpshooter, but the 1AP version is probably also affected.

**Comment by Tedster59** [comment]
Double Tap uses an ability allowlist, so just a config addition to fix.

![image](https://github.com/long-war-2/lwotc/assets/21696818/6dc073bd-1085-41ea-9489-8a86d923d400)

**Comment by copyrite** [comment]
Gonna check this now
