### ISSUE TITLE
Rescue Compound will spawn multiple evacs if you gain control of the vip and then hack the door (Beta 1.2)

### ISSUE THREAD

**Issue by wdanny69** [long-war-2/lwotc#1676]
Issue: multiple evacs can spawn if you first obtain the VIP in any other way than hacking the door and then proceeding to hack the door afterwards (for things such as the hack reward). This will also reset the evac timer forcing players to stay longer if they do not immediately hack in the same turn as the VIP is obtained.

Expected Behavior: As the VIP is already in XCOM's control, any further evac spawns does not make sense (unless it spawns in an area that can be destroyed).

modlist:
[lwotc.txt](https://github.com/long-war-2/lwotc/files/14229062/lwotc.txt)

save:
[save_compound multi evac.zip](https://github.com/long-war-2/lwotc/files/14229063/save_compound.multi.evac.zip)

Reproducing: use the soldier to throw a shaped charge to destroy the wall and gaining control of the VIP, afterwards proceed to hack the door and will result in a total of two evacs with the second evac being the used evac point. If checking on different turns it can be seen that the evac timer adjusts and resets to the base timer (effectively increasing the evac timer if done on later turns).

**Comment by Tedster59** [comment]
should be fixed by https://github.com/long-war-2/lwotc/commit/e82f1b155d58a5deda8d3ade2e517db56464c90c
