### ISSUE TITLE
Vektor Conventional is only base aim bonus change.

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#1678]
https://github.com/long-war-2/lwotc/blob/6c72a023bb4469d84ec82bf6ade35ee26938311d/LongWarOfTheChosen/Config/XComGameData_WeaponData.ini#L1892

**Comment by Clibanarius** [comment]
Noticed this when a car blew up due to a Vektor conventional misfire. Clearly lacking the environmental damage nerf LW2 standardized, use this.

VEKTORRIFLE_CONVENTIONAL_AIM = 10
VEKTORRIFLE_CONVENTIONAL_CRITCHANCE = 0
VEKTORRIFLE_CONVENTIONAL_ICLIPSIZE = 3
VEKTORRIFLE_CONVENTIONAL_ISOUNDRANGE = 35
VEKTORRIFLE_CONVENTIONAL_IENVIRONMENTDAMAGE = 1

**Comment by wdanny69** [comment]
unsure what you mean by base aim and as for the environmental damage it IS the same as lw2 as it is the same as all other weapons, being around 1.

this is just a consequence of how environmental damage works and unless it is completely removed then it can still result in sometimes destroying things

**Comment by Tedster59** [comment]
I just checked, environment damage is set to 5 in the base game config, I should at least set this back to 1.

**Comment by Clibanarius** [comment]
> unsure what you mean by base aim and as for the environmental damage it IS the same as lw2 as it is the same as all other weapons, being around 1.
> 
> this is just a consequence of how environmental damage works and unless it is completely removed then it can still result in sometimes destroying things

Except if it's not explicitly configured, it's NOT the same as LW2 because these guns did not exist in LW2 and were never configured in it as such to be imported. What Tedster already found is that the environmental damage is defaulting to 5 on the Vektor conventional.

**Comment by wdanny69** [comment]
ah sorry my bad, i was definitely looking at the other tiers as you said
