### ISSUE TITLE
A "Nerf" to Permanent Dark Events 

### ISSUE THREAD

**Issue by ProjjectDelta** [long-war-2/lwotc#168]
After watching a Favorite Twitch Streamer of Mine get, Particularly Frustrated at his inability to be able to stop two WOTC Dark Evens from Occurring (Undying Loyalty and Sealed Armor for those who are Curious), Me and a Mod of his, Planned two potential Nerf Proposal's to Dark Events.

The First one was created by me, and supported by the Mod, in which after a Dark Event has been created, a very rare mission, in which you attack a Alien Research Facility, and, after you break stealth, Reinforcements will continue to be summoned every 2 turns, until finally, you hack a device that turns of the "Distress Beacon", in which then you can finish off all enemies and complete the mission (This can be changed), upon completion it turns one permanent dark event, into a Temporary One (How long this is should, in all honesty, be up to you, I wouldn't be to good at it, I also figured it should be temporary, due to the Sudden lack in production and training would only affect new soldiers, not old ones.) This would help Early Runs (At least in this stage of the game, Im not sure what restrictions you will be putting on Dark Events Later in Development, like In Long War 2) These Dark Events can be Re-Researched by the Aliens of Course.
Oh yeah, The Mod asked me to Put this in here 
 FirstMonthNumDarkEvents=0 NumDarkEvents=0 DarkEvents.RemoveItem(CreateCounterintelligenceSweepTemplate());
Probably some kind of codding to put in the mission? Might not be exactly what I said though, Im not a Coder myself, so I cant check.

Here is my Second Idea, Created by me, and not supported by the Mod, Its pretty much the same as the last mission, but less luck based, in which you can send out a Covert Operation to locate a Alien Research Facility instead of it appearing randomly, Due to Covert Ops Only Refreshing every Supply Drop, it means that it is still rare, as well as that there is no chance you can INSTANTLY find a Research Facility for a Project that just finished, due to Dumb Luck, you will at least have to wait sometime, of course, the requirement to do these Covert Ops should change depending on how big the Dark Event is (Again, you can be the Judge of it, Im not the best at Balancing)
And that is it, Hope to hear why either one of these Suggestions are bad ideas (Or Good ideas!)

**Comment by jmartinez989** [comment]
As far as I know the 2 dark events that you mentioned (Undying Loyalty and Sealed Armor) were not permanent. I have cleared lwotc and when those Dark Events triggered they definitely did not persist through the whole campaign.

I do like the idea of reversing some permanent dark events like alien conditioning to be temporary. This is definitely a good way of introducing some more counterplay to the dark events.

**Comment by pledbrook** [comment]
Except those tactical dark events are there to make sure that the enemy units scale with XCOM.

**Comment by ProjjectDelta** [comment]
Honestly, The Mod and I wrote this up to counter some of the Dark Events that would be, very, annoying to deal with on a constant scale, and thinking they were permanent (These Dark Events are Undying Loyalty, High Alert, Dark Tower, And Show of Force), because they all Sounded like events that WOULD be Permanent,
 Undying Loyalty essentially screwed over Shinobi's Early game, especially if they were used to finish off the last enemy, and its the last turn, and a Zombie comes back, it caused alot of...unplanned Losses and Wounds do to some big DMG that can come,
 High Alert is...well...High Alert, permanently 
Dark Tower would make things harder in the long run, especially for Long Missions, causing people to become Tired in one mission, something that cant really be afforded in a game like this
Show of Force, This one essentially means "Increase the Difficulty of a Mission by 1 Rank) (Not one Strength),

**Comment by ansabalirai** [comment]
Unless you are playing with Grim Horizons, these DEs should not be permanent. As mentioned above, LW2 split DEs into two groups: tactical and strategic. The former represent scaling up the strength of its forces over time and are part of the balance of the game itself and are hence permanent; the latter are meant to cripple XCOM at the strategic layer and usually last for about a month. For more details, please check: https://www.ufopaedia.org/index.php/Dark_Events_(LW2)
For WOTC specific dark events, since almost all of them correspond to strategic DEs, I imagine they would not be made permanent for LWOTC either.

**Comment by ProjjectDelta** [comment]
Feel Free to Close this issue, I didnt understand that it was only permanent if it said "Tactical Research", because I was expecting Temporary Events to have "Strategic Operation" at the Beginning of it, although on my last note, can you add something like that to the beginning of these Dark Events (Like make Undying Loyalty,  SQ: Undying Loyalty) it would help allow for newer Long War Player's who only have the Wiki to go off of, to understand that they are temporary, Dont tell me if you can or can not, thank you for your time, and thank you for help!
