### ISSUE TITLE
Using multiple Suppression's onto a single target will only trigger one leaving the others not firing and stuck in the animation

### ISSUE THREAD

**Issue by wdanny69** [long-war-2/lwotc#1681]
Issue; having multiple Suppression's onto a single target (NOT AREA SUPPRESSION) will only trigger one of them to fire if the target moves, resulting in the suppression's that have not fired to be stuck in the suppression animation (I cannot tell whether the effect has stopped or not for those that have not fired) until they suppress again and the target dies.

Expected Behavior: Multiple suppression should be able to fire a reaction shot similar to area suppression. If multiple is allowed to fire and process that may also help in removing the animation bug.

modlist
[lwotc.txt](https://github.com/long-war-2/lwotc/files/14320152/lwotc.txt)

save
[save_bug_suppression_stuck_anim_1.zip](https://github.com/long-war-2/lwotc/files/14320155/save_bug_suppression_stuck_anim_1.zip)

how to reproduce:
simply use suppression (NOT AREA SUPPRESSION) onto the purifier with both gunners

**Comment by Tedster59** [comment]
This one should be fixed on Experimental.
