### ISSUE TITLE
Income without anyone on supply job

### ISSUE THREAD

**Issue by torma** [long-war-2/lwotc#169]
New Mexico generates income for me while noone is on supply job.

Logs:
Launch-backup-2019.05.18-00.38.10.log (12 hits)
	Line 3215: [0336.80] LWTrace: [Resupply New Mexico] Previous income pool: 21.6000
	Line 3218: [0336.80] LWTrace: [Resupply New Mexico] Final income pool: 32.4000
	Line 3456: [0364.70] LWTrace: [Resupply New Mexico] Previous income pool: 32.4000
	Line 3459: [0364.70] LWTrace: [Resupply New Mexico] Final income pool: 43.2000
	Line 19246: [1556.22] LWTrace: [Resupply New Mexico] Previous income pool: 43.2000
	Line 19249: [1556.22] LWTrace: [Resupply New Mexico] Final income pool: 54.0000
	Line 19463: [1580.56] LWTrace: [Resupply New Mexico] Previous income pool: 54.0000
	Line 19466: [1580.56] LWTrace: [Resupply New Mexico] Final income pool: 64.8000
	Line 19646: [1586.46] LWTrace: [Resupply New Mexico] Previous income pool: 64.8000
	Line 19649: [1586.46] LWTrace: [Resupply New Mexico] Final income pool: 75.6000
	Line 19874: [1605.82] LWTrace: [Resupply New Mexico] Previous income pool: 75.6000
	Line 19877: [1605.82] LWTrace: [Resupply New Mexico] Final income pool: 86.4000

Launch.log (44 hits)
	Line 9420: [1615.66] LWTrace: [Resupply New Mexico] Previous income pool: 86.4000
	Line 9424: [1615.66] LWTrace: [Resupply New Mexico] Final income pool: 86.4000
	Line 9779: [1684.50] LWTrace: [Resupply New Mexico] Previous income pool: 86.4000
	Line 9783: [1684.50] LWTrace: [Resupply New Mexico] Final income pool: 86.4000
	Line 9993: [1727.51] LWTrace: [Resupply New Mexico] Previous income pool: 86.4000
	Line 9997: [1727.51] LWTrace: [Resupply New Mexico] Final income pool: 86.4000
	Line 10190: [1803.86] LWTrace: [Resupply New Mexico] Previous income pool: 86.4000
	Line 10194: [1803.86] LWTrace: [Resupply New Mexico] Final income pool: 86.4000
	Line 10342: [1805.22] LWTrace: [Resupply New Mexico] Previous income pool: 86.4000
	Line 10346: [1805.22] LWTrace: [Resupply New Mexico] Final income pool: 86.4000
	Line 18808: [2955.16] LWTrace: [Resupply New Mexico] Previous income pool: 86.4000
	Line 18812: [2955.16] LWTrace: [Resupply New Mexico] Final income pool: 86.4000
	Line 18989: [2971.64] LWTrace: [Resupply New Mexico] Previous income pool: 86.4000
	Line 18993: [2971.64] LWTrace: [Resupply New Mexico] Final income pool: 86.4000
	Line 25188: [3616.98] LWTrace: [Resupply New Mexico] Previous income pool: 86.4000
	Line 25192: [3616.98] LWTrace: [Resupply New Mexico] Final income pool: 86.4000
	Line 25413: [3704.78] LWTrace: [Resupply New Mexico] Previous income pool: 86.4000
	Line 25417: [3704.78] LWTrace: [Resupply New Mexico] Final income pool: 86.4000
	Line 25676: [3756.18] LWTrace: [Resupply New Mexico] Previous income pool: 86.4000

Save file and logs at:
https://drive.google.com/file/d/1kBYYjP9T4c-txcoXJoaM1n_TfSYsEbcN/view?usp=sharing

Mod list:
[WOTC] New Target Icons
WOTC - Extended information
Evac All - WOTC
[WOTC] Additional Icons
[WOTC + Classic] Tacticalui Killcounter
Yet Another F1

**Comment by pledbrook** [comment]
This is probably vanilla behaviour and requires highlander changes to implement. The original LW2 added a few events around end-of-month processing, one or more of which I suspect are required to sort out supply income.

**Comment by pledbrook** [comment]
Actually, it looks like this is working as expected. Did you have people on supply at some point in the past in that region? It looks like you did. And then you took everyone off supply, which is when the resupply stopped increasing at 86.4. That number represents accumulated supplies over the life of the haven, not the current monthly income.

**Comment by torma** [comment]
I had people on supply job before the previous supplydrop.
I still think there is a problem. I was close to the end of the same month so I fast forwarded to take some screenshots:
![20190605002055_1](https://user-images.githubusercontent.com/26032734/58917801-17d83e00-8728-11e9-8fb6-a728cfa934fc.jpg)
![20190605001921_1](https://user-images.githubusercontent.com/26032734/58917807-1eff4c00-8728-11e9-891f-e60d043cfb1f.jpg)

So as you can see. As I receive the income at the end of the month and the supply income from the region doesn't get reset to 0.
New save file:
https://drive.google.com/file/d/1_GupwNANkQiL8DFvbZD8xTSvrA5QuShB/view?usp=sharing

**Comment by pledbrook** [comment]
That latter behaviour is the same as described in #208 I believe, which is now fixed.
