### ISSUE TITLE
Return Fire should change "enemy fire" to "enemy attacks"

### ISSUE THREAD

**Issue by wdanny69** [long-war-2/lwotc#1699]
issue: return fire states that it triggers when an "enemy fires" but it can trigger on other attacks such as aoe moves or melee attacks

proposal" should change it to enemy attacks to give a better representation that it can trigger on many attack types

**Comment by wdanny69** [comment]
the localization was changed for the dark event but does it change the ability?

**Comment by wdanny69** [comment]
also realizing the DE states "missed" attacks but i'm not sure if that is how return fire works either? which return fire ability is it using as I do recall we made a new version for the xcom row to work with primary weapons as the original was with the pistol.

**Comment by copyrite** [comment]
Looks to me that we still reuse the _gameplay tag_ for Officer/Priest Return Fire is still the same as in base game, even though the DE is not the same (we have our own that makes it a sitrep).

The DE ability `DarkEventAbility_ReturnFire` is defined in `X2Ability_DarkEvents.uc` of the base game. It's building an `X2Effect_ReturnFire` with `bOnlyWhenAttackMisses = true`.

Our `PrimaryReturnFire` is defined in `X2Ability_XMBPerkPackAbilitySet`. It's building an `X2Effect_ReturnFire` with `bOnlyWhenAttackMisses = false`.
