### ISSUE TITLE
T4 Chosen Assassin HP not following proper scaling based on difficulty

### ISSUE THREAD

**Issue by wdanny69** [long-war-2/lwotc#1700]
Issue: Chosen Assassin HP is not following proper scaling based on difficulty

Expected Behavior: Chosen have their HP scale by 0.5/0.65/0.8/1 based on difficulty level. The T4 Assassin specifically does not follow that scaling. With 64 HP on legend, the HP should be about 32/42/52/64 vs 23/32/40/64 like it is currently.

**Comment by copyrite** [comment]
Fixed in f8c0d3e9ebc2c372e8817b6d77152c028df533e0
