### ISSUE TITLE
Min/max dodge stats going beyond specified limits

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#171]
Looking at LW2, with hidden potential on at 50%, the min/max dodge values a rookie can get is -10/+10, but I seemed to have been blessed by rookies with up to 19 dodge. 
My instinct is that the 478 point limit is not being respected according to [LW2 stats wiki page](https://www.ufopaedia.org/index.php/Soldiers_(LW2)) 

See screenshot below
![20190518150608_1](https://user-images.githubusercontent.com/15093261/57975520-7909be80-797f-11e9-9bb1-50c644a443bb.jpg)

**Comment by micahswab** [comment]
Based on all my experience and information on the wiki, this is expected behaviour. Default dodge is 5 and NCE gives +/- 15. Wiki source: https://www.ufopaedia.org/index.php/Soldiers_(LW2)

**Comment by micahswab** [comment]
I misunderstood the wiki. It says default is 5, min is -10, and max is 15. I think this is incorrect as it's inconsistent with how the other stats are distributed. The XComLW_Toolbox.ini file is a better source for the expected range. I'll take a look at it later to confirm if someone doesn't beat me to it.

**Comment by pledbrook** [comment]
Yeah, configuration says +/-15 on top of the base dodge. So 19 is within range. And it's not possible to judge whether the 478 point limit is honoured without knowing what the psi offence is.

I suspect the 50% NCE configuration is not working (I'm not familiar with it to be honest).

**Comment by micahswab** [comment]
Thanks for checking! I updated the wiki to match the configuration.

**Comment by pledbrook** [comment]
@ansabalirai Is it OK to close this? Are you happy with the explanation?

**Comment by pledbrook** [comment]
Going to close. Reopen if you think there's still an issue here.
