### ISSUE TITLE
Alien rulers not showing up on missions after doing mission with viper king.

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#173]
As the title states. They do actually show up on missions like the avenger defense and I had one show up on the advent tower before leviathan but all other missions seem to not spawn them. No real save file but can reproduce it easy.

**Comment by pledbrook** [comment]
They're only supposed to be added to facilities. That's probably not happening, because I don't think the appropriate code is enabled.

**Comment by jmartinez989** [comment]
Well that is if you choose to integrate the dlc with wotc. If you uncheck that box and then check the 2 below the dlc will run as the game used to and rulers will not spawn until you have done the dlc mission first (the one with all of the vipers).

**Comment by jmartinez989** [comment]
In vanilla lwotc I had the rulers spawn on things like council missions and gops after the first encounter in the dlc mission.

**Comment by torma** [comment]
If I remember correctly vanilla LW2 had them on HQ assaults, troop columns, resupply and UFO defense. They also showed up pretty late. I usually had plasma by the time the berserker queen showed up.

I would also keep it this way though. On legend they can easily squad wipe you unless you can get the jump on them from range, can stun&freeze them or kill them with an overwatch trap.

**Comment by jmartinez989** [comment]
> If I remember correctly vanilla LW2 had them on HQ assaults, troop columns, supply raid and UFO defense. They also showed up pretty late. I usually had plasma by the time the berserker queen showed up.
> 
> I would also keep it this way though. On legend they can easily squad wipe you unless you can get the jump on them from range, can stun&freeze them or kill them with an overwatch trap.

Ahh actually this might be the case then. Yeah I don't remember alien rulers showing up on anything other than old supply raids, troop columns and UFO (I assume they can show up on HQ raids and alien facilities. They don't seem to be showing up on GP missions though).

**Comment by ansabalirai** [comment]
If they are indeed only showing up on untimed missions, can confirm that this is the same as in LW2 and should be ok to keep in my opinion

**Comment by jmartinez989** [comment]
ok so this looks like a case of me just not remembering where they spawned. Closing then.
