### ISSUE TITLE
Lightning Slash unusable with last action unless in melee range

### ISSUE THREAD

**Issue by copyrite** [long-war-2/lwotc#1743]
Expected behaviour: If you have only 1 action remaining, you can use Lightning Slash to attack an enemy 1 movement away, i.e. use it as a bargain bin Fleche.

Actual behaviour: If you have only 1 action remaining, you can only use Lightning Slash to attack an adjacent enemy.

What causes this is that it has `MovementRangeAdjustment` of 1. That is, you can use all of your actions *minus one* to dash to the target. Suggested solution is to give LS the "snap shot" treatment: LS the perk gives two activateables. One of these would be the current LS but with the added condition that you have at least 2 actions (of suitable type), The other one would be a copy of base game Slash that's only usable when you have 1 action remaining. The two abilities should have the same localization and shared cooldown.

The only base LWOTC class that would care about this is Gunner (no dashing slash at Squaddie rank, LS in XCOM deck).

**Comment by Tedster59** [comment]
closing since PR is merged
