### ISSUE TITLE
Templar rebalance suggestions

### ISSUE THREAD

**Issue by torma** [long-war-2/lwotc#175]
These guys can learn very strong melee and defensive abilities. So they go in, kill a target (or several with reaper) and then act as an unkillable mimic beacon for the rest of the turn.
I see the following problems:

1. Rend always hits
2. Parry and Deflect are free
3. Templars can train Fortress and Sustain

As with reapers I will try to provide multiple suggestions in a staged fashion and it can be decided later which ones to implement or integrate.

1. There is a mod which actually aims to fix the first issue I have. I think integrating it would help:

Templar Rend Can Miss
https://steamcommunity.com/sharedfiles/filedetails/?id=1134095383
I have not yet tried this mod. I assume Rend would still trigger momentum. I would also make some changes to the baseline:

1. Don't add them any crit chance in compensation 
2. Make the base hit chance depend on aim

Preferably they would still get the benefits of aim increasing abilities like holotarget and focus fire.
I don't know of any other mods which would try to address the issues I mentioned.

2. Remove abilities, Make parry and Deflect cost 1 focus

Remove Fortress and Sustain as a trainable ability. In other words: make templars mortals.
I'm not sure how much effect the focus cost would have. The only thing I'm expecting make them vulnerable to shots when there are multiple enemies active.
So this would mean that if there is a target to tank the templar could still present himself as an easy target and parry shots. This would cost focus and lower the damage output on the following turns and also limit other abilities requiring focus.
Or they could just move into cover and keep the focus. Templars would still have very strong melee damage, would still be able to tank more reliably than any other class and also be able to sometimes stun targets with Rend.

But at least this way they wouldn't be ridiculous like: Run into the middle of a rainbow pod. Kill almost everything with bladestorm. Tank and kill the survivors and the possible other pods triggered in the process with Deflect and Reflect. Take rockets, grenades, poison, fire, acid to the face and after pulling of all this finish with a flawless mission.

3. Rework class tree, some ability tweaks

I see the templar to be able to fill three different roles:

1. A melee tank, who can take out weakened targets or just weaken targets himself.
2. A psy support who can help protect allies, debuff enemies.
3. An offensive psy caster.

There are some holes in the templar tree which could just be filled in with melee abilities and move around the rest.

| Rank | Psiblade | Dynamo | Sage |
| --- | --- | --- | --- |
| Squaddie | Rend | | Focus |
| Lance Corporal | Parry | Pillar | Volt |
| Corporal | Lightning Reflexes | Shadowstep | Aftershock |
| Sergeant | Bladestorm | Mentally Awake | Void Conduit |
| Staff Sergeant | Deflect | Overcharge | Channel |
| Tech Sergeant | Reflect | Invert | Deep Focus |
| Gunnery Sergeant | Arc Wave | Exchange | Ionic Storm |
| Master Sergeant | Reaper | Amplify | Ghost |

4. AWC abilities or XCOM abbilities for training, New assets, upgrades

Most of the offensive AWC abilities don't make sense for a templar. The ones which could remain are: **Quick Study**, Executioner, Boosted Cores, Biggest Booms, Full Kit, Bombardier, **Sprinter**, Heat Warheads, Volatile Mix, Salvo, **Combat Fitness**, **Lone Wolf**, Damn Good Ground, Sapper, **Cutthroath**, **Blademaster**
These are not a lot. I highlighted the ones I would take. Which makes it even less. I think this is not a problem but the others would need to be removed for the class as options for offensive abilities.
The defensive abilities are mostly fine. The following would need to be removed: Cool Under Pressure, Ever Vigilant, Shadowstep, Lightning Reflexes, Suppression, Covering Fire, Kill Zone, Close Combat Specialist, Sentinel, Rapid Reaction, Guardian, Aim.

As for trainable XCOM abilities at the training center if the melee abilities I proposed get integrated to the templars ability tree then I think it would make sense to a the following: Sprinter, Cutthroath, Blademaster, Infighter, Combatives (as expensive upgrade for 25 points always), Combat Fitness (as expensive upgrade for 25 points always)
I would also remove all trainable pistol abilities.

They don't really have a secondary weapon. I argue they would need a psy focus of some sort instead of the auto pistol. They could start out with just nothing but an empty seconary slot (or just put a walking stick in there as a placeholder).
They could get a focus after unlocking psyonics. Which would give them a psyonic ability after each upgrade. I think these could be existing psyonic powers using the LW2 versions.
Level 1 Focus: Inspire or Fuse
Level 2 Focus: Stasis or Soulfire
Level 3 Focus: Solace or Null Lance
I thinking about one of the abilities for each level. I don't think there needs to be a choice involved but it would be possible to make an offensive and a support psy focus. So at level 3 focus would have 3 abilities. I also think that the costs and requirements would be the same as for psy amps but in addition the Focuses would need to be upgraded. So to build a level 2 Focus one would need to use a level 1 Focus as one of the parts.

The templar gauntlet on the other hand doesn't need any updates. I would just leave the valnilla version with the caveat that they need to be manufactured individually.

**Comment by DerAva** [comment]
Saw this in the 1.6 milestone, and wanted to share some thoughts here:
It feels like you are viewing the Templar power level with a vanilla lens, and not in a LW2 context. In the current state of the game I'd say Templars are barely viable, but you are probably better off bringing a sword shinobi anyway. The suggested changes would put them firmly into the "permanent Haven advisor" territory.  
The main weakness right now is their low damage, which does not scale well with LW2 health pools. This in turn translates into focus generation issues, so I doubt that Templars will reach the power level that they have in a vanilla wotc setting.

**Comment by torma** [comment]
Damage isn't my concern. To me it looked fine but it's true I have only ever reached the mid game with them.

**Comment by captainbeastfeast** [comment]
I disagree, templars as well as skirmishers need to be stronger to balance them with the (currently) OP reaper class. Either giving them guaranteed early access to reaper skill or giving them more focus based skills would help with re-balancing.

RE heroes: they are meant to be stronger than other classes right up into the late game because you only get 1 or two of each of these unique soldiers.

**Comment by torma** [comment]
Well we have different tastes. I don't like OP classes. I also think skirmishers are fine since #79 
That being said it might be that the damage is fine on legend but needs a bump on lower difficulty levels.

**Comment by rrnwang** [comment]
I'm of the opinion that Reapers' Shadow ability needs a nerf, while Skirmishers and Templars need a buff. Currently Reaper is broken AF on missions with low infiltration. While Templars really can't go in on ANY missions where you might trigger another pod (due to how much more potent pods are in LW). I play my Shinobis like a scout. They usually never attack unless I'm desperate because I don't want to trigger multiple pods. The Reaper's "Silent Killer" may need to be changed to like 90% chance of not revealing instead of 100% chance of not revealing.

The buff for templar, IMO is some increase to Dodge stats as they level up. Currently, once they get in, they can't get out - even with momentum, they are still in the range of too many units. I have not had a mission where the Templar did not take damage (to hp or ablative) because using rend pretty much guarantees putting them in harm's way. 

Regarding Skirmishers, they are more "dull". Their biggest "sell" seems to be the early game grapple. In LW2, Rangers have "light 'em up", so their "marauder" ability isn't impressive. Justice and Wraith are just slightly more accurate than shooting; wraith is often suicidal because you do not control where the Skirmisher lands - usually in the open. In late game they kind of act as a secondary Officer since they can use a move that's basically "Command" on anyone.

**Comment by tunbridgep** [comment]
I think the other thing people overlook is that they basically render Psi Operatives obsolete

**Comment by rrnwang** [comment]
Wat? No. PsiOps are still pretty OP with the guaranteed 1 turn stun via Stasis, and guaranteed hit Via Soulfire. Additionally, bastion allows you to crows everyone together with no fear of explosive, fire, or poison; while Quick Study allows them to all become Officers quickly. The biggest problem with them is their training time for new abilities - which if you're running a huge barrack, shouldn't be an issue.

**Comment by Grobobobo** [comment]
The suggestion was already taken into consideration in #717.
