### ISSUE TITLE
Chain lightning only targets 4 units instead of 5 and targeting method seems different than volt (which was the intention)

### ISSUE THREAD

**Issue by wdanny69** [long-war-2/lwotc#1763]
Chain lightning currently only targets and hits up to 4 targets instead of 5. There was an extra focus ability that was made specifically for this but it seems to not be working or there was some change somewhere in LWOTC"s development that caused it to stop working. I can't confirm or have anything but I believe pre 1.0 that it did work.

The targeting also seems to be a bit different than how it was originally made. The targeting should be similar to how templar's volt work in that you choose a target and within an area also hits up to a certain amount of targets. How it actually currently works is that it simply looks for any target within an area bounces to them and then recalculates the area where it should bounce to so it can theoretically reach a large line of enemies assuming it is within range rather than a central target.

**Comment by Tedster59** [comment]
had to fix some typos in the ability names/mappings for the focus mechanic.

![image](https://github.com/user-attachments/assets/b84a6947-80a7-4f82-a4c4-db15b3bf7138)

**Comment by wdanny69** [comment]
https://github.com/long-war-2/lwotc/commit/572a2a3456e164ad1f864659897d5a6ec26b7488

issue now resolved
