### ISSUE TITLE
Smash and Grab mis-configure ObjectiveName?

### ISSUE THREAD

**Issue by fatdes** [long-war-2/lwotc#1766]
https://github.com/long-war-2/lwotc/blob/master/LongWarOfTheChosen/Config/XComMissionDefs.ini#L2691

should this be configured with `ObjectiveName="MinimumCrateRecovery"` instead of `ObjectiveName="Recover"`

**Comment by Tedster59** [comment]
No, MinimumCrateRecovery is for the "new" WOTC mission type which has 12 crates, and you need to get 4 for the mission to be marked a success.  "Recover" is correct for the old school LW2 Smash n Grabs.
