### ISSUE TITLE
Too many Point of Interest scans

### ISSUE THREAD

**Issue by The13Inquisitor** [long-war-2/lwotc#178]
So, I just got three POIs in a row from the one Intel package.

The Vanilla behaviour for POIs seems to be creeping in.
[save_AUTOSAVE- Campaign 62, Mission 4_1.zip](https://github.com/long-war-2/lwotc/files/3220263/save_AUTOSAVE-.Campaign.62.Mission.4_1.zip)

**Comment by pledbrook** [comment]
Was this after a specific mission? Did you do an ambush or some other type of vanilla mission?

**Comment by The13Inquisitor** [comment]
Just a plain old VIP Extraction.

Then suddenly, I've gotten three POI scans in a row one after the other.

**Comment by pledbrook** [comment]
Ok, thanks. I got a series of POIs after an ambush mission, which is generated by the base game, not LW2. But that doesn't sound like the same situation as yours. So could be random. Ugh.

**Comment by The13Inquisitor** [comment]
No, this was a Vanilla mission as well. So maybe it's vanilla missions that are causing the behaviour?

**Comment by pledbrook** [comment]
Yes, but VIP extraction is generated by LW2. At least the standard one is. So it should t be triggering follow up POIs. Perhaps the POI rewards themselves are messing things up.

**Comment by The13Inquisitor** [comment]
Maybe, because like I said, I got three in a row without any interruptions.

**Comment by pledbrook** [comment]
Haven't seen this reported since, so assuming fixed.
