### ISSUE TITLE
Disable Interchangable Upgrades Breakthrough

### ISSUE THREAD

**Issue by The13Inquisitor** [long-war-2/lwotc#179]
The functionality of Interchangeable Upgrades is included in LW as standard, so having it as a Breakthrough is redundant.

**Comment by pledbrook** [comment]
It probably makes sense to review the other breakthroughs as well.

**Comment by pledbrook** [comment]
These are configured in `X2StrategyElement_XpackTechs.uc` and `XComStrategyTuning.ini`.

**Comment by The13Inquisitor** [comment]
Never done .ini edits. I've never tried my hand at coding, so I didn't want to screw things up.
