### ISSUE TITLE
Squad select is auto filling empty squads

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#18]
If a new, empty squad is created for a mission (because no other squad is available), then squad select should not be allocating any soldiers to it or displaying them.

**Comment by ansabalirai** [comment]
I think there is an option if you have MCM installed to disable that autofilling. It seems to be working for me

**Comment by pledbrook** [comment]
robojumper's Squad Select fires a 'rjSquadSelect_AllowAutoFilling' event that can be used to override this on a per-mission basis. We probably need to override on every mission, or at least every mission with a squad assigned (which I think is every mission in LW2 because it creates a squad if necessary).

**Comment by pledbrook** [comment]
So I've added the event listener that overrides this behaviour, but it means you can't change id via Mod Config Menu. It seems that we can either support the config option, but leave the default as autofill enabled, or implement the listener, in which case you can never enable autofill. Bleh.

**Comment by pledbrook** [comment]
Fixed
