### ISSUE TITLE
Zombie dropping loot

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#180]
This has a fix in the original LW2, probably in the highlander code. Just load the following save file and kill the Sectoid:

[save_Bug_ZombieDropsLoot.zip](https://github.com/long-war-2/lwotc/files/3220570/save_Bug_ZombieDropsLoot.zip)

**Comment by tracktwo** [comment]
See `XComGameState_Unit.OnUnitDied` for this fix as well as a fix for bleeding out units being reported as killed by themselves.

**Comment by pledbrook** [comment]
This issue depends on [X2WOTCCommunityHighlander#682](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/682).
