### ISSUE TITLE
Smoke can crash the game

### ISSUE THREAD

**Issue by Aurelicornus** [long-war-2/lwotc#183]
I have a rare bug in some missions where smoke made by smoke grenades, Technical concussion rocket and other similar perks, crash the game. From what I tracked, the bug kicks when some animations are playing, like camera pointing toward targets, launching evac flare, ecc, and if there are some units inside the smoke cloud.
I have this bug also in Long War 2 for the base game (without WotC but with the DLC), seems related to the mod code. I use some other mods, but they are all cosmetic (armour, voicepack etc) and not gameplay modifications, therefore I don't think they are the cause.
I have not anymore the saves where the bug occurs, but I can ship one next time I hit it again.

**Comment by pledbrook** [comment]
Without a save, can't do much about this. I haven't had any crashes due to smoke grenades myself.
