### ISSUE TITLE
Suppressing stunned enemies move them in another tile

### ISSUE THREAD

**Issue by Aurelicornus** [long-war-2/lwotc#184]
There is a glitch where If an enemy is stunned (usually from the Assault arc thrower) and is suppressed by a soldier with the Suppression perk (ie Gunner), the enemy is moved to another tile:
* The program doesn't play no animations, but immediately relocate the units somewhere else.
* The stun effect is not removed: the unit remains stun in the new tile.

The bug seems kicks when the stun wears out, but the unit is still under suppression: the game doesn't remove the stun effect to the unit, but activates anyway the logic to move it in a safer location out of the range of the suppression.
Also, I met this bug when I flanked these units with an unit (usually an Assault), but I'm not sure if this condition is needed to kick the bug in.

**Comment by pledbrook** [comment]
Probably won't look into this, sorry. Not a high enough priority (and I haven't heard of it since).
