### ISSUE TITLE
Thoughts about the new WotC gameplay mechanics

### ISSUE THREAD

**Issue by Aurelicornus** [long-war-2/lwotc#185]
I feel the best improvement on the gameplay that WotC introduces is the score-base system and the new Training Center functions for add new perks to the units. I think is a bigger improvement than Vanilla (with or without Long War 2) because the new system encourage "clever tactics": the player is rewarded of points each time shoots enemies from high elevations, or flanks them, that are at same time the cornerstone concepts of this game itself (you should rely on flanking or aim bonus than just only being luck with your shots).
I think, therefore, that the new Training Center mechanics should be left untouched: the player can unlock extra perks for their soldiers, but only because they are good with the game. Is a reward that really felt me that all my efforts to play smart are rightly rewarded, and have a long standing effects on my play style that extends over the single map.
In short: it really makes the game more fun to play for me. :)

I think the new Training Center and Faction units have just need only of little tweaks for balance them inside LwoC, although my experience in the game is that they already works quite well without reworking. Even better, the LW options even improve their gameplay concept, ex I found that the Shadowkeeper is the best object for the Reapers because it allows an extra cloaking charge if they kills a target with that gun. Reapers and Shadowkeeper are a powerful combination, but they fits in the unit idea along with Claymore, Sting and similar perks.
My idea is that gun training now should go in the 4th row "Xcom" misc perks, and these should be chosen randomly for each soldier like done for the extra perks randomly proposed there. Not all soldiers will receive pistol perks, and not everybody the same ones.
My experience with the guns in Long War 2 is that I don't find use for them in all classes, for some is better leave the equipment slot of other stuff (grenades or armour), while for these I would have more use of different perks (btw, I understand the reasoning of LW2 behind the AWC reworking, but I explain just my gameplay experience here).
Randomize pistol skills in the Training center is a fallback to vanilla non-long war game, but I feel is a good compromise to mitigate the new WotC system with the AWC concept of LW2. In some way, I feel is a good way to introduce a bit of randomization into perk training, because you cannot built two units in the same way for use effectively them, in the same way like every unit in Long War has not the same stats and everybody is suited better toward a certain build than another. Random perks throws another factor you need to keep in count, but the ability to choose which ones at the same time empower the player to suit these to its strategy, instead to be at mercy of the random rolls. Is a middle way to offer unique units, and leave the player to play with what he likes most.

Another needed tweak for me is fill all the perks row for Factions units: in Vanilla these units are already powerful, and despite have less perks, in the mods they still are anyway. I think the better way is fill the missing slot with some bonus buff (like Lone Wolf for Reapers), because the vanilla perks already seems quite good for the mod (or maybe some very little tweak).
@pledbrook I have some ideas for these tweaks: which are the files that keeps the class perk trees for the Training center? I already edited the tree lists for Xcom 1 Long war in past, if I have time I could tweak something for WotC.

**Comment by Grobobobo** [comment]
The direction for XCOM AP row and faction hero classes has been mostly picked.
