### ISSUE TITLE
Reduce rewards from Smash N Grab

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#188]
The Basic2 and Basic3 crates come too soon and give XCOM a ton of resources. I suggest we get rid of the PCS crates (and maybe the elerium core ones), delay when Basic2 and Basic3 turn up to later in the campaign, and reduce the overall resource amount by 20-30%.

**Comment by jmartinez989** [comment]
I definitely would not get rid of the elerium core crates, in certain cases I would rather have them then supplies in some cases. I would get rid of the crates that reward PCS and weapon upgrades. Make it alloys, supplies, crystals and cores only.
