### ISSUE TITLE
Shred not applying on shielded units

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#190]
This happens in the save file below, where a shielded unit is shot by an XCOM soldier with Shredder and damaged enough to take an HP loss. And yet the armour isn't shredded.

Use Joey Martinez and Shoot Shieldbearer:

[save_Shoot_Shieldbearer_with_Admin_-_Shredder.zip](https://github.com/long-war-2/lwotc/files/3242951/save_Shoot_Shieldbearer_with_Admin_-_Shredder.zip)

**Comment by Favid** [comment]
This is a weird one that might actually be a base game bug. It appears to be a weird interaction between Pierce and Shredding. Martinez has AP Rounds equipped and does not shred any armor in this scenario. If you add Shredder to a soldier without AP Rounds (AddAbility Shredder in console), then they will shred as expected.

**Comment by pledbrook** [comment]
I'm not sure I'm ever going to get round to this, so removing from milestones.

**Comment by pledbrook** [comment]
And closing. If it crops up again, can potentially take another look.
