### ISSUE TITLE
Defense Matrix - No XCOM Turrets during Avenger Defense

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#195]
Greetings.

I had the defense matrix up (and upgraded with an engineer staffed) when I got intercepted by the UFO. The XCOM turrets, however, did not show up.

Thanks,
Black Rose.

**Comment by jmartinez989** [comment]
Can confirm this is not happening. Could be that LW2 has it's own UFO defense mission type? I know that they were showing up in vanilla LW2.

**Comment by MiserablePileOfBugs** [comment]
LW2 seems to have it's own Avenger Defense Mission. From XComMissionSource:

`+arrSourceRewardMissionTypes=(MissionSource="MissionSource_AvengerDefense", RewardType="Reward_None", MissionFamily="AvengerDefense_LW")`

I'll upload a save when I get this mission.

**Comment by Ankaridan** [comment]
In WOTC, Defense Matrix turrets all gain Squadsight (which is a little game breaking). However the construction of the Matrix is supposed to reduce the success rate of Chosen sabotage attempts but has a vanilla bug where it does not function: see [Defense Matrix Sabotage Fix](https://steamcommunity.com/sharedfiles/filedetails/?id=1135867452)

**Comment by Maebalzurakin** [comment]
In addition to no turrets in this mission type, any reinforcements are getting no action points.

**Comment by tunbridgep** [comment]
On top of this (not really a bug), the defence matrix is sort of useless in vanilla. Maybe the devs could think about making it a bit more useful?
