### ISSUE TITLE
Double Tap - Not penalized from Squadsight

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#196]
Greetings.

When I had a sniper from squadsight, I noticed a difference in aim percentage between the standard shot and double tap. Seems double tap didn't get penalized from squadsight for some reason.

Thanks,
Black Rose.

**Comment by pledbrook** [comment]
Could you please provide more details and perhaps a save? Are you saying it doesn't have a penalty when a standard shot does?

**Comment by BlackRose39** [comment]
Thank you for your response. That is correct. It happened some time ago when a sniper is targeting an enemy behind full cover. With standard sniper shot, it was a gamble, but with double tap, somehow I did not see any of that 'squad sight' penalty to hit in the box to the left and it was a solid chance to hit because it ignored that penalty, but not for a standard shot. I'll find time to reproduce it and screenshot it.

**Comment by Kazanir** [comment]
I can't reproduce this; I don't see a "Squad Sight" penalty but rather just "Weapon Range" at 20% in both cases.
