### ISSUE TITLE
Squad Management Open on Geoscape - Column heads are 'labels' and don't do anything

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#197]
Greetings.

While opening up a squad infiltration in process on the geoscape, the columns were "labels" and didn't do anything upon clicking on them.

Thanks,
Black Rose.

**Comment by pledbrook** [comment]
I think this is expected. There was a LW2 mod that displayed a normal soldier list instead, with sortable columns. Hoping to integrate that into this mod.

**Comment by pledbrook** [comment]
Fixed by integrating the View Infiltrating Squad mod with [this commit](https://github.com/long-war-2/lwotc/commit/b19934424092d90562bb38e9f2b5ca36993e2390).
