### ISSUE TITLE
Load out change of Infiltrating soldier

### ISSUE THREAD

**Issue by imn01** [long-war-2/lwotc#204]
Load out of already infiltrating team can be changed through Squad management>View squad

Also I'm not sure if intended, wounded soldiers get dropped from the View squad. In vanilla LW2 wounded soldier were viewable in there.

**Comment by pledbrook** [comment]
Do you have a screenshot or a save file? I've just tested this and although the "Loadout" button can be clicked on, you can't actually change any of the items in the soldier's inventory.

As for the second part of the issue, "View Squad" should only be showing the soldiers that are actually infiltrating. That's intended.

**Comment by pledbrook** [comment]
Can't reproduce either of these issues.
