### ISSUE TITLE
Reloading causes ADVENT corpses to spawn unobtainable loot.

### ISSUE THREAD

**Issue by Kerbomancer** [long-war-2/lwotc#209]
This happened when reloading an autosave on a jailbreak mission. The countdown timer reads "1" but never expires, and soldiers can't pick it up.

**Comment by pledbrook** [comment]
This could be the same bug with Psi zombie dropping loot. Do you have a save file that reproduces the problem?

**Comment by pledbrook** [comment]
No save file to invesigate.
