### ISSUE TITLE
Only faceless on the first rendezvous

### ISSUE THREAD

**Issue by torma** [long-war-2/lwotc#211]
I'm actually not sure this is a bug or intended but I don't remember having any rendezvous without advent in LW2. It also contradicts the description of the mission.
In my experience "extra" faceless should not start the mission as civilians, they should be revealed faceless. So in my case I had 2 faceless resistance members (matching the strength of the region which is the expected cap) and 2 extra faceless who should have started the mission revealed.

Save files at:
https://drive.google.com/file/d/17YCYLNmjZ__Sa4W-YLIs2ywpe_duq2Jb/view?usp=sharing

Some more details:
The "roaming" pod was one faceless civilian (standing still the whole mission). There were 3 more faceless civilians in the faceless pod. The mission had these two pods.
I don't mind having a mission like this. Especially at the beginning of a campaign. Since killing clumped up faceless who don't react is easy to kill with grenades. They didn't drop any loot or drone corpses so this is a trade off.
The last faceless civilian also didn't activate. I have also seen #63 and I'm playing on legend. So I assume it should have transformed when seeing the group. In LW2 the only case when faceless didn't transform is when they are close to the vision range of a revealed soldier. I'll keep an eye out for this.

**Comment by pledbrook** [comment]
This should be fixed in alpha 4 which is imminent.
