### ISSUE TITLE
Soldiers can only be carried out of a mission once for a whole campaign

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#212]
See this save file with a bleeding out soldier that can't be carried:

[save_Cant_grab_joey_martinez_body.zip](https://github.com/long-war-2/lwotc/files/3268551/save_Cant_grab_joey_martinez_body.zip)

There is a highlander fix from LW2. Also, [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1378606631) provides a workaround. But it does so by adding another carry ability.

**Comment by tracktwo** [comment]
Found the fix I made earlier - see `XCGS_Unit.OnBeginTacticalPlay`:

```
	// PI Mods: Reset the body recovered flag. A unit that was previously carried to evac while KO'd/bleeding out will have
	// this flag set, and this flag prevents units from being carried. If this unit gets KO'd again, they won't be able to
	// be picked up if this flag is still set.
	bBodyRecovered = false;
```

**Comment by pledbrook** [comment]
Fixed by [this commit](https://github.com/long-war-2/X2WOTCCommunityHighlander/commit/4048a2da19fa0866e945b5c6a4bb87bb18951396) in the community highlander.
