### ISSUE TITLE
Sidewinder triggering reaction fire from supression

### ISSUE THREAD

**Issue by torma** [long-war-2/lwotc#219]
Sidewinders have shadow step. So they should not trigger reaction fire.

Save file at:
https://drive.google.com/file/d/1ReUP1CYetUuJA1oIegIVZmYXinG0Yg6L/view?usp=sharing

**Comment by pledbrook** [comment]
I believe this is intentional to ensure that the Suppression debuff is removed from them. The reaction fire shouldn't hit, though.
