### ISSUE TITLE
TLP weapons not upgradeable

### ISSUE THREAD

**Issue by Ankaridan** [long-war-2/lwotc#225]
Weapons added by TLP can be used but the mods cannot be changed and new mods cannot be added. Switching to non-TLP weapons allows all weapon mod functions. The option for Weapon Upgrades remains greyed out, and the mods available indicator does not appear with these weapons equipped.

Only tested with 1st tier weapons.

**Comment by pledbrook** [comment]
They're not supposed to be ugpradeable, are they? That's my understanding.

**Comment by Ankaridan** [comment]
Took a wander through the xcom wiki and reddit. It does indeed seem that you are not supposed to be able to remove or add weapon upgrades to these as vanilla behaviour, as they are permanent and fixed.

Evidently one of the mods I long used prior to this Alpha test changed that behaviour and I never realized it. Learned something new.
