### ISSUE TITLE
Concealmeant breaking for unkown reasons

### ISSUE THREAD

**Issue by gen-martox** [long-war-2/lwotc#228]
My specialist "Valkyrie" is breaking concealment during the alien turn, the game is acting like she is being flanked but there isn't anyone flanking her. I moved her behind the tree shown the in screenshot and she didn't break concealmeant but moved her behind the car she did. This happens everytime after both pods move. Have a save file for this, just end the turn and watch the magic
![Inked20190611144504_1_LI](https://user-images.githubusercontent.com/51533309/59309774-11871c00-8c6a-11e9-884b-8ea98681459c.jpg)

[concealment breaking for unkown reason.zip](https://github.com/long-war-2/lwotc/files/3278740/concealment.breaking.for.unkown.reason.zip)

**Comment by pledbrook** [comment]
The depends on [X2WOTCCommunityHighlander#644](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/644).
