### ISSUE TITLE
Coilguns shred only 1 armor

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#230]
Coilguns shred only 1 armor, but must be 2.
 In XComGameData_SoldierSkills file said
 +ShredAmounts=(WeaponTechName="laser_lw", ShredAmount=1)
+ShredAmounts=(WeaponTechName="coilgun_lw", ShredAmount=2)

**Comment by pledbrook** [comment]
This is in conjunction with the Shredder perk i take it?

**Comment by nightmaRok** [comment]
yes, i play today and pick perks shredder on Gunner and Technical, magnetic shred 2, coils shred 1, so i`am here

**Comment by pledbrook** [comment]
If you have a save, that would be very helpful.

**Comment by nightmaRok** [comment]
Save is on russian language, its ok?

**Comment by pledbrook** [comment]
Sure, that will be fine, thanks.

**Comment by nightmaRok** [comment]
[save_Coil shred 1 armor.zip](https://github.com/long-war-2/lwotc/files/3291312/save_Coil.shred.1.armor.zip)

**Comment by pledbrook** [comment]
This is a problem with `X2Effect_Shredder`, which is hard-coded for magnetic and plasma tier weapons. Original LW2 actually modified that class to support extra weapon tiers. Don't know whether that's the best option now.

**Comment by nightmaRok** [comment]
I remember one thing, i play few months ego in vanilla wotc and set mod *Weapon Tier Overhaul for War of the Chosen (Add Coil and Lasers anywhere)* In this mod u can setup tiers, and on forum some one said about shred, and its problem of weapon tier, maybe need set coilguns on tier 2?

This information from steam: ttps://steamcommunity.com/sharedfiles/filedetails/comments/1275622993
Author: KnaveOfSpades
What is this mod?
This mod allows you to add coil guns and/or laser guns at any tier level you want. 
So, want laser weapons to come before magnetic weapons? Now they can.
Want coil guns to come after plasma? Easy to do.

**Comment by nightmaRok** [comment]
Maybe this information be helpful

**Comment by nightmaRok** [comment]
Find this:
some one ask
Hi Great mod however i have one problem, how do i reduce the shredding of laser cannon weapons (with the grenadier shredder talent?) my tier 2 laser cannons can already shred 3 armour and my tier 3 magnetic weapons shred only 2. There must be a way cheers :)

KnaveOfSpades answer:
To fix it, you'd need to edit and rebuild the mod. There's a line in X2Item_WeaponTeirWeapons.uc file for each gun that sets the tiers. All laser and coil guns are set as tier 3 (same as plasma weapons). When I was writing the code, I didn't even think about changing that. I can't change that for base game weapons, but I can alter laser and coil so they change tier level based on where you insert them. I'll put it on my to do list. No promise on when I'll get to it though.
insightguy - It works that way because I didn't set up the upgrading. It's an ease of use thing, not a core functionality and I skipped over it because I was getting burned out on writing the mod and wanted to be done. It's definitely doable. The main obstacle is untangling the unholy pile of nested if loops required to make sure everythign upgrades the right guns. I'll put it on my to do list for when I'm willing to look at Modbuddy again. In the mean time, sorry for the annoyance.

**Comment by pledbrook** [comment]
There are two reasonable options:

 1. Modify X2Effect_Shredder in the community highlander so that mods can configure additional weapons with > 1 shred
 2. Add a persistent effect to Coilgun weapons that adds additional shred damage via `X2Effect_Persistent.GetExtraShredValue()`

The second is a bit more work, but doesn't require a highlander change. The first is only worth doing I think if it helps other mods.

**Comment by pledbrook** [comment]
When implementing this, verify that the Weak Points resistance order, which adds +1 shred to any existing shred, also applies to coilguns.
