### ISSUE TITLE
Avatar have not full health

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#234]
Avatar have 60\83 HP at start, then he can regen to full, its a sacond one i see today playing, dont know how much he must have HP, i play legend difficulty
![Avatar_60-83_HP](https://user-images.githubusercontent.com/51829747/59554218-3fd96400-8fa8-11e9-8a9f-6718177f2e33.jpg)

**Comment by nightmaRok** [comment]
Add save file, save on russian language
[save_Avatar_60-83_HP.zip](https://github.com/long-war-2/lwotc/files/3294226/save_Avatar_60-83_HP.zip)

**Comment by torma** [comment]
I actually think this is not a bug.
Please see episode from Xwynns:
Long War 2 - Legend #114 "No More Questions" - XCOM 2 Let's Play: Long War 2 Gameplay Mod
https://youtu.be/TM3ZFGsRffE?list=PLkr09O8z61-oQlwmtjnczgQTccjbZP_9n&t=2347

**Comment by nightmaRok** [comment]
I see it, and this is avatar from codex, in last mission avatars have full hp in packs: 
1st-39:37
2nd-1:02:57
3rd-1:19:42
https://www.youtube.com/watch?v=wmXeI6nzRZg&list=PLkr09O8z61-oQlwmtjnczgQTccjbZP_9n&index=128

**Comment by nightmaRok** [comment]
Some strange happens, i test it on console *dropunit advpsiwitchM3*
If i start new run, this command drop full hp avatar, and not full hp if i load my save, maybe its some conflict version, i started play alpha 3 and after few days set alpha 4 and continue play

**Comment by nightmaRok** [comment]
Now i think need close this Issue and play from start
