### ISSUE TITLE
Incorrect training center abilities: Quickburn, electroshock, vital point targeting

### ISSUE THREAD

**Issue by SydenInsomniac** [long-war-2/lwotc#235]
The extra random abilities granted in the training center are showing up on a few classes that are unusable

Assault and Specialist: Quickburn: Your next use of flamethrower doesn't cost an action.  These units have no access to flamethrowers

Shinobi: Vital Point Targeting: Attacks against your halo marked targets do more damage.  Again no way for a Shinobi to use a halo targeter

Shinobi: Electroshock: Your arc thrower disorients the target when it misses.  No arc thrower

See attached screen shots for training center shots and abilities purchased on the wrong classes. Along with a saved game 

![20190615215207_1](https://user-images.githubusercontent.com/51498114/59558944-54265c80-8fba-11e9-882c-6e28ccd7435a.jpg)
![20190615215724_1](https://user-images.githubusercontent.com/51498114/59558945-54265c80-8fba-11e9-8782-40b4c07165da.jpg)
![20190615215810_1](https://user-images.githubusercontent.com/51498114/59558946-54265c80-8fba-11e9-8f3d-69404e98dd71.jpg)
![20190615215826_1](https://user-images.githubusercontent.com/51498114/59558947-54265c80-8fba-11e9-9589-02a60353bce7.jpg)
![20190615215930_1](https://user-images.githubusercontent.com/51498114/59558948-54265c80-8fba-11e9-97da-0650409b4da3.jpg)
![20190615220206_1](https://user-images.githubusercontent.com/51498114/59558949-54265c80-8fba-11e9-900c-a7da1715aa0d.jpg)

[save_Quickburn.zip](https://github.com/long-war-2/lwotc/files/3293816/save_Quickburn.zip)

**Comment by pledbrook** [comment]
Yeah, some abilities that are specific to certain class-constrained secondary weapons are actually marked as eligible for cross-class application. Which makes no sense. I'll fix the ones I can find.
