### ISSUE TITLE
Weight XP more towards mission XP

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#236]
The current system does provide substantial mission XP to soldiers, but it is stil valuable to stack kills on particular soldiers as that counts _on top of_ the mission XP. In addition, Wet Work and Deeper Learning only apply to the XP gained by the killer. Neither of them apply to mission XP, which is bad.

**Comment by Anxoczt** [comment]
I agree, this way soldiers that dont kill but still contribute in some way (Like by suppression, healing, CC) will be able to keep up with their comrades.

**Comment by Kazanir** [comment]
Not sure how far Peter has gotten with this but I dug up this old post by Xwynns about how vanilla LW2 worked:

https://pavonisinteractive.com/phpBB3/viewtopic.php?f=15&t=23409#p25156

**Comment by pledbrook** [comment]
Will probably keep things as they are in classic LWOTC.
