### ISSUE TITLE
Rocketeers has no rocket

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#239]
Play alpha 4 about one week and see no rocket from rocketeers. I use this console command to check it:
dropunit advrocketeerM1
dropunit advrocketeerM2
dropunit advrocketeerM3
[save_Rocketeer has no rocket.zip](https://github.com/long-war-2/lwotc/files/3294180/save_Rocketeer.has.no.rocket.zip)

**Comment by pledbrook** [comment]
Probably related to #129

**Comment by pledbrook** [comment]
In fact, this is unrelated to the issue with the priest AI. Apparently Rocketeers aren't getting rocket launchers.

**Comment by pledbrook** [comment]
Some logic related to disabling heavy weapons in the armory loadout was also being triggered when loading out ADVENT rocketeers, preventing them from getting rocket launchers. Oops. Will be fixed soon.
