### ISSUE TITLE
Secondary weapon effects are missing

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#24]
The rocket launcher projectile and holotargeter visual effect don't show in game. I think the effect for the stun gun is also missing.

**Comment by pledbrook** [comment]
Stun gun actually seems to be OK.

**Comment by MagSigeasol** [comment]
I have no animation on the technical rocket - the rocket doesn’t appear, nor does the explosion. Any resulting damage works correctly and it appears to function properly in respect of scatter and damage.

**Comment by pledbrook** [comment]
Ooops. Yes, ignore that previous comment. I _was_ seeing the rocket projectile, but not any more.

**Comment by pledbrook** [comment]
OK, this is fixed if you install the community highlander and LW2 mods separately. But the single LW2 mod with built-in highlander is still showing this bug. No idea why.

**Comment by GitWadeanthony** [comment]
Could this missing package mods fix the issue? I'm not able to test it myself right now but I can try in about an hour-

https://steamcommunity.com/workshop/filedetails/?id=1124064427

and here's the one for maps

https://steamcommunity.com/sharedfiles/filedetails/?id=1140305914&searchtext=add+missing

**Comment by pledbrook** [comment]
@GitWadeanthony No, and one or both of those mods appear to cause problems with some missions. See #81.

**Comment by cicero225** [comment]
I don't see technical flamethrower animations either. I built my highlander and LWOTC using more or less the package directions from the github (I did have to copy the highlander files over to the LWOTC folder to get the .bat file to finish though)

**Comment by pledbrook** [comment]
> I did have to copy the highlander files over the LWOTC folder

? What do you mean exactly by this? You didn't copy across the XComGame classes, did you?

Anyway, I haven't seen any problems with the flamethrower animations and none have been reported. Which suggests to me a problem with the build. So the "more or less" immediately strikes me as the potential culprit :smile:

**Comment by pledbrook** [comment]
Not sure whether to leave this issue open. I think I'd still like to sort out the holotargeter effect. Either try to get the old effects working or use a different approach that is much faster (holotargeting is so slow in the original LW2).

I think the LW2 secondary weapons mod replaced the holotargeting animation with a simple shooting one. May be worth a try.

**Comment by cicero225** [comment]
Well, trying to use the directions as-is means that the batch file for LWOTC terminates because it can't find the class XComLWTuple. After digging around, I guessed that the intent was to have the highlander files in there as well, so I copied stuff over from XComGame while denying replacement, and that was enough to finish it.  I just assumed the directions were incomplete.

**Comment by pledbrook** [comment]
@cicero225 Ah, I see. Yes, I delegate to the community highlander instructions here, which aren't particularly clear. You should not copy the highlander files into the lwotc project. That will cause problems (as I experienced first hand).

Instead, you need to specifically follow the instructions under [_Building Against the Highlander_](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/#building-against-the-highlander).

**Comment by cicero225** [comment]
Ah okay. I'll rebuild and test against that instead. I thought that section was referring specifically to other mods, so I didn't use it.

Thanks!

**Comment by pledbrook** [comment]
Closing this for now. Future problems should be raised as separate issues.
