### ISSUE TITLE
Soldier not counting for Evac all XCOM Solderis objectived

### ISSUE THREAD

**Issue by torma** [long-war-2/lwotc#240]
The Evac all XCOM operatives objectives was marked complete on a Jailbreak before the last solder (a reaper) was evacuated.

https://drive.google.com/file/d/1iJ8aOJ0QxU3bmw5gZzKD5NnDyqf1-50S/view?usp=sharing

**Comment by pledbrook** [comment]
Yeah, Jailbreak and the retaliations all use original LW2 Kismet which probably isn't accounting for faction soldier classes.
