### ISSUE TITLE
[Suggestion] Add aiming angles as suggested by Sid Meir for Xcom: Enemy Within expansion

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#241]
Vanilla Xcom: Enemy Within had an alternative 'second wave' option that changed the way aiming in the game worked to make flanking shots easier. I suggest that this feature be added to LWOTC at some point i the future, as this was a fun feature that added tactical depth and could be described as 'cannon' by Firaxis staff. In terms of implementation the option to enable this setting could be included in either the long war toolbox or the pre-game advanced options menu, which is similar to the second wave options menu in Xcom 1. Adding it as an option would main that it doesn't tread on Pavonis's LW design because the player can choose whether or not to use the feature in game.

**Comment by captainbeastfeast** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1124381333&searchtext=aiming+angles

Specifically, I was thinking hat this mod could be integrated into LWOTC as a advanced options or LW toolbox option (with the author's consent of course).

**Comment by DerAva** [comment]
Aiming angles already exists in LW2 and is intentionally disabled, as it only applies to XCOM units, not to Advent and was considered a once sided bonus. The AI would also not be smart enough to take advantage of better angles.
Either way players can freely enable that with an edit to XComGameCore.ini and change these lines to the values mentioned as "vanilla" values:

```
MIN_ANGLE_TO_COVER=10
MAX_ANGLE_TO_COVER=44
MAX_TILE_DISTANCE_TO_COVER=0	; vanilla was 11
MIN_ANGLE_BONUS_MOD=0.0
MAX_ANGLE_BONUS_MOD=0.0			; vanilla was 0.5
```
