### ISSUE TITLE
Battle Scanners tech tree

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#242]
Battle Scanners in lw2 tech must be after research *Hybrid Materials, ADVENT Robotics* and then need to do it in proving ground, but now in alpha 4, its like vanilla tech, after ADVENT trooper autopsy
[save_Battle scanners.zip](https://github.com/long-war-2/lwotc/files/3295406/save_Battle.scanners.zip)

**Comment by pledbrook** [comment]
This is probably caused by the same issue as with Mimic Beacons. Somehow the vanilla configuration is remaining active.

**Comment by pledbrook** [comment]
Did you change difficulty at any point in the campaign?

**Comment by nightmaRok** [comment]
No change difficulty, play Legend.
