### ISSUE TITLE
Claymore show incorrect explosion target

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#243]
When you place claymore on pack it show all 3 targets, but then ADVENT Sentry not in target, it work if place claymore on Sentry
![Claymore_1](https://user-images.githubusercontent.com/51829747/59582331-a19ce980-90e0-11e9-86b6-5bd5bb79c39e.jpg)
![Claymore_2](https://user-images.githubusercontent.com/51829747/59582344-ae214200-90e0-11e9-8d64-d83381e1ec16.jpg)

[save_Claymore.zip](https://github.com/long-war-2/lwotc/files/3295441/save_Claymore.zip)

**Comment by pledbrook** [comment]
I wouldn't be surprised if this is a vanilla WOTC bug.

**Comment by pledbrook** [comment]
Claymores are not really a thing in LWOTC any more. Even if they were, probably wouldn't get round to looking into this.
