### ISSUE TITLE
[Game crash] Following enemy VIP extraction mission

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#244]
See uploaded save. crash occurred a minute or so after this save.

save link:
https://www.dropbox.com/s/3as5qcyukjl211b/save_AUTOSAVE-%20Campaign%2024%2C%20Mission%2017%2C%20Turn%208?dl=0

**Comment by captainbeastfeast** [comment]
the crash didn't actually occur again when I loaded the save..

**Comment by pledbrook** [comment]
Can't investigate if not reproducible, and it doesn't seem like it's a common bug if it's still around.
