### ISSUE TITLE
End of the Month screens broken with Chosen disabled

### ISSUE THREAD

**Issue by yoshimo** [long-war-2/lwotc#246]
At the end of each month you normally get a tiled red screen with the advances the chosen made , how much knowledge they gained about xcom and which abilities they learned.
If you play with Chosen disabled, these screens are empty.
Narrative voice overs might also be off a little in this case, but i need to verify that part.

**Comment by yoshimo** [comment]
![EOM_1](https://user-images.githubusercontent.com/17909/59829385-998db580-933d-11e9-8201-a07883d33441.png)
![EOM_2](https://user-images.githubusercontent.com/17909/59829393-9eeb0000-933d-11e9-9089-a3f7093abec8.png)

**Comment by pledbrook** [comment]
Should be fixed by above commit.
