### ISSUE TITLE
New mod resource: Force Level Extender

### ISSUE THREAD

**Issue by SirMrMister** [long-war-2/lwotc#248]
https://steamcommunity.com/sharedfiles/filedetails/?id=1769840441

Astral Descend has released a modification of the force level logic to increase its maximum to 50. Something to consider if in the future we want to make the enemy's force progression more seamless (for instance, by scaling the current 20 force levels to 40, with the odd force levels being new "interpolated" force levels, and 41-50 force levels being new endgame-pushing force levels, at a point where you might actually be able to prevent the ScheduledOffworldReinforcements ADVENT mission that increases their global force level.

**Comment by Xymanek** [comment]
The default increase is 99 actually, although you could set it to anything

**Comment by Grobobobo** [comment]
Not needed.
