### ISSUE TITLE
No icon *Chosen strengths and weaknesses* on mission

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#249]
When you are on mission meet chosen, in vanilla wotc, in top right corner must be icon his *strengths and weaknesses*
![Chosen stregths and weaknesses](https://user-images.githubusercontent.com/51829747/59771003-9ea52300-92b1-11e9-90be-4d55dc12d9b6.jpg)

**Comment by pledbrook** [comment]
Do you have a save game for this?

**Comment by nightmaRok** [comment]
Create clear save for you, no mods, just at 1st mission *killallais*, then after mission use *activatechosen* and send one soldier at 1st spowned mission. Hope this will enough.
[save_Chosen_on_mission.zip](https://github.com/long-war-2/lwotc/files/3512862/save_Chosen_on_mission.zip)

**Comment by pledbrook** [comment]
Just for my reference, this is happening because the officer pack is overriding `UITacticalHUD_MouseControls.UpdateControls()`, which is the code that adds the Chosen Info button. I need to work out some way for the Command Range button and the Chosen Info button to coexist reliably.

**Comment by ansabalirai** [comment]
Another comment here, slightly unrelated but the positioning of the icons could be better as well. Specifically, when an officer is present on the mission, the command range view icon and chosen icons overlap like this: 
![image](https://user-images.githubusercontent.com/15093261/65837367-5d0e1600-e2ab-11e9-9d94-6b2c20d4e26b.png)

**Comment by pledbrook** [comment]
I think the path of least resistance here is to add the command range button either to all soldiers' ability bars, or just to officers' ones.
