### ISSUE TITLE
Empty UI window after completing network tower mission

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#251]
[save_AUTOSAVE-_Campaign_43_Mission_137_Turn_16.zip](https://github.com/long-war-2/lwotc/files/3307737/save_AUTOSAVE-_Campaign_43_Mission_137_Turn_16.zip)

**Comment by BlackRose39** [comment]
Right, I am pretty sure that that is suppose to be the screen indicating that the HQ assault is ready, and is prompting the player to view/wait to launch.
