### ISSUE TITLE
Crash when loading HQ assault

### ISSUE THREAD

**Issue by torma** [long-war-2/lwotc#253]
I have been playing around with this issue for quite some time.
I have narrowed down the issue to just killing one Sectoid with the sniper. 

1. Kill the sectoid with the sniper. (Use Precision shot.)
2. Steady weapon
3. Wait for the new autosave
4. Load the next autosave

The pod where the Sectoid seems to be the leader accompanied by two sidewinders. The pod was also not patrolling but I don't know if this is related.

Save file and crash dump:
https://drive.google.com/file/d/1qs5DPujyGEA8Cao1xAu2YpxgV-VxN3rY/view?usp=sharing

**Comment by pledbrook** [comment]
Yeah, that pod is in a state. It should activate when you shoot the Sectoid. Something's definitely broken there.

**Comment by pledbrook** [comment]
Collating these save issues in #600
