### ISSUE TITLE
[Suggestion] Allow weapon upgrades to be unequipped (as well as swapped)

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#256]
LW2 allows you to swap one weapon upgrade for another but you cant (as far as I know) simply remove an upgrade from a weapon. This can leave you with weapons that you wont use later on. It can be problematic when you upgrade weapons, as the new weapons don't come readily equipped with upgrades. Therefore, if you don't have surplus upgrades you can't swap upgrades over to your new weapons. This is less of a problem in vanilla xcom 2 because weapon upgrades are automatically transferred as weapon classes are upgraded for all of your soldiers.

**Comment by Kazanir** [comment]
There's a "Strip Weapon Upgrades" button for a given weapon on the weapon upgrades loadout screen. I have used it as well as the "Strip All Weapon Upgrades" button that removes them from all weapons not currently assigned to mission duty. The latter button disappears sometimes and we should file a separate issue for that, but as far as I can tell what you're requesting here already exists.

**Comment by pledbrook** [comment]
[This mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1337050242&searchtext=soldier+development) should do what we need. May leave this issue open in case we want to do something with it.

**Comment by wdanny69** [comment]
lwotc has its own feature to remove weapon mods however the singular removals is not working. 

this mod does functionally the same https://steamcommunity.com/sharedfiles/filedetails/?id=1162274976
