### ISSUE TITLE
Arc pulser bug

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#259]
Arc pulser stun enemys on unlimited turns. I skip few turns and trooper do nothing, in previous mission same been with sentinel
[save_Arcpulser_01.zip](https://github.com/long-war-2/lwotc/files/3310982/save_Arcpulser_01.zip)

**Comment by nightmaRok** [comment]
Also test it on other units like muton and archon, same thing
[save_Arc pulser_bug.zip](https://github.com/long-war-2/lwotc/files/3311223/save_Arc.pulser_bug.zip)

**Comment by torma** [comment]
I believe this is the same issue as #99

**Comment by nightmaRok** [comment]
As i see bug was fixed in issue #99
