### ISSUE TITLE
Enemies occasionally fail to scamper on reveal

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#26]
Don't have a save game for this yet, but it happens maybe 30-50% of the time, leaving the enemy flanked on XCom's turn.

**Comment by pledbrook** [comment]
This may only happen when the aliens reveal XCOM on the alien turn. And maybe only when one of them shoots the flanked soldier.

**Comment by MagSigeasol** [comment]
I have had this occur where XCOM ambushed a pod, which caused other pods to move. It only happens sometimes - I.e, reloading and taking the same action to ambush will cause scamper when it didn’t previously. Interestingly, the order of pod reveal and scamper would change in each instance. 

I can provide a save but it will be a few days.

**Comment by pledbrook** [comment]
The original LW2 has a dedicated listener for `ProcessReflexMove` events that does something around scamper. Not sure if it's connected or not. I think it requires a highlander change.

**Comment by ionbomb** [comment]
> This may only happen when the aliens reveal XCOM on the alien turn. And maybe only when one of them shoots the flanked soldier.

I have had this happen too. I believe that this is the Vanilla Anti-Beaglerush maneuver, that was removed from LW2 in v1.1. One alien stands still and shoots, the rest scamper.

Unfortunately I have not been able to replicate it reliably, so cannot provide a useful savegame.

**Comment by pledbrook** [comment]
The yellow alert changes and other AI modifications have probably fixed this. I certainly haven't noticed it recently.
