### ISSUE TITLE
Stat Upgrade System

### ISSUE THREAD

**Issue by gen-martox** [long-war-2/lwotc#260]
First off I want to thank Musashi for creating the Stat Upgrade system and for allowing us to use it if we choose to

for those you use RPGO you already know how the system work and for those you don't let me attempt to explain it 

so Musashi created a new version of Combat Intelligence call "Natural Aptitude" and new Stat Points, SP. Natural Aptitude will only effect how many SP soldiers get each promotion and SP can only be used to increase stats and the only way to get SP is on promotion
when you select a soldier you will see a new button call Soldier Stats, when you click on that it will bring you to a new screen where you can increase the soldier's stats

![20190620132917_1](https://user-images.githubusercontent.com/51533309/59877393-66621b00-936b-11e9-864f-5e4d5c7b5566.jpg)

![20190620132924_1](https://user-images.githubusercontent.com/51533309/59877406-6a8e3880-936b-11e9-8ddb-d24793e47018.jpg)

at this point is fairly simple you just select which stat you want to increase then your done. Soldiers will only get so many SP per promotion based on natural aptitude once you spent the soldiers SP you can use the soldier AP for additional stat points but you can not use the XCom AP pool for stat point, again you CAN NOT USE XCom AP Pool for stat points

now I'm still working out the cost for each stat and how many SP soldiers should get. I'm leaning toward 10 SP per promotion and maybe 1 or 2 extra for natural aptitude level if any
for cost I'm thinking
Health SP cost = 15 ;for those of us who uses Beta Strike Health SP cost with spike to about 50
Mobility = 20
Aim = 7
Will = 5
Dodge = 5
Defense = 7
Hack = 7
PSI = 5

with this system it would give player more options in developing their soldiers especially for those players who will not use certain abilities, like the Sharpshooters holo-targeting, if we do go down this road it might be worth looking at reducing the stat increases on promotions

I would really like to see this add with the changes I suggested to abilities cost, I think it would lead to some interesting choices. like would player rather build up enough AP to get the more expensive abilities, are probably more powerful but can be more situational, or get a few more stat points which are always useful

**Comment by BTAxis** [comment]
I've played some RPGO and I have a couple of gripes with this system. 

Firstly, it becomes rather tedious to raise the stats of every soldier, especially with the kind of deep roster required for LWOTC. My RPGO mod configuration also favors deeper rosters (via More Will Loss), and I have to say it's a lot of clicks for the promotions.

Secondly, in my experience the system counteracts Not Created Equal to some degree, because raising low stats is cheaper and thus more cost effective than raising ones that were rolled high to begin with. As such, my soldiers tend to all end up with the same baseline of stats with only minor differences toward the end.

In RPGO there really isn't an alternative for this system because it's effectively a classless mod, but in LWOTC I think class-based stat growths are probably the better approach.

**Comment by gen-martox** [comment]
I have been testing this out for about a week now and yeah it can get a bit tedious, there has been several times where I haven forgotten and just didn’t feel like doing. It being “tedious” is mostly just our opinion, I mean there are ppl who spend hours customizing the look of the soldiers so. In RPGO you can get a lot more SP than how many I would have it for LWOTC, I would set it where you would only maybe get 2 stats points per promotion unless you spend AP.

If you really think about it, getting stats on promotion also counteracts NCE. A sniper who get a low aim will get 28 extra points for aim by Master Sergeant, at least according to wiki. I think stats on promotion is far to restrictive and it will pretty much be the same for soldier of that class even with NCE and hidden potential active. I mean doing it this way will probably will probably still be that way but at least that will be  to the players.

I think it is always better to give the players more options and let them decide what and how they use things.

**Comment by BTAxis** [comment]
> If you really think about it, getting stats on promotion also counteracts NCE. A sniper who get a low aim will get 28 extra points for aim by Master Sergeant, at least according to wiki.

No, that's not accurate. The Sharpshooter class gets 28 aim at MSGT _regardless_ of what the initial NCE roll was. A 55 aim rookie will become a 83 aim MSGT, while a 75 aim rookie will become a 103 aim MSGT. With the manual stat upgrades, they'll likely end up much closer together because raising aim past 80 becomes more expensive.

**Comment by gen-martox** [comment]
That’s basically what I said, albeit not as well explained, but my point still stands 83 aim is still prettier good even if you have to wait till MSGT. IMO that is too much of a jump so I would like to see all stats progression reduce by at least half, even without this system in place.

Stat costs and when the cost increases can be managed, right now with the aim cost at 5 SP it will increase to 6 SP when the soldiers aim is at 67 or higher, then it will increase to 7 SP at 78. It all about getting the numbers right. The way I would I would like to have it so where player will only be able to increase most of their soldiers stats by 2 points on promotion, unless they spend the solders AP. Which when combined with the changes I had suggested to ability AP cost would probably mean for most soldiers will get extra stats or extra abilities, depending on ComInts and such.

And again giving players more options is always, always better

**Comment by Maebalzurakin** [comment]
I actually like the learn by doing system in this mod, which I can confirm is working well in beta 5.

[https://steamcommunity.com/sharedfiles/filedetails/?id=1337050242&searchtext=soldier+development](url)

**Comment by pledbrook** [comment]
Not going to be a core feature of LWOTC. Could be handled as a mod.
