### ISSUE TITLE
Turning off 'not created equal' doesn't apply to faction soldiers

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#261]
Greetings.

I noticed that despite turning off 'not created equally,' there is still stats discrepancy between faction soldiers of the same rank. It works fine on regular soldiers aside will stats.

Black Rose

**Comment by pledbrook** [comment]
Does this apply to particular faction soldiers? I'm not sure how faction soldiers are awarded.

**Comment by pledbrook** [comment]
Does not seem to be a problem any more
