### ISSUE TITLE
[BUG] The dots system that indicates liberation mission progression doesn't always update correctly following mission completion

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#262]
Specifically when viewing each region's liberation progression in the resistance management screen, I found that the tracker often doesn't update correctly following the second liberation mission. This could be a bug that carries over from LW2.

I will test this further as I do more liberation missions.

**Comment by ansabalirai** [comment]
Could it just be a matter of going to the geoscape briefly just after finishing the mission to allow it to update?

**Comment by Grobobobo** [comment]
I recall something like that being fixed a while ago.
