### ISSUE TITLE
bug) 워록 전투후 월드멈춤 [bug) World Stops after Warlock]

### ISSUE THREAD

**Issue by bogkj1** [long-war-2/lwotc#264]
![아멈춤](https://user-images.githubusercontent.com/52105632/59964943-b8a96480-9542-11e9-9fed-af04f6577b79.png)

**Comment by jmartinez989** [comment]
So I translated the title of this to: bug) World Stops after Warlock. Are you saying that the game freezes on strategy layer when revealing the warlock? (That is what I am getting from the title and the image).

Also I included the translation in the title.

**Comment by bogkj1** [comment]
yes

**Comment by jmartinez989** [comment]
closing this. the issue has been resolved. will be available in the next release.
