### ISSUE TITLE
[Suggestion] activate all chosen simultaneously after liberation 2 mission (possibly slightly later)

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#265]
One thing that bugs me about WOTC is the way the chosen activate as you meet them, rather than all together. This doesn't make narrative sense and feels overly 'gamey,' in my opinion. LWOTC could have them all activating together. This would hake them stronger and would be a foil to the strategy of liberating regions ASAP in each play-through.

**Comment by Grobobobo** [comment]
Currently the beta branch has all chosen activating in fl3 at the same time, so the suggestion is redundant.
