### ISSUE TITLE
(Suggestion) Consider integrating EU aim roll mod to Long War

### ISSUE THREAD

**Issue by Anxoczt** [long-war-2/lwotc#267]
There is a mod on the workshop called EU aim rolls (for WOTC). In short it changes how crit, dodge and hit chances work in XCOM 2 that instead of all 3 actions (Hit,dodge,crit) rolling at once, it will change that only % hit will roll, THEN it will roll the crit/dodge.

What it does in game is that all troops (yours and Advent) will hit far less with low hit chances against targets in cover, this is most apparent with Advent and their units that have innate critical hit chance.

_Story time to explain myself, skip it if you dont care about my misfortune of gothic proportions_

 I found this mod after googling "Why are Advent units consistently hitting me through solid cover". Because in one mission, Andromedon crit killed my sniper in solid cover in a building (literally the first attack the enemy made and it killed someone). Then mission after my machinegunner who was in high cover and hunkered down got hit critically by Muton Elite.

At first i remembered the legendary Civ Ghandi bug with what happens if numbers go negative... 
But on second thought i thought it couldnt be negative due to numbers, it had to be still a positive hit, the negative wouldnt let the AI fire at all.

So i thought off that some in-build "challenge" "mechanic" that increases the aim for aliens if i do too well against them (Like have 10 missions in row without even a graze from aliens) so i forcefully take casualties, i wouldn't be really surprised if Long War 2 pulled such cheap shot at me for doing too good, might as well remove soldiers from my pool but thankfully thats not the case. 
_**End of my origin story**_

And after installing this mod, hits through cover went down considerably and now for a change i dont have to CC everyone 24/7. It also fixes the bug that causes flashbangs to make things worse if you get hit. 

Its like throwing three dices, if even one lands on a favourable number, you get hit. With this mod you throw a single dice, if it lands on a favourable number THEN you roll another dice.

Consider integrating this mod in LWOTC, it will make it way better.
- Makes cover better on both sides.
- Makes low hit chances attacks less likely to hit on both sides. 
- Fixes flashbangs ( https://www.reddit.com/r/Xcom/comments/4g77cp/were_flashbangs_ever_fixed/ )and smoke grenades, making both more potent in its supposed job. Its not actually LW2 "feature", its intentionally in vanilla game but in Long War its way more apparent.

https://steamcommunity.com/sharedfiles/filedetails/?id=1123516056

What do you think ? Yes or no ?

**Comment by pledbrook** [comment]
That mod has nothing to do with hits through cover. What it _does_ do is make sure that low percentage shots that hit don't crit as often.

Anyway, we are using the original LW2 graze band mechanic (#132) instead.
