### ISSUE TITLE
Advent convoy assault and Advent retaliation has quite static spawnpoint

### ISSUE THREAD

**Issue by Anxoczt** [long-war-2/lwotc#268]
A bug that i noticed that i dont remember from vanilla LW2 is that on when you have to defend resistance convoy from Advent troops or evacuate civies while endless stream of Advent troops pours in.
They have quite static and predictable spawn point, which lets the player to camp the living shit out of them.

![20190619184133_1](https://user-images.githubusercontent.com/50877085/59968642-42563380-953d-11e9-920c-2e5249990207.jpg)

In these three zones all reinforcements were arriving... as you can see theres a nice pile of corpses as they were massacred at point blank with overwatch. But the spawn camping on Heaven evac mission is even worse but i didnt made a picture (I only realized this aint suppose to happen on this mission, so here i am).

**Comment by jmartinez989** [comment]
Well with RNF drops they are usually dropped some place relative to XCOM. In the case of the supply convoy assault they usually spawn between the 2 XCOM groups some where in the middle. If you can get a good enough spot where you can kill advent pods by not having to move too much then RNF spawn points aren't really going to change.

The Defend_LW defense (the one that is all RNFs from turn 1) is a bit different but if you keep the majority of your soldiers in the same place the same thing happens.

Not really too sure what can be done about this other than to make RNF spawn points random but I think that would make things either much harder or even easier actually, would depend on the spawn points.

**Comment by MiserablePileOfBugs** [comment]
I think that a bit of predictability is actually healthy. There are already enough random elements in the game. 

We should also take into account the fact that rebel units are push-overs and having reinforcements drop just behind them on the first turn would likely result in a butchery (and a very frustrating game experience).

**Comment by pledbrook** [comment]
Reinforcements drops are more random now.
