### ISSUE TITLE
So I translated the title of this to: bug) World Stops after Warlock. Are you saying that the game freezes on strategy layer when revealing the warlock? (That is what I am getting from the title and the image).

### ISSUE THREAD

**Issue by bogkj1** [long-war-2/lwotc#269]
So I translated the title of this to: bug) World Stops after Warlock. Are you saying that the game freezes on strategy layer when revealing the warlock? (That is what I am getting from the title and the image).

Also I included the translation in the title.

_Originally posted by @jmartinez989 in https://github.com/long-war-2/lwotc/issues/264#issuecomment-504669095_

**Comment by bogkj1** [comment]
yes

**Comment by jmartinez989** [comment]
closing this. the issue has been resolved. will be available in the next release.
