### ISSUE TITLE
Reaper don`t back after Haven defense

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#270]
Reaper was haven adviser and after mission *Defend haven* don`t back. Dissapear in view soldiers but his name in squad management.
[save_Reaper_haven defense.zip](https://github.com/long-war-2/lwotc/files/3317746/save_Reaper_haven.defense.zip)

**Comment by jmartinez989** [comment]
closing this as a clone to #222. The haven defense mission is causing haven advisers to disappear.
