### ISSUE TITLE
Death from Above can activate multiple times per turn

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#273]
This is a particular problem with the Hunter's sniper rifle (Darklance?) which can be fired with just a single action.

**Comment by pledbrook** [comment]
Fixed by [this commit](https://github.com/long-war-2/lwotc/pull/271/commits/4a1e3c29752e7d5a8c90c75ee68160d5c0812914).

**Comment by PodliKirill** [comment]
There is 2 problems with DFA.
1. Darklance - basicaly can wipe all map.
2. DFA + snapshot - also can make multiple shots in one turn.

But, you basicaly cannot use DFA free move after multiple kills in one turn with Double tap, serial, or command usage. Good solution - is change for DFA. DFA should provide not a free action, but free non-damaging action. This allow reload/move/steady after multiple kills, but block Darklance/snapshot abuse.
