### ISSUE TITLE
Network Tower map bug *remote start*

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#275]
A lot of explosion on Network Tower, only one is correct.
[save_A lot of explosion.zip](https://github.com/long-war-2/lwotc/files/3325676/save_A.lot.of.explosion.zip)

![Remote start](https://user-images.githubusercontent.com/51829747/60105712-867b4b00-976c-11e9-8301-62220c858543.jpg)

**Comment by jmartinez989** [comment]
Are you saying that a lot of icons show up but you can only actually use Remote Start on one of them?

**Comment by nightmaRok** [comment]
No, i can use on every one of them.

**Comment by nightmaRok** [comment]
Today play other Network Tower mission, same thing on map.

[save_Tower_bug_remote_2nd.zip](https://github.com/long-war-2/lwotc/files/3329530/save_Tower_bug_remote_2nd.zip)

![Remote start_02](https://user-images.githubusercontent.com/51829747/60172507-7c615700-9815-11e9-85e3-2e8184b117ad.jpg)

**Comment by Grobobobo** [comment]
We removed remote start from the game with no intention of bringing it back. Even then, this probably woundn't be an issue we could fix.
