### ISSUE TITLE
Alien Rulers not appearing in integrated DLC mode

### ISSUE THREAD

**Issue by Kazanir** [long-war-2/lwotc#279]
Follow-up to #173 it looks like this is not actually working. I haven't seen any rulers 10 months into the campaign in integrated mode and I suspect they aren't working (except for the initial mission) at all.

Goal: Fix this and limit them to the original LW2 mission list, which was anything that is untimed by default:

- Troop column
- Supply raid
- HQ assault
- Facility assault

Some people have mentioned UFO missions but I'm not sure if these make sense because a) thematically the alien ruler is not likely to be on a UFO, they are sort of independent and b) the UFO missions do secretly have a post-activation timer.

**Comment by jmartinez989** [comment]
I have fought all 3 rulers in lwotc but it was when not integrated (completed the nest mission). I only ever saw the rulers in the missions you mentioned above plus golden path missions.

**Comment by TheReigningKing** [comment]
Just popping in to say I've never seen a Ruler yet. I've done multiple facility and HQ assaults. And countless Troop columns/Supply Raids.

In LW2 I'm pretty sure the Rulers were meant to be guarding the Facilities or UFOs, and once activated, would show themselves on any mission until killed.
