### ISSUE TITLE
Shadowkeeper don`t give -1 mobility

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#280]
Also shadowkeeper cost wrong, on LW2 wiki says Shadowkeeper - 25 supplies, Enhanced Shadowkeeper - 45 supplies 5 Alloys. Dont know abaut other "Aliens hunters DLC"
 stuffs (axe, frost bomb and bolt caster), Axe i lose so cant check it, Frost Bomb and Bolt Caster don`t find on LW2 wiki weapons.

![Shadowkeeper_01](https://user-images.githubusercontent.com/51829747/60164018-782d3d80-9805-11e9-9d55-7cef5afe67e1.jpg)

![Shadowkeeper_02](https://user-images.githubusercontent.com/51829747/60164038-80857880-9805-11e9-8931-391c8b3f645e.jpg)

![Shadowkeeper_cost](https://user-images.githubusercontent.com/51829747/60164113-a7dc4580-9805-11e9-9d2c-12ffb745008b.jpg)

![Shadowkeeper_cost_02](https://user-images.githubusercontent.com/51829747/60164117-aad73600-9805-11e9-80b6-2a015cdb2962.jpg)

[save_Shadowkeeper_cost_mobility.zip](https://github.com/long-war-2/lwotc/files/3329040/save_Shadowkeeper_cost_mobility.zip)

**Comment by pledbrook** [comment]
I don't trust the wiki. If you can demonstrate that LW2 1.5 had different costs for these weapons from LWOTC, then I'll change. But I can't find any modified costs in the original LW2 source code or configuration.

**Comment by pledbrook** [comment]
Also, the Shadowkeeper is explicitly configured with a weight of 1, which I think implies a -1 Mobility.

**Comment by nightmaRok** [comment]
Its seems wiki lies abaut price, test in lw2 1.5, so need just fix - mobility

**Comment by pledbrook** [comment]
Oops. This broke #43 again.
