### ISSUE TITLE
[BUG] broken save on alien base assault

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#281]
Dead aliens are T-posing and I am unable to hack a mech with my specialist despite being able to shot at it with him. 

This may be due to the fact that I have allowed many turns to pass, blowing up many of the aliens on the map with remote start and saving the game many times.

Mods: Just the kill counter mod so i can keep track of my tallied kills more easily.

See saved file link: 
https://www.dropbox.com/s/bjqqbp1cvimv1ae/save_Save%20199?dl=0

**Comment by captainbeastfeast** [comment]
on closer inspection the advent mech in question has previously been hacked. However, this shouldn't stop it from being hacked on a later turn. Any ideas whats causing this?

**Comment by Kazanir** [comment]
My understanding was that you can only fail a hack on a given mechanical unit one time per soldier; after that you're locked out.

**Comment by pledbrook** [comment]
Link above is no longer valid (file deleted), so can't investigate.
