### ISSUE TITLE
Enemy units not taking offensive reflex actions when scampering from yellow alert

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#283]
When units scamper after seeing XCOM and they were previously in yellow alert, they fail to perform any offensive actions, such as shooting or Insanity (for Sectoids).

**Comment by jmartinez989** [comment]
odd enough, the only exception to this seems to be the Avatar. They can open up with demensional rift.

**Comment by pledbrook** [comment]
This requires some more changes to the highlander because the reflex actions that are being awarded to units in yellow alert can't be used by the enemy units to do anything. That's because a WOTC change made `StandardAction` the only support type of action point for reflex actions. And LW2 awards custom types of action point.

There is a separate issue with pod leaders not getting to use their reflex action points because they've alread moved (followers don't use action points while their patroling apparently).
