### ISSUE TITLE
Wierd images after research screen and on black market

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#285]
Almost all weapon images shows strange after researching and on black market, made few printscreens.

![Images_01](https://user-images.githubusercontent.com/51829747/60257383-03790280-98dc-11e9-8374-5fd09c8cf539.jpg)
![Images_02](https://user-images.githubusercontent.com/51829747/60257384-03790280-98dc-11e9-8d4b-8b1693a62d23.jpg)
![Images_03](https://user-images.githubusercontent.com/51829747/60257385-04119900-98dc-11e9-849f-348f24be7b32.jpg)
![Images_04](https://user-images.githubusercontent.com/51829747/60257386-04119900-98dc-11e9-93c3-f981373a0c47.jpg)
![Images_05](https://user-images.githubusercontent.com/51829747/60257387-04119900-98dc-11e9-802f-7b54fd24395e.jpg)
![Images_06](https://user-images.githubusercontent.com/51829747/60257388-04119900-98dc-11e9-8929-0ef736437d28.jpg)
![Images_07](https://user-images.githubusercontent.com/51829747/60257389-04119900-98dc-11e9-9962-9490f9f04345.jpg)

**Comment by pledbrook** [comment]
Apparently the Covert Infiltration mod fixed this issue [here](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/commit/b008d77d7e29c6d4dabd5a90406b4f962ef7ec84);

**Comment by pledbrook** [comment]
Note that this also impacts anything that uses `UIItemCard` to display item information.

**Comment by Grobobobo** [comment]
Was this problem actually fixed after the commit?

**Comment by wdanny69** [comment]
this doesn't seem to be an issue anymore
