### ISSUE TITLE
All plasma requered 7 engeeners, Bullpup 90 not

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#286]
![Plasma_bullpup_01](https://user-images.githubusercontent.com/51829747/60258887-b9dde700-98de-11e9-9c71-f312699dee1a.jpg)

![Plasma_bullpup_02](https://user-images.githubusercontent.com/51829747/60258898-bf3b3180-98de-11e9-9e9f-32b67278cf76.jpg)

[save_Bullpup_90.zip](https://github.com/long-war-2/lwotc/files/3334124/save_Bullpup_90.zip)

**Comment by jmartinez989** [comment]
closing as this has been fixed.
