### ISSUE TITLE
Training Center Bugged, Letting me level up at will.

### ISSUE THREAD

**Issue by Roflmaows** [long-war-2/lwotc#287]
So I was going through planning to upgrade a few of my characters and when I hit tab to move to the next page it increased the rank on the soldier and gave me AP. It allowed me to hit Master Sergeant on every class, at max you aren't able to get infinite points. 
But I also ran into the issue of usually at least one option of each row costing only 0 AP.
Game is on May 29th, Veteran Difficulty, Mods are Evac All - WOTC, LONGWAROFTHECHOSEN, X2WOTCCOMMUNITYHIGHLANDER, WOTC TacticalUI Killcount, Free Camera Rotation. I had enabled Gotcha Again after a few missions, but first mission with it enabled crashed when I tried a hack so I disabled it, I didn't test if that was the cause of the crash.

**Comment by pledbrook** [comment]
This is a feature of the community highlander when it's not published with the `-final_release` option. So during the alpha phase this will remain.
