### ISSUE TITLE
chosen base assaults number of enemies issue

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#289]
Having infiltrated a chosen base to 100% my pre-mission enemy count states that there are 12-15 enemies. This seems lower than vanilla Xcom 2. Is this a bug?

Also is it intended to have up to 10 soldiers infiltrating on these missions? if so the mission could potentially be very easy if you're willing to wait the much longer infiltration time.

**Comment by pledbrook** [comment]
Chosen missions haven't been touched at all, so they should be vanilla. What may differ is the alert used for them.

**Comment by captainbeastfeast** [comment]
Thanks for your response, I thought this may be worth discussing for balance reasons. 

it seems that the default number of enemies in xcom 2 is 14 for this mission (plus spawned enemies in the final chamber). It might be worth putting a cap on the number of soldiers for this mission type (6 is the vanilla maximum), or increasing the number of enemies to compensate for potentially larger xcom squads on these missions.

**Comment by pledbrook** [comment]
So I'm thinking about limiting this to a 5-man squad. You should be able to test this by opening _Documents/My Games/XCOM 2 War of the Chosen/XComGame/Config/XComMissionDefs.ini_, finding the mission definitions for "ChosenStrongholdShort" and "ChosenStrongholdLong", and then adding a `MaxSoldiers=5` entry to those definitions. You can find examples of `MaxSoldiers` and where to put it elsewhere in that INI file.

**Comment by pledbrook** [comment]
We'll go with limiting squad size to 5 for now.
