### ISSUE TITLE
Drones aren't patrolling

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#29]
The gamestate change doesn't seem to be working. I'm seeing an error about it not being added to the history.

**Comment by ansabalirai** [comment]
Have to say, not having to worry about drones has made scouting in GOps a lot easier. It is worth mentioning that drones that are part of pods do not seem to have this issue

**Comment by pledbrook** [comment]
Try the old LW2 fix to the highlander in `XGAIBehavior.GetTileWithinOneActionPointMove()` to see whether that helps.

**Comment by pledbrook** [comment]
This is fixed [in the community highlander](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/505)
