### ISSUE TITLE
Blaster launcher targeting issues

### ISSUE THREAD

**Issue by Kazanir** [long-war-2/lwotc#292]
Two different things appear to happen with blaster launchers:

1. Opening the Blaster Bomb ability results in the targeting reticle moving all over the screen in unpredictable ways, usually stabilizing on a single map location after some time and failing to respond to the cursor in any sort of predictable way.

2. Sometimes locating the cursor well out of range and hitting the Blaster Bomb button results in a game crash, as follows:

```
[0218.28] Warning: Redscreen: Assertion failed, line 121
	XComPrecomputedPath Plot_CTY_Extract_LgObj_Park.TheWorld:PersistentLevel.XComPrecomputedPath_34
	Function XComGame.XComPrecomputedPath:GetEndPosition:003A
	Script call stack:
	Function XComGame.UITacticalHUD_AbilityContainer:Tick
	Function LW_Overhaul.X2TargetingMethod_LWBlasterLauncher:Update
	Function XComGame.XComPrecomputedPath:GetEndPosition

[0218.98] Critical: appError called: Assertion failed: appErrorf [File:G:\BuildAgent\work\9a884cb2af69f6ff\main\XCOM2\Development\Src\Core\Src\UnCorSc.cpp] [Line: 267]
Assertion failed, line 121
	XComPrecomputedPath Plot_CTY_Extract_LgObj_Park.TheWorld:PersistentLevel.XComPrecomputedPath_34
	Function XComGame.XComPrecomputedPath:GetEndPosition:003A
	Script call stack:
	Function XComGame.UITacticalHUD_AbilityContainer:Tick
	Function LW_Overhaul.X2TargetingMethod_LWBlasterLauncher:Update
	Function XComGame.XComPrecomputedPath:GetEndPosition

Stack: Address = 0x1af648dc (filename not found) [in C:\Program Files (x86)\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\Binaries\Win64\XCom2.exe]
```

**Comment by Sinkingeye** [comment]
Yeah,I encounter the same problem too,I can upload some save files to the modders,hope it helps:
[save_Blaster bomb bug.zip](https://github.com/long-war-2/lwotc/files/3547339/save_Blaster.bomb.bug.zip)

**Comment by pledbrook** [comment]
Fixed in [this commit](https://github.com/Favid/lwotc/commit/e6c3d4c25300ad72bb6b093c2e2f64e849e334f7) by Favid.
