### ISSUE TITLE
Disable ability point events

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#293]
As I point out in #23, the ability point events for flank shots, high ground shots, etc. don't necessarily reward good play and they encourage AP farming.

**Comment by yoshimo** [comment]
Will you still show the event so we can see that we made such an action even though it won't reward points?

**Comment by imn01** [comment]
Will it be configurable through .ini to enable disable those event?

**Comment by gen-martox** [comment]
You can only get 2 tactical AP event per missions, there is no such thing as AP farming.

**Comment by pledbrook** [comment]
That is true, although you are incentivised to get those 2 AP on every mission. The feature in no way improves the tactical gameplay.

@yoshimo No, the event is intrinsically tied to whether an ability point is awarded or not, which is random. And anyway, why? You know if you have a height advantage or are attacking from ambush.

@imn01 If you look at the associated commit, you will see that it's an INI change. You can change that number if you want.
