### ISSUE TITLE
Convert localisation files to UTF-8

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#295]
This will make it so much easier to work with them via git, GitHub, text editors and so on. The build just needs adjusting, as demonstrated by the [Covert Infiltration mod](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/afa8221900058e038ff2a0e377f1163432b03792/.scripts/build.ps1#L164).

**Comment by MrNiceUK** [comment]
Well strictly, it's only "easier" WRT to Git/GitHub diffing. Text Editors of all stripes will handle UTF-16 (which is ultimately what the localization files have to be at build time) just fine...
