### ISSUE TITLE
On loading tactical save, some enemies appear in the wrong place

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#297]
See this save file, where two of the ADVENT Gunners in vision of XCOM appear far close to XCOM than they actually are:

[save_Enemies in Wrong Place Visually.zip](https://github.com/long-war-2/lwotc/files/3349781/save_Enemies.in.Wrong.Place.Visually.zip)

**Comment by captainbeastfeast** [comment]
Cnn confirm that this occurs. In my save a unit appeared further away than it actually was..

 Isn't this a vanilla xcom 2 issue though related to 'bugging out' when you load saves too often?

**Comment by pledbrook** [comment]
No. This is something specific to LWOTC which has now been "fixed". That's in quotes because it probably breaks something else, but I'm hoping that what it breaks is less important.

**Comment by BlackRose39** [comment]
Has there been any reports when reloading/loading into a tactical game, the enemies for some reason are untargetable?
