### ISSUE TITLE
Remove promotions and Doom reduction from Covert Actions

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#298]
This is just to remove some OP aspects of Covert Actions for 1.6. The intention is to overhaul them later (#218).

**Comment by jmartinez989** [comment]
I honestly think that as far as doom reduction goes, we should make it so it can still be done but only once per faction ala reality machina's mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1368352200&searchtext=sabotage

**Comment by rrnwang** [comment]
Regarding doom reduction. I'm thinking whether if can be made more expensive, and more costly, and more time-requirement each time, that it becomes infeasible.

i.e. Start off with able to do those missions with corporals, then it requires higher ranked pairs each time, and the time needed increases by like 3 days each time - making it eventually take longer to remove a doom tick than it takes for the aliens to generate more. Additionally, require commitments of intel AND supplies (is this even possible?) that increases each time this activity is done - eventually going to like 5k intel and 5k supplies, by which case, not possible without cheating.

**Comment by tunbridgep** [comment]
I'd say make it more effective, but limit it to 1 use only, as an "oh shit" button.

Sorry for the duplicate, I didn't see this :(
