### ISSUE TITLE
Defence PCS

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#299]
When I add this to a soldier it doesn't seem to improve the defence stat in that is visible in the armory. Is the defence PCS working correctly in this build?

____

P.S i'd like to thank the team for all their hard work fixing so many bugs and making this mod work.

**Comment by jmartinez989** [comment]
Can you send a screenshot of what you are describing. In the current state the armory should not be displaying defense.

**Comment by captainbeastfeast** [comment]
There is a stat in the armory directly to the right of the dodge stat (right next to it). It varies in colour (red orange and green but the game doesn't seem to say what it is). Is this not the soldier's defence stat? I can send a screenshot if needed.

**Comment by jmartinez989** [comment]
Oh that stat is combat intelligence. Right now there is no display of intelligence in the barracks yet. We have code that we will push that will display defense in the soldier header (where you manage their loadout and other things).

**Comment by captainbeastfeast** [comment]
thankyou :) I can see the beta build in the milestone tab. Things seem to be progressing nicely.

**Comment by jmartinez989** [comment]
yep things are moving by surprisingly well. I am going to close this as you will be able to see the defense stat in the next available build.
