### ISSUE TITLE
Research resistance com objective unchecked even after completing the research 

### ISSUE THREAD

**Issue by imn01** [long-war-2/lwotc#301]
So I researched resistance communication and build resistance com before finishing first network tower. But after doing first network tower new objective appear to research resistance communication(which I already did) and the objective box is unchecked.

I'm running a list of mods mostly cosmetic. I can provide the list if needed.

Not sure about the build version but I'm sure it's after alpha-4, got that and the highlander from Kaen_SG's Twitch chat, he said it's a dev build. Save file is attached. 

[save_Resistance Com Bug.zip](https://github.com/long-war-2/lwotc/files/3360203/save_Resistance.Com.Bug.zip)

**Comment by imn01** [comment]
Also I had a weird glitch which look like vanila xcom 2 under avenger bug before the objective window appear. After clicking ok on that window I was stuck into commander's quarter. I had to press esc key to get out of it. 

Attached 3 screenshots.

![XCOM 2 Screenshot 2019 07 05 - 00 40 11 45](https://user-images.githubusercontent.com/51266990/60684117-af62b500-9ebd-11e9-8798-4169b1156920.png)
![XCOM 2 Screenshot 2019 07 05 - 00 40 25 68](https://user-images.githubusercontent.com/51266990/60684118-affb4b80-9ebd-11e9-96a9-30b22d7652e2.png)
![XCOM 2 Screenshot 2019 07 05 - 00 40 49 68](https://user-images.githubusercontent.com/51266990/60684119-affb4b80-9ebd-11e9-9126-edf01f1d2128.png)

**Comment by pledbrook** [comment]
There is some mention of this in `XComGameState_LWListenerManager`, or at least it contains a fix for what it term "busted objectives". This could be one of them.

**Comment by pledbrook** [comment]
Yep, looks like this is one of the "busted objectives" referred to. Just need to enable the 'OnGeoscapeEntry' listener that's currently sitting in `XComGameState_LWListenerManager`.
