### ISSUE TITLE
Squad management bug

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#302]
I download latest devs build *lwotc-a73b2be.zip* and start new compaign
https://www.dropbox.com/s/n1kdmdkua6ina45/lwotc-a73b2be.zip?dl=0

If i send squad on mission and add some soldiers not in this squad, they are not send.

[save_Squad management.zip](https://github.com/long-war-2/lwotc/files/3361319/save_Squad.management.zip)

![Squad_management_01](https://user-images.githubusercontent.com/51829747/60701101-2cfce400-9f03-11e9-875c-888a4cbe2c90.jpg)
![Squad_management_02](https://user-images.githubusercontent.com/51829747/60701106-31290180-9f03-11e9-99a0-70909047185e.jpg)

**Comment by nightmaRok** [comment]
Very wierd things, i off all my mods and test it, some times i can send normal, but some times not. Seems like if i change auto squad select (For example: if auto pick 1st squad and i change it to 2nd) its will be bug.

**Comment by nightmaRok** [comment]
Now play alpha 5, still have this bug with squad select

**Comment by jmartinez989** [comment]
When you start the mission with the roster of units that do not show up, do they at least show up in the tactical layer?

I have not been having this issue but I have never checked the squad management tab when infiltrating so I cannot say whether or not I am seeing the same behavior as you.

**Comment by nightmaRok** [comment]
You can test on this save, he is clear, no mods, after gatecrasher.
[save_Squadmanagement_bug_test.zip](https://github.com/long-war-2/lwotc/files/3369064/save_Squadmanagement_bug_test.zip)

I create 2 squads TEST_1 and TEST_2 and put templar in TEST_1 and one soldier in TEST_2.
If you go on mission, game auto chose some of  your squads (for example TEST_1).

![1](https://user-images.githubusercontent.com/51829747/60821191-b6364400-a1ab-11e9-843d-d3b21175ce44.jpg)

If you press on SELECT SOLDIER and add some soldiers from your roster and infiltrate, all be fine.
But if you change squad, add soldiers and then press infiltrate, only soldier from this squad be  infiltrating. 

![2](https://user-images.githubusercontent.com/51829747/60821364-15945400-a1ac-11e9-8d69-a9e3d62c1a0a.jpg)

All work fine if you after change squad press back button, you dont go at world map, its just close your privious squad.

![3](https://user-images.githubusercontent.com/51829747/60821773-d9adbe80-a1ac-11e9-948f-8257a989e834.jpg)

Try do my best, hope this help =)
