### ISSUE TITLE
Templar can't do parry after rend kill

### ISSUE THREAD

**Issue by PodliKirill** [long-war-2/lwotc#305]
Save file:
https://www.dropbox.com/s/bpx9oxn68mj1kbh/save_Templar%20no%20parry%20after%20rend%20kill?dl=0

Logs says nothing :(

**Comment by pledbrook** [comment]
I'm confused. That Templar doesn't appear to have the Parry ability.

**Comment by pledbrook** [comment]
In fact, that Templar is a Squaddie, so can't possibly have the Parry ability. Closing.
