### ISSUE TITLE
Soldiers able to get additional abilities for zero AP from Traning Center Still

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#306]
![Free Abilities](https://user-images.githubusercontent.com/52621448/60765910-8124d700-a06f-11e9-8cbc-1637f8293207.jpg)

The previous thread on this was closed a bit back, said it was fixed by a random series of letters. I only downloaded the mod yesterday, but either this problem is not yet solved, or I do not understand what if anything I am supposed to do to fix it.

**Comment by pledbrook** [comment]
It's fixed in the shortly-to-be-release alpha 5.
