### ISSUE TITLE
Pods chain activating

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#308]
It seems that there are cases where if you activate a pod by shooting one of its members within range of another pod it activates the other pod. So far I have only seen this happen when you activate via shooting.

[save_Chain Activation.zip](https://github.com/long-war-2/lwotc/files/3365688/save_Chain.Activation.zip)

**Comment by jmartinez989** [comment]
with the above save, use the skirmisher to attack the sectoid it is flanking and it should activate another pod.

**Comment by Grobobobo** [comment]
I think this has been fixed at some point because it doesn't happen anymore.
