### ISSUE TITLE
After Action Report shows wrong VIPs number, Jailbreak mission.

### ISSUE THREAD

**Issue by Aurelicornus** [long-war-2/lwotc#310]
As reported in the title, here some pictures:

![Istantanea_2019-07-08_17-28-16](https://user-images.githubusercontent.com/51163042/60822773-630dc280-a1a6-11e9-947f-9ac5bae73cc2.png)
3 VIPs.

![Istantanea_2019-07-08_17-30-26](https://user-images.githubusercontent.com/51163042/60822815-715bde80-a1a6-11e9-9181-1a0f7f5ca932.png)
However only one is showed, when three should be here.

![Istantanea_2019-07-08_17-30-42](https://user-images.githubusercontent.com/51163042/60822839-8173be00-a1a6-11e9-993e-167acfbe7835.png)
Luckly, the haven is updated correctly after the mission.

I had this bug in a Jailbreak mission.

**Comment by pledbrook** [comment]
This is a known issue and requires a highlander fix. It just hasn't been a priority since you do get all the rebels.

**Comment by pledbrook** [comment]
This was implemented with the 'GetRewardVIPStatus' event in the original LW2 I believe.

**Comment by Tedster59** [comment]
Implemented with a few MCOs in the Experimental build, if other mods MCO these screens, there will be issues unfortunately.
