### ISSUE TITLE
Duplicated AWC abilities

### ISSUE THREAD

**Issue by Aurelicornus** [long-war-2/lwotc#311]
Double Salvo perk in this soldier.
![Istantanea_2019-07-08_17-57-21](https://user-images.githubusercontent.com/51163042/60824658-41163f00-a1aa-11e9-8016-2acb145fdb13.png)

**Comment by pledbrook** [comment]
Let me know if you find any others. These are simple errors in the _XComClassData.ini_ config file.

**Comment by nightmaRok** [comment]
Some soldiers have empty additional ability slot, or its fine?
[save_Empty_ability_slot.zip](https://github.com/long-war-2/lwotc/files/3371623/save_Empty_ability_slot.zip)
![00_0](https://user-images.githubusercontent.com/51829747/60866802-f3451980-a231-11e9-8d85-527d194a9efd.jpg)
![00_1](https://user-images.githubusercontent.com/51829747/60866809-f7713700-a231-11e9-9468-a6529d40d3ce.jpg)

**Comment by pledbrook** [comment]
Yes, that's expected. I think the base game always has a chance to roll empty for a random ability slot.

**Comment by ionbomb** [comment]
Found another duplicated 'AWC' perk - Biggest Booms on a Technical:

![20190710220033_1](https://user-images.githubusercontent.com/49572327/61011668-77eb8100-a373-11e9-8b8b-a9631abedb6c.jpg)

**Comment by rrnwang** [comment]
> Yes, that's expected. I think the base game always has a chance to roll empty for a random ability slot.

I'm pretty sure that's actually because of the comma at the end of the random choices. That makes it so the last ability in the list is empty.
