### ISSUE TITLE
Time to modify/update advanced options? (Suggestions welcome)

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#312]
Greetings.

Having played LW2, I think I remembered dark events are permanent and enemies are damaged less when they're not at center of explosion? If still true, "Grim Horizons" and "Precise Explosives" are no longer needed for LWOTC since they are already integrated.

Perhaps there can be other interesting ideas and suggestions to expand upon the advanced settings.

Thanks,
Black Rose.

**Comment by NsilverDV** [comment]
This is just a suggestion, but the decision to lock perks from the same rank on promotions bummed me out pretty much! i can understand it was a decision taken for the sake of balance but still, it would be great if there was a choice to disable this.

**Comment by BlackRose39** [comment]
I totally understand the reasons as mentioned in #316 for balance reasons, plus it is how it was back in vanilla/lw2, so I have no objections regarding so. 

However, I do strongly agree that each player should be given personal freedom to edit the ini. files to their preference, especially when it comes to difficulty mods like new enemies/increased pod sizes/chosen buffs (which the chosen appearing in the campaign can be turned on or off anyways by player's choice), etc.

For a temporarily workaround, I find that you can head to xcompromotionuimod.ini and set the "abilitiesperrank" to 0 (currently only for individual classes), and it should work exactly as it should that the original promotion mod does where you can pick any many abilities per rank as much as you like. For modded classes, you'll have to add the class manually.

example:
+ClassAbilitiesPerRank = (ClassName=LWS_Specialist, AbilitiesPerRank=0)
;change the 3 to 0 to revert the change for that class. Not sure if there's a global setting that I can find anyways.

**Comment by NsilverDV** [comment]
> I understand the reasons as mentioned in #316 for balance reasons, plus it is how it was back in vanilla/lw2, so I have no objections regarding so.
> 
> However, I agree being able to change the ini. settings to allow this, whether for personal freedom/experience and/or taking into account difficulty mods like new enemies/increased pod sizes/chosen buffs (**_which the chosen appearing in the campaign can be turned on or off by player's choice anyways_**), etc. Plus, skills can be modified in xcomgamedata_soldierskills ini. file.
> 
> Reasonable players would elect to avoid abusive combinations like the frequently mentioned DFA + snapshot.
> 
> For a temporarily workaround, I find that you can head to xcompromotionuimod.ini and set the "abilitiesperrank" to 0 (currently only for individual classes), and it should work exactly as it should that the original promotion mod does where you can pick any many abilities per rank as much as you like. For modded classes, you'll have to add the class manually.
> 
> example:
> +ClassAbilitiesPerRank = (ClassName=LWS_Specialist, AbilitiesPerRank=0)
> ;change the 3 to 0 to revert the change for that class. Not sure if there's a global setting that I can find anyways.

Well it certainly worked! however to anyone using this, i would advice also increasing APs per promotion in XcomClassData.ini, +BaseAbilityPointsPerPromotion .As you'll find there is not enough AP to buy one perk. 20 should do.

**Comment by PodliKirill** [comment]
Advanced option for perks from the same rank is good idea. Add good new experience. Also, AP events during mission checkbox will be another good option.

**Comment by NsilverDV** [comment]
> Advanced option for perks from the same rank is good idea. Add good new experience. Also, AP events during mission checkbox will be another good option.

If i understand correctly there's going to be a completely different AP reward system, but until then, as of alpha 1.5 killing bosses is the only way to acquire AP. Tactical rewards however can be activated in the mod folder's XcomGameCore.ini. MaxTacticalEventAbilityPointsPerBattle is set to 0, and i think default is 2.

**Comment by The13Inquisitor** [comment]
I've mentioned this before, but the ability to disable Chosen and\or Factions for a more 'vanilla' campaign would be good for people just looking for the new mission types and improved performance.

**Comment by wdanny69** [comment]
new second wave options

chosen can be disabled or have their prime reactions disabled (as they have been reworked)
same rank perks is now allowed
