### ISSUE TITLE
UI Bug on Startup

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#313]
![Inked20190708144155_1_LI](https://user-images.githubusercontent.com/44072125/60841591-6e092880-a18f-11e9-822b-8f76b12c294b.jpg)

![Inked20190708144156_1_LI](https://user-images.githubusercontent.com/44072125/60841597-706b8280-a18f-11e9-9e78-356f405d448e.jpg)

**Comment by pledbrook** [comment]
Can be fixed by moving the credits panel in `UIScreenListener_ShellDifficulty.AddLogoAndCredits()`.
