### ISSUE TITLE
Wrong spawn crate point for smash and grab, abandoned city map.

### ISSUE THREAD

**Issue by Aurelicornus** [long-war-2/lwotc#315]
As from the title, this crate spawned in a wrong, inaccessible point of the map; Smash and Grab mission in the abandoned city.

![Istantanea_2019-07-09_18-51-53](https://user-images.githubusercontent.com/51163042/60908286-c3baff00-a27b-11e9-963a-5dae5a85ab1c.png)

**Comment by jmartinez989** [comment]
This is a known bug from WotC. I believe this might require a highlander change but not sure.

**Comment by copyrite** [comment]
The map where this occurs has been removed from the map pool.
