### ISSUE TITLE
Combatives perk - Animation Glitch

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#318]
I have been noticing this issue since the lw2 perk pack came out, (it's uninstalled now, just using lwotc) but everytime a unit activates combatives perk (unit targeted by stun lance, etc.), they seem to do the same attack animation the stun lancer does, but then no damage pops out. Then, they do a normal melee attack animation afterwards and the damage proceeds as normal.

Just a visual glitch in short.

**Comment by pledbrook** [comment]
I think this was probably fixed (but the Bladestorm/Combatives glitch that causes enemies to use the shooting animation for the melee attack is still there).
