### ISSUE TITLE
Unfunctional Labels on Squad Management within Barracks (Not Geoscape)

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#320]
This is the same issue found within #197. Just needs that fix as mentioned there where you go to create a squad in the armory window.
Thanks!

**Comment by pledbrook** [comment]
I don't suppose you know if those column headers could be clicked to sort the list in original LW2? And I think it's much less easy to change the implementation here than it was for the View Infiltrating Squad mod.
