### ISSUE TITLE
how to update from alpha 4 to alpha 5

### ISSUE THREAD

**Issue by awesomeness031** [long-war-2/lwotc#321]
hello, new here. Just wondering how do I update my game to alpha 5 since it's out already. I already have a saved game but in alpha 4. my question is do I just overwrite the files of alpha 4 from alpha 5? will I still be able to continue my playthrough/saved game?

sorry new here. if this isn't allowed just ignore or delete it thanks!

**Comment by pledbrook** [comment]
I recommend you start a new campaign with alpha 5 if possible, or at least wait until you've completed/stopped the current one before upgrading.

The upgrade, simply remove the alpha 4 versions of the LongWarOfTheChosen and X2WOTCCommunityHighlander folders in your "Mods" directory and replace them with the alpha 5 versions.

**Comment by awesomeness031** [comment]
oh ok thanks! been testing alpha 4 and the only issues i found are already posted.
