### ISSUE TITLE
Floating Heads in Skirmish

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#322]
It looks like, in **_Skirmish Mode_**, there is still the case of floating heads. (Related to #117)

![floating heads skirmish](https://user-images.githubusercontent.com/44072125/61019729-719bdb80-a358-11e9-94ff-8602577d47a1.jpg)

**Comment by pledbrook** [comment]
This won't be a priority I'm afraid. It would probably only be fixed if we overhaul how the alien pack works.

**Comment by pledbrook** [comment]
Pretty sure this is now fixed
