### ISSUE TITLE
LWOTC build requires PowerShell 3

### ISSUE THREAD

**Issue by NsilverDV** [long-war-2/lwotc#325]
Hello! I apologize if it's all the result of my inexperience. I wanted to build the mod myself so maybe i could tweak things later on. I built and cooked the lwotc-highlander and it seems to be running just fine, but running build-lwotc.bat (with no modifications at all to the mod itself, aside from placing the content on the "content" folder as instructed) creates a flawed LongWarofTheChosen folder on the SDK, and not on the game folder (Which leads me to believe something went wrong). Placing it in the main game folder and running it causes the mod to crash when starting GateCrasher.

Mounting and building the mod through the Modbuddy yields no "errors" but does the same: A botched LongWarOfTheChosen folder on the SDK's mods. I will post the crash log file and all errors and warnings i could find while running the .bat.

I apologize for the first capture being spanish. Essentially Get-ChildItem can find no parameters that coincide with the name of the 'Directory' Parameter.

![errors](https://user-images.githubusercontent.com/52796147/61072562-ef5bf780-a3e9-11e9-93bd-1b953b27c6a0.png)

[XCom-CL374751-2019.07.11-14.17.26_Logfile.log](https://github.com/long-war-2/lwotc/files/3383268/XCom-CL374751-2019.07.11-14.17.26_Logfile.log)

**Comment by pledbrook** [comment]
What do you have the `%XCOM2SDKPATH%` and `%XCOM2GAMEPATH%` environment variables set to?

**Comment by NsilverDV** [comment]
> What do you have the `%XCOM2SDKPATH%` and `%XCOM2GAMEPATH%` environment variables set to?

The enviromental variables are set like so:
XCOM2GAMEPATH: D:\Program Files\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen
XCOM2SDKPATH: D:\Program Files\Steam\steamapps\common\XCOM 2 War of the Chosen SDK

**Comment by pledbrook** [comment]
So your PowerShell doesn't like the `-Directory` argument it looks like. What version of Windows are you running on?

For the TLE/Day0 warnings, take a look at the [this Reddit post](https://www.reddit.com/r/xcom2mods/comments/9nepzu/known_issues_with_the_new_wotc_sdk_and_some_fixes/).

**Comment by NsilverDV** [comment]
> So your PowerShell doesn't like the `-Directory` argument it looks like. What version of Windows are you running on?
> 
> For the TLE/Day0 warnings, take a look at the [this Reddit post](https://www.reddit.com/r/xcom2mods/comments/9nepzu/known_issues_with_the_new_wotc_sdk_and_some_fixes/).

Yes, the TLE/Day0 issues were done with, though the problems with the -Directory argument and XcomSoundManager persist. Currently running on Windows 7, Powershell 2.0. So that might be it.

**Comment by pledbrook** [comment]
Yeah, it looks like `-Directory` requires PowerShell 3.0. I'm not that keen on trying to work out a fix myself since I don't know PowerShell at all, but happy to accept patches.

**Comment by pledbrook** [comment]
Sorry, I think the requirement has gone up even further. I don't see the build being modified for older PowerShell versions.
