### ISSUE TITLE
'Hero' WOTC characters are missing final promotion tier (unchanged from vanilla WOTC)

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#327]
In game play terms this means you can't train them up to become field commander officers and other classes have access to more skills in the late game. They miss out on perks other classes get when promoted to master sergeant.

**Comment by jmartinez989** [comment]
This will likely be addressed in the alpha release as we have already implemented these ranks for the hero characters. At this point we are just testing them for balance. Still a few things left to tweak.

**Comment by pledbrook** [comment]
Fixed in [this commit](https://github.com/long-war-2/lwotc/commit/95b36ab529bb79b8e991343385a14abddde70999).
