### ISSUE TITLE
Highlight tiles with evac flare where soldiers can't evac

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#328]
e.g you place the beacon under a bridge overhead. The area of the ' blue beacon evac zone' that is under the bridge can't be used for soldier evac. because of the bridge is in the way. However, the part of the blue beacon area that isn't under the bridge (or other overhead terrain) can be used by soldiers for an evac. I have seen this numerous times during my play-through. In-game UI states 'Not inside EVAC zone' when this occurs.

**Comment by tracktwo** [comment]
This is vanilla behavior, not LW specific. The game will prevent you from placing an evac zone if too many of the tiles would be blocked, somewhere about half IIRC, but it specifically doesn't require all tiles to be clear.

**Comment by BlackRose39** [comment]
Would be neat if there is some display of which tiles of the evac would be available and which tiles are off limits, like showing the red cross during evac placement preview. I would say it's similar to https://steamcommunity.com/sharedfiles/filedetails/?id=1306820727.

**Comment by pledbrook** [comment]
I've changed the issue title to reflect the request to display which tiles are under cover. I'm not sure we'll ever get round to this, though!

**Comment by pledbrook** [comment]
Yeah, can't see this happening, sorry.
