### ISSUE TITLE
Coil gun not shredding any armour 

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#329]
My coil rifles tested on the latest alpha 5 build do not appear to be shredding any armour at all.

Edit: shredding is occurring against some enemies and not others. Shredding didn't work against heavy advent mechs.

**Comment by captainbeastfeast** [comment]
its not yet clear to me why the coil gun is shredding sometimes and not others. However, it seems that this issue hasn't been fixed from previous builds (yet). I can confirm that the +1 shredding resistance order also does not stack with coil gun shredding when the coil gun does shred correctly.

**Comment by BlackRose39** [comment]
Hello.

Referring to the weapon chart here: https://www.ufopaedia.org/index.php/Weapons_(LW2)

I don't recall that coilguns shred any armor from enemies from the original lw2 mod. There's no shredder perk on the units I assume? The coilguns should innately only be piercing one point.

**Comment by pledbrook** [comment]
As BlackRose39 says, the shredding only occurs if there if the shooter has a relevant perk or has shredder ammo. As stated in #230, coilguns don't shred as much armour as they should when the shooter does have a source of shred.

I'll make a note of Weak Points in #230 and close this. If you can confirm with evidence that Coilguns are failing to shred even when the shooter has a source of shred then please do reopen this.
