### ISSUE TITLE
Chosen ballistic weapons don't confer rupture (1) effect 

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#330]
Even though they are 'final tier' plasma weapons they don't confer rapture (1) on targets that they hit, unlike other beam weapons. I suggest that this effect could apply when the chosen use them as well, as I feel the chosen are a bit weak in general.

**Comment by ansabalirai** [comment]
The question is if we want them to apply the effect. 
Thematically, they do not seem to fire a plasma based projectile/beam. Also, IIRC, they come with superior/elite attachments and unique aspects (guaranteed crits against psi for warlock, 100% hit chance for katana, snapsot for dark lance, etc.), so they seem already pretty OP to me

**Comment by jmartinez989** [comment]
Yeah I don't think we will have them confer rupture. I believe that just bringing their damage in line with plasma weapons is good enough as their special bonuses are already so good.

**Comment by pledbrook** [comment]
These were reworked as side grades and aren't considered plasma weapons.
