### ISSUE TITLE
Game UI text doesn't display a stunned enemy as being stunned

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#331]
When stunned the game UI will state that an enemy has been stunned. However,  when highlighting the 'enemy alien' icon the UI text doesn't say that the enemy is stunned (it does display other status effects such as poisoned or wounded due to red fog etc..).

This can be slightly problematic when you have hit an enemy with a stun rocket (red smoke), or if the enemy is obscured from your vision.

**Comment by pledbrook** [comment]
YAF1 does show this information, so let's just rely on that since it's now a required mod.
