### ISSUE TITLE
MacOS installation instructions?

### ISSUE THREAD

**Issue by ostrolucky** [long-war-2/lwotc#334]
So MacOS version apparently has different folder structure for mods. So instructions at https://github.com/long-war-2/lwotc/wiki/Play-testing-Long-War-2-%5BWOTC%5D don't work for me.

It seems to be of following format
`/Users/{username}/Library/Application Support/Steam/steamapps/workshop/content/{6digitnumber}/{10digitnumber}/`

And making up these numbers and putting there content of `LongWarOfTheChosen` folder from zip file does not work, it does not make it appear in mod manager. How do we need to proceed?

**Comment by pledbrook** [comment]
No, it's a different location.  Try the instructions detailed [here](https://support.feralinteractive.com/en/mac-linux-games/xcom2/faqs/modding_steam_full/), specifically under the heading "Installing mods that you have downloaded".

**Comment by ostrolucky** [comment]
Well could you pls link to it in https://github.com/long-war-2/lwotc/wiki/Play-testing-Long-War-2-%5BWOTC%5D ?

**Comment by ostrolucky** [comment]
So I have it in `/Users/gostrolucky/Library/Application Support/Steam/steamapps/common/XCOM 2/XCOM2Data/xcomgame/mods/LongWar2_WOTC-1.6-alpha-5.1 2/LongWarOfTheChosen/LongWarOfTheChosen.XComMod` (yes copied whole zip content)

And content of `defaultmodoptions.ini` is 
```
[Engine.XComModOptions]

ActiveMods="LongWarOfTheChosen"
```

But it shows blank in mod manager and after enabling it anyway, it doesn't work in game.

<img width="913" alt="Screenshot 2019-07-14 at 12 56 36" src="https://user-images.githubusercontent.com/496233/61182686-165b3900-a637-11e9-8542-6b04e21403ad.png">
