### ISSUE TITLE
Consider allowing multiple abilities per rank

### ISSUE THREAD

**Issue by cshen6** [long-war-2/lwotc#337]
Just started Lwotc alpha, and would like to discuss this issue regarding balance. Multiple abilities per rank is definitely one of WOTC's favorite feature to a lot of ppl. I also liked Musashi's RPG Overhaul mod, which opens up even more possibilities for xcom soldiers. 

So I would love to be able to select a few abilities even in the same soldier rank, which current alpha version dis-allows. It can be balanced by requiring significantly more AP points on main branch abilities, also nerf a few abilities (say DFA can only be triggered once per turn, which RPGO did). 

I understand Lwotc is designed for each soldier to take one ability per rank for balance reason. And I suspect we may soon see such sub-mod, once Lwotc hits the workshop. Just want to discuss & see what others think.

**Comment by NsilverDV** [comment]
I'm thinking it should be left as an option. I personally found that feature really fun on all my former WOTC runs and i didn't even get to buy all that many perks. Or we should at least inhabilitate the most broken combinations of it.

Check out #312 . BlackRose39 gave me a temporary workaround for it, but you'll need further .ini tweaking (Actually granting each soldier enough AP to buy at least one skill per rank (XcomClassData), and reactivating tactical events(XcomGameCore))

**Comment by cshen6** [comment]
Thank you! The ini edit works for current save!

I would also like an option to toggle it on/off, with some balancing on those OP combinations.

**Comment by Anxoczt** [comment]
Oh hell yes, it makes your soldiers more potent and in general more useful.

**Comment by pledbrook** [comment]
It does indeed make your soldiers more potent and more useful. That's kind of the reason to restrict those abilities. You are also taking away a tough decision that the player needs to make in terms of choosing perks. This mod is about overcoming a challenge and having to take tough decisions regularly. This request runs counter to that.

One other reason that this is unlikely to change any time soon is that I hope that RPGO will be compatible with LWOTC by the time of the release, so those folks that really want to choose lots of abilities will be able to do so. Just understand that that's not the Long War experience.

**Comment by gen-martox** [comment]
Actually restricting 1 ability per rank isn’t a tough choice, ppl will just pick the ability that will give them the best chance to win. What would be a tough choice would be to allow multiple abilities at the cost of 30+ AP, then have the AWC and pistol abilities at the cost of 15 AP or less. This way ppl would have to choose to between getting a more powerful and expensive ability or getting a couple cheaper abilities that could be just as good, and this would lead to more interesting class builds.

**Comment by jmartinez989** [comment]
@gen-martox but doing that really doesn't change anything by that logic. People will then still just pick the ability that will give them the best chance to win.

I definitely feel that being restricted to 1 ability per rank makes a lot more sense and does feel like a tough choice a lot of the time and feels more meaningful (though there are some abilities out there that are so good that are an auto pick or so bad that they are an auto avoid so those have to be looked at)

**Comment by gen-martox** [comment]
Well no probably not, ppl will always pick the abilities that will give them the best chance to win but allowing multiple abilities per rank will at least give them a reason to use abilities they wouldn’t normally use.

it’s really not a tough choice which abilities I get, I look at my soldiers stats and decide what I want to do with that soldier and then get the abilities for the purpose, it’s really not that tough of a choose.  

it’s all fine a good to look at the abilities that don’t get used a lot but that will just open up a bigger can of worms. I mean you can buff up some abilities to make them on par with others but that could lead to more OP abilities and you can try to nerf other but that might lead to them being useless/worthless. Just as example, I almost never get the gunners shedder ability over hail of bullets or mayhem, and while shedder is a good ability i think the other 2 are far better. 

Allowing multiple abilities per rank will lead to more tough choices especially with the changes to how much AP soldiers can get.

**Comment by cshen6** [comment]
@jmartinez989 
yes I agree, ppl always choose the best perk to win. Say when I used the RPGO mod, a lot of soldiers end up having a few same core perks -- so variability ends up lower. So despite the mod being cool, it makes the game easier and less challenging, and I still prefer the soldier variability in LW.

My hope is that to have multiple abilities per rank, but with a carefully balanced AP & some re-designed abilities to make LW2 having the same fun as before - so if not, I would still enjoy with single ability per rank.

However, since this option is so easily moddable, I imagine a lot of ppl who like this WOTC feature will just mod this option at the cost of reducing the fun of LW2 inadvertently --  it is really hard to resist one or two cool abilities in the other branches!

**Comment by MiserablePileOfBugs** [comment]
I very much like it the way it's now. I don't get why Firaxis suddenly allowed the player to get as many skills as they want instead of just adding new ones like we have in the mod right now. It shows just how lazy these devs are. Or maybe they were too focused on the story to really care about game design.

**Comment by cshen6** [comment]
> I very much like it the way it's now. I don't get why Firaxis suddenly allowed the player to get as many skills as they want instead of just adding new ones like we have in the mod right now. It shows just how lazy these devs are. Or maybe they were too focused on the story to really care about game design.

Chosens are too strong to handle in WOTC, so they need to buff soldiers up.

I am currently playing LW2 alpha 5 on legendary with chosen enabled. Usual missions are extremely engaging just like LW. Then I had two missions with chosen assasin comes in, which I almost lost ... save scum and with squad half injured to get these two done.  

The first mission was my A-team with very good stat, and I was helped by having AWC with one extra ability per soldier.  Still need to save scum to know her location in advance, and manage to face the assasin with just another pod of two aliens; luckily the mission timer freezes, otherwise I will lose entire squad as well. I also had a ranger in team, so that short-range gun (forget the name) deals a lot of damage to half her health bar -- so now I keep at least 1 ranger each squad and will make it 2 if I can get more soldiers with ok aim.

I cannot imagine how difficult it may get after Chosen & alien gets stronger in game, and whether my soldiers can keep up the speed with only one ability per rank (AWC helps, but the rolled-ability sucks quite often). Not to mention that Chosens make the strategy level more difficult as well.

With chosen enabled, the balance shifts a lot to alien's favor, and I think a lot of luck is needed to not lose out the squad whenever chosen appears (And I have been playing XCom / LW / XCom 2 / LW2 for at least >2000 hours on legendary). Without chosen though, there is indeed no need for extra soldier abilities & I can handle the missions pretty well just like in vanilla LW2.

Alternatively, if AWC abilities can be slightly optimized for each rank (so snipers no longer gets these useless grenades perks), that may balance it back -- but then again, mission without chosen will get easier.

**Comment by Maebalzurakin** [comment]
> @jmartinez989  
> However, since this option is so easily moddable, I imagine a lot of ppl who like this WOTC feature will just mod this option at the cost of reducing the fun of LW2 inadvertently -- it is really hard to resist one or two cool abilities in the other branches!

This is what will happen.  Steam already has new mods popping up with LW2 classes and abilities under witch the WOTC AP training rules apply. 

>  @pledbrook
> One other reason that this is unlikely to change any time soon is that I hope that RPGO will be compatible with LWOTC by the time of the release, so those folks that really want to choose lots of abilities will be able to do so. Just understand that that's not the Long War experience.

I know you want to re-create that 'kicked in the balls' LW experience.  Some people want that.  Most don't.  Some people select Legend and some select Rookie.  Some people play on Iron Man, some don't.  Firaxis wanted to appeal to the greatest audience, so they gave people the option.  LW2 has some amazing content that everyone wants.  Wouldn't it be a shame to put in all these years of effort for something someone else was going to change with a mod, then have that simple little mod be the preferred way that people play?

Your solution is actually very simple.  Allow people to use their AP to buy whatever they want.  Put difficulty options in the LW2 mod config menu that controls how plentiful AP is.  If on the most difficult setting, someone has to fight through the entire campaign to get enough AP to get one extra ability, then I am sure everyone would agree they had 'the Long War experience.'

**Comment by siath70** [comment]
Make the Chosen an option in the config, when you chose to turn them on it opens up another selection to enable WOTC buy abilities function.
Giving people options is not a bad thing, maybe you want the Chosen in and don't want to use ability to buy more abilities, well don't buy them. Ultimately it's up to the person playing as to what they will do or want.

**Comment by pledbrook** [comment]
Implemented #505, which closes this issue
