### ISSUE TITLE
No music playing on advent city center maps

### ISSUE THREAD

**Issue by MiserablePileOfBugs** [long-war-2/lwotc#338]
I saw this two times since alpha 5.1 but never before. There is no music playing at the start of the mission. When you engage the aliens, the combat music plays normally.

[save_music not playing.zip](https://github.com/long-war-2/lwotc/files/3390075/save_music.not.playing.zip)

**Comment by BlackRose39** [comment]
I can confirm that this issue has happened on multiple occasions for me.

**Comment by tn67078** [comment]
I'm having the same issue. Sound effects and combat music play normally, but the music that should play when not detected/engaged doesn't work.

**Comment by aturaki** [comment]
+1.

**Comment by Bluemethod** [comment]
This issue is still active. Any fixes yet?

**Comment by RogueSeeker24** [comment]
> This issue is still active. Any fixes yet?

Oh good, it's not just on Jailbreak missions then (I've only had those in cities). My second thought was it might be a conflict with the Soundtrack Restoration mod, but no dice.

Said mod author mentions it overrides "XComTacticalSoundManager" and "XComStrategySoundManager" classes, so it got me thinking that maybe there's something missing in there but I'm not really sure where to look for them.

**Comment by copyrite** [comment]
Pretty sure this has been fixed. Closing.
