### ISSUE TITLE
Return Fire has an erroneous description 

### ISSUE THREAD

**Issue by MiserablePileOfBugs** [long-war-2/lwotc#342]
It looks like Return Fire mentions the secondary weapon of each class instead of the pistol. This soldier is a ranger but if you select a specialist, the description will instead be "fire back with your gremlin" and so on for each different class.

I haven't tested the ability in combat yet but one of my assaults just learned it so I'll be able to very soon.

![return fire description error](https://user-images.githubusercontent.com/51516141/61277607-d0c37b00-a7b2-11e9-8d9d-6d2376651039.jpg)

**Comment by rrnwang** [comment]
I believe the description defaults to whatever the unit's secondary weapon is. For gunners it's their combat knife. For Sharpshooters, it's holotargeter. Etc.

**Comment by MiserablePileOfBugs** [comment]
I have confirmed that the ability works as intended so it's only a bug in the description.

**Comment by pledbrook** [comment]
I'm guessing this was a bug in original LW2 as well. It's something we probably need to take into account for Sharpshooter primary pistols @jmartinez989.

**Comment by KaesoVenator** [comment]
Came to report this. I don't remember seeing this in the original LW2, though. Maybe it can be changed to a static "sidearm" description?

**Comment by Grobobobo** [comment]
Was fixed a while ago, and is no longer relevant due to being replaced with magnum.
