### ISSUE TITLE
Is dark event spawning bugged?

### ISSUE THREAD

**Issue by cshen6** [long-war-2/lwotc#343]
I am currently in alpha 5. It turns out I can counter most dark events in the first three months just in my home region. 

I recall LW2 should have dark event happening in every region, so we cannot stop some of them. So is the spawning system different now, or is it bugged, or just I am lucky?

**Comment by jmartinez989** [comment]
Nope this is not a bug, you are just getting super lucky. From my play testing I have only been able to counter a few dark events in my home regions some times. They are definitely spawning all over the world (at least they are for me).

**Comment by cshen6** [comment]
Thank you for the quick comment! I will just close it then -- if I keep on getting dark events countered in home region in the next few months, will go buy a lottery ticket :-)

**Comment by ansabalirai** [comment]
This is indeed a good thing to point out and it would be good if others can confirm that the spawning of the GOps for countering the dark events (COINResearch and COINOps) is indeed as in LW2 and the player does not always get the chance to counter them, for balance and all that...
