### ISSUE TITLE
In which mission I can meet the Choosen Ones?

### ISSUE THREAD

**Issue by Adromolek** [long-war-2/lwotc#344]
I want to konw in which mission I can meet the first choosen one? Cause I always reroll and reroll and reroll again LOL

**Comment by jmartinez989** [comment]
you first meet them after first completing Liberation 2 mission. Also you have to set `ACTIVATE_CHOSEN=true` in order for them to show up at all.

**Comment by Adromolek** [comment]
> 你在第一次完成解放2任务后第一次见到他们。你也必须设置`ACTIVATE_CHOSEN=true`它们才能显示出来。

Thanks a lot, and where can I set the "ACTIVATE_CHOSEN=true"? And need I reroll again for this set?

**Comment by jmartinez989** [comment]
Oh sorry. that is in `XComLW_Overhaul.ini`

**Comment by Adromolek** [comment]
> 哦对不起。那是在`XComLW_Overhaul.ini`

Yep, I got this. Thanks a lot

**Comment by jmartinez989** [comment]
no problem. closing the issue.
