### ISSUE TITLE
UI Abilities HUD Error

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#347]
Well, decided to push the limits of the UI abilities list and got this!

![ui error](https://user-images.githubusercontent.com/44072125/61341292-f7110700-a802-11e9-8b68-bf333f05d46c.jpg)

![ui error 2](https://user-images.githubusercontent.com/44072125/61340752-e52e6480-a800-11e9-8889-00673d394ef8.jpg)

A save isn't necessary since it's just some ability mods (overwatch all, medikit/stabilize me, etc.) as well as officer perks and pistol utilities that got me this error. 

But, it's possible to hit this limit anyways, such as a max ranked soldier with many abilities who is also a max ranked officer with all those officer perks, all active (not passive) AWC abilities, packed with usable items AND with all pistol utility perks, as well as other cumulative circumstances (evac, pick up body, hack, etc). 

Consider enhancing the UI to support another column of abilities or two.

**Comment by BlackRose39** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1374808007

Just wanted to leave this here in case someone wants to take a look. Same thing here, but with more rows so it doesn't overflow.

**Comment by Grobobobo** [comment]
I don't think this is something we can really do anything about other than decreasing the amount of useless icons in the future.
