### ISSUE TITLE
Freed civilians trigger a reveal check on hidden Reapers after moving

### ISSUE THREAD

**Issue by MiserablePileOfBugs** [long-war-2/lwotc#348]
After hacking the cells of some captured rebels and rookies with my specialist, it occurred to me that each one of them triggered a reveal check on my hidden Reaper after they finished moving. Also when this happens, the Reaper's stealth UI bugs out because only some of the elements are displayed. The reveal percentage seems to be around 30%. Very annoying bug.

[save_civilian reveal reaper.zip](https://github.com/long-war-2/lwotc/files/3400647/save_civilian.reveal.reaper.zip)

**Comment by Grobobobo** [comment]
No longer relevant.
