### ISSUE TITLE
Injured soldiers available to be sent on mission (2)

### ISSUE THREAD

**Issue by MiserablePileOfBugs** [long-war-2/lwotc#349]
It looks like this issue (#111) isn't resolved yet. On occasion, the auto fill squad feature will pick injured soldiers. Load the save and start a new infiltration to see the sniper with 1HP.

Pledbrook mentioned injured soldiers mistakenly receiving the **eStatus_Active** status so it could be that the bug causing this is still out there.

Don't know if it will help but the injured sniper in question had last participated in a faceless mission where it was shot two times and was bleeding out at some point.

[save_injured soldier squad select.zip](https://github.com/long-war-2/lwotc/files/3400716/save_injured.soldier.squad.select.zip)

**Comment by Grobobobo** [comment]
I think this was already fixed at some point.
