### ISSUE TITLE
Melee weapon strike (rend also) crash the game

### ISSUE THREAD

**Issue by frigle** [long-war-2/lwotc#350]

**Comment by jmartinez989** [comment]
Can you please provide a description as to what is happening and also possibly a save file of the issue. No one else is reporting this issue so more information would be appreciated.

**Comment by BlackRose39** [comment]
I confirm that this is happening.

When you right click to attack an enemy, nothing happens, except for maybe some lag. But you go to click on an melee icon to attack an enemy, the game hangs indefinitely.

The same thing happens to rapid fire.

I'll see if I can upload a save if there are no further responses.

**Comment by jmartinez989** [comment]
If all of this is in skirmish mode it might be a while before any of the issues in skirmish mode ever get resolved. From what I can tell skirmish mode works differently than the regular base game and has issues that lwotc cannot handle right now.

I know there is an issue where skirmish mode has floating heads for the advent that are part of the alien pack even though floating heads was fixed a while back.

**Comment by BlackRose39** [comment]
No, this happens in the normal game.

**Comment by BlackRose39** [comment]
I also am noticing another issue, it seems if you move your soldiers at the same time right after another soldier finishes reaching their destination, the game sometimes hangs.

**Comment by pledbrook** [comment]
This is an issue with the graze band implementation, but it's not at all clear why it's happening. That's why we need as many data points (save games) as we can get.

**Comment by BlackRose39** [comment]
I see, thanks for the reply! So in the meantime, just set graze to 0 for now?

**Comment by pledbrook** [comment]
I'm pretty sure that won't solve the problem I'm afraid, but you're welcome to try.

**Comment by Jaffapug** [comment]
Having the same issue, gatecrasher, rending a trooper with Templar and screenfreeze with eventual CTD.

[save_AUTOSAVE- Campaign 105, Mission 1, Turn 3.zip](https://github.com/long-war-2/lwotc/files/3412744/save_AUTOSAVE-.Campaign.105.Mission.1.Turn.3.zip)

**Comment by cshen6** [comment]
This sounds an important bug! 
But I didn't encounter this bug though, 6 months into the alpha 5 -- and I have been rending / slashing all the time using Templar / Shinobi. So the bug should be situational.

**Comment by MiserablePileOfBugs** [comment]
Nothing to do with swords but since alpha 5 my game tends to crash a lot and always in the exact same situation: after taking the last action that completes the map. It doesn't mater if I kill the last remaining enemy or move my last soldier to the evac zone: as soon as the animation starts the game dies.

I can't remember having so much crashes before even after playing LW2 for hundred of hours.

**Comment by BlackRose39** [comment]
Yes, in regards to my previous post about the game freezing when moving another soldier at the same time, the other was finishing their animation when the game hanged forever, forcing a program shutdown.

Even happens too when enemies move, and when about to take their second action, the game freezed.

**Comment by pledbrook** [comment]
If you're encountering regular crashes, then I recommend you try to clean up your installation. That primarily means clearing out your config directory (_Documents\\My games\\XCOM2 War of the Chosen\\XComGame\\Config_) and the _profile.bin_ file (in _Documents\\My games\\XCOM2 War of the Chosen\\XComGame\\SaveData_). And if you started the campaign prior to alpha 5, start a new one with alpha 5.

The mod really shouldn't be crashing as much as you seem to be experiencing, so I'm guessing the main issues are connected with incompatibilities with other mods and earlier versions of the mod.
