### ISSUE TITLE
Tab to Next Soldier not working at abilities screen

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#352]
While at the promotion screen in barracks, shift switches soldier, but tabbing does not, forcing players to return to previous screen to tab back to soldier.

**Comment by pledbrook** [comment]
That's the nature of the new promotion screen. Not sure if it's possible to change the behaviour. Probably.

**Comment by Favid** [comment]
I am able to use Tab to cycle through soldiers while in the new promotion screen. Has this been inadvertently fixed?

**Comment by pledbrook** [comment]
This is down to whether a final-release version of the Community Highlander is used or not.
