### ISSUE TITLE
Skill conflict of PSI class with WotCRichardsClasses3TreeVer mods

### ISSUE THREAD

**Issue by Adromolek** [long-war-2/lwotc#353]
If you active this mod and WotCRichardsClasses3TreeVer mod, the mage PSI class of WotCRichardsClasses3TreeVer mod cannot learn VoidRift, Domination and Bastion skills because they need Solace skills, but even I have learned Solace, I still cannot learn these skills.

**Comment by Grobobobo** [comment]
we're not aiming for compatibility with other psi mods, and we already have drastically changed the psi tree since 2019.
