### ISSUE TITLE
Tactical Rigging doesn't do anything

### ISSUE THREAD

**Issue by MiserablePileOfBugs** [long-war-2/lwotc#355]
In LW2, armors don't provide bonus utility slots like in the base game so all soldiers always have three slots (except the Grenadier class which has an additional grenade slot). Right now, Tactical Rigging doesn't do anything at all. So we should consider either removing it or changing the bonus.

![tactical rigging](https://user-images.githubusercontent.com/51516141/61576887-11d3cc00-aae0-11e9-9c02-bb1ae0dfb763.jpg)
![tactical rigging 2](https://user-images.githubusercontent.com/51516141/61576888-1304f900-aae0-11e9-8c22-577b6e16435f.jpg)

**Comment by pledbrook** [comment]
@jmartinez989 Does the Reaper rebalance change Tactical Rigging?

**Comment by jmartinez989** [comment]
The reaper rebalance just removes it since it doesn't do anything.

**Comment by pledbrook** [comment]
Removed by [this commit](https://github.com/long-war-2/lwotc/commit/95b36ab529bb79b8e991343385a14abddde70999).
