### ISSUE TITLE
Additional yellow move after pulling out the pack on double move

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#356]
After pulling out the pack on double move, i have additional yellow move

[save_Pull_bug_additional_move.zip](https://github.com/long-war-2/lwotc/files/3414368/save_Pull_bug_additional_move.zip)

![Pull_bug_additional_move_01](https://user-images.githubusercontent.com/51829747/61587968-6fc5e980-ab9c-11e9-82f1-3bf1bb911779.jpg)

![Pull_bug_additional_move_02](https://user-images.githubusercontent.com/51829747/61587971-73597080-ab9c-11e9-84ed-ba54ca58e4c2.jpg)

**Comment by pledbrook** [comment]
This is a bug in original LW2 and probably the base game. If you end within a blue-move distance of your starting square, the game treats that as a blue move. It can be abused quite heavily, but I doubt there's anything I can do about it.

**Comment by nightmaRok** [comment]
Ok, i close then this issue
