### ISSUE TITLE
"Trial By Fire" Resistance Order

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#357]
With the removal of the AP points reward system, this order now does nothing, correct?

Maybe could have it grant all soldiers that level that month extra AP, or maybe remove it so it does not come up and permanently take up an orders slot.

**Comment by cshen6** [comment]
I am playing with chosen on, and I think defeating the chosen (which does not count as Tactical AP) still gives 10AP, so that resistance order still doubles that award. (and 10*2 is pretty hefty..)

**Comment by pledbrook** [comment]
Not sure what to do with this. For a start, it has the same name as an officer perk, which is confusing. And it only applies to defeating the Chosen, not the AP automatically gained on promotions. We could potentially make it apply to the promotion AP as well, but I don't know how difficult that would be. And it could be insanely strong. AP is just an all round headache currently :smile:

**Comment by ToastedAmphibian** [comment]
Yeah, having it affect promotion AP seems like a huge problem. Does the AP go away if you remove it? If your combat intelligence increases, how do you recalculate, blah blah. 

Honestly, removing completely is probably good enough. No idea how this game is coded, so maybe blanking it out, or lowering it's probability of being selected, is difficult.
