### ISSUE TITLE
Small detection radius Hive Queen\Chryssalid soldier\Gatekeeper

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#358]
Looks like for reaper 2x2 and 3x3 tiles units still have 1 tile detection

[save_No_detection_hive_queen.zip](https://github.com/long-war-2/lwotc/files/3414775/save_No_detection_hive_queen.zip)

![No_detection_hive_queen_02](https://user-images.githubusercontent.com/51829747/61593499-dec92f80-abe8-11e9-8537-0c335346de5c.jpg)
![No_detection_hive_queen_01](https://user-images.githubusercontent.com/51829747/61593502-e7216a80-abe8-11e9-8f99-2e92277bfe1f.jpg)
![No_detection_hive_queen_03](https://user-images.githubusercontent.com/51829747/61596041-0202d780-ac07-11e9-80ae-01c95d65cbed.jpg)

**Comment by rrnwang** [comment]
This issue also exists for Sectopods, last I recall. This is because the detection radius extends from one of the model's foot.

**Comment by nightmaRok** [comment]
I close this issue because after rebalance reaper have highter detection radius
