### ISSUE TITLE
Bladestorm not always working?

### ISSUE THREAD

**Issue by cshen6** [long-war-2/lwotc#359]
The description says "Free sword attacks on enemies that enter or attack from melee range."

So far, it works 100% of the time for enemies entering or leaving the melee range;
however, I saw a number of times that when enemy does not move in adjacent tile (which can be melee-d by slash next turn as I check the shinobi), but simply attacks within melee range on another team member, and does not trigger bladestorm.

Not entirely sure whether that is just behavior from vanilla WOTC. But in vanilla WOTC with RPGO mod (which I used before LW2 alpha 5), I recall bladestorm works fine all the time.

**Comment by pledbrook** [comment]
If you have a save file that demonstrates the issue, that would be helpful. I don't know whether this is intentional or not.

**Comment by Grobobobo** [comment]
Nothing like that has been reported since.
