### ISSUE TITLE
Sting grenade bug

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#360]
Never see this before, maybe its new item? but i cant made it. As i know only grenadiers ability do this, so i think its a bug.
[save_Sting_grenades_bug.zip](https://github.com/long-war-2/lwotc/files/3418879/save_Sting_grenades_bug.zip)

![Sting_grenade_01](https://user-images.githubusercontent.com/51829747/61658649-7785ab00-acce-11e9-9af0-93a6d1637d64.jpg)

**Comment by jmartinez989** [comment]
This is something I have recently noticed as well. For some reason the sting grenade perk puts an actual Sting Grenade into the grenadiers inventory and then saves it after the tactical layer. Not sure why this is happening. It could be that post mission cleanup is not removing those like it should.

**Comment by ToastedAmphibian** [comment]
The same thing is occurring with the Dense Smoke perk. And both of these grenades can be equipped by any soldier. Kind of a problem.
