### ISSUE TITLE
Can't load ADVENT HQ mission save

### ISSUE THREAD

**Issue by ionbomb** [long-war-2/lwotc#361]
Was playing an HQ mission (34  -36 enemies), and I cleared all but the last pod. I decided to stop for the night, and continue later.

However when I tried to load the mission the next day, the game hung.

I restarted my machine, verified game cache, redownloaded the LWotC mod files, and deleted my Config folder and had Steam rebuild it - none of this worked.

I should note that Vanilla WotC works fine, as does loading other saves from elsewhere in this LWotC campaign. But trying to load any saves from the HQ mission (I have 3 autosaves, and 1 manual save), all force the game to hang.

_My mods:_

- Evac All - WotC                       		
- [WOTC] Additional Icons               	
- [WotC] Mod Config Menu               	
- Free Camera Rotation                  	
- [WotC+Classic] TacticalUI KillCounter 	 	
- Yet Another F1                        	
- Long War 2 [WOTC] - alpha 5.1                     	
- X2WOTCCommunityHighlander                  	

_My machine specs:_

- intel i5-2500K
- nVidia 970
- 16GB RAM
- Samsung 500GB SSD
- Windows 7 Ultimate

_Save file:_ 
[save_Save 37_1.zip](https://github.com/long-war-2/lwotc/files/3418872/save_Save.37_1.zip)

_Log:_ 
[Launch-backup-2019.07.22-16.12.50.zip](https://github.com/long-war-2/lwotc/files/3418950/Launch-backup-2019.07.22-16.12.50.zip)

_Dump:_ 
https://www.dropbox.com/s/iqgbpu6m0oza4t8/XCom-DNR-PC-CL374751-2019.07.22-16.14.41_Minidump.zip?dl=0

**Comment by MiserablePileOfBugs** [comment]
Just had the exact same bug but on my second alien transmission relay mission. Just have to start it over, yeah...

By the way, this mission is easily the one I hate the most in this mod. And now you can cheese it effortlessly with the undetectable Reaper. I would rather do one more Liberation mission instead of this shit. In terms of tactical gameplay, it's really at the bottom.

**Comment by jmartinez989** [comment]
> 
> 
> Just had the exact same bug but on my second alien transmission relay mission. Just have to start it over, yeah...
> 
> By the way, this mission is easily the one I hate the most in this mod. And now you can cheese it effortlessly with the undetectable Reaper. I would rather do one more Liberation mission instead of this shit. In terms of tactical gameplay, it's really at the bottom.

well with the next few updates coming up, you won't have to worry about being able to cheese them with reapers anymore. I'll just say that much.

**Comment by ansabalirai** [comment]
> Just had the exact same bug but on my second alien transmission relay mission. Just have to start it over, yeah...
> 
> By the way, this mission is easily the one I hate the most in this mod. And now you can cheese it effortlessly with the undetectable Reaper. I would rather do one more Liberation mission instead of this shit. In terms of tactical gameplay, it's really at the bottom.

In the meantime, maybe try this: https://steamcommunity.com/workshop/filedetails/?id=1731970378.
Seems to be working fine for me for now

**Comment by ionbomb** [comment]
Just to add to my original report - I went back to a geoscape save, and replayed the mission. I did this in one go - so no loading a save mid-mission. 

Upon killing the last enemy on the map, the game crashed. Now if I try to load an autosave from this replayed mission, I get the same game hang I did before.

**Comment by pledbrook** [comment]
Collating these save issues in #600
