### ISSUE TITLE
Is officer training time tooo long?

### ISSUE THREAD

**Issue by cshen6** [long-war-2/lwotc#362]
I am training officers, and it is about 10 days per level, which takes them out for a long time....

This wasn't that bad in vanilla lw2; but with the bonding (which takes another 18 days) and potential covert actions (each takes 7-14 days, of course we can choose a non-officer to do them but sometime there is no other choice...), officers are now out of actions for much longer, which kind of ruins the point of an officer in mid games where missions are everywhere.

So I am wondering whether anyone is bothered by this, and whether the required officer training time needs to be balanced and tone down a bit due to WOTC's other new systems.

**Comment by MiserablePileOfBugs** [comment]
Xwynns suggested that the game should force you to have a larger roster of soldiers but with all the new mechanics brought by the extension, it's already the case. Between fatigue, covert actions, negative traits removing and bond upgrading, it occurred to me that I wasn't able to send out squads on missions as often as before. It took a while before I could assemble my third squad.

I think a global balance pass on down times wouldn't hurt. Some tasks could take longer (bonding) while others could be a bit faster (like soldiers recovering from fatigue).

**Comment by Grobobobo** [comment]
Not gonna be changed in this scope.
