### ISSUE TITLE
Rapid Deployment for Grenadier is not working

### ISSUE THREAD

**Issue by imn01** [long-war-2/lwotc#364]
Activating rapid deployment should remove action cost for next throwing/launching grenade. But it ends the turn for the grenadier. 

[save_Rapid Deploy Bug.zip](https://github.com/long-war-2/lwotc/files/3428961/save_Rapid.Deploy.Bug.zip)

**Comment by jmartinez989** [comment]
I need to ask for clarification. Are you trying to launch an offensive grenade when using rapid deployment or using a non damaging grenade? The skill states that launching a defensive grenade is free when activating rapid deployment.

**Comment by imn01** [comment]
Sorry I completely missed that. My apologies, I should have known better. Closing now.
