### ISSUE TITLE
Center Mass Text Glitch

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#365]
Probably need to fix the localization file.

![centermass](https://user-images.githubusercontent.com/44072125/61839339-6a8dc680-ae4a-11e9-94e0-b87731b1144c.jpg)

**Comment by MiserablePileOfBugs** [comment]
http://www.pavonisinteractive.com/phpBB3/viewtopic.php?f=15&t=26486&p=46787&hilit=center+mass#p46787

**Comment by pledbrook** [comment]
Fixed.
