### ISSUE TITLE
Bug and Graphical issues with squad deployment

### ISSUE THREAD

**Issue by Maebalzurakin** [long-war-2/lwotc#368]
Two graphical issues I have encountered related to deploying squads.

a) If a squad is selected with the squad selection menu, then a new random soldier is added in the deployment screen, then when the launch button is hit and the platform raises, the new soldier that was added will not raise with the other soldiers and will clip through the floor.
Edit: Apparently it is more than just a graphical issue.  The soldiers who sink through the platform will not be in the mission.

b) If a squad X is sent on a mission and is currently infiltrating, and the game gives you a 'hunt the spy' mission with the faceless vs. territory adviser + random resistance, then both the mission brief screen and the mission debrief screens for 'hunt the spy' will display the soldiers from squad X.

**Comment by Maebalzurakin** [comment]
Edit: Apparently it is more than just a graphical issue. The soldiers who sink through the platform will not be in the mission.

**Comment by tn67078** [comment]
I can confirm both issues. I have seen the issue with soldiers sinking through the platform three times now, always when I try to add a soldier who is not part of the selected squad. This bug seems to be random - it doesn't always occur again if I load a previous save and set up the same mission again.

**Comment by pledbrook** [comment]
I'm pretty sure this is related to either or both of #302 and #314. Have you tested against alpha 6?

**Comment by Grobobobo** [comment]
No response since those fixed issues, assuming closed.
