### ISSUE TITLE
Suggestion:  Make Black site mission come sooner.

### ISSUE THREAD

**Issue by Maebalzurakin** [long-war-2/lwotc#369]
Right now the game introduces the Black Site after you finish the 4th liberation mission for a territory.  In the video that plays, you are told that you should track down the Black Site and start up a resistance movement.  

At that point in the game I was already controlling 11 territories, so the context of the video is very misplaced.  The average player isn't going to know which missions lead them to the tower mission and even if they do, which I did, with the random nature of mission generation, it can take a few months to get to the first tower.

It would make a lot more sense have that video trigger tied to a something a lot earlier, perhaps after 1 month.

**Comment by jmartinez989** [comment]
The thing is that with lw2 it was meant for xcom to not even know anything about the blacksite until they have uncovered enough alien activity to know that the site even exists.

I get that it is kind of hard to uncover it as there is not a lot of information that lw2 gives in this regard (the explanation of the liberation chain in the commanders quarters is not very helpful) but once you understand how it works it actually flows well with the narrative of lw2.

There are ways to get mission generation to occur much faster like having a scientist as a haven adviser (which I do to get mission generation up as high as possible as they provide a 20% boost to intel generation). Also it helps to put all rebels in all regions on intel as that can help with detection times as well (apparently income from jobs accumulate on a global bucket and not a per region bucket).

**Comment by Maebalzurakin** [comment]
It does make sense and I do like the way that LW2 does it.  It is just the dialogue in the cutscene that doesn't fit, but I guess that is impossible to edit.  Half of the cutscene is telling you to set up a resistance movement and the second half is telling you to go after the black site.  Maybe a video editor could split it into two separate videos?

**Comment by Grobobobo** [comment]
Already done in the beta branch, and lwotcr.
