### ISSUE TITLE
Suggestion:  The game needs Advent Strength and Vigil explanations

### ISSUE THREAD

**Issue by Maebalzurakin** [long-war-2/lwotc#370]
I know what Strength and Vigil represent, but they are given no context.  Presumably 1 is the lowest, but what is high?  If Vigil is 5 is that still low?  What does it go up to?  When should I worry?  A player shouldn't have to play a game for hundred of hours to figure out in hindsight what S10 means.  How much does V rise if you take a mission is a territory?  How long does it take for V to fall by a point if you don't take a mission in a territory?  I assume Advent will move troops around so that S=V?  That should be explained in a tutorial.

 When should I put my resistance into hiding mode?  Why would I ever take a mission why the objective of raising vigil "get advents attention"?  How do strength and vigil effect mission difficulty and type?

S and V also need  visibility in the mission brief.  Currently is tells you which territory the mission is in, but then I have to back out, check the current S and V in on the map, then re-enter the mission to decide if I should take it or not.

**Comment by ansabalirai** [comment]
https://www.ufopaedia.org/index.php/ADVENT%27s_Agenda_(LW2)

**Comment by Maebalzurakin** [comment]
That you!  That is very helpful.  Some of that should be in the game archives in the commanders quarters.

S and V should be visible on the mission brief.

**Comment by pledbrook** [comment]
It needs a whole load of explanation! I'd like to add tutorial boxes to help ease players into the game.

**Comment by Grobobobo** [comment]
This should already be explained in the tutorial we added.
