### ISSUE TITLE
Suggestion:  Reduce frequency of Rendezvous missions

### ISSUE THREAD

**Issue by Maebalzurakin** [long-war-2/lwotc#371]
I am several months in, have 12 territories contacted, 1 liberated.  I am getting multiple 'Rendezvous' missions generated every day.  I can be 1 hour away from researching some cool new toy and have to fight 2-3 'Rendezvous' missions back to back before it is done.  It really is becoming tedious as they can not be skipped and they all play out the same way with no variety.

I increased  'MinRequiredAlertLevel' of all of the Rendezvous tiers by +5 in the 'XComSchedules.cfg'.  I am hoping this will stop all of my low level territories from constantly generating these missions.  I am not sure if +5 is too high or not because I don't really have any context of what 5 means.  Is there another place in the config where % chances for generation can be adjusted?

**Comment by jmartinez989** [comment]
actually rendezvous missions can 100% be skipped and with the added benefit that the faceless that were there are gone. The only downside to skipping a rendezvous is missing out on corpses.

**Comment by Maebalzurakin** [comment]
Interesting.  So detecting the faceless is enough to kill it.  That is cool.

I was just reading on a wiki: [https://www.ufopaedia.org/index.php/ADVENT%27s_Agenda_(LW2)#ADVENT.27s_Strategy]
that every time your haven recruits a new member, there is a % chance that they are secretly flagged as being a faceless, that they reduce the income of your haven.  This would also be the source of the 'unknown activity' income reduction at the end of every month. 

Is all of that true or just backstory to justify having the missions?

My new suggestion would be to alter the text of the  mission screen, so that the options are (intercept meeting) or (Eliminate Faceless) in place of (abort mission).

**Comment by rrnwang** [comment]
Wat?! I thought skipping rendezvous would leave you with 0 haven people....? Did they change this at some point...?

**Comment by jmartinez989** [comment]
> Wat?! I thought skipping rendezvous would leave you with 0 haven people....? Did they change this at some point...?

that was never the case for skipping rendezvous. That only happened when you skipped a retaliation. If you skip a retal then you lose all haven personnel and adviser.

**Comment by rrnwang** [comment]
Hmmm maybe it was the intel raid mission...?

**Comment by jmartinez989** [comment]
Going to close this as you can skip rendezvous missions.
