### ISSUE TITLE
Consider removing Rendezvous from the missions the Chosen can appear on

### ISSUE THREAD

**Issue by tn67078** [long-war-2/lwotc#374]
I don't think the Chosen should be allowed to spawn on Rendezvous missions unless these missions are rebalanced/reworked (the Chosen are balanced around having your A team and best equipment while the rebels are balanced around weaker enemies).

I'm in mid-April and just had my first Chosen encounter of the campaign. I got a Rendezvous in a region with four rebels, and my squad was a Squaddie Ranger and three rebels (two of them with SMGs, so a lack of firepower was always going to be a problem). The Chosen was the Hunter, who is usually the easiest one for me. I tried this mission several times, but I was unable to complete it successfully. I don't mind a challenge and I'm fine with the idea that some missions will be too difficult, but the Chosen make this mission type a complete lottery since the difficulty goes through the roof if they show up and there is nothing the player can do to prepare (you can't reliably predict when the Chosen show up, and the equipment of the rebels obviously can't be edited).

**Comment by jmartinez989** [comment]
well the thing is they are already excluded from showing up on rendezvous except for if the rendezvous you get is like 2 or 3 missions after you completed lib 3. For some reason After completing lib2 the chosen are guaranteed to show up on the next few missions no matter which ones they are.

This is a fix we are looking into at the moment but no eta on the fix yet really.

**Comment by jmartinez989** [comment]
I actually found out the exclusion list is not working at all and chosen can show up to any of these missions at any point. It's just that after lib2 they are pretty much guaranteed to show up to the first few missions.

**Comment by tn67078** [comment]
Thank you for the update. The Rendezvous was the first mission after lib2, so that explains why the Hunter showed up. He has appeared on every guerrilla op since then - I have done maybe 6-7 missions of various types since he was revealed, and the only times he did not appear were another Rendezvous and a Data Tap.

**Comment by rrnwang** [comment]
@jmartinez989  Wait, are you saying that Chosens can show up on any rendezvous missions after a Lib2?!

**Comment by jmartinez989** [comment]
> @jmartinez989 Wait, are you saying that Chosens can show up on any rendezvous missions after a Lib2?!

yes they can show up to any mission after lib2. The first few missions after lib2 they will be just about guaranteed to show up on. After say maybe 3 or 4 appearances a mission will have about 25% chance of them spawning.

There is supposed to be a mechanic stopping them from showing up but it does not work at the moment for some reason.

**Comment by pledbrook** [comment]
Are you sure they're guaranteed to show up like that? There's no special mechanism for that.

**Comment by jmartinez989** [comment]
> 
> 
> Are you sure they're guaranteed to show up like that? There's no special mechanism for that.

yeah I have been testing this for quite some time now. It seems that the first few missions after they activate they show up guaranteed. After that it does seem to follow the 25% cap but they are definitely showing up to missions they are not supposed to be on like rendezvous. That part I have not been able to test yet but I will see if I can in the current campaign.
