### ISSUE TITLE
Placing evac zone intermittently seems to crash the game

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#38]
I don't know whether this is dependent on which soldier does it, or whether it's from a previously saved game, or what. But this is game breaking.

**Comment by MatthewEHurd** [comment]
So far in my testing I have been able to reproduce this on two occasions. 

If the evac flare is thrown as the first action it is able to be correctly placed and acts as expected. If you try to place the evac flare after the first characters actions such as at turn end, the game client reliably crashes each time. 

I have two saved games where this can be reproduced. I will post both here shortly.

**Comment by pledbrook** [comment]
I managed to reproduce the first time, then ran it through the debugger. Haven't managed to reproduce since 😢  I may have to try reproducing with new missions each time. Unfortunately, I don't have an inkling what the trigger conditions are.

**Comment by pledbrook** [comment]
I think I may have a fix for this. It's hard to be sure considering the trouble I've had with reproducing the bug, but I'm 80% confident. We'll have to see once alpha 2 is out and people are testing it. (No config fix this time, unfortunately)

**Comment by pledbrook** [comment]
This should be reopened if the fix doesn't actually fix the problem.

**Comment by pledbrook** [comment]
This is clearly not fixed, unfortunately.

**Comment by ansabalirai** [comment]
So, I thought this was maybe dependent on a particular soldier throwing evac or if it is thrown in a particular turn. However, it is seemingly completely random and very hard to reproduce, but it is happening frequently enough to be an annoyance.

**Comment by aondiar** [comment]
Had this happen to me twice. Both time it was using a faction soldier (Reaper, Skirmisher) as the first action of the turn.

**Comment by jmartinez989** [comment]
So at this point this seems almost random. I have gotten this with just about any soldier type and didn't matter if it was the first or last action of the turn.

Only way I have been consistently able to avoid this is to save and then load before placing evac.

**Comment by The13Inquisitor** [comment]
So, any progress with this bug?

I've presently got a mission I've been stuck on for a while whenever I try and throw an evac flare.

It's a destroy a relay mission on an underground map, which I'd argue extractions on that map type ought to have a fixed evac zone anyway, a la Lost and Abandoned for thematic reasons.

I mean, it's not like you can very well go and expect an aerial extraction underground, unless Advent's knocked a hole in the roof for you.

**Comment by pledbrook** [comment]
Nope, sorry. I can't reproduce it myself and some new logging hasn't clarified why this is sometimes happening. If you have a save file that reproduces the problem, please attach it here and I'll try it.

**Comment by pledbrook** [comment]
Has anyone noticed whether this is happening for any soldiers other than specialists?

**Comment by The13Inquisitor** [comment]
Well, it's happened with the Rookies in this particular mission, although I've got to wonder whether the map type has anything to do with it.

Also, where exactly ought I look for the saves? I'm going through now and can't seem to find them.

**Comment by pledbrook** [comment]
My Documents\\My Games\\XCOM2 War of the Chosen\\XComGame\\SaveData

**Comment by The13Inquisitor** [comment]
Thanks. Now I'm getting an unsupported file type message though.

**Comment by pledbrook** [comment]
When you're trying to attach it to this issue? If so, that's because you need to zip the save file before uploading it.

**Comment by The13Inquisitor** [comment]
Ah. Okay. That should do it then.
[save_AUTOSAVE- Campaign 61, Mission 2_1.zip](https://github.com/long-war-2/lwotc/files/3219442/save_AUTOSAVE-.Campaign.61.Mission.2_1.zip)
