### ISSUE TITLE
Training centre and resistence ring still cost monthly upkeep,is this intended?

### ISSUE THREAD

**Issue by Sinkingeye** [long-war-2/lwotc#380]
In both LWotC and original LW 2,vanilla facilities are free to maintain.However in LWotC,only new added facilites(training centre and resistence ring)require monthly upkeep.Perhaps we either rebalance the cost or completely remove it?

**Comment by jmartinez989** [comment]
As far as I know all facilities in both lwotc and lw2 still add an upkeep, it's just that if the upkeep gives you a negative monthly income then it would not be subtracted from your current supply stores at the end of the month. In my current lwotc campaign I only have vanilla facilities built and I definitely have an upkeep.

**Comment by ionbomb** [comment]
Per LW2 patch 1.3:

_- Removed all upkeep costs from facilities to work around negative supply bug. Raised initial price of some facilities and upgrades._

https://www.ufopaedia.org/index.php/Change_Log_(LW2)#Patch_1.3_.28Released_May_15.2C_2017.29

**Comment by Sinkingeye** [comment]
> 
> 
> As far as I know all facilities in both lwotc and lw2 still add an upkeep, it's just that if the upkeep gives you a negative monthly income then it would not be subtracted from your current supply stores at the end of the month. In my current lwotc campaign I only have vanilla facilities built and I definitely have an upkeep.

![income](https://user-images.githubusercontent.com/53558693/62410215-636a7380-b615-11e9-8eeb-874c81b474aa.jpg)
![avenger report](https://user-images.githubusercontent.com/53558693/62410216-64030a00-b615-11e9-9551-4b3f2f82e835.jpg)
here is my screenshot(alpha 5.1):
As you can see,WotC facilaties require upkeep,and others are free.
And by calculating total income,you will notice that some income is token(fogive my poor English)

**Comment by jmartinez989** [comment]
so I have a fix for this. I will push the fix pushed up to the repo as soon as I can.
