### ISSUE TITLE
Avenger reserve reinforcements do not have action points

### ISSUE THREAD

**Issue by Spirit117** [long-war-2/lwotc#382]
All of the soldiers that have been dropped in for my avenger reserve defense come in without recieving any action points (and they do not get any more next turn either, so they are useless.)
Avenger reserve is also dropping in soldiers that are wounded and not equipped for battle, when I have other soldiers that are full health that could be used instead. What gives here?

**Comment by pledbrook** [comment]
I encountered this as well and made a save for it:

[save_BUG Soldiers arrive no AP on Av- Def-.zip](https://github.com/long-war-2/lwotc/files/3485222/save_BUG.Soldiers.arrive.no.AP.on.Av-.Def-.zip)

Not sure if there's anything we can do about which soldiers are chosen from the reserve on the Avenger. That's probably vanilla logic.
