### ISSUE TITLE
Squad selection issue - removed soldier appears on the mission

### ISSUE THREAD

**Issue by tn67078** [long-war-2/lwotc#383]
I'm having issues with the squad selection and load-out screen. I've had a number of instances where a soldier who was removed in the load-out screen is still on the mission. E.g. if I select a squad that has six soldiers available and I remove one soldier, the removed soldier is still in the infiltrating squad and appears on the mission. I thought at first that I was doing something wrong because I haven't used the squad select mod before, but I can now confirm that this is a bug (possibly related to some of the other squad selection issues that have been reported by other players).

**Comment by Spirit117** [comment]
Getting this as well. Currently the best way I've been dealing with this is to add only the soldiers you want on the mission to a fire team, and then select the fire team for the mission.

**Comment by ToastedAmphibian** [comment]
Oh good! Thought it was only me. Have also had entire squads not show up on the mission at all. A squad of zero soldiers does infiltrate very quickly... Mixing solders from different squads seems to correlate with this problem for me, and is often preceded by a graphical glitch: the rising floor of the squad select screen moves up, and clips through the legs of the soldiers whos elevation does not change.

**Comment by tn67078** [comment]
I have the clipping floor / missing soldiers problem as well - at least as far as I can see, this bug only affects soldiers that belong to a different squad. I've been using the workaround suggested by Spirit117 to avoid having to use soldiers from different squads.

**Comment by pledbrook** [comment]
Could someone please provide a save file that demonstrates the problem?

**Comment by ToastedAmphibian** [comment]
Here is one I saved after noticing zero infiltrators on a mission:

[save_No Infiltrators.zip](https://github.com/long-war-2/lwotc/files/3485836/save_No.Infiltrators.zip)

**Comment by pledbrook** [comment]
I'm pretty sure this is fixed. See #302 and #314. Are people using alpha 6?

**Comment by ToastedAmphibian** [comment]
Nope. Release page says alpha 6 was posted on 8/9/19, this thread is from 8/4/19.

But now that I know alpha 6 is out, i'll grab it and let you know if the problem persists.

**Comment by j-thiessen** [comment]
Any updates on this issue? This happens to me rather often (removed soldiers appear on mission)

**Comment by pledbrook** [comment]
I have not seen this, so assuming fixed. Can be reopened or another issue created if there's still a bug somewhere.
