### ISSUE TITLE
Skull Mining Game Freeze

### ISSUE THREAD

**Issue by Maebalzurakin** [long-war-2/lwotc#387]
I have been experiencing an issue where the screen will freeze when I attempt to skull mine an advent soldier with my reaper.  Has anyone else seen this?  The only time I have seen this before was when I tried to have a spark throw a grenade.  I don't think the animation file exists for that, so it locked up.

**Comment by Maebalzurakin** [comment]
Update:  It isn't happening 100%.  Sometime it will work.

More detail on what I am seeing:  I select a target for Skull Mining, and hit the button.  The screen will freeze.  The music is still playing and I can move the cursor around.  When I alt-tab, I can see other windows open, but when I try to go to them nothing happens and it stays on the frozen game screen.  When I ctrl-alt-del, I can get the screen with restart or task manager options.  However, when I try to open task manager it just goes back to the frozen game screen.  Selecting restart will work.

**Comment by pledbrook** [comment]
This is likely the same problem as #350.

**Comment by pledbrook** [comment]
If you have a save file, I'd appreciate it. Or test against alpha 6 to see if it's fixed.

**Comment by Grobobobo** [comment]
no response since then, assuming closed.
