### ISSUE TITLE
Suggestion:  Covert action to find facility

### ISSUE THREAD

**Issue by Maebalzurakin** [long-war-2/lwotc#389]
I am pretty far in my playtesting of beta 5.  Power armor, plasma weapons.   I just completed the gate mission.

I have never seen a 'facility lead'.  They should be a lot more common.  I feel like I should have attacked 2 or 3 of them by now.

There is currently a covert action to reduce the avatar project.  I think this should be removed and replaced with 'search for facility'.  Success would mark an alien facility on the map.  You would have to successfully destroy the facility to get that reduction in the avatar project.

It just seems a bit odd that I can send out a team to 'search for Chosen base', but I can't do the same thing for a facility.  A Chosen base would be much more hidden.

**Comment by Grobobobo** [comment]
facility lead covert action is already implemented.
