### ISSUE TITLE
Add a short campaign

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#39]
Allow players to undertake a shorter campaign than the normal one. There are a couple of ways we could approach this:

 * Reduce the number of missions per month (this is effectively how Long War 1's Dynamic War option works)
 * Double the speed of everything

The former could perhaps be implemented in the alien activity manager and is probably the easier option to implement.

The second would involve doubling the rate of: 

 * Scanning
 * Force level increases
 * XP gain on soldiers
 * Wound recovery (?)
 * Research
 * Doom accumulation, and so on

In both cases, resource rewards would have to be doubled (or you halve resource requirements). VIP and soldier rewards could probably stay the same.

**Comment by micahswab** [comment]
It'd be nice if milestones like research and force level still occur around the same calendar date in a shorter version of the campaign. This would prevent confusion in strategy planning and discussion. I envision the game would play strategically identical but with less tactical time.

Option 1, reducing the number of missions, would preserve the existing milestones on the calendar. In addition to mission rewards, things like infiltration time, wound time, experience gain, and POI rewards should increase proportionately to the mission reduction.

**Comment by ansabalirai** [comment]
I am not sure how reducing the missions per month works with how mission generation happens in LW2, i.e. dependent on contacted regions as well as strength/vigilance requirements. Imposing a hard limit on how many missions are generated seems like a artificial restriction, given that it is up to the player to attempt as many as they can anyway. Perhaps a more cautious approach can be to look at vigilance decay if no missions are attempted by the player. Alternatively, some way of basically speeding up overall in game time can be done such that mission generation, infiltration, research speeds, wound recovery etc. are all scaled correspondingly (no idea if this is even possible)

**Comment by BlackRose39** [comment]
We could integrate quicker start:
https://steamcommunity.com/sharedfiles/filedetails/?id=756948560

**Comment by BlackRose39** [comment]
Legend was able to double the research time. Perhaps take a look at relevant coding and see if it can be applied via second wave options, etc.?

**Comment by Grobobobo** [comment]
Out of scope of this project.
