### ISSUE TITLE
Screen locked when defeating chosen warlock temporarily the first time 

### ISSUE THREAD

**Issue by Sinkingeye** [long-war-2/lwotc#391]
when I defeat chosen warlock the first time(during mission,not base assult) and mission complete,the screen seem to freeze on the chosen icon in geoscope.I can see the in-game clock ticking,but nothing can be interacted--I can't use mouse and keyboard.
![655add188618367a6d42050e20738bd4b21ce523](https://user-images.githubusercontent.com/53558693/62450566-25995680-b79f-11e9-955b-44ff494867ab.jpg)

Not solved when save & load.

**Comment by BlackRose39** [comment]
Could have something to do with missing narratives. I remember there was an issue when the psi gate mission appeared, the same thing occurs as well.

https://steamcommunity.com/sharedfiles/filedetails/?id=1334298434

![softlock](https://user-images.githubusercontent.com/44072125/62503252-9dbc4800-b7b0-11e9-882c-368a425aa181.PNG)

Hope this helps the coders in pinpointing the issue.

**Comment by Grobobobo** [comment]
That's caused by enabling lost and abandoned.
