### ISSUE TITLE
Promotion screen doesn't show MSGT ranks 

### ISSUE THREAD

**Issue by Spirit117** [long-war-2/lwotc#393]
I just got my first soldier up to Master Sergeant rank, however the abilities only go to Gunnery Sgt (on all soldiers, not this one, I just didn't realize it till now). So I'm not able to see or give him a MSGT perk, but the barracks has the little promotion icon for the soldier on it still. Is there something I'm missing here? I've also realized that for the Skirmisher, all of the top end abilities like battle lord are at GSgt rank, does this mean there are no master Sgt perks and I just need to use the abilities to pick another ability? And just ignore the promotion icon in barracks?

**Comment by BlackRose39** [comment]
Right, so lw2 classes have 7 ranks, but the hero classes only have 6 ranks, so they don't have that title/rank at this time. I'm guessing that there will be a rebalance so that the hero classes will have another row of abilities, so there's a total of 7 ranks, allowing them to attain that rank.

Or, we could consider giving the hero classes their own ranking titles (similar to psi operatives).

**Comment by Spirit117** [comment]
Is it normal that a MSGT Sniper or any other non hero class doesn't have perks at that level tho? I chose "light em up" for my sniper with the extra ability points which definitely seems like a top rank perk, but it's still telling me there's a promotion available.

**Comment by BlackRose39** [comment]
Apologies, I'm a little confused, can you take a screenshot and share it here? 

All lw2 classes should have the master gunnery rank attainable, and I don't recall a sharpshooter being able to obtain that ability at max rank (Don't think it's GTS/AWC either). They should have double tap, alpha mike and serial.

**Comment by Spirit117** [comment]
Yes, heres some. In case the files links dont work check the link to my steam page, 2 screenshots are posted most recent. As you can see, my snipers top perks category are labeled under GSgt, which i unlocked when he reached GSgt. Reaching MSgt hasnt unlocked any new perks, although it gave me enough AP to pick up Light Em Up. You may also notice that the icon is there for "promote soldier" indicating i have unused abilities. I have a shinobi that just got to MSgt and its the same story there, just wondering if thats working as intended or a bug on my end. 


![image](https://user-images.githubusercontent.com/53424774/62505682-e24ce100-b7ba-11e9-848f-c878906d1205.png)

![image](https://user-images.githubusercontent.com/53424774/62505666-da8d3c80-b7ba-11e9-8ddb-55e110232175.png)
https://steamcommunity.com/profiles/76561198071965224/screenshots/

**Comment by ToastedAmphibian** [comment]
"Is there something I'm missing here?" Aside from the last row of buttons, you mean? I don't think so. On mine, the abilities window extends further to the right. Yours stops at the left side of the berserker head, mine extends all the way to the right side of it, behind my sharpshooter's elbow.

Now that you mention it, I have a screenshot from previously showing the same problem. From the last build. You may be using an out of date version.
![short box](https://user-images.githubusercontent.com/52621448/62605483-3396c680-b8c8-11e9-9185-dec6a1d9da7b.jpg)

**Comment by Spirit117** [comment]
Ok so you are confirming there is supposed to be another row of perks right for master Sgt?

**Comment by ToastedAmphibian** [comment]
Yes.

**Comment by Spirit117** [comment]
Interesting. Any ideas how to fix? I just downloaded this like a week ago, alpha 5.1 if I'm not mistaken.

**Comment by jmartinez989** [comment]
@Spirit117 make sure you do not have the New Promotion Screen By Default mod installed as that mod is integrated with lwotc. If you do it could be causing this issue.

**Comment by pledbrook** [comment]
I'm going to close this because it seems to be an environment issue. You can continue to comment on it if you want more help, or head to [Discord](https://discord.gg/squpHaD).
