### ISSUE TITLE
Bug: Negative Trait Switching to Positive Trait text error

### ISSUE THREAD

**Issue by Maebalzurakin** [long-war-2/lwotc#394]
When a negative trait is getting converted to a positive trait the notification it titled "Negative Trait Acquired"

**Comment by BlackRose39** [comment]
I can confirm that this happens. Will upload a screenshot when I get the chance.

**Comment by rrnwang** [comment]
Wait, What?! A negative trait can become a positive one?!

**Comment by Maebalzurakin** [comment]
Yes.  They all can.  Don't cure them.  Send the soldier out on a few missions.  It will eventually flip.  If you cure them in the med bay, you lose the opportunity.

Fear of the Chosen ----> Chosen Hunter

**Comment by pledbrook** [comment]
Does this work properly in vanilla?

**Comment by ToastedAmphibian** [comment]
You sure that's not from a mod or something? The only information on positive traits I can find is a patch note from 2017 saying positive traits where removed, and a "More Trait's" mod. 

If this is actually a thing, where can I find more info on it?

**Comment by rrnwang** [comment]
I'm also 99% sure that's from a mod.

**Comment by Dragon-32** [comment]
_Does this work properly in vanilla?_

I don't think so.

Copying and pasting some discussion from [More Traits](https://steamcommunity.com/sharedfiles/filedetails/?id=1122837889)

**RealityMachina  [author] 15 Nov, 2018 @ 12:19am** 
the positive trait UI isn't actually used at all by the game (if it exists on the flash end), I'll probably get around to seeing if the highlander can fix that once I get done with this semester next month
 
**Dragon32 14 Nov, 2018 @ 7:06pm** 
@Fluff Bunny:
Hrm. In XComGame.int - 
[UIAlert]
m_strNegativeTraitAcquiredTitle=NEGATIVE TRAIT ACQUIRED
m_strPositiveTraitAcquiredTitle=POSITIVE TRAIT ACQUIRED

I guess the way this mod works is hijacking the existing negative trait assignment. Vanilla positive traits are only acquired by, IIRC, successful missions for a soldier with negative traits
 
**Fluff Bunny 14 Nov, 2018 @ 4:58pm** 
Re:. "The only nit-picky thing I have is that "NEGATIVE TRAIT ACQUIRED" pops up even when the trait's positive. Other than that, this is a really cool mod."

I noticed that with my first one to get a trait. It was for a bonus to attack Chosen. I was wondering if I was reading the description of trait wrong somehow.

Surely somewhere in localization files there is a place to Change "Negative Trait Acquired" to "Trait Acquired".

Other than that... I'm very excited to use this mod.

**Comment by Grobobobo** [comment]
That's the bug of the positive traits mod, not this one.
