### ISSUE TITLE
Suggestion:  A more interesting resistance

### ISSUE THREAD

**Issue by Maebalzurakin** [long-war-2/lwotc#395]
I know getting the LW2 up and running like it used to be is the primary goal, but I have an idea that I personally think would make the strategy layer a lot more fun.

Currently we are limited to 1 upgrade of a radio tower.  What if there were additional upgrades?  I was thinking that by investing, you build it up into an outpost.  It becomes a resource sink and also attracts more attention, but comes with benefits and also allow for the creation of more interesting missions.  

**Barracks 1-3:**  Initially you can't station anyone in the territory, but each level of barracks lets you station an additional soldier.  You can make the faceless missions harder and more interesting to compensate. 
**lab 1-2 :** Each level lets you station an scientist with a 10% intel boost.
**Engineering 1-2 :** Each level lets you station an engineer with a 10% resourse boost.
**Robotics Lab:** Requires Engineering 2 and allows defensive mechs to be built (~half the cost of sparks).  mechs can also be transferred between any two outposts that have robotics labs.
**Fortifications:**  Starting locations have some good high cover buildings for missions where you get attacked.
**Defenses 1-2:** Requires Fortifications and each level puts down a turret.
**Radio tower:** Original upgrade that requires a level 1 lab.

In the end the player ends up with a few more benefits (the effects of the combined soldier, scientist and engineer) but at the cost of ~5000+ credits.  There is more functionality with mech management instead of it being random chance where they get assigned.  Rendezvous and defense missions are more engaging and dynamic.

I wish I could write the code myself to help out, but I lack that skill.

**Comment by Anxoczt** [comment]
I am not sure how exactly do the LWOTC devs want their version of LW2 differ from vanilla aside from inclusion of WOTC features (If they ofc stop removing them like they did with multiple abilities per rank and i am expecting further stripping of WOTC features like stat rewards from cover ops cuz "balance" and "People would have too much fun" (Ofc they will sugarcoat it when it will eventually happens).

While i would be all in for LWOTC to be a much deeper take, with being developed further than the base version. i dont think its the intention of the dev team.

**Comment by Maebalzurakin** [comment]
Yeah its just very wishful thinking.  I don't expect it to happen because it is 'not the Long War experience'.   However, once it is officially released, I expect a lot of 'modding the mod' to occur.

**Comment by pledbrook** [comment]
This is an interesting idea, but starts moving the stategy layer away from a mechanism for delivering tactical missions to making the strategy layer more of a game in its own right. That's not necessarily a bad thing, so worth considering.

**Comment by cshen6** [comment]
very cool idea -- anything enhances the strategy level is great!
This idea may even worth a submod I think.

Maybe also add some upgrade options that can 
1: prevent chosen sabotage reducing income in that region;
2: prevent faceless being recruited in that region.
I think they are two "biggest" small issues on the mid-game strategy level. 

These two are challenging at early to mid game, but just starts to be boring and just micro-management in mid to late game; it is especially annoying for faceless to still be recruited in liberated region..

**Comment by tunbridgep** [comment]
Might be good as a Second Wave option :P

**Comment by Grobobobo** [comment]
Not interested in something like this.
