### ISSUE TITLE
Promotion issue: Bottom row of abilities cost AP on level up

### ISSUE THREAD

**Issue by SydenInsomniac** [long-war-2/lwotc#397]
I ran into this issue when I upgraded to 1.6 and assumed it was a mod compatibility issue.  So I reinstalled the game along with clean install of LongWarOfTheChosen and X2WOTCCommunityHighlander.

Disabled all mods and still have the issue.  Restarted game with no mods:  Once you get to the first level/rank up your third row of abilities isn't "free".  It costs AP instead of the choice of the three abilities you get at rank. Only the top two abilities are "0 AP".  Also on rank up I can see the Xcom abilities that normally require a training center to view and purchase.

I am able to buy those extra abilities at rank up with AP without a training center.

See screen shots for examples.  Included 2 save files one with mods and one on the clean install.
[saves and screenshots.zip](https://github.com/long-war-2/lwotc/files/3488160/saves.and.screenshots.zip)

**Comment by jmartinez989** [comment]
this is indeed weird but this may be a config issue. Please delete the config folder in the "my documents\my games\wtoc" (or something like that) folder. After that try a new campaign and see if that works.

**Comment by pledbrook** [comment]
That second save is working for me. Look for an _XComPromotionUIMod.ini_ file in your user config directory and also in the integrated mod. Make sure that they contain the following lines:
```

+ClassAbilitiesPerRank = (ClassName=LWS_Technical, AbilitiesPerRank=3)
+ClassAbilitiesPerRank = (ClassName=LWS_Specialist, AbilitiesPerRank=3)
+ClassAbilitiesPerRank = (ClassName=LWS_Grenadier, AbilitiesPerRank=3)
+ClassAbilitiesPerRank = (ClassName=LWS_Gunner, AbilitiesPerRank=3)
+ClassAbilitiesPerRank = (ClassName=LWS_Ranger, AbilitiesPerRank=3)
+ClassAbilitiesPerRank = (ClassName=LWS_Sharpshooter, AbilitiesPerRank=3)
+ClassAbilitiesPerRank = (ClassName=LWS_Shinobi, AbilitiesPerRank=3)
+ClassAbilitiesPerRank = (ClassName=LWS_Assault, AbilitiesPerRank=3)
```

Also make sure you don't have a separate New Promotion Screen By Default mod installed.

**Comment by SydenInsomniac** [comment]
Thanks to both of you that fixed the issue.
