### ISSUE TITLE
"Wanted" soldiers not displaying on city map prop

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#398]
![wanted not showing](https://user-images.githubusercontent.com/44072125/62815237-37973400-bad4-11e9-97c8-48b2ccd20fde.PNG)

For those unfamilar with what I'm talking about:
https://steamcommunity.com/app/268500/discussions/0/412448158148830430/
https://www.reddit.com/r/Xcom/comments/45puc4/ever_notice_how_the_faces_of_your_veteran_guys/

**Comment by Dragon-32** [comment]
This isn't specific to LWotC, those Wanted posters haven't been displaying since WotC.

**Comment by BlackRose39** [comment]
I thought so, was wondering because I remember not seeing the poster since last year.
Hmm...

**Comment by BlackRose39** [comment]
Oh, why not then I wonder. Let's add it back in! It's awkward to be hearing the voice telling citizens to "watch" for your wanted soldiers without any visualization there, just ruins immersion.

**Comment by Grobobobo** [comment]
Not a lwotc issue.
