### ISSUE TITLE
Suggestion: Primary Weapon Adjustments?

### ISSUE THREAD

**Issue by CSAndrew** [long-war-2/lwotc#399]
# Overview

I'd like to start this out by saying that I'm actively running over 450+ WOTC mods (because why not), in conjunction with LWOTC Alpha 6, and it's working pretty well. There are icons missing here & there, but that's probably largely attributed to the fundamental differences.

The only mod I haven't seen work is the WOTC Akimbo class. Personally, it's just something I (and I assume some others) find interesting. The soldier can actually equip the pistol, even the modded pistol(s), in the primary weapon slot, it just limits the secondary slot from having one then, stating, essentially, that only one can be equipped.

## Question

Is the dual pistol, or alternative weapon, setup something that would have to be done in beta, a feature that would have to be added, or is it just up to the mod developer to possibly offer a LWOTC version in the future?

On a side note, is this a concept that you would consider adding into LWOTC, or does it stray too much from the core vision of the mod?

### Comments

I've tried to read up on this project as much as I could; I definitely want to say good job on everything thus far. This is a huge accomplishment, as well as integration of some of the QOL mods thus far.

Also, for those wondering, RPGO seems to work fairly well in LWOTC thus far (for me). Commander's choice is still working well as well. The only issue with the former is that some abilities seem to be missing here & there, but that's not a giant ordeal.

**Comment by pledbrook** [comment]
These kinds of balance changes will be considered for the rebalancing work that will come after the first release. In fact, one avenue we are pursuing is allowing sharpshooters to equip pistols as primary weapons. I doubt we will do much more extensive work than that though. It will be up to mod authors to produce LWOTC-compatible versions in many cases.

I'm surprised RPGO is working well as we both have conflicting versions of the New Promotion Screen By Default mod integrated! That's part of the reason we're planning to work on an updated NPSBD that works with both LWOTC and RPGO.

**Comment by Grobobobo** [comment]
Beyond the scope.
