### ISSUE TITLE
ADVENT reinforcements indicator does not show "INCOMING" status. (Alpha 6)

### ISSUE THREAD

**Issue by TyborPL** [long-war-2/lwotc#401]
Just started a new campaign with alpha 6 and encountered this issue (title). Advent reinforcements status jumps to the next one instead of INCOMING while ADVENT troops are inbound.

**Comment by pledbrook** [comment]
Do you have a save file that reproduces this?

**Comment by cshen6** [comment]
Can confirm this minor issue.

I kept on playing my alpha 5 progress. The reinforcement indicator starts with green, then yellow, then green again -- and enemy arrives after the second green indicator -- after which the indicator goes to green & repeat the g-y-g cycle. 

Previously it is green, yellow, and red, and enemy arrives after the red incoming status.

**Comment by rrnwang** [comment]
> Can confirm this minor issue.
> 
> I kept on playing my alpha 5 progress. The reinforcement indicator starts with green, then yellow, then green again -- and enemy arrives after the second green indicator -- after which the indicator is still green & repeat the g-y-g cycle.
> 
> Previously the indicator is green -> yellow -> red, and enemy arrives after the red incoming status.

I have had this issue as well. It was on my blacksite mission, so it was extra concerning.

**Comment by TyborPL** [comment]
> Do you have a save file that reproduces this?

Sorry but no. Played Ironman so I lost it. Next time I'll try to alt+tab and secure a save file.

**Comment by TyborPL** [comment]
Finally got a save file. And a little update to my previous report: After loading this save I've seen correct ("INCOMING") status for a few moments but when all textures loaded and game unfreezed, status has changed to incorrect one. 
[save_IRONMAN- Campaign 57.zip](https://github.com/long-war-2/lwotc/files/3498631/save_IRONMAN-.Campaign.57.zip)
