### ISSUE TITLE
Chosen strength "beastmaster" error

### ISSUE THREAD

**Issue by Sinkingeye** [long-war-2/lwotc#402]
![20190811232535_1](https://user-images.githubusercontent.com/53558693/62836951-cc985980-bc9b-11e9-8c65-e0802c81737c.jpg)
"immune to damage from berserkers"?!
In the original WotC,the "beastmaster" strength is "The Chosen may summon savage enemies(Melee units, such as Chryssalids, Berserkers, and Faceless). "
I guess it may has something to do with LW2's muton elite,because it has a perk also called "beastmaster" which is "immune to damage from berserkers".

**Comment by BlackRose39** [comment]
Indeed, just like how the reaper's unused (?) executioner perk conflicted with the Shinobi's perk tree, it's no surprise there will be other issues like this.

Nice find!
