### ISSUE TITLE
Review Chosen activities

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#403]
Some Chosen activities may not make sense or may be ineffective. For example, Retribution ("a brutal crackdown on the resistance") probably has no to little effect because income is handled differently by LWOTC.

**Comment by jmartinez989** [comment]
well it does actually affect how much income you will bring in. It can make your monthly income go into negative if you do not have any rebels on supply and if you do have any on supply it reduces the amount that they gather.

**Comment by Anxoczt** [comment]
By the time you activate the Chosen, your income shouldn't be that low for them to go in to negative so  as pledbrook said, this is a waste of their time, as the damage they do is almost non existing.

**Comment by jmartinez989** [comment]
well I was just pointing out that it does affect how much income a region brings and that it can actually put you in the negative (most of the time you are going to need to have most regions on intel so there could be some months where your income will be negative but I do believe the lw2 code handles that).

But yes I think something else other than lowering income would be more interesting. Maybe make it so that they spike vigilance or make it harder for havens to recruit more people via the recruit job.

**Comment by PodliKirill** [comment]
Vigilance spike - it's not a penalty, but buff IMHO. Big vigilance slowdown the Avatar project. You have only one negative thing from the big vigilance - big reinforcements event. But slowing Avatar is much more profitable.
For now, i use supply gathering only in the liberated region. Even in the region with very big Advent strength you're very likely to get Troop Ambush mission with good timer.
Good event is a penalty for **any** rebel job. ~20% penalty seems reasonable i think.

**Comment by pledbrook** [comment]
Chosen activities are set up in `X2StrategyElement_XpackChosenActions`. There aren't many, so it may not make sense to disable Retribution, although Sabotage and Dark Event actions have several options each.

**Comment by pledbrook** [comment]
I think for now it makes sense to remove the Increase Income reward from covert ops and disable Retribution. They don't currently fit the mechanics of income in LWOTC. We can consider alternative implementations for both at a later date.

**Comment by pledbrook** [comment]
Actually, since @jmartinez989 says that the event affects rebels on supply job, Retribution works fine in LWOTC. We can review the Chosen Actions again at a later date to make things more interesting/challenging.

**Comment by wdanny69** [comment]
chosen has gone through reworks and activities adjusted
