### ISSUE TITLE
Yellow alerted PODS almost never move?

### ISSUE THREAD

**Issue by cshen6** [long-war-2/lwotc#408]
This is again something I am not sure is a bug or intended:

In original LW2, inactive pods will become yellow alerted by sound, and usually rush to the battle / sound location.

Now in Lwotc so far, I notice that most pods, once alerted, simply stay where they are (I use reaper & target definition to see their movement), until they see XCOM soldiers. They do move before being alerted, but almost always stay where they are once being alerted.

Personally, I think that is actually a good thing for them to do most of the time--- especially with reaper's target definition, it is quite easy to get a good position & overwatch shot any incoming pods; now they mostly stay where they are, which poses more challenge in my opinion.

Again, I am asking this because it is just too rare for alerted pods to move at all, which is quite distinct from original LW2 experience. So I am not sure if it is intended, or bug, or just what happens on higher difficulty level?

**Comment by RedDoby** [comment]
I would say that this is most likely not intended.  Long war has a pod management system that is quite complicated, and my guess is that LWOTC still needs work in this area.  The pod management system gets pods moving,  and not always towards Xcom.  Sometimes they flank, defend the object, etc.

**Comment by pledbrook** [comment]
I've just encountered this and have a save. Will investigate.

**Comment by PodliKirill** [comment]
There is another issue with pod mecanics.
Pretty rare situation - pod finishes their move - and **one** alien steps in the range of XCOM. He is killed instantly by overwatch.
Result - pod is activated at alien turn, but aliens not hide in cower - and you can just kill entire pod in open space. Probably caused because pod didn't see anyone after overwatch kill.

**Comment by RedDoby** [comment]
Pledbrook, LW2 has a fix for this in the function Skipturn in XGAIBehavior.

**Comment by pledbrook** [comment]
I'm not sure that's the case. It doesn't say that it breaks the scamper itself, just the reflex moves they might have _after_ the scamper. Although the comment is somewhat ambiguous. Have you tested it?

**Comment by RedDoby** [comment]
I have used it yellow alert gameplay for a while now, and have not noticed the bug personally.  Never tested it though so I am not 100% sure.
