### ISSUE TITLE
Game crash when press "Evac all"

### ISSUE THREAD

**Issue by Sinkingeye** [long-war-2/lwotc#411]
It happened several times in different missions,when I move 2 or more soldiers to evac zone and press Evac All,the game crashes.
But when I restart the game and Evac All again,no crash happened.
Here's the save file
[Evac all-Crash.zip](https://github.com/long-war-2/lwotc/files/3505641/Evac.all-Crash.zip)

**Comment by pledbrook** [comment]
I've been using Evac All without any issue for quite a while now. I suspect there's a problem with another mod. How many other mods are you using?

**Comment by Sinkingeye** [comment]
> I've been using Evac All without any issue for quite a while now. I suspect there's a problem with another mod. How many other mods are you using?

![可用Mod](https://user-images.githubusercontent.com/53558693/63205420-98c39680-c0d6-11e9-96b8-a0e0e18c3703.png)
These are all the mods I'm currently using.

**Comment by pledbrook** [comment]
I can't reproduce it, sorry.

**Comment by Sinkingeye** [comment]
Thanks,I will try it later.

**Comment by wdanny69** [comment]
have not heard new reports of evac all crashing, 

reopen this if there are still issues
