### ISSUE TITLE
Bug?  Overwatch kill on enemy VIP

### ISSUE THREAD

**Issue by Maebalzurakin** [long-war-2/lwotc#419]
I am now in a new campaign with beta 6.

Twice now I have killed an enemy VIP due to overwatch shots.  I don't remember this ever happening before.  I don't remember them ever trying to run before.  Or maybe my soldiers just ignored them as targets.  I think they never moved before, but now then try to run.

I would prefer to subdue them, so this outcome is not desired.  Has something changed or was I just really lucky in years of gameplay to have never seen this before?

**Comment by pledbrook** [comment]
Do you move close to them before they run? Save file that reproduces the problem would help.

**Comment by Maebalzurakin** [comment]
I was not close.  It seems their movement (for citizens) usually triggers within ~3 tiles.  I was about 10 tiles away, but within visual range.  The next time I have one of these missions I will try to reproduce and get you a save file.

**Comment by pledbrook** [comment]
The reason I asked is because I changed the way civilians become panicked. It now happens when an XCOM soldier moves within 7 tiles of the enemy. However, I think the VIP is supposed to be panicked but not move, so it's probably something else wrong.

**Comment by BlackRose39** [comment]
It does happen. I remembered moving in a concealed unit right next to the vip to subdue them, then they unexpectedly scamper upon reveal. They were not panicked until I moved a hidden unit right to them.

See if the problem can be reproduced this way. Not sure if maybe an associated pod protecting it has something to do with it, check if they scamper if by themselves.

**Comment by lpgagnon** [comment]
Still happens in build 23.1

Concealed squad on overwatch gets revealed on AI turn. VIP runs and gets shot by my squad. VIP is first to move, before even the pod that triggered the reveal, so the VIP draws _all_ the fire and doesn't stand a chance.

Minimal distance to trigger the scamper is 8 tiles (soldier, 8 blank tiles, VIP), so "within 7 tiles" isn't it.
Getting close _after_ the reveal (VIP already crouching) doesn't trigger the scamper.

I can provide a save if that's useful; I don't know how usable saves are without exact mod matching

**Comment by wdanny69** [comment]
worked around by granting them shadowstep 

https://github.com/long-war-2/lwotc/commit/3cd842caf07012daa72def7910aeb10234bd988e
