### ISSUE TITLE
Integrate Show Infiltration Percentage mod

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#421]

**Comment by ansabalirai** [comment]
Here is a link to a local modbuddy project I had to get this working locally a few months ago. No idea if it works with the current build or about the dependencies, etc. 
Might be helpful or save a few minutes
https://drive.google.com/file/d/1WN0RLH8IeyVzhYxQ5WtPBMeKLpWeess5/view?usp=sharing

One more thing to consider is to add indication in the panel if the mission being infiltrated is within a liberated region that the mission would be pre-boosted by 50% e.g. by updating the numbers shown with normal or boosted infiltration. Just a small enhancement

**Comment by MiserablePileOfBugs** [comment]
I really miss this mod, it was a huge QoL improvement.

I'm excited to have it integrated in LWOTC.
