### ISSUE TITLE
Finish covert action to discover Templar - game stuck

### ISSUE THREAD

**Issue by buezer** [long-war-2/lwotc#422]
[save_AUTOSAVE- Campaign 61, Mission 9_1.zip](https://github.com/long-war-2/lwotc/files/3517980/save_AUTOSAVE-.Campaign.61.Mission.9_1.zip)

First covert action to find the Templar finishes, Central goes through his lil speech, I get stuck on this screen. Can't move camera or do anything else

![xcom2 bug screen](https://user-images.githubusercontent.com/54293447/63304819-a8dba180-c2a1-11e9-8091-ade4799b420d.PNG)

**Comment by Grobobobo** [comment]
That's caused by lost abandoned being active.
