### ISSUE TITLE
Remove "Reduce Avatar Progress" covert op

### ISSUE THREAD

**Issue by tunbridgep** [long-war-2/lwotc#424]
I feel like this covert op is way too powerful and completely nullifies the avatar project completely.

I think it should either be made more powerful but limited to a one-use "oh shit I am about to lose the game" tactic, or be removed entirely.

With all the changes LW2 makes to the avatar system, it seems really badly designed that the entire system can be basically bypassed completely.

**Comment by pledbrook** [comment]
Covered by #298
