### ISSUE TITLE
AWC ability lists:  How to set up ability prerequisites ?

### ISSUE THREAD

**Issue by Maebalzurakin** [long-war-2/lwotc#425]
I have bee seeing in the classdata.ini that the AWC ability decks still need a lot of work.  

A mod like "I am commander" https://github.com/long-war-2/lwotc/wiki/Mod-compatibility-(community-maintained), listed as 'working with issues' almost seems necessary, due to the large volume of randomness with useless abilities.  Similar to the static pistol line, there should be an infiltration line, where abilities like 'tradecraft' are a guarantee.  Ideally, each class has a smaller amount of set specializations, so that "I am commander" isn't even needed.

It would be nice if the abilities were set up with prerequisites and allow a character to build towards a specialization.  Example:  Center Mass ---> Lethal ---> Alpha Foxtrot, but each ability is an extra +1 damage, instead  of +1, +2 and +4.  

I have no idea how or where to set up the prerequisites though.  Can someone point me to that?

Would putting the pistol abilities above the AWC abilities in the classdata.ini and setting AbilitiesPerRank=4, in the promotionuimod.ini solve the line swapping glitch?

Where are ability line titles kept?  They are the titles on the left, 'XCOM, Pistols...."

**Comment by pledbrook** [comment]
I don't want to veer into RPG Overhaul territory. The random ability decks match original LW2 (minus some mutual exclusions I can't replicate right now) and the fact they're not split into defensive/offensive right now. I didn't really fancy the extra work.

Don't forget that LW2 is about dealing with the stuff you get. Be that a "poor" class for a particular soldier's stats, or the XCOM perks they get.

That said, I'm not terribly happy with the current implementation or the original LW2 one. Any new implementation, though, should satisfy ideally result in:

 * Distinctive soldiers
 * A balanced gameplay experience
 * Variety between campaigns

An element of randomness can help here, but it's not the only solution. I just don't want to invest a lot of thought and energy into this particular feature before the first release is out.

**Comment by pledbrook** [comment]
In answer to the original question, prerequisite requirements need to be set up in code rather than INI. And the text for ability tree names is in the localisation files with the key `AbilityTreeTitles`.
