### ISSUE TITLE
Integrating WOTC missions within the LW2 narrative

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#426]
So first off, this is purely an enhancement and might be more trouble than it is worth. Anyway, the idea is to incorporate the new mission types that wotc introduced into the LW2 set of guerilla ops. Specifically, the following can be considered:

- Rescue Stranded Resistance Agents (Can be a variant of a rescue scientist/engineer, with or without the downed resistance agent)
- Stealth Rescue (As a variant of the jailbreak mission. At the very least, the map layout looks interesting and can be used for the conventional jailbreak)
- Assassinate Advent General ( As a variant of either the lib 3, propaganda or COINResearch mission which involve a neutralize target objective)
- Supply raid with crate tagging (already replaced smash and grab, but I hope both types are ultimately incorporated)
- Haven retaliation with resistance fighters (as an "easier" variant of the classical retaliation or even an invasion or foothold  mission)
- Psionic transmitter sabotage (as a variant to lib3, ProtectData, Counterinsurgency, COINResearch and COINops destroy relay missions)

I am sure some or all of these would need a lot of tweaking to come to par with the vanilla variants, but it would be good to at least document these here for reference

**Comment by MiserablePileOfBugs** [comment]
> Haven retaliation with resistance fighters 

I really loved this new addition in WOTC. That's what HR should have been from the start IMO. Seeing the rebels just standing there in wait of getting killed by the aliens breaks the immersion.

It would be nice to have this variant in LOTWC along with the HR where reinforcements drop every turn.

**Comment by Anxoczt** [comment]
I would like to have militia included in some of the resistance defence based missions too.

**Comment by pledbrook** [comment]
I would probably lock the VIP + soldiers missions behind covert actions, because the rewards are so strong. So the Recruit Scientist/Engineer covert actions wouldn't give you one of those staff, but instead spawn a rescue mission. I think it might be nice to have the Supplies covert action do the same but with a Smash N Grab.

**Comment by Grobobobo** [comment]
We only decided to add supply extraction, psionic transmitter and ambushes.
