### ISSUE TITLE
officer ability"focus fire"error

### ISSUE THREAD

**Issue by Sinkingeye** [long-war-2/lwotc#429]
Focus fire description:
Spend an action to pinpoint a target and grant your squad CUMULATIVE Aim bonuses and 1 Armor Piercing on attacks against that target for the rest of the turn.
Which means the aim bonus will increase by 5% each time the target is shot(hit or miss),reach 15% at maximum.
However in LWotC,the bonus will not increase accordingly,for example:
First shot:
![20190823171449_1](https://user-images.githubusercontent.com/53558693/63586887-186ccc00-c5d5-11e9-82e9-6afcfe311543.jpg)
Second shot:
![20190823171530_1](https://user-images.githubusercontent.com/53558693/63586898-21f63400-c5d5-11e9-9ddc-5ae907f5c85b.jpg)

**Comment by pledbrook** [comment]
Save file?

**Comment by Sinkingeye** [comment]
Sorry,I just presume anyone can have a officer with focus fire and test it in their campaign.
I will provide a save file as soon as posdible.

**Comment by Sinkingeye** [comment]
> 
> 
> Save file?

[Focus fire error.zip](https://github.com/long-war-2/lwotc/files/3537871/Focus.fire.error.zip)
Here you go.
In this save,a great archon is panicking,and there is a specialist officer with focus fire ability.

**Comment by pledbrook** [comment]
Thanks. It saves me a lot of time and effort in verifying the bug and then diagnosing it. Remember that there are lots of issues that need to be dealt with and it can be awkward to try to replicate a problem, particularly if it's caused by special circumstances.
