### ISSUE TITLE
Unequip Skirmisher gain +2 mobility

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#431]
Today start new campaign, download last devs build from discord #releases, and see this +2 mobility on unequip skirmisher, does its ok?

[save_Skirmisher_equip.zip](https://github.com/long-war-2/lwotc/files/3534860/save_Skirmisher_equip.zip)

![Skirmisher_equipment](https://user-images.githubusercontent.com/51829747/63598720-d2117000-c5c8-11e9-86b4-fea37c66364c.jpg)

**Comment by nightmaRok** [comment]
I think if you set up bullpup as SMG_weapon type, then its should be Ok

**Comment by jmartinez989** [comment]
This is intentional, we made bullpups grant +2 mobility. They also give skirmishers slightly reduced detection radius (a little bit lower than assault rifle and a little higher than smg).

**Comment by nightmaRok** [comment]
OK, then I’ll close this issue
