### ISSUE TITLE
Skirmisher and Templar cant select where throw EVAC

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#433]
Skirmisher\Templar cant select where  throw EVAC, only if you select other soldier and select where throw EVAC, then skirmisher\templar can throw EVAC at last selected place, even if it in other map corner. Work fine with Reaper.

[save_Call_scyranger_skirmisher.zip](https://github.com/long-war-2/lwotc/files/3535666/save_Call_scyranger_skirmisher.zip)
[save_Call_scyranger_templar.zip](https://github.com/long-war-2/lwotc/files/3535667/save_Call_scyranger_templar.zip)
[save_Call_scyranger_reaper.zip](https://github.com/long-war-2/lwotc/files/3535674/save_Call_scyranger_reaper.zip)

![Call_scyranger_skirmisher](https://user-images.githubusercontent.com/51829747/63613047-735bee80-c5e8-11e9-83ac-131cc6d10676.jpg)
![Call_scyranger_templar](https://user-images.githubusercontent.com/51829747/63613058-7951cf80-c5e8-11e9-88a8-8429e70259ea.jpg)
![Call_scyranger_reaper](https://user-images.githubusercontent.com/51829747/63613065-7ce55680-c5e8-11e9-96d7-8adbd71583b0.jpg)

**Comment by pledbrook** [comment]
So, this doesn't happen always. No idea why you've encountered it these three times. Looks challenging to diagnose.

**Comment by nightmaRok** [comment]
This happen always with skirmisher and templar

**Comment by pledbrook** [comment]
OK, I'll test again. I started a new campaign and it worked OK with a Reaper.

**Comment by pledbrook** [comment]
Weird that it seems to work OK on a new campaign Gatecrasher with Reaper but not Skirmisher. 😕

**Comment by nightmaRok** [comment]
Yeap, as i said, reaper work fine, templar and skirmisher no.

**Comment by aturaki** [comment]
+1
