### ISSUE TITLE
Rapid Fire has 5 turn cooldown when it should be zero

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#435]
XCOM 2 Vanilla: no cooldown
LW2: no cooldown
WotC: nerfed to 5 turn cooldown
LWotC: Presumably should have no cooldown, but has 5 turn cooldown

**Comment by pledbrook** [comment]
Fixed with [this commit](https://github.com/long-war-2/lwotc/commit/3839e8630c554282f4d3195258ee8aec0d17d9e1)
