### ISSUE TITLE
Technical has 3 rockets when entering chosen base assault part 2

### ISSUE THREAD

**Issue by Sinkingeye** [long-war-2/lwotc#437]
Technicals can have at most 2 normal rockets(EXO suit),but when I start chosen base assault part 2(in stasis chamber),I find out that a technical has 3 normal rockets.
[Technical three rockets-before assault.zip](https://github.com/long-war-2/lwotc/files/3537925/Technical.three.rockets-before.assault.zip)
[Technical three rockets-mission part 2.zip](https://github.com/long-war-2/lwotc/files/3537926/Technical.three.rockets-mission.part.2.zip)
another thing is,my ranger was injured and all her ablative points was removed in Part 1,but in part 2,her ablative points is restored,you can find it out in the save file.

**Comment by BlackRose39** [comment]
I noticed too that when transitioning from one map to another in the same mission, the game tends to rerun checks on certain item/abilities and equipment, causing similar glitches like this.

Check and see if the same happens when going to the second stage in the final mission.

**Comment by pledbrook** [comment]
See #451 for another reproducible sample, this time on the Lost Towers mission.

**Comment by Grobobobo** [comment]
Already fixed.
