### ISSUE TITLE
Recruit soldiers dont show their stats

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#438]
In original LW2 recruit soldiers show stats

[save_Recruit_stats.zip](https://github.com/long-war-2/lwotc/files/3538225/save_Recruit_stats.zip)

![Recruit_stats](https://user-images.githubusercontent.com/51829747/63651630-5f86c880-c75f-11e9-8b75-f5db1b807b0c.jpg)

I test it on original lw2
save from lw2_1.5
[save6.zip](https://github.com/long-war-2/lwotc/files/3538233/save6.zip)

![Recruit_stats_lw2](https://user-images.githubusercontent.com/51829747/63651631-5f86c880-c75f-11e9-802d-de1d91a68126.jpg)

**Comment by pledbrook** [comment]
This could be done as an MCO of `UIRecruitSoldier`, but the original implementation relied on a highlander hook. That's probably the best option as it provides other mods an easy way to extend this screen. I'll find out whether the highlander approach is acceptable.
