### ISSUE TITLE
Faceless resistance not scampering after revealing pod

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#440]
Found a couple of Faceless in my resistance haven, so I started the mission. Revealed pod with Faceless resistance members. They transform, but don't scamper towards me like other members of the pod. They just stand there.

**Comment by BlackRose39** [comment]
This is international. Faceless revealed normally through pods will scamper, but those which are revealed by transforming don't have scamper.

**Comment by pledbrook** [comment]
Right, I don't think this is a bug (unlike the invisible Faceless...)
