### ISSUE TITLE
Injured grenadiers will unequip flashbangs and turn them into sting grenades others can use or sell

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#442]
![20190826194516_1](https://user-images.githubusercontent.com/54481962/63735301-58d67f00-c84d-11e9-9945-a151b7524a1b.jpg)

**Comment by pledbrook** [comment]
Is this a duplicate of #360? Which version of LWOTC are you playing?

**Comment by allenhu0912** [comment]
This was the Aug 20 version
