### ISSUE TITLE
Suggestion: make more fraction solder classes

### ISSUE THREAD

**Issue by frigle** [long-war-2/lwotc#443]
My example of it :
Xcom2 classes 
Templars:
Warrior - standard Templar 
Pciop (telecenethic, shield, mind control) 
Necromenser (necro, asid-poison, shaman) 
Mage (freezer, piro, flash) 
Skirmishers:
Skirmisher (solder) 
Defender (shotgun + shield) 
Demolitioner (granade)
Officer 
Reapers:
Skyte (mallie) 
Rogue middle range combat 
Sniper 
Specops (spy) maroon beret
XCOM:
Specialist 
Engineer 
Spark 
Gunner

Make 4 classes for each fraction based on the lore of the game. For example, xcom is high technology fraction coz it has drones, robots and stuff. Reapers are destroyed Russian special forces, etg. I know, that classes aren't based on LW2 classes, but I think it's a good idea to make smth new.

**Comment by Anxoczt** [comment]
Just no, i dont want LWOTC to go that far above its original mission. It should be simply WOTC friendly version of LW2, not a new mod altogether. Or atleast not when its still developing, sure, once the mod is finished and for general audiences ready, then a version of it, with new features and stuff, would be great, but the core experience should be remained untouched as much as possible on the way to that "finished" state.

**Comment by Grobobobo** [comment]
Way Beyond the scope.
