### ISSUE TITLE
Wierd infiltration time with reaper

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#445]
Play last devs build with rebalanced faction soldiers. Wierd infiltration time, if send reaper solo its 4d 3h, if + shinobi its lower 3d 22h, solo shinobi 3d 12h. Never see before, add soldiers always increase infiltration time, maybe its fine now because you dont want to send up reaper solo on missions? Or its because new rebalance ability shadow take longer to infiltrate?

[save_Reaper_infiltration_time.zip](https://github.com/long-war-2/lwotc/files/3547851/save_Reaper_infiltration_time.zip)

![reaper_inf_01](https://user-images.githubusercontent.com/51829747/63803527-ceaa1b80-c91d-11e9-88f7-e1e14f4b9516.jpg)

![reaper_inf_02](https://user-images.githubusercontent.com/51829747/63803535-d2d63900-c91d-11e9-9b6b-b492cdd4da29.jpg)

**Comment by Grobobobo** [comment]
That was changed and fixed a while ago.
