### ISSUE TITLE
TAB on Promotion screen leads to easy and instant promotions for all soldiers

### ISSUE THREAD

**Issue by charliepryor** [long-war-2/lwotc#447]
I think this might be some sort of debugging feature, but it's certainly happening in my game, so it's clearly on. You can promote any soldier to max rank just by hitting tab on the abilities screen now. It's likely a conflict with another mod perhaps?

Streamer in your Pre-Beta confirms it exists for them too.
MOD LIST: (Everything that's installed aside from the Alpha): https://steamcommunity.com/sharedfiles/filedetails/?id=1248890570
VIDEO: [https://www.twitch.tv/videos/473375257](https://www.twitch.tv/videos/473375257)

Save File Also Attached
[save_Save 64.zip](https://github.com/long-war-2/lwotc/files/3549005/save_Save.64.zip)

**Comment by pledbrook** [comment]
This is just an artifact of using a non-final-release community highlander: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/578

**Comment by pledbrook** [comment]
It was basically "fixed" with the beta 1 release.
