### ISSUE TITLE
Training Center interactions

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#450]
I constantly find myself guessing, or spending time on fruitless google searches, when it comes to determining how different XCOM abilities interact with the classes and their abilities: Does Close and Personal work with shinobi sword attacks, how does Run and Gun interact with Fleche, What does Run and Gun do for a sharpshooter and does that answer change depending on if they have snap shot?

This is perhaps out of bounds of the scope of the project, but if the list of abilities available to each class is set, perhaps we could pool knowledge of how they interact with the classes that get access to them and their features into one place? Adding them to the "?" button on the skills themselves would be ideal, obviously, but even a post with the combined info over on the Pavonis forums would be immensely helpful.

Planning what abilities to take to customize your soldiers to get the most out of their random abilities adds fun and variety, but is more rewarding when you can accurately predict what outcome your choices will have. To that end, is their anyway to get the "?" button, and the information held within, to display before you reach the level where it becomes selectable?

Light Em Up: Takes one action and does not end your turn. 'Death from Above' does not trigger on kills made with first action.

Close and Personal: Applies to Ranged and Melee attacks.

**Comment by Grobobobo** [comment]
already reworked the localization on most abilities to be made more clear.
