### ISSUE TITLE
Grenade count increments on transitions between mission stages

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#451]
On multi-stage missions, like Lost Towers, Chosen Strongholds and the Alien Fortress, XCOM soldiers gain grenade charges on entering each stage after the first.

To reproduce, have Lily evac via the lift in the following save:

[save_SPARK_DLC_Extra_Grenades_on_2nd_map.zip](https://github.com/long-war-2/lwotc/files/3550059/save_SPARK_DLC_Extra_Grenades_on_2nd_map.zip)

Frost bombs, flashbangs, etc. gain a charge.

**Comment by Sinkingeye** [comment]
I guess it's same as issue#437 ?
