### ISSUE TITLE
"Tactical Upgrades: Hard Target" missing flavor text

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#454]
Dark Event is missing text:

![20190829045555_1](https://user-images.githubusercontent.com/52621448/63926182-66d8fb00-ca19-11e9-8baf-928d843f6fa3.jpg)

**Comment by pledbrook** [comment]
Don't suppose you have a save for this? I can probably reproduce using cheat commands, but not sure.

**Comment by ToastedAmphibian** [comment]
Yeah, just hit the Dark Events button on the globe, it is still pending.

[save_AUTOSAVE- Campaign 7, Mission 43.zip](https://github.com/long-war-2/lwotc/files/3558922/save_AUTOSAVE-.Campaign.7.Mission.43.zip)

**Comment by pledbrook** [comment]
Couldn't reproduce, so I'm assuming this has already been fixed.
