### ISSUE TITLE
Regarding enemy AI vs unseen targets

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#455]
LW2: Activating a pod, no matter how, would cause them to make a beeline for the nearest unconcealed soldier. They would even know if you had set up an Overwatch ambush, and would stand at the edge of your vision to avoid reaction fire.

LWotC: Activating a pod when the nearest unconcealed target is too far away (e.g. a sniper taking potshots on an Advent HQ map) will cause most if not all enemies to run back and forth like headless chickens.

Also, a side note: Sectoid zombies seem to have maphack. If you send a solo Reaper on a mission and start killing stuff, most aliens will run around randomly like described above. However, zombies will make a beeline for you as if they know where you are. I don't know if they still do that if there are farther but unconcealed XCOM soldiers.

**Comment by yoshimo** [comment]
the lw2 version feels wrong.

lwotc, mhmm headless if you dont know what hit you is understandable for rookies but not for trained advent soldiers.
Heading for cover and spreading out to find the source seem more realistic

**Comment by Dragon-32** [comment]
Maybe something like [Sniper Defense Fix](https://steamcommunity.com/sharedfiles/filedetails/?id=1502740820)?

**Comment by Grobobobo** [comment]
Sniper defense has already been integrated, and turned out to be a mistake, probably will get reverted. I have made a behavior for out of los ai that actually works, but it's lwotcr only.
