### ISSUE TITLE
Two slots skirmisher ability Heavy Ordnance

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#457]
[save_Heavy Ordnance.zip](https://github.com/long-war-2/lwotc/files/3559815/save_Heavy.Ordnance.zip)

![skirm](https://user-images.githubusercontent.com/51829747/64019396-b7467a80-cb37-11e9-81e1-3bd1a1a3e509.jpg)

**Comment by pledbrook** [comment]
This is happening because Heavy Ordnance appears in the Skirmisher's second random ability deck twice. @jmartinez989 I've asked in Discord, but makes sense to ask here too: is there supposed to be another ability here in place of the second H.O.? Or is it a duplicate that can just be removed?

**Comment by jmartinez989** [comment]
oh I didn't even realize that. yeah I meant to remove that duplicate so it can be safely removed. I'll actually do that as I address all of the conversations of the pull request this weekend.

**Comment by pledbrook** [comment]
Fixed in [this commit](https://github.com/long-war-2/lwotc/commit/95b36ab529bb79b8e991343385a14abddde70999).
