### ISSUE TITLE
Overwatch shots frequently have low aim for XCOM

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#46]
This may be to do with WOTC's new overwatch mechanics. It basically looks like the overwatch aim is being reduced by the cover the enemy starts in. I'm going by what Perfect Information is saying, so I'm not 100% sure that there is a problem here. But those low odds overwatch shots all missed.

**Comment by MagSigeasol** [comment]
I believe this is less of a bug and more of a feature of WotC. See my comment in #4. May wish to consolidate the two as I believe this is a question of balance and proposed implementation of overwatch mechanics between the two versions.

**Comment by BlackRose39** [comment]
Believe the issue was also mentioned here some time ago.
https://www.pavonisinteractive.com/phpBB3/viewtopic.php?f=22&t=27095

**Comment by pledbrook** [comment]
We'll just make [Revert Overwatch Rules Change](https://steamcommunity.com/sharedfiles/filedetails/?id=1127539414) a required/recommended mod dependency.

**Comment by Grobobobo** [comment]
Dependency already implemented, no additional issues reported.
