### ISSUE TITLE
"Tech: Additional Co!!!!!! Station Construction"

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#460]
![20190831050207_1](https://user-images.githubusercontent.com/52621448/64061722-a421c200-cbac-11e9-9d1a-41ebe3fb82c0.jpg)
[save_AUTOSAVE- Campaign 7, Mission 47.zip](https://github.com/long-war-2/lwotc/files/3562246/save_AUTOSAVE-.Campaign.7.Mission.47.zip)

**Comment by Grobobobo** [comment]
This hasn't been reported again in 3 years, so I'm assuming it got fixed somewhere along the way.
