### ISSUE TITLE
Bug in sniper

### ISSUE THREAD

**Issue by Hilera** [long-war-2/lwotc#463]
He can see soldier in monument and shot him too. 
Right? or is my config?
[save_Bug Jowar Banerjee.zip](https://github.com/long-war-2/lwotc/files/3562696/save_Bug.Jowar.Banerjee.zip)

thx for this mod ;)

**Comment by pledbrook** [comment]
Sadly I can't load that save file because it's not in English. Which language is it? Perhaps someone else will be able to load it to verify and explain the bug.

**Comment by Anxoczt** [comment]
I see this bug often when doing the monument demolition, because the area around where you are supposed to plant a bomb is revealed, if any pod patrols in to it, somehow the sniper gets the knowledge of them being there and he can shoot there as if he is using squadsight.

**Comment by Hilera** [comment]
Srry pledbrook, my game is in spanish. The bug is exactly as Anxoczt said. In the standard game nobody can get on the monument, this is the problem i think.

I only hope help in your work. Thx for the fantastic mod.
