### ISSUE TITLE
Class Tweaks: Specialist

### ISSUE THREAD

**Issue by ChrisTheThinMint** [long-war-2/lwotc#464]
As discussed in the project discord, I'm going to collect the various suggestions i have for improving the class trees and post them in one issue per class. After collecting one initial round of feedback, I'll then start adding code that can be pulled in at the team's discretion.  

Here's my proposed perk tree for the Specialist class:

**Squaddie**: Aid Protocol, Interference Protocol, Haywire Protocol
**LCPL**: Field Medic - Sentinel - Combat Protocol
**CPL**: Medical Protocol - Threat Assessment - Airdrop Protocol
**SGT**: Revival Protocol - Scanning Protocol - Failsafe Protocol
**SSGT**: Field Surgeon - Covering Fire - Trojan
**TSGT**: Savior - Cool Under Pressure - Full Override
**GSGT**: Rescue Protocol - Multitasking - Skeleton Key
**MSGT**: Restoration - Killzone - Capacitor Discharge

### New Perks:
**Multitasking** - When Aid Protocol is used on an ally, it also applies the effect to the Specialist.
**Skeleton Key** - Improve skullmining ability of skulljack: 85% hit chance (from 70), +20 hack score, +50% intel from the intel reward.

### Perk Changes:
**Interference Protocol** - Shares its cooldown with Aid Protocol. Now debuffs enemy aim and hack defense, and disables any overwatch for a turn.
**Combat Protocol** - Doesn't end the turn if used as the first action. 
**Airdrop Protocol** - Equipping a grenade changes the grenade type Airdrop distributes to that grenade. With multiple, the first one found is used.
**Failsafe Protocol** - Changed to: Use an action to gain +10 hack score and prevent negative effects on your next hack. 4-turn cooldown.
**Covering Fire** - Added: Reaction shots ignore 50% of cover defense and crit reduction. (Refer to https://steamcommunity.com/sharedfiles/filedetails/?id=1448296443 ) 
**Field Surgeon** - Added: Soldier gains a regeneration of 1 HP/turn.
**Savior** - Healing bonus reduced to +3.

### Design Explaination:
First off, there are two design goals that the proposals for all classes have in common:
- Improve weak/niche options so they can be reasonably picked
- Keep overly strong options from dominating a choice

Both of these goals can involve buffing/nerfing perks, but are also the reason for why I reshuffle perk trees so much, as perk placement is very important.

Secondly, there is a smaller design goal for the Specialist in particular:
- Encourage crosspicking and provide more options (= interesting choices) in the class for combat

This is a big part of why I made Interference a squaddie ability, as it gives the Specialist another basic ability without increasing their strength too much due to the increased cooldown. 
The changes to Failsafe and Airdrop are also meant to enable more active decision-making.

Here are the thought processes between the individual perk changes and moves, ordered by rank.

**Squaddie**
Interference was an interesting, but very weak ability that would never be picked unless it was buffed severely. The decision to include it at Squaddie is a major one, but should finally let it shine.
**LCPL**
Revival Protocol dominated this rank, and at the same time it didn't really define the build early on like the other perks do. Field Medic puts an early focus on quantity over quality, it's the base for a medic build but you need to deal with manual healing for a bit.
Making Combat Protocol non-turnending makes it more consistent with other protocols and lets the offensive Specialist contribute more in combat.
**CPL**
This perk intentionally puts three very flexible abilities against each other. Medical Protocol is very useful, but the defensive strength of Threat Assessment and the flexibility of Airdrop might be considered more valuable, which serves to make the remote heal not dominate the class - to good right, as remote healing has little tradeoff and leaves the Specialist in perfect safety.
**SGT**
This rank is intended as an utility rank, where any perk can be reasonably picked by any build as they don't depend on other perks. Failsafe is changed to an active to keep it in check while rewarding good action management and planning, if you activate it the turn beforehand knowing you will hack something, you can stack it with Interference or move before the hack.
**SSGT**
Trojan inevitably ended up in this rank because all other hacker perks required a specific placement. To keep the choice balanced and make the perks feel less underwhelming, both Field Surgeon and Covering Fire get a buff. The Field Surgeon buff in particular serves to make the perk interesting on the tactical later and not just in strategic considerations, even if it is significant in the latter.
**TSGT**
These perks heavily reinforce an existing build. Savior is a non-brainer for any Medic, but I atleast want it to not scale healing too much so that other options like spare Medikits and vests stay valuable. 
Full Override comes a bit earlier so that the resistance mecs it generates can be more relevant.
**GSGT**
This rank introduces two new perks to spice up the late-game specialist, and puts them alongside the already interesting Rescue Protocol.
Multitasking is a perk that enhances both the overwatch and the defensive capabilities of the Specialist. The combo with Threat Assessment is the most obvious, but it also allows them to stay in low cover or even advance aggressively without too much worry.
Skeleton Key builds on the existing idea of providing strategic benefits in the hacker tree, while instakilling any advent unit is valuable in a pinch, getting more intel and facility leads can be even more so.
**MSGT**
This rank is unchanged, as it's pretty much fine. The three perks are nice capstones for their respective rows without being too overpowered.

**Comment by allenhu0912** [comment]
IMO: Failsafe at GSGT is really weak. Either move it to the newbie levels, so that you're more confident with hacking the early MECs, or improve the effect. Maybe refund one action if you fail the hack, or halve the hack cooldown, etc. Or simply give a flat bonus to tech score

**Comment by Grobobobo** [comment]
I certainly like it more than the old tree, multitasking with threat assesment will make OW specialist interesting, and full override needed to come earlier to make the resistance MEC's more practical. The only perks I'd never pick are manual override and failsafe.

**Comment by allenhu0912** [comment]
I would also like to add that with the Chosen and Lost in the game, Revival Protocol (which can remove those daze attacks from Chosen. Also, IIRC, Chosen kills are guaranteed to make the first soldier bleed out instead of dying.) far outclasses Airdrop on just about everyone. The demolition grenadier tree is a bit on the weak side, and having to send one on the same mission as the Specialist is just another hoop to jump through. And now it even attracts Lost on certain missions, not fun

**Comment by ChrisTheThinMint** [comment]
Thanks for the feedback. Manual Override seems fine to me, it can help the rotation of Aid, Interference and Haywire Protocol but is not a must-have. I looked at Failsafe and Airdrop and had some ideas for how to improve them, and moved them in the tree. I changed the original post to reflect those changes.

**Comment by Grobobobo** [comment]
Manual override would be bad because you don't have enough actions to go through all of your protocols, and my usual go to officers are specialists, so you'll never really gonna need to refresh either aid, interference or haywire. I'd always pick rescue on standard specialists instead.

Failsafe giving + hack is probably the way to go, although 5 turn cooldown seems a bit too big. Don't push MO too hard now :p

**Comment by ChrisTheThinMint** [comment]
I just looked at Aid Protocol to get the exact cooldown it has, and it occured to me that i was completely off with it. I thought it has a 3 or 4 turn cooldown. Manual Override really isnt worth it then, and ill make Failsafe a 4-turn cd instead.

The Airdrop change means that you can select the grenade it will give to allies by equipping one. It will still default to Frag/Plasma.

**Comment by ChrisTheThinMint** [comment]
Added Skeleton Key perk to replace Manual Override.

**Comment by Grobobobo** [comment]
Oh, you don't NEED to remove MO, just buff it severly, like make it a free action with a 4-6 turn cooldown. Skeleton key soulds great because skullmining sucks right now, but's it's far too specific for GSGT.

**Comment by gen-martox** [comment]
I like most of the changes except for Savior, I don’t think it needs to be changed. Specialist’s will still only have a couple for medkits, and that 1 extra health can be the difference between losing and solider and the mission or not, plus not even mentioning beta strike.

I still would like to see revival protocol changed into a cooldown and fixing its bug so it will wake up stunned soldiers.

**Comment by ToastedAmphibian** [comment]
> I still would like to see revival protocol changed into a cooldown and fixing its bug so it will wake up stunned soldiers.

I've been using "[WotC] Revival Protocol Fixes" without apparent conflict.
https://steamcommunity.com/sharedfiles/filedetails/?id=1123037187

**Comment by ChrisTheThinMint** [comment]
As requested by paledbrook, I updated the original post with a long explanation of the suggested changes and my overall intent.

**Comment by allenhu0912** [comment]
I think it bears pointing out that by adding Multitasking and removing Ever Vigilant from the overwatch build, you're essentially turning the overwatch Specialist into an immobile turret. Is that intended?

**Comment by PodliKirill** [comment]
> Revival Protocol dominated this rank, and at the same time it didn't really define the build early on like the other perks do.
I disagree. All legend players i know use combat protocol. Sometime - sentinel. Field medic builds isn't very valuable because of impact of the specialist in the fight is very low in this case. They are working well only in the big encounters - ambushes, raids etc.

**Comment by TheReigningKing** [comment]
We need to be careful of Covering Fire b/c the blue advent guys are going to be much much harder to deal with if that perk gets buffed.

**Comment by ChrisTheThinMint** [comment]
@allenhu0912
It isn't directly intended, more of a side effect of not being able to find a spot for Ever Vigilant on the tree anymore. 
I'm fine with it though, as they can use Threat Assessment to setup overwatch with their squadmtes instead.

@PodriKirill
It's intended that Field Medic isn't instantly valuable, but serves as an investment into future missions and general roster health. 
Also, opinions on Revival Protocol are split, yes. I voiced my opinion there, which is based on the prevalence and danger of stuns and unconsciousness in the early game.

@TheReigningKing
ADVENT Sentries can keep an older version of the perk. Thanks for reminding me of it, I'll consider it when I start coding for the issue.

**Comment by Grobobobo** [comment]
Chris quit.
