### ISSUE TITLE
Enhancement - Change "Momentum" to "Extra Move"

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#465]
When a character gets a movement bonus from whirlwind, the yellow popup that shows up when re-selecting the soldier says "momentum available." Consider coding these text notifications to account for a wider variety of contexts/perk specific.

**Comment by pledbrook** [comment]
Why did you close this?

**Comment by BlackRose39** [comment]
I was having trouble replicating it.

I had given the soldier with the implacable ability an extra action point from the Skirmisher's "Combat Presence." After making a kill, it said "Momentum." 

However, every time I reloaded to replicate the issue, it appropriately said "movement" available. Out of frustration, I decided to move on with the issue.

I'll go ahead and reopen to see if others are able to reproduce the issue when giving soldiers extra action points. (Be it through Combat Presence, Teamwork, or modded abilities like PSI Inspire)

**Comment by Grobobobo** [comment]
Not worth bothering with.
