### ISSUE TITLE
Ghost grenade and other free grenades (Smoker/Flashbanger) persist after end of mission

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#475]
The free grenades from abilities are appearing as physical grenades in inventory after missions.

**Comment by pledbrook** [comment]
Can't reproduce any more. I think this was fixed with the other bug related to `X2Effect_TemporaryItem` .

**Comment by rrnwang** [comment]
I think this is the same X2Effect_TemporaryItem issue that was causing my CTD upon finishing the last objective of a non-evac mission. I'm glad it's fixed. Can't wait to test out the beta once it's out.
