### ISSUE TITLE
Point Blank Headshot?

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#478]
It seems odd to me that Headshot works with pistols, but not the rangers sawed off. Double Barrel makes sense, as it is kind of a special attack I guess, but Point Blank is just firing a sidearm. Would be nice.

**Comment by pledbrook** [comment]
Honestly, I just want to get rid of the Headshot ability. Anyway, Point Blank and Double Barrel are both special shots, although I understand your point. I just don't know whether it's worth adding them to the headshot list. It's easy enough to do, although I can't remember the INI file or config var.

**Comment by BlackRose39** [comment]
Someone has made the mod to remove the head shot mechanic if someone wants to take a look at the code (If the decision to remove it stands).

https://steamcommunity.com/sharedfiles/filedetails/?id=1872649487

**Comment by Grobobobo** [comment]
Headshot mechanic has been removed.
