### ISSUE TITLE
Scientist in infirmary boosts healing rate too much

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#481]
[save_BUG Healing boost too high infirmary.zip](https://github.com/long-war-2/lwotc/files/3574297/save_BUG.Healing.boost.too.high.infirmary.zip)

It seems like adding a scientist to the infirmary halves wound times, whereas it should be increasing the healing rate by 50%. Healing at Templar HQ seems to be working as expected.

**Comment by allenhu0912** [comment]
Not directly related, but has anyone checked the excavation and building times? I'm pretty sure some of the numbers in the Avenger layer are off, especially excavation.
