### ISSUE TITLE
Fortress behaviour is wonky

### ISSUE THREAD

**Issue by DreadnoughtCyberdisk** [long-war-2/lwotc#482]
At the moment the "fortress" perk is acting really inconsistent:
https://www.reddit.com/r/Xcom/comments/79iqbp/fortress_what_does_it_really_make_you_immune_to/

In my oppinion it should either be clarified, what "explosions" it wont protect you from (blazing pinions for example) or it should just be unified to include all kind of explosions (Wich would probably mean that these effects should deal actual explosion damage and not whatever damage it is atm).

Long War 2 / LWOTC is just too punishing to find out the hard way, and the decisionmaking can be heavily influenced by relying on that perk to protect you.

**Comment by gen-martox** [comment]
This is an easy fix just need to change blazing pinions damage type in the weapondata.ini and it will need to be changed for the archon king

[XComGame.X2Item_DefaultWeapons]
-ARCHON_BLAZINGPINIONS_BASEDAMAGE=(Damage=5, Spread=1, PlusOne=50, Crit=0, Pierce=0, Shred=0, Tag = "", DamageType="BlazingPinions")
+ARCHON_BLAZINGPINIONS_BASEDAMAGE=(Damage=5, Spread=1, PlusOne=50, Crit=0, Pierce=0, Shred=0, Tag = "", DamageType="Explosion")

[DLC_2.X2Item_DLC_Day60Weapons]
-ARCHONKING_BLAZINGPINIONS_BASEDAMAGE=(Damage=4, Spread=2, PlusOne=0, Crit=0, Pierce=0, Shred=0, Tag = "", DamageType="BlazingPinions")
+ARCHONKING_BLAZINGPINIONS_BASEDAMAGE=(Damage=4, Spread=2, PlusOne=0, Crit=0, Pierce=0, Shred=0, Tag = "", DamageType="Explosion")

**Comment by pledbrook** [comment]
Hmmm...but what are the side effects of that? I assume there's a reason that it got a dedicated damage type.

**Comment by pledbrook** [comment]
The LW2 folks had Incoming! specifically treat BlazingPinions as explosive. We might be able to modify Fortress to do the same.

**Comment by gen-martox** [comment]
ther shouldn’t be any side effects, I pulled that from a mod I used for wotc and I didn’t see any issues with it. The only reason I can think of it haveing  dedicate damage type is so fortress doesn’t prevent the damage
