### ISSUE TITLE
"Soldier remaining"number do not count reaper in Avenger Defense.

### ISSUE THREAD

**Issue by Sinkingeye** [long-war-2/lwotc#483]
It occured before completion of  Avenger Defense mission,reaper was still out of the line,but the number already reached zero.I wonder if it may occur on skirmisher and templar as well?
Save files below:
[Avenger Defense Faction soldier not counting.zip](https://github.com/long-war-2/lwotc/files/3578445/Avenger.Defense.Faction.soldier.not.counting.zip)

**Comment by pledbrook** [comment]
Which version of the mod are you using? Sounds connected to #199, which is fixed in the dev builds.

**Comment by Sinkingeye** [comment]
> 
> 
> Which version of the mod are you using? Sounds connected to #199, which is fixed in the dev builds.

1.6 alpha 6

**Comment by pledbrook** [comment]
OK, well reopen if the beta hasn't fixed it. I have seen the counter go down to -1, but that's when I carried a unit into the evac zone. Bit weird.
