### ISSUE TITLE
Handle SitReps that modify encounter spawn lists

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#484]
Certain SitReps modify the units that can spawn on missions. For example, they may force only robotic or psionic units. They do this by overriding the encounter spawn lists.

In order to support that mechanism, we will have to ensure that the LWOTC units are including in the appropriate SitRep spawn lists (search for `DefaultFollowOverride`). We would also need to factor in that the base game won't use the SitRep spawn lists if an encounter specifies its own ones, and most LWOTC encounters specify named spawn lists.

If we do support these types of SitRep, we will also need to make sure that `X2DownloadableContentInfo_LongWarOfTheChosen.PostEncounterCreation()` takes them into account.

**Comment by Anxoczt** [comment]
And how will the sitreps be included in the game ? Will be all random just as in the vanilla WOTC or will there be some requirements for missions  ?
What i have in mind is that certain actions could spawn these sitreps, for example doing really well in a region could start increasing the chance of the "Show of Force" sitrep on missions as Advent just throws more at you than usual to stop you. Or if your psiops are doing too well then Advent will try to send more robotic enemies in a sector to counter them.

And infiltrating more (Above 100%) or covert ops could spawn positive sitreps like caches, explosives on the battlefield, or even some new sitreps like lowering the enemy count even more, halved enemy detection radius for everyone and things like that.

Though i wouldnt mind it being random, but sitreps being affected by things you do feels more Long War-ish.

**Comment by pledbrook** [comment]
Kind of implemented with [this commit](https://github.com/long-war-2/lwotc/commit/4c6ebf22d4b0c4869a56e9f1e831d90fad997bd4). Best I can do at the moment.
