### ISSUE TITLE
Weapon pattern selection button not working

### ISSUE THREAD

**Issue by MalekDeneith** [long-war-2/lwotc#486]
The "weapon pattern" button when trying to customize soldier's weapon does not work. This happens only *in-campaign*, the character pool version of this button works without issue. Guessing this is tied to the addition of "remove all mods" button beneath the pattern one.

**Comment by pledbrook** [comment]
This was a [Community Highlander bug](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/877) that has now been fixed.
