### ISSUE TITLE
Pistol Abilities Do Not Work

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#488]
Pistol abilities right now are not working. What happens is that any pistols ability when you try to use it will give a message stating "Insufficient Ammo". I was doing some testing of this a while back and narrowed it down to how the game tries to apply to skills to the pistol in the utility slot.

More specifically it seems that the game does not properly scroll through the soldier inventory to find the pistol and instead just takes the first item it finds in the soldiers utility slots and tries to apply the abilities to that.

The way I confirmed this was to remove the ammo requirement for the Lightning Hands. When I did this I was able to use the skill but when the soldier tried to fire the pistol they just raised their hand like they were firing an assault rifle and not projectile came out and nothing happened. It's as if they were trying to use another item as a firearm.

**Comment by pledbrook** [comment]
@tracktwo Do you remember if you guys changed anything in the highlander or anywhere else to support this? I couldn't see anything obvious when I did a quick search in the old Long War 2 code.

**Comment by Grobobobo** [comment]
Already fixed.
