### ISSUE TITLE
Remove custom LW2 behaviour for Alien Rulers

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#489]
WOTC made Alien Ruler behaviour saner (in terms of how Alien Reactions are handled), so the extra random chance that LW2 adds weakens the Alien Rulers further, while introducing an unnecessary element of RNG.

**Comment by ansabalirai** [comment]
I am unaware of how the alien reactions in wotc are different from vanilla. Is it that now they only act on actions that cost AP and are not in concealment? Or something else?

**Comment by SteveS8** [comment]
They only react when shot at. Not when you move

**Comment by ansabalirai** [comment]
Wait so they are primes now? When did that happen??

**Comment by pledbrook** [comment]
Implemented in [this commit](https://github.com/long-war-2/lwotc/commit/c33b7c43a267a740b27bf41b557df22e1de7ba22).
