### ISSUE TITLE
Faceless presence not draining supplies from monthly drop

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#490]
[save_what_1.zip](https://github.com/long-war-2/lwotc/files/3586598/save_what_1.zip)
Alright. This should be easy enough to look at and see the problem: Got +36 supplies from East Africa and +30 from South Africa coming in 20 hours. Hit the point, Faceless are supposed to be eating 20 of them and then the drop is a full 66.

**Comment by pledbrook** [comment]
[Fixed in highlander](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/542#issuecomment-539433067).
