### ISSUE TITLE
I can't continue training a psi soldier

### ISSUE THREAD

**Issue by Hilera** [long-war-2/lwotc#491]
[save_Bug PSI soldiers.zip](https://github.com/long-war-2/lwotc/files/3587271/save_Bug.PSI.soldiers.zip)

When I finish training a PSI soldier dont let me continue it. I tried to put other new recruits but the same thing happens. Previously never install another mod that changes the physics of the game. I only have skins mods.

P.D: this game is in spanish version.

**Comment by DreadnoughtCyberdisk** [comment]
That is normal behaviour, once you trained them, they need to go to missions to level up before you can train the next rank. At the moment it doesnt show you when they actually leveled up after a mission so you have to try it out when they are back from the mission you sent them on.

**Comment by Hilera** [comment]
ah ok. Thx DreadnoughtCyberdisk i dont know it. Excuse my ignorance.
