### ISSUE TITLE
Rebalance reinforcements on invasions

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#492]
Reinforcements are both broken and ridiculously challenging on Invasion missions. They're broken because they don't always show up when they're supposed to at the start. And they're challenging because they both start dropping every turn shortly into the mission and scale to 10-12 unit pods soon after that.

This is important to balance now that players can no longer cheese the mission by dealing 10 damage in one shot to the transmitter/spike/whatever it is.

**Comment by PodliKirill** [comment]
There is one important thing. Invasion is a full loot mission. If there will be way to farm reinforcements - this can broke game economy.

**Comment by pledbrook** [comment]
That's true. Let's see how far players can push it. Don't forget it's more challenging now because you can't cheese the spike, and the reinforcements should still be pretty punishing.

And honestly, the rebels you typically lose to an invasion probably offset much of the gain in corpses.
