### ISSUE TITLE
Squad Management sorting column headers broken; labeled LABEL all.

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#495]
![whaaaaaaaaaaaaaaaaaaaaaaaaaaat](https://user-images.githubusercontent.com/54611482/64490903-7df0c780-d227-11e9-9f67-eeed612fcc62.jpg)

**Comment by Clibanarius** [comment]
They don't sort, either. Actually clicking the header of the column in question does not change the ascending/descending sort state.

**Comment by BlackRose39** [comment]
#320

**Comment by pledbrook** [comment]
Duplicate of #320
