### ISSUE TITLE
Skirmisher Return Fire non-functional

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#498]
Been testing this one out for the last 15 minutes once I realized it hadn't triggered on a proper instance where it shoulda: I got a Skirmisher with Skirmisher Return Fire and he took a point-blank shot from a Trooper. Figured there might've been some condition in the skill where it only functions on a would-be missing shot, but, sure enough, I stick him in low cover and wait for someone else to shoot at him, and it doesn't trigger. Though it might be worth noting that I'm using an Assault Rifle on him and not a Bullpup (I have the weapon availability expanded some in my game), but I didn't think that would matter. If anyone else could test on their end and see if Skirmisher Return Fire functions, it'd be appreciated!

**Comment by gen-martox** [comment]
Actually yes it does matter that your using an assault rifle instead of the bullpup. For Return fire to work the weapon needs to have the “pistol return fire” ability attacted to it, which the bullpup has and assault rifle doesn’t.

**Comment by Clibanarius** [comment]
Welp, that solves this issue! Here's the sound of me smacking my own forehead.
