### ISSUE TITLE
Suggestion: Make an SW option so you can buy all soldiers abilities with AP (like WOTC)

### ISSUE THREAD

**Issue by dall0078** [long-war-2/lwotc#505]
Hey, I know there will be balance involved (which I think should not be accommodated for this option as it will not be the default one), but one of the things that was really fun on WOTC was that the fact that the more you would invest in them, you could see the results with improving their effectiveness. This was balanced out by the fact that AP is a shared and balanced element so you can't make everyone into killing machines.
I'm pretty sure this will be one of the first things people will mod out the behaviour, so why not integrate it as a option so they can choose what experience they want? Of course if it's not that much trouble and would not affect time into other things.
Kind Regards

As BlackRose mentioned : For a temporarily workaround, I find that you can head to xcompromotionuimod.ini and set the "abilitiesperrank" to 0 (currently only for individual classes), and it should work exactly as it should that the original promotion mod does where you can pick as many abilities per rank as much as you like. For modded classes, you'll have to add the class manually. Its recommended you increase the ap on promotions too, or else you dont get even ap for one perk, to balance it out (because of the costs).

**Comment by BlackRose39** [comment]
Hello.

There has been a discussion regarding so in #337, and I think the general consensus has been to enable this option by player choice. (The same way the Chosen can be activated or not). I definitely agree with having second wave options for this.

**Comment by pledbrook** [comment]
It's not _that_ balanced by AP being shared (in fact, most AP is awarded to the individual soldiers). The key issue is that most players have an "A" team, so its members are the only ones you need/want to buff with extra abilities.

That said, now that I have experience with adding a custom second wave option, it should be pretty easy to add this one. I'm considering calling it "Super Hero Mode" :smile:

**Comment by pledbrook** [comment]
But yes, the game will not be balanced around such a mode, particularly as I think ability points need to be rethought in general. I think they could be used more interestingly than they are now.

**Comment by Anxoczt** [comment]
"Ubermench mod" 

But anyway, i think the second wave should be utilised to help out even out the difficulty from the player side. If they feel they want it easier, they can play with more useful soldiers, or if they are core experience loving users they can ignore it. Literally no harm done and i would support more of the WOTC new features that will be and are removed to be transfered there so the difficulty will be more customizable.

And besides, with tiring mechanics, infiltration and larger soldier pool requirements it has a sort of natural barrier towards the "A Team of Gods of War" or atleast it will take alot longer when compared to WOTC. But anyway i would really appreciate the second wave to be used for this and nerfs/balances of the "fun" stuff.

**Comment by Favid** [comment]
Implemented Advanced Option for this, but I did not do any sort of balancing (e.g. mutually exclusive perks, rules for conflicting abilities). But since this feature is optional and inherently unbalanced, I figure that if this gets merged in, additional Issues can be created for that.
