### ISSUE TITLE
Camera Angle Menu Option

### ISSUE THREAD

**Issue by harlequin565** [long-war-2/lwotc#507]
New to Github (joined to comment) so please be gentle with me...
1st issue I've spotted and can't find an open case for is that the camera angle settings in the Long War options don't seem to do anything.
Options>Campaign>Camera Rotation.
I've "fixed" it by installing the Camera Rotation Config mod which works just fine.

**Comment by pledbrook** [comment]
Yes, sorry, the code that does all that is a bit scary, so I've ignored it for now. The correct solution is to install one of the camera rotation mods, as you have done.

**Comment by pledbrook** [comment]
Fixed in [this commit](https://github.com/long-war-2/lwotc/commit/083bbbbc318719adb3ee25a90c2a4f9885851e6b).
