### ISSUE TITLE
Rookies Available On New Game

### ISSUE THREAD

**Issue by harlequin565** [long-war-2/lwotc#508]
In LW2, you had no rookies available to recruit when the game began, they had to be recruited from Havens (with the recruit job or Jailbreak missions)

Currently, there are 5 rookies available for me to recruit on day 1

(Hindsight edit - I play Legend LW2 and am starting this LWoTC campaign on Vet so it might be that?)

**Comment by Clibanarius** [comment]
It is, indeed, that. My Legend LWotC campaigns always start with 0 recruits available.

**Comment by harlequin565** [comment]
OK. Thanks for that.
