### ISSUE TITLE
Can't select declined missions from map

### ISSUE THREAD

**Issue by rocknin** [long-war-2/lwotc#510]
As title, all missions are titled "LW generic overhaul mission" and cannot be activated after you decline them the first time. This includes missions that are required, such as liberation missions that don't expire.

**Comment by pledbrook** [comment]
Do you have a picture? It sounds like you have a bad installation, or a mod conflict or something like that. In fact, my guess is that you have a conflicting highlander. Have you looked at the [troubleshooting guide](https://docs.google.com/document/d/1EEZqmzCQQoprh3sDFZQZyiuyRE8I_lsA7Z8pHTSRuzU/edit?usp=sharing)?

**Comment by rocknin** [comment]
I followed the troubleshooting guide, unsubscribed from the other highlander, and that seemed to do it.
i was using the highlander LWOTC provided, weird that that happens. Thanks!
