### ISSUE TITLE
Assigning scientists to tasks doesn't properly increase research time

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#511]
LW2: Assigning scientist to infirmary or haven advisor or psi lab means that they do not contribute to research speed

Current behavior: You can assign scientists to jobs and they will still contribute to research time

**Comment by pledbrook** [comment]
Confirmed. Swapping the scientist in and out of the infirmary has no effect on research times:

[save_BUG Infirmary Scientist doing research.zip](https://github.com/long-war-2/lwotc/files/3612546/save_BUG.Infirmary.Scientist.doing.research.zip)

**Comment by pledbrook** [comment]
This requires a highlander change in `XCGS_HeaderquartersXCom.GetScienceScore()` to allow mods to adjust it. It currently only ignore dead, injured, or on-covert-action scientists.

**Comment by pledbrook** [comment]
It looks like we should also set the status for scientist and engineer haven advisers to `eStatus_CovertAction`, just as we do for soldiers. At the moment, scientist haven advisers seem to also be contributing to research.

**Comment by pledbrook** [comment]
Depends on [highlander #626](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/626).
