### ISSUE TITLE
Cosmetic Issue: Big Head Mode

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#514]
OH MY GOD BECKY, LOOK AT HER HEAD!

![20190914012920_1](https://user-images.githubusercontent.com/52621448/64903888-494d9780-d68f-11e9-9912-f30d03606285.jpg)
![20190914012807_1](https://user-images.githubusercontent.com/52621448/64903893-51a5d280-d68f-11e9-9a08-535182c1bd6c.jpg)

Post action screen for Gatecrasher, looked fine at first, then suddenly their heads exploded and their hair fell out (In? Back?). Looked fine in the armory after.

Happening on mission deployment screen also. Look fine until I hit the go button, and all the heads expand as they turn to board the ship.

**Comment by Anxoczt** [comment]
Doesnt looks like a LWOTC problem to me... more like some cosmetic mod problem. Because as far as i am aware, LWOTC doesnt touch anything about the customization of your troops.

**Comment by ToastedAmphibian** [comment]
A logical conclusion, were I running any cosmetic mods. Only change I made was updating LWOTC from Alpha 6 to Beta 1.

**Comment by Witt-Github** [comment]
I sometimes see this sort of thing while playing plain old WOTC (I haven't even downloaded LWOTC yet). Usually mine only show up like that in the headshots for the characters, but I'm pretty sure it's a cosmetic mod issue (I'm using several, including the New Faces mod).

**Comment by ToastedAmphibian** [comment]
Current Mod List:
STOP WASTING MY TIME - WOTC
WOTC: ROBOJUMPER'S SQUAD SELECT
[WOTC] MOD CONFIG MENU
[WOTC] ADDITIONAL ICONS
[WOTC] GOTCHA AGAIN
**DISABLE REAPER OVERLAY**
[WOTC] REVERT OVERWATCH RULES
**[WOTC] REVIVAL PROTOCOL FIXES**
EVAC ALL - WOTC
**[WOTCH] FREE RELOAD ANYTIME**
BETTER SECOND WAVE MOD SUPPORT
LONGWAROFTHECHOSEN
X2WOTCCOMMUNITYHIGHLANDER
[WOTC+CLASSIC] TACTICALUI KILLCOUNTER
YET ANOTHER F1
----------------

Mostly just the ones required or recommended by the Mod developers. The odd one are mods that remove the annoying green tent when reapers are in Shadow, Fix revival protocol to actually cure stun as it claims to in its skill description, and allow you to perform a regular reload if you want instead of an auto loader reload. I'm not sure how any of those would be causing this...

*shrug* If I see it continuing to happen I'll try and grab a save instead of just screenshots. As is, I only noticed it at the end of gatecrasher and the beginning of the second mission.

**Comment by pledbrook** [comment]
Input from robojumper:

> ^ This is interesting. I ran into this issue when I worked on the CHL custom heads feature when I hid the base unit pawn and it'd decide to disable some feature of the AnimTree responsible for applying female animations. This is why I'm using an invisible material https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/1a31c1620d9ace07fc46cc716510c7bebc637073/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComHumanPawn.uc#L1405-L1420
> To clarify, I expect this issue to only apply to female pawns
> I would have thought that this is an issue with custom .umap files for CIN_PreMission/CIN_PostMission, but I just downloaded the latest beta and it doesn't seem to override those maps, so ¯\\\_(ツ)\_/¯
> The reason I suspected the umaps is that both descriptions of the issue mentioned situations where Kismet/Matinee takes over

**Comment by Grobobobo** [comment]
not a lwotc issue.
