### ISSUE TITLE
Battlemaster skill description

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#517]
![20190914025347_1](https://user-images.githubusercontent.com/52621448/64904648-e4983a00-d69a-11e9-80ed-f0126596885a.jpg)

I'm not sure what this is intended to say. At any rate, it is talking about skirmishers in general, not the skill.

**Comment by nightmaRok** [comment]
@pledbrook i try 1st time do some changes in files, test on my game, now its look like on printscreen. Is this OK? If its fine I can try add this changes as fork on github =)

![Skirmisher_battlemaster_01](https://user-images.githubusercontent.com/51829747/65066908-fe34cc80-d98d-11e9-991c-8a5ba7cf3b85.jpg)

**Comment by pledbrook** [comment]
I would remove the first line, remove the "more" from "+10 more aim", and remove "significantly" from the last line. Otherwise, looks great, thanks!

**Comment by ansabalirai** [comment]
Just wondering, what is the point of the first line? Coz i would challenge that in court :D

Also, had this issue with LW2 tooltips as well, what does "reduced infiltration time" mean exactly? Can we be precise as to how many hours it reduces? Or is it dependent on the overall squad composition and cannot be determined easily?

**Comment by nightmaRok** [comment]
@pledbrook there some different texts in LocPromotionPopupText= and LocLongDescription=, do i need remove "significantly" from LocLongDescription=? 

![Skirmisher_battlemaster_01](https://user-images.githubusercontent.com/51829747/65067679-bdd64e00-d98f-11e9-85be-3afe5810045a.jpg)
![Skirmisher_battlemaster_02](https://user-images.githubusercontent.com/51829747/65067681-bdd64e00-d98f-11e9-878e-2eac41e1ee29.jpg)

**Comment by pledbrook** [comment]
It depends on the number of soldiers in the squad. It currently reduces the infiltration "contribution" to 80% of a normal soldier. It's the same effect as putting an SMG on an Assault/Ranger. It's really hard to put a number to it.

On top of that, we may end up making changes to Skirmisher related to infiltration bonuses. Don't really want to have to update the text if and when we do that.

@nightmaRok Yes, please remove "significantly" from there too. In a normal(ish) mission, you might reduce infiltration by a couple of hours. Which probably doesn't count as significantly for many people.
