### ISSUE TITLE
Players currently excavate twice as fast as they should in the Avenger compared to LW2

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#518]

**Comment by pledbrook** [comment]
Is this something that changed with WOTC? I can't see any LW2 configuration that changes this.

**Comment by pledbrook** [comment]
I just had a look at xwynn's last LW2 campaign, and the very first alien debris excavation took 8 days, exactly as long as the LWOTC one I just tried. Can you please provide examples/evidence that excavation is twice as fast in LWOTC as in LW2?

**Comment by allenhu0912** [comment]
I have had 45 day excavations at the bottom in LW2. I have never had more than 23 days in LWOTC.

**Comment by pledbrook** [comment]
Are you sure you're not getting confused with the base game or an older version of LW2? The setting for LW2 1.5 is:
```
ClearRoomProject_TimeScalar[3]=1.5 ;Impossible
```

but for plain WOTC, it's:
```
ClearRoomProject_TimeScalar[3]=3.0 ;Impossible
```

**Comment by allenhu0912** [comment]
No, I wasn't actually playing on Impossible. I played on Veteran for LW2, right now I'm playing on Commander

**Comment by pledbrook** [comment]
The [Alternative Mod Launcher](https://github.com/X2CommunityCore/xcom2-launcher) supports profiles, which allows you to save mod lists to a text file and load them again at a later date. I used that feature to switch between LW2 and WOTC, i.e. I had one profile for LW2 and one for WOTC.

**Comment by pledbrook** [comment]
Since the first excavation time matches what I saw in one of Xwynn's LW2 videos, assuming this is working as it should.
