### ISSUE TITLE
Liberation 1 objective description is different for real and fake versions

### ISSUE THREAD

**Issue by Favid** [long-war-2/lwotc#520]
In LW2, the objective text for the first liberation mission was "Find a lead". There were also dummy missions that wouldn't start the liberation chain with the same name, so that the player didn't know for sure if completing the mission would actually start the liberation chain. 

In LWOTC, the objective text for the real first liberation chain was changed to "Start liberating the region" to make it more clear. However, the fake ones still use the "Find a lead" text, so the player always knows which one is real now. The localization should be changed to be the same for the real and fake liberation 1 missions.

**Comment by ToastedAmphibian** [comment]
I don't think they are "fake", I think they are to help discover the location of other things.

**Comment by pledbrook** [comment]
Are you sure there were dummy missions? As far as I'm aware, and as far as I've seen both playing and watching Xwynns videos, the only other mission that looks like a Lib 1 is the Landed UFO Detection mission.

**Comment by allenhu0912** [comment]
Ditto. The "fake mission" is actually the precursor to finding a landed ufo mission

**Comment by Favid** [comment]
http://pavonisinteractive.com/phpBB3/viewtopic.php?t=23754
http://pavonisinteractive.com/phpBB3/viewtopic.php?t=25535

Looks like I was sort of off. Find a Lead missions will either start liberation, reveal a point of interest, or lead to finding a landed UFO. I assumed they made it difficult to know exactly what the outcome would be on purpose. If we're fine with making the results more clear for starting liberation (which I think is fine, I found it was more confusing than necessary in LW2) then please close this issue.

**Comment by TheReigningKing** [comment]
It was pretty obvious that a Find a Lead mission without an Intel Package reward was Lib 1.  If you've already found Lib 1, A Find a Lead mission without an Intel Package is a UFO.

I don't think there were any other choices if there was not an "Intel Package" listed as a reward.

**Comment by pledbrook** [comment]
They did deliberately hide Liberation 1, but those in the know pretty much knew if it was Lib 1 or possibly UFO detection. I don't know why it was done this way. I don't think it adds much strategy, particularly for experienced players, but it does make it harder for newcomers to get into the mod. This change was done explicitly to make the start of the Liberation chain clearer.
