### ISSUE TITLE
Disable the Lost and Abandoned mission

### ISSUE THREAD

**Issue by Favid** [long-war-2/lwotc#521]
Toggling the Lost and Abandoned mission on will result in LWOTC not working properly. Though this is mentioned in the setup guides, many players don't read them and will enable the mission, not realizing that their game will eventually stop working. To prevent this, we should prevent the player from toggling the mission on.

UIShellNarrativeContent.BuildMenu() handles creating the checkbox option in the new campaign screens. This will require a Highlander change to let mods force disable the checkbox. Need to figure out exactly how to do this. An ideal way would be for the Highlander to emit an event when building the checkbox, and a mod can listen to the event and pass in a value to make the Highlander disable the checkbox. Can mods listen for events in the main menu?

**Comment by Favid** [comment]
Something similar to this Highlander issue may work here: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/148

**Comment by pledbrook** [comment]
Thanks, I was planning to raise this issue myself today. Disabling the option is obviously the correct solution. We should disable the Precision Explosives second wave option as well.

Note that the Covert Infiltration mod has already [implemented this](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/master/CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_CampaignStartMenu.uc).

**Comment by Favid** [comment]
Should we also prevent the The Nest and The Lost Towers from being turned on? This was the case in LW2.
