### ISSUE TITLE
Soldier respec time does not match LW2

### ISSUE THREAD

**Issue by Favid** [long-war-2/lwotc#522]
In LW2, the time needed to respec soldiers was (rank * difficulty setting), instead of a flat 5 days. Changing this will likely require a Highlander hook.

**Comment by pledbrook** [comment]
This made use of a custom `SoldierRespecced` event. The code is currently in `XComGameState_LWListenerManager`.

**Comment by pledbrook** [comment]
Depends on [highlander #624](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/624).
