### ISSUE TITLE
Getting two hack resource rewards of the same type only gives you one

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#523]
On the same mission:

Hack lamp post for small alloy cache

Hack cell door for small alloy cache

Even if you succeed at both, you will only get 10 alloys. Also applies to supply cache of both sizes

**Comment by pledbrook** [comment]
If you have an English-language save file that reproduces the problem, that would be really helpful.

**Comment by TheReigningKing** [comment]
This was a bug in LW2 as well.

**Comment by allenhu0912** [comment]
[save_AUTOSAVE- Campaign 72, Mission 38, Turn 8.zip](https://github.com/long-war-2/lwotc/files/3613760/save_AUTOSAVE-.Campaign.72.Mission.38.Turn.8.zip)

When you hack the door, regardless of whether or not you choose small cache of alien alloys, you will always get 10 when the mission ends. Also, I am pretty sure this bug did not exist in LW2, as I have memories of getting 20 alloys out of a single mission

**Comment by ansabalirai** [comment]
I can confirm that this exists in LW2 (and probably in base game too, but much less likely to occur anyway)

**Comment by Clibanarius** [comment]
This is a base-game bug, sadly. Never saw anyone fix that bug with a mod or anything.

**Comment by copyrite** [comment]
Closing as a base game bug. https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/1190
