### ISSUE TITLE
I can build a Workshop even though I've used up all my power

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#531]
![20190915192818_1](https://user-images.githubusercontent.com/54481962/64929082-3ce05080-d7ef-11e9-8e9a-402edf6048aa.jpg)

**Comment by ansabalirai** [comment]
Is it because technically a workshop actually gives you +1 power (as in the screenshot)? Not sure if this is  vanilla or LW2 behavior though

**Comment by allenhu0912** [comment]
I think you're right, and I've never thought of that before. But I'm also not sure whether it gave or consumed power in LW2. I just assumed it cost 1 power

**Comment by pledbrook** [comment]
Workshop provides 1 Power, hence it can always be built if you have enough supplies and space.
