### ISSUE TITLE
Technical can't equip Gauntlet (or any secondary)

### ISSUE THREAD

**Issue by Witt-Github** [long-war-2/lwotc#532]
My freshly promoted technical can't equip any secondary weapon (they're all red and say "Can't Equip") including the Gauntlet. Makes her pretty useless, I suspect. 

Am I missing a mod? Do I have a mod that might be causing this? 

I'm using several mods; only ones I can imagine might cause this could include: 

[WotC] Weapon Fixes
[WotC] Open Class Weapon Restrictions
[WotC] LW2 Secondary Weapons

If it's not one of these, I can provide a full list (but it's long). 

Thoughts? Image attached.

- Witt

![20190915192455_1](https://user-images.githubusercontent.com/55356470/64931979-c3e1f880-d7f0-11e9-853a-99f398c9bdd8.jpg)

**Comment by shiremct** [comment]
I don't think you are supposed to use LW2 Secondaries with this mod. It contains its own, slightly different versions of the items, abilities, and effects from the LW2 Secondaries standalone built in.

**Comment by ToastedAmphibian** [comment]
Or a secondary top...

**Comment by pledbrook** [comment]
LW2 Secondaries almost certainly conflicts. The others may or may not cause problems. Don't know.

**Comment by Witt-Github** [comment]
Perfect, thanks guys. I'll remove it and see what happens.

**Comment by murdernator** [comment]
Was this issue ever resolved OP? I'm having a similar issue with equipping secondaries

**Comment by Witt-Github** [comment]
Yeah, for me removing the LW2 Secondaries mod did the trick. What other mods are you using? Gotta be a mod conflict.
