### ISSUE TITLE
chosen freezing bug

### ISSUE THREAD

**Issue by rapiel104** [long-war-2/lwotc#535]
![20190916183229_1](https://user-images.githubusercontent.com/55390995/64955505-5bb01700-d8c3-11e9-892b-d4f8d34f4ec4.jpg)

I can't play game after encounting first warlock battle. What can I do for it?
[freezing save.zip](https://github.com/long-war-2/lwotc/files/3616346/freezing.save.zip)

**Comment by rapiel104** [comment]
I want to play game with chosen. Anyone meeting chosen help me please.

**Comment by nightmaRok** [comment]
First of all your save in some strange language, i cant load it for test because of language. Try to play on english language, if you want to some one can load your save. Problem can be in other mods or wrong installation, try read starter guide, its in archive with LWotc.

**Comment by pledbrook** [comment]
Did you enable Lost and Abandoned when you started the campaign?

**Comment by TheSaneWonko** [comment]
Seeing the same. I started a new campaign with Beta 2, so Lost and Abandoned should be disabled. It was still checked in the campaign creation screen, but was greyed out and thus not changeable. I'm using most of the mods in the steam collection "[LWOTC] Suggested Mods for Beta 2.0". Just encountered the first Chosen, and if I enter the Geoscape after return, the game zooms to the Chosen's location and freezes there. Time is still running, though. Just can't leave the map anymore.
[save_strategic_1.zip](https://github.com/long-war-2/lwotc/files/3941003/save_strategic_1.zip)

**Comment by copyrite** [comment]
Closed as old and L&A being a plausible explanation.
