### ISSUE TITLE
Bug: Haywire protocol seems to have no cooldown

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#541]
I am not sure if others have come across this issue, but for me, haywire does not seem to have a cooldown anymore. Pretty sure this is not intended behavior.

I will share save game once I get on my PC.

**Comment by aturaki** [comment]
@ansabalirai I noticied the same thing but then realized that it may be an old bug (LW2 or xcom2, no idea).  Basically, if u time it correctly and hit ESC or cancel after the hack has been initiated (but not visually completed), the game goes ahead with the hack, but registers that no hack attempt has been made.  I am pretty sure this is a xcom2 vanilla bug.

**Comment by pledbrook** [comment]
I suspect this is due to an assertion that fails. If you try to break out of the hacking animation early with a debug version of the mod, the game crashes. But assertions don't crash the game when compiled with the `-final_release` flag, they just cause issues. Like this one, probably.

**Comment by wdanny69** [comment]
this issue is very old and haywire should have proper cooldown now

if it still occurs please provide a save if reproducible, a modlist and as much details about the set up leading to the bug
