### ISSUE TITLE
 Napalm x does not work properly

### ISSUE THREAD

**Issue by jth1324** [long-war-2/lwotc#543]
This is a serious problem, like failing to use a tree of technologists.

**Comment by nightmaRok** [comment]
If you find some bugs, or not working properly stuff, give save file for test. I try test by my self, as i understand napalm-x does not disorient or panic enemyes, right?
[save_Napalm-x_test_1.zip](https://github.com/long-war-2/lwotc/files/3619826/save_Napalm-x_test_1.zip)

**Comment by pledbrook** [comment]
Are you saying that you have used the flamethrower many times and it has never panicked an enemy?

Thanks for the save @nightmaRok.

**Comment by nightmaRok** [comment]
I try use it 6 times, all time no effect, and on engineer always icon Immune

![003](https://user-images.githubusercontent.com/51829747/65045082-d4b47a80-d966-11e9-93fb-35aa4bce31d9.jpg)
