### ISSUE TITLE
The Smart Macrophages skill in the skirmisher skil will not recover HP 1 from injuries after combat

### ISSUE THREAD

**Issue by jth1324** [long-war-2/lwotc#544]
With Specialist's Field Surgeon, you must recover 2 HP after battle but only 1

**Comment by nightmaRok** [comment]
Dj you have Save file to see it and try test?

**Comment by pledbrook** [comment]
I don't think Smart Macrophages works with Field Surgeon. Do you have evidence it should?

**Comment by jth1324** [comment]
I tried the same condition with the console. The same result. Still, HP recovered by 1.

![1](https://user-images.githubusercontent.com/55336603/65049274-74422f00-d9a0-11e9-8f78-ab3680745395.png)

![2](https://user-images.githubusercontent.com/55336603/65049304-7f955a80-d9a0-11e9-85d9-470f91e2de33.png)

**Comment by pledbrook** [comment]
I just tested this and it works fine with Field Surgeon. I had the Skirmisher take 3 damage and they had only lost 1 HP after the mission.

Was your Skirmisher bleeding out at any point?

**Comment by jth1324** [comment]
Skirmishers have never been bleeding. I retested, but still with the same results. Here's the save file that the console also retested.

[save_IRONMAN- Campaign 73.zip](https://github.com/long-war-2/lwotc/files/3624030/save_IRONMAN-.Campaign.73.zip)

**Comment by pledbrook** [comment]
That save file crashes when I load it. Sorry.

**Comment by wdanny69** [comment]
this is now fixed https://github.com/long-war-2/lwotc/commit/47e158fc1f6e86173212fe674bada1d6fbd5e9b5
