### ISSUE TITLE
The Smoker perk gives 2 smokes instead of one, starting from the second mission after obtaining the perk

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#547]
![20190916230645_1](https://user-images.githubusercontent.com/54481962/65010802-041fa480-d8df-11e9-8340-42fbe373f257.jpg)

**Comment by nightmaRok** [comment]
Do you have save file?

**Comment by allenhu0912** [comment]
[save_Save 62_1.zip](https://github.com/long-war-2/lwotc/files/3623726/save_Save.62_1.zip)
Check out the Shinobi, who has Smoker.

**Comment by allenhu0912** [comment]
OK, this is odd. It appears that the smoker perk is actually stuffing smokes into my soldier's inventory. Am 1000% sure this is a bug, as this happened on both a gunner and a shinobi, and I never give shinobis smokes

**Comment by nightmaRok** [comment]
I load your save file, use console *endbattle*, and after mission your shinobi and gunner have additional smoke in inventory.

![smoker_01](https://user-images.githubusercontent.com/51829747/65128409-22ca8c00-da02-11e9-9894-f000575d6447.jpg)
![smoker_02](https://user-images.githubusercontent.com/51829747/65128410-23632280-da02-11e9-933a-cd0e1011788b.jpg)

I removed smoke and send shinobi on mission, he have 1 smoke on mission

![smoker_00](https://user-images.githubusercontent.com/51829747/65128607-7210bc80-da02-11e9-8a22-225a14d67554.jpg)

**Comment by nightmaRok** [comment]
I test it on assault, no additional smoke on mission

[save_Test_smoker_1.zip](https://github.com/long-war-2/lwotc/files/3625221/save_Test_smoker_1.zip)

**Comment by pledbrook** [comment]
@allenhu0912 Did you start the campaign pre-beta? And if so, do you remember if the soldier acquired Smoker before you moved to the beta (if you moved to the beta)?

**Comment by nightmaRok** [comment]
Test it more, send soldier at 5 misssion in a row, still 1 smoke from perk

**Comment by allenhu0912** [comment]
> @allenhu0912 Did you start the campaign pre-beta? And if so, do you remember if the soldier acquired Smoker before you moved to the beta (if you moved to the beta)?

No, this was the beta release

**Comment by TheReigningKing** [comment]
[save_DenseSmoke.zip](https://github.com/long-war-2/lwotc/files/3628812/save_DenseSmoke.zip)
I ran into the same issue. This is the beta release. I have 3 smoke grenades.  This is also applying to the Flashbanger perk too.
My grenadier has 9 grenades total (Doesn't have Full Kit yet)

**Comment by allenhu0912** [comment]
Aha, I manged to catch this bug red-handed.
![20190918203749_1](https://user-images.githubusercontent.com/54481962/65200356-75cd2f00-da54-11e9-8451-9a0476bdb305.jpg)

You can see two smokes during the mission...

![20190918203832_1](https://user-images.githubusercontent.com/54481962/65200361-7e256a00-da54-11e9-9289-9b7afc01394d.jpg)

... but upon inspection afterwards, he is not carrying a smoke in his inventory.
[save_AUTOSAVE- Campaign 72, Mission 67, Turn 9.zip](https://github.com/long-war-2/lwotc/files/3628848/save_AUTOSAVE-.Campaign.72.Mission.67.Turn.9.zip)

**Comment by nightmaRok** [comment]
@pledbrook can confirm, i test TheReigningKing save, granadier have 2 perks defense smoke and flash, on mission he have a lot of additional grenades
[save_Grenadier_defensesmoke_flash_perks_bug.zip](https://github.com/long-war-2/lwotc/files/3630149/save_Grenadier_defensesmoke_flash_perks_bug.zip)

![001](https://user-images.githubusercontent.com/51829747/65226253-398ae480-dacf-11e9-998b-b890bd34a7a2.JPG)
![002](https://user-images.githubusercontent.com/51829747/65226254-398ae480-dacf-11e9-9b1e-e7b3f690a057.JPG)
![003](https://user-images.githubusercontent.com/51829747/65226256-3a237b00-dacf-11e9-9197-2f336509e8f5.JPG)
![004](https://user-images.githubusercontent.com/51829747/65226257-3a237b00-dacf-11e9-889b-7fb30a6b7b4d.JPG)

**Comment by nightmaRok** [comment]
@pledbrook I really in confuse, i tryhard and reprduse same perks for tests, when i use TheReigningKing save then use console RebuildSelectedSoldiersClass and roll same perks, send rerolled soldier on mission, same things with additional grenade. But!!!!! When i start new clear compaign and send soldier with rolled same perks on mission its all fine.
[save_RebuildSoldier_test_grenadier_1.zip](https://github.com/long-war-2/lwotc/files/3630292/save_RebuildSoldier_test_grenadier_1.zip)

![001](https://user-images.githubusercontent.com/51829747/65228997-27f80b80-dad4-11e9-9687-5cbd0da94228.JPG)
![002](https://user-images.githubusercontent.com/51829747/65228999-2890a200-dad4-11e9-9bb3-7942dcc8f4e3.JPG)
![003](https://user-images.githubusercontent.com/51829747/65229000-2890a200-dad4-11e9-8f61-5cc01a0a9506.JPG)

**Comment by allenhu0912** [comment]
It doesn't happen on the first mission, or maybe it's not guaranteed. It worked fine for me on first mission after picking the perk, but started giving me the extra on later missions

**Comment by wdanny69** [comment]
this is an old issue and may have been fixed now, unable to reproduce

if it still occurs please provide a save (ideally reproducible) a mod list and as much detail leading up to the issue
