### ISSUE TITLE
Small skill description issues

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#549]
Templar: Changes to Pillar regarding usage is not reflected on it's info screen when promoting.

Skirmisher: Justice claims to end your turn (on the tool-tip for the button to trigger the ability. It does not end your turn, just uses 1 action, even against a non flanked enemy. Pulling an enemy too you, then shooting him, then shooting him again thanks to hit and run is thus possible. Not complaining, exactly, just saying the info should be there to let people know that.

Skirmisher: Body Shield promotion screen information does not give any information about usage: Type of action, limited uses, cool down, etc. Would be helpful to know when deciding to take it or not.

Specialist: Field Surgeon claims that downed and stabilized enemies do not gain a bonus from it. My downed Templar had 2 health in the post action screen, so I am guessing that surgeon is triggering when it shouldn't.

**Comment by nightmaRok** [comment]
You can see now if your abilities turn ending or not, about Body Shield in LW2 info said same https://www.ufopaedia.org/index.php/Equipment_(LW2)#Portable_Equipment without turn cooldown\free action\limited action... so same like LW2 settings, more info only in battle

![001](https://user-images.githubusercontent.com/51829747/65026954-34e4f580-d942-11e9-8a2f-ec629689a81e.JPG)

![002](https://user-images.githubusercontent.com/51829747/65027773-9bb6de80-d943-11e9-8cfa-2a632a63314d.jpg)

**Comment by ToastedAmphibian** [comment]
Justice: Check the tooltip for Justice, the thing you have opened for body shield. Says "Ends turn", at least on mine.

Body Shield: Would it be hard to add that information to the popup on the promotion screen? Call it a feature request if that helps. Vague PCS descriptions are annoying, Vague SKILL DESCRIPTIONS much more so.

**Comment by nightmaRok** [comment]
I dont know, i am not a dev =) just try to help when i can, just answer few questions. On github now 240 opened issues, maybe Peter or Joey can answer you.

**Comment by pledbrook** [comment]
For text descriptions, look in the [_LongWarOfTheChosen/Localization/*.int_](https://github.com/long-war-2/lwotc/tree/master/LongWarOfTheChosen/Localization) files. We'd be happy to accept updates to those, which you can do through the GitHub UI. You would need to fork the repo first and then edit the files in place in your fork.

**Comment by nightmaRok** [comment]
@pledbrook I also do this changes: change Grapple 3 turn cooldown (was -1), add cost one AP and change Justice and Wraith on 4 turn cooldown (was 3), add no cost an action and 2 turn cooldown on Body Shield. Its all for now, dont do only Templar pillar from this issue

![Skirmisher_bodyshield_01](https://user-images.githubusercontent.com/51829747/65068849-1eff2100-d992-11e9-8c8f-f29ede2240e8.jpg)
![Skirmisher_justice_01](https://user-images.githubusercontent.com/51829747/65068851-1eff2100-d992-11e9-9f7f-60d1e65b86cb.jpg)
![Skirmisher_wrath_01](https://user-images.githubusercontent.com/51829747/65068853-1f97b780-d992-11e9-94fd-bfdde9b55d2d.jpg)
![Skirmisher_grapple_01](https://user-images.githubusercontent.com/51829747/65068854-1f97b780-d992-11e9-9cd6-fe2e29f47094.jpg)

**Comment by pledbrook** [comment]
Assuming all those things are correct (can't confirm myself) looks good!

@ToastedAmphibian Field Surgeon shouldn't work on bleeding-out soldiers. Probably shouldn't work on stabilised either, but not sure. Would you mind raising that as a separate issue?

**Comment by nightmaRok** [comment]
@pledbrook check my changes to Templar Pillar, if its Ok i do pull request for this

![Templar_pillar_01](https://user-images.githubusercontent.com/51829747/65136081-aa6ac780-da0f-11e9-8518-fd20cc44498c.JPG)

**Comment by pledbrook** [comment]
Yup, that looks good to me, although would be good to check these changes with martox, who has better knowledge of the actual behaviour and numbers.

**Comment by nightmaRok** [comment]
Before write this, i chek it, can give you a save for tests
[save_Templar_LWotc_mission.zip](https://github.com/long-war-2/lwotc/files/3625714/save_Templar_LWotc_mission.zip)

**Comment by ToastedAmphibian** [comment]
Body Shield: **Does** not cost an action.
Justice/Wrath: **Costs** one action point.
Pillar: Pillar has **a** 1 turn cooldown.
