### ISSUE TITLE
[Balance] Tactical Map AI Jobs

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#552]
I have a very strong feeling that AI jobs are not working correctly. As shown here, I have 3 guard pods rather than any other type of AI jobs.

I have on other maps - reported on Issue #479 - where AI pods don't crash the objective after it has been activated.

On HQ Assaults, I have seen 90% of the pods either at the very front of the map (immediately next to your starting buildings), or standing next to the Boss pod at the very back of the map.

I'll try to get some saves for the above two issues as I find them in the future.

[save_3 guard pods.zip](https://github.com/long-war-2/lwotc/files/3621492/save_3.guard.pods.zip)
![3GuardPods](https://user-images.githubusercontent.com/54255029/65045532-95fdd080-d924-11e9-9836-1cedb04f611a.png)

**Comment by allenhu0912** [comment]
I can concur that pod jobs are kind of busted on HQ assaults. There's a huge advent "rainbow" pod right there in the very first building up front. In LW2 this building would always be empty, aside from a few turrets on top.

**Comment by pledbrook** [comment]
It's important for diagnosis not to confuse where pods spawn and their jobs. Pods spawn in what are known as encounter zones. It seems that sometimes those encounter zones don't actually match the corresponding specification in the configuration. My hunch is that this only occurs on maps with large numbers of enemies, which the HQ Assault is by definition. But if you underinfiltrate missions heavily, you may see the same issue.

Pod jobs are basically things like patrolling, or guarding (although "guard" pods typically patrol too - they just patrol in a small area around the objective).

**Comment by ansabalirai** [comment]
What would help is using 'lwdebugpodjobs' to see how the pod jobs change as you encounter pods and complete objectives. Regarding the HQ, even in LW2, you could encounter pods either very close to your starting position or near the command pod in the back. I am not sure if there is really an issue with that

**Comment by pledbrook** [comment]
Closing as this seems more to do with pod distribution on the HQ, which depends on which schedule is picked. I may try to add some more schedules to the HQ assault for more variety.
