### ISSUE TITLE
Basic Research infinitely inspired

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#553]
[save_Save 111.zip](https://github.com/long-war-2/lwotc/files/3621860/save_Save.111.zip)
I researched basic research first, got an inspiration for another basic research, did that too.
Since then, I've always had the option to do another inspired basic research.

Gut feeling is the bug is due to the fact that basic engineering/research is a repeatable so it doesn't go back to its original after it's complete once.

**Comment by pledbrook** [comment]
While not exactly a duplicate, this will be fixed with #91 .
