### ISSUE TITLE
Mind Control doesn't state how long it will last in F1

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#554]
[save_MindControl.zip](https://github.com/long-war-2/lwotc/files/3622610/save_MindControl.zip)

Using F1 will not show how long the Naga is MC'd for.  I think this also applies to hacked units where it doesn't say how long it will last for.

You can see it if you hover over the down red arrows in the bottom left corner

**Comment by pledbrook** [comment]
Is this just behaviour of Yet Another F1 and not LWOTC?

**Comment by TheReigningKing** [comment]
LW2 showed time limits on MC and hacks, so I'm assuming the issue is with LWOTC.
I am using Yet Another F1 so it may just be that mod that's not capturing it correctly.

**Comment by pledbrook** [comment]
Are you sure that LW2 showed the durations and it wasn't just another mod you were using with LW2? I know that Perfect Information was showing the duration of buffs and debuffs. I just can't find where original LW2 would be doing it.

**Comment by TheReigningKing** [comment]
I've been looking around the patch notes for LW2 and I can't find it either. I was pretty sure it was a recent addition to LW2 in like 1.4/1.5. It may have just been compatibility with PI.

The problem I'm running into is that Shutdown units don't have turn timers on them anywhere. If I MC a unit, I can click on it, and then view debuffs, but for SD units there's no way for me to tell how many turns it'll be shutdown for. (or panic'd, or burning, or disoriented, etc).

I'm not sure if this is a UI thing that another mod should be in charge of handling or LWotC should do. Feel free to close if you think another mod should do this.

**Comment by pledbrook** [comment]
Try [Show More Buff Details](https://steamcommunity.com/sharedfiles/filedetails/?id=709499969). But this is also a bug because I shouldn't really have the Perfect Information tooltips showing.

**Comment by pledbrook** [comment]
PI tooltips removed in [this commit](https://github.com/long-war-2/lwotc/commit/907723f07127251b3a51a7761e09cf7b1b1a40d4).
