### ISSUE TITLE
I sometimes have 75 supplies in place of an intel package for mission rewards

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#555]
I thought giving 75 supplies was a temporary measure in a LW2 patch where intel packages were busted?

**Comment by pledbrook** [comment]
Save? Screenshot? I've never seen this. Unless you mean you had an Point Of Interest reward that gave supplies.

**Comment by allenhu0912** [comment]
Will take a screenshot next time. Basically instead of an intel package, I instantly received 75 supplies for escorting a scientist to evac

**Comment by pledbrook** [comment]
So the mission had an Intel Package as a reward, but instead of a POI you got supplies? And you didn't get that from a hack?

**Comment by allenhu0912** [comment]
No. On the geoscape, when I am choosing the mission to begin infiltrating, rewards look like: Amy King (Scientist), 75 Supplies. Or something like that. Usually you would expect something like Amy King (Scientist), Intel Package

**Comment by allenhu0912** [comment]
![20190917222715_1](https://user-images.githubusercontent.com/54481962/65118522-2ede2b80-d9b9-11e9-97d9-6a8eaecdc791.jpg)
Not quite the same, but close. IIRC, supplies were never a reward for taking in dark vip alive in LW2

**Comment by allenhu0912** [comment]
Never mind, found what I was talking about
![20190915183021_1](https://user-images.githubusercontent.com/54481962/65118863-985e3a00-d9b9-11e9-9ddb-1d4a3f83095b.jpg)

**Comment by pledbrook** [comment]
This is the code:
```

	if (MissionFamily == 'Neutralize_LW')
	{
		if (CanAddPOI())
		{
			RewardArray[0] = 'Reward_POI_LW'; // this will only be granted if captured
			RewardArray[1] = 'Reward_Dummy_POI'; // The first POI rewarded on any mission doesn't display in rewards, so this corrects for that
			RewardArray[2] = 'Reward_Intel';
		}
		else
		{
			RewardArray[0] = 'Reward_Supplies';
			RewardArray[1] = 'Reward_Intel';
		}
	}
```

It's similar for the rescue mission you were talking about. My guess is that `CanAddPOI()` is no longer returning `true` for you for some reason. Why that is, I don't know. If you have a save file from shortly before that mission spawned, I may be able to find out.

**Comment by allenhu0912** [comment]
This is still occurring continuously on the current version for me. I don't know what causes this; most of my campaigns don't have this. But in my current one it pops up all the time.

**Comment by wdanny69** [comment]
this is an old issue and we have not seen much reports on this recently.

if it still occurs, please provide a save if reproducible, a mod list and as much details leading up to the issue
