### ISSUE TITLE
Advent Turret is shooting my troops when it hasn't been activated yet

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#558]
The save is my turn after the Advent turret shot my gunner in the back of my formation.  The turret is by the objective.

The turret is nowhere close to activating (didn't even know it existed), and it has started shooting.

[save_TurretActive.zip](https://github.com/long-war-2/lwotc/files/3624314/save_TurretActive.zip)

**Comment by nightmaRok** [comment]
I load your save, and restartlevel, turret dont shot, so how you activated it i dont know. You can load my save to see this, or use console command *restartlevel*, turret not active.

[save_TurretActive_1.zip](https://github.com/long-war-2/lwotc/files/3625005/save_TurretActive_1.zip)

**Comment by Anxoczt** [comment]
Sometimes it happened to me, but i thought it was because turrets have squadsight and will shoot at me even if i havent triggered it yet.

**Comment by TheReigningKing** [comment]
@nightmaRok What happens if you restartlevel?  The turret only started shooting after I activated the first pod (which did not include the turret).

**Comment by nightmaRok** [comment]
its restart your mission, you give save when turret already activated, so how can some one understand you activate turret or not, so i do it to see does turret do shot when i revealed

**Comment by TheReigningKing** [comment]
Well I expected you to continue from where the save game was, not restart the level.
If you walk forward from my save, you'll get the turret activation cutscene which means it wasn't activated normally

**Comment by nightmaRok** [comment]
Yeap, you right, if i skip turn turret do shots, I dont know how turret was activate but this massege makes me confuse, maybe Peter have some time and can answer you

![turret](https://user-images.githubusercontent.com/51829747/65170553-9ba50480-da51-11e9-85cd-82e168cc7fe2.JPG)

**Comment by pledbrook** [comment]
This may be related to a bug I saw on one of my missions where an unactivated Naja shot my guys. There is definitely some weird behaviour in the mod right now. I'll be looking at my own save file with the Naja, but I'll take a look at this one too in case it helps identify the cause.

**Comment by Clibanarius** [comment]
Squadsight Turrets is a thing in LW2, configurable in XcomLW_Overhaul.ini

EARLY_TURRET_SQUADSIGHT=TRUE
MID_TURRET_SQUADSIGHT=TRUE
LATE_TURRET_SQUADSIGHT=TRUE

**Comment by TheReigningKing** [comment]
@Clibanarius Turrets have squadsight, but they don't activate through squadsight.  You have to activate them first, and then squadsight kicks in.

**Comment by Clibanarius** [comment]
Here I thought I was helping, haha. Yeah, that makes sense to me, as well as it being a bug with having reloaded the mission. There's an awful lot of bugs that pop up with a reload (like the ADVENT starting in phantom new locations, but being targetable on their original tiles). Doh!

**Comment by wdanny69** [comment]
this issue may have been fixed https://github.com/long-war-2/lwotc/commit/662aab58ebfb513094324084608332db6ef63779

if it still occurs please provide a save if reproducible, a modlist and as much details about the set up leading to the bug
