### ISSUE TITLE
Hard Target still missing flavor text on newest beta version, Sep 17

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#559]
![20190917222632_1](https://user-images.githubusercontent.com/54481962/65118764-7795e480-d9b9-11e9-8113-a63f489b5b69.jpg)
IIRC it had no flavor text in LW2 either

**Comment by Clibanarius** [comment]
Yeah, that's just what it was in LW2. Might just be time to ignore that unless you wanna write some flavor text up in here and someone can splice it in.
