### ISSUE TITLE
Pods don't seem to enter yellow alert

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#56]
This may be because the base game is overriding the pod behaviour. If that's the case, we will need to enable the `ShouldMoveToIntercept` event handler and of course add the event trigger to the community highlander if that's acceptable.

The event trigger is in `XComGameState_AIGroup`.

**Comment by pledbrook** [comment]
Also, see what the "yellow alert gameplay" mod does to make sure the highlander supports what it needs (if it wants to switch to the highlander).

**Comment by ansabalirai** [comment]
I used the mod you mentioned for part of my campaign and it seems to work fine, in that, I do see enemy pods move around as if they are on alert upon hearing gunfire, seeing corpses and take shorts upon finding xcom on their turn. Need more in game testing to see if it is indeed working identical to LW2.

**Comment by ansabalirai** [comment]
@pledbrook I am not sure if you were able to look into this? Also, not sure if anyone else has tried this out to find out if we can rely on this to incorporate yellow alert mechanic as is or more work needs to be done. Ofc even then, mission based alert (e.g. raids, haven assaults, retals) would still require changes such that all pods are alerted from turn 1 if we end up using this mod

**Comment by pledbrook** [comment]
No, sorry. Other priorities.

**Comment by ansabalirai** [comment]
No worries. I will keep using the yellow alert mod with alpha-2 and see if it behaves exactly as in LW2, especially on retaliations.

**Comment by ansabalirai** [comment]
Not sure if people have done any raids with the new alpha yet? I am curious to see how the AI behaves in those missions, i.e. if the pods in raids are just acting as in vanilla or do they exhibit LW2 behavior? I am personally playing with the yellow alert mod separately, so I cannot be sure.

**Comment by pledbrook** [comment]
These are the things that need to be done:

 - [x] Disable vanilla patrolling
 - [ ] Hook into the 'ScamperBegin' event to refund reflex action points
 - [ ] Implement sound-based activations for pods (i.e. XCOM noises putting pods on yellow alert)
