### ISSUE TITLE
Rend not displaying correct values on destructible objects

### ISSUE THREAD

**Issue by scmantikor** [long-war-2/lwotc#561]
![image](https://user-images.githubusercontent.com/55502272/65162888-999c6f00-da6c-11e9-820e-6d17249101ce.png)

Rend is displaying 4-5 which doesnt account for the 2 focus. The actual rend hit for 6. Visual bug

**Comment by nightmaRok** [comment]
Give please save file for tests

**Comment by Favid** [comment]
I don't have a save file, but I have also seen this happen with Fleche (the movement-based damage bonus is not included in the preview)

**Comment by copyrite** [comment]
Closing as Rend damage no longer scales with Focus.
