### ISSUE TITLE
Beta: Mission Timers not pausing when chosen appear

### ISSUE THREAD

**Issue by SydenInsomniac** [long-war-2/lwotc#564]
As I understand it mission timers are supposed to suspend when a chosen appears because dealing with them takes a lot of time.  In the beta I'm not seeing this happening.  

Save attached shows attacking and chosen appearance will still cause the mission timer to count down like nothing happened.
[Save.zip](https://github.com/long-war-2/lwotc/files/3628440/Save.zip)

**Comment by ansabalirai** [comment]
They have to be active, i.e. in LoS of xcom for the timer to freeze

**Comment by SydenInsomniac** [comment]
Yup sorry I'm an idiot
