### ISSUE TITLE
Laboratory Expansion Text Descriptions Missing

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#565]
![LabText](https://user-images.githubusercontent.com/54255029/65200651-4666f400-da4d-11e9-8339-601740a440d5.png)
Picture should be self-explanatory

**Comment by wdanny69** [comment]
this does not appear to be an issue any longer

if it still occurs please provide a save if reproducible, a modlist and as much details about the set up leading to the bug
