### ISSUE TITLE
One guy is hogging both of the psi lab tubes

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#566]
![20190918230048_1](https://user-images.githubusercontent.com/54481962/65210333-d36b7680-da68-11e9-844d-0d8a65e86345.jpg)

[save_AUTOSAVE- Campaign 72, Mission 69.zip](https://github.com/long-war-2/lwotc/files/3629157/save_AUTOSAVE-.Campaign.72.Mission.69.zip)

You can remove one of the Artyom's but not the other.

**Comment by Grobobobo** [comment]
Unable to reproduce.
