### ISSUE TITLE
Issues with Chosen Assassin?

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#567]
I'm not sure if these things are bugs or not, I don't have a save unfortunately. I assumed at the time it was working as intended, but now I am not so sure.

1: Ends Concealment
     Was on a smash n grab mission, about 70% infiltration with a pair of squadies. After the end of the first turn, The assassin show up on the far side of the map, does her little intro, and then my turn starts. Squad has somehow lost concealment.

2: Summoned Unit Loot
    Throw the evac flare, and after a few turns she makes her way over to the start point. She summons a trooper. One squadie kills the trooper while the other suppresses. The trooper drops loot.

3: Explosion damage
     On her turn she runs into the nearby shack. The one near the edge of the wilderness smash n grab map. Squadie shoots the propane tank on the building, and she takes damage from it.A lot of damage, leaving her at 1 health out of 22.  Her weakness is explosions, but that kind of tank typically does 6 damage. She had shields from the suppression shot missing, so I'm assuming the explosion did 24 damage in total. Should she be taking 4x damage?

**Comment by nightmaRok** [comment]
1. Consealed Start Requires 100% infiltration
![001](https://user-images.githubusercontent.com/51829747/65230348-61ca1180-dad6-11e9-82b5-bf7af5ca8880.JPG)
2. Yes, chosens summoned units drop loot.
3. Weakness to explosions.... one time in my run i kill her with oneshot reaper (weakness to reaper and explosions), so its might be true.
