### ISSUE TITLE
SNG spawning unreachable crates

### ISSUE THREAD

**Issue by scmantikor** [long-war-2/lwotc#568]
![image](https://user-images.githubusercontent.com/55502272/65253355-1858e100-db2d-11e9-9073-16d2807ab759.png)

attached save : [save.zip](https://github.com/long-war-2/lwotc/files/3631742/save.zip)

**Comment by nightmaRok** [comment]
Known bug, as i see maybe its will be fixed in next patch #501

**Comment by pledbrook** [comment]
No, this is a vanilla bug that is unlikely to be fixed. The Abandoned City map just has illegal spawn points for chests. I don't know how to fix it.

#501 is about where the enemy pods spawn on the map. They're a bit compressed and spawn fairly far from XCOM's spawn point.

**Comment by nightmaRok** [comment]
Oops.... I`m sorry I got it wrong

**Comment by Grobobobo** [comment]
This is a vanilla bug that we can't really do anything about.
