### ISSUE TITLE
Resistance Order Munitions Expert doesn't work

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#569]
[save_MunitionsExpert.zip](https://github.com/long-war-2/lwotc/files/3631768/save_MunitionsExpert.zip)
If you check I have the Munitions Expert Resistance Order active, but my ammo projects in the Proving Grounds are not completing instantly.

I re-ordered my Proving Grounds list, so that may be the issue along with new ammo added by LW2?

**Comment by pledbrook** [comment]
It only applies to the "Experimental Ammo" Proving Ground project. This resistance order needs to be disabled because all special ammo can be built instantly anyway.

**Comment by pledbrook** [comment]
Bomb Squad should be disabled as well, because it only works for the random grenade and heavy weapon projects, which LWOTC doesn't have.
