### ISSUE TITLE
Solder stat rewards are always set to 0 in covert ops

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#57]
It seems like all soldier rewards (e.g. +aim, hacking, dodge, etc.) are showing as +0 in covert ops. Might be some unwanted interaction happening somewhere...

**Comment by pledbrook** [comment]
Do you have a save file? Not critical, but will save me a bit of time.

**Comment by pledbrook** [comment]
Actually, I think I can use the save file from #59

**Comment by pledbrook** [comment]
You can fix this by adding the following lines below the other `+StatBoostTable` lines in the mod's `XComGameData.ini` config file:

```
+StatBoostTable=(PowerLevel=4, StatType=eStat_Mobility, MinBoost=1, MaxBoost=1)
+StatBoostTable=(PowerLevel=4, StatType=eStat_HP, MinBoost=1, MaxBoost=1)
+StatBoostTable=(PowerLevel=4, StatType=eStat_Will, MinBoost=3, MaxBoost=5)
+StatBoostTable=(PowerLevel=4, StatType=eStat_Offense, MinBoost=2, MaxBoost=4)
+StatBoostTable=(PowerLevel=4, StatType=eStat_PsiOffense, MinBoost=1, MaxBoost=2)
+StatBoostTable=(PowerLevel=4, StatType=eStat_Dodge, MinBoost=5, MaxBoost=10)
+StatBoostTable=(PowerLevel=4, StatType=eStat_Hacking, MinBoost=3, MaxBoost=5)
```

**Comment by ansabalirai** [comment]
Ok, thanks. I will check them when I get back to my PC and report. In the meantime, you can close this issue if needed.

**Comment by Tylon01** [comment]
I applied the fix to the ini as described. Assuming that I did not make any mistakes with my edit (thats always a good possibility :) ) . Stat bonus is working correctly within the first soldier assignment box but still showing as +0 in the second assignment box. Please see screenshots. 
![nobonus](https://user-images.githubusercontent.com/10909121/55919407-e7f73900-5bc3-11e9-8302-886decfe7e28.jpg)
![nobonus2](https://user-images.githubusercontent.com/10909121/55919409-eb8ac000-5bc3-11e9-9ee0-5c0cec166e14.jpg)

**Comment by pledbrook** [comment]
Do you have  a save file for that? Perhaps it's a different cause.

**Comment by Tylon01** [comment]
I don't have a save for this particular instance. Next covert that I get, I will post a save.

**Comment by Tylon01** [comment]
I will have to keep testing this as it does not always hold to be true. I had a covert op that had a positive value in the second box. This may be trait specific so I will keep this updated as I keep testing
