### ISSUE TITLE
Enemy pods spawning too close to start position

### ISSUE THREAD

**Issue by Winterwire** [long-war-2/lwotc#570]
![Starting position](https://user-images.githubusercontent.com/55554439/65267372-db67fc80-dae2-11e9-8bd7-3abfea3b04e7.jpg)

It was a 34-36 enemy supply raid, 24 of them spawned in vision of the starting position and two pods immediately patrolled into the starting area. 

I am guessing the map selected was too small for the number of enemies, although I have had similar problems on larger maps where pods spawn in vision of the starting zone and immediately patrol on top of the player..

**Comment by TheReigningKing** [comment]
I've had the same issue, but I was able to just power through it so no save.
I've only seen these scenarios on Supply Raids.

**Comment by nightmaRok** [comment]
Its normal thing for LW https://www.youtube.com/watch?v=XTqpVHgR-gs

**Comment by Grobobobo** [comment]
Working as intended.
