### ISSUE TITLE
Missing Space on Boost Infiltration Screen

### ISSUE THREAD

**Issue by Chaotic-Entropy** [long-war-2/lwotc#572]
I'm not saying it's unplayable, but it's close. Missing space between spend and the intel value e.g. "spend25"

![20190914115630_1](https://user-images.githubusercontent.com/55556991/65272769-a2964a80-db17-11e9-9e4e-ef7197b88cae.jpg)

**Comment by ansabalirai** [comment]
Haha, if we have gotten to this level of "bug" hunting, then I'd say the mod has reached a pretty stable state 🤣

**Comment by Chaotic-Entropy** [comment]
Line 435 of LW_Overhaul.int, if it helps, I don't know how to Git yet.

**Comment by nightmaRok** [comment]
I do pull request for this

![001](https://user-images.githubusercontent.com/51829747/65276765-214bb180-db31-11e9-9ac8-5ce43394e6f8.JPG)
