### ISSUE TITLE
Invisible faceless in security breach mission

### ISSUE THREAD

**Issue by Slivicon** [long-war-2/lwotc#577]
First security breach mission to send haven advisor (sharpshooter) and resistance fighters to attack faceless spy and advent. Faceless did not transform or trigger a transform cinematic, and appeared to be invisible. The faceless sound fx were working, though, and I was still able to target and kill the faceless and win the mission despite the faceless being invisible.

Here is the video: https://youtu.be/DRlBZKP5Y4k?t=343

In a subsequent rendezvous security breach mission, the faceless transformed and appeared fine, so whatever the cause, it did not persist.

**Comment by Grobobobo** [comment]
Unable to reproduce.
