### ISSUE TITLE
Can only Fleche point blank mind-controlled target, but not Slash

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#578]
![20190920221622_1](https://user-images.githubusercontent.com/54481962/65367925-414da480-dc07-11e9-86c9-47aaa699dfdb.jpg)

**Comment by BlackRose39** [comment]
I have seen this issue as well where you can only fleche the target, but not slash it. 100% of the time that it occurred to me was because of elevation differences. (One unit was on the truck, and the other on the ground next to her).

**Comment by LaksonVell** [comment]
This was also true for a hacked robotic unit for me today.
