### ISSUE TITLE
Map fails to fully draw its tiles

### ISSUE THREAD

**Issue by MagSigeasol** [long-war-2/lwotc#58]
Commenced Gatecrasher with no other mods.

Map failed to fully draw all tiles, meaning that advent was stuck on an island and another part of the map with no way to complete. Restarting mission did not resolve the issue.

[save_Bugged_Map.zip](https://github.com/pledbrook/lwotc/files/3050141/save_Bugged_Map.zip)

**Comment by pledbrook** [comment]
Just to keep a note of this, the plot is `Plot_SLM_Overpass_LgObj_10_LW`

**Comment by MagSigeasol** [comment]
Update: I undertook another two gatecrashers, both of which drew tiles correctly.

After both missions were completed successfully, the game crashed after the loading screen with the crew inside the avenger. I wonder if the former issue relates to a problem with my specific installation, so will attempt another mission on a different machine to see if I can replicate or otherwise if the crashing issue continues.

**Comment by pledbrook** [comment]
The map from the first mission you did definitely has a problem. I can reproduce, but I don't know what's causing the issue.

I haven't heard about anyone else's game crashing after Gatecrasher, so it could be an environmental issue. Do you have any other mods installed? I noticed you have Anarchy's Children enabled. That shouldn't be a problem, but you might want to try without it.

Another option you can try is to move the _Documents\My Games\XCOM2 War of the Chosen\XComGame\Config_ directory somewhere else temporarily and then start the game and try a new campaign. Old config can sometimes mess up LW2.

If you still have problems, would you mind attaching a copy of the log file: _Documents\My Games\XCOM2 War of the Chosen\XComGame\Logs\Launch.log_

**Comment by pledbrook** [comment]
BTW, you mod's directory name is misspelled (_LongWarOfTheChosne_ I think). I don't think it should be an issue after Gatecrasher, but it's probably worth fixing.

**Comment by pledbrook** [comment]
OK, so I'll probably solve this by simply removing the plot so it can't be picked.

**Comment by MagSigeasol** [comment]
Regarding the crash, I followed your instructions and the next run through worked without issue. Seems the config folder change solved that problem.

**Comment by Tylon01** [comment]
Here is another save that has a section of tiles not being properly rendered. Dont know if this is the same map issue or a different map that is causing this issue
[save_Tilesnotdisplay.zip](https://github.com/pledbrook/lwotc/files/3056616/save_Tilesnotdisplay.zip)

**Comment by pledbrook** [comment]
@Tylon01 That's a different map. The ADVENT HQ maps seem to have problems. For the record, this map is `Plot_ALB_AlienBase_01_LW`.

In case others find such maps, you can find out what plot (map) was loaded in _Documents\My Games\XCOM2 War of the Chosen\XComGame\Logs\Launch.log_. Just look for the last reference to `Plot_` (all plots are prefixed with that string).

**Comment by pledbrook** [comment]
So the problem with the overpass map is that the PCPs it was using for the overpass itself are no longer available. I think WOTC refactored them into smaller PCPs. I guess ideally the plot should use the new PCPs, but I'm going to try to restore the old PCPs and see whether that fixes the map.
