### ISSUE TITLE
Armor research occuring instantly

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#582]
![20190921124536_1](https://user-images.githubusercontent.com/54481962/65376477-48f46400-dc6e-11e9-96a6-1ed94697c83a.jpg)
[save_Save 77.zip](https://github.com/long-war-2/lwotc/files/3638884/save_Save.77.zip)

**Comment by TheReigningKing** [comment]
Do you have the continent bonus?

**Comment by allenhu0912** [comment]
I think I have the suit up resistance order, but that should only apply to proving ground projects

**Comment by pledbrook** [comment]
Are you sure this isn't LW2 behaviour? Because this is all vanilla WOTC. And that is armour research. So if anything, it's a vanilla bug.

**Comment by pledbrook** [comment]
I actually think this is fine. In vanilla, WAR Suit (Battlesuits) and the others are Proving Ground projects. It looks like they were moved to normal tech research for LW2. I think I'll leave this open, but only to have the description of Suit Up changed so it doesn't mention the Proving Ground.

**Comment by allenhu0912** [comment]
It feels broken. I instantly skipped some 20-30 days of research. In comparison, Ballistic Modeling only speeds weapon research by 15%

**Comment by pledbrook** [comment]
Fair point and I see that LW2 effectively disabled it along with Lock And Load and Fire When Ready.
