### ISSUE TITLE
Network tower hack bug

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#583]
After hacking network tower, you can hack any mec unit (i test it on drone or MEC), animation of hacking tower starts again and you get additional + 2 turns stun. Save files before hacking and after.
[save_network_tower_hack_bug_1.zip](https://github.com/long-war-2/lwotc/files/3639031/save_network_tower_hack_bug_1.zip)

![001](https://user-images.githubusercontent.com/51829747/65378546-82ef5580-dcc2-11e9-9139-00c8c52766c6.JPG)

**Comment by nightmaRok** [comment]
Save 01 after hacking loading much longer for me

**Comment by BlackRose39** [comment]
Perhaps the tower stun uses a different type of stun in the coding/script that makes it different from the regular hacking? We may have to check what the internal name of the effect was when the tower stun occurred.

Definitely worth checking this too for when a specialist hacks a tower (in cities) and see if the problem also happens too there for robotic units.

**Comment by pledbrook** [comment]
I'm pretty sure this must be a LW2 bug as well. Hack reward abilities are all treated the same in XCOM 2, being triggered by an event. So whenever that event is fired, the Network Tower hack reward kicks in again.

I somehow need to make the "stun all enemies" ability trigger once only. Perhaps I can give it a charge?
