### ISSUE TITLE
Panicked soldiers do shit other than hunker down

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#586]
Hey, this is something new that's come up after I started using jm001's latest build on the Discord, LongWarOfTheChosen.zip from 9/16, 6:54 AM. If panicked by a Sectoid, a soldier will frequently take a run off in some direction or shoot their weapon at random. This is a problem since panic behavior in LW2 is specifically supposed to be ONLY hunkering down on the initial panicked turn, no movement, no firing or throwing grenades or anything. Again, I hope this is just isolated to that one build.

**Comment by BlackRose39** [comment]
Yes, I have also been seeing advent/aliens taking shots at their own units after being panicked by insanity, then hunkering down afterwards. That behavior shouldn't be occurring in LW2 in the first place. I never saw it in LW2, but have seen it here in LWOTC builds.

Verify that the panic behavior in the ai files only selects hunker down as an action when panicked. (Might be worth checking other states too, such as berserk, shattered, etc.)

**Comment by Clibanarius** [comment]
This all seems to be fixable in the first lines of XcomAI.ini. Why and when the LW2 panic stuff got commented out, I have no idea. I'll have to get some confirmation that it's... supposed to be this way and all, but in the mean time, I'm uncommenting these:

+BehaviorRemovals="Panicked_FirstAction_Selector"
+BehaviorRemovals="Panicked_LastAction_Selector"
+BehaviorRemovals="PanickedAction"

**Comment by pledbrook** [comment]
Probably because I didn't think it was necessary as I hadn't ever seen them do anything other than hunker. Let me know how it goes with those lines uncommented. If all seems well, I'll make the change.

**Comment by pledbrook** [comment]
@Clibanarius Did the change make any difference?
