### ISSUE TITLE
Covert Action Requirements bug

### ISSUE THREAD

**Issue by Pi-Nal-Nizzre** [long-war-2/lwotc#59]
There seems to be a bug with the covert actions, specifically for the Reapers ( I have not played enough to see if it pops up for other factions, or if I can recreate the issue) The required soldier is grayed out, I assume because I do not have a soldier of the appropriate rank, but there is no rank requirement showing up on the opp itself.
I attached a second picture showing that I have a soldier available, and one that is above the rank of corporal.

Not sure if I have done this correctly, let me know if I need to do anything else!

[save_LW WotC Bug 1.zip](https://github.com/pledbrook/lwotc/files/3050142/save_LW.WotC.Bug.1.zip)

![1bug1](https://user-images.githubusercontent.com/49331045/55664727-e101ac80-57f8-11e9-95ed-9556f0bcc558.png)
![1bug2](https://user-images.githubusercontent.com/49331045/55664733-e65ef700-57f8-11e9-8a52-94df66fee9a9.png)

**Comment by pledbrook** [comment]
Thanks for the report and the save file. It looks like "Improve Combat Intelligence" has a special hidden requirement, which is that a soldier class needs to have a `bAllowAWCAbilities` value of `true` or 1 in order to be eligible. The LW classes don't yet have that config setting. This should work as soon as I add it.

**Comment by pledbrook** [comment]
You can fix this by adding the following line to each LW soldier class block in the mod's `XComClassData.ini` config file:
```
+bAllowAWCAbilities=true
```
For example, I put it just below the `+bCanHaveBonds=true` line for each soldier class.

So each block should start out like:
```
[LWS_Technical X2SoldierClassTemplate]
+bMultiplayerOnly=0
+ClassPoints=3
+IconImage="img:///UILibrary_LW_Overhaul.class_Technical"
+NumInForcedDeck=1
+NumInDeck=4
+bCanHaveBonds=true
+bAllowAWCAbilities=true
+BaseAbilityPointsPerPromotion=3
+KillAssistsPerKill=5
...
```
