### ISSUE TITLE
Psi soldier's Solace currently does not work against "Dazed" effect produced by Chosen

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#590]

**Comment by pledbrook** [comment]
What's it supposed to do? And why?

**Comment by allenhu0912** [comment]
Should remove the effect, just like stuns and disorients. It's blocked and/or removed by mind shield and templar's solace aura, so I don't see why the active ability shouldn't remove it.

**Comment by Grobobobo** [comment]
Fixed a while ago.

**Comment by ansabalirai** [comment]
Wouldn't it be a good idea to link the commit that fixes this when closing the issue

**Comment by Grobobobo** [comment]
Maybe, but I don't feel like digging through 6 month old commits to document one out of like 300+ stale issues. Besides, Daze is getting scrapped in the upcoming chosen update.
