### ISSUE TITLE
Killing a Spectre (who Shadowbound one of my men)produced a loot pile with 4 items

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#591]
[save_Save 85.zip](https://github.com/long-war-2/lwotc/files/3640359/save_Save.85.zip)

This is after the Spectre was killed, one of the loot piles has 4 items

**Comment by wdanny69** [comment]
this was because the vanilla loot tables were still being used

their loot table has now been adjusted like all other enemies 

https://github.com/long-war-2/lwotc/commit/0eb1dd496fda39fd81e05043b9aab59ca280a0a8
