### ISSUE TITLE
Firestorm not destroying cover

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#592]
Current behavior: basically a 360 degrees flamethrower

Expected behavior: Should pretty much vaporize any cover within radius, including any floors above you if you are in a building

**Comment by wdanny69** [comment]
firestorm now properly destroys cover and like the affected area 

fixed by https://github.com/long-war-2/lwotc/commit/282ff84316f27947be42f06a11f70217ccf0caaa
