### ISSUE TITLE
Shaken soldier recovering to full will almost instantly upon return to Avenger

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#594]
[save_AUTOSAVE- Campaign 72, Mission 103, Turn 6.zip](https://github.com/long-war-2/lwotc/files/3640491/save_AUTOSAVE-.Campaign.72.Mission.103.Turn.6.zip)

**Comment by pledbrook** [comment]
I think this has to do with borderline Shaken and some of the logic in the base game. Although even so, that's very weird. Will look into it.

**Comment by pledbrook** [comment]
Can confirm. There's some rounding error in the base game such that the soldier is given a status of Shaken, even though their will is high enough to be just Tired. The transition value is 18.48. A will below that should be Shaken, whereas a will above it should be Tired. The soldier has a will of 19.

**Comment by idontknow12** [comment]
I've just encountered this behavior of recovering their full will when the shaken effect wears off and it feels very wrong to me. The soldiers should recover their will slowly in a couple of weeks not instantly when the shaken effect wears off.

**Comment by ansabalirai** [comment]
I know WOTC introduced new will mechanics compared to vanilla. but just to point out that in LW2, a shaken soldier (i.e. with zero will) can recover and have their will increases after doing a successful mission and getting a kill, effective immediately. Not sure how we can make it consistent here, but just pointing it out

**Comment by idontknow12** [comment]
Yeah but there was some risk there in taking a 0 will soldiers on a mission, here you get full will for free. ALSO will was not a replenishing bar in long war 2, It was just a stat like aim that was always full. It can't be compared to the new will mechanic in wotc, which indicates fatigue.

**Comment by pledbrook** [comment]
This issue depends on [WOTCCommunityhighlander#637](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/637).

**Comment by pledbrook** [comment]
The highlander now has the fix.
