### ISSUE TITLE
Landed UFO mission dont end

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#595]
Cant end mission, if beacon dont hacked and all aliens dead.

![003](https://user-images.githubusercontent.com/51829747/65430420-94e70a80-de20-11e9-800f-9a6ace98bb4c.JPG)

[save_Landed_UFO.zip](https://github.com/long-war-2/lwotc/files/3642347/save_Landed_UFO.zip)

**Comment by pledbrook** [comment]
I'm updating the mission so that it's based on the WOTC Kismet. I'll also be adjusting the RNFs so that they're _really_ scary. Don't want folks farming RNFs too heavily.
