### ISSUE TITLE
Combat protocol doesnt deal double damage to friendly mechanical units

### ISSUE THREAD

**Issue by scmantikor** [long-war-2/lwotc#596]
hacked mechanical units dont take double damage from CP

[link](https://youtu.be/sFQcW8XkrL4)

**Comment by MrNiceUK** [comment]
That isn't a LWotC specific issue. I did a fix for it as part of my "Ability Interactions Fixes" mod.

**Comment by copyrite** [comment]
Closing as base game bug.
