### ISSUE TITLE
Rescue Resistant Contacts crash

### ISSUE THREAD

**Issue by SkippyMcSkippins** [long-war-2/lwotc#598]
Every time I attempt a resistance rescue missions, the ones that give you three new rebels in a territory, I get a crash when the loading screen is about to change to the briefing screen. Every time it gives me the same error, which is at the bottom of this Launch log. I am running a good number of mods but the majority are cosmetic and the only one touching maps or anything is the missing packages/parcels fix.
[Launch.log](https://github.com/long-war-2/lwotc/files/3644894/Launch.log)

**Comment by Slivicon** [comment]
Cosmetic mods can still be a problem if the right combination are put in place to load a mission. There are a lot of errors in that log from cosmetic mods, you're probably going to have to disable them all and use the "remove missing mods" mod to try and get through that, or start over with them disabled. I've had no trouble with resistance rescue missions, but I run very few mods with this beta.

**Comment by SkippyMcSkippins** [comment]
It would appear that (Missing packages fix - parcels and maps edition) is causing the crash, so tha
