### ISSUE TITLE
Crash On Start Up 

### ISSUE THREAD

**Issue by DanB12341** [long-war-2/lwotc#602]
I have followed all of the troubleshooting guides (deleting config files and verifying game cash) as well as uninstalling deleting any left over files and reinstalling. The initial startup that creates the config files works but upon restart and all subsequent launches immediately crashes. I only have the 5 required mods installed.

[Launch.log](https://github.com/long-war-2/lwotc/files/3648466/Launch.log)

Errors seem to start at line 205.

PC Specs:

[DxDiag.txt](https://github.com/long-war-2/lwotc/files/3648484/DxDiag.txt)

Thanks

**Comment by Lance2448** [comment]
I seem to have the same problem.

**Comment by Dragon-32** [comment]
That launch.log is implying there's more than 5 mods being loaded. Are you using Firaxis' launcher? Have a read of the "Mods not activating/deactivating properly in WOTC" section of [Mod not working? Mods still have their effects after you disable them?](http://steamcommunity.com/sharedfiles/filedetails/?id=625230005)

**Comment by DanB12341** [comment]
I have wiped all config files several times (both the defauts in the install folder and documents) and verified. The active mods in the ModOptions config are empty. 

My ModOptions ini after generating them on first run:

[Engine.XComModOptions]
ActiveMods=WOTCRevertOverwatchRules
ActiveMods=BetterSecondWaveSupport
ActiveMods=robojumperSquadSelect_WotC
ActiveMods=LongWarOfTheChosen
ActiveMods=X2WOTCCommunityHighlander

[IniVersion]
0=1569430467.000000

As you can see only the default 5 are on.

Thanks for the help

**Comment by pledbrook** [comment]
That's almost certainly a highlander issue, i.e. you're using the wrong one. Are you sure you have unsubscribed from *all* highlanders? And are you definitely using the X2WOTCCommunityHighlander directory that comes in the LWOTC 1.0 beta 1 zip package?

**Comment by DanB12341** [comment]
![image](https://user-images.githubusercontent.com/55759483/65622763-4a9b9000-dfbe-11e9-8922-af3b3e957cae.png)

Yea, just placed it within the Mods folder (which I created). Im unsubbed from highlanders on steam too.

**Comment by pledbrook** [comment]
Err...you've put the mods in the wrong directory. Should be in _XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods_.

**Comment by DanB12341** [comment]
I now feel VERY dumb. Its working now. Apologies for time wasted!
