### ISSUE TITLE
trojan controlled units are not losing their actions once the hack ends

### ISSUE THREAD

**Issue by scmantikor** [long-war-2/lwotc#605]
[link](https://youtu.be/SrvLh2sH7FY)

[save_IRONMAN- Campaign 1555.zip](https://github.com/long-war-2/lwotc/files/3649666/save_IRONMAN-.Campaign.1555.zip)

**Comment by pledbrook** [comment]
This seems unrelated to #627. The Trojan Virus effect is remove the action points from the unit, but it's somehow getting them back. Will require more investigation to find out why.

**Comment by pledbrook** [comment]
Ugh. I kind of got this working, but the highlander "fix" for #627 is messing this up.

**Comment by pledbrook** [comment]
Fixed in above commit
