### ISSUE TITLE
Advent trooper "ready for anything" (overwatch after firing) indicator is set before firing instead of after

### ISSUE THREAD

**Issue by Slivicon** [long-war-2/lwotc#608]
I believe it should be the reverse: Advent trooper should fire before "ready for anything" overwatch is set by the AI.

It appears it all still works, so this is arguably a more minor issue where the advent trooper who has "ready for anything" should first fire, then set "ready for anything" overwatch action.

**Comment by pledbrook** [comment]
This is probably another one of the many visualisation ordering issues in the mod. WOTC changed the whole system for the visuals, i.e. the stuff you see as a player, and I think that's causing a lot of glitches. They don't typically break the game though.

**Comment by wdanny69** [comment]
this won't affect the gameplay and the game tends to be a bit weird in visualization. won't fix
