### ISSUE TITLE
SPARKs can infiltrate more than one mission at once

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#609]
Similar to issue 584, a wounded SPARK is always available for infiltration even if he is currently already on a mission

**Comment by pledbrook** [comment]
Do you have a save for this? I remember this was an issue before, but it was fixed.

**Comment by allenhu0912** [comment]
[save_Save 90.zip](https://github.com/long-war-2/lwotc/files/3657722/save_Save.90.zip)
SPARK wounded with 10 hours left, you can send him on multiple missions at once

**Comment by pledbrook** [comment]
@allenhu0912 Can you confirm that once you remove the SPARK from the squad in Squad Select, you can't add it back?

This appears to be a problem with the Squad Select screen's autofill mechanism, which ignores `eStatus_CovertAction` for wounded soldiers that can go on missions, i.e. SPARKs.

The solution is probably to fix the bug in the highlander: `XComGameState_Unit.CanGoOnMission()` should check that the unit's status is not `eStatus_CovertAction`.

**Comment by pledbrook** [comment]
Depends on [X2WOTCCommunityHighlander#665](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/665).

**Comment by pledbrook** [comment]
Should be fixed in beta 2 with [this highlander pull request](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/684).
