### ISSUE TITLE
Pods lack diversity

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#61]
Pods seem to be very limited in what enemies they can contain and generally don't include the Alien Pack enemies in Guerrilla Ops.

I think this is because the spawn distribution lists are not configured correctly (I didn't know what they were about when I converted the inclusion/exclusion lists to spawn distribution lists). A lot of work to fix these up.

**Comment by pledbrook** [comment]
Download [this zip](https://www.dropbox.com/s/rfbhfpdsc84kjgz/lwotc-pod-diversity-config.zip?dl=1) and extract its contents to the mod's _Config_ directory to get a temporary fix for most guerrilla ops, rendezvous and maybe other missions.

Warning: this may noticeably increase the difficulty as you can encounter significant numbers of the harder enemies when they first start appearing.

**Comment by ansabalirai** [comment]
Just to check, when you say increase in difficulty, do you mean that the pods will start having FL appropriate enemies as soon as FL is updated, regardless of regional strength/vigilance and the infiltration percentage? I am afraid I am still not entirely sure whether the pod compositions themselves are affected by strength/vigilance and infiltration percentage or whether it is just the pod sizes that are impacted.

**Comment by pledbrook** [comment]
Let's say mutons start appearing when you hit force level 5. The original LW2 gave it a low spawn weight at this force level, which meant that it appeared very infrequently at force level 5. Its spawn weight then increased with force level, meaning that it appeared more often.

The configuration in that zip file behaves differently in that the muton gets the same spawn weight for all the force levels in which it appears. That means you're more likely to see them at force level 5 than before. So for example, you could feasibly see 2 or 3 on a mission rather than just the one with the original LW2. Or you may just see them on more missions.

Since they're a difficult opponent at lower force levels, the currently behaviour makes the game a bit more difficult, and in some extreme examples, ridiculously difficult depending on RNG. Not sure, but just want to make sure you're aware.

**Comment by ansabalirai** [comment]
I see. In that case, I can see the elegance of the granular approach of the LW2 method, especially in a longer campaign (no pun intended). I gather it would be quite complex to port this differential weight based method from LW2? Let us see how this affects people's campaigns in the meantime

**Comment by pledbrook** [comment]
Not complex, no. It will just triple or quadruple the length of the spawn distribution lists in the config. The relevant file is `XComEncounterLists.ini`. We would just need to add extra lines for each enemy type with different combinations of force level range and spawn weight. I hope.

**Comment by SirMrMister** [comment]
I take it that an alien type's actual spawn rate is affected not just by its own spawn weight, by also by the spawn weight of other alien types at that force level?

**Comment by pledbrook** [comment]
That's my understanding, yes. And the spawn weights typically increase with force level. So an enemy type introduced at force level one might have a spawn weight of 15, but one introduced at level 6 might have a spawn weight of 30. This means that the earlier enemy types get pushed further into the margins as force level increases.

I'm beginning to think that an extra line of configuration per enemy type would be sufficient to mitigate the works effects of the current setup. So for a couple of force levels each advanced type has say, half or less of its normal spawn weight.

**Comment by SirMrMister** [comment]
Sounds like something you would want to keep on an excel table/macro or such while fine-tuning (for instance, so that while you are changing an entry's weight, that force's level "total weight" summed across all of its alien typez is updated to give you an idea of what scale you're working with.

**Comment by captainbeastfeast** [comment]
Forgive me if out of date with this (currently testing alpha 4) but, from what I've seen so far WOTC enemies aren't appearing in pods either. So, WOTC's new units also need to be added on to the existing LW pods that are currently being used by the mod.

**Comment by pledbrook** [comment]
Priests, Purifiers, and Spectres are definitely appearing.

**Comment by pledbrook** [comment]
This is still an issue because the code for making alien pods in particular more diverse has yet to be ported. The [Diverse Alien Pods](https://steamcommunity.com/sharedfiles/filedetails/?id=1535962428) mod helps alleviate some of the worst cases. However, it doesn't for alien pods that include at least one forced template. Either the forced template is ignored or the encounter definition is untouched and you end up with pods with just one alien type (on top of the forced template).
