### ISSUE TITLE
Hit and run not giving action if shot occurs on first action

### ISSUE THREAD

**Issue by eraserman59** [long-war-2/lwotc#612]
[save_hitAndRunBug.zip](https://github.com/long-war-2/lwotc/files/3655508/save_hitAndRunBug.zip)

Hit and run seems to only give a free action if you shoot at a flanked target as your yellow action.

In attached save, shoot at the exposed viper that is binding the ranger. Hit and run activates (notification pops up) but the skirmisher ends up with only one remaining action.

If you instead blue move first, then shoot, you get your free action.

**Comment by allenhu0912** [comment]
You are remembering LW1's HnR. Read the tooltip closely, in LW2 it DOES NOT make it a free action. Instead you get an action back

**Comment by eraserman59** [comment]
Oh. huh yeah I'm too use to LW 1 version. That'll take a while to get use to.

Closing because this is not a bug,
