### ISSUE TITLE
on Rendezvous pod start shooting after break concealment

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#614]
After end turn, pod go on me, break concealment and start shooting. Dont remember how its must work, maybe if you not in cover pod can do shoots.

[save_Test_rendezvos.zip](https://github.com/long-war-2/lwotc/files/3658645/save_Test_rendezvos.zip)

![001](https://user-images.githubusercontent.com/51829747/65703325-40949280-e08d-11e9-8519-98ea1a79a857.JPG)

**Comment by pledbrook** [comment]
You should look carefully at what dark events you have active :wink: After a lot of debugging, I discovered that DarkEvent_Counterattack is adding an extra standard action that is being used for shooting. It _should_ simply be putting the soldier into overwatch. Don't know why that's not happening. Really don't fancy trying to find out.

I'll disable the dark event as it overlaps with the existing LW2 reflex action behaviour and isn't working as advertised.
