### ISSUE TITLE
Haywire Protocol: Values inconsistent

### ISSUE THREAD

**Issue by bmp2** [long-war-2/lwotc#619]
The values shown on Haywire Protocol in the soldier's action menu are different than the values shown in the Hack screen.

https://imgur.com/a/ynpZJUs

**Comment by ansabalirai** [comment]
There is a variance in the haywire rolls that LW2 adds which are not depicted by perfect information. The same thing exists in vanilla LW2 and is something people unfortunately lived with . Not sure if this could be fixed now that PI is integrated

**Comment by bmp2** [comment]
I never used Perfect Information with LW2 so I never knew about the issue. Thanks for the explanation.
________________________________

**Comment by Grobobobo** [comment]
Working as intended.
