### ISSUE TITLE
Customization Bug

### ISSUE THREAD

**Issue by GitWadeanthony** [long-war-2/lwotc#62]
The color customization of soldiers are locked as green, reaper's black, reaper hood is locked red and none of it can be changed besides beside weapon color. Hair and eyes also can't be changed. Patterns and Tattoos don't show up. Issue happens in character pool as well.

Only using the LWotc 1.6 alpha mod in this save file. 
Works correctly in base WotC and base Xcom 2 without mods

Fixes I've tried on my end.
Uninstalled all other mods
Verified integrity of game files.
Deleted the config folders and had it rebuild. (in MyDocs and steamfolder..\XCom2-WarOfTheChosen\XComGame)
Tried installing a color mod to see if it would override any config files related to color customization.

[save_Customization Bug.zip](https://github.com/pledbrook/lwotc/files/3051215/save_Customization.Bug.zip)

After changing weapon color. Testing reaper hood.
![20190407011253_1](https://user-images.githubusercontent.com/49357270/55679065-7624a400-58d2-11e9-961e-ab7458595587.jpg)
![20190407012818_1](https://user-images.githubusercontent.com/49357270/55679177-d0266900-58d4-11e9-9a44-6e20e9450ce4.jpg)
![20190407012920_1](https://user-images.githubusercontent.com/49357270/55679178-d0266900-58d4-11e9-9859-cd64dff850ab.jpg)
![20190407013021_1](https://user-images.githubusercontent.com/49357270/55679179-d0266900-58d4-11e9-9415-a99428a323b3.jpg)
![20190407013418_1](https://user-images.githubusercontent.com/49357270/55679202-55aa1900-58d5-11e9-9322-a4e9e44b2813.jpg)

**Comment by pledbrook** [comment]
OK, so I'm not imagining things. Earlier iterations of the mod worked fine with my customised soldiers, but the latest versions do have this problem I noticed. I was hoping it was just a local glitch.

**Comment by MagSigeasol** [comment]
Can confirm I have the same issue - Xcom are green by default and cannot be altered

**Comment by pledbrook** [comment]
This happens because I bundle the community highlander code (a customised version) into the mod, but I apparently also need to incorporate some config.

**Comment by ansabalirai** [comment]
Interestingly, upon update to predator armor, the color changes to black and orange color scheme. I don't mind it too much personally, but since one of the big selling points of X2 was the depth of customization, I guess we may have to address this

**Comment by pledbrook** [comment]
Ah, I forgot to post the fix here yesterday. Just add the following text to `XComContent.ini` in the mod's Config directory:
```
[XComGame.X2PhotoboothHelpers]
; Contains all class filters! A soldier class may have multiple PhotoboothSoldierClassFilters lines.
; In this case, the first entry is considered the "primary" filter for purposes of randomly rolling
; class poses.
+PhotoboothSoldierClassFilters=(SoldierClass="Grenadier", ClassFilter=ePAFT_Grenadier)
+PhotoboothSoldierClassFilters=(SoldierClass="CentralOfficer", ClassFilter=ePAFT_Ranger)
+PhotoboothSoldierClassFilters=(SoldierClass="NestCentral", ClassFilter=ePAFT_Ranger)
+PhotoboothSoldierClassFilters=(SoldierClass="LadderCentral", ClassFilter=ePAFT_Ranger)
+PhotoboothSoldierClassFilters=(SoldierClass="Ranger", ClassFilter=ePAFT_Ranger)
+PhotoboothSoldierClassFilters=(SoldierClass="Sharpshooter", ClassFilter=ePAFT_Sharpshooter)
+PhotoboothSoldierClassFilters=(SoldierClass="PsiOperative", ClassFilter=ePAFT_PsiOperative)
+PhotoboothSoldierClassFilters=(SoldierClass="ChiefEngineer", ClassFilter=ePAFT_Specialist)
+PhotoboothSoldierClassFilters=(SoldierClass="TLE_ChiefEngineer", ClassFilter=ePAFT_Specialist)
+PhotoboothSoldierClassFilters=(SoldierClass="Specialist", ClassFilter=ePAFT_Specialist)
+PhotoboothSoldierClassFilters=(SoldierClass="Skirmisher", ClassFilter=ePAFT_Skirmisher)
+PhotoboothSoldierClassFilters=(SoldierClass="Templar", ClassFilter=ePAFT_Templar)
+PhotoboothSoldierClassFilters=(SoldierClass="Reaper", ClassFilter=ePAFT_Reaper)

; Soldier classes mentioned here cannot have poses with a ePAFT_SoldierRifle,
; or poses marked bExcludeFromTemplar.
+TemplarLikeSoldierClasses="Templar"


; Character templates mentioned here will use the spark poses and have some
; extra space for themselves.
+SparkLikeCharacterTemplates="SparkSoldier"


[XComGame.CHHelpers]

; For maximum flexibility, the material categories are not mutually exclusive except when redundant.
; So, since Hair Tint is applied to Skin Materials, being a Hair Material in addition is ignored.
; Similarly, being an Armor Material takes precendence over also being WepAsArmor material.

; Hair Materials get the Hair Tint

+HairMaterial="M_HairCustomizable"
+HairMaterial="F_HairCustomizable"
+HairMaterial="M_HairCustomizable_Trans"
+HairMaterial="F_HairCustomizable_Trans"
+HairMaterial="HairSimple_TC"


; Skin Materials get skin & hair tints, and if applied to the Head component mesh, Scar & face paint applied
; Otherwise, tattoos are applied.

+SkinMaterial="HeadCustomizable_TC"						
+SkinMaterial="SkinCustomizable_TC"
+SkinMaterial="HeadCustomizable_Scars_TC"
+SkinMaterial="Skin_M"


; Armor Materials get armor tints & pattern applied.

+ArmorMaterial="SoldierArmorCustomizable_TC"
+ArmorMaterial="Diffuse_TC_Metalic"		
+ArmorMaterial="M_Master_PwrdArm_TC"
+ArmorMaterial="Diffuse_TC_Metalic"
+ArmorMaterial="Props_OpcMask_TC"
+ArmorMaterial="CivilianCustomizable_TC"					
+ArmorMaterial="SoldierArmorCustomizable_Decals_TC"
+ArmorMaterial="UnitArmor_M"
+ArmorMaterial="UnitArmor_M_ClearCoat"
+ArmorMaterial="UnitArmor_M_OpacityMasked"


; WepAsArmor Materials get armor tints & pattern applied ONLY if NOT applied on an attachment mesh.
; As the name implies, this is mainly used for weapon materials which are also used on armors.
+WepAsArmorMaterial="UnitWeapon_M"
+WepAsArmorMaterial="UnitWeapon_M_OpacityMasked"
+WepAsArmorMaterial="WeaponCustomizable_TC"
+WepAsArmorMaterial="UnitWeapon_M_ClearCoat"

; Eye Materials get the eye color tint.
+EyeMaterial="EyesCustomizable_TC"


; Flag Materials get the appropriate flag texture applied.
+FlagMaterial="TC_Flags"
```
