### ISSUE TITLE
Teleporting alien bug

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#623]
Hiding in the corner of a map on a 0% supply line raid, when suddenly overwatching troops open fire. Apparently an Archon magically teleported to my corner of the map; the rest of his pod was about 2 screens away

[save_Save 97.zip](https://github.com/long-war-2/lwotc/files/3664853/save_Save.97.zip)

**Comment by pledbrook** [comment]
This is very likely to be the same issue as #228. Reopen if you still experience the issue once the fix is in a release that you're playing.
