### ISSUE TITLE
Cannot Whiplash hacked target

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#625]
![20190927222531_1](https://user-images.githubusercontent.com/54481962/65811719-ccd8af80-e18a-11e9-81d0-3dd5ea75fc81.jpg)
You can see a drone to the right that I can't target

**Comment by copyrite** [comment]
Whiplash, Justice and Wrath targeting will be fixed in CHL: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/1291.

Ripjack Slash targeting and Whiplash's bonus damage will be fixed in LWOTC. I'll pick this up again when the CHL fix comes out.

**Comment by copyrite** [comment]
Fixed in https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/1292
