### ISSUE TITLE
Stunned MC unit bugs out

### ISSUE THREAD

**Issue by eraserman59** [long-war-2/lwotc#627]
[save_Stun+MC preStun.zip](https://github.com/long-war-2/lwotc/files/3665161/save_Stun%2BMC.preStun.zip)
When a Mindcontrolled unit reverts to player control, the stun from the arc thrower doesn't properly count down, and the unit becomes some weird stunned but mobile state that can't attack or use items, but can move.

There are two saves in the attached zip. The save called prebug is from the turn before the mind control wears off. Move the assault closer and use the arc thrower to stun the MC's unit. On the next player turn the MC should finish, and the grenadier will be stuck in some sort of limbo state.

The other save is from the start of the turn where I noticed the unit being in it's limbo state, in case the reproduction steps do not cause the bug to re-manifest. Loading this save will have the unit be in the weird limbo state.

**Comment by scmantikor** [comment]
same issue with hacking btw

**Comment by pledbrook** [comment]
Could be same cause as #605

**Comment by pledbrook** [comment]
Depends on [X2WOTCCommunityHighlander#643](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/643) being fixed.
