### ISSUE TITLE
Increase detection radius for red and yellow alert enemies

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#628]
The idea here is to make stealth riskier once XCOM have engaged or have put the enemy on (yellow) alert. It also makes sense logically, since the enemy is more alert and should therefore find it easier to notice XCOM soldiers.

**Comment by DerAva** [comment]
I have several concerns with this change and the current implementation in the test build of "Red and Yellow Alert enemies now have a 6- and 4-tile bonus to their detection radius":

This significant increase combined with high detection range enemies and/or the vigilance Dark Event could lead to detection ranges that are very close or even identical to visible range.

This poses a significant impact to missions in which enemies already start on yellow alert (retaliations and mini-retals) - these missions are already among the more punishing and difficult missions, so increasing the difficulty on those could have too much of an effect.

There are situations where pods will self-activate or put themselves into yellow alert, most prominently supply convoys where enemies run through a fire on the map or Sectopods / Gatekeepers blowing up a vehicle they walk through. It's already annoying when that happens, having enemies even gain a buff from that seems excessive.

This kind of change devalues stealth builds, which already have a reduced combat performance, so it could lead to less build variety and more "cookie cutter" builds.  

Finally, on an untimed mission it might just mean that you creep forward very slowly, maybe even waiting for something like a Ghostwalker cooldown each time before you advance, making an already long and tedious mission even longer.

**Comment by ansabalirai** [comment]
I agree with DerAva based on my experience with this change over the past couple of days. I am all for nerfing stealth cheese, but with the current changes to pod detection ranges, it basically means your shinobi/reaper is pinned by the alerted pod and since they are on alert, they end up revealing you anyway. Having a pod on yellow alert already means that you need to be mindful of its movements, the current changes to the detection radius seem quite excessive nerf to phantom. If nothing else, maybe the increase can apply to red alerted pods only or have reduced values for both (i.e. +3 and +1)

**Comment by pledbrook** [comment]
1. The adjustments are high to make sure that the impact of them could be felt, with a view to potentially reducing them if necessary.

2. Since covertness perks like Ghostwalker and Covert are percentage based, one can argue that they are even more important with this change. In other words, the +6 becomes more like +1 or +2.

3. Fair point about retaliations, although I'd like to see more play on those. The +4 tiles may be a bit much for yellow alert, but that's not +4 for Shinobis, especially ones with Covert. So I would be wary about reducing it to just +1. +2 or +3 seems more reasonable.

4. I would prefer other solutions to overwatch creeping, such as XCOM Scamper (which makes non creeping less weak/dangerous) and/or will check rolls per turn, so very slow missions would mean a bigger fatigue build up.
