### ISSUE TITLE
Remove Volunteer Army resistance order

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#634]
This RO has the chance to add a resistance fighter to XCOM missions, which is pretty strong. Although an interesting idea, it would take too much effort at this point to balance it reasonably. It might also make a better SitRep than resistance order.

**Comment by Anxoczt** [comment]
Speaking of cards that add new units for XCOM, what about the Double Agent Skirmisher order ? I like it in concept but it could use larger selection pool of units that LW2 added.

**Comment by Thrawn007** [comment]
I think this can be balanced by adjusting the % of time it comes up.  It's nice when it works, but it's already undependable, and by making it even less reliable, the power added when it does come up may not be worth the opportunity cost of another order you could slot.  So overall, I think nerfing it may be the better solution than removing it.  (The soldier given likely needs a nerf as well.)
