### ISSUE TITLE
Rebalance Information War resistance order

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#635]
-20 Hack defense on all missions right from the start of the campaign is just a bit too strong as it almost guarantees hack control of drones (and does guarantee it in a lot of cases).

One option would be to weaken the hack effect, but then the card would scale very badly indeed. Another option is to delay the availability of the card so that it requires a higher faction influence.

The best option may be to introduce one or two more variants with weaker and stronger effects. For example, a -10 Hack defense reduction would probably work nicely for a starting card.

**Comment by Thrawn007** [comment]
The one things to be careful of if multiple versions were introduced, is stacking them.  For example a tier 1 with -10 and tier 2 with -20 would give a total of -30, which might be more than is desirable.  My recommendation would be to simply reduce the current order to -10 and leaving it at that.  Save any bigger balances for the future.
