### ISSUE TITLE
Smash and Grab: Soldiers Bleeding Out come home when last XCOM is killed (none evacuated)

### ISSUE THREAD

**Issue by bmp2** [long-war-2/lwotc#638]
I had a TPK, 8 soliders on the mission, all 8 killed or bleeding out. Of them, 4 had their bleeding out counters still going when the last solider was killed. The evac counter had not finished counting. The 4 soldiers who were bleeding out came home at the end.

The mission results screen showed 4 wounded and 8 killed.

**Comment by pledbrook** [comment]
Do you have a save that reproduces the problem? This should have been fixed for the beta (see #238).

**Comment by bmp2** [comment]
I am on the beta. I also saw it when most soldiers evacuated; a soldier bleeding out came home. In both cases I saw it on Smash and Grab missions. I don't have a save for the original report but I have one for this later mission.

[Uploading save_AUTOSAVE- Campaign 3, Mission 10, Turn 12.zip…]()

**Comment by pledbrook** [comment]
Thanks. This was a simple misconfiguration of the mission type.
