### ISSUE TITLE
Trojan doesn't activate before enemy takes an action

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#64]
In the following save file, the drone is shut down. When it comes back, it shoots before dying to Trojan:

[trojan-bug.zip](https://github.com/pledbrook/lwotc/files/3051496/trojan-bug.zip)

**Comment by ansabalirai** [comment]
In my experience, it depends on the situation. If the drone is not active when it is hacked (i.e. concealment hack), it dies immediately when coming back up, but if it is active when you hack it, it does get an action.

**Comment by pledbrook** [comment]
In this case, the drone was hacked from concealment, but the soldiers were revealed by the time it came back. Anyway, hopefully it's an easyish one debug.

**Comment by nightmaRok** [comment]
Trojan ability don`t work correct, after dron wake up he moves and use action, then take damage. But he must skip turn and take damage.
[save_Trojan.zip](https://github.com/long-war-2/lwotc/files/3319925/save_Trojan.zip)
