### ISSUE TITLE
Increase AP cost of extra abilities beyond the standard ability selected on promotion

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#640]
One of the issues with allowing multiple perks to be selected at each rank through the Training Center is that most of the perks are relatively cheap, so many can be purchased. This leads to over-powered soldiers.

This problem particularly applies to faction soldiers, so one idea is to make each purchase of an ability, beyond the ability that gets selected on promotion, more and more expensive as you purchase more abilities.

**Comment by Witt-Github** [comment]
Sometimes I like OP soldiers. :) However, your point is taken and the solution sounds reasonable.  Could you make it configurable in the mod settings menu?
