### ISSUE TITLE
TLP pack guns don't provide their weapon upgrade perks.

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#641]
see title.

**Comment by Clibanarius** [comment]
That's because they don't have any weapon upgrades at all in LWotC. Besides, that's only a free base-level scope here and there.

**Comment by yoshimo** [comment]
it still is a lil weird to not have the upgrades in, even if its just a scope, a repeater or a shaft.

**Comment by tunbridgep** [comment]
The TLP stuff kinda sucks anyway because of this. The "No Upgrades" wasn't worth the crappy built-in upgrades.

I say either make them behave as skins for normal weapons and be identical, or give them special addons not findable anywhere else that are signifncant.

**Comment by yoshimo** [comment]
It is ok that they are sub-par and irreplaceable. They are meant to help you in the early game a little and then you replace them with laser or magnet weapons.

**Comment by tunbridgep** [comment]
Yes, but they are even worse than the tier 1 weapons since they can't take upgrades, making them literally pointless.

**Comment by yoshimo** [comment]
I think this is just a symptom of https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/657

**Comment by Grobobobo** [comment]
No plans to change it.
