### ISSUE TITLE
GTS rookie selection

### ISSUE THREAD

**Issue by scmantikor** [long-war-2/lwotc#642]
can we get something in line with officer selection for GTS training? Memorizing names for training is quite irksome when we currently have something working for the same purpose
![image](https://user-images.githubusercontent.com/55502272/65839898-48319100-e344-11e9-97ee-b93ab8590529.png)

**Comment by Clibanarius** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=865667559 works on LWotC.

**Comment by scmantikor** [comment]
noice ty
