### ISSUE TITLE
Suggestion:Chosen weapons need buff.

### ISSUE THREAD

**Issue by Sinkingeye** [long-war-2/lwotc#643]
In WotC,chosen weapons,when unlocked,deal damage equal to plasma weapons,and have built-in 4 superior upgrades.
But now,their damage output are similar to coil guns,and ripped off upgrade.
Combine this with additional research time to unlock them,I doubt anyone will waste time to unlock them.
So here are my suggestions:
Katana(chosen blade):no buff,since it's already powerful(pierce 5 armor and 100% hit)
Arashi(Chosen shotgun) and Disruptor rifle:raise damge to plasma level,and give it bouns to compensate for its lacking of upgrade.
Dark lance(Chosen sniper rifle):debatable,althrough the one-action to fire trait is attractive,I still prefer snapshooters with regular sniper rifle.bonus is appreciated.
Dark claw(Chosen pistol):it can pierce 5 armor,so it's ok.
 
Besides,do anyone notice that Disruptor rifle doesn't deal 100% critical damage to psionic enemies in LWotC?

**Comment by Fallguy55** [comment]
I believe this is simply because the chosen haven't recieved any numerical changes since Vanilla wotc. They are essentially tacked on at the moment. I'm sure they're slated for a rebalance pass moving forward.

**Comment by copyrite** [comment]
Already implemented.
