### ISSUE TITLE
dev build-0004 spawning faceless in GOps

### ISSUE THREAD

**Issue by scmantikor** [long-war-2/lwotc#644]
![image](https://user-images.githubusercontent.com/55502272/65877348-05140400-e3be-11e9-8642-f1d24f538a39.png)

![image](https://user-images.githubusercontent.com/55502272/65877634-bca91600-e3be-11e9-8b2e-a47f024e0b04.png)

im getting faceless on a jailbreak while the DE is still preparing on the latest dev build

[faceless on jailbreak.zip](https://github.com/long-war-2/lwotc/files/3670960/faceless.on.jailbreak.zip)

attached save file- 1 before the jailbreak and 1 before the faceless transform. Just kill the 2 troopers 1 pectoid

**Comment by pledbrook** [comment]
I can't reproduce from your pre-mission save file. The mission does not start with a Faceless infiltrator "pod". Perhaps this has inadvertently been fixed by some recent change. Perhaps it's a random glitch.

**Comment by scmantikor** [comment]
closing issue apparently these missions exist as per joinrbs' comment
![image](https://user-images.githubusercontent.com/55502272/66503787-78262480-eafa-11e9-8b63-8b4294a55a7b.png)
