### ISSUE TITLE
Chosen spawning in unreachable position

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#646]
Warlock Chosen spawned in area of map that is unreachable, but I guess is somehow still playable.
[save_ChosenNotReachable.zip](https://github.com/long-war-2/lwotc/files/3679205/save_ChosenNotReachable.zip)

I'm not playing with any map mods.

**Comment by Fallguy55** [comment]
This happened for me once, except with the assassin. She did nothing the whole match because she couldn't reach me

**Comment by ansabalirai** [comment]
I have not checked the save, but I am guessing it is one of those tunnels map. I had Chosen repeatedly appear there and get stuck. So, can confirm this "bug" exists

**Comment by copyrite** [comment]
Missions with Chosen no longer occur on subway maps.
