### ISSUE TITLE
Lost squad

### ISSUE THREAD

**Issue by murdernator** [long-war-2/lwotc#648]
Hello, I have a squad that has been infiltrating for several weeks (200%) but the mission does not appear on the geoscape. Is there a way to retrieve them from infiltration or force the mission to start?

**Comment by imn01** [comment]
try this command "LWForceSquadPostMissionCleanup (squad name)"
this one worked for me in base game LW2

**Comment by pledbrook** [comment]
You don't have Lost and Abandoned enabled for the campaign, do you?

**Comment by copyrite** [comment]
Closing as old and a having a near duplicate with the same solution offered.
