### ISSUE TITLE
Dark Events Non-Tactical do not disappear

### ISSUE THREAD

**Issue by srclamp** [long-war-2/lwotc#650]
BETA Version
I know tht 'Tactical' Dark Events are pernament but I didn't select 'Grim Horizons' and I've had a non-tactical dark event for greater faceless and one extra hit point for Advent for three game months now (and i've just had another dark event 'under a different title' giving Advent a further hit point!!!) In vanilla these events should only stay for a month but these non-tactical also seem to be permanent so is this expected behaviour?

**Comment by pledbrook** [comment]
Alien Conditioning (+1 HP) is a permanent dark event to ensure that the aliens scale with XCOM. The Greater Faceless dark event is also permanent.
