### ISSUE TITLE
Reinf do not spawn in visual range of XCOM

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#652]
Just click end turn.  Reinf will drop near the original objective location (cell blocks), but will not spawn near XCOM.

I'm not saying that the Reinf is dropping behind some visual LOS blocker, but all Reinf should be dropping within visual range of some XCOM soldiers. I believe in LW2, they took the center location of all alive XCOM solders and then added some randomizer to that value.

[save_ReinfSpawn.zip](https://github.com/long-war-2/lwotc/files/3688311/save_ReinfSpawn.zip)

**Comment by ansabalirai** [comment]
In LW2, them dropping on the other side of the map was certainly possible, so I don't think it is a bug. If you WANT them to always drop in LoS, that is another story...

**Comment by pledbrook** [comment]
This can be forced, but it also makes overwatch very strong. So depending on the mission type, such a change could make life a little harder for XCOM or a lot easier.

**Comment by ToastedAmphibian** [comment]
I've noticed this with every prison break mission. Assumed it was an intentional choice, giving the escaped prisoners a chance to run and hide. Constant reinforcements dropping directly on top of you just seems cheap and un-fun.

**Comment by TheReigningKing** [comment]
This RNF spawning along with #479 makes completing missions a breeze if you can sneak to the objective if you don't do a normal straight line attempt.

I'm almost positive that 99% of the time in LW2 RNFs dropped within visual range of XCOM. This meant that you couldn't just dash out, you had to deal with RNFs or try somehow to break LOS to prevent getting shot at.  Right now, I can dash in a straight line and not even worry about activating the RNF pod.

**Comment by DerAva** [comment]
If I remember the LW2 spawning rules correctly the game would calculate the center of your squad and spawn the (hidden) RNF flare within 20ish tiles of that center. Keep in mind that this is determined on the turn the red RNF warning show up, not on the turn where the drop in actually happens. That means if you got lucky with the RNF drop location and also moved away from it it can be way out of the way - but it can just as likely be in the middle of your squad.

**Comment by pledbrook** [comment]
RNF drops are working as intended.
