### ISSUE TITLE
Capacitor Discharge is affected by Armor

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#654]
[save_AUTOSAVE- Campaign 20, Mission 157, Turn 17.zip](https://github.com/long-war-2/lwotc/files/3691501/save_AUTOSAVE-.Campaign.20.Mission.157.Turn.17.zip)
Capacitor discharge the Sectopod.
It may be due to damage control adding in armor.

**Comment by TheReigningKing** [comment]
Also, it doesn't seem to stun robotic units. Not sure if its just supposed to be damage, but I remember that it did do some sort of shutdown.

**Comment by pledbrook** [comment]
It has disorient, but no stun. And the disorient apparently doesn't apply to robots. Also, the robotic damage explicitly does not pierce armour (unlike with Combat Protocol for example).
