### ISSUE TITLE
Highlander issue

### ISSUE THREAD

**Issue by Opie2891** [long-war-2/lwotc#656]
I've followed the install guide to the letter and have installed all files and subscribed to all mods as directed.  I've even installed all other mods to address the issue.  That said, the highlander mod never appears as a choice on the launch screen, but the other four are there.  I've launched and relaunched several times but than changes never take affect.  What am I doing wrong?  Will there soon be an .exe dumb people like me can use to play LWotC released soon?  I should note this is a first time install

**Comment by TheReigningKing** [comment]
Check the FAQ. Sounds like you need to delete out the config folder and/or unsubscribe from the steam highlander

**Comment by pledbrook** [comment]
What is the path to the Community Highlander directory (_X2WOTCCommunityHighlander_) that you installed? And are you using the standard game launcher or the Alternative Mod Launcher?

**Comment by Opie2891** [comment]
> What is the path to the Community Highlander directory (_X2WOTCCommunityHighlander_) that you installed? And are you using the standard game launcher or the Alternative Mod Launcher?

L:\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods\X2WOTCCommunityHighlander-lwotc-dev

I'm using the standard launcher I believe.

**Comment by Opie2891** [comment]
> Check the FAQ. Sounds like you need to delete out the config folder and/or unsubscribe from the steam highlander

I deleted my config file from here:  C:\Users\Aaron Opheim\Documents\my games\XCOM2 War of the Chosen\XComGame

**Comment by pledbrook** [comment]
What's this? _X2WOTCCommunityHighlander-lwotc-dev_ How did you get the highlander?

**Comment by Opie2891** [comment]
> What's this? _X2WOTCCommunityHighlander-lwotc-dev_ How did you get the highlander?

Here on Github, from the LWOTC files.  https://github.com/X2CommunityCore/X2WOTCCommunityHighlander.git

**Comment by pledbrook** [comment]
> I've followed the install guide to the letter

Are you sure? Step 1 in the online [installation guide](https://github.com/long-war-2/lwotc/wiki/Installing-Long-War-of-the-Chosen) says to use the X2WOTCCommunityHighlander that comes in the LWOTC download zip.

The zip should contain two directories:

* LongWarOfTheChosen
* X2WOTCCommunityHighlander

*Both* of those need to be unpacked to the _Mods_ directory.

**Comment by copyrite** [comment]
Closing as pre-Workshop release install issue.
