### ISSUE TITLE
WOTC Community Highlander didnt work

### ISSUE THREAD

**Issue by Tobias26** [long-war-2/lwotc#658]
Hi to all. Unfortunately, WOTC Community Highlander didnt work at my current game version. I can launch the game with 1.16.0 version only. But LongWarOfTheChosen didnt work with this version of WOTC CH! Please, help me, i realy want to play LW...:( I was deleting Config folder several times, I was installing different versions of WOTC CH, but i still cant launch the game with LW...

**Comment by pledbrook** [comment]
Have you followed the [Troubleshooting guide](https://docs.google.com/document/d/1EEZqmzCQQoprh3sDFZQZyiuyRE8I_lsA7Z8pHTSRuzU/edit?usp=sharing)?

**Comment by Tobias26** [comment]
that was the first I did, and that didnt help me

**Comment by pledbrook** [comment]
What's the path to your LongWarOfTheChosen and X2WOTCCommunityHighlander directories?

**Comment by pledbrook** [comment]
In fact, if you could explain exactly what steps you have taken to install the mod, that would be helpful.

**Comment by Tobias26** [comment]
I put 5 mods in a folder c:\Games\XCOM 2\XComGame\Mods\:
robojumperSquadSelect_WotC  (latest version from steam)
WOTCRevertOverwatchRules    (latest version from steam)
BetterSecondWaveSupport     (latest version from steam)
X2WOTCCommunityHighlander   and    LongWarOfTheChosen from LongWarOfTheChosen-1.0-beta-1  archive. 
Then I deleted the XCOM2 War of the Chosen folder from Documents\My Games.
Then I launch the game with that 5 mods. The first start is normal, but without LW2, as it should be. Second launch - and crush. I turn off all mods except X2WOTCCommunityHighlander - and crush again. Actually, game crushes with X2WOTCCommunityHighlander only. I found old versions of that mod, and game launch with 1.16.0 version, but LW2 didnt work with it and crush the game.
Now I'm stumped. The game does not work with other versions of X2WOTCCommunityHighlander, and LW2 does not work with this version of X2WOTCCommunityHighlander.

**Comment by pledbrook** [comment]
What's the path to XCOM 2? And do you have a log file I can look at? It's in _Documents\My Games\XCOM2 War of the Chosen\XComGame\Logs_. Launch.log is the one to open.

**Comment by Tobias26** [comment]
Ofc
[Launch.log](https://github.com/long-war-2/lwotc/files/3694249/Launch.log)

**Comment by pledbrook** [comment]
The correct highlander isn't being loaded. Since you don't appear to be using a valid Steam copy of the game, I'm afraid I can't help further.
