### ISSUE TITLE
Jailbreak: No Fixed EVAC + Resistance Contacts not controllable

### ISSUE THREAD

**Issue by UMebius** [long-war-2/lwotc#661]
Hi I just installed LWOTC not long ago, one issue that I run into every Jailbreak missions, is no fixed EVAC (though I can manually put down an EVAC) and inability to command Resistance Personnel after hijacking prison doors. When mission launches, there are 2 objectives listed: Break into Holding Cells + Extract XCOM soldiers. But after the pointers of Resistance Personnel have all appeared and the camera shifts back to my troops, the objective "Break into Holding Cells" would automatically be removed. I have played LW2 before and so I can tell something isn't quite right, probably I installed some mods that would clash with the LWOTC and messed things up. Here's a log attached. Would appreciate if anyone could provide some insights into this.
[Launch.log](https://github.com/long-war-2/lwotc/files/3693973/Launch.log)

**Comment by pledbrook** [comment]
If this is beta 1 of LWOTC, then this is likely a mod conflict. No idea which one might be causing the issue though.

**Comment by imn01** [comment]
I had that same problem when I tried to use "[WotC] Mission: Prison Break" mod with LWOTC

https://steamcommunity.com/sharedfiles/filedetails/?id=1788645591&searchtext=mission

I removed that mod and the problem was solved

**Comment by UMebius** [comment]
Ahh I see, I will give it a shot, thanks guys !
