### ISSUE TITLE
Templar rend kill as a result of being given action via officer command does not generate focus

### ISSUE THREAD

**Issue by Slivicon** [long-war-2/lwotc#665]
I noticed this on a mission today in beta 1. An officer used command to give templar an action. Templar uses rend on advent officer, killing the officer. Focus was not generated, despite templar only having 1 focus bar out of 3 filled (had deeper focus perk).

**Comment by pledbrook** [comment]
Please re-test with beta 2 when it's out and if it's still a problem, please attach a zipped save file that reproduces the issue.

**Comment by wdanny69** [comment]
templar has been reworked and now provides focus on use of rend instead of kill, no longer an issue
