### ISSUE TITLE
Prevent lost from triggering officer collector ability

### ISSUE THREAD

**Issue by eraserman59** [long-war-2/lwotc#667]
Admittedly this may be less of a concern once headshot is removed, but right now the lost can be effectively farmed for intel (and I assume later alloys and elerium) because they can still proc the collector ability from officers.

**Comment by pledbrook** [comment]
Scavenger already tests for Team Alien, so it doesn't trigger on The Lost. Collector just tests for whether it's an enemy unit. That's native, so I have no idea what it actually checks.

Anyway, even if Headshot is removed, there are several abilities that can kill swarms, so I think it's definitely best to disable Collector for Lost at the moment.

**Comment by pledbrook** [comment]
Do you happen to have a save file so I can test the fix? It's fiddly and time consuming to set up a situation to test this.

**Comment by eraserman59** [comment]
Unfortunately it looks like I don't currently have a save that has an officer with collector and the lost, as the mission that caused me to notice this interaction is no longer in my autosaves.

Next time I get a mission with the lost and an officer with collector I'll grab a save

**Comment by MiserablePileOfBugs** [comment]
Here's a save with a mission with lost where I have an officer with collector. It's the dev build 14.1.
[save_collector.zip](https://github.com/long-war-2/lwotc/files/4421216/save_collector.zip)

**Comment by eraserman59** [comment]
[save_Collector bugged-.zip](https://github.com/long-war-2/lwotc/files/4432962/save_Collector.bugged-.zip)
I think collector is bugged again. Save attached where I am pretty sure I saw the message popup upon killing a lost.
