### ISSUE TITLE
Shaken soldier can training officer abilities

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#669]
[save_IRONMAN- Campaign 116.zip](https://github.com/long-war-2/lwotc/files/3695964/save_IRONMAN-.Campaign.116.zip)

![001](https://user-images.githubusercontent.com/51829747/66292855-fc578c80-e8ed-11e9-815b-d8df2abf556c.JPG)

**Comment by pledbrook** [comment]
Fixed with #462
