### ISSUE TITLE
No mission reward

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#670]
[save_IRONMAN- Campaign 116.zip](https://github.com/long-war-2/lwotc/files/3697726/save_IRONMAN-.Campaign.116.zip)

![001](https://user-images.githubusercontent.com/51829747/66317946-1e1f3680-e923-11e9-874d-7ff71be8ad9b.JPG)

![002](https://user-images.githubusercontent.com/51829747/66318180-7eae7380-e923-11e9-8420-1f805737d8f2.JPG)

**Comment by pledbrook** [comment]
As far as I can tell, this only happens for VIP missions. Don't know why yet.

**Comment by TheReigningKing** [comment]
I just got a mission that is a Extract VIP mission, and the reward is an Intel Package. No personnel reward.

**Comment by pledbrook** [comment]
Someone mentioned this happens when soldiers have been captured and the game is trying to place that captured soldier as a VIP reward. Does that sound like it might be the case in your examples? Been a long time, so I can understand if you pass on the question.

**Comment by TheReigningKing** [comment]
Sorry too long ago.

**Comment by pledbrook** [comment]
So this is probably the "captured soldier" bug, because it applies to extract, rescue and jailbreak missions. WOTC changed the name of the reward template for captured soldiers, so the rewards simply break. Fortunately, the fix is very easy.
