### ISSUE TITLE
Possible bug in PerfectInformation.ini file, not sure

### ISSUE THREAD

**Issue by aturaki** [long-war-2/lwotc#671]
I have the mod installed and working, however, I wanted to try the extended information mod so I followed the instructions to disable perfect information:
"Edit the LWOTC] config file XComPerfectInformation.ini and change the ENABLE_PERFECT_INFORMATION entry to false "

I noticed the actual line was not terminated with a semicolon i.e the entire section reads:
ENABLE_PERFECT_INFORMATION = true

I was expecting to see:
ENABLE_PERFECT_INFORMATION = true;

I double checked the source in github and sure enough, the semi colon is missing there.
https://github.com/long-war-2/lwotc/blob/master/LongWarOfTheChosen/Config/XComPerfectInformation.ini

As the title says, not sure if this is a bug, but it seemed odd that every other entry was terminated with semicolon and this one was not.  

thanks!

**Comment by MrNiceUK** [comment]
Config lines do not need to be terminated with a semicolon. Arguably it's more correct to *not* terminate with a semicolon.

**Comment by aturaki** [comment]
Yeah, I looked through other config files and saw that.  I used to be a bug hunter, so whenever I see different styles used in a config file, it raises flags.   I always ask , "Well, it is ok to do this, buuuuttttt, what if.....".    

I guess it uses linebreaks to terminate and strips any semicolons if found at end.  Just wanted to flag it for the team.

thanks

**Comment by pledbrook** [comment]
That config was done by the Perfect Information developer, which is probably why the lines are terminated by `;`. They really shouldn't be. The `ENABLE_PERFECT_INFORMATION` config entry was added by me, so it doesn't have one.

BTW, I'll be looking to remove that config entry anyway. I should be able to work out whether the Shot HUD is the base game one or not in the screen listener without the need for players to change the config.
