### ISSUE TITLE
'Private Channel' Resistance Order does not do anything

### ISSUE THREAD

**Issue by Q-Plasmalord** [long-war-2/lwotc#673]
Title.
The first mission I loaded up after selecting it was an S&G, which was 12 turns, which should have turned 14.
I thought maybe it only applies to missions I actually detected after selecting it.
Well, I just went to another S&G, and it's still 12 turns.
Please take a look.

**Comment by pledbrook** [comment]
This is probably an issue specific to Smash and Grab and Jailbreak missions. (Or any of the old custom LW2 mission types)

**Comment by pledbrook** [comment]
This appears to be fixed (just tested it).
