### ISSUE TITLE
Boosted cores not working as intended

### ISSUE THREAD

**Issue by Q-Chaos** [long-war-2/lwotc#676]
Yesterday I fire grenaded a sergeant, who only took 1 burn damage next turn, same thing happened with a snake on a later mission.
Given how the description says it boosts DOT effect by one, the minimum DOT damage should be 2 at least.
I will do some more testing with gas grenades when I get back today.

**Comment by eraserman59** [comment]
Is it possible that the unit is being burned/poisoned by the resulting environmental hazard instead of the grenade itself, and as a result not triggering boosted cores?  I'm not sure if boosted cores would affect the fire or poison cloud left behind by the grenade.

**Comment by Q-Plasmalord** [comment]
No. not possible. I clearly saw the burning took place from the explosion
itself(Even got the message:'x' is burning), and that's not on one
occasion, but multiple.
Another thing. Just the other day, my fire grenade pulled a crit, and
scored a damage of 4 on a sectoid commander.
I repeat, score a critical hit of 4, while the minimum noncrit damage
possible is 5 with boosted cores.
There has to be something fundamentally wrong here.

**Comment by Q-Plasmalord** [comment]
Update: As of update build 11, this issue has yet not been fixed.
Boosted cores is still resulting in 1 damage from fire grenades.

**Comment by wdanny69** [comment]
can't reproduce the issue, boosted cores is providing burning damage of 2-4 (as expected)

reopen the issue if it still occurs, provide a modlist, a reproducible save (ideally) and provide as much details of what you are doing, how you are doing it, what has been done previously leading up to the issue and all info about the soldiers used
