### ISSUE TITLE
Full override does not lose charge if hack animation was cancelled before it completed

### ISSUE THREAD

**Issue by scmantikor** [long-war-2/lwotc#678]
related to #541 
complete hack
https://youtu.be/nth2cZgsA2I

hack animation cancelled
https://youtu.be/CfYJv7FrV-E

attached save
[save_IRONMAN- Campaign 1576.zip](https://github.com/long-war-2/lwotc/files/3714473/save_IRONMAN-.Campaign.1576.zip)

**Comment by pledbrook** [comment]
Depends on [Community Highlander #648](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/648).
