### ISSUE TITLE
Please support the controller

### ISSUE THREAD

**Issue by yangenqi** [long-war-2/lwotc#679]
Will you fix the longwar controller problem？
xd

**Comment by lordarter** [comment]
Hello everybody.
i have folowing issue:
on my gamepad Logitech F310D doesnt work Reload Weapon button (X) - not big issue and
Evacuation with Ranger (RB) - extremelly important ISSUE!!! cause every second mission requires evac.
i want to let you know that my gamepad perfectly works in original XCOM2 War of the Chosen and it is very-very comfortable to play this game using gamepad so i was sadly surprised when noticed that those 2 buttons doesnt work in LWOTC, although even with Long War installed and activated if i load my savings from original WotC - all buttons works perfectly.
another related issue which might helps you to fix this problem or mb to someone who has the same issues is this:
when its time to evac i do save the game and exit to main menu (cause by unknown reason it is not possible to change controller while you re in game)
so from the main menu i go to controller settings and - again it is not possible to change controller without restarting the game completelly, but i found a bag
you push LB which starts showing you list of game authors, escape it with (B) button
now you can change controller to mouse
save settings changings and exit
go load your save
push (P) on keyboard to call Ranger evac
save the game
exit to main menu
go to controller settigns - you cannot change controlle again (dont worry)
push Authors button then ESC it
change mouse to gamepad
(X) to save and exit
load game
play...but only till next mission with evac required.

fix that please please please!

**Comment by pledbrook** [comment]
Please raise individual issues for controller support that needs to be added or fixed.
