### ISSUE TITLE
Skins (aka weapon variants) as item customization

### ISSUE THREAD

**Issue by tunbridgep** [long-war-2/lwotc#684]
There are many mods out there which add new variants of existing weapons and armors. These variants are effectively skins - they have no impact on gameplay - and only exist to serve as alternate visuals. However, the game doesn't really support a way to have alternate variants in the customization options, so most mod authors tend to create a new item entirely just for the ability to use a new model.

There are some problems with this approach. It is inherently incompatible for the following reasons:
1. New weapons are effectively clones of the old ones. If a weapon mod (like LW2) changes the stats of some weapons, the "skin" versions will only have the default stats.
2. The new weapons clog up the selection menus
3. New classes sometimes cannot use the skin versions of weapons if they aren't configured correctly
4. Weapons that you produce in limited quantities have a separate quantity counter for each skin variant.

I propose a better system. Instead, all items should support "variants", which allow mod authors to very easily add new models, particle effect etc to existing weapons and items, without changing their properties. Armors sort of already have this through the customization menu, although it's admittedly clunky. These skins would always have the stats of their parent items, and wouldn't appear in the item selection menu, instead you would select a skin the same way you normally customize a weapon or armor item. Instead of adding this to LW2 directly, I would think this would be a better feature of the highlander, as it doesn't exactly fix any bugs or add new gameplay but does increase mod compatibility (in some ways significantly), especially since there are MANY weapon and armor skin mods on the Steam workshop, and almost all of them simply duplicate the existing weapon or item and change the model. There are also many base-game or DLC items (like the Resistance Warrior armor and the TLP item/weapon variants) which do this too, further clogging up the menu, and they should probably also be moved over to this new system.

Imagine using, say, the [Mercenary Plasma Rifles Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1701830636) and a handful of other weapon skin mods, but having proper compatibility with any mod that modifies weapons (not just LW2), and a non-cluttered weapon menu. Obviously, these weapon skin mods would have to be updated to use the new system, and new weapon mods might have to be made to work with the Highlander (unless it can be somehow made to detect new weapons and assign them skin compatibility automatically). This would mean that ANY skin mod made compatible with the highlander would automatically be compatible with any gameplay mod that relies on the highlander, even if it modifies item statistics.

I am not a modder myself, so I don't know the intimate details of how this works, and I fully understand that this suggestion is likely to be rejected because it's not a mission-critical issue, because of it's complexity, or it might simply be impossible within the engine. But I do think it would make things significantly easier for everyone, as mod authors wouldn't have to make LWOTC versions of their weapon skin mods, and players wouldn't have to make sure they are using weapon skin mods that are compatible with their (possibly over a hundred) gameplay mods.

**Comment by Grobobobo** [comment]
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/687
