### ISSUE TITLE
Additional Faction Soldiers

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#685]
Ability to recruit extra (2 total) faction soldiers from each faction, even if they are not your starting faction.

This should require a MSGT soldier to accomplish.

See RealityMachina mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1126788564

**Comment by Fallguy55** [comment]
I don't think it should require master sergeant. Maybe gunnery sergeant? Or maybe it should require a mid rank officer to complete the mission. I feel as if two of each faction soldiers isn't so overpowered as it would have been in vanilla, being as though your forces are spread much much wider in the long war setting.
