### ISSUE TITLE
New enemies in WotC need Render projects

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#689]
I don't believe any enemies in WotC have corresponding render projects. Currently only action is to sell them.

Specifically: Priest, Purifier, Spectre

**Comment by Anthogator** [comment]
How much should they be worth? Here are my thoughts:

Priest: 3 Elerium (Only 3 other renders offer elerium and one of those is an elerium core render. Faceless offer 2 and Archon offer 5. I feel a Priest is worth more than a Faceless but not near as much as an Archon.)

Purifier: 3 Alloy (Consistent with Shieldbearer and Stun Lancer)

Spectre: 5 Alloy (Less than Chryssalids and Andromedons, but more than Mutons. Equal to Berserkers.)

Full list below for ease of reference:
RENDER_REWARD_ELERIUM_CORE=8			; Elerium Dust
RENDER_REWARD_SECTOID_CORPSE=3			; Alien Alloy
RENDER_REWARD_VIPER_CORPSE=3			; Alien Alloy
RENDER_REWARD_MUTON_CORPSE=4			; Alien Alloy
RENDER_REWARD_BERSERKER_CORPSE=5		; Alien Alloy
RENDER_REWARD_ARCHON_CORPSE=5			; Elerium Dust
RENDER_REWARD_GATEKEEPER_CORPSE=10		; Alien Alloy
RENDER_REWARD_ANDROMEDON_CORPSE=6		; Alien Alloy
RENDER_REWARD_FACELESS_CORPSE=2			; Elerium Dust
RENDER_REWARD_CHRYSSALID_CORPSE=6		; Alien Alloy
RENDER_REWARD_ADVENTTROOPER_CORPSE=2	; Alien Alloy
RENDER_REWARD_ADVENTSTUNLANCER_CORPSE=3	; Alien Alloy
RENDER_REWARD_ADVENTSHIELDBEARER_CORPSE=3; Alien Alloy
RENDER_REWARD_MEC_WRECK=5				; Alien Alloy
RENDER_REWARD_TURRET_WRECK = 3			; Alien Alloy
RENDER_REWARD_SECTOPOD_WRECK = 12		; Alien Alloy
RENDER_REWARD_ADVENTOFFICER_CORPSE=3	; Alien Alloy
RENDER_REWARD_DRONE_WRECK = 2			; Alien Alloy
RENDER_REWARD_MUTONELITE_CORPSE = 6		; Alien Alloy

**Comment by Anthogator** [comment]
After discussion with Peter, these have been agreed to be set at the following:

Priest: 3 Alloys
Purifier: 3 Alloys
Spectre: 4 Elerium

**Comment by mdger** [comment]
I made a pull request with the proposal of Peter
