### ISSUE TITLE
"Infiltrate" Resistance Order not working?

### ISSUE THREAD

**Issue by Grognerd** [long-war-2/lwotc#69]
Infiltrate, the Resistance Order which is supposed to not start the mission timer until concealment is broken, does not seem to be working for me in LWOTC. The timer runs at mission start, concealment or no.

A slightly larger issue: The "hard" mission timer is of greatly reduced importance in LW2; the biggest time pressure is generally caused by the "soft timer" of incoming reinforcements. Perhaps the Infiltrate order should be retooled to delay reinforcements instead?

**Comment by pledbrook** [comment]
This is probably down to most LW2 missions using a custom timer implementation. There is a larger question over what to do with resistance orders and sitreps, not just Infiltrate.

I think we'll have to look at sitreps and resistance orders on a case-by-case basis and decide what to do with each one. For example, it may be best to just remove Infiltrate. Alternatively, it could be used to boost infiltration by a small amount.

**Comment by ansabalirai** [comment]
Agree that sitreps in general would need an overhaul. In the case of infilitrate, IIRC some LW2 GOps do have the timer not starting before concealment is broken. Maybe that can be reused?

**Comment by pledbrook** [comment]
This will probably be looked at as part of a rework of resistance orders. For now, resistance orders are disabled by default. Closing to reduce congestion in the issue tracker.
