### ISSUE TITLE
after 12 months in game

### ISSUE THREAD

**Issue by alexu4326** [long-war-2/lwotc#692]
1 I dont know how to disable dark events ( 2 regions liberated but all dark events still in place)
i dont remember if dark event is disabled for liberating region or destroy advent facility.

2 advent scaling health and weapone damage is to high ? maybe i am paranoid but i need 2 3 xcom sergents with magnetic weapone to kill an advent shock trooper/advent longbow etc

3 in long war when i skullmine a advent i had option to find a facility lead ( now i dont)

**Comment by pledbrook** [comment]
1. You can't disable dark events except via a console command. What you _can_ do is complete missions that prevent the dark event from becoming active, but you have to find those missions and they often spawn in regions you haven't contacted.

2. Yes, that sounds about right. You should have Gunnery and Master Sergeants by the time you encounter those units. And you should have Coil Guns and/or plasma 12 months into the game. Longbows are susceptible to hacks, Combat Protocol, Whiplash, Trojan Virus, etc.

3. I think facility lead is one potential hack reward. It's not guaranteed.
