### ISSUE TITLE
What do I need to do in the XcomEncounterLists inis to add mod enemies

### ISSUE THREAD

**Issue by DarkFalcon81** [long-war-2/lwotc#698]
I read the instructions in the XcomEncounterLists ini about adding mod enemies, but they just weren't clear enough for a newbie like me to understand, where can I find more information about this and/or maybe a tutorial? I don't understand the spawnweight thing for example, if lower number means more frequent appearances or the other way around.

**Comment by DarkFalcon81** [comment]
And Im supposed to do ini changes to the XcomEncounterLists.ini file or for the ini file for the mod enemy in question? That I'm not sure about either. :(

**Comment by DarkFalcon81** [comment]
I managed to figure it out by myself how to do it. Didn't think I had it in me, lol.
Here's how I did it, I used Wilko's excellent [WOTC] Advent Medic as test subject.

Here's how to do it:

Step 1: Locate the Config folder where the XcomEncounterLists ini for the mod in question is; in this example for the medic it's parent folder has the ID 1177720393. (The id you can find on the steam page for the mod).

Step 2. Open the XcomEncounterLists ini in notepad and delete everything in there except the top line that says [XComGame.XComTacticalMissionManager]   Don't worry, nothing bad will happen.

Step 3: Now you need to locate the XcomEncounterLists ini for the LongWaroftheChosen mod, which you will find where you installed it in it's own config folder.

Step 4: Open this other XcomEncounterLists ini here, just like you did with the Medic one, and then find the the lines for the grenadier. Copy and Paste the whole thing from Grenadier M1 to M3 and copy all of this in the Medic ini in which you deleted everything.

Step 5: In notepad, click on Edit and then choose "Replace". Find AdvGrenadierM1 and replace with AdvMedicM1. Do this with the other tiers as well and then save. And voila, that's it. The Advent Medic will now share the spawn pattern with the engineer/grenadiers. 

Step 6: Buffing the stat on the medic can be done in another ini if you want it to be more in line with LWOTC. Mostly a bit of an HP buff is what is needed. Other than that it will work fine out of the box from my testing. 

Hope this small tutorial can be of help for other ini config newbies. I'm so happy I got this to work, have never done anything related to coding before, so this was complex for me to figure out ;)

**Comment by copyrite** [comment]
Unfortunately, there are more appropriate places for this information than the issue tracker.
