### ISSUE TITLE
Advent Vanguard Close Combat Specialist don't work

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#699]
[save_Advent_CCS_1.zip](https://github.com/long-war-2/lwotc/files/3756062/save_Advent_CCS_1.zip)

![001](https://user-images.githubusercontent.com/51829747/67292972-6d9d5f00-f4ec-11e9-892f-6a1052f27623.JPG)

**Comment by BlackRose39** [comment]
Just to add, the elite sidewinder doesn't move after it triggers "Hit and sliter."

**Comment by Grobobobo** [comment]
Almost none of the "active" alien abilities worked. Likely an AI issue.

**Comment by BlackRose39** [comment]
CCS needs to apply to the primary weapon slot of the unit as well as other abilities that require a slot.

**Comment by Grobobobo** [comment]
That's it? That's what wasn't working? I'm 99% sure that's a config change

**Comment by pledbrook** [comment]
See [this pull request](https://github.com/long-war-2/lwotc/pull/739).
