### ISSUE TITLE
Reinforcement flares visible when loading a tactical save game

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#70]
See the EvacBug2 save game from #38. The reinforcements appear after a few turns, with the flare/psi gate teleport appearing the turn before.

**Comment by cicero225** [comment]
I would like to note that this seems to only occur on loading a save game - it doesn't happen when the mission is played straight through from the avenger.

In case it helps, here's another save that shows this - when you load you can see the psi-gate immediately, and the reinforcements show up the next turn.
[save_SpottableReinforcementLocation.zip](https://github.com/long-war-2/lwotc/files/3120154/save_SpottableReinforcementLocation.zip)

![20190426000311_1](https://user-images.githubusercontent.com/1408556/56790338-2b9f9480-67b9-11e9-8bbf-6b6e139650b8.jpg)

**Comment by TLabsPeter** [comment]
I have encounterd with this bug too.

It would be nice, to know where will the enemy appear. (Maybe you can give it as something you can research in time, or some psychic ability or item, what gives you a heads up. You can do it too separate thing with the flares and the psi-gate)

I can understand that too, if you decide, that you remove this. Right now, after you reload a save, you can see either the red flares or the psi-gate the round before the reinforcement comes.

And I don't know wheater I should make a separate issue about it, so I try to report it here first:
In the left corner there is the reinforcement tag:
Its not conclusive.
The messages: Warning, Incomeing, (there was a 3rd, but I forget), does not relate to how soon will an enemy group appear. It changes sometimes, but does not help. It would be better if it gave a warning, maybe a few rounds ahead (for example, when it swithes to incomeing, the enemy arrives in 1-3 rounds). Or it should stay static. But now it is really annoying.

**Comment by ToastedAmphibian** [comment]
@TLabsPeter 
When the flares are visible is determined by difficulty. I think Rookie shows them, and all others are not supposed to, but could be wrong. The reinforcement tag has been noted in a previous. When it goes from yellow to green, it is supposed to be going from yellow to red. Typically your soldiers will give out a voice call the turn immediately before reinforcements appear, if that helps out in the meantime.

@pledbrook 
I believe this bug happens just as frequently for me in vanilla longwar2. Also, sometimes the Evac flare vanishes upon loading. The counter is still there, and Firebrand still arrives on time, but the little blue indicator flare is not.

**Comment by pledbrook** [comment]
You're correct. Reinforcement flares should only be visible on Rookie.

**Comment by pledbrook** [comment]
Fixed by [this pull request](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/1098).
