### ISSUE TITLE
Specialist unable to hack from outside visual range

### ISSUE THREAD

**Issue by Swarbs1982** [long-war-2/lwotc#701]
[save_QUICKSAVE- Campaign 18, Mission 28, Turn 8.zip](https://github.com/long-war-2/lwotc/files/3762140/save_QUICKSAVE-.Campaign.18.Mission.28.Turn.8.zip)

Liberation 1 mission to hack the objective. Specialist can't hack it from outside visual range, even when Shinobi is positioned within visual range.

Not an LoS issue, as I've checked from multiple angles, including through the large window to the left, currently covered by Muton / Sectoid pod.

**Comment by Swarbs1982** [comment]
[save_QUICKSAVE- Campaign 18, Mission 28, Turn 7_1.zip](https://github.com/long-war-2/lwotc/files/3762221/save_QUICKSAVE-.Campaign.18.Mission.28.Turn.7_1.zip)

Also confirmed as reproducible by reloading the autosave from Avenger and regenerating the mission

**Comment by pledbrook** [comment]
Apparently normal hacks (unlike Haywire) can't be used from squad sight.
