### ISSUE TITLE
Assaulted the same Chosen base twice bug

### ISSUE THREAD

**Issue by SydenInsomniac** [long-war-2/lwotc#702]
So in my game I killed the hunter and warlock chosen.  I never got the warlocks gun and just thought I needed to unlock some research or something and thought nothing of it.  But I just completed the infiltration of the Assassin's base and the Warlock was who I fought.

So basically I fought the warlock twice and never got to kill the Assassin.  At the end of the mission I did unlock the warlocks weapon finally but fighting the wrong chosen seems like a bug.

Saved game attached showing it's still the Assassin on the board.  But Warlock's base I end up going into... again.
![Assassin](https://user-images.githubusercontent.com/51498114/67452772-8b002500-f5e1-11e9-908b-1f7c399b2c3d.jpg)

Only using mods on approved list.
[Save files.zip](https://github.com/long-war-2/lwotc/files/3765670/Save.files.zip)
Attached Pictures showing Assassin icon on game map.
Save before assault on base starts
Save round before warlock is killed...again.

**Comment by nightmaRok** [comment]
Duplicate to same issues #439 , fixed in next build. Close #702

**Comment by pledbrook** [comment]
@nightmaRok You should have a GitHub invite for the Triage role. If you accept, you'll be able to close issues and add labels yourself.

**Comment by SydenInsomniac** [comment]
Thanks nightmaRok sorry missed the duplicate issue.
