### ISSUE TITLE
Mind controlled and hacked enemies that die during the effect don't drop corpses.

### ISSUE THREAD

**Issue by Grobobobo** [long-war-2/lwotc#706]
Can link save as an example
[save_AUTOSAVE- Campaign 99, Mission 1, Turn 6_1.zip](https://github.com/long-war-2/lwotc/files/3775054/save_AUTOSAVE-.Campaign.99.Mission.1.Turn.6_1.zip)

Kill the hacked drone, finish the mission and you'll notice that the drone wreck won't be collected. Same with purifiers (I encountered 3 this mission but 2 dropped).

Weirdly enough, dominated enemies that survive through the mission DO drop corpses.

**Comment by HarmlessOrange** [comment]
They also don't drop items if they have it.

**Comment by copyrite** [comment]
Duplicate of #1639.
