### ISSUE TITLE
Car lacking cover spots on front and rear

### ISSUE THREAD

**Issue by idontknow12** [long-war-2/lwotc#707]
The "ARC_ModernSedanA_NoDoors" is lacking cover spots on the front and rear side. I assume this is a bug because there doesn't seem to be a reason for it to not provide cover?
![20191026135926_1](https://user-images.githubusercontent.com/10792691/67623205-1acbec00-f7f9-11e9-8b2e-bb2ff7fe3338.jpg)

**Comment by wdanny69** [comment]
there isn't anything we can really do about cover
