### ISSUE TITLE
Disorient does not disable special abilities

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#708]
Assault still able to stun while disoriented. Pretty sure this was not possible in LW2

![20191027200941_1](https://user-images.githubusercontent.com/15093261/67649360-03265d80-f8f6-11e9-93ad-3b34a59e8b40.jpg)

**Comment by pledbrook** [comment]
I need a save file to find out what's happening there, because the associated abilities are configured correctly to be disabled if the shooter is disoriented.

**Comment by pledbrook** [comment]
Sorry, misread the code. This is intentional. Disoriented does not disable the arc thrower stun ability.

**Comment by nightmaRok** [comment]
It's possible, test it in LW2 1.5, doublebarrel also work while disoriented

![001](https://user-images.githubusercontent.com/51829747/67667729-234a3100-f977-11e9-83a9-ec981c36068c.JPG)
![002](https://user-images.githubusercontent.com/51829747/67667730-234a3100-f977-11e9-9596-bfeda2e96449.JPG)

**Comment by ansabalirai** [comment]
Hmmm that seems like an oversight surely? I thought disorient should disable "special abilities" like using your gauntlet, etc? Is it the same behavior for all LW2 classes?

**Comment by pledbrook** [comment]
I'm pretty sure it's *not* an oversight. Abilities have to be explicitly excluded from being disabled by disorient (not the whole story, but sufficient for explanation here). So this was done deliberately.
