### ISSUE TITLE
Game hanging on completion of research

### ISSUE THREAD

**Issue by Swarbs1982** [long-war-2/lwotc#709]
[SaveData.zip](https://github.com/long-war-2/lwotc/files/3779406/SaveData.zip)

Happens when completing resistance radio, and also lost autopsy after using console to give the first tech.

**Comment by pledbrook** [comment]
Was rectified as part of the [original pull request](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/634)
