### ISSUE TITLE
Can capture dead hostile VIPs

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#713]
You can kill a hostile VIP, pick up the body and evac the mission to earn any "Capture VIP" rewards. See: https://www.twitch.tv/videos/501680765?t=05h53m25s

**Comment by BlackRose39** [comment]
Might also want to check if putting down a VIP, then picking them back up again and evac weirdly results in them being considered dead in results. That was the case back in vanilla wotc.

**Comment by pledbrook** [comment]
The intel package gets rewarded whether VIP is captured or dead, so not a bug.

**Comment by BlackRose39** [comment]
Wait, if an enemy VIP is "dead," they can't be interrogated, so there shouldn't be any intel bonuses. (As hinted by intel package with capture only). Or was that changed between vanilla and lw2?

**Comment by pledbrook** [comment]
On Neutralize VIP missions with Intel and Intel Package rewards, the former requires a capture, whereas the latter does not. Who knows how killing a VIP is supposed to result in an intel package 🤷‍♂
