### ISSUE TITLE
mod luncher 

### ISSUE THREAD

**Issue by Napoleon231187** [long-war-2/lwotc#714]
I have an issue getting the mod started 

in my mod launcher are 4 out of the 5 mods what are required the only mod missing is LWOTC  one it is in the same mod folder as the highlander one so im a bit puzzled what is now wrong :-?

**Comment by Napoleon231187** [comment]
the game is fresh installed and only this 5 mods are installed

**Comment by idontknow12** [comment]
Can you send a picture of your
XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods

folder and of the LongWarOfTheChosen folder inside that?

**Comment by Napoleon231187** [comment]
![Untitled](https://user-images.githubusercontent.com/32913193/67988115-f4f27d00-fc26-11e9-9969-7a262c46d95f.png)

**Comment by Napoleon231187** [comment]
![Untitled2](https://user-images.githubusercontent.com/32913193/67988255-51559c80-fc27-11e9-8d58-7ed28a983433.png)

**Comment by idontknow12** [comment]
Your long war of the chosen folder is missing files, you need those! See if they are in the zipped folder you downloaded and then extract again.
Check pic:

![lwotc](https://user-images.githubusercontent.com/10792691/67989923-1cd7e580-fc13-11e9-8d3d-51b13727b722.jpg)

**Comment by Napoleon231187** [comment]
i downloaded it from here \Oo ok i have a look

**Comment by Napoleon231187** [comment]
i just looked in the folder there are inside why on earth did they not extract thx so much
