### ISSUE TITLE
Civilians triggering Pods making them go yellow alert

### ISSUE THREAD

**Issue by DarkFalcon81** [long-war-2/lwotc#715]
Not sure if this is a known issue or not, but I saw the other day in an episode of DerAva's playthru of LWOTC that civilians were screaming and making near pods go into yellow alert by themselves, and today in my own game it happened to me as well. (Advent spooking civilians on their own that is..)

**Comment by pledbrook** [comment]
He reported this on Discord, but I appreciate having it on GitHub, so thanks for raising it. I think this is probably dependent on [Community Highlander #666](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/666).

**Comment by nightmaRok** [comment]
#705

**Comment by pledbrook** [comment]
I'm an idiot. Thanks @nightmaRok . Closing as duplicate.
