### ISSUE TITLE
Add pistol slot

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#716]
Pistol abilities work erratically or not at all with the utility slot (#488), so adding a dedicated pistol slot seems to be the best option going forward. We can then balance around that.

Also relates to #597.

**Comment by Anxoczt** [comment]
So everyone will have a pistol ? Or will it be that a soldier needs to spend AP to get a perk that adds the pistol slot ?

**Comment by pledbrook** [comment]
Everyone except factions soldiers should get a pistol slot. Subject to change based on playtesting.

**Comment by HarmlessOrange** [comment]
I'm actually curious how that will go.

Currently I only have 1 soldier with pistol skills and even then I barely use it.

**Comment by Swarbs1982** [comment]
Personally I'd like to see pistols go back to the snipers and holotargeters become the utility item. Not sure if it's possible or easy to do, but it would give shinobis and reapers in particular another option from concealment. Also thematically more solid imo - the sneaky scout tagging high defence enemies from concealment so they can be better targeted by the snipers and other units. Could also give an option for improving the shinobi and reaper trees by including a holotargeting option as part of the tree.

Other classes could potentially have a dedicated pistol slot, but maybe as an optional replacement for their other secondary? Gunners and rangers in particular I think might get more use from a pistol in some cases than a knife or shorty, although it would mean grenadiers, technicals, specialists and psi would never use them.
