### ISSUE TITLE
Rebalance Templar (specific changes from beta 1)

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#717]
* Remove mobility bonus from gaining Focus
* Reduce dodge gained from Focus to +3/+6/+9/+12 (Templar starts with 10 dodge base)
* Use Standard Aim for hit calculations, but give gauntlets +25 Aim to hit
* Use standard random abilities for XCOM row (although keep psionic-specific perks)
* Add pistol perks row

Perks:

Rank | PsiBlade | Dynamo | Sage
----|----|----|----
SQ |  Rend  | Momentum | Volt
LCPL | Parry | Aftershock | Amplify
CPL | Overcharge |  | Channel
SGT | Deflect | Pillar | Stun Strike
SSGT | Reflect | Invert | Deep Focus
TSGT | Arc Wave | Exchange |
GSGT | Reaper | Ghost | Void Conduit
MSGT | Bladestorm | Supreme Focus | Ionic Storm

The main idea is to get the Templar to choose early how they gain focus, and therefore whether they are more geared towards using their psionic abilities or Rend. Nerfing the bonuses associated with Focus also makes it less detrimental to use Focus on abilities, which makes it much harder to go the caster route.

Also tempted to just straight up grant Deep Focus and Supreme Focus when the Templar reaches those ranks, but perhaps nerf some of the abilities that scale with Focus.

**Comment by Anxoczt** [comment]
Can Templars get combatitive perk ?

**Comment by gen-martox** [comment]
they already have Parry which blocks melee and there is a config option to let deflect block melee, which is off by default so they don’t need combative

**Comment by Grobobobo** [comment]
Volt is still bad
Aftershock is bad. I'm not sure if I'd pick it even if volt wasn't terrible. 
Amplify needs too much focus to be worth it.
Channel is a superior means of focus aquisition to overcharge, might need an increase to proc chance?
Deflect seems much stronger than pillar and stun strike
On the other hand, reflect can't compete with invert or deep focus
Void conduit can't compete with Ghost and Reaper

Overall not bad, It's gonna be a good tree with some ability changes. I still hate bladestorm on templars though

**Comment by gen-martox** [comment]
I have been using volt a bit more than I normally do and it’s not quite as bad as I remember it being. It’s still not great maybe we could increase it’s damage some or increase the range to hit multiple target?

If volt was good that would be more of a reason to get aftershock 

to me deflect and pillar are close, pillar is a free action that give high cover and can be used durning momentum. And deflect has a low chance of triggering so it’s not really reliable 

Reflect is great but so is having 3 focus points 

Templars have a primary melee weapon, there isn’t a reason they shouldn’t have bladestorm

**Comment by Grobobobo** [comment]
You should also consider removing the rend damage from focus, or at least reduce it.
If deflect is unreliable, then reflect is even more so, reflect only triggers after the deflect.

**Comment by allenhu0912** [comment]
I think removing rend damage from focus is a good idea, BUT there must be some other way to increase rend damage. As it stands, even with bonus damage from focus, Templars' damage output is something like half that of Shinobis, and it's best to use them as tanks instead. I don't think their damage dealing capabilities need a nerf when they're already kind of crap

I also think faction soldier XCOM abilities need to be balanced out. Some of them are really strong, such as Lightning Reflexes on Skirmishers. Hard Target and the templar aura are also very strong, and whether or not you have them can make or break a faction soldier. These should be guaranteed to either appear or not.

**Comment by gen-martox** [comment]
Just cut the damage gained from focus in half, so lvl 1 and 2 will give +1 damage and lvl 3 and 4 will give +2. There is no reason to completely remove it

 and the faction awc abilities aren’t any stronger than on normal soldiers

**Comment by Johannes38** [comment]
We really need to boost the base damage on the gauntlets then because as it is doing at max 13-14 damage endgame at 3 focus is absolutely pitiful, especially once we introduce the ability to miss with it.

Especially since Shinobis can easily deal 25+ damage with their swords at the same point.

**Comment by allenhu0912** [comment]
> Just cut the damage gained from focus in half, so lvl 1 and 2 will give +1 damage and lvl 3 and 4 will give +2. There is no reason to completely remove it
> 
> and the faction awc abilities aren’t any stronger than on normal soldiers

Yes they fucking are, Skirmishers can get LR at Corporal, for everyone else it was a T3 defensive AWC skill in LW2

**Comment by Grobobobo** [comment]
So, here are my suggestions:

- Remove, or at least reduce the Rend damage gained from focus

- Volt has the area suppression targetting, and it's damage now scales with LW2 better.

- Amplify now has 4 ticks regardless of focus

- Overcharge now has 100% chance to trigger

- Stun Strike now scales it's stun effect with gauntlets (2/3/4) actions

- Pillar now lasts 7 turns regardless of focus

- Swap Deep focus with Pillar

- Swap Invert with Exchange

- Rescale Ionic Storm damage and radius to be less reliant on focus amount

**Comment by gen-martox** [comment]
I think giving volt the area suppression targeting would be too big of a buff for the Templars. I don’t think a bit more damage would hurt

100% trigger for overcharge is a bit much, maybe 50-70%

Pillar and ionic storm are fine how they are and don’t need to be changed 

the rest is ok I guess

**Comment by Grobobobo** [comment]
They can handle a buff with a reduced rend damage. You're really overestimating just how much a templar uses a non-lethal slash.  Pillar is decent without this change but could use it too. Ionic storm sparks up the most complaints regarding the templar late game, might need to take a look at its focus gained on kill too.

**Comment by Swarbs1982** [comment]
Can templars gain a distance based damage bonus with Rend, similar to what Shinobis gain with Fleche? That could counter the removal of the extra damage with focus, and also encourage more aggressive play with Templars - striking the guy at the back rather than taking the nearest target to avoid triggering more pods

**Comment by pledbrook** [comment]
@Grobobobo It's hard to judge your comments and suggestions because they don't explain the reasoning. Why is Volt bad? Why is Aftershock bad? And so on.

It's also important to remember that Templar's damaging psi abililities do extra damage against psi units.

Anyway, I would like to balance around Templars starting with 1 focus and (effectively) gaining Deeper Focus and Supreme Focus automatically at SGT/SSGT and MSGT. Starting with 1 focus allows Templars to provide some utility/damage before any enemies have been killed. I think this is necessary for any caster-oriented builds, particularly ones that are used because the Templar lacks mobility and/or aim.

Automatic expansion of the Focus pool just makes sense in my head, and provides room for the other abilities. I just don't know that the decision between scaling and another ability that does something is particularly interesting. This is also because I suspect that those two abilities are must picks, regardless of build, even if it costs XCOM AP.
