### ISSUE TITLE
Rebalance Skirmisher (specific changes from beta 1)

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#718]
* Give Bullpup infiltration modifier of 0.9 (compared to SMG value of 0.8 and assault rifle value of 1.0)
* Use standard XCOM row abilities

Perks:

Rank | Hussar | Judge | Tactician
----|----|----|----
SQ |  Hit and Run  | Justice | Battlemaster (1)
LCPL | Reflex (2) | Retribution | Damn Good Ground
CPL | Heavy Ordnance | Wrath | Tradecraft
SGT | Formidable | Whiplash (3) | Full Throttle
SSGT | Forward Operator (4) | Shredder | Combat Presence
TSGT | Salvo | Judgement | Death From Above
GSGT | Implacable | Tactical Sense | Manual Override (5)
MSGT | Lethal | Reckoning | Battlelord (6)

1. Battlemaster has Damn Good Ground and Tradecraft removed from it (so basically just a grenade slot)
2. Reflex has a cooldown (trigger once per turn or once every other turn for example)
3. Align Whiplash with Justice/Wrath, i.e. costs one action point, not turn ending, +20 aim. Damage scales with Ripjack tech, i.e. 4, 7, 10. Long cooldown (5 or 6 turns)
4. Forward Operator can only trigger once per turn
5. Manual Override is a free action (6 or 7 turn cooldown, or maybe 1 charge)
6. Battlelord (no limit on number of times it can trigger; 1 charge? Or long cooldown?)

**Comment by gen-martox** [comment]
Salvo should be traded in for Total Combat, it’s the skirmisher version of that, minor detail.

Salvo and heavy ordnance should trade places 

Justice and Wrath having a 5 turn CD is too long which is why I changed it to 4

idk how I feel about FO, I kinda think it should stay gone, and I don’t think Shredder fits the skirmishers that well

Manual Overide should be free with a 5-6 CD

Battlelord should have  6-7 CD with the no limit

**Comment by Grobobobo** [comment]
I cannot see how a grenade-focused skirmisher would ever work, but I guess that's just me. 

Full throttle is just as worthless as before

I'd never pick tacsense at GSGT against implacable

I don't like this tree tbh, i kind of have a set build for that one too.

**Comment by Maebalzurakin** [comment]
As long as you are reworking this class, I think there are a few ideas to consider.

They have claws.  They should get to use them from level 1.  Claws should shred armor.  They should also have an unlockable ability to use the claws as a skulljack as seen in the intro movie.  Advent to witness a skirmisher killing another advent should have a chance to panic.

They should have bonuses when fighting advent.  Advent should have reduced detection range against them.  At high levels they should have an ability to use their formal neural link to cause fear, confuse or stun advent soldiers.    This could be balanced with their own weaknesses to Psionic Advent or Sectoids.

**Comment by Grobobobo** [comment]
So, here are my suggestions:

- Give ripjack crit damage (2/4/6)

- Swap Retribution with Wrath

- Full throttle bonus now lasts 3 turns and stacks with each other 

- Swap full throttle with Combat presence

- Give judgement scaling panic strength, simmiliar to napalm-x

- Replace Tacsense with Deadeye
 
I still dislike the tree, but at least the Judge and Tactitian options will be viable

**Comment by Grobobobo** [comment]
No, really, can we move the grenadier perks to the XCOM Tree?

**Comment by gen-martox** [comment]
it’s fine to have a couple of them on the main tree, especially something like salvo/total combat

**Comment by allenhu0912** [comment]
I don't see how Deadeye is useful on Skirmishers, unless it's supposed to be a nerf. Tac Sense is really nice when you play aggressively with your Skirmisher and activate a pod with your grappling hook.

I also don't see how Retribution aka Bladestorm currently fits Skirmishers, as there's no real incentive to be in melee range otherwise. It's just there as a failsafe skill that helps finish off a target you used Justice/Wrath on but failed to kill. Since some of the other skills involve tanking, Combatives would probably fit much better on the skirmisher

**Comment by Grobobobo** [comment]
Tac sense is garbage in just about any situation at GSGT If you've left 5 enemies one way or the other 15 defence is gonna do jack shit, and if not, the enemy will just target anybody else. Deadeye at least helps offset skirmisher's one main weakness, which is low base damage.

**Comment by DerAva** [comment]
Deadeye, at least in the current version, requires 2 actions to use, even for non-snipers. Unless you have a target that you can't Hit&Run it's a damage downgrade compared to two shots. Seems a bit too situational for a GSGT skill (unless it's changed to only require one action).

**Comment by Grobobobo** [comment]
Really? Probably should be 1 by default, just like precision shot then.

**Comment by Grobobobo** [comment]
One more fun way to implement Manual override is to make it work on your entire squad instead of making it a free action. Think of the support possibilities!

**Comment by pledbrook** [comment]
That seems like it might be too strong, but making it targetable (including on self) could be interesting.

**Comment by Grobobobo** [comment]
It's really hard to make sacrificing action economy for cooldown reduction "too strong", I think It's worth a try.

**Comment by pledbrook** [comment]
The grenadier Skirmisher would depend on the XCOM perks to fully realise itself as a great build. But it helps with shockingly low aim and mobility, plus it synergises well with the free actions the Skirmisher can get, since they can do something other than shoot (or use the Ripjack if Justice and Wrath are on cooldown).

Full Throttle probably does need to be removed or reworked. I just don't see how it can be made to work except (possibly) in exceptional circumstances (Reflex *and* Forward Operator *and* Advanced Teamwork /Command have been procced or used for example).
