### ISSUE TITLE
Can't train additional skills in training center - bug or feature?

### ISSUE THREAD

**Issue by insufferablesmartypants** [long-war-2/lwotc#720]
After the initial skill, I can't train from either of the other 2 class skills even after the training center has been built. The XCOM skills have opened up and can be trained. I have plenty of AP to spend.

Any ideas?

(Posted here and on Pavonis site)

**Comment by insufferablesmartypants** [comment]
Eureka!

Been searching since last night for any info on this.   Finally found a page that stated that it was definitely a deliberate feature in LWotC.

Is it possible for me to revert this change on my own system?   I loathe this change.  Training soldiers was the whole point of having a training center to begin with.

**Comment by eraserman59** [comment]
If you join the LW 2 discord and play the latest dev build, it's a second wave option.
