### ISSUE TITLE
Sabotage Covert Mission didn't remove any AVATAR progress. Bug or intentional? 

### ISSUE THREAD

**Issue by HarmlessOrange** [long-war-2/lwotc#722]
![20191101232815_1](https://user-images.githubusercontent.com/57143695/68071108-62152800-fd77-11e9-92b5-4db211f068ae.jpg)

**Comment by nightmaRok** [comment]
Do you have save file?

**Comment by HarmlessOrange** [comment]
Here is my save data, all of the safe files here should be from the same campaign https://www58.zippyshare.com/v/4PKzZ1NM/file.html

**Comment by HarmlessOrange** [comment]
I know in vanilla WOTC, having too many AVATAR facilities will nerf the Sabotage mission, making it reduce progress by 1 instead 2.

**Comment by Grobobobo** [comment]
There are 2 types of pips: one tied to facilities, and one to avatar itself. The golden path and CA reductions only work on the latter pips. This is unlikely to be a bug, it just seems like all the pips were facility pips so it had nothing to reduce.

**Comment by HarmlessOrange** [comment]
Does that mean I wasted my Sabotage mission and I won't be able do that again? (With the same faction, I mean)

If yes, maybe that should be changed.

**Comment by Grobobobo** [comment]
The most likely course of action is to remove the sabotage CA entirely and to replace it with a facility lead CA.
