### ISSUE TITLE
No ability points for defeating a chosen.

### ISSUE THREAD

**Issue by steven0202** [long-war-2/lwotc#723]
Hello,

in this mission I have beaten a chosen but it seems like I dont get any reward for it. My ability pool points were 3 before this mission and are still only 3 right after. Savegame is attached.
[WinRAR-ZIP-Archiv (neu).zip](https://github.com/long-war-2/lwotc/files/3801639/WinRAR-ZIP-Archiv.neu.zip)

**Comment by Grobobobo** [comment]
Fixed a while ago.
