### ISSUE TITLE
Can there be a limit on how many Faceless there can be inside 1 haven?

### ISSUE THREAD

**Issue by HarmlessOrange** [long-war-2/lwotc#724]
I just had a Rendezvous mission with _4_ Faceless.

That left me with 1 soldier and 3 resistance members.

Here's a pic.

![20191102222334_1](https://user-images.githubusercontent.com/57143695/68111574-bd6a2600-feef-11e9-8004-cf9b03d22947.jpg)

And here's the save file

[save_Faceless.zip](https://github.com/long-war-2/lwotc/files/3803334/save_Faceless.zip)

**Comment by Anxoczt** [comment]
Yep, happens when you deploy a soldier in a heaven that has so many of them already. Kinda why i send technicals as my advisors when heaven is heavily infested while i send Rangers to heavens where the infestation is low or not even existing yet.

**Comment by DerAva** [comment]
When the mission pops up you willl see, how many faceless there are on the mission. You can always opt to not go on the mission, the faceless will be removed from the haven either way.

**Comment by copyrite** [comment]
Closing as there has been a bugfix for this specifically.
