### ISSUE TITLE
Smash and Grab Mission wont let you open last crate.

### ISSUE THREAD

**Issue by spankahontis** [long-war-2/lwotc#726]
I've noticed a pattern in the Smash and Grab mission, NOT the Crate Marking one.
It's the one where you are in the ADVENT City Center, a Gene Therapy Clinic littered with crates you open to get the supplies, around 4-5 crates.
I've noticed they can all be opened except the 5th and final crate.

I have a Savefile here, about 5 turns left till reinforcements arrive.

I also have mods installed. (Including the Mandatory ones).
- Zhang Voicepack
- Japanese Voicepack
- More Nations and Names WOTC
- Xcom International Voicepack
- Evac All WOTC
- Capnbubs Accessories WOTC
- Extract Corpses WOTC (FEEDBACK: You don't get enough missions that drop corpses)

I hope this helps you

[Smash and Grab Crate Bug.zip](https://github.com/long-war-2/lwotc/files/3815173/Smash.and.Grab.Crate.Bug.zip)

**Comment by nightmaRok** [comment]
Load your save and restart level, soldiers pick all creates, so probably your mods conflict

![001](https://user-images.githubusercontent.com/51829747/68311884-e5f24b80-00ba-11ea-9168-866ce1798022.JPG)

**Comment by spankahontis** [comment]
I've just figured it out, that each soldier can only carry 1 crate.
Using the Fulten Harness from the Extract Corpses mod carrys a corpse and the crate contents away, allowing you to carry another crate.
So the mod actually improves on gameplay in this regard.

So, sorry I didn't realise how the mission works. It seems to be working as intended.
