### ISSUE TITLE
Allow the faction heroes to go on the Increase Combat Intelligence Covert action

### ISSUE THREAD

**Issue by Grobobobo** [long-war-2/lwotc#728]
Currently they can't, which is silly.

**Comment by Dragon-32** [comment]
Doesn't [WotC: "Increase Combat Intelligence" for everyone](https://steamcommunity.com/sharedfiles/filedetails/?id=1134537412) work with LWotC?

**Comment by Grobobobo** [comment]
It does, but it should be in the base mod.

**Comment by pledbrook** [comment]
Implemented in [this commit](https://github.com/long-war-2/lwotc/commit/f896352ddc4337cdab283a31e53a6938df8699b0).
