### ISSUE TITLE
Avatar progress reduction framework

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#73]
Based on my experience following through with the liberation chain and doing the HQ assault (at which point in LW2 you get the avatar progress reveal at the geoscape), there is no perceived change and the doom clock is still hidden. While that, in itself, might be an easy fix, a bigger issue is whether any adjustment is needed in terms of slowing/reducing avatar progress with the overhaul. For instance, the resistance order to reduce one tick each month is quite powerful and is basically equivalent to doing one HQ assault each month, it might be worth discussing if we want to introduce/balance additional ways of interacting with the doom clock. 
One example could be reducing the progress based on a Chosen stronghold assault (assuming they are incorporated within the mod) by 1/2/3.

P.S. I can share the save file in a few days when I have access to my PC

**Comment by Tylon01** [comment]
I had this experience myself. After the first liberation, The doom clock still remained as a hidden element.

**Comment by pledbrook** [comment]
The bug with the Avatar progress not appearing should be a separate issue.

**Comment by pledbrook** [comment]
I think I've already tracked down why the avatar progress isn't being displayed: a bunch of objectives, one of which adds the "reveal avatar progress" objective, were commented out.

**Comment by pledbrook** [comment]
While a valid discussion, this is probably something that will be revisited at a later stage just through other work. Plus the "issue" part should be fixed now.
