### ISSUE TITLE
Network Tower does not stun Codexes

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#731]
Currently have Tactical Analysis and Network Tower stun, and Codexes are not stunned, and not affected by Tactical Analysis.

**Comment by DerAva** [comment]
This is vanilla LW2 behaviour - network tower stun (and also arc thrower stun) would always clear at the start of the alien turn.

**Comment by TheReigningKing** [comment]
Just because it happened in LW2 doesn't mean it's not a bug

**Comment by Grobobobo** [comment]
It's not a bug, codices are just immune to stun. That said, I'm considering removal of said immunity with the autoloader nerf

**Comment by Swarbs1982** [comment]
Stunning a codex does prevent it from using its clone / teleport ability on the turn it is stunned tho', which is quite a useful outcome if you don't want it jumping around all over the place

**Comment by Grobobobo** [comment]
It's intended, codices are immune to stun.
