### ISSUE TITLE
Network Tower does not stop Chosen

### ISSUE THREAD

**Issue by TheReigningKing** [long-war-2/lwotc#732]
This is a balance thing, but if a Chosen is active, he can summon units the turn you activate the tower, and those units will not be stunned.
The Chosen can also arrive the turn you activate the beacon.

Stunning the Chosen maybe going too far, but not allowing him to summon non-stunned units or not allowing the Chosen to enter the fight if the Tower has been activated are decent changes in my opinion.

**Comment by Grobobobo** [comment]
As far as I know, the chosen shouldn't appear on the network tower at all.
