### ISSUE TITLE
Other Chosen Become Warlock When Hunted

### ISSUE THREAD

**Issue by Zoldnier** [long-war-2/lwotc#734]
This has happened on a couple of campaigns now - when I go in to the Assassin or Hunter base to kill them, the Warlock spawns instead. Cinematic, disruptor rifle, the whole deal. When I get back to the overmap the right Chosen is gone. Saves attached. It's not gamebreaking, just kind of weird.

[save_Warlock instead of Assassin.zip](https://github.com/long-war-2/lwotc/files/3826714/save_Warlock.instead.of.Assassin.zip)
[save_Warlock Instead of Hunter---.zip](https://github.com/long-war-2/lwotc/files/3826715/save_Warlock.Instead.of.Hunter---.zip)

**Comment by DerAva** [comment]
Duplicate of #439 - fixed in current dev build.

**Comment by Zoldnier** [comment]
Oh awesome, thanks! Sorry about the redundancy - it didn't come up in my search. Thanks for your help!
