### ISSUE TITLE
Add lategame knife for gunner or make vibroblade more useful with some CC

### ISSUE THREAD

**Issue by Anxoczt** [long-war-2/lwotc#735]
While this is outside of normal LW2, i think it would be great idea to add a lategame variation for gunners. Vibroblade is pathetic and doesnt hold up and only tickles Elite enemy troops. And given that Gunners arent a melee class, nor they have amazing mobility, there is little reason to bother with knifes. You are better of taking your chances and shooting your machinegun at close range since if it hits, it will most likely kill the target instantly vs pathetic shank.

When knifes keep the pace, they do have a usage for finishing off, but it stops at vibroblade and then goes downhill while gunners aim grows so his main weapon is the only weapon he uses.

Lategame variant could be done in two ways.
- The cheap way, after archon's autopsy, a proving ground project would appear that would bump vibro-blades damage.
- The harder way, to actually get a model and make Fussion-version of the knife.

Another alternative could be to simply add a useful crowd control ability for the vibroblade like combustion proc. So damage isnt the thing you go for, but crowd control.

Bleeding would make sense the most but the problem is such DoT is absolutely useless in game sense. Advent troops dont have a tendency to live for long and bleeding doesnt stop them shooting the gunner at point blank. So unless this bleeding would be upgraded to suppped up version of ignition then it would be useless despite on paper sounding good.

**Comment by Grobobobo** [comment]
There isn't really a reason not to, but it's a low priority change. I'm also definitely not spending money on a commision for a knife asset.

**Comment by HarmlessOrange** [comment]
Maybe give gunners a something like RAGE Strike from RAGE Suit. A Fleche that is a free action but without dmg bonus.

...Maybe as a perk.

Also gunners can actually get Fleche in XCOM abilities. Two of my Gunners have it.

**Comment by Anxoczt** [comment]
> Maybe give gunners a something like RAGE Strike from RAGE Suit. A Fleche that is a free action but without dmg bonus.
> 
> ...Maybe as a perk.
> 
> Also gunners can actually get Fleche in XCOM abilities. Two of my Gunners have it.

Hmm, never rolled it, but one of my gunners got bladestorm though, but given the stage i got it and that vibroblade is weak, its just more cream on top of combatitive. Slightly useful but not balance breaking.

**Comment by HarmlessOrange** [comment]
>     * The cheap way, after archon's autopsy, a proving ground project would appear that would bump vibro-blades damage.

Maybe alongside bumping the damage, it would also bump the stun chance.

Also to add to my previous suggestion, a 'Takedown' ability for gunners. It works like Fleche but instead dmg bonus it will disable enemy's weapon. One of Gunner's roles is to pin down an enemy, Takedown would help them disable key targets that are dangerous even when Suppressed.

For balance purposes it could have a cooldown of 2 turns, and would require the Combatives perk, meaning you need to sacriface +1 damage and Grazing Fire.

**Comment by copyrite** [comment]
Closing as Gunners now have access to Advanced Vibroblade.
