### ISSUE TITLE
MC Beserker knocked a Viper unconscious and now it can't be targeted

### ISSUE THREAD

**Issue by Swarbs1982** [long-war-2/lwotc#737]
[save_MC UC bug.zip](https://github.com/long-war-2/lwotc/files/3831265/save_MC.UC.bug.zip)

On a smash n grab, I dominated a Beserker and used it to attack a Viper. The viper was knocked unconscious, but now can't be targeted by any other soldiers. Similar to an earlier bug on a defend the relay mission where a Beserker knocked another Beserker unconscious and the unconscious Beserker counted as dead at the end of the mission

**Comment by HarmlessOrange** [comment]
Unconscious units can't act for the rest of the mission (unless you use Revive Protocol). They might as well BE dead.

**Comment by Swarbs1982** [comment]
Yes, but they can usually (IIRC) still be attacked by other units. I suppose it doesn't make as much difference if it's an enemy unit, as the aliens don't have any unit that can use revive?

**Comment by Grobobobo** [comment]
They can't.
