### ISSUE TITLE
Wrong chosen for Chosen Assault mission

### ISSUE THREAD

**Issue by BradyMorris** [long-war-2/lwotc#738]
Context: I have already killed the warlock chosen. I am now on the mission to kill the assassin. I am now in the final chamber but the game incorrectly shows my objective as Destroy the Warlock's Sarcophagus. The warlock also showed up in popup dialogue as if he wasn't dead, and when the battle started it was against the warlock instead of the assassin. I killed him again, and got his disruptor rifle as a reward again. 

However, on the geoscape it now has the warlock and the assassin marked as dead, so the game counted it as killing the assassin. 

I will update after fighting the hunter to see if it comes up again.

**Comment by ansabalirai** [comment]
I guess you are not on the discord server yet. This issue has been reported repeatedly, both here and on discord, and has already been fixed in one of the development builds after beta 1. Beta 2 should solve this issue

**Comment by BradyMorris** [comment]
Great, thanks.
