### ISSUE TITLE
13 Turns Left ADVENT are throwing Reinforcements after Reinforcements at me

### ISSUE THREAD

**Issue by spankahontis** [long-war-2/lwotc#746]
So I am doing this Rescue Operation, saving 6 Resistance members.
Gets to Turn 13 and they are sending Reinforcements.. It happens right?

But then after they send those reinforcements (1xADVENT Gunner 1xADVENT Mec/Green), more are on the way next turn.
Then again, and again.
I still have several turns left before i'm supposed to get over run like this?

Following Mods

   - Zhang Voicepack
   - Japanese Voicepack
   - More Nations and Names WOTC
   - Xcom International Voicepack
   - Evac All WOTC
   - Capnbubs Accessories WOTC
   - Extract Corpses WOTC (FEEDBACK: You don't get enough missions that drop corpses)

[save_Turn 13 Swarms of Reinforcements.zip](https://github.com/long-war-2/lwotc/files/3860673/save_Turn.13.Swarms.of.Reinforcements.zip)

**Comment by HarmlessOrange** [comment]
Yeah, that's pretty normal in Long War 2. 

When doing any kind of mission with reinforcements active (so basically anything that isn't 'Kill Everyone') you WILL be overwhelmed by the reinforcements if you don't haul your ass. Generally speaking you want to be gone before the reinforcements even arrive, or 2nd wave at worst. Any later than that and you'll see yourself overwhelmed.

Here's how the reinforcements in LW2 works. https://www.ufopaedia.org/index.php/Reinforcements_(LW2)

Also if you're playing on anything that isn't Rookie, the flare showing where the reinforcements will drop won't appear.

**Comment by ansabalirai** [comment]
Any chance rapid response DE is active?

**Comment by Chaotic-Entropy** [comment]
What was the level of infiltration before starting the mission?

**Comment by spankahontis** [comment]
I believe it was 'Vulnerable' and troop numbers was 'Extremely Light 7-9'.
I don't have the 'Rapid Response' Dark Event.
This has never happened on any other mission.
I've noticed this same problem in a previous build.
Identical Battlemap, it was also a Prison Break Mission. Building packages were all placed exactly the same positions and order.

**Comment by spankahontis** [comment]
It's not a Doom Reinforcement, they come in stacks of 8 Units.
First wave started as 2 Units, followed by another stack on the way.
Plus it's Rookie Difficulty, says you don't get D.R in Rookie, only higher difficulties.

**Comment by Swarbs1982** [comment]
I had that happen in LW2, IIRC something was corrupted with the game files causing the reinforcement counter to break. I needed to verify the game on Steam, restart the PC and reload a strat save (from Avenger / Geoscape) and it fixed the problem.

**Comment by Sanjyuuichi** [comment]
This also happened to me on a collect the resource crates. There were 5 crates left to try and steal, but I was getting 5 enemies dropped in per turn. Overwhelmed and I wasn't even half way through the mission. Let alone this was the second mission of my play through, so I was not nearly equipped enough to handle that many reinforcements.

**Comment by pledbrook** [comment]
As far as I'm aware, reinforcements are currently working as intended, although I dislike the way that cavalry/doom reinforcements work to "encourage" you to leave after completing the mission objective.
