### ISSUE TITLE
Played through on Veteran and here's what I found.

### ISSUE THREAD

**Issue by InterloperWest** [long-war-2/lwotc#747]
First off, thanks Peter and team for the amazing work.

So, just finished a play through on Veteran and here are the issues that I found in the 148 missions it took me.

1. The biggest one, I killed the warlock 3 times, although I fought the assassin and the hunter several times during regular missions, I never got to their hold out's. The game said I was infiltrating their holds and they were taunting me while I fought my way to the ascension chambers, but once I got there the Warlock was there all three times. The game continued as if I had killed the others but I never did. So I never got the other chosen weapons. My thought was that it is a possibly place holder?

2. The protect the supplies retaliation missions, the enemy drops in at the same place every time making the mission very trivial.

3. Some Dark event's didn't expire, even if I set them to expire in the menu. Like poison rounds, extra HP, combat reflexes etc.

4. A few times rewards would show as nothing on missions.

Other than that just a few glitches hardly worth mentioning, nothing game breaking, although don't play it on Iron man just yet ;). It ran pretty darn smoothly all things considered. Well done!

Just want to mention real quick that, holy mother of the messiah this mod needs more mission types, things got real repetitive real fast.

Anyways, I included a save file where I was supposed to be entering the chamber to fight the assassin, but guess who...

[save_LW assasin_1.zip](https://github.com/long-war-2/lwotc/files/3861103/save_LW.assasin_1.zip)
Keep up the good work fellaz.
Cheers!

**Comment by ansabalirai** [comment]
1 and 2 have been reported several times and were reportedly fixed in later builds.
Regarding 3, there are tactical DEs that are supposed to be permanent (as they represent the aliens teching up over time) and strategic ones that do expire. Consult LW2 dark events wiki to see which is which (although it does not contain the WOTC specific ones).
For 4, it would be good to know what the missions type was. Retaliation missions in particular do not give any explicit awards other than uninterrupted operations in havens.

**Comment by InterloperWest** [comment]
I was playing the 1.0 beta build. I think the mission types where you couldn't see the reward were rescue a defector. I could be mistaken, but it was most def. a regular infiltration missions.

**Comment by Anxoczt** [comment]
2. This is vanilla behavior, reinforcements drop in some coordinates derived from your troop locations so if you stand still while nuking them, they will drop on similar locations. Nothing new in LWOTC.

**Comment by Swarbs1982** [comment]
I've seen no reward shown on the rescue a defector mission a couple of times with the current dev version. It was usually in the late game (possibly only on liberation missions, can't recall). Never played one of those by that stage, so don't know what would have happened.

**Comment by spankahontis** [comment]
Beta 1.0 is an old build, as I was getting the Warlock in every Stronghold Mission as well.

**Comment by Anxoczt** [comment]
> Beta 1.0 is an old build, as I was getting the Warlock in every Stronghold Mission as well.

And where is the newest version then ? When i scroll at releases i only see Beta 1 and dev test which has no patchlog attached to it aside from adding a ability picture for sectopods resiliance.

**Comment by Swarbs1982** [comment]
https://www.dropbox.com/s/1220nq71sbdj0j0/lwotc-dev-0007.zip?dl=0

**Comment by pledbrook** [comment]
Beta 2 will be out shortly.

The missing mission reward only seems to happen when the reward is a VIP. It has been reported before (see #670).

Thanks for the feedback. We definitely would like to add more mission types, but each one is a fair chunk of effort.
