### ISSUE TITLE
One in progress infiltration is not progressing while others are. 

### ISSUE THREAD

**Issue by Ledzeff** [long-war-2/lwotc#750]
Squad "Hussar's" mission infiltration is only progressing 1 or 2 % over the 1 day 4 hour time that is left on the clock, while others will progress many % over the same time. 

Save: https://www.dropbox.com/s/xi3id6w4kw2nggk/save_infil%20percent%20bug?dl=0

Note: Just finished a mission which freshly spawned the rookie POI and just started infiltrating the mission in New Arctic, if that could possibly be relevant. 

~~Edit: I just remembered that I left the screen afk for a few minutes and when I came back it seemed to progress like normal so that may be worth looking into.~~ couldn't reproduce it, dunno why

**Comment by copyrite** [comment]
Old issue + user couldn't reproduce the bug. Closing.
