### ISSUE TITLE
Smash and grab crates on third floor on lost cities.

### ISSUE THREAD

**Issue by Harryalerta** [long-war-2/lwotc#752]
It happened to me twice when I had a Smash and grab mission on a lost infested city and some of the crates spawned on the nonexistent third floor of a building. I do have a save file if it is of any help.

**Comment by teepee2345** [comment]
This issue isn't unique to lwotc, I have encountered this problem in base WotC

**Comment by nightmaRok** [comment]
Duplicate #315  
Close #752
