### ISSUE TITLE
Arc wave kill grant extra action point from Reaper; Run & Gun and hit and run not working together.

### ISSUE THREAD

**Issue by Harryalerta** [long-war-2/lwotc#754]
I am not sure if those are working as intended so I decided to report anyway. 

Run & gun and hit and run not working together is probably for the best.

**Comment by nightmaRok** [comment]
Press yellow -?- on skill in game to see more information, on wiki same info
https://www.ufopaedia.org/index.php/Assault_(LW2)

![001](https://user-images.githubusercontent.com/51829747/69475606-d02d9780-0dd7-11ea-9c6e-44876b34b652.JPG)

**Comment by Grobobobo** [comment]
Working as intended.
