### ISSUE TITLE
Smash & Grabs only generating lg_GeneClinic_01_LW / City Center missions.

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#764]
Never seen a single instance of lg_Advent_Recruitment_01_LW in a Small Town or lg_RemoteScienceStation_01_SG_LW in Wilderness. Is there something causing that to be the case? I miss the variety, haha.

**Comment by pledbrook** [comment]
Fixed by [this commit](https://github.com/long-war-2/lwotc/commit/b66f9aa4f9eb6dd33a90333044a905968e0ab9d1).
