### ISSUE TITLE
Lost not appearing at all ever

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#765]
Hey, guys, another minor thing: Lost are supposed to be appearing after FL3. Before FL3, I was getting missions and none of them gave me the Tygan verbal warning at squad selection about Lost being present. Rightly so. Then, FL3 popped and I have gotten at least 3 missions where he's said the Lost would be present and... nada. Done the missions, they were in Abandoned Cities. No Lost at all.

**Comment by Clibanarius** [comment]
Whoops, update on this: I have seen the lost since using dev-0007, but only extremely rarely, like on Supply Extraction missions in abandoned cities.

**Comment by DrBots276** [comment]
Same thing on my end, do you have any mods than affect the lost?

**Comment by ansabalirai** [comment]
This is all expected. With no sitreps, this is how the lost are functioning at the moment.

**Comment by Clibanarius** [comment]
Makes sense, thanks!

**Comment by pledbrook** [comment]
I'm surprised they're not appearing on other Abandoned City maps. Which missions are they not appearing on exactly? We may need to update the mission Kismet to allow Lost spawns.

**Comment by DrBots276** [comment]
While the new update might have fixed it, for me the lost only appeared twice.  Both times where on an abandon city mission, but I've had around 5 missions on those map types.

**Comment by Clibanarius** [comment]
To answer your question about missions where they SUPPOSEDLY will spawn that they aren't spawning on: Abandoned City Destroy Relay maps. I've had three of those in my campaigns lately and in all I got the voice-over by Tygan to expect Lost presence in the area. And none spawned, even with me popping quite a few 'nades off.

**Comment by pledbrook** [comment]
Think I found the issue. If there are no Lost on the map, the Lost reinforcement swarms are disabled. And since the LWOTC Lost missions start with no Lost, they're disabled from the start. For some reason, this behaviour is different for Destroy Relay vs Supply Extraction. I'll try to see if there are any other missions like this.

**Comment by Clibanarius** [comment]
Nice find!

**Comment by DrBots276** [comment]
I recall that the mission where you access data/ hack a terminal also does not spawn the Lost.
