### ISSUE TITLE
Resistance Ring - Able to deploy Covert Action Before Ring finished

### ISSUE THREAD

**Issue by KarlKFoley** [long-war-2/lwotc#766]
So noticed that I was able to deploy a covert action before the Resistance Ring was finished. This accrued when I received my first supply drop when it went though Resistance Orders. It gave me the options to deploy on finding the 2 other faction or doing a single mission for current faction. Wasn't sure if this was a bug or expected behaviour.

![Covert Action](https://user-images.githubusercontent.com/42328649/69595240-24907b80-1053-11ea-86fa-a6f9417d6061.png)

**Comment by Clibanarius** [comment]
That's normal.

**Comment by Anthogator** [comment]
To expand on Clibanarius' comment, it is normal to be able to do one covert action at the start of every month without the resistance ring.

**Comment by KarlKFoley** [comment]
Thanks for clarification.
