### ISSUE TITLE
Pistols weight / mobility loss once you fill the sidearm slot

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#769]
Okay, so right now, Sidearm slots can't be cleared once filled with a pistol. Once you install a pistol on a soldier, it stays there and can only be swapped for other pistols. Not the biggest issue until... you see that all pistols have a weight of 1 right now, causing a mobility loss of 1 on a soldier no matter what once you've filled their sidearm slot initially! I recommend, with the sidearm slot now being on every soldier, you simply ditch the weight on pistols.

**Comment by Grobobobo** [comment]
Oh crap really? Welp, the pistol slot has been a massive nerf to XCOM apparently.

**Comment by ansabalirai** [comment]
I mean, I thought the intention was to nerf mobility but leave it to the player to equip it or not?
If so, then the only issue is not being able to remove it once equipped, for which the temporary "fix" is to have zero weight for pistols?

**Comment by Grobobobo** [comment]
Yeah, i think peter just forgot to include an "empty" option.

**Comment by gen-martox** [comment]
The pistol slot already comes with an empty slot option but when Peter put the restriction to only allow pistols he prevented the empty slot. The simple solution would be to undo the restriction, I don’t see the reason for it to begin with.

**Comment by pledbrook** [comment]
I did it to remove autopistols as an option. That may change in the future. Anyway, also noticed another bug: you can change pistol slot loadout while a unit is infiltrating.
