### ISSUE TITLE
LW unit class bugs 

### ISSUE THREAD

**Issue by GitWadeanthony** [long-war-2/lwotc#77]
The Shinobi and Ranger have the Reaper's Death Dealer perk instead of Executioner.
This is the line in the config, 
_(	(AbilityType=(AbilityName="Executioner",			ApplyToWeaponSlot=eInvSlot_PrimaryWeapon)), \\_

The Reaper doesn't seem to have this perk however- unless it's a hidden passive. I never played much of Wotc. 

![Capture](https://user-images.githubusercontent.com/49357270/55841365-e0b92800-5afc-11e9-926c-f3434afcbc9d.JPG)
![Capture2](https://user-images.githubusercontent.com/49357270/55841366-e0b92800-5afc-11e9-922e-4c2e31c2bd96.JPG)

Sparks can equip extra rocket and high pressure tanks but can't use them.
![Capture3](https://user-images.githubusercontent.com/49357270/55841395-fa5a6f80-5afc-11e9-9111-26702ba1e249.JPG)
![Capture4](https://user-images.githubusercontent.com/49357270/55841396-fa5a6f80-5afc-11e9-8167-3707e8b0d999.JPG)
![Capture6](https://user-images.githubusercontent.com/49357270/55841397-fa5a6f80-5afc-11e9-9ec6-da510bf568f7.JPG)

Shredder guns works fine.
![Capture5](https://user-images.githubusercontent.com/49357270/55841420-0c3c1280-5afd-11e9-91e8-8fd77990b086.JPG)

Edit: Sorry forgot to add what death dealer does
![death dealer](https://user-images.githubusercontent.com/49357270/55844156-f7b24700-5b09-11e9-8a44-bfd314be36ac.JPG)

**Comment by ansabalirai** [comment]
I noticed that too, but I always thought that when the LW2 classes were ported to WOTC, the perks were changed

**Comment by pledbrook** [comment]
I'm guessing the Executioner problem is because WOTC ~~stole~~ used that as the internal name for Death Dealer. Probably just need a new internal name for Executioner. Like "ExecutionerLW" if I'm being imaginative :smile:

**Comment by ansabalirai** [comment]
TBH, it is an interesting perk to replace, since it is not exactly executioner and may convince some people (certainly not me) to try a flanking shinobi. Crazy, I know...

**Comment by pledbrook** [comment]
Someone mentioned that SPARKs shouldn't be able to equip heavy weapons other than the shredder line of guns. Probably a related issue to the ammo.

**Comment by GitWadeanthony** [comment]
Yes LW2 only let the Sparks have the shredder gun line of heavy weapons (like the other soldiers) since they added Technicals, I personality don't feel having another unit have access to flamethrowers and rockets would make them too overpowered since they will get none of the perks but that's a balance issue for another time.

Another thing I noticed is that the Spark Rifles are missing the ability to equip weapon attachments that Wotc added. This I feel Sparks really need since in the late mid game/endgame aliens just get so much natural defense(+perks) coupled with dodge and Sparks can't really pump their aim since they lack PCS, weapons attachments, and small items.

It's a quick fix and I've already tested it. 
Just have to edit the slots in for SparkRifle_CV, SparkRifle_MG and SparkRifle_BM in XComLW_Overhaul.ini from 0 to 3.

![sparkrifle](https://user-images.githubusercontent.com/49357270/56334444-41cca580-6166-11e9-8c1c-e2567ff3d1eb.JPG)

I also don't feel like the hero units need to have their weapon attachments limited to 1 as well but I haven't searched for their weapons in the ini files yet.

**Comment by ansabalirai** [comment]
A somewhat related issue (maybe separate from this) is that any soldier class can currently equip rockets and flamethrowers instead of just shredder guns. Since this is not LW2 behavior, a fix might be needed.

**Comment by pledbrook** [comment]
@ansabalirai Are you sure? The only issue I'm seeing is that heavy armour allows you to equip shredder gun, high-pressure tanks, or an extra rocket, regardless of soldier class. Technicals should only be allowed the latter, while every other soldier class should only be allowed to equip a shredder or shredstorm gun.

As far as I can tell, rocket launcher, blaster launcher, and flamethrower are disabled (except for Technicals).

**Comment by pledbrook** [comment]
Wow, this was harder to fix than I expected, but it is all done now.

**Comment by pledbrook** [comment]
Fixed
