### ISSUE TITLE
Capped Kill XP sometimes miscounts the number of enemies on the map. (Also in LW2)

### ISSUE THREAD

**Issue by Anthogator** [long-war-2/lwotc#770]
Sometimes RNFs give kill xp even when every other enemy on the map has been killed. See this video for reference:

https://www.youtube.com/watch?v=Wn3HdZR0iQQ&feature=youtu.be&list=PLtdFbHeD9CNw-iBPC2FnRdBnmRYPMgmIO&t=1576

Note that this was also a LW2 bug.

It looks like Utilities_LW.uc is ultimately using the GetShadowChamberInfo function to determine how many enemies were on the map to determine kill counts. This may be causing some enemies, such as turrets, faceless, and chryssalids to count improperly against the kill xp cap?

**Comment by pledbrook** [comment]
What am I supposed to be looking at in that video? Note that LW2 had a bug where Wet Work would still grant XP even above the kill cap. That was fixed in LWOTC.

**Comment by wortkarg** [comment]
I've checked the videos from DerAva and he bought Wet Work a couple of episodes before that happens. That's it, i suppose. That means that despite the fix in patch 1.5 reinforcement farming was still possible in LW2, but is not possible in LWOTC.

**Comment by Anthogator** [comment]
Sounds like this old Wet Work bug is the culprit then. Closing this issue.
