### ISSUE TITLE
Bug: Black Market reverts to vanilla black market after first month.

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#78]
I have only just really started testing but I have found that after the first month the market goes back to vanilla functionality in that it goes back to dealing with intel instead of supplies. Not sure if this has been reported yet but I did not see it so I decided to report it.

This is potentially game breaking as it would make it too hard to use the black market.

**Comment by pledbrook** [comment]
After first month or might I have been after loading from a save? Do you have a save file with the bug in it?

I'm wondering if this is a similar problem to reinforcement flares appearing after loading a save.

**Comment by ansabalirai** [comment]
I had the same bug with the black market and for me, it happened after the first supply drop. Definitely a blocker

**Comment by pledbrook** [comment]
OK, I think I see the issue. The code that overrides the black market behaviour is called explicitly at the beginning of the campaign. But the general implementation relies on an event from the highlander, which isn't implemented yet.

Solution: add `OverrideBlackMarketGoods` event to the community highlander and move the listener to an `X2EventListener_` class from the LWListenerManager.
