### ISSUE TITLE
The Lost are now longer giving free actions on death, no matter the difficulty.

### ISSUE THREAD

**Issue by DrBots276** [long-war-2/lwotc#781]
I just installed the most recent version of the Beta, and the first mission I had contained the Lost.  I was playing on veteran difficulty, which to my knowledge would allow for "Headshots". But the lost where behaving like normal enemies  when killed. I went in to the config files and modified the " head shot" text but nothing changed.

**Comment by pledbrook** [comment]
Did you download beta 2 before or after it was officially released, i.e. when [this page](https://github.com/long-war-2/lwotc/releases/tag/v1.0-beta-2) went up? Check to see whether you have the [`DISABLE_LOST_HEADSHOT`](https://github.com/long-war-2/lwotc/commit/ab8ee9c1bde9bb27a860ad05c582160586ca0670#diff-1a46b2cb210700088dfc5f63191b7e77) setting in the mod's _XComLW\_Overhaul.ini_ file.

**Comment by DrBots276** [comment]
Well I got the version that's on your most recent reddit post, so I'm positive I have the most recent version.

This is from my config folder, the one you specified. 

; Per-difficulty enabling of the Headshot ability
HEADSHOT_ENABLED[0]=true
HEADSHOT_ENABLED[1]=true
HEADSHOT_ENABLED[2]=true
HEADSHOT_ENABLED[3]=true

**Comment by Clibanarius** [comment]
There's a high probability it's working but not for all your skills.

Go to XComGameData_SoldierSkills.ini, make sure lines 88-93 look like this:

[XComGame.X2Effect_TheLostHeadshot]
; Disable Headshot!
; !ValidHeadshotAbilities=()

+ValidHeadshotAbilities=LightEmUp
+ValidHeadshotAbilities=SnapShot

**Comment by Clibanarius** [comment]
Yep, just went into the repo to confirm that !ValidHeadshotAbilities=() made it into release. That's why people can't headshot Lost except with LEU and SnapShot. It's cleared out except for those skills. For you: Add a semicolon before that line and you'll get it working.

**Comment by pledbrook** [comment]
This was fixed in some commit. Bit hard to track down.
