### ISSUE TITLE
City Center VIP Vehicle Objectives spawning out of bounds

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#784]
So this is a thing I ran into the other day and I THOUGHT it might have something to do with Dr. Maldorb's map pack that I was using at the time. It wasn't the cause, however. Redrat on the Discord saw the same issue in his game. So I'm tentatively pinning this on line 98 in XcomPlots.ini, where Plot_CTY_LgObj_Mixed_01 is allowed to get a vehicle objective on it. Simple change:

    ObjectiveTags[0]="CityCenter", ObjectiveTags[1]="LargePlot")

https://cdn.discordapp.com/attachments/590853806175158272/649947266618097665/efbb5a9f25791499.jpg

https://cdn.discordapp.com/attachments/590853806175158272/649945111807131659/10262e8baff98453.jpg

Props to Redrat for mentioning this and providing the screengrabs

**Comment by pledbrook** [comment]
Have you been able to confirm whether making this change fixes the problem?

**Comment by Clibanarius** [comment]
Well, I won't know FOR CERTAIN for a couple of days. Once I've been through the city center maps a few times trying to get VIPs out of vehicles, I'll know. As it stands, best bet is to have this change go in for as many people as possible and then have them play regularly and see if they get it after the change. If I can have even a week or two to test this change out on my end to confirm it's working right, that'd be enough. I encountered the bug within a day before. I figure a week gives me clearance at the rate I play missions to be confirmation.

**Comment by Anthogator** [comment]
So I finally got to take a look at these plots in the x2 editor. I don't understand it at all, but I've noticed that the one plot that seems to be causing the issues, Plot_CTY_LgObj_Mixed_01 has a different what-I'm-assuming-is-an-objective-spawn-box than all the other plots that have vehicle tags.

Here is a picture for reference. You can see that the green line extends all the way to the outside in Plot_TWN_Retail_LgObj_01 for my exampled, and that it does not extend all the way in Plot_CTY_LgObj_Mixed_01.

Plot_CTY_LgObj_Mixed_01:
https://i.imgur.com/ut12AK5.png

Plot_TWN_Retail_LgObj_01:
https://i.imgur.com/MmFqlWo.png

**Comment by Anthogator** [comment]
Nope, scratch all that. I was dumb and didn't download the full content. Now that I can take a look at all the specific parcels, I have verified that Plot_CTY_LgObj_Mixed_01 is the only plot with a vehicle tag that does not include a street parcel with "Can Be Objective" checked, as can be seen in this screenshot of Plot_TWN_Mixed_LgObj_02.

https://i.imgur.com/MaaGTVV.png

**Comment by pledbrook** [comment]
Fixed with #794
