### ISSUE TITLE
Are Alien Relays meant to have ridiculous health?

### ISSUE THREAD

**Issue by DrBots276** [long-war-2/lwotc#789]
Each alien relay I have encountered has had a health bar comparable to that of a Boss enemy. Is this a new gameplay mechanic? Is there anyway I can change this? 

I'm playing on the most recent beta, but this issue has been a problem all campaign. I'm playing on the veteran difficulty.  

I should note that a sword slash from a shin-obi , makes the relay far for vulnerable to damage.  As in after a sword slash, the relay takes damage like everything else.

**Comment by ansabalirai** [comment]
Can you indicate how much exact health it has and which FL (or month in game) you are? Relays in general have much higher healths compared to vanilla and this is expected behavior similar to LW2. This is primarily to avoid stealthing destroy relay missions

**Comment by DrBots276** [comment]
The relays health bar is large enough to the point attacks of 5-10 damage have no noticeable affect on the relays.

**Comment by Anthogator** [comment]
There is currently a visual bug on the relay health bars where it only shows about 7 pips of health and does not tick down until it is reduced below that value. But it should have between 25-30 health or so (in the early game on Legend) and you are still doing damage to it when you hit it, even if it doesn't show it.

**Comment by DrBots276** [comment]
Well this mechanic is fine for normal missions, but is possible to keep this from happening on the Avenger defense mission? This is mostly an issue due to one of the Chosen and an alien ruler showing up on the same mission, along side the already large number of regular enemies.

**Comment by gen-martox** [comment]
Wait a second, you had a Chosen and an Alien ruler on the same mission? That shouldn’t be possible.

**Comment by pledbrook** [comment]
Working as intended. Please raise another issue if you think the Chosen and Rulers shouldn't appear on Avenger Defence, or shouldn't appear together. (I gather from martox's response that the latter shouldn't be happening anyway).
