### ISSUE TITLE
Balance Suggestion: Make bullpups have same mobility bonus as smg

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#79]
As the title suggests. This should help with the edge cases of where you get a skirmisher with 11 base mobility before items (which happened in my campaign). I actually already have the code written for this as I did it for another mod.

**Comment by ansabalirai** [comment]
Somewhat unrelated, but does vanilla WOTC have varying starting stats for faction soldiers (like not created equally/hidden potential in LW2)? 
Regarding mobility, since the base damage is more than smg but less than assault rifle, I think the mobility should be in the middle likewise. Maybe +1 or +2 rather than +3?

**Comment by GitWadeanthony** [comment]
Another thing to keep in mind is that they have a grapple and Justice right from the start so +3 mobility might be too much so I agree ansabalirai that +1-2 would be better.

**Comment by jmartinez989** [comment]
I actually brought this up because I actually had a skirmisher start with 11 mobility base before any items. With all 3 items they have only 8 mobility. I understand that skirmishers can get around alot but with only 8 mobility they would be crippled. Mainly only good for like any mission that is not timed.

Though I guess that may be another interesting take on them, to be specialized units for certain types of missions.

I am actually more in line with giving bullpups less than smg mobility wise but skirmishers should definitely be starting with a higher base movement speed. Though this could be a bug with not created equal in that it likely didn't add to mobility enough times likely do to not having enough points to give them proper movement.

**Comment by jmartinez989** [comment]
On the topic of having the code written for these abilities, is there a way to compile the mod with the new code without having to install the sdk? I really dont feel like installing it again.

**Comment by pledbrook** [comment]
This is a bug: #80. The faction soldiers shouldn't have a mobility lower than 13. You'll see in that issue which config file to edit to fix the problem.

**Comment by pledbrook** [comment]
BTW, I'm leaving this issue open as I think there's still a case for adjusting the stats of the bullpup to reduce mobility penalty and perhaps decrease detection range. A similar case for the latter was made for Templars.

**Comment by jmartinez989** [comment]
I should mention that the skirmisher in question was acquired after completing the covert op to find the skirmishers. It seems that if I start a campaign with one it usually starts with about 13 mobility (has had that much every time I started a campaign. Not sure if coincidence or happens every time).

**Comment by pledbrook** [comment]
I wonder whether covert op rewards get randomised stats. They may not, but should.

**Comment by pledbrook** [comment]
@jmartinez989 You will definitely need the SDK to build the project, but apparently you don't need the `full_content` "beta" branch. The default "light" version of the SDK is said to be 1GB in size, which is significantly better than the 10s of GB for the full_content branch. However, some did suggest that Steam (or whatever) may check whether you have enough space for the full SDK and download that by default if you have.

**Comment by jmartinez989** [comment]
I am going to close this. Seems Bullpups are in a really good place now. Not as much mobility as smgs (+2 as opposed to +3) and slightly worse detection radius while also having about the same weapon ranges and t3 bullpups are about the same damage as beam smgs (slightly higher average damage as beam bullpups will do 8-9 damage whereas smsgs will do 6-10 so while smgs will be capable of a higher max damage the overall average damage of bullpups should be higher by a small amount).

**Comment by ansabalirai** [comment]
Just to check, is it a conscious decision to have smaller damage ranges on faction weapons? I can see the Spread=0 option in config, so I assume it can be changed. I didn't fully understand why that was the case in vanilla WOTC and whether we need to follow the same behavior here?

**Comment by jmartinez989** [comment]
yeah that is what vanilla had for those weapons and I actually agree. Thing is faction heroes had more tools at their disposal than regular soldier so having their damage ranges be more normalized was a good balance choice. I think that following suit in lwotc would be a good idea so long as the proper damage buffs come in for the higher tier weapons. If we need to adjust them as we start introducing more wotc stuff we can. As they are right now they seem to be in a good spot.

**Comment by ansabalirai** [comment]
Fair enough. I just wonder how to incorporate specifically skirmishers into a typical Gop:

Are they close range flankers? If so, they don't have extra crit chance and damage buff abilities
Are they medium range flankers? The weapon range table seems to suggest that is not the case
Medium range suppression build? Why not range or gunner instead and potentially do more damage per shot
They also do not get any infiltration bonus like shinobis (maybe looking like advent should give them an edge there?)
Perhaps others will have more luck playing around and finding a niche for them

**Comment by jmartinez989** [comment]
> Fair enough. I just wonder how to incorporate specifically skirmishers into a typical Gop:
> 
> Are they close range flankers? If so, they don't have extra crit chance and damage buff abilities
> Are they medium range flankers? The weapon range table seems to suggest that is not the case
> Medium range suppression build? Why not range or gunner instead and potentially do more damage per shot
> They also do not get any infiltration bonus like shinobis (maybe looking like advent should give them an edge there?)
> Perhaps others will have more luck playing around and finding a niche for them

hmmm... an infiltration bonus might make sense. After all they are former advent so they know the advent network well which would give them knowledge of things like advent patrol paths and missions strategies. This could be a good way to give them a bit of extra incentive to use them.
