### ISSUE TITLE
Bugged Cover 

### ISSUE THREAD

**Issue by j663beast** [long-war-2/lwotc#791]
![Picture](https://user-images.githubusercontent.com/57375060/69992829-76993b80-1542-11ea-8890-3f6168f4146b.png)

My modlist has no map pack changes and almost all the mods I have are from the required and suggested mods (with voice packs).

This is the first mission of a new Beta 2 campaign.
[save_Bugged Truck.zip](https://github.com/long-war-2/lwotc/files/3913219/save_Bugged.Truck.zip)

Restarting mission and reloading saves both didn't change anything about this.

**Comment by wdanny69** [comment]
there isn't really much that can be done about cover
