### ISSUE TITLE
More upgrades at GTS?

### ISSUE THREAD

**Issue by HarmlessOrange** [long-war-2/lwotc#792]
I saw that the Faction Soldiers still have their own Tactics. How about adding some to XCOM classes?

My ideas:

Gunner - Padlock - Suppression now works on Shadowstep aliens (with 25% Aim penalty) and has 75% aim bonus when suppressing enemies with 'Lighting Reflexes'. (So  LR gives 25% aim penatly instead 100%. Still a hefty penalty but it's finally possible to hit those bastards.)

Gunner - Takedown - Attack any enemy within movement range with your knife, reducing their action points by 1 and disabling their weapon.

Shinobi - From The Shadows - Hacking the objective won't reveal the squad as long as you received one of the hacking rewards. +50 Tech to all Shinobis.

Shinobi - Discipline - Sword attacks will never graze. (Now it will either hit or miss)

Specialist - Remote Control - Haywire and Hacking access points don't require LOS. (I fear this one might be OP, so if its possible then exclude the Objective hacks from this. If it's not possible then just lower the cooldown of Haywire by 1 turn.)

Specialist - Lootbox - Gremlin can now pick up items. (Basically this mod https://steamcommunity.com/sharedfiles/filedetails/?id=675346883 )

Technical - ??? - Rocket radius is increased by 1 

Technical - ??? - The flamethrower has increased chance to inflict 'Burning'.

Assault - Heavy Lifting - No mobility penalty for taking items.

Assault - Hard to Kill - Grants + 10 Defense and + 2 Ablative Health Points 

Sharpshooter - Shoot to Kill - Steady Weapon grants +15% Crit **OR** aim boost by Steady Weapon isn't gone when you shoot (but it's still gone when you do anything else.) 

Sharpshooter - Blindfold - Holotargeted enemies have a penalty to aim. (10/15/20 depending on Holotargeter. I was thinking the whole Holotarget mark getting into their eyes and making it harder for them to aim.)

Ranger - Opportunist - Either removes of halves the Overwatch penalty.

Ranger - Stick and Move - When attacking, + 3 mobility on the next move. When moving, +2 Damage and +15 Defense on the next attack. (Basically Stick and Move from this class https://steamcommunity.com/sharedfiles/filedetails/?id=1128300381 )

Grenadier - ...I got none.

SPARK - Malware / Robot Overlord / Trojan Horse - Allows SPARKs to use Haywire and grants them 25 Hack.

SPARK - So the Others May Live - Aliens prioritize SPARK over other XCOM soldiers. Grants 10 Defense.

SPARK - Maximum Overdrive - Overdrive's cooldown is reduced by 1.

Your thoughts? Do you have other ideas?

**Comment by Clibanarius** [comment]
Grenadier: Take Needle Grenades off the tree and add it to the GTS! Hell, that'd even make sense a little. (although Needle Grenades are potentially being reworked right now to add a little more damage to unarmored, which would be a nice change). I like these ideas, generally. Some of these skills already exist in Extended Perk Pack or Shadow Ops, too. Just ask Favid to use the code! Opportunist does, And Rush could be given to Gunners for a 1AP, 1move quick stab at a target.

**Comment by Grobobobo** [comment]
No plans for that.
