### ISSUE TITLE
More Dark Events?

### ISSUE THREAD

**Issue by HarmlessOrange** [long-war-2/lwotc#793]
The majority of suggestions are related to XCOM stuff, but what about the Ayyliens? They should also get some new things.

My idea are 'Research Dark Events'. Dark Events that ADVENT can endlessly repeat. With permanent, stacking bonuses. On their own they're small, insignificant things. But ignoring them will bring huge long-term problems. They take from 3 weeks-1 month to finish.

So that they can actually make an impact how about there's 1 random RDE every 2 months? With the first RDE starting on the 2nd month.

RDE - Basic Research - Non-Research Dark Events will take less time to finish (5-10% per RDE. Similar to XCOM's Basic Research)

_Scientists at ADVENT are certainly skilled, but there's always more to learn. - Dr. Tygan_

RDE - AVATAR Research - Speeds up the AVATAR Progress (3-5% Per RDE on Rookie-Commander, 5-10% on Legend)

RDE - Engineering Research - Better forces will arrive faster. (Force level will raise 0.5 day quicker)

And now for some other Dark Events:

Heavy Surveillance - Slows down the Infiltration OR removes 'Boost Infiltration. This is NOT a permanent Dark Event.  

Ambush - Remember Trap UFO from EW Long War? This is basically it. Every mission has a chance to have more enemies than currently shown (2-3 levels more). Chance increases with Vigilance level and decreases with Over Infiltration (with 0% at 200% infiltration). This is NOT a permanent Dark Event.

Tactical Research - A Plan - Increases the max and minimal amount of Dark Events the Aliens can do at once by 1 (so if they can do from 0 to 3, then after this Dark Event it will turn into 1-4 DE.)

Tactical Research - The Grand Plan - Increases the max and minimal amount of Dark Events the Aliens can do at once by 1 (Visible after A Plan has completed)

Tactical Research - The Final Plan - Increases the max and minimal amount of Dark Events the Aliens can do at once by 1 (Visible after The Grand Plan has been completed)

Because being swarmed by Dark Events is fun for everyone :)

**Comment by Clibanarius** [comment]
Ambush could feasibly just expand the chances of a Trap mission spawning. Those are already a thing, after all, where you'll get a seemingly-easy (hack?) mission with a long timer spawn, go in, and it's suddenly a dogpile (for if you've never experienced one). I think what you're looking for in some of these ideas are covered by Tactical Dark Events, the ones that are permanent. Like, Alien Conditioning already exists, in 3 waves, and makes the difficulty decidedly harder. I like the idea of trying to make the strategic game a little bit more capable of pushback, though, outside of simple Vigilance.

**Comment by HarmlessOrange** [comment]
Well, I had no idea Trap missions were a thing in Long War 2. There were no mention of these on the Wiki.

**Comment by Clibanarius** [comment]
Snare, I think it's properly called in the files. For reference:

[Snare X2LWAlienActivityTemplate]
iPriority=26
RequiredRebelMissionIncome=0
DiscoveryPctChancePerDayPerHundredMissionIncome=85
MinAlert=8
MinVigilance=6
AlertLevelModifier=-1
ForceLevelModifier=1

MissionTree[0] =	(	MissionFamilies[0]="Hack_LW", \\
						Duration_Hours=216, \\
						DurationRand_Hours=72 \\
					)

So at 8 Strength and 6 Vigilance, a 'good-looking' Hack mission will spawn and ~it's a trap~.

**Comment by Anxoczt** [comment]
I rather not want to have more DE going on at once, since most of the time player cannot do anything if the event like completes on the other side of the planet where you havent even contacted the local rebel forces. Unless more features would go in (Like Advent would prefer these DE more in XCOM territory to get results ASAP or some in-game explanation or something, or covert ops could counter dark events and let XCOM strike in a territory they arent present in but that mission would be like ??? for mission type and enemy troop concetration) then nope. Although some new dark events like you suggested could be added either way.

**Comment by HarmlessOrange** [comment]
> or covert ops could counter dark events and let XCOM strike in a territory they arent present in 

That would actually be a really nice Covert Mission. "Sabotage ADVENT's Research" Immediately stops a Dark Event (Kinda like Counter Chosen Activity). 2 missions per faction per campaign.

**Comment by Anxoczt** [comment]
> > or covert ops could counter dark events and let XCOM strike in a territory they arent present in
> 
> That would actually be a really nice Covert Mission. "Sabotage ADVENT's Research" Immediately stops a Dark Event (Kinda like Counter Chosen Activity). 2 missions per faction per campaign.

Charged based DE counters sound interesting, i would remove it to one DE counter per faction so the player has to chose more carefully. I would for sure save this for things like barriers, sealed armour or grazing fire, especially the barrier DE... i hate that one in particular.

**Comment by ansabalirai** [comment]
I'd argue that playing with those "temporary' DEs is what makes the game interesting and replayable, since it forces you to change your team comps and tactics. Even permanent DEs like iron skin make you rethink your shinobi speccing since swords become a little less useful.

**Comment by HarmlessOrange** [comment]
> 
> 
> > > or covert ops could counter dark events and let XCOM strike in a territory they arent present in
> > 
> > 
> > That would actually be a really nice Covert Mission. "Sabotage ADVENT's Research" Immediately stops a Dark Event (Kinda like Counter Chosen Activity). 2 missions per faction per campaign.
> 
> Charged based DE counters sound interesting, i would remove it to one DE counter per faction so the player has to chose more carefully. I would for sure save this for things like barriers, sealed armour or grazing fire, especially the barrier DE... i hate that one in particular.

Maybe instead of removing the DE in progress, the Covert Op would remove a Tactical Research that was already finished. Covert usually takes a long time, the DE would be finished before it completes. 

This way would probably be easier to code, and less of a chance for the bug to occur (like what happens if you go on a DE removal Covert Op, and the DE finishes mid-way?) Less of a headache while still achieving the similar result.

**Comment by spankahontis** [comment]
There was a mod out for WOTC where you could weaken a Chosen, give them a new weakness via covert ops, they were risky to complete, high Capture/Ambush Chance but in essence you could make defeating a Chosen that little bit easier if successful.

**Comment by HarmlessOrange** [comment]
I realized some Dark Events could be made by flipping around the Resistance Orders:

Rapid Information Processing - Aliens get additional AP on their next turn when revealed on enemy turn. The opposite of Tactical Analysis. This is NOT a permanent Dark Event (Possible variations: XCOM gets -1 AP when enemy pod is revealed on enemy turn // Aliens get +1AP PERMANENTLY, until the Dark Event is over.)

Tactical Research - Between the Eyes - All shots on Lost are instant kill. Now Lost are even less of a distraction.

Seekers - Increased chance of Capture and Ambush on the Covert Actions. (Low is medium, medium is high, high is guaranteed if it's possible). This is NOT a permanent Dark Event.

Rapid Self-Destruction - Enemies won't drop any loot. NOT a permanent Dark Event. (OR, Loot will take just 1 turn to self-destruct, instead of 3)

Uneducated - Soldier's XP gain is halved. NOT a permanent Dark Event.

**Comment by Grobobobo** [comment]
Thank you for the suggestions, but we don't think they'd fit LWOTC.
