### ISSUE TITLE
Integrate training center and infirmary

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#8]
Since the AWC has been split into two, all of LW2's AWC functionality needs to be rejigged. This includes all the localisation files that reference the Advanced Warfare Center!

**Comment by DerAva** [comment]
If the training center functionality from wotc is integrated then we need some class filters for the bonus abilities, similar to the AWC restrictions in XComLW_AWCPack.ini. At the moment they can get abilities they already have (screenshot) or abilities they can not even use.
![20190427003908_1](https://user-images.githubusercontent.com/49518216/57569608-c45c2400-73f7-11e9-85d1-6bcc807d79d2.jpg)

**Comment by pledbrook** [comment]
This has effectively been done. More specific changes should be handled by separate issues.
