### ISSUE TITLE
Guerrilla Tactics School upgrades draw 2 power instead of 1

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#802]
Turns out the -1 iPower draw for the slots in the GTS for officer training are baked into the scripts. Check X2StrategyElement_LW_OTS_OfficerStaffSlot.uc lines 66 and 92. Wouldn't be a problem, but the GTS upgrades are in XcomLW_Overhaul.ini as well, which is causing a doubling up of their power draws. You can confirm this by building a GTS and then adding a single Officer Training slot in, it'll SAY it's going to need 1 power, but actually knock 2 out in the Avenger power grid.

Recommend either removing iPower=-1 from the two lines in LW_Overhaul (the rest of the stat definitions should be unaffected there) or lines 66+92 from the script. Either way should work. I'm going to test the Overhaul.ini tweak method myself right now to make sure that way works best, as it's probably the least intrusive.

**Comment by Clibanarius** [comment]
![Clipboard04](https://user-images.githubusercontent.com/54611482/70409011-dd6d9780-1a0f-11ea-818e-f86833967042.jpg)
![Clipboard05](https://user-images.githubusercontent.com/54611482/70409012-dd6d9780-1a0f-11ea-9126-064399848026.jpg)
![Clipboard06](https://user-images.githubusercontent.com/54611482/70409013-dd6d9780-1a0f-11ea-83e6-4c9f0d20ebab.jpg)

**Comment by Clibanarius** [comment]
Changing XcomLW_Overhaul.ini to remove iPower = -1 from the two upgrades to the GTS yields 0 power draw. So that solution's out.

Anthogator suggests changing line 111 in the script from:

	Facility.PowerOutput += Upgrade.GetMyTemplate().iPower;


to

	Facility.PowerOutput = Upgrade.GetMyTemplate().iPower;

**Comment by pledbrook** [comment]
Fixed by commit above
