### ISSUE TITLE
Conflict with mod "Mission: Prison Break"

### ISSUE THREAD

**Issue by DenMartin38** [long-war-2/lwotc#806]
It's just a notice. 
I download mod "Mission: Prison Break". When i choose a vanilla mission "Escape" - (Don’t know how it is called in English version. You need to free a hostages from the prison), i can't control the hostages. Just can not click on them.
In WoT (without lw2) there is no such problem.
Sorry for my english and sorry if i wrote this in wrong place :)

**Comment by Grobobobo** [comment]
Ensuring compatibility with other mods is not our responsibility.
