### ISSUE TITLE
Upcoming Chosen Changes Part 3 - Showdown Behaviour, Avenger Defense and Chosen Weapons

### ISSUE THREAD

**Issue by Grobobobo** [long-war-2/lwotc#807]
This issue is about implementation of [my chosen changes proposal](https://drive.google.com/file/d/1wRUuNnb8g0eGpPsFKZalZWqaIrGv74IT/view) and less the discussion about it, as I feel it has been talked about to death already.

I wasn't sure how to have chosen have 2 seperate movesets untill i found [this kismet sequence](https://i.imgur.com/El8Jb0e.png) Now it seems more than doable, just gotta make a similiar one that disables the NL behaviours, and the Showdown ones will remain.

Avenger Defence Will be mostly about changing actual mission and some kismet parameters, not exactly ground-breaking.

As for chosen weapons, I actually feel like keeping them a secret for now, hee hee.

**Comment by HarmlessOrange** [comment]
In the google docs you said you're unsure about Chosen's weapons, but here you imply you have an idea what to do with them.

So are we supposed to give our suggestions, or do you already have a plan for these?

**Comment by Grobobobo** [comment]
That's the part that doesn't have to be as "Tight" design wise, so I haven't set them in stone yet.

**Comment by HarmlessOrange** [comment]
In that case

Katana:

- 3 less damage than Fusion Blade

- Never Miss nor Graze (or just never Graze if too OP)

- Never crits

- Assassin's Tracking - Free Action (3 turn cooldown) - Shows the direction of the nearest pod (Makes those yellow sound waves appear)

- +8% Defense and + 10% Dodge

_OR_

- Fleche grants +2 damage every 4 tiles. (But using Fleche or Slash leaves you with 1 AP less on your next turn)

- Assassin's Tracking - Free Action (3 turn cooldown) - Shows the direction of the nearest pod (Makes those yellow sound waves appear)

- +8% Defense and + 10% Dodge

So Scunts will be able to immediately know where to go, swordsmen will have either more damage or a reliable blade at cost of AP or DMG, and those weird guys going with the centrer branch will have higher defense and dodge.

Arashi:

- Aim penalty for long range is halved.

- -15% Aim

- 2 less damage than Plasma.

- 1 less crit damage than Plasma

- Refuge in Audacity - Free Action (4 turn cooldown) Every enemy within 4 tiles, and the targeted enemy can't retaliate. On enemy's turn the affected enemies are forced to shoot at someone else or perform other action. Lasts 1 turn. (They can still target the soldier indirectly.)

The main benefit of this weapon is Refuge in Audacity. Having your Soldier completely safe near enemies is huge and Assaults and Shinobis will benefit from that the most.  You can combine RiA with Run and Gun or Fleche to just move in, deal damage and laugh as you enemies are forced to take shots at your other comrades.

Disruptor Rifle:

- Damage comparable to Magnetic Rifle

+ 20% Aim 

- Standard shots has 100% to disorient enemies, including mechanical enemies. It will also reduce Hack Defense by 15. All lasts for 1 turn. 

- Shots at psionic enemies have 50% chance to inflict Stun for 1 turn (So if you hit that one Sectoid he'll be either disoriented or outright stunned. Either way you won't need to fear him)

_Or_

- Standard shots will inflict Disrupted. A new completely new debuff unique to the Disruptor Rifle

Disrupted: Enemy weapon is disabled and the next reload will end this unit's turn. Lasts 1 turn.

- Shots at psionic enemies have 50% chance to inflict Stun for 1 turn (So if you hit that one Sectoid he'll be either disoriented or outright stunned. Either way you won't need to fear him)

This is a support weapon.

Pitiful damage but with higher chance to hit and crowd control abilities. If you want to disable someone, you know who to use. If you want to finish off that one Muton with 1hp, this rifle has the bigger chance. If you want pure damage, go with Plasma. 

Darkclaw

I have no bloody idea.

**Comment by Grobobobo** [comment]
Scrapped.
