### ISSUE TITLE
Pistol costs on technicals is incorrect.

### ISSUE THREAD

**Issue by eraserman59** [long-war-2/lwotc#809]
Per discussion in bug reports channel of discord, technical pistol costs are incorrect (instead of 5, 15, 25 it's 10, 20, 40).  Supposedly an ini typo issue. 

In save compare technical ap costs on ability screen with other soldier costs. 
[save_Save 226.zip](https://github.com/long-war-2/lwotc/files/3943328/save_Save.226.zip)

**Comment by Clibanarius** [comment]
It's because of a typo in the XComPromotionUIMod.ini file. The class name is simply misspelled Techincal instead of Technical. Fix is obvious and easy!

**Comment by KaesoVenator** [comment]
Nice, I noticed it too, I posted about it a few days ago on the Discord, I came here to open the issue but thought of checking for "typo" first.
Lots of thanks to Clibanarius, fix is easy to implement on my own.

**Comment by Grobobobo** [comment]
Already fixed.
