### ISSUE TITLE
Freezing when zooming to newly discovered Chosen

### ISSUE THREAD

**Issue by TheSaneWonko** [long-war-2/lwotc#810]
This might be a duplicate of #535, which was created in September, but it happens with Beta 2. 
[save_strategic_1.zip](https://github.com/long-war-2/lwotc/files/3943531/save_strategic_1.zip)
 
I started a new campaign with Beta 2, so Lost and Abandoned should be disabled. It was still checked in the campaign creation screen, but was greyed out and thus not changeable. I'm using most of the mods in the steam collection "[LWOTC] Suggested Mods for Beta 2.0". Just encountered the first Chosen, and if I enter the Geoscape after return, the game zooms to the Chosen's location and freezes there. Time is still running, though. Just can't leave the map anymore.

**Comment by dkornishev** [comment]
I have same issue.

In the state described above all input is ignored except opening console (at which point I can type commands).

Sadly, don't see any errors in the logs.

**Comment by cyberpillow** [comment]
same issue.campaign started with chosen enable.

**Comment by cyberpillow** [comment]
btw,I recently found this only happens if the chosen‘s location zone wasn't connected.

when encountered hunter(who's base was in Asia which I haven't contact with the local resist .). I get the same issue.

so I load the save before the tower mission and this time encountered the assassin(who's base on the connected zone.) And there was not a freeze anymore.

**Comment by Killboy-tipa** [comment]
So if i load back and connect zone with the chosen i wont have any issues with other things, at campaign? Or i have no other choices than start a new campaign?

**Comment by Zvax** [comment]
Experiencing the same and it does seem to fit the "non-connected region" condition from above.
When finishing establishing contact with western europe, there's a zoom to the new available locations for scan, one of which is occupied by a chosen, and game hangs on the chosen. I've left it at its own devices for a half hour, was still hanging.

**Comment by TwinuX** [comment]
Did you enable the Lost and Abandoned tutorial mission, even unintentionally? Did your Gatecrasher have 8 soldiers, one of whom was a Faction Hero? If not, your campaign is unfortunately bricked, because of the aforementioned Lost and Abandoned tutorial.

**Comment by Zvax** [comment]
Hi! Thanks, I do not believe I have enabled the lost and abandoned tutorial mission, as I remember seeing a warning not to do so and I think I've heeded it, but possibly I inadvertently did.

There was 8 soldiers in gatecrasher, I don't think - or don't know if - one was a faction here, I have neither reapers, skirmishers or templars in my soldiers.

**Comment by TwinuX** [comment]
Yeah, L&A is accidentally enabled. There's some popup window that appears on older builds that overrides LWOTC's in-built disable for L&A, so it's easy to accidentally enable it without realising. Unfortunately, there isn't a fix for an ongoing campaign.

**Comment by Zvax** [comment]
Yes, I tried restarting a new campaign but said no to some popup about a LWOTC tutorial this time and there is a Shadow (reaper I think) in the gatecrasher squad.

Oh well, thanks for you time! Back to gatecrasher with me :)

**Comment by pledbrook** [comment]
I haven't heard reports of this, possibly because you can no longer enable the Lost and Abandoned mission.
