### ISSUE TITLE
Give Lost bonus damage for multiple hits

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#811]
Lost need to be more threatening, as they are often used by players to blunt the greater threat of aliens/ADVENT. To keep their threat a little unique and inline with their "threat from numbers" approach, we should add an effect that means a series of blows from the Lost increases bonus damage for each blow that hits. So being hit by one Lost could be shrugged off, two would hurt but be manageable, 3+ would be very dangerous.

**Comment by Grobobobo** [comment]
Oh, wow, that's exactly what I was thinking.

**Comment by Anxoczt** [comment]
So, pretty much a rupture but for lost. Cant wait for a sectopod to be mobbed by 7 lost gathered around it, hitting it for like 10 damage a pop even through armour.

**Comment by ansabalirai** [comment]
I thought this would only apply to xcom hehe

**Comment by pledbrook** [comment]
Consider this as part of the Lost rework, but doesn't necessarily have to be implemented if the reworked Lost don't need it.

**Comment by pledbrook** [comment]
Lost overhaul is done. Probably don't need this any more.
