### ISSUE TITLE
Grenade Panic

### ISSUE THREAD

**Issue by Shadewolfe** [long-war-2/lwotc#812]
I have two of my guys next to each other and one of them resisted a mind control, panicked, and pulled a grenade out... then blew himself and his buddy up. 5 man squad, smash and grab

[save_AUTOSAVE- Campaign 18, Mission 2, Turn 5.zip](https://github.com/long-war-2/lwotc/files/3943956/save_AUTOSAVE-.Campaign.18.Mission.2.Turn.5.zip)

**Comment by wdanny69** [comment]
this is a really old issue and no reports of panic has been made recently on unexpected panic behavior. provided save can't be used as its no longer compatible

if it still occurs please provide a save if reproducible, a modlist and as much details about the set up leading to the bug
