### ISSUE TITLE
GTS - Vanilla soldier rank requirements

### ISSUE THREAD

**Issue by TiCapriKWolf** [long-war-2/lwotc#813]
New combat tactics "Tactical Infiltrations" and "Large Unit Infiltrations" show a major and colonel soldier rank requirement instead of the long war ranks.

PS: Great work on this LWOTC team!

**Comment by teepee2345** [comment]
It requires a soldier trained to the Officer rank of Major

**Comment by TiCapriKWolf** [comment]
That was quick!  Indeed, I missed the officer part.
