### ISSUE TITLE
controller compatibility - Geoscape "Make Contact" & Squad Management "Create Squad" not accessible

### ISSUE THREAD

**Issue by aikomiko** [long-war-2/lwotc#815]
Using Xbox360 game controller with LWOTC, beta Highlander, community launcher, and the set of LWOTC required and 'recommended' mods, there are some important base game, and "new" UI buttons that are inaccessible via the game controller, e.g.:

* Geoscape ->  "Make Contact"  (controller moves the cursor but the "A" button no longer selects the new contact)
* Squad Management ->"Create Squad" (no controller mapping to activate this button)

Workaround:  Save game and temporarily switch from controller to K+M allows access to all of these buttons which then function normally.  

Thoroughly enjoying the LWOTC beta 2 which has been very stable with enjoyable challenging gameplay.  

NOTE: After getting LWOTC instance configured, I have been testing a good variety of WOTC mods in various new LWOTC campaigns.  Happy to report that other WOTC mods all seem to be generally working quite well with LWOTC. 

<img width="1351" alt="Capture" src="https://user-images.githubusercontent.com/58750335/71047473-973fc480-20f0-11ea-8d87-b16ab4ec67fc.PNG">

<img width="1331" alt="Capture" src="https://user-images.githubusercontent.com/58750335/71026106-57131e80-20bd-11ea-99c8-d1bd489f23e0.PNG">

**Comment by pledbrook** [comment]
The Make Contact has been fixed. Squad Management is currently disabled. I'll add the latter as a separate issue.
