### ISSUE TITLE
Crash on Mission Load;

### ISSUE THREAD

**Issue by RaynorCZE** [long-war-2/lwotc#820]
Hi,

I'm having an issue loading a mission, when there should appear the "door loading" game crashes, game is quite modded but Up until this point it ran normal without crash, it's about 3rd or 4th mission in this playthrough. Both Mod list and Log file will be attached to this post in zip file. Most of the mods are just cosmetics and few map packs that worked before and when I tried to load the map without them it also crashed.

Thanks in advance for response
[XCom-CL374751-2019.12.18-13.51.01_Logfile.log](https://github.com/long-war-2/lwotc/files/3978482/XCom-CL374751-2019.12.18-13.51.01_Logfile.log)

[XCom-DESKTOP-LN9SQ15-CL374751-2019.12.18-13.50.53-Crash.zip](https://github.com/long-war-2/lwotc/files/3978492/XCom-DESKTOP-LN9SQ15-CL374751-2019.12.18-13.50.53-Crash.zip)

.

**Comment by Clibanarius** [comment]
ActiveMods=DoctorMandarbsMap-Pack(WotC)

Found your crash-causing mod. You CANNOT use that mod with LWotC, no idea why, but it WILL cause this exact crash (usually upon trying to start a mission in the first month). On the plus side, if you disable it and try the mission again, it will load and you can continue with your campaign. It sucks, too, because Mandarb's is a good map pack.

**Comment by RaynorCZE** [comment]
Allright I'll try that, although I tried to play the mission with the mod disabled and it also crashed before .. will try again and we'll see

**Comment by Clibanarius** [comment]
Oh. Then it's probably the same reason for having the crash, but with MissingPackagesFix_ParcelsMaps. That one is one of those known-incompatible mods as well, so any map pack relying on it is out as well. I think the only map packs you should use with LWotC is eclipsezr's for right now.

**Comment by RaynorCZE** [comment]
ok the Doctor's pack is out and it loaded fine .. thanks a lot buddy .. ok so if any further crashes disable map mods and the missing package fix, got it!

**Comment by RaynorCZE** [comment]
any other mods that I should know that are Highly incompatible possible Crashing the game? :D

**Comment by Clibanarius** [comment]
Glad it loaded now! Uh, lemme look real quick. Looking it over, I'd say you're probably fine! Only thing is relatively minor: That EWMECWeapons is KINDA bundled into LWotC already. I dunno if it'll cause any conflicts or anything, though, so I'd say you're safe moving forward!

**Comment by denysbielkin** [comment]
Thank you @Clibanarius !
LWOTC is already released but seems there is still this conflict...
I already was thinking that I would not have a possibility to play in LWOTC - but you saved my day and maybe month :D

**Comment by Grobobobo** [comment]
Issue closed, turned out to be a map mod conflict.
