### ISSUE TITLE
lost disabled

### ISSUE THREAD

**Issue by nytro68** [long-war-2/lwotc#822]
Hello everyone and merry christmas ^^

i have a slight problem, so after downloading beta 2 and installing it , the game works fine, expect some crashes but not that bad, the chosen is enable 
But seeing the troubleshooting guide at the same time, i didnt saw that the lost and abandonned was not active, its weird because the option is grey , i cant click on it and when i put my mouse over, it says that the lost are disabled while running LWOTC ! i saw that the option can be enabled or disabled like the chosen 
So thats bizarre since i saw several streams with the mod and the lost in it so if someone please can tell me if i miss something in the process of installation
Thanks in advance and thank you for doing the mod.

**Comment by Clibanarius** [comment]
The Lost & Abandoned is an introduction mission. Specifically, that storyline mission where Mox is kidnapped and all. It's not meant to be played in LWotC. It WAS enable-able in an earlier version, but it was decided that it screwed up too many things.

**Comment by Clibanarius** [comment]
Oh, forgot about the actual Lost: They're gated behind Force Level 3. So you'll see them pop up in missions starting in... April or so?

**Comment by nytro68** [comment]
ok ok thanks for your response, i didnt know the lost and abandonned was just the name of the mox kidnapping mission, i didnt play vanilla war of the chosen, i was too preoccupied with long war 1 and 2 to play it, but seeing what the series of missions there are, i dont really care if i have it or not
my post was especially for the lost and their mechanics and missions where they pop up
I'm in the end of april as of now so maybe they will pop soon maybe not, thats ok
thanks again

**Comment by Clibanarius** [comment]
Yep! Not a problem! There IS a small bug in Beta 2, though, wherein Lost are supposed to pop up in a lot more places than they do in that version. In the fixed version, they should pop up in any mission in Abandoned City tilesets. In beta 2, they only appear in the Supply Extraction missions set there. IF you want them to properly appear in all Abandoned City missions, I can provide the files that were changed or direct you to where to get them. It's probably easier for me to just do the former, though, just in case anyone else wants the fix before Beta 3's official release! Just unzip the 4 files therein into the LongWarOfTheChosen/Content/Missions folder and overwrite. Probably best to do it when you have a Geoscape save though.

And merry Christmas as well to ya!

[Missions.zip](https://github.com/long-war-2/lwotc/files/3992674/Missions.zip)

**Comment by BlackRose39** [comment]
Merry Christmas to you and everyone as well!
