### ISSUE TITLE
On missions to rescue VIPs and resistance members, reinforcements are on the way from the start

### ISSUE THREAD

**Issue by Meijiro** [long-war-2/lwotc#825]
I thought it may have been mod related but I disabled virtually everything that wasn't cosmetic (voice packs or soldier customizations). Is this intentional?

**Comment by Clibanarius** [comment]
Some Guerrilla Ops missions start with the RNF counter going in squad concealment, yeah. They shouldn't be ACTUALLY DROPPING from the start of turn 2, though. Hopefully you just mean the former's happening, which is intended behavior.

**Comment by Meijiro** [comment]
It wasn't like this in the original LW2.

I tested just hunkering down at the spawn zone and it took about 7 turns for the reinforcements to spawn. Interestingly though when I played the mission normally, the spawn was delayed after breaking concealment compared to the original.

**Comment by jmartinez989** [comment]
@Meijiro are you saying that you see the rnf indicator at the top of the mission? If you do does it start off green then go to yellow then to red? If that is what you are experiencing then that is definitely how it used to be in LW2 as of I believe 1.3 and later or 1.4 or later. Basically the rnfs are a soft timer where they start coming in after a few turns and if you stick around for too long it is just wave after wave.

**Comment by Meijiro** [comment]
Ah you are correct. I had been playing the original LW for a while and double checked my mods -- I was using True Concealment which disables this.
