### ISSUE TITLE
Are Chosen meant to appear on Network Tower missions?

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#827]
If yes, we should reconsider. If no, there's currently a bug going on wherein they can appear there because ExcludeChosenMissionSources="MissionSource_Broadcast" in the base game that's being inherited is only for the Golden Path 4 version of the network tower, NOT the Liberation IV one. To fix this, we gotta use ExcludeChosenMissionSources="AssaultNetworkTower_LW". Just an FYI!

**Comment by Grobobobo** [comment]
Yes, the chosen should not appear in the network tower mission.

**Comment by Clibanarius** [comment]
Then I recommend making those changes! I'm testing them in my current play-through, but I do not know 100% if it's something that will work on my current campaign. I have, however, 100% confirmation that the Chosen do appear in Network Tower missions, as I faced the Hunter the first time there.

**Comment by Grobobobo** [comment]
Already done in dev builds.

**Comment by pledbrook** [comment]
Fixed in [this commit](https://github.com/long-war-2/lwotc/commit/ea2a5c85bea4278ee2b666b295ddc6716f8fcd97)
