### ISSUE TITLE
When starting faction = Skirmisher, all excavation and construction times are halved.

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#828]
Yeah, this one I should've picked up on a long time ago. See, I always use Skirmishers to start out with, and I'd once complained that the time for excavation/facility construction was never high enough. I just realized why: For some reason, when you start at the Skirmisher HQ, its effect of doubling the speed of those things persists forever. WEEEEEEEEIRD. Any ideas as to why? I don't imagine it's the case, but could the other two HQs be doing that as well, in applying their effects permanently no matter where you're scanning?

**Comment by Grobobobo** [comment]
Maybe the trigger that stops the bonus isn't working?

**Comment by wdanny69** [comment]
this is an old issue so it may have been fixed now. tried testing some things and it seems to correctly update the skirmisher hq bonus when entering/leaving

if it still occurs please provide a save if reproducible, a modlist and as much details about the set up leading to the bug
