### ISSUE TITLE
Can't make Medkit

### ISSUE THREAD

**Issue by Usafcurry92** [long-war-2/lwotc#832]
Encountered this problem playing the main story. For some reason, only the shaped charge is available and I'm not sure why it itself cant be made if the resources needed are there as well O.o? Any help woiuld be appreciated!
![Issue](https://user-images.githubusercontent.com/59424434/71648329-e54bef00-2cd0-11ea-966f-576c883c512a.png)

**Comment by DerAva** [comment]
Basic Medkits don't need to be produced. You have an unlimited amount available for free from the start of the game when you equip your soldiers.

**Comment by Usafcurry92** [comment]
I guess I should have added that when I get to this screen theres no way out except force closing the game...

**Comment by Usafcurry92** [comment]
Maybe the game has to be played normally up to this point, then it can be enabled due to lwotc enabling unlimited medkits... I didnt see an option that would allow me to disable that feature.

**Comment by DerAva** [comment]
Oh, did you start with the tutorial enabled and it's telling you to craft a medikit? Yeah, don't enable the tutorial.

**Comment by Usafcurry92** [comment]
Ahh okay got it! I'll give it a go tomorrow, Thanks!

**Comment by Grobobobo** [comment]
Wasn't tutorial meant to not be enabled?
