### ISSUE TITLE
integrate suggest by my tencent group friends

### ISSUE THREAD

**Issue by feihu233** [long-war-2/lwotc#834]
(This article is written in machine translation.The original language is Chinese.)
My friends and I think that some mods can be integrated into LWOTC to make game more differently or more smooth.
I haven't played this mod but my friends in a Tencent group give me a list of mods that want to join.The most of mods in this list are tested in WOTC.But we don't know if some of them can work in a big Integration packages or not.

Overhaul mod list:
    Gene Mods : Make Advanced Warfare Center more useful and can experience the new Gene system.
    Facilities+ : Make some facilities more useful that player can use other space to build other buildings.
    Proving Ground Overhaul : Make Proving Ground more harder in early time.But more playfully.
        [WOTC] PGO: PCS Addon + [WOTC] PGO: Weapon Upgrades Addon
    XCOM Psi Overhaul [NEW UPLOAD]
    Mechatronic Warfare Total SPARK Overhaul
    MEC Troopers + [WotC]Kinetic Strike Module + Psionic MEC Troopers
    Augmentations : 
        I know these Mods may make many crush to other mods.Just a joke.

functional mod list:
    Accurate Covering Fire
    Overwatch All/Others
    Rend The Lost (just joke)
    Turrets Are Cover
    Rapid Fire Reverted
    Original High Hit Dodge Behaviour
    Peek From Concealment
    Scientist Staff Slots
    Evac All
    Alien Rulers Immunities & Ruler Reactions Revised
    Enhanced AoE Preview
    Numeric Health Display
    Color Coded Bonds
    Cost-Based Ability Colors
    Extended Information!
    Cinematic Rapid Fire (and other abilities)
    Less Overwatch Lock Ups!
    Still Stop Wasting My Time
    Instant Avenger Menus
    Better Grappling!
    Gotcha Again
    Quicker Reload
    No Reveal Cinematics
    Force Level Display
    New Target Icons
    Carry Unit Fix
    Blackmarket Usage

**Comment by Anxoczt** [comment]
No, no gameplay twisting mod should be added to LWOTC. You can do that for yourself, it should stay true to its nature. I am ok with divergent balancing because WOTC is simply too different from vanilla to stay unchanged so they can keep changing stats around, buffing and nerfing trashy stuff or stuff that is just too good.

I am fine with QoL mods like evac all being part of the mod as long as they dont damage performance.

**Comment by Grobobobo** [comment]
The only mods that will be integrated/required are the ones nescessary for the game to function on the technical scale.

Content mods are definitely a bad idea, becuase WOTC already added enough bloat for us to worry about.
