### ISSUE TITLE
Gunner Rebalance Discussion 

### ISSUE THREAD

**Issue by eraserman59** [long-war-2/lwotc#837]
There has been quite a bit of discussion about re-balancing the Gunner Class specifically on the Discord. While this effort should be done post 1.0 release, discord discussions get lost over time very easily, and can end up repeating itself. I will summarize the most recent discussion on discord here, to prevent it from being lost to time, and hope that future discussion on gunner re-balance either occur here, or get summarized here, in order to maintain visibility on it. 

Current discussion note:
- Gunners are a bit weak compared to other classes early game.
- This is primarily due to suppression not being a truly effective method of controlling enemies due to the overwatch penalty on shots.
- Mid late game, gunners become useful/strong due to Hail + demo, or Lockdown + CUP, rapid fire, etc. However reaching that point requires the gunner to be semi carried as in the earlier levels they're effectively a rookie with a bigger gun until sgt/ssgt.
- Suppression itself might be underpowered, which is better than the LW 1 state of overpowered but not great for gunners considering how it defines the class early game.

**Comment by Anxoczt** [comment]
Suppression...
While this has saved my ass multiple times, i have a problem of enemies simply walking out of suppression and hitting the gunner with AOE attack. Like Mechs can simply walk through machinegun fire, nuke the gunner (Probably destroying his cover) and now every alien comrade is free from it. Yeah its handy it prevents the targets from using such abilities when under fire but they can simply walk through the zone and here they are...

Even with +25% damage on suppressed targets, its not enough for enemies that really need to die to prevent an ability waste. If like suppression would cause a debuff called "Discalibrated targeting systems" that lasts till the end of the alien turn... that would disable such abilities... now that would be perfect.

**Comment by Grobobobo** [comment]
Discussion has expired.
