### ISSUE TITLE
Allow hunker down to remove the burning effect

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#84]
As the title states, it looks like LWotC is ignoring the fact that hunker down is supposed to remove fire.

This one can be reproduced easily so I did not include a save file.

**Comment by ansabalirai** [comment]
In LW2, hunker down is not supposed to remove burning, which was a design choice to make fire based technicals useful. I assume this is intended behavior here, and if so, should be kept that way

**Comment by jmartinez989** [comment]
Well in the original LW2 hunker down did not remove burning as that was just vanilla behavior they kept. WotC introduced hunker down removing burning. This only worked in XCOM favor as the the aliens could not hunker down.

I mean I am not really sure how I feel about it either way. Not the biggest issue but since this is supposed to be the LWotC adoption of LW2 then figured it should still be there so that is why I consider it a bug. I guess whether or not it should be a thing can be discussed.

**Comment by ansabalirai** [comment]
Hmmm, I am pretty sure aliens hunker down in LW2 if they do not have any other available actions. 

The problem I see with the whole alpha striking nature of XCOM 2 in general and LW2 in particular is that burning was just about the only (somewhat) reliable way to control scary enemies like MK3 trooper variants and blutons in the late game that you could not finish off in one turn (apart from maybe sting (50%), concussion (<50%?) or chain lightning (even more situational)). It is a matter of balance indeed and as much as I hate to cheese it, the burning chance from most sources is not guaranteed anyway and it is very useful to not have to worry about a few enemies for an extra turn.

**Comment by jmartinez989** [comment]
Hmmm I am pretty sure that aliens could not hunker down but I would really not be too upset if hunker does not remove burning, not really a big deal to me. I just thought since it was in WotC that it could be in LWotC but I guess I could see the balance cases for it.

I'll leave it to pledbrook to see if he wants to keep this one open.

**Comment by SirMrMister** [comment]
A compromise could be to only allow fire-disposing hunkering on humanesque enemies - ADVENT, avatars and chosen; and if any of the latter two decide to spend an action hunkering down, that's an action they don't spend on some scarier shit.


Aditionally, you could turn burning into something akin to the complimentary of acid from LW1: Instead of at the beggining of the turn, you take damage for each action not spent moving or hunkering down, but hunkering down still doesn't remove it (ending turn with leftover actions inflicts damage too).

**Comment by pledbrook** [comment]
I've removed the "removes burning" text from the description Hunker Down. We'll leave the behaviour as it is to make burning scarier and to give a buff to SPARKs, Hazmat vests, Fortress and Medikits.
