### ISSUE TITLE
No control over resistance personnel in rescue missions

### ISSUE THREAD

**Issue by RedEyebrow** [long-war-2/lwotc#841]
[save_BUGGED SAVE.zip](https://github.com/long-war-2/lwotc/files/4030937/save_BUGGED.SAVE.zip)

**Comment by RedEyebrow** [comment]
For clarification, everything  was installed correctly on this campaign, however I did start this campaign with  the 'civilians revamped' mod enabled. Initially I assumed this was causing the glitch, however after uninstalling that mod and starting a different campaign (unfortunately I don't have a save file from that one for comparison) the issue persisted the same; upon hacking and opening cell doors I have no control of resistance personnel

**Comment by imn01** [comment]
Do you have "[WotC] Mission: Prison Break" mod installed? I had the same problem when that mod was enabled.

**Comment by RedEyebrow** [comment]
> 
> 
> Do you have "[WotC] Mission: Prison Break" mod installed? I had the same problem when that mod was enabled.

Ah, I do, that's a good point actually. Totally forgot I had that mod installed. Will uninstall it and try a new campaign.

**Comment by RedEyebrow** [comment]
> 
> 
> Do you have "[WotC] Mission: Prison Break" mod installed? I had the same problem when that mod was enabled.

Yup, this was teh conflict, works fine now. Cheers!
