### ISSUE TITLE
psi zombie and lost

### ISSUE THREAD

**Issue by nytro68** [long-war-2/lwotc#843]
Hello everyone,i have 3 questions or issues or whatever , i prefer to post something and get answer and help others and the modders

so basically i'm doing a troop column in the metro map , i clear the first pod , the dark event with the lost is active so after a couple of turn ( headshot desactivated since i'm in legendary difficulty ) , a swarm of lost comes to me, at that moment a sectoid commander (NOT ACTIVE for me ,out of line of sight ) does a psi zombie revive thingy so some psi zombies are there too, with where i'm in the map , i'm stuck in a corner not the problem here, but some problems comes up

Question/issue 1 = the psi zombie thingy , the number of psi zombies that are revived depends on what basis ? 
if there are like 10 corpses of aliens , does 10 psi zombies appear ? does the lost count in that ? because every 3-4 turns after every psi zombies are killed, the sectoid commander just revived them infinitely so like 10-13 zombies pop up again
i played long war 2 a lot , i finished it even in legendary, i never had such a thing in all of my runs

Question/issue 2 = its my second run on that beta , in the first one i enable headshot mechanics but it seems to me that was too easy in some way so i disabled it for my second run
however in the main page here , i saw that the lost does a 50/50 when they're going to attack alien or xcom, i can clearly see thats more a 80/20 xcom and in some cases the lost know where i'm even though i broke line of sight and hide when they cant see me because of double high cover or higher ground 

Question/issue 3=
is that normal that even a smoke grenade triggers lost ? a flashbang ? toxic grenade ? it doesnt seem logic to me since its not a explosion like a frag grenade or a rocket 

anyway thanks for the mod, even though i'm nearly raging against some BS mechanics or nearly 100% hits chance misses, i'm enjoying it and thanks for upcoming answers and keep up the good work on the mod :)

**Comment by Anxoczt** [comment]
I think there is no limit on how much psi-zombies can be raised. Simply kill the sectoid commander or throw a flashbang at him to kill all the zombies.

Also if you have the Reapers order that any attacks against Lost is instant death, A skirmisher with retribution can delete losts by hundreds on his own because any hit means instant death.

Flashbang is **_loud_**
But what shouldnt be as loud should be smoke grenades and gas grenades so these two items should be added to some sort of exception list. 

Lost do seem to still prefer my troops over Advent even with the 50/50 targetting, but i might have been just unlucky in general with positioning.

**Comment by nytro68** [comment]
thanks first of all,

no limit? thats odd, i mean chrysallid can do a cocoon from a victim , even though its a psi zombie it should need a corpse to be able to control it, that seems logic to me 

i dont have the order you're referring to, i had it in the first run , not yet in the actual one or i forgot it i dont know ^^ my skirmisher was injured i couldnt have him for that mission but his retribution is useful against lost as well as bladestorm and ccs 

yeah thinking about it the flashbang is loud, i concur that but as you're saying, there should be a exception list or maybe its not possible since its in the base game ( in the dlc i mean )

as for the lost, positionning makes the problem harder , in the mission i was referring to in my first post, in one swarm i got like 6 dashers and 6 slow so maybe since they cant reach me with slower ones , all the dashers are focusing on me, i dont know for sure, anyway

thanks again
