### ISSUE TITLE
Killing Lost in certain missions doesn't refund turn.

### ISSUE THREAD

**Issue by spankahontis** [long-war-2/lwotc#844]
In certain missions killing the Lost doesn't refund your turn.
Savefile example below.

Current Mods.
- Zhang Voicepack
- Japanese Voicepack
- More Nations and Names WOTC
- Xcom International Voicepack
- Evac All WOTC
- Capnbubs Accessories WOTC
- Extract Corpses WOTC (FEEDBACK: You don't get enough missions that drop corpses)

[Lost dont refund headshot kill.zip](https://github.com/long-war-2/lwotc/files/4051456/Lost.dont.refund.headshot.kill.zip)

**Comment by spankahontis** [comment]
UPDATE: This Mission was even more cnfusing, Certain Lost gave you the "Headshot" turn refund where others didn`t.
I believe it was the Lost Dashers that you didn`t get a refund, regular ones did?
But I'm not even sure about that. I think the Sharpshooter killed regular Lost and didn't get the turn refund either?

[save_Dashers dont refund regulars do.zip](https://github.com/long-war-2/lwotc/files/4054972/save_Dashers.dont.refund.regulars.do.zip)

**Comment by ShinyRobotGod** [comment]
I had a similar issue, but in my case none of the lost provided the "headshot" refund.  I am playing on veteran difficulty since this is my first time trying long war.

**Comment by spankahontis** [comment]
> I had a similar issue, but in my case none of the lost provided the "headshot" refund. I am playing on veteran difficulty since this is my first time trying long war.

Hey, ShinyRobotGod

I was Searching if others were having the same problem? 
I came across this issue and how to manually fix the files. I tried it out and have not had an issue with the Lost not refunding turns since.

[https://github.com/long-war-2/lwotc/issues/781]Solution here(url)

**Comment by ShinyRobotGod** [comment]
Thanks for this!  I edited the ini.  I didn't think to keep my game save at the time, so I will see if I did it correctly when I next face the lost. I appreciate your help!

**Comment by ShinyRobotGod** [comment]
I confirm adding a semicolon in front of this line in the XComGameData_SoldierSkills.ini fixed the headshot problem.

; !ValidHeadshotAbilities=()

**Comment by Grobobobo** [comment]
Intentional behaviour.
