### ISSUE TITLE
VIP placed in wrong place at start of Mission.

### ISSUE THREAD

**Issue by spankahontis** [long-war-2/lwotc#845]
This has happened a few times, instead of the VIP being placed in a Cell or Van at the start of the mission, they appear standing on top of a holo-sign on the pavement.

Once you see them, they can teleport off the object, so they are not trapped. But it's not supposed to happen either.

Current Mods.
- Zhang Voicepack
- Japanese Voicepack
- More Nations and Names WOTC
- Xcom International Voicepack
- Evac All WOTC
- Capnbubs Accessories WOTC
- Extract Corpses WOTC (FEEDBACK: You don't get enough missions that drop corpses)
[VIP trapped in Object.zip](https://github.com/long-war-2/lwotc/files/4051483/VIP.trapped.in.Object.zip)

**Comment by Anthogator** [comment]
This has been fixed. Please see #784 for reference. It has not yet been integrated into the release package yet.

**Comment by spankahontis** [comment]
Great Work, Clibanarius!

**Comment by copyrite** [comment]
Appears to be fixed.
