### ISSUE TITLE
Crash on a mission start

### ISSUE THREAD

**Issue by Voker57** [long-war-2/lwotc#847]
Save: [save.zip](https://github.com/long-war-2/lwotc/files/4065746/save.zip)
wait until mission infiltrates to 100%, then start it
Mods: required, recommended, CapNBubs accessories pack for WoTC https://steamcommunity.com/sharedfiles/filedetails/?id=1123427895
OS: Linux

**Comment by zygny** [comment]
Possibly a duplicate of: #829 ?

**Comment by Grobobobo** [comment]
Duplicate of  #829. Nothing we can do about linux either way.
