### ISSUE TITLE
Reaper losing stealth on second conceal automatically upon shooting

### ISSUE THREAD

**Issue by MagSigeasol** [long-war-2/lwotc#85]
Had a jailbreak with a reaper. Lost conceal taking a shot on a sectoid as normal (rolled on the meter). Used shadow to enter concealment, took a shot on a troop which automatically revealed the reaper. Afterwards, the animation for shadow played but half of the animation was not visible. 

Ill try to get a save just prior.

**Comment by ansabalirai** [comment]
I suspect if this is related to the issue I experienced earlier on the NW tower with enemy detection radius being set to normal xcom soliders for the reaper (who normally has a 1 tile detection radius) after the button is pushed

**Comment by pledbrook** [comment]
Probably not relevant any more and haven't heard similar reports since this.
