### ISSUE TITLE
Visual Glitch Keeps Occuring

### ISSUE THREAD

**Issue by Classick2002** [long-war-2/lwotc#851]
I keep getting this glitch. I can cycle through soldiers and hear the sound, but I need to reload to get this to go away.

![20200122154355_1](https://user-images.githubusercontent.com/60203634/72945812-d84f7800-3d31-11ea-9be8-bcf610f7d055.jpg)

**Comment by Grobobobo** [comment]
I think this is an issue with one of the camera mods

**Comment by Classick2002** [comment]
Thank you! I’m running the one that was recommended w/ LWOTC; I’ll try
disabling it. I can live w/o it if it fixes the issue.

Cheers!

**Comment by Grobobobo** [comment]
Resolved.
