### ISSUE TITLE
Label all permanent dark events with "Tactical Upgrades:"

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#854]
Almost all the permanent dark events in LW2/LWOTC are labelled with "Tactical Upgrades:", but there are a few that aren't, such as Alien Conditioning and Veteran Units. We should make all of them include the "Tactical" label so that it's easier for players to identify the permanent ones.

In addition "Tactical Upgrades" is long-winded and forces many of the dark event names to scroll in the UI. We should probably just shorten it to "Tactical:".

**Comment by Grobobobo** [comment]
Perhaps for even more clarity other dark events should have a "Strategic:" prefix

**Comment by pledbrook** [comment]
Not sure about that. Some of them still apply to the tactical layer. In fact, we should probably just label the permanent ones as "Permanent:" to make it absolutely clear what is meant.

**Comment by Grobobobo** [comment]
Sounds good

**Comment by MiserablePileOfBugs** [comment]
That would be a significant enhancement. I'm always confused about which events are permanent/not permanent.
