### ISSUE TITLE
Rebalance HP granted by vests

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#860]
Due to purifier autopsy granting +1 HP on all vest items, nanoscale ends up granting +3 HP which is the same as predator armor. I believe it might be worth considering reducing +1 HP gains from all vests to compensate.

**Comment by pledbrook** [comment]
I don't really want to do this, because I think Purifier autopsy should give you incendiary grenades (rather than Officer autopsy).

**Comment by ansabalirai** [comment]
Well I am in favor of that change. Makes them more useful in general. Although I guess you mean purifier corpse for building incendiary grenades, not (just) unlocking them?
I would be ok with both

**Comment by pledbrook** [comment]
Yes, for research and to build. Not sure whether to do something else for Officer autopsy, but that's required anyway to progress the story, so it's not critical that it's used for an item or anything.

**Comment by allenhu0912** [comment]
Officer autopsy already leads to mag tier weapons, which is more than enough by itself
