### ISSUE TITLE
Use Purifier corpses/autopsy for incendiary grenade research

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#861]
Building incendiary grenades and bombs should also require Purifier corpses. Note that this means officer corpses will no longer be needed for these grenades.

**Comment by Grobobobo** [comment]
I was actually thinking about them being requiriments for frost bombs if we were to integrate dlc slightly better, but that's good too.

**Comment by pledbrook** [comment]
There are other corpses available for those, such as Officer, Priest, or Spectre.
