### ISSUE TITLE
"Meele Resistance" Chosen Trait

### ISSUE THREAD

**Issue by tmorse425** [long-war-2/lwotc#862]
During my fight with the chosen hunter, I noticed he had a trait called "Meele Resistance." I assumed it was a resilience perk that makes melee attacks do 50% less damage against him since thats what the title says, but in actuality, it makes the hunter take 50% less damage from everything I throw at it. Guns, Bombs, Fire, Acid grenades, Fall Damage, The Lost, You name it. The only thing it won't take reduced damage from is Psionic attacks like Soul fire. I looked at my mod cache to see if I had a mod that was causing this, but I have no mods that give the chosen any traits. How do I go about fixing this?
![Sound effects 00_08_32_22 Still001](https://user-images.githubusercontent.com/60725750/73906824-42a80280-4872-11ea-9d7a-afc2e546acab.jpg)

**Comment by Grobobobo** [comment]
That has been fixed in the dev build 8.

**Comment by tmorse425** [comment]
is there a way that I can update my current build with the dev build?

**Comment by Grobobobo** [comment]
https://www.reddit.com/r/LWotC/comments/exbebv/lwotc_dev_build_8_available/
