### ISSUE TITLE
Reinforcements starting in concealment

### ISSUE THREAD

**Issue by ThinkerOf3000** [long-war-2/lwotc#863]
Not sure if this is a bug or a feature, but it seems really weird that on stealth missions, reinforcements are called right from the start and begin dropping in before concealment has been broken.

**Comment by Grobobobo** [comment]
It's a feature. Whether that feature should be change is up to discussion.

**Comment by ThinkerOf3000** [comment]
Well, I guess I would argue that it should be changed.

While it does certainly make things more difficult, it makes very little sense as to why they are rapidly air-dropping in mechs and mutons, heavy front-line fighters, to a scene that (as far as they know) is just an everyday security detail.
Especially when you get to the point where they air-drop people every single turn. Until you have an army guarding a completely routine data transfer.

**Comment by Grobobobo** [comment]
No plans to change it, since it's an anti-stealth mechanic, and removing that would warrant nerfing stealth in some other way.
