### ISSUE TITLE
[balance/ enhancement] Lost missions "overwatch advent"

### ISSUE THREAD

**Issue by Crolock** [long-war-2/lwotc#865]
So I just felt like doing another quick post on my take about the no-headshot lost.

Pros 
- 3 party mixes up tactical combat
- lost my serve as meatshield to buffer advent
- different tactical approach is required do to liability of explosives to draw in more lost
- lost prioritize advent and x com equally
- no headshot on x com levels the playing field as advent doesn't headshot lost either

Cons
- the lost spwan can be very random (had a javelin rocket on max range spwan 5 lost ontop of the soldier who launched it)
- the lost and advent ai seem to act in a strange way (had a trooper who was surrunded by 3 lost shoot one of my soldiers in high cover, then a stunlancer within 7 tiles to an injured soldier of mine decided to run all the way back to the trooper and attack one of the lost... ?!?)
- the logical turn order of lost- advent- x com severely limits x com overwatch option 
(don't get me wrong the order has to be this way, otherwise these missions would probably be a cakewalk. However taking into account that explosions are already not viable, it feels bad to have overwatch be so clunky to use as well) -> this promotes the single effective playstyle of all out offense take away a lot of the tactical decision making

Suggestions:
- no headshot can be kept
- a**dd an "overwatch advent only" option on lost missions** which can be activated as alternative,
ever vigilant overwatrch etc. should still grant regular overwatch and effect every hostile 
- spawning location of the lost should be somewhere near the explosion that triggered the spawn and have the lost run toward that location (I think this is already the case to some extend but the lost priorities and spawn mechanics are hard to comprehend as a player. The game should communicate how this works)

All things considered though I feel like the lost missions are in a pretty descent spot right now.

**Comment by Grobobobo** [comment]
Lost eating up xcom overwatch is intentional.
