### ISSUE TITLE
Assassin's katana should be able to miss

### ISSUE THREAD

**Issue by Anxoczt** [long-war-2/lwotc#866]
After reading the nightmarish buffs Chosen will get, since Templars got their psionic blades nerfed so they can graze or miss entirely. The Chosen Asssassin should get the same treatment, because an undodgeable, high damaging melee attack with the buffs Chosen get is really, _really cheap._ 

This would also make it possible for shinobies and gunners to parry such attack once a turn so you can try to mitigate damage with well placed soldier.

**Comment by Grobobobo** [comment]
>because an undodgeable, **high damaging** melee attack
I don't think you actually read those changes

**Comment by Anxoczt** [comment]
> > because an undodgeable, **high damaging** melee attack
> 
> I don't think you actually read those changes

66% is still enough for katana to either go through all of your plating or send your soldier to hospital for few days in the worse case alongside the daze effect.

**Comment by Grobobobo** [comment]
Most chosen changes will be reverted in beta 3.
