### ISSUE TITLE
Suggestion: Randomized Pistol Perks

### ISSUE THREAD

**Issue by Thrawn007** [long-war-2/lwotc#867]
With pistols back working again, there are a number of different ways they can be handled.  One is to handle Pistol Perks like XCOM perks (but a cheaper alternative) with their own randomized tree.  Ideally there should be between 6 and 10 perks per level just to give some randomness to it, but here is a starter suggestion of how to divide up perk pools and add a first few perks.

Common/Uncommon/Rare would have same distribution as XCOM perks.  So you'd get more common perks, and get common perks early.

--------------
COMMON POOL
--------------
Packing Light
Your pistol does not have a move penalty.

Quickdraw
Firing your pistol with your first action no longer ends your turn.

Pistol Expert
Pistol perks can be purchased at a discount (discount TBD)

Pistol Whip (Animation exist?)
Make a melee attack with your pistol.

Return Fire
When targeted by enemy fire, automatically fire back with your pistol once per turn.

---------------
UNCOMMON POOL
---------------
Bloodlet
Standard pistol shots cause bleed damage

Clutch Shot
Once per mission, fire a pistol shot that cannot miss.

Doubletap <NEW>
Fire the pistol two times at the same target.

Lightning Hands
Fire your pistol at a target. This attack does not cost an action.

Pistolero
All your pistol attacks do +1 damage

--------------
RARE POOL
--------------
Faceoff
Fire once at every visible enemy with your pistol.

Fan Fire
Fire the pistol three times at the same target.

Gunslinger
Take a reaction shot with your pistol against any enemy that moves or attacks within 8 tiles and a wide cone of fire.

Uload Clip
Fire 1 to 6 shots at a target.  Your pistol is disabled until the next time you reload.

**Comment by Grobobobo** [comment]
The current system is more than fine.
