### ISSUE TITLE
Mission site icons at the bottom of Geoscape all the same

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#87]
The same icon is used for all mission sites (or at least most of them). Those icons are supposed to be overridden via a highlander hook so that they look like the icons on the Geoscape itself.

**Comment by ansabalirai** [comment]
While these should be fixed as a priority, having played many hours of late game LW2, one enhancements I would suggest is to at least be able to differentiate between missions that are currently being infiltrated and ones that aren't. I know that hovering over them shows a squad name for the ones which are being infiltrated, but I wonder if a better way could be maybe add a glow around those or at least change their color from green (to yellow or something) to be able to tell them apart quickly.

**Comment by pledbrook** [comment]
I have to work out why the proper icons aren't being displayed first, but I do like the idea. I don't understand why the icons aren't displaying. The appropriate event is in the highlander and the LW2 code is active. It just doesn't work.

**Comment by pledbrook** [comment]
This was fixed in Alpha 4 with [this commit](https://github.com/long-war-2/lwotc/commit/0bc178068072405ba169374a7ef0eebed2efbec8).
