### ISSUE TITLE
Bladestorm cancels Combatives

### ISSUE THREAD

**Issue by McTrevor79** [long-war-2/lwotc#871]
Most notably when when cryssalids attack a shinobi with both skills. Bladestorm triggers but combatives not. Also experienced it when a berserker hit my shinobi. Is this intended behaviour?

**Comment by allenhu0912** [comment]
Bladestorm procs first, then Combatives, so if they die you won't see combatives proc. It's a good thing because you might be facing multiple melee enemies and this conserves the combatives proc

**Comment by McTrevor79** [comment]
In all those cases the enemies survived bladestorm and then punished my shinobi. I have seen only once, that bladestorm and combatives triggered. It was against a Lost and the bladestorm missed. When bladestorm did hit, I didn´t get combatives counter yet.

**Comment by ansabalirai** [comment]
Was it just that one lost that meleed the shinobi that turn? Could it be another lost already attacked and proc-ed combatives, since it only procs on the first melee attack.
I ask since visualizations in WOTC in general and with lost in particular are wonky and you may not be able to see everything in order all the time.

**Comment by McTrevor79** [comment]
The incident with the lost was the only time for me when combatives worked after Bladestorm triggered. Combatives worked fine before my shinobis got Bladestorm. Once they got both and an enemy procs bladestorm, combatives won't trigger in most cases. On three different occasions  a cryssalid survived the blade storm and successfully attacked my shinobi afterwards.  One time a beserker did the same.

**Comment by allenhu0912** [comment]
Combatives will fail to activate if they roll a crit and you are unable to downgrade it to a graze

**Comment by McTrevor79** [comment]
Ok, so I can consider myself just unlucky so far in this camaign since 4 out of 5 times when bladestorm triggered, combatives failed. On at least one of those occasions my shinobi was wearing a nanoscale vest which reduces crit-chance by 25%. I will keep an eye on that matter.

**Comment by DerAva** [comment]
You mentioned Cryssalids mostly being responsible for this. Is this related to burrow charge? Combatives only works on the alien turn, not on XCOM's turn, so if a Shinobi triggers a burrowed lid then Combatives will not protect from the charge attack.

**Comment by McTrevor79** [comment]
> You mentioned Cryssalids mostly being responsible for this. Is this related to burrow charge? Combatives only works on the alien turn, not on XCOM's turn, so if a Shinobi triggers a burrowed lid then Combatives will not protect from the charge attack.

Ok, that is the perfect explanation. But how the heck is one supposed to know, that combatives only works on the alien turn??

**Comment by MrNiceUK** [comment]
Guess the localision text could be tweaked of it's not clear enough.
