### ISSUE TITLE
Vanguards will use CCS if panicked.

### ISSUE THREAD

**Issue by Anxoczt** [long-war-2/lwotc#872]
During one of my missions, Advent Vanguard got panicked, but when i send my Spark to flank him, he fired at him, i am pretty sure all reaction abilities should be disabled if the unit is panicking but this isnt the case.
I lost the save of that moment but if i'll manage to get these circumstances together again i will update this report with gif of it in action but i'll rather report this now just in case you will find it from your side more quickly.

**Comment by allenhu0912** [comment]
CCS, Bladestorm and Overwatch continue to function for panicked units. Whether or not this is intentional, I don't know.

**Comment by Anxoczt** [comment]
> CCS, Bladestorm and Overwatch continue to function for panicked units. Whether or not this is intentional, I don't know.

I am pretty sure this is unintended behaviour, if someone is shaking like they are going through drug withdrawal then facing and shooting at someone who tries to pass by seems shaky to me.

**Comment by InterventoR** [comment]
A conversation about it has passed in Discord recently. Panicked state wouldn't equal to Stunned. In order to mark this difference, panicked unit should still be allowed some restricted "instinctual" actions but with an extra aim penalty of course. (Shaky individual is still "shaky" after all)

**Comment by McTrevor79** [comment]
If the panicked unit hunkers down, overwatch and similar abilities should be cancelled.

On a different note: Vanguards have CCS, so should have reaction fire within 4 tiles? Didn´t trigger even once yet. Quite sure it is not working in my campaign (still beta 2).

**Comment by Grobobobo** [comment]
Intended.
