### ISSUE TITLE
Codex split on damage triggers Bladestorm

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#873]
Triggered it with this save

[save_AUTOSAVE- Campaign 76, Mission 83, Turn 7.zip](https://github.com/long-war-2/lwotc/files/4198996/save_AUTOSAVE-.Campaign.76.Mission.83.Turn.7.zip)

**Comment by Grobobobo** [comment]
That's technically not a bug, but weird behaviour nonetheless.

**Comment by copyrite** [comment]
Since Bladestorm no longer triggers on the unit's turn, this should occur significantly less often. I also agree with Grobo that it's not necessarily a bug, but now there's even less reason to spend dev time on it.
