### ISSUE TITLE
Reaper gives you an extra action if you kill with Bladestorm during your turn

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#875]
1. Activate Reaper
2. Attack unactivated enemy pod, but fail to kill
3. Enemy pod scampers on activation, triggering Bladestorm which kills an enemy
4. Get an extra action from Reaper

Not sure whether or not this interaction existed in LW2, but I don't remember seeing it

**Comment by McTrevor79** [comment]
Reading the description of Reaper I would assume it to work exactly like that. Reaper is already bad enough for negating whirlwind.

**Comment by Grobobobo** [comment]
Working as intended.
