### ISSUE TITLE
Yellow alert naja squadsight snipe without activating

### ISSUE THREAD

**Issue by McTrevor79** [long-war-2/lwotc#879]
Don't know if this is supposed to be, but I had a naja squadsight sniping my soldier out in the open without the pod being active or activating. Just like sectoids raise psi zombies from out of sight.

**Comment by allenhu0912** [comment]
[SaveData.zip](https://github.com/long-war-2/lwotc/files/6645252/SaveData.zip)

Before and after saves of a naja taking a yellow alert shot with Hunter active
