### ISSUE TITLE
Two possibly unintended Battlelord interactions with balance implications

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#882]
1. For every proc of Battlelord, you can activate Hit and Run again
2. Battlelord will activate on enemy yellow alert reactions. Not sure about green alert reactions

**Comment by Grobobobo** [comment]
Battle lord should only allow hit and run to trigger once per turn. It activating on YA actions is fine though.

**Comment by DerAva** [comment]
"Should" being the important word here. At the moment it seems that Hit&Run can trigger on each action you take during Battlelord activations. It also triggers Implacable multiple times. Here is an example from Ronar's stream from last night: https://www.twitch.tv/videos/586582322?t=03h10m16s

**Comment by allenhu0912** [comment]
Yes, it seems that each Battlelord proc is an individual turn

**Comment by Grobobobo** [comment]
Weirdly enough, from what I've tested it doesn't work with interrupt. Will have to check why it does with battlelord.

**Comment by Grobobobo** [comment]
Nerfed in latest verions.
