### ISSUE TITLE
LWOTC: Game not starting up

### ISSUE THREAD

**Issue by Hunter11199** [long-war-2/lwotc#884]
I have went through all the troubleshooting steps given on the website and everytime i try to boot up the game crashes.

**Comment by Hunter11199** [comment]
C:\Users\Hunter\Documents\My Games\XCOM2 War of the Chosen\XComGame\Logs\XCom-HUNTER-CL374751-2020.02.18-23.32.02-Crash
to complete saving

zipping and sending
	 C:\Users\Hunter\Documents\My Games\XCOM2 War of the Chosen\XComGame\Logs\XCom-HUNTER-CL374751-2020.02.18-23.32.02-Crash
 
This is my error code

**Comment by pledbrook** [comment]
Please attach a log file from when the crash happens. Should be *C:\Users\Hunter\Documents\My Games\XCOM2 War of the Chosen\XComGame\Logs\Launch.log* right after the crash happens and the game exits.

**Comment by Grobobobo** [comment]
It's been over a month and the log file has not been provided.
