### ISSUE TITLE
CCS on Vanguard not working

### ISSUE THREAD

**Issue by McTrevor79** [long-war-2/lwotc#885]
Playing beta 2. Had vanguard on several occasions now as enemy and went into close range  at least 3 or 4 four times. CCS never triggered.

**Comment by pledbrook** [comment]
Duplicate of #699

**Comment by McTrevor79** [comment]
Sorry. I am on mobile. Didn't show me related issues.

**Comment by pledbrook** [comment]
No worries. Also, GitHub no longer pops the suggestions up as you type as far as I can tell. They show a little link with, for example, "4 similar issues found" as its text.
