### ISSUE TITLE
How to make free plasma grenades

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#887]
1. Research plasma grenades in proving grounds
2. Unequip grenade slot on skirmisher
3. Send on covert action
4. Skirmisher returns home with free plasma grenade in grenade slot

**Comment by InterventoR** [comment]
After Proving Ground research, all conventional grenades should turn into plasma grenades, shouldn't they? So this situation seems a minor glitch at best.

**Comment by allenhu0912** [comment]
No, you build plasma grenades one by one. They're not supposed to be free.

**Comment by InterventoR** [comment]
You're right. Why am i remembering on contrary for my LW2 days? Then Skirmisher have proved himself very "crafty" :P

**Comment by Grobobobo** [comment]
Does that work with a grenadier's slot too?

**Comment by Anthogator** [comment]
You don't even need to send the soldier with the equipped plasma grenade on the covert action. You can slot the soldier into the CA and then cancel gearing up the mission and the items will be converted. This also applies to medkits.
