### ISSUE TITLE
Resistance Warrior Kevlar Armor has 2 utility slots rather than 3

### ISSUE THREAD

**Issue by cicero225** [long-war-2/lwotc#89]
Something I noticed in my playthrough. Seems like a minor inconsistency that could be fixed - it should match the baseline Kevlar armor.

I have no other mods active except this and highlander. I noticed this issue just scrolling through my soldiers on the mission select screen.

**Comment by pledbrook** [comment]
I'm assuming it uses a different template from the normal one. I don't suppose you know what the template name is, do you? Although it probably makes sense to support arbitrary armours that might be added by mods. Not sure how to do that.

**Comment by pledbrook** [comment]
Actually, don't worry. I think I'll assume that all armours except a select few, known ones, will get the extra slot.

**Comment by cicero225** [comment]
I was going to say I'm not sure, but the armor is called KevlarArmor_DLC_Day0. Sounds like you know what you need to know though!
