### ISSUE TITLE
Where is the chosen?

### ISSUE THREAD

**Issue by exilitywork** [long-war-2/lwotc#892]
I started new game with lwotc, played ten or more missions, but dont met chosen. Is it normal? Is original story work?

**Comment by Swarbs1982** [comment]
In the current version, I believe Chosen don't appear until your reach Force Level 4 (FL4 under the region name). Also you need to have enabled them under Advanced Options before starting the campaign

**Comment by Grobobobo** [comment]
Beta 2 - after the network tower mission, dev builds - at FL5
