### ISSUE TITLE
Chosen can spawn in unescapable region 

### ISSUE THREAD

**Issue by eraserman59** [long-war-2/lwotc#896]
[save_Trapped assasain.zip](https://github.com/long-war-2/lwotc/files/4303582/save_Trapped.assasain.zip)
In this subway map the assassin spawned in a region of the map she cannot escape from. This made for an interesting shootout, but I don't think this is intended.

**Comment by copyrite** [comment]
Chosen no longer spawn in missions that occur in subway maps, closing.
