### ISSUE TITLE
Mac: Help with Installing LWotC

### ISSUE THREAD

**Issue by RomanTriumph** [long-war-2/lwotc#897]
I tried following the directions located in the mod installation page for LWotC. However, I cannot determine where I must extract the .zip file on this Mac OSX?

Any further help with this would be greatly appreciated!

**Comment by pledbrook** [comment]
See [Feral Interactive's web site](https://support.feralinteractive.com/en/mac-linux-games/xcom2/faqs/modding_steam_full/), specifically the section titled "Installing mods that you have downloaded".
