### ISSUE TITLE
Squad Select screen doesn't show Combat Intelligence

### ISSUE THREAD

**Issue by cicero225** [long-war-2/lwotc#90]
Combat Intelligence _does_ show up when looking through the soldiers any other way, but not while choosing soldiers for missions. This is minorly impacting, since a commander might choose soldiers to use based on who has the higher intelligence.

**Comment by pledbrook** [comment]
Where exactly are you expecting to see the combat intelligence?

**Comment by cicero225** [comment]
Good question. I went and took a more specific look and I'm basically hoping to see it along with everything else when selecting weapons or armor or attachments. As it is, it's only visible if you specifically click the soldier name at the very bottom. 

e.g. (which also shows the resistance kevlar armor thing I mentioned in the other issue)
[https://i.imgur.com/ZqTksRB.jpg](url)

Come to think of it, I'm not sure if this is normaly wotc behavior, but I never noticed this using the same robojumper squad select screen in my normal campaigns.

**Comment by pledbrook** [comment]
I don't think this has anything to do with squad select. You should notice the same thing if you go to the loadout of a soldier from the normal Armory menu. I'll double check that.

**Comment by pledbrook** [comment]
I've changed the title of the issue to reflect that I think it's just the loadout screen that's missing the bond status and ability points. You can always go back one from Loadout to get to the main armory menu and that shows both.

**Comment by pledbrook** [comment]
Not sure this is worth the effort, especially at the potential cost of MCOing the relevant bit of UI.
