### ISSUE TITLE
Ruler action for chosen at Starting season is OP

### ISSUE THREAD

**Issue by abcd7655** [long-war-2/lwotc#907]
Last in the game, the chosens' difficulty is low but early's that is hard.

Ruler reaction is strongly harder that issue.

I suggest the chosen's Ruler reaction is revised to chosen's 3rd or 4th strength for chosens they get definitely. Also we make chosen's ruler reaction activating option.

thanks for reading this short writing.

**Comment by Anxoczt** [comment]
It requiring higher force level could be reasonable. So you have more time to prepare.

**Comment by abcd7655** [comment]
> It requiring higher force level could be reasonable. So you have more time to prepare.

If they have not ruler reaction, I agree. Against chosen with ruler reaction for convention weapon is so hard.

**Comment by Grobobobo** [comment]
A different direction has been picked for the chosen, and prime reactions will be likely reverted for beta 3.
