### ISSUE TITLE
Chosen do not activate after network tower

### ISSUE THREAD

**Issue by xauier** [long-war-2/lwotc#909]
Hello there,

when starting the campaign, i did not activate the chosen in difficulty settings. I changed the difficulty afterwards to activate the chosen.
But as far I can tell, it did not work. I also finished a network tower, after I changed the difficullty.

Is changing the chosen setting supposed to work? 
Or maybe there is another way to activate the chosen for my campaign?

Thx for your help

**Comment by Grobobobo** [comment]
use the ActivateChosen console command.
