### ISSUE TITLE
Some research should not be inspired

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#91]
Basic Research, Engineering Research and the Render corpse technologies should not qualify for inspired research.

**Comment by MiserablePileOfBugs** [comment]
I agree. I got the render sectoid inspiration the other day and it felt out of place.

**Comment by pledbrook** [comment]
This can either be done by a highlander change that allows you to specify excluded techs or by setting the `bCheckForceInstant` flag on the tech's template and ensuring its `InstantRequirements` can't be met. The latter is hacky, but we're not expecting any more changes to XCOM 2, so it should be safe.

**Comment by pledbrook** [comment]
The hacky fix made Gatekeeper Shell a requirement for all those techs, so people couldn't research them until the late game. It looks like this needs a highlander fix.

**Comment by TheReigningKing** [comment]
Remember to include Advent/Alien Datapad Research into this list as those are repeatable as well.

**Comment by pledbrook** [comment]
Depends on [X2WOTCCommunityHighlander#633](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/633)
