### ISSUE TITLE
Mejorar cirugía de campo del especialista

### ISSUE THREAD

**Issue by daruperez** [long-war-2/lwotc#911]
Hola, 
Posible mejora: mejorar la cirugía de campo del especialista.
Actualmente solo es uno..., muy poco atractivo a medio y largo plazo, ya que las heridas son mayores.
Mejora: aumente según rango y/o robot a 2,  4, 6 y 8; o degradar el daño de herida leve a nada, herida moderada a leve y herida grave a moderada

Gracias

**Comment by Grobobobo** [comment]
I'm assuming this is about combat protocol scaling, which is actually worth discussing. I'd prefer to not have to assume what you're talking about though.
