### ISSUE TITLE
suggestion give mobility back

### ISSUE THREAD

**Issue by RambelZambel** [long-war-2/lwotc#915]
If u use a rocket with the rocket launcher mod from Iridar, u get 1 mobility back. Maybe u can do this with grenades and anything else too?

**Comment by KaesoVenator** [comment]
This is how LW1 works, if I remember correctly. It would make sense, if it can be balanced properly.

**Comment by Grobobobo** [comment]
Current lw2 has the dynamic of choosing between utility and mobility, this would destroy that dynamic.
