### ISSUE TITLE
Hit & Run not working for not cover taking enemies

### ISSUE THREAD

**Issue by xauier** [long-war-2/lwotc#920]
Shooting at MECs or any other thing which do not take cover, does not count for Hit&Run. From my point of view, the description (exposed targets) would include those enemies.

**Comment by allenhu0912** [comment]
This is an intentional nerf because HnR was absurdly strong in LW1. It's not a bug.

**Comment by ChrisTheThinMint** [comment]
Its also related to how the definition of 'exposed' changed from XCOM 1 to XCOM 2. 

In XCOM 1 all units could be exposed when not in cover, but certain units recieved a hardened bonus that negated the critical hit chance from being exposed.
In XCOM 2 these kinds of units don't count as exposed in the first place, they are excluded from all cover and flanking crit chance checks. 

As Pavonis ported Hit and Run from LW1 along with other perks, they made it consider the same rule. Apart from the technical side of things, I agree that Hit and Run would be too strong against units that dont take cover. MECs, Chryssalids, Berserkers and other similar units are already bullet sponges that easily die to concentrated fire. 
And I don't think the description needs changing, as the new exposed/flanked terms are already universal across all abilities that work in the same fashion (for example Hunter's Instinct).

**Comment by xauier** [comment]
Thanks for the quick response.
I guess you're right with your explanation. But for someone without such an extensive history of XCOM, it is just not working according to the description of HnR. From my point of view, a MEC, drone or zombie are all "exposed" .. just because they are not taking cover...

It's a kind of weird discussion about the term definitions :)
But anyway - a small hint within the skill description would be nice 

Thx!

**Comment by ChrisTheThinMint** [comment]
I agree that it's a weird discussion. In my view a unit can't be "exposed" if it doesn't try to cover itself in the first place. But we can certainly clarify it a bit. I'll take a look at it in the next localization pass.

**Comment by MiserablePileOfBugs** [comment]
I have also been confused by this before I figured it out. On the UI, units that are considered exposed always have a yellow icon. So would it help if we add "(yellow target icon)" after the term "exposed"?

**Comment by Facekast** [comment]
And from my point of view, the Jedi are evil.

**Comment by InterventoR** [comment]
I was waiting for this comment.

**Comment by xauier** [comment]
One more thing, I just discovered.
After taking a standard shot and gaining the HnR Action, it is not possible to activate Run&Gun.

I guess this is intended. But not documented - at least I cannot find it...

**Comment by ChrisTheThinMint** [comment]
It should be documented in the detailed info for Hit and Run, which you can bring up by pressing the small question mark button on the perk.

**Comment by copyrite** [comment]
Personally I'd only say *flanked* (without *exposed*). We can call this done, probably.
