### ISSUE TITLE
Error Occured Exit Code: -1073740940

### ISSUE THREAD

**Issue by DarkFalcon81** [long-war-2/lwotc#924]
Getting this error while trying to cook the dev branch of lwotc, I've read the instructions over and over but just can't figure out what I'm doing wrong. In the log file all it says regarding this error is this: [0000.24] DevDataBase: Connection to "Provider=sqloledb;Data Source=production-db;Initial Catalog=EngineTaskPerf;Trusted_Connection=Yes;Connection Timeout=2" or "10.1.20.20" failed

Any ideas? :(

**Comment by robojumper** [comment]
You may have to change some things in the config file according to https://www.reddit.com/r/xcom2mods/wiki/firsttime :

> Find and open this file:
> `..\steamapps\common\XCOM 2 War of the Chosen SDK\XComGame\Config\XComEditorUserSettings.ini`
> Under [SourceControl], change Disabled=False to True, like this:
> ```
>    [SourceControl]
>    Disabled=True
>
>    [GameAssetDatabase]
>    OfflineMode=true
> ```

**Comment by DarkFalcon81** [comment]
Thank you kindly for your response robo! I changed the Ini settings to that but still nothing. Although the error message I get now is different the error log file seems read the same: 

-1073741819

[0000.26] DevDataBase: Connection to "Provider=sqloledb;Data Source=production-db;Initial Catalog=EngineTaskPerf;Trusted_Connection=Yes;Connection Timeout=2" or "10.1.20.20" failed

**Comment by robojumper** [comment]
That message is normal. Can you get the editor to start at all (ModBuddy->Tools->XCOM 2 Editor)? Once you get that working, post the full log.

**Comment by DarkFalcon81** [comment]
Well, I'm downloading the full version of the SDK right now, is the full version needed btw? It will take 9 hours to download, lol.. So I will get back to you tomorrow with an answer - if the full version is needed - or i guess I could just cancel it and take a look? It's only downloaded 4GB so far, so not to big of a deal to cancel.

**Comment by robojumper** [comment]
The `full_content` branch of the SDK is required. I'll make sure to mention that in the CHL Readme.

**Comment by DarkFalcon81** [comment]
Ah, I see, cool.. I'll get back to you tomorrow with a progress update after this massive download is done! :)

**Comment by DarkFalcon81** [comment]
I downloaded the brand new experimental branch of the dev version and it worked out of the box! Thank you for the help tho Robo! :)
