### ISSUE TITLE
[BUG] Too many bodies are rewarded (BETA2)

### ISSUE THREAD

**Issue by McTrevor79** [long-war-2/lwotc#928]
In my campaign I noticed several times that of some enemy types more bodies were rewarded than actual enemies of that type were present on the mission. DerAVA noticed this too in his playthrough on youtube. In some cases up to 4 bodies were given for a single enemy. Most notably mechs and archons so it might be related to hacking/mind controlling.

**Comment by pledbrook** [comment]
An English-language save with a reproducible example would be much appreciated

**Comment by copyrite** [comment]
The probable cause and resolution are the same as in https://github.com/long-war-2/lwotc/issues/987, and that one is more detailed. Closing this one.
