### ISSUE TITLE
Chosen (Hunter) takes action after each attack (Dev build 14.1)

### ISSUE THREAD

**Issue by xauier** [long-war-2/lwotc#932]
I recently started with dev build 14.1 
Today I just encountered the Hunter Chosen the first time.  

He is taking an action everytime he was attacked (On commanders turn). Either attacking or running.
I hope this is not intended.

But if it is... This means - with a small squad, he could daze everyone on commanders turn... kind of silly :(

**Comment by xauier** [comment]
Addition: He is also able to shoot any solider on the map without the solider having line of sight to any enemy. According to the  wiki, the "Tracking Shot" is supposed to allow this kind of shot...

**Comment by Grobobobo** [comment]
Chosen were drastically changed from dev 8 onwards, read the patch notes. Coincidentally, we'll be reverting a lot of them soon.
