### ISSUE TITLE
Game crashes on mission start

### ISSUE THREAD

**Issue by BenthienDK** [long-war-2/lwotc#936]
Hi
Maybe someone can help me make sense of this,. 
Played for a good long while, and all of a sudden game crashes on mission load, right after the deploy animation.
Tried verifying game via steam.
tried deleting all config files.
tried disabling mods one by one.
tried on other computer.
tried deleting all other saves.
tried reinstalling game from scratch..
If someone could take a quick peak in the log file, and maybe point me in the right direction, I'd sure be grateful.
[XCom-CL374751-2020.04.09-14.31.28_Logfile.log](https://github.com/long-war-2/lwotc/files/4456303/XCom-CL374751-2020.04.09-14.31.28_Logfile.log)
![XCom-CL374751-2020 04 09-14 31 28_Screenshot](https://user-images.githubusercontent.com/63406541/78898642-69ea9e00-7a74-11ea-8f07-4f29b474e505.png)

**Comment by pledbrook** [comment]
Check you have the file *...\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Content\XPACK\Maps\Missions\Sitrep_IntroVO.umap*

**Comment by BenthienDK** [comment]
No, no such file:
E:\spil\SteamLibrary\steamapps\common\XCOM 2>attrib Sitrep_IntroVO.umap /s
File not found - Sitrep_IntroVO.umap

In fact I have no Content dir in ..XComGame\ 
?

**Comment by BenthienDK** [comment]
I do have a Sitrep_IntroVO.upk in my ..XCOM 2\XCom2-WarOfTheChosen\XComGame\CookedPCConsole folder though.

**Comment by pledbrook** [comment]
Yes, sorry, I was going by what I have locally, which is based on having the SDK tools installed.

You have the content file, so I'm guessing that the sit rep is not adding IntroVO to the mission maps. What sit reps were active on this mission?

**Comment by BenthienDK** [comment]
It crashes on all missions no matter what kind, this mission had this sitrep:
![Untitled2](https://user-images.githubusercontent.com/63406541/78987394-26ed0100-7b2e-11ea-8dcc-744a18a082b7.png)
![Untitled](https://user-images.githubusercontent.com/63406541/78987396-28b6c480-7b2e-11ea-8590-50951d3ed3bb.png)

**Comment by BenthienDK** [comment]
Or was it something else you wanted to know?

**Comment by pledbrook** [comment]
If you have a save file, I may be able to take a look.

**Comment by BenthienDK** [comment]
Sure, and thank you :-)
[XCom-CL374751-2020.04.10-13.18.zip](https://github.com/long-war-2/lwotc/files/4491861/XCom-CL374751-2020.04.10-13.18.zip)

**Comment by pledbrook** [comment]
Sorry, I can't use that as it's a non-English save file.

**Comment by BenthienDK** [comment]
Non English? The game is in English, I don't use language packs, I do use a mod giving me different uniforms from different countries, could that be it? Or else I could try to upload the original save, this one was from the dump directory, I don't know if that does a difference?

**Comment by Grobobobo** [comment]
No response since then.
