### ISSUE TITLE
Door not opening when advent pod opens door and reveals squad.

### ISSUE THREAD

**Issue by cicero225** [long-war-2/lwotc#94]
I am hesitant to share this one, as it could very well be a vanilla bug and is rather esoteric, but since I noticed it...

[save_WeirdDoor.zip](https://github.com/long-war-2/lwotc/files/3078286/save_WeirdDoor.zip)
Reproduction steps:
1. Prepare overwatch on the assumption that a pod is about to enter through the door two xcom soldiers are standing next to
>1a. leave the ones next to the door in place and OW
>1b. have everyone else grab cover and OW
>1c. have the guy in the other room that can see a different pod break line of sight to avoid triggering the second pod
2. End turn

What happens:
Advent trooper pod will enter through door, reveal XCom by flank
OW goes off - trooper in front dies (I'm not sure if this is important for the bug)
At the start of turn, rather than being OPEN, as you would expect, the door is closed.

As I said, a bit esoteric. Reproducible, though, since I can reload the turn, do pretty much the same thing, and have it happen again.

**Comment by pledbrook** [comment]
Yup, can reproduce. Units should not be walking through doors without opening them. Could be a vanilla issue. It may depend on who the pod leader is and whether _they_ went through the door.

**Comment by BlackRose39** [comment]
Could be a similar issues to this as well.
https://www.reddit.com/r/Xcom/comments/bipyfy/i_guess_advent_troops_have_limited_psionic_powers/

**Comment by pledbrook** [comment]
I don't think this is down to LWOTC itself, so closing.
