### ISSUE TITLE
geoscape lagging

### ISSUE THREAD

**Issue by gohanf22** [long-war-2/lwotc#944]
the speed of the geoscape is like very very laggy and slow.  is there a way to fix that or make it less laggy?

**Comment by McTrevor79** [comment]
I had the same problem with basic Long War 2. In my case it was the fault of conflicting file overrides through mods. Funnily enough the problematic overrides had nothing to do with geoscape or its ui. You can use alternate mod launcher tipp detect conflicts. Also notice, not every conflict causes this problem. In later had a smooth geoscope with two conflicts left.

**Comment by zyxpsilon** [comment]
I can confirm such conditions **DO** happen when mysterious override(s) occur.
In my specific case -- the **_WC_GeoscApps_** mod was often targeted by players as the likely cause. Wrong... it was simply through a secondary Mod conflict related to HUD control.

Furthermore .. i also use/released a custom external GFX tool called _**SwappIMG**_ (another public mod of mine) to alter many UI elements like colored Class-Icons. This too was cited as guilty for various lagging flaws on the Geoscape and/or elsewhere. It was later proven that anyone's PC system settings (and tricky Overrides) were directly responsible for similar gameplay flaws.

We had to work --very-- hard to create/verify multiple stable Mods & such buggy events were progressively tackled by much more people than just I (TrackTwo, JohnnyLump, RoboJumper, etc).

**Comment by pledbrook** [comment]
This is troubleshooting. If you would like help, try [Reddit](https://www.reddit.com/r/LWotC/) or the #Troubleshooting channel on [our Discord server](https://discord.gg/9fUCvcR).
