### ISSUE TITLE
Suggestion: Naja Defensive AI Improvement

### ISSUE THREAD

**Issue by NilchEi** [long-war-2/lwotc#956]
**Issue:** Naja AI have very little tools to disengage from close-range engagement. 

**Proposed solution:** Naja uses default DoIfFlankedMove which uses AdvanceCover movement profile. This contributes heavily to flanked Naja's current response which is to flail around near the flanking unit instead of opening up distance. 
**Specifics:** Create custom DoIfFlankedSniperMove that calls SniperMove like its all other movement checks.

**Proposed solution:** Naja has 2AP weapon so cannot perform reload-shoot turn. Therefore first AP should prioritize moving ahead of reloading to allow for possibility of move-move turn. Note that AI will use normally use move-reload. Move-move turn will only happen for extreme situations where there's still nearby enemy and/or flanking enemy after first move.
**Specifics:** Switch the order of RandMoveIfEnemyClose and NeedsReload for LWNajaRedFirstActionSelector.

_________________________________

+Behaviors=(BehaviorName=LWNajaRedFirstActionSelector, NodeType=Selector, \\
    Child[0]=DoIfFlankedSniperMove, \\
    Child[1]=TryHighPriorityShot, \\
    Child[2]=RandMoveIfEnemyClose, \\
    Child[3]=NeedsReload, \\
    Child[4]=TrySniperShootOrReload, \\
    Child[5]=MoveIfAnyEnemyWithin12Tiles, \\
    Child[6]=TrySniperShootOrReloadOrOverwatch, \\
    Child[7]=TryMoveThenPoisonSpit, \\
    Child[8]=SniperMove, \\
    Child[9]=HuntEnemyWithCover)

+Behaviors=(BehaviorName=LWNajaRedLastActionSelector, NodeType=Selector, \\
    Child[0]=TryHighPriorityShot, \\
    Child[1]=DoIfFlankedSniperMove, \\
    Child[2]=MoveIfAnyEnemyWithin12Tiles, \\
    Child[3]=TrySniperShootOrReloadOrOverwatch, \\
    Child[4]=TryPoisonSpitSingle, \\
    Child[5]=SniperMove, \\
    Child[6]=HuntEnemyWithCover)

+Behaviors=(BehaviorName=DoIfFlankedSniperMove, NodeType=Sequence, Child[0]=CheckIfNeedToMove, Child[1]=SniperMove)

_________________________________

These proposal have advantage of only affecting Naja's retreat behaviour. I do not touch order of actions at all other than reloading and moving, so Naja's offensive AI are identical to the original.

THIS PROPOSAL IS NOT YET TESTED IN-GAME

**Comment by Grobobobo** [comment]
Another thing I wanted to consider is changing naja's scamper movement profile to be extremely defensive.

**Comment by NilchEi** [comment]
I guess one immediate improvement that could be done is to add 

CharTemplate.strScamperBT = "ScamperRoot_Soldier";

to Naja's template on **X2Character_AlienPack.uc**. ScamperRoot_Soldier checks for defensive move before standard move; advantage of using it is that ScamperRoot_Soldier is already available scamper pattern in original game, and therefore unlikely to cause any problems.

Seems like it wouldn't be too hard to set up custom behaviour with even more defensive scamper movement on XComAI.ini, just like how LW2 team override GenericScamperRoot there.

**Comment by Grobobobo** [comment]
Already implemented (or rejected? don't remember). Already done either way.
