### ISSUE TITLE
Controller - can't call skyranger

### ISSUE THREAD

**Issue by dadjumper** [long-war-2/lwotc#962]
Vanilla WOTC allows you to do this with R3 on a controller. I know that LW2 (and LWOTC) changes the evac system, so I guess this functionality was removed? Any chance of getting this re-bound to R3 for controllers?

**Comment by kdm2k6** [comment]
Can't get the Highlander to build; however, I think I know the general problem with your code.

When I use a controller the Call Skyranger button isn't appearing thus I think :
XComTacticalInput --> Stick_R3() never gets past the SkyrangerButton.bIsVisible check at the top of the function.

UITacticalHUD --> UpdateSkyrangerButton(), I believe, is where the SkyrangerButton is shown or hidden. It might not like the check : AbilityTemplate.DataName == 'PlaceEvacZone'; although I don't know why it would work for mouse & keyboard, but not controller.

**Comment by pledbrook** [comment]
Thanks for investigating. I don't think there's an issue in `UITacticalHUD_AbilityContainer`, but that hard-coded reference to 'PlaceEvacZone' in `UITacticalHUD` looks like the problem, since that's where the visibility of the button is set. :sigh:

I'll have to make further changes to the highlander.

**Comment by RedDoby** [comment]
There are two functions `function bool Stick_R3` in `XComTacticalInput.uc` which set the binding for the R3 button.

**Comment by pledbrook** [comment]
I think this was made available in an earlier release. If not, it will definitely be in dev build 20 and beta 4.
