### ISSUE TITLE
caster gauntlet attacking motion totally broken

### ISSUE THREAD

**Issue by abcd7655** [long-war-2/lwotc#964]
everything is coreect, but that motion is totally broken to standardshot motion. I installed lwotc highlander and required mods.

**Comment by pledbrook** [comment]
Have you cleared your configs? Are you subscribed to any other mods? No one else has reported this, so I'm guessing that this issue is local to your system.

**Comment by copyrite** [comment]
No longer relevant as caster gauntlets no longer exist.
