### ISSUE TITLE
Translation (FRA) - Issues, Questions & Solution

### ISSUE THREAD

**Issue by Savancosinus** [long-war-2/lwotc#966]
Hi there!
Several translations were missing in the "XcomGame.fra" files, so I decided to add them.
Folders:
- LongWarOfTheChosen (main)
- LW_FactionBalance
- NewPromotionScreenByDefault_Integrated & DetailedSoldierListWOTC_Integrated

The files are almost ready, but I have few questions before sending it. It was difficult for me to translate the following abilities, because I never played LWotC.
Someone could help me to understand those ones?

`[DetonateMindshield X2AbilityTemplate]
LocFriendlyName="Overwhelm Mindshield"
LocHelpText="Powers through a Mindshield."
LocLongDescription="Powers through a Mindshield."
LocFlyOverText="Overwhelm Mindshield"`
&
`[Primary_Daze_Passive X2AbilityTemplate]
LocFriendlyName="Primary Daze"
LocHelpText="Your primary attacks daze."
LocLongDescription="Your primary attacks daze."`
&
`[Secondary_Daze_Passive X2AbilityTemplate]
LocFriendlyName="Secondary Daze"
LocHelpText="Your Secondary attacks Heavy daze."
LocLongDescription="Your Secondary attacks Heavy daze."`

And just want to be sure... 
`[Reckoning_LW X2AbilityTemplate]
LocFriendlyName="Reckoning"
LocLongDescription="Unlocks the <Ability:SecondaryWeaponName/> Charge and Slash attack."`

If I understand this ability correctly, "Charge attack" = "SkirmisherFleche" ability?

Thx.

**Comment by pledbrook** [comment]
1. Detonate Mindshield is a Warlock ability that allows him to apply heavy daze to XCOM units that have a Mind shield (who would otherwise be immune). This ability has been disabled in the game, so it's not critical that's it translated right now.

2. The Daze passives simply allow the Chosen to apply Daze and Heavy Daze with their normal weapon attacks. Again, I believe this has been disabled for beta 3 and probably won't be returning. So these can be safely ignored.

3. Yes, Charge attack is the SkirmisherFleche ability

**Comment by pledbrook** [comment]
Also, please come up with an alternative name for the Grenadier abilty branch currently called "Baby-boom" 😆

**Comment by Savancosinus** [comment]
:D
OK. But only if you promise to choose ability names that could be translated easily. No more "Yoink" for example. ;)

Also, I think there's a mistake in the "XcomGame.int".
`[Bullpup_CG X2WeaponTemplate]
FriendlyName="Kal-69 \"Bullpup\""
BriefSummary="We can manufacture a modified Laser SMG That can be used by Skirmishers"`
Should be "coilgun", right?

**Comment by pledbrook** [comment]
I take no responsibility for "yoink" :smile: Note that it isn't player visible, so doesn't need translation. And yes, that should be "coilgun" not "Laser". Thanks for catching that.

**Comment by Savancosinus** [comment]
Daily meeting!
I finished all the files, except the "LW_Overhaul.fra".

"Yoink" -> "Transposition" (Dragonball style, \o/).
"Baby-boom" -> "Pyrotechnicien" or "Expert pyrotechnique" (pyrotechnic expert / pyrotechnist in english).
"Heavy daze" -> "Hébété" (which is funny, because "Hébété" could be translated as "Daze" in english... The basic daze effect has been translated as "Sonné" in french).

1 - You have a conflict between "Danger zone" (Templar) and "Danger zone" (Gunner). Maybe something like "High voltage" ("Haute tension")?

2 - A template is present in "XcomGame.fra" but doesn't appear in the "XcomGame.int" file (LWotC). I think I could delete it, but I want to be sure.
`[XComGame.ThreatAssessment X2AbilityTemplate]
[ThreatAssessment X2AbilityTemplate]`

3 - If I changed the english files, could I do it on the same branch, or should I checkout a new branch?

**Comment by pledbrook** [comment]
1. It's not really a conflict since only a Templar can have their variant of Danger Zone. I kept the name since LW2 folks will know what it does. I can sort of see "High Voltage" working, but I imagine some folks thinking that implies greater damage. Eh. The more I think about it, the more I like High Voltage. Feel free to change that.

2. That translation should be in Localization\LW_PerkPack_Integrated\XComGame.int

3. I'm not sure. It's irrelevant now as Heavy Daze isn't a thing. I would just ignore it.

4. You should make changes in a fork. See [this page](https://github.com/long-war-2/lwotc/wiki/Contributing#first-steps) for info.

**Comment by ChrisTheThinMint** [comment]
> Also, I think there's a mistake in the "XcomGame.int".
> `[Bullpup_CG X2WeaponTemplate] FriendlyName="Kal-69 \"Bullpup\"" BriefSummary="We can manufacture a modified Laser SMG That can be used by Skirmishers"`
> Should be "coilgun", right?
For Bullpups and Vektor Rifles, note that there is new localization for those in the master branch and Beta 3 (I made a PR for that a while ago). This line isnt up-to-date anymore.

**Comment by Savancosinus** [comment]
Arf, I thought Cmder -> git clone/add/commit/push will be sufficient. I'll read that asap. :/

> This line isnt up-to-date anymore.
Thx!

**Comment by Savancosinus** [comment]
Pull request done.
> I can sort of see "High Voltage" working, but I imagine some folks thinking that implies greater damage. Eh. The more I think about it, the more I like High Voltage. Feel free to change that.

I agree. But I also hope that payers read the description before spending AP into an ability. ;)

Don't think I can help for source code, but if you need it, I'll update french translation if you create new contents. :)

And congratulations for your work. Really cool that you keep LW alive, XCOM2 is one of my favorite game, and I can't play with the vanilla version anymore.

**Comment by Savancosinus** [comment]
Hi,
I almost finish to add the new translations (Apotheosis, etc.), + update of the main file ("XcomGrame.fra")... And I have sevral questions.
- The Mobility boost of the Bullpups doesn't display properly in french (english only), but I can't find which line I've to change. Any idea? Surprinsigly, the boost of the SMG appears correctly. :/
- Apotheosis: "for each point of focus above 2" is missing for the dodge's part. Intended?
- SkirmisherVengeance/Justice/Whiplash don't end the turn. Can I add "Cost 1 action but doesn't end Skirmisher's turn" to their description?

**Comment by Grobobobo** [comment]
Those changes were already commited.
