### ISSUE TITLE
Avatar project is busted

### ISSUE THREAD

**Issue by nwngdngl** [long-war-2/lwotc#970]
LWotC is practically my first experience with LW2, I played LW2 way back when for maybe 10-15 hours or so. And so I did not figure out the region liberation mechanic until like 80 hours into my current LWotC campaign where I grinded for my guys to be op af and I contacted all the regions.

so I liberate the region... and the 25 days timer appears (playing on medium difficulty) so I infiltrate the blacksite and nothing happens! I do the forge mission and nothing happens also! the meter won't go down! I'm really sad about it, I don't want to start over, but now I'm stuck with a day and a half left till the game ends, the removeFortressDoom command does nothing and idk what to do...

**Comment by Grobobobo** [comment]
Working as intended.
