### ISSUE TITLE
World map freeze after first temporarily defeating Warlock

### ISSUE THREAD

**Issue by fear2** [long-war-2/lwotc#972]
After I finished a standard mission with the warlock appearing, I go check the world map but the game instantly drags me to what I assume is the chosen icon and the area he's staying. But nothing happens and the game seemingly softlocks with the clock still ticking but nothing happening at all and no input allowed for me, could someone please help me?
This is how it looks like 
![Untitled](https://user-images.githubusercontent.com/64721255/80899317-343c7c00-8ce5-11ea-9f0f-d517010105a5.png)

This is the save
[save_Save 43.zip](https://github.com/long-war-2/lwotc/files/4569669/save_Save.43.zip)

Using just the required mods for Lwotc
I've been searching all over the place for a fix to this issue, found some people with it but no solution thus far. Could someone please help me ?

This is what the last few lines of the

 log looks like 
![Untitled2](https://user-images.githubusercontent.com/64721255/80899356-a3b26b80-8ce5-11ea-8753-2e163793cb43.png)

**Comment by pledbrook** [comment]
You probably had the Lost and Abandoned option ticked when starting the campaign, or when it asked you whether you really wanted to start without the tutorial, you enabled it by accident. Unfortunately, there's no way to recover the campaign when this happens. Sorry.

**Comment by copyrite** [comment]
Nothing to add to Peter's assessment, closing.
