### ISSUE TITLE
Many mods not loading despite being enabled and present in mod config menu, including required ones

### ISSUE THREAD

**Issue by mgoldstein322** [long-war-2/lwotc#980]
I've made sure that all of my mods are on the compatible list, but many of them, including robojumper's Squad Selection Screen are not working in-game with LWOTC.

I'm using the alternative mod launcher and running the newest version of LWOTC; everything else is maintained by the steam workshop and is at its most recent version.

My mods in the order they load:

1. X2WOTCCommunityHighlander
2. Long War of the Chosen
3. Improved Camera Updated WotC
4. WotC: robojumper's Squad Select
5. Restored Sitreps
6. Covert Action Missions
7. Capnbubs Accessories - WotC
8. [WOTC] Peek From Concealment
9. WotC Katana Pack Reloaded
10. WotC: Color Coded Bonds
11. [WotC] Gotcha Again
12. Custom Solders Evac Zone Fix
13. [WOTC] Cinematic Rapid Fire (and other abilities)
14. Metal Over Flesh Redux
15. Skirmisher Cape
16. Evac All - WotC
17. WotC Mod Everything Reloaded
18. Free the Hood - WotC
19. [WOTC] Advent Flashlights
20. [WOTC] Resistance Firearms - Assets
21. [WOTC] Resistance Firearms - Main Module
22. Additional Mission Types Redux
23. Unrestricted Customization - Wotc
24. [WOTC] Additional Icons
25. [WOTC] Revert Overwatch Rules Change
26. Better Second Wave Mod Support
27. WOTC - Extended Information!
28. [WOTC] Stats on New Promotion Screen
29. Turrets Are Cover [WOTC]
30. [WotC+Classic] TacticalUI KillCounter
31. Yet Another F1
32. New Contries
33. Custom Bandanas - Armor Colours/Pattern
34. Custom Face Paints
35. Stop Wasting My Time - WotC
36. Upgrade Reminder [XCOM2 Vanilla & WotC]
37. Clean Cinematic
38. [WotC] Resistance Firearms - Attachments
39. [WotC] Get A Rifle Grip! - Animation Fix
40. [WotC+Classic] Reliable Smoke
41. [WotC] Mod Config Menu
42. Add part Names
43. Warden Gear[WoTC Friendly Now]
44. New Target Icons
45. Smooth Scrolling

**Comment by copyrite** [comment]
Closing because issue is old, and I'm having a hard time grasping what the problem exactly is.
